// Visual motifs, not new historical or hadith assertions. Every entry is explicit.
// Captions are editorial scene labels; quotations remain in quotes.tsv unchanged.
const scenes={};
function add(ids,type,variant,ru,en,ky){for(const id of ids.split(' '))scenes[id]={type,variant,caption:{ru,en,ky}};}
add('battle','armies','encounter','Аль-Мальхама','Al-Malhama','Аль-Мальхама');
add('constantinople','city','gates','Константинополь','Constantinople','Константинополь');
add('dajjal','trial','contrast','Испытание Даджаля','Trial of the Dajjal','Дажжалдын сыноосу');
add('medina-protected','sanctuary','medina','Медина','Medina','Медина');
add('mecca-protected','sanctuary','pair','Мекка и Медина','Mecca and Medina','Мекке жана Медина');
add('isfahan','people','followers','Последователи из Исфахана','Followers from Isfahan','Исфахандан чыккан жолдоочулар');
add('believer','trial','steadfast','Стойкость верующего','Steadfastness of the believer','Ыймандуунун бекемдиги');
add('isa','minaret','light','Белый минарет к востоку от Дамаска','White minaret east of Damascus','Дамасктын чыгышындагы ак мунара');
add('ludd','city','ludd','Ворота Лудда','Gate of Ludd','Лудддун дарбазасы');
add('yajuj','land','multitude','Выход Яджудж и Маджудж','Emergence of Yajuj and Majuj','Яжуж жана Мажуждун чыгышы');
add('yajuj-end','land','stillness','Гибель Яджудж и Маджудж','Death of Yajuj and Majuj','Яжуж жана Мажуждун өлүмү');
add('peace','land','peace','Мир между людьми','Peace among people','Адамдардын ортосундагы тынчтык');
add('wind','wind','gentle','Ветер','The wind','Шамал');
add('idols','idols','return','Возвращение к поклонению идолам','Return to idol worship','Буттарга сыйынууга кайтуу');
add('hour','sky','hour','Наступление Часа','The coming of the Hour','Кыяматтын келиши');
add('smoke','sky','smoke','Дым','Smoke','Түтүн');
add('beast','emergence','unnamed','Выход Зверя','Emergence of the Beast','Жаныбардын чыгышы');
add('sun','sky','sun','Запад','West','Батыш');
add('east-sinking','earth','east','Восток','East','Чыгыш');
add('west-sinking','earth','west','Запад','West','Батыш');
add('arabia-sinking','earth','arabia','Аравийский полуостров','Arabian Peninsula','Араб жарым аралы');
add('fire-gathering','fire','gathering','Огонь из Йемена','Fire from Yemen','Йеменден чыккан от');
add('bayda','earth','army','Равнина аль-Байда','Plain of al-Bayda','Аль-Байда түздүгү');
add('euphrates','water','gold','Евфрат и гора золота','The Euphrates and a mountain of gold','Евфрат жана алтын тоосу');
add('arabia-green','water','green','Луга и реки','Meadows and rivers','Шалбаалар жана дарыялар');
add('hajj-isa','journey','valley','Долина ар-Рауха','Valley of al-Rawha','Ар-Рауха өрөөнү');
add('hajj-continues','sanctuary','pilgrimage','Хадж и умра','Hajj and umrah','Ажылык жана умра');
add('kaaba','sanctuary','destruction','Кааба','The Kaaba','Кааба');
add('medina-empty','city','empty','Опустевшая Медина','Deserted Medina','Ээн калган Медина');
add('hijaz-fire','fire','hijaz','Хиджаз · Бусра','Hijaz · Busra','Хижаз · Бусра');
add('du-khalasa','idols','khalasa','Зу-ль-Халаса','Dhu al-Khalasa','Зул-Халаса');
add('payments','trade','stopped','Ирак · аш-Шам · Египет','Iraq · al-Sham · Egypt','Ирак · аш-Шам · Мисир');
add('romans','people','many','Ар-Рум','Al-Rum','Ар-Рум');
add('qahtan','authority','staff','Правитель из Кахтана','Ruler from Qahtan','Кахтандык башкаруучу');
add('jahjah','authority','jahjah','Джахджах','Jahjah','Жахжах');
add('caliph','wealth','giving','Раздача богатства','Distribution of wealth','Байлыкты бөлүштүрүү');
add('truce','treaty','broken','Перемирие и его нарушение','Truce and its violation','Келишим жана анын бузулушу');
add('conflict','armies','trees','Сообщение о сражении','Account of a battle','Салгылаш жөнүндө баян');
add('false-prophets','voices','false','Ложные притязания','False claims','Жалган дооматтар');
add('knowledge','knowledge','morals','Уход знания','Loss of knowledge','Билимдин азайышы');
add('women-men','people','fifty','50 женщин · один попечитель','50 women · one caretaker','50 аял · бир камкорчу');
add('trust','balance','trust','Ответственность и доверие','Responsibility and trust','Жоопкерчилик жана аманат');
add('buildings','towers','competition','Пастухи чёрных верблюдов','Shepherds of black camels','Кара төөлөрдүн чабандары');
add('slave','relation','mother','Рабыня и её ребёнок','The enslaved woman and her child','Күң аял жана анын баласы');
add('earthquakes','earth','quakes','Землетрясения','Earthquakes','Жер титирөөлөр');
add('time','time','closer','Сближение времени','Time drawing closer','Убакыттын жакындашы');
add('killing','armies','unrest','Смуты и убийства','Turmoil and killing','Бүлгүн жана киши өлтүрүү');
add('wealth','wealth','abundance','Изобилие имущества','Abundance of wealth','Мал-мүлктүн көбөйүшү');
add('grave','land','grave','Испытания и могила','Trials and the grave','Сыноолор жана мүрзө');
add('rain','water','barren','Дождь без урожая','Rain without crops','Түшүмсүз жаан');
add('harshness','conduct','harshness','Насилие и внешний облик','Violence and appearance','Зомбулук жана сырткы көрүнүш');
add('prohibitions','conduct','prohibitions','Объявление запретного дозволенным','Declaring the forbidden lawful','Арамды адал деп эсептөө');
add('east-fitna','trial','east','Смута с востока','Trial from the east','Чыгыштан чыккан бүлгүн');
add('mission','time','adjacent','Миссия Пророка ﷺ · Час','The Prophet’s mission ﷺ · the Hour','Пайгамбардын миссиясы ﷺ · Кыямат');
add('moon','sky','moon','Раскалывание луны','Splitting of the moon','Айдын жарылышы');
add('death-prophet','memorial','medina','Медина · 632 н. э. / 11 г. х.','Medina · 632 CE / 11 AH','Медина · 632-ж. / 11-х. ж.');
add('jerusalem','city','jerusalem','Байт аль-Макдис','Bayt al-Maqdis','Байт аль-Макдис');
add('plague','people','loss','Массовая смертность','Widespread mortality','Жапырт өлүм');
add('arab-fitna','city','unrest','Каждый арабский дом','Every Arab household','Ар бир араб үйү');
add('hira-safety','journey','safe','Аль-Хира → Кааба','Al-Hira → Kaaba','Аль-Хира → Кааба');
add('kisra','wealth','kisra','Сокровища Кисры','Treasures of Kisra','Кисранын казыналары');
add('barrier','wall','opening','Отверстие в преграде','Opening in the barrier','Тосмодогу тешик');
add('tamim','journey','island','Остров в рассказе Тамима','The island in Tamim’s account','Тамимдин баянындагы арал');
add('baysan','water','palms','Пальмы Байсана','Palms of Baysan','Байсандын курмалары');
add('two-armies','armies','two','Две большие группы','Two large groups','Эки чоң топ');
add('turks','armies','turks','Сообщение о сражениях','Account of battles','Салгылаштар жөнүндө баян');
add('treasures','wealth','earth','Золото и серебро','Gold and silver','Алтын жана күмүш');
add('faith-trial','trial','night','Испытания веры','Trials of faith','Ыймандын сыноолору');
add('earnings','balance','earnings','Происхождение дохода','Sources of income','Кирешенин келип чыгышы');
add('pledges','treaty','pledges','Свидетельства и обеты','Testimonies and vows','Күбөлүктөр жана убадалар');
add('scholars','knowledge','scholars','Уход учёных','Loss of scholars','Аалымдардын кетиши');
add('medina-growth','towers','medina','Расширение застройки Медины','Growth of Medina’s buildings','Мединанын курулуштарынын кеңейиши');
add('medina-fitna','city','rain','Смуты среди домов Медины','Trials among Medina’s houses','Мединанын үйлөрүндөгү бүлгүн');
add('rulers','authority','interests','Собственные интересы правителей','Rulers’ self-interest','Башкаруучулардын жеке кызыкчылыктары');
add('young-rulers','authority','young','Юные правители','Young rulers','Жаш башкаруучулар');
add('hasan','treaty','peace','Примирение двух групп','Reconciliation of two groups','Эки топтун жарашуусу');
add('ammar','memorial','siffin','Сиффин · 657 н. э. / 37 г. х.','Siffin · 657 CE / 37 AH','Сыффин · 657-ж. / 37-х. ж.');
add('conquests','sequence','four','Аравия → Персия → ар-Рум → Даджаль','Arabia → Persia → al-Rum → Dajjal','Аравия → Персия → ар-Рум → Дажжал');
add('mahdi','relation','family','Из семьи Пророка ﷺ, из потомков Фатимы','From the Prophet’s family ﷺ, descendants of Fatima','Пайгамбардын үй-бүлөсүнөн ﷺ, Фатиманын урпактарынан');
add('joint-campaign','armies','alliance','Совместный поход','Joint campaign','Биргелешкен жортуул');
add('truce-breach','treaty','meadow','Луг с холмами · нарушение мира','Meadow with hills · breach of peace','Дөбөлүү шалбаа · тынчтыктын бузулушу');
add('return-sham','journey','return','Константинополь → аш-Шам','Constantinople → al-Sham','Константинополь → аш-Шам');
module.exports=scenes;
