// Original paraphrases; reviewed against the numbered transmissions on 2026-09-18.
module.exports=function enrich(d){
 const L=(ru,en,ky)=>({ru,en,ky});
 const add=(id,refs,title,summary,places=[])=>d.events.push({id:id==='truce'?'joint-campaign':id,group:'expected',refs,places,title,summary});
 add('mahdi',['abudawud:4284'],L('Имам Махди','Imam Mahdi','Имам Махди'),L('Махди будет из семьи Пророка ﷺ, из потомков Фатимы. В этой передаче место появления и присяги не названо.','The Mahdi will belong to the Prophet’s ﷺ family, among Fatimah’s descendants. This transmission does not name his place of emergence or allegiance.','Махди Пайгамбардын ﷺ үй-бүлөсүнөн, Фатиманын урпактарынан болот. Бул риваятта анын чыга турган жана ант бериле турган жери аталбайт.'));
 add('truce',['abudawud:4292'],L('Мир с ар-Рум и совместный поход','Peace with al-Rum and a joint campaign','Ар-Рум менен тынчтык жана биргелешкен жортуул'),L('После мирного соглашения мусульмане и ар-Рум вместе выступят против общего врага и одержат победу. Противник и место похода здесь не названы.','After a peace agreement, Muslims and al-Rum campaign together against an enemy and prevail. This report names neither the enemy nor the campaign’s location.','Тынчтык келишиминен кийин мусулмандар менен ар-Рум жалпы душманга каршы чыгып, жеңишке жетет. Бул баянда душман да, жортуулдун жери да аталбайт.'));
 add('truce-breach',['abudawud:4292'],L('Возвращение и нарушение мира','Return and breach of peace','Кайтуу жана тынчтыктын бузулушу'),L('На обратном пути войско остановится на лугу с холмами. После возгласа о победе креста и его разрушения ар-Рум нарушит договор и соберётся для аль-Мальхамы. Это не названо возвращением из Константинополя; точное место не указано.','On the return, the army stops in a meadow with hills. A claim of victory for the cross and its breaking precede al-Rum’s breach of the treaty and preparation for al-Malhama. The report does not call this a return from Constantinople or identify the meadow.','Кайтар жолдо кошуун дөңсөөлөрү бар шалбаага токтойт. Айкаш жыгач жеңди деген сөздөн жана анын сындырылышынан кийин ар-Рум келишимди бузуп, аль-Мальхамага даярданат. Бул Константинополдон кайтуу деп аталбайт; шалбаанын так жери берилбейт.'));
 add('return-sham',['muslim:2897'],L('Возвращение в аш-Шам','Return to al-Sham','Аш-Шамга кайтуу'),L('После взятия Константинополя войско выходит из города из-за ложного известия. При возвращении в аш-Шам появляется Даджаль. Линия на карте показывает только направление между названными местами.','After taking Constantinople, the army departs following a false report. The Dajjal appears upon their return to al-Sham. The map line shows only a direction between named places.','Константинополь алынгандан кийин жалган кабардан улам кошуун шаардан чыгат. Аш-Шамга кайтып келгенде Дажжал пайда болот. Картадагы сызык аталган жерлердин ортосундагы багытты гана көрсөтөт.'),['constantinople','sham']);
 d.sequences.unshift({id:'truce',title:L('Мир → совместный поход → нарушение договора','Peace → joint campaign → broken treaty','Тынчтык → биргелешкен жортуул → келишимдин бузулушу'),refs:['abudawud:4292'],ids:['joint-campaign','truce-breach']});
 d.sequences.find(s=>s.id==='sham').ids.splice(2,0,'return-sham');
 d.sequences.find(s=>s.id==='sham').refs.push('muslim:2937a');
 d.places.constantinople.name=L('Константинополь · ныне Стамбул','Constantinople · present-day Istanbul','Константинополь · азыркы Стамбул');
 d.events.find(e=>e.id==='constantinople').places=['dabiq','amaq','constantinople'];
 for(const e of d.events){e.grade=e.refs.every(r=>/^(bukhari|muslim):/.test(r))?L('Сахих · аль-Бухари / Муслим','Sahih · al-Bukhari / Muslim','Сахих · аль-Бухари / Муслим'):L('Сахих · оценка аль-Альбани','Sahih · graded by al-Albani','Сахих · аль-Альбанинин баасы');}
 d.routes={battle:['medina','dabiq'],constantinople:['dabiq','constantinople'],'return-sham':['constantinople','sham']};
 d.review=[
 {title:L('Чёрные знамёна из Хорасана','Black banners from Khurasan','Хорасандан чыккан кара туулар'),text:L('Ат-Тирмизи, 2269: Хорасан и Илия (Иерусалим); оценка Darussalam — даиф. Ибн Маджа, 4084: восток и Махди; оценка Darussalam — даиф. Эти передачи не включены в достоверную последовательность и не задают маршрут на карте.','Al-Tirmidhi 2269 names Khurasan and Iliya (Jerusalem); Darussalam grades it daif. Ibn Majah 4084 mentions the east and the Mahdi; Darussalam grades it daif. These reports are not included in the authenticated sequence or used to plot a route.','Ат-Тирмизи, 2269: Хорасан жана Илия (Иерусалим); Darussalam баасы — даиф. Ибн Маджа, 4084: чыгыш жана Махди; Darussalam баасы — даиф. Бул баяндар сахих ыраатка киргизилбейт жана картадагы жолго негиз болбойт.')},
 {title:L('Присяга Махди в Мекке','Allegiance to the Mahdi in Mecca','Меккеде Махдиге ант берүү'),text:L('Абу Дауд, 4286 описывает присягу между Углом Каабы и Макамом; аль-Альбани оценивает эту передачу как даиф. Достоверное сообщение о Махди в Абу Дауде, 4284 не подтверждает все подробности этой передачи. Поэтому место присяги не показано как установленное будущее событие.','Abu Dawud 4286 describes allegiance between the Corner of the Kaaba and the Maqam; al-Albani grades this transmission daif. The sahih report in Abu Dawud 4284 does not authenticate every detail of this account. The allegiance site is therefore not plotted as an established future event.','Абу Дауд, 4286 Каабанын бурчу менен Макамдын ортосундагы антты баяндайт; аль-Альбани бул риваятты даиф деп баалайт. Абу Дауд, 4284төгү сахих баян анын бардык деталдарын ырастабайт. Ошондуктан ант берилчү жер аныкталган болочок окуя катары белгиленбейт.')}
 ];
 d.version=2;return d;
};
