// Date intervals are half-open [from, to). Rounded transitions are labelled approximate.
// Map coordinates identify a named site or a representative point within a named region,
// never a reconstructed border. Source URLs are for the editorial record, not UI links.
const L=(ru,en,ky)=>[ru,en,ky];
const P=(from,to,period,title,text,sources,coord)=>({from,to,period,title,text,sources,...(coord?{coord}:{})});
const sources={
 mesa:{title:'National Park Service. An Introduction to Mesa Verde; Places; Mesa Verde National Park — A National and Worldwide Treasure.',urls:['https://www.nps.gov/meve/learn/education/introduction-to-mesa-verde.htm','https://home.nps.gov/meve/learn/historyculture/places.htm','https://www.nps.gov/meve/learn/management/worldheritage_meve.htm']},
 chaco:{title:'National Park Service. Chaco Culture: History & Culture; Chaco Canyon and the Antiquities Act.',urls:['https://home.nps.gov/chcu/learn/historyculture/index.htm','https://home.nps.gov/articles/000/chaco-canyon-and-the-antiquities-act.htm']},
 cahokia:{title:'UNESCO. Cahokia Mounds State Historic Site. National Park Service. Midwest Region’s Only World Heritage Site… and a Promise of More to Come.',urls:['https://whc.unesco.org/en/list/198/','https://www.nps.gov/articles/midwest-region-s-only-world-heritage-site-and-a-promise-of-more-to-come.htm']},
 tikal:{title:'UNESCO. Tikal National Park.',urls:['https://whc.unesco.org/en/list/64/']},
 chichen:{title:'INAH. Zona Arqueológica de Chichén Itzá. UNESCO. Pre-Hispanic City of Chichen-Itza.',urls:['https://www.inah.gob.mx/zonas/146-zona-arqueologica-de-chichen-itza','https://whc.unesco.org/en/list/483/']},
 mayapan:{title:'INAH. Zona Arqueológica de Mayapán.',urls:['https://www.inah.gob.mx/zonas/zona-arqueologica-de-mayapan']},
 tula:{title:'INAH. Zona Arqueológica y Museo de sitio de Tula; Examining Tula’s Complex Urban Layout.',urls:['https://www.inah.gob.mx/zonas/zona-arqueologica-y-museo-de-sitio-de-tula','https://lugares.inah.gob.mx/en/node/5542']},
 wari:{title:'Louise Deglin. Wari Imperial Art; Tunic (Wari artist, 650–1000 CE). The Metropolitan Museum of Art.',urls:['https://www.metmuseum.org/essays/wari-imperial-art','https://www.metmuseum.org/art/collection/search/675980']},
 moche:{title:'The Metropolitan Museum of Art. Architectural Models from the Ancient Americas; Rain of the Moon.',urls:['https://www.metmuseum.org/de/essays/architectural-models-from-the-ancient-americas','https://www.metmuseum.org/exhibitions/listings/2000/peruvian-silver']},
 tiwanaku:{title:'UNESCO. Tiwanaku: Spiritual and Political Centre of the Tiwanaku Culture.',urls:['https://whc.unesco.org/en/list/567/']},
 andes:{title:'The Metropolitan Museum of Art. Heilbrunn Timeline of Art History: Central and Southern Andes, 1000–1400 A.D.',urls:['https://82nd-and-fifth.metmuseum.org/toah/ht/07/sac.html']},
 sican:{title:'The Metropolitan Museum of Art. Funerary mask, Lambayeque (Sicán), 900–1100 CE.',urls:['https://www.metmuseum.org/art/collection/search/309959']},
 chimu:{title:'UNESCO. Chan Chan Archaeological Zone.',urls:['https://whc.unesco.org/en/list/366/']},
 marajo:{title:'Júlia Morim. Museu do Marajó (Ilha do Marajó, PA). Fundação Joaquim Nabuco. Museu Goeldi e IPHAN catalogam quatro sítios arqueológicos no município de Anajás.',urls:['https://pesquisaescolar.fundaj.gov.br/pt-br/artigo/museu-do-marajo/','https://www.gov.br/museugoeldi/pt-br/arquivos/noticias/museu-goeldi-e-iphan-catalogam-quatro-sitios-arqueologicos-no-municipio-de-anajas']},
 dongola:{title:'Włodzimierz Godlewski, Dorota Dzierzbicka, Adam Łajtar (eds.). Dongola 2015–2016: Fieldwork, Conservation and Site Management. PCMA Excavation Series 5, 2018. PCMA: Dongola.',urls:['https://pcma.uw.edu.pl/2018/09/05/dongola-2015-2016/','https://pcma.uw.edu.pl/en/2019/04/02/dongola-2/']},
 sahel:{title:'The Metropolitan Museum of Art. The Empires of the Western Sudan; The Trans-Saharan Gold Trade (7th–14th Century).',urls:['https://www.metmuseum.org/essays/the-empires-of-the-western-sudan','https://www.metmuseum.org/essays/the-trans-saharan-gold-trade-7th-14th-century']},
 mali:{title:'The Metropolitan Museum of Art. Sahel: Art and Empires on the Shores of the Sahara — Inside the Exhibition.',urls:['https://www.metmuseum.org/es/exhibitions/sahel-art-empire-sahara/inside-the-exhibition']},
 kilwa:{title:'UNESCO. Ruins of Kilwa Kisiwani and Ruins of Songo Mnara.',urls:['https://whc.unesco.org/en/list/144/']},
 mapungubwe:{title:'UNESCO. Mapungubwe Cultural Landscape; ICOMOS evaluation (2003).',urls:['https://whc.unesco.org/en/list/1099/','https://whc.unesco.org/document/1440']},
 zimbabwe:{title:'UNESCO. Great Zimbabwe National Monument.',urls:['https://whc.unesco.org/en/list/364/']},
 lalibela:{title:'UNESCO. Rock-Hewn Churches, Lalibela.',urls:['https://whc.unesco.org/en/list/18/']},
 budj:{title:'UNESCO. Budj Bim Cultural Landscape. Gunditjmara Aquaculture System: World Heritage nomination.',urls:['https://whc.unesco.org/en/list/1577/','https://whc.unesco.org/document/166283']},
 kakadu:{title:'UNESCO. Kakadu National Park.',urls:['https://whc.unesco.org/en/list/147/']}
};
const regions=[
 {id:'north',name:L('Северная Америка','North America','Түндүк Америка'),scope:L('Включая Мезоамерику','Including Mesoamerica','Мезоамериканы кошкондо'),view:[-99,29,2.5],color:'#855330'},
 {id:'south',name:L('Южная Америка','South America','Түштүк Америка'),scope:L('Анды и Амазония','Andes and Amazonia','Анд тоолору жана Амазония'),view:[-66,-16,2.25],color:'#45644a'},
 {id:'africa',name:L('Африка','Africa','Африка'),scope:L('Сахель, Нил, восток и юг','Sahel, Nile, east and south','Сахель, Нил, чыгыш жана түштүк'),view:[20,-3,1.85],color:'#86582f'},
 {id:'australia',name:L('Австралия','Australia','Австралия'),scope:L('Культурные ландшафты','Cultural landscapes','Маданий ландшафттар'),view:[133,-26,2.7],color:'#735747'}
];
const entries=[
 {id:'mesa',region:'north',kind:'community',coord:[-108.49,37.18],name:L('Меса-Верде · предки пуэбло','Mesa Verde · Ancestral Pueblo','Меса-Верде · пуэблолордун ата-бабалары'),phases:[
 P(550,750,L('ок. 550–750','c. 550–750','болж. 550–750'),L('Поселения на плато','Mesa-top communities','Бөксө тоодогу конуштар'),L('Земледельческие общины живут в полуземлянках на плато. Выращивание кукурузы и хранение запасов поддерживают оседлую жизнь.','Farming communities live in pithouses on the mesa tops. Maize cultivation and stored harvests support settled life.','Дыйкан жамааттары бөксө тоодогу жарым жер төлө үйлөрдө жашайт. Жүгөрү өстүрүү жана азык сактоо отурукташкан жашоону камсыз кылат.'),['mesa']),
 P(750,1180,L('ок. 750–1180','c. 750–1180','болж. 750–1180'),L('Надземные селения','Above-ground villages','Жер үстүндөгү айылдар'),L('Распространяются многокомнатные надземные дома. Поселения связаны земледелием, ремеслом и обменом; знаменитые скальные комплексы относятся к более позднему этапу.','Multiroom houses spread above ground. Farming, crafts and exchange connect villages; the famous cliff complexes belong to a later phase.','Көп бөлмөлүү жер үстүндөгү үйлөр тарайт. Айылдарды дыйканчылык, кол өнөрчүлүк жана соода байланыштырат; белгилүү аска конуштары кийинки мезгилге таандык.'),['mesa']),
 P(1180,1300,L('ок. 1180–1300','c. 1180–1300','болж. 1180–1300'),L('Скальные селения и переселение','Cliff villages and migration','Аска конуштары жана көчүү'),L('Под скальными навесами строят каменные селения. В конце XIII века жители переселяются южнее; их потомки продолжают историю народов пуэбло.','Stone villages occupy cliff alcoves. In the late thirteenth century people migrate south; their descendants continue the history of the Pueblo peoples.','Аска үңкүрлөрүнө таш конуштар курулат. XIII кылымдын аягында тургундар түштүккө көчөт; алардын урпактары пуэбло элдеринин тарыхын улантат.'),['mesa'])]},
 {id:'chaco',region:'north',kind:'city',coord:[-107.96,36.06],name:L('Чако','Chaco','Чако'),phases:[
 P(850,1050,L('ок. 850–1050','c. 850–1050','болж. 850–1050'),L('Строительство больших домов','Building great houses','Чоң үйлөрдүн курулушу'),L('В каньоне Чако растут крупные каменные комплексы предков пуэбло. Поселения становятся центрами церемоний и обмена.','Large Ancestral Pueblo stone complexes grow in Chaco Canyon. Settlements become centres for ceremonies and exchange.','Чако капчыгайында пуэблолордун ата-бабаларынын чоң таш комплекстери өсөт. Конуштар жөрөлгөлөрдүн жана сооданын борборлоруна айланат.'),['chaco']),
 P(1050,1250,L('ок. 1050–1250','c. 1050–1250','болж. 1050–1250'),L('Региональный центр','Regional centre','Аймактык борбор'),L('Чако объединяет церемониальные, хозяйственные и административные связи бассейна Сан-Хуан. Позднее значение центра уменьшается, а связанные общины развиваются в других местах.','Chaco anchors ceremonial, economic and administrative networks in the San Juan Basin. Its central role later diminishes as related communities develop elsewhere.','Чако Сан-Хуан алабындагы жөрөлгөлүк, чарбалык жана башкаруу байланыштарын бириктирет. Кийин борбордун мааниси азайып, ага байланышкан жамааттар башка жерлерде өнүгөт.'),['chaco'])]},
 {id:'cahokia',region:'north',kind:'city',coord:[-90.06,38.66],name:L('Кахокия','Cahokia','Кахокия'),phases:[
 P(800,1050,L('ок. 800–1050','c. 800–1050','болж. 800–1050'),L('Миссисипская культура','Mississippian culture','Миссисипи маданияты'),L('В долине Миссисипи складывается земледельческий центр с земляными насыпями. Кахокия входит в сеть поселений и обмена.','An agricultural centre with earthen mounds develops in the Mississippi Valley. Cahokia belongs to a network of settlements and exchange.','Миссисипи өрөөнүндө топурак дөбөлөрү бар дыйканчылык борбору калыптанат. Кахокия конуштар жана соода тармагына кирет.'),['cahokia']),
 P(1050,1400,L('ок. 1050–1400','c. 1050–1400','болж. 1050–1400'),L('Большой центр на Миссисипи','Major Mississippi centre','Миссисипидеги чоң борбор'),L('Монументальные насыпи, площади и жилые кварталы образуют крупный центр. Наибольшая численность населения приходится примерно на 1050–1150 годы; позднее город сокращается.','Monumental mounds, plazas and neighbourhoods form a major centre. Population peaks around 1050–1150; the city contracts later.','Монументалдуу дөбөлөр, аянттар жана турак жайлар чоң борборду түзөт. Калк болжол менен 1050–1150-жылдары эң көп болуп, кийин шаар кичирейет.'),['cahokia'])]},
 {id:'tikal',region:'north',kind:'city',coord:[-89.62,17.22],name:L('Тикаль · города майя','Tikal · Maya cities','Тикаль · майя шаарлары'),phases:[
 P(250,900,L('ок. 250–900','c. 250–900','болж. 250–900'),L('Классический период майя','Classic Maya period','Майялардын классикалык доору'),L('Тикаль — один из крупных городов майя, с храмами, дворцами и надписями. Города имеют собственные династии; общего государства всех майя нет. К концу IX века Тикаль теряет прежнее значение.','Tikal is a major Maya city with temples, palaces and inscriptions. Cities have their own dynasties, rather than one state ruling all Maya peoples. Tikal loses its former importance by the end of the ninth century.','Тикаль — ибадатканалары, сарайлары жана жазуулары бар ири майя шаары. Шаарлардын өз династиялары бар; бардык майяларды бириктирген мамлекет жок. IX кылымдын аягында Тикалдын мурдагы мааниси төмөндөйт.'),['tikal'])]},
 {id:'chichen',region:'north',kind:'city',coord:[-88.57,20.68],name:L('Чичен-Ица','Chichen Itza','Чичен-Ица'),phases:[
 P(525,900,L('ок. 525–900','c. 525–900','болж. 525–900'),L('Город северного Юкатана','Northern Yucatán city','Түндүк Юкатандагы шаар'),L('Город развивается рядом с сенотами — естественными источниками воды. Ранняя застройка принадлежит архитектурной традиции майя.','The city develops beside cenotes, natural water sources. Early buildings belong to the Maya architectural tradition.','Шаар сеноттордун — табигый суу булактарынын жанында өнүгөт. Алгачкы курулуштар майялардын архитектуралык салтына таандык.'),['chichen']),
 P(900,1200,L('ок. 900–1200','c. 900–1200','болж. 900–1200'),L('Крупный центр Юкатана','Major Yucatán centre','Юкатандын ири борбору'),L('Чичен-Ица становится одним из важнейших центров Юкатана. Архитектура сочетает местные традиции с влияниями Центральной Мексики.','Chichen Itza becomes one of Yucatán’s leading centres. Its architecture combines local traditions with influences from central Mexico.','Чичен-Ица Юкатандын эң маанилүү борборлорунун бирине айланат. Архитектурасы жергиликтүү салттарды Борбордук Мексиканын таасири менен айкалыштырат.'),['chichen'])]},
 {id:'mayapan',region:'north',kind:'city',coord:[-89.46,20.63],name:L('Майяпан','Mayapan','Майяпан'),phases:[
 P(1200,1450,L('ок. 1200–1450','c. 1200–1450','болж. 1200–1450'),L('Поздний политический центр майя','Later Maya political centre','Майялардын кийинки саясий борбору'),L('Майяпан — укреплённый город и важный политический центр позднего постклассического Юкатана. История майя продолжается после упадка южных городов классической эпохи.','Mayapan is a walled city and an important political centre of Late Postclassic Yucatán. Maya history continues after the decline of the southern Classic-period cities.','Майяпан — дубал менен курчалган шаар жана кийинки постклассикалык Юкатандын маанилүү саясий борбору. Түштүктөгү классикалык шаарлардын начарлашынан кийин да майялардын тарыхы уланат.'),['mayapan'])]},
 {id:'tula',region:'north',kind:'city',coord:[-99.34,20.06],name:L('Тула · тольтеки','Tula · Toltecs','Тула · тольтектер'),phases:[
 P(900,1150,L('ок. 900–1150','c. 900–1150','болж. 900–1150'),L('Расцвет Тулы','Tula at its height','Туланын гүлдөшү'),L('Тула становится крупным городом Центральной Мексики. Торговля и политическое влияние связывают её с другими областями Мезоамерики. Середина XII века отмечает конец её гегемонии.','Tula becomes a major city in central Mexico. Trade and political influence connect it with other parts of Mesoamerica. Its hegemony ends around the mid-twelfth century.','Тула Борбордук Мексиканын ири шаарына айланат. Соода жана саясий таасир аны Мезоамериканын башка аймактары менен байланыштырат. Анын үстөмдүгү XII кылымдын орто ченинде аяктайт.'),['tula'])]},
 {id:'moche',region:'south',kind:'culture',coord:[-79.01,-8.14],name:L('Моче · северное побережье Перу','Moche · northern coast of Peru','Моче · Перунун түндүк жээги'),phases:[
 P(100,800,L('ок. 100–800','c. 100–800','болж. 100–800'),L('Прибрежные центры моче','Moche coastal centres','Моченин жээктеги борборлору'),L('Центры моче известны монументальными глинобитными сооружениями, расписной керамикой и обработкой металлов. На карте отмечен комплекс Уака-дель-Соль и Уака-де-ла-Луна в долине Моче.','Moche centres are known for monumental adobe buildings, painted ceramics and metalwork. The map marks the Huaca del Sol and Huaca de la Luna complex in the Moche Valley.','Моче борборлору чоң чопо курулуштары, сүрөттүү керамикасы жана металл иштетүүсү менен белгилүү. Картада Моче өрөөнүндөгү Уака-дель-Соль жана Уака-де-ла-Луна комплекси көрсөтүлгөн.'),['moche'])]},
 {id:'wari',region:'south',kind:'city',coord:[-74.19,-13.06],name:L('Уари','Wari','Уари'),phases:[
 P(600,1000,L('ок. 600–1000','c. 600–1000','болж. 600–1000'),L('Государство Анд','Andean state','Анд тоолорундагы мамлекет'),L('Уари управляет сетью центров в горах и на побережье современного Перу. Дороги, ремесло и административные поселения связывают разные области; центр расположен близ нынешнего Аякучо.','Wari governs a network of centres in the highlands and coast of present-day Peru. Roads, crafts and administrative settlements link different regions; its centre lies near modern Ayacucho.','Уари азыркы Перунун тоолорундагы жана жээгиндеги борборлор тармагын башкарат. Жолдор, кол өнөрчүлүк жана башкаруу конуштары аймактарды байланыштырат; борбору азыркы Аякучого жакын жайгашкан.'),['wari'])]},
 {id:'tiwanaku',region:'south',kind:'city',coord:[-68.67,-16.55],name:L('Тиуанако','Tiwanaku','Тиуанако'),phases:[
 P(500,1000,L('ок. 500–1000','c. 500–1000','болж. 500–1000'),L('Центр у озера Титикака','Centre near Lake Titicaca','Титикака көлүнүн жанындагы борбор'),L('Тиуанако — политический и ритуальный центр высокогорных Анд. Монументальная каменная архитектура и ремесленные традиции отражают его широкие связи; расцвет относят к 500–900 годам.','Tiwanaku is a political and ritual centre in the Andean highlands. Monumental stone architecture and craft traditions reflect wide connections; its peak is dated to 500–900.','Тиуанако — бийик тоолуу Анд аймагынын саясий жана жөрөлгөлүк борбору. Чоң таш курулуштары жана кол өнөрчүлүгү кеңири байланыштарын көрсөтөт; гүлдөгөн мезгили 500–900-жылдарга туура келет.'),['tiwanaku']),
 P(1000,1150,L('ок. 1000–1150','c. 1000–1150','болж. 1000–1150'),L('Ослабление центра','Decline of the centre','Борбордун начарлашы'),L('Политическое господство Тиуанако ослабевает. Город теряет население, а региональная система распадается в XI — первой половине XII века.','Tiwanaku’s political dominance weakens. The city loses population and its regional system breaks apart during the eleventh and first half of the twelfth centuries.','Тиуанаконун саясий үстөмдүгү начарлайт. Шаардын калкы азайып, аймактык система XI кылымда жана XII кылымдын биринчи жарымында ыдырайт.'),['tiwanaku','andes'])]},
 {id:'sican',region:'south',kind:'culture',coord:[-79.77,-6.49],name:L('Сикан / Ламбайеке','Sicán / Lambayeque','Сикан / Ламбайеке'),phases:[
 P(800,1100,L('ок. 800–1100','c. 800–1100','болж. 800–1100'),L('Батан-Гранде','Batán Grande','Батан-Гранде'),L('В районе Ламбайеке развивается культура сикан, известная металлообработкой и погребальными масками. Батан-Гранде — один из главных церемониальных центров.','Sicán culture develops in Lambayeque, known for metalwork and funerary masks. Batán Grande is a major ceremonial centre.','Ламбайеке аймагында металл иштетүүсү жана сөөк коюу беткаптары менен белгилүү сикан маданияты өнүгөт. Батан-Гранде — негизги жөрөлгөлүк борборлордун бири.'),['sican','andes']),
 P(1100,1300,L('XII–XIII века','12th–13th centuries','XII–XIII кылымдар'),L('Новый центр в Тукуме','New centre at Túcume','Тукумедеги жаңы борбор'),L('После оставления Батан-Гранде значение приобретает Тукуме. Возводятся большие глинобитные платформы; земледельческие и рыбацкие общины поддерживают местную экономику.','After Batán Grande is abandoned, Túcume gains importance. Large adobe platforms are built, supported by farming and fishing communities.','Батан-Гранде ташталгандан кийин Тукуменин мааниси өсөт. Чоң чопо платформалар курулуп, жергиликтүү чарбаны дыйкан жана балыкчы жамааттар камсыз кылат.'),['andes','sicanContinuity'],[-79.84,-6.51])]},
 {id:'chimu',region:'south',kind:'city',coord:[-79.07,-8.10],name:L('Чиму · Чан-Чан','Chimú · Chan Chan','Чиму · Чан-Чан'),phases:[
 P(1150,1200,L('ок. 1150–1200','c. 1150–1200','болж. 1150–1200'),L('Прибрежное государство','Coastal state','Жээктеги мамлекет'),L('Чан-Чан становится столицей государства чиму. Дворцовые комплексы, мастерские и оросительное хозяйство обеспечивают развитие центра в долине Моче.','Chan Chan becomes the capital of the Chimú state. Palace compounds, workshops and irrigation support the centre in the Moche Valley.','Чан-Чан чиму мамлекетинин борборуна айланат. Сарай комплекстери, устаканалар жана сугат чарбасы Моче өрөөнүндөгү борбордун өнүгүшүн камсыз кылат.'),['andes','chimu']),
 P(1200,1300,L('ок. 1200–1300','c. 1200–1300','болж. 1200–1300'),L('Расширение Чиму','Chimú expansion','Чимунун кеңейиши'),L('Чиму расширяет влияние к северу от Чан-Чана. Растут дворцовые и административные комплексы; наибольшая территория государства относится к последующим векам.','Chimú expands north from Chan Chan. Palace and administrative compounds grow; the state’s largest territorial extent belongs to later centuries.','Чиму Чан-Чандан түндүккө карай таасирин кеңейтет. Сарай жана башкаруу комплекстери өсөт; мамлекеттин эң кең аймагы кийинки кылымдарга таандык.'),['andes','chimu'])]},
 {id:'marajo',region:'south',kind:'landscape',coord:[-49.5,-0.8],name:L('Маражо · Амазония','Marajó · Amazonia','Маражо · Амазония'),phases:[
 P(400,1300,L('ок. 400–1300','c. 400–1300','болж. 400–1300'),L('Культура маражоара','Marajoara culture','Маражоара маданияты'),L('На острове Маражо у устья Амазонки известны искусственные насыпи и сложная керамическая традиция. Обозначение на карте относится к островному региону.','Marajó Island at the Amazon’s mouth is known for artificial mounds and a complex ceramic tradition. The map symbol represents the island region.','Амазонканын куймасындагы Маражо аралы жасалма дөбөлөрү жана өнүккөн керамикалык салты менен белгилүү. Картадагы белги аралдык аймакты көрсөтөт.'),['marajo'])]},
 {id:'dongola',region:'africa',kind:'city',coord:[30.44,18.22],name:L('Старая Донгола · Макурия','Old Dongola · Makuria','Эски Донгола · Макурия'),phases:[
 P(500,1000,L('VI–X века','6th–10th centuries','VI–X кылымдар'),L('Христианское царство Нубии','Christian kingdom of Nubia','Нубиянын христиан падышалыгы'),L('Донгола — политический и хозяйственный центр Макурии на Ниле. Укреплённая цитадель, царские здания и церкви образуют ядро города.','Dongola is Makuria’s political and economic centre on the Nile. A fortified citadel, royal buildings and churches form its core.','Донгола — Нилдеги Макуриянын саясий жана чарбалык борбору. Чептүү цитадель, падышалык имараттар жана чиркөөлөр шаардын өзөгүн түзөт.'),['dongola']),
 P(1000,1300,L('XI–XIII века','11th–13th centuries','XI–XIII кылымдар'),L('Столица и монастыри','Capital and monasteries','Борбор шаар жана монастырлар'),L('Макурийская столица сохраняет дворцы, жилые кварталы и монастыри. Стенные росписи и тексты на греческом, коптском и древненубийском языках свидетельствуют о её культурных связях.','The Makurian capital contains palaces, neighbourhoods and monasteries. Wall paintings and texts in Greek, Coptic and Old Nubian attest to its cultural connections.','Макуриянын борборунда сарайлар, турак жайлар жана монастырлар бар. Дубал сүрөттөрү, грек, копт жана байыркы нубия тилдериндеги жазуулар анын маданий байланыштарын көрсөтөт.'),['dongola'])]},
 {id:'ghana',region:'africa',kind:'region',coord:[-7.97,15.67],name:L('Гана / Вагаду · Кумби-Сале','Ghana / Wagadu · Kumbi Saleh','Гана / Вагаду · Кумби-Сале'),phases:[
 P(800,1200,L('IX–XII века','9th–12th centuries','IX–XII кылымдар'),L('Торговля через Сахару','Trans-Saharan trade','Сахара аркылуу соода'),L('Гана связывает золотодобывающие области с караванной торговлей Сахары. Кумби-Сале — важный городской центр; к концу XII века прежнее господство Ганы ослабевает.','Ghana links gold-producing areas with Saharan caravan trade. Kumbi Saleh is an important urban centre; Ghana’s former dominance weakens by the late twelfth century.','Гана алтын өндүрүлгөн аймактарды Сахаранын кербен соодасы менен байланыштырат. Кумби-Сале — маанилүү шаардык борбор; XII кылымдын аягында Гананын мурдагы үстөмдүгү начарлайт.'),['sahel'])]},
 {id:'mali',region:'africa',kind:'region',coord:[-8.5,12],name:L('Мали · Верхний Нигер','Mali · Upper Niger','Мали · Жогорку Нигер'),phases:[
 P(1230,1300,L('с ок. 1230 · XIII век','from c. 1230 · 13th century','болж. 1230-жылдан · XIII кылым'),L('Возникновение державы Мали','Rise of Mali','Мали мамлекетинин түзүлүшү'),L('Сундиата Кейта объединяет силы манден и закладывает основу державы Мали. Карта показывает область Верхнего Нигера; это регион формирования государства.','Sunjata Keita unites Manding forces and establishes the basis of Mali’s empire. The map shows the Upper Niger, the region in which the state emerged.','Сундиата Кейта манден күчтөрүн бириктирип, Мали мамлекетинин негизин түзөт. Картада мамлекет калыптанган Жогорку Нигер аймагы көрсөтүлгөн.'),['mali','sahel'])]},
 {id:'kilwa',region:'africa',kind:'city',coord:[39.52,-8.96],name:L('Килва-Кисивани','Kilwa Kisiwani','Килва-Кисивани'),phases:[
 P(800,1200,L('IX–XII века','9th–12th centuries','IX–XII кылымдар'),L('Суахилийский порт','Swahili port','Суахили порту'),L('Островной порт развивается в сети поселений восточноафриканского побережья. Морские связи способствуют торговле и распространению ислама.','The island port develops within the settlement network of the East African coast. Maritime connections support trade and the spread of Islam.','Аралдагы порт Чыгыш Африка жээгинин конуштар тармагында өнүгөт. Деңиз байланыштары соодага жана исламдын жайылышына көмөктөшөт.'),['kilwa']),
 P(1200,1300,L('XIII век','13th century','XIII кылым'),L('Торговля Индийского океана','Indian Ocean trade','Инд океанындагы соода'),L('Килва вступает в период большого торгового подъёма. Через порт проходят золото и другие товары; находки связывают город с Аравией, Персией и Китаем.','Kilwa enters a period of major commercial growth. Gold and other goods pass through the port; finds connect it with Arabia, Persia and China.','Килва соодасы күчтүү өнүккөн мезгилге кирет. Порт аркылуу алтын жана башка товарлар өтөт; табылгалар шаарды Аравия, Персия жана Кытай менен байланыштырат.'),['kilwa'])]},
 {id:'mapungubwe',region:'africa',kind:'city',coord:[29.61,-22.21],name:L('Мапунгубве','Mapungubwe','Мапунгубве'),phases:[
 P(1220,1300,L('ок. 1220–1300','c. 1220–1300','болж. 1220–1300'),L('Царский центр на Лимпопо','Royal centre on the Limpopo','Лимпоподогу падышалык борбор'),L('На холме Мапунгубве складывается царский центр. Земледелие и торговля золотом и слоновой костью через восточноафриканские порты поддерживают общество с выраженной социальной иерархией.','A royal centre takes shape on Mapungubwe Hill. Farming and trade in gold and ivory through East African ports support a socially stratified society.','Мапунгубве дөбөсүндө падышалык борбор калыптанат. Дыйканчылык, алтын жана пил сөөгүн Чыгыш Африка порттору аркылуу сатуу социалдык катмарларга бөлүнгөн коомду камсыз кылат.'),['mapungubwe'])]},
 {id:'zimbabwe',region:'africa',kind:'city',coord:[30.93,-20.27],name:L('Великий Зимбабве','Great Zimbabwe','Улуу Зимбабве'),phases:[
 P(1100,1300,L('ок. 1100–1300','c. 1100–1300','болж. 1100–1300'),L('Рост каменного центра','Growth of a stone-built centre','Таш курулуштуу борбордун өсүшү'),L('На холме и в прилегающих долинах развивается центр предков шона. Каменная кладка и дальние торговые связи характеризуют его рост; Большая ограда относится уже к XIV веку.','A centre of Shona ancestors develops on the hill and in adjoining valleys. Stone masonry and long-distance trade characterise its growth; the Great Enclosure belongs to the fourteenth century.','Дөбөдө жана жанындагы өрөөндөрдө шона элинин ата-бабаларынын борбору өнүгөт. Таш курулуштары жана алыскы соода байланыштары анын өсүшүн мүнөздөйт; Чоң коргон XIV кылымга таандык.'),['zimbabwe'])]},
 {id:'lalibela',region:'africa',kind:'city',coord:[39.05,12.03],name:L('Лалибэла · аль-Хабаша','Lalibela · al-Habasha','Лалибэла · аль-Хабаша'),phases:[
 P(1100,1300,L('XII–XIII века','12th–13th centuries','XII–XIII кылымдар'),L('Скальные церкви Эфиопии','Rock-hewn churches of Ethiopia','Эфиопиянын аска чиркөөлөрү'),L('В Лалибэле формируется комплекс высеченных в скале церквей. Их строительство связывают с царём Лалибэлой; город становится важным центром эфиопского христианства.','A complex of rock-hewn churches takes shape at Lalibela. Their construction is associated with King Lalibela; the town becomes an important centre of Ethiopian Christianity.','Лалибэледе аскадан чегилген чиркөөлөр комплекси түзүлөт. Алардын курулушу падыша Лалибэла менен байланышат; шаар эфиоп христианчылыгынын маанилүү борборуна айланат.'),['lalibela'])]},
 {id:'budj',region:'australia',kind:'landscape',coord:[141.88,-38.08],name:L('Будж-Бим · гунджитмара','Budj Bim · Gunditjmara','Будж-Бим · гунджитмара'),phases:[
 P(610,1300,L('Длительная культурная традиция','Long cultural continuity','Узакка созулган маданий салт'),L('Управление водой и ловля угря','Water management and eel harvesting','Сууну башкаруу жана жылан балык кармоо'),L('Гунджитмара используют каналы, плотины и ловушки для угря. Этот культурный ландшафт юго-восточной Австралии складывался тысячелетиями и продолжал существовать в рассматриваемую эпоху.','Gunditjmara people use channels, weirs and traps to harvest eels. This cultural landscape in southeastern Australia developed over millennia and continued through the period shown.','Гунджитмара эли жылан балык кармоо үчүн каналдарды, бөгөттөрдү жана тузактарды пайдаланат. Түштүк-чыгыш Австралиядагы бул маданий ландшафт миңдеген жылдар бою калыптанып, көрсөтүлгөн доордо да жашап турган.'),['budj'])]},
 {id:'kakadu',region:'australia',kind:'landscape',coord:[132.5,-12.8],name:L('Какаду · север Австралии','Kakadu · northern Australia','Какаду · түндүк Австралия'),phases:[
 P(610,1300,L('Длительная культурная традиция','Long cultural continuity','Узакка созулган маданий салт'),L('Знание ландшафта и наскальное искусство','Landscape knowledge and rock art','Ландшафтты билүү жана аска сүрөттөрү'),L('Общины коренных народов связаны с речными долинами, водно-болотными угодьями и скальными убежищами. Наскальные изображения и археология свидетельствуют о длительной истории хозяйственных и обрядовых традиций.','Indigenous communities are connected to river valleys, wetlands and rock shelters. Rock art and archaeology document a long history of subsistence and ceremonial traditions.','Түпкү элдердин жамааттары дарыя өрөөндөрү, саздак жерлер жана аска баш калкалоочу жайлар менен байланышкан. Аска сүрөттөрү жана археология чарбалык жана жөрөлгөлүк салттардын узак тарыхын көрсөтөт.'),['kakadu'])]}
];
module.exports=require('./continuity.cjs')(require('./to1789.cjs')(require('./early-modern.cjs')(require('./late-medieval.cjs')(require('./education.cjs')(require('./expansion.cjs')({regions,sources,entries}))))));
