'use strict';
// Africa, 1454–1600. Annual snapshots and schematic regional cores.
// Research, dated transitions and limits: EARLY_AFRICA_RESEARCH.md.
module.exports=(c,H)=>{
 const {L,source,phase,entry,continueEntry,area,event}=H;
 const OTTOMAN='#bc815a',PORTUGAL='#7d99bb';
 const learn=(government,economy,society)=>({government,economy,society});
 // Every continuation is an explicit historical decision, not a blanket extension.
 // Row: from, to, title, text, outline, map kind, optional phase/map overrides.
 function D(id,name,coord,sources,learning,rows,opt={}){
  const phases=rows.map(([from,to,title,text,_p,_k,x={}])=>phase(from,to,title,text,x.sources||sources,{learning,...x.phase}));
  const e=c.entries.some(e=>e.id===id)?continueEntry(id,phases):entry(id,'africa',opt.kind||'state',coord,name,phases);
  for(const [from,to,_t,_x,p,k='polity',x={}] of rows)if(p!==null)area(id,from,to,p,{kind:k,color:opt.color,name:opt.areaName,...x.area});
  return e;
 }
 const E=(id,y,e,kind,coord,t,x,s,extra={})=>event(id,y,e,({state:'politics',building:'culture',religion:'culture',trade:'diplomacy'})[kind]||kind,coord,t,x,s,extra);
 const box=(x,y,dx=.35,dy=.3)=>[[x-dx,y-dy],[x+dx,y-dy],[x+dx,y+dy],[x-dx,y+dy]];
 source('earlySonghay','John O. Hunwick. Timbuktu and the Songhay Empire: al-Saʿdi’s Taʾrikh al-sudan down to 1613 and Other Contemporary Documents. Brill, 1999; OpenStax. World History, Volume 2, section 3.2, The Songhai Empire.', ['https://books.google.com/books/about/Timbuktu_and_the_Songhay_Empire.html?id=7L4TVckuppUC','https://openstax.org/books/world-history-volume-2/pages/3-2-the-songhai-empire']);
 source('earlySahel','The Metropolitan Museum of Art. Western and Central Sudan, 1400–1600 A.D.; Sahel: Art and Empires on the Shores of the Sahara.', ['https://82nd-and-fifth.metmuseum.org/toah/ht/08/afu.html','https://www.metmuseum.org/exhibitions/sahel-art-empire-sahara']);
 source('earlyAfricaV','B. A. Ogot (ed.). General History of Africa, Volume V: Africa from the Sixteenth to the Eighteenth Century. UNESCO, 1992.', ['https://unesdoc.unesco.org/ark:/48223/pf0000121577']);
 source('earlyBornu','Ahmad ibn Furtu. A Sudanic Chronicle: The Borno Expeditions of Idris Alauma (1564–1576), edited and translated by Dierk Lange. Franz Steiner, 1987; B. G. Martin. Maî Idrîs of Bornu and the Ottoman Turks, 1576–78. International Journal of Middle East Studies 3, 1972.', ['https://www.cambridge.org/core/journals/international-journal-of-middle-east-studies/article/abs/mai-idris-of-bornu-and-the-ottoman-turks-157678/F5206F26778715286BE4CC3E15450D9A']);
 source('earlyFunj','P. M. Holt. The Sudan of the Three Niles: The Funj Chronicle, 910–1288/1504–1871. Brill, 1999; UNESCO Khartoum. Sudanese Cultural Heritage Sites.', ['https://www.cambridge.org/core/journals/international-journal-of-middle-east-studies/article/abs/pm-holt-the-sudan-of-the-three-niles-the-funj-chronicle-910128815041871-islamic-history-and-civilization-studies-and-texts-leiden-ej-brill-1999-pp-228-7100-cloth-/D9204B40B4242AB08184CC083D06710A','https://sudan.un.org/sites/default/files/2019-10/180520_WH%20sites%20Final%20en_0.pdf']);
 source('earlyOttomanAfrica','Ira M. Lapidus. Islamic Societies to the Nineteenth Century, chapter 28: Libya, Tunisia, Algeria, and Morocco. Cambridge University Press, 2012; Suzan Yalman. The Art of the Mamluk Period (1250–1517). The Metropolitan Museum of Art.', ['https://www.cambridge.org/core/books/abs/islamic-societies-to-the-nineteenth-century/libya-tunisia-algeria-and-morocco-from-the-thirteenth-to-the-nineteenth-centuries/BC566434A319CE7054B34432EE033507','https://www.metmuseum.org/essays/the-art-of-the-mamluk-period-1250-1517']);
 source('earlyAlgiers','James McDougall. A History of Algeria, chapter 1: Ecologies, Societies, Cultures and the State, 1516–1830. Cambridge University Press, 2017.', ['https://doi.org/10.1017/9781139029230.003']);
 source('earlyTunis','Leïla Temime Blili. The Regency of Tunis, 1535–1666: Genesis of an Ottoman Province in the Maghreb. American University in Cairo Press, 2021; Museum With No Frontiers. Tunisia: Historical Timeline, 1500–1800.', ['https://www.jstor.org/stable/j.ctv2ks6xjw','https://islamicart.museumwnf.org/hcr_result.php?country=tn&end_date=1800&lng=en&start_date=1500']);
 source('earlyMorocco','Eloy Martín Corrales. Muslims in Spain, 1492–1814: Living and Negotiating in the Land of the Infidel, chapter 3. Brill, 2021; Jamil M. Abun-Nasr. A History of the Maghrib in the Islamic Period. Cambridge University Press, 1987.', ['https://tile.loc.gov/storage-services/master/gdc/gdcebookspublic/20/20/04/61/45/2020046145/2020046145.pdf','https://doi.org/10.1017/CBO9780511608100']);
 source('earlyHorn','ʿArab Faqih. Futuh al-Habasha: The Conquest of Abyssinia, translated by Paul Lester Stenhouse, annotations by Richard Pankhurst. Tsehai, 2003; Marilyn E. Heldman. African Christianity in Ethiopia. The Metropolitan Museum of Art.', ['https://www.metmuseum.org/essays/african-christianity-in-ethiopia','https://search.worldcat.org/title/52380543']);
 source('earlyOromo','Mohammed Hassen. The Oromo and the Christian Kingdom of Ethiopia, 1300–1700. Boydell & Brewer, 2015, chapters 3–5.', ['https://doi.org/10.1017/9781782045809']);
 source('earlyHarar','Nicholas M. T. Tait. Archaeological Ceramics as Chronological Indicators on Islamic Sites in Eastern Ethiopia. University of Exeter doctoral thesis, 2020; UNESCO. Harar Jugol, the Fortified Historic Town.', ['https://ore.exeter.ac.uk/repository/bitstream/handle/10871/121775/TaitN_TPC.pdf?isAllowed=y&sequence=2','https://whc.unesco.org/en/list/1189/']);
 source('earlySwahili','UNESCO. Ruins of Kilwa Kisiwani and Ruins of Songo Mnara; Historic Town and Archaeological Site of Gedi, nomination dossier.', ['https://whc.unesco.org/en/list/144/','https://whc.unesco.org/document/199048']);
 source('earlyKilwaFort','Fundação Calouste Gulbenkian. Heritage of Portuguese Influence: Fort, Kilwa Kisiwani. Research catalogue.', ['https://hpip.org/en/heritage/details/2009']);
 source('earlyIndianPorts','UNESCO. Fort Jesus, Mombasa; Island of Mozambique; Albino Jopela. Saving Urban Landscapes: The Island of Mozambique. UNESCO, 2019.', ['https://whc.unesco.org/en/list/1295/','https://whc.unesco.org/en/list/599/','https://www.unesco.org/en/articles/saving-urban-landscapes-island-mozambique']);
 source('earlyBenin','The Metropolitan Museum of Art. Seated Portuguese Figure, collection 1991.17.31; University of Cambridge, Museum of Archaeology and Anthropology. Kingdom of Benin.', ['https://www.metmuseum.org/art/collection/search/316502','https://maa.cam.ac.uk/schools/resources/african-collections-schools-resources/kingdom-benin']);
 source('earlyKongo','UNESCO. Mbanza Kongo, Vestiges of the Capital of the Former Kingdom of Kongo, ICOMOS evaluation; Malyn Newitt (ed.). The Portuguese in West Africa, 1415–1670, chapter 10: Christianity in the Kongo. Cambridge University Press, 2010.', ['https://whc.unesco.org/archive/2017/whc17-41com-inf8B1-en.pdf','https://www.cambridge.org/core/books/abs/portuguese-in-west-africa-14151670/christianity-in-the-kongo/B4656F226EE7B26AAB67437D29B597E8']);
 source('earlyZimbabwe','UNESCO. Great Zimbabwe National Monument; Khami Ruins National Monument; Thimlich Ohinga Archaeological Site, nomination dossier (regional comparisons).', ['https://whc.unesco.org/en/list/364/','https://whc.unesco.org/en/list/365/','https://whc.unesco.org/document/165555']);
 source('earlyMutapa','Edward A. Alpers. Ivory and Slaves in East Central Africa. University of California Press, 1975; The Metropolitan Museum of Art. Southern Africa, 1600–1800 A.D.', ['https://www.ucpress.edu/books/ivory-and-slaves-in-east-central-africa/paper','https://82nd-and-fifth.metmuseum.org/toah/ht/09/afo.html']);
 source('earlyMadagascar','UNESCO and ICOMOS. Royal Hill of Ambohimanga: Evaluation and Statement of Outstanding Universal Value.', ['https://whc.unesco.org/document/1118','https://whc.unesco.org/en/list/950/']);

 const sahel=learn(L('Двор, провинциальные правители и местные общины.','Court, provincial rulers and local communities.','Сарай, облустук башкаруучулар жана жергиликтүү жамааттар.'),L('Золото, соль, земледелие и торговля по Нигеру.','Gold, salt, farming and Niger River trade.','Алтын, туз, дыйканчылык жана Нигердеги соода.'),L('В городах действуют мечети, школы и ремесленные кварталы.','Mosques, schools and craft quarters shape urban life.','Шаарларда мечиттер, мектептер жана усталардын кварталдары иштейт.'));
 const maliCore=[[-12.5,11.2],[-12,13.3],[-9,14.1],[-6.1,13.9],[-5.4,12],[-7.5,10.1],[-10.8,10.2]];
 D('mali',null,null,['earlySahel','earlySonghay'],sahel,[
  [1454,1500,L('Мали и земли манден','Mali and the Manden lands','Мали жана манден жерлери'),L('Мансы сохраняют власть на западе. Усиление Сонгая и самостоятельных соседей сокращает прежнюю сеть зависимости.','The mansas retain power in the west. Songhay and independent neighbours reduce Mali’s former network of dependencies.','Мансалар батышта бийлигин сактайт. Сонгайдын жана өз алдынча коңшулардын күчөшү Малиге көз каранды аймактарды азайтат.'),'previous','influence'],
  [1500,1601,L('Мали в XVI веке','Mali in the sixteenth century','XVI кылымдагы Мали'),L('Мали сохраняется в манденском ядре, хотя прежняя имперская система распадается. Возвышение и падение Сонгая не означают исчезновения Мали.','Mali survives in its Manden heartland as the old imperial network fragments. Songhay’s rise and fall do not mean Mali’s disappearance.','Мурунку империялык байланыштар ыдыраса да, Мали манден өзөгүндө сакталат. Сонгайдын көтөрүлүшү жана кулашы Малинин жок болушун билдирбейт.'),maliCore,'influence']
 ]);
 const songhay1468=[[-4.2,15],[-4.5,17.2],[-1.5,18],[1.9,17.5],[2,14],[.8,12.8],[-1.8,13.2]];
 const songhay1473=[[-6.1,12.6],[-5.5,16],[-4.5,17.2],[-1.5,18],[1.9,17.5],[2.2,14],[.8,12.8],[-2.5,12.1]];
 const songhayAskia=[[-7,13],[-6.3,16.4],[-5,18.3],[-1.5,19.6],[2.5,18.4],[4.5,16.5],[4.5,13.5],[1,11.9],[-2.5,12],[-5.1,11.8]];
 D('gao',null,null,['earlySonghay','earlySahel'],sahel,[
  [1454,1464,L('Сонгай перед Сонни Али','Songhay before Sonni Ali','Сонни Алиге чейинки Сонгай'),L('Гао служит центром сонгайской власти на Нигере. Тимбукту пока находится вне её прочного контроля.','Gao is a centre of Songhay power on the Niger. Timbuktu remains outside its firm control.','Гао Нигердеги Сонгай бийлигинин борбору. Тимбукту азырынча анын туруктуу көзөмөлүнө кирбейт.'),'previous','polity'],
  [1464,1468,L('Начало правления Сонни Али','Sonni Ali takes power','Сонни Али бийликке келет'),L('Сонни Али усиливает конницу и речные силы. Начинается расширение государства вдоль Нигера.','Sonni Ali strengthens cavalry and river forces. Expansion along the Niger begins.','Сонни Али атчан жана дарыя аскерлерин күчөтөт. Мамлекет Нигер боюнда кеңейе баштайт.'),'previous','polity'],
  [1468,1473,L('Тимбукту под властью Сонгая','Timbuktu under Songhay','Тимбукту Сонгай бийлигинде'),L('Сонни Али овладевает Тимбукту в 1468 году. Северные торговые пути входят в сонгайскую сферу власти.','Sonni Ali takes Timbuktu in 1468. Northern trade routes enter the Songhay sphere.','Сонни Али 1468-жылы Тимбуктуну алат. Түндүктөгү соода жолдору Сонгайдын таасирине өтөт.'),songhay1468,'influence'],
  [1473,1493,L('Расширение к Дженне','Expansion towards Djenné','Женнеге карай кеңейүү'),L('После длительной осады Дженне подчиняется Сонни Али. Речные города связывают зерновые районы с караванной торговлей.','After a long siege Djenné submits to Sonni Ali. River towns connect grain-producing districts with caravan commerce.','Узак курчоодон кийин Женне Сонни Алиге баш иет. Дарыя шаарлары дан өстүрүлгөн аймактарды кербен соодасы менен байланыштырат.'),songhay1473,'influence',{phase:{approx:true}}],
  [1493,1591,L('Сонгай династии Аския','Songhay under the Askias','Аскиялар бийлигиндеги Сонгай'),L('Аския Мухаммад сменяет династию Сонни. Государство объединяет области через наместников и дань; Тимбукту становится крупным центром исламской учёности.','Askia Muhammad replaces the Sonni dynasty. Governors and tribute connect the provinces; Timbuktu becomes a major centre of Islamic scholarship.','Аския Мухаммад Сонни династиясын алмаштырат. Облустар башкаруучулар жана алым аркылуу биригет; Тимбукту ислам илиминин ири борборуна айланат.'),songhayAskia,'influence'],
  [1591,1601,L('Гао после марокканского вторжения','Gao after the Moroccan invasion','Марокко басып киргенден кийинки Гао'),L('После поражения при Тондиби Гао занимает марокканская армия. Единая империя распадается, но сонгайское сопротивление продолжается ниже по Нигеру.','After Tondibi the Moroccan army occupies Gao. The empire breaks apart, while Songhay resistance continues downriver.','Тондибидеги жеңилүүдөн кийин Марокко аскери Гаону ээлейт. Империя ыдырайт, бирок Сонгайдын каршылыгы Нигердин төмөн жагында уланат.'),box(-.03,16.28),'settlement',{area:{name:L('Гао','Gao','Гао'),color:'#ba9b74'}}]
 ],{areaName:L('Сонгай','Songhay','Сонгай')});
 D('early-songhay-dendi',L('Сонгай · Денди','Songhay · Dendi','Сонгай · Денди'),[3.1,11.7],['earlySonghay'],sahel,[
  [1591,1601,L('Сопротивление в Денди','Resistance in Dendi','Дендидеги каршылык'),L('Преемники Аския сохраняют власть и ведут борьбу в Денди. Марокканская победа на севере не установила единого контроля над всем прежним Сонгаем.','Askia successors retain power and resist in Dendi. Morocco’s northern victory does not establish control over all former Songhay lands.','Аскиянын мураскерлери Дендиде бийликти сактап, каршылык көрсөтөт. Марокконун түндүктөгү жеңиши бүт мурдагы Сонгайды көзөмөлдөөгө алып келген жок.'),[[1.1,12.6],[1.8,13.3],[3.9,12.7],[4.6,11.3],[3.5,10.4],[1.8,10.9]],'influence']
 ],{color:'#b8a379'});
 const townLearning=learn(L('Городские правители, судьи и влиятельные семьи.','Urban rulers, judges and influential families.','Шаар башкаруучулары, казылар жана таасирдүү үй-бүлөлөр.'),L('Рынки соединяют речные и сухопутные перевозки.','Markets connect river and overland transport.','Базарлар дарыя жана кургактык ташууларын байланыштырат.'),L('Учёность и ремёсла поддерживаются городской средой.','Learning and crafts are sustained by urban society.','Илим жана кол өнөрчүлүк шаардык коомго таянат.'));
 for(const [id,cut,name] of [['timbuktu-late',1468,'Тимбукту'],['djenne-late',1473,'Дженне']])D(id,null,null,['earlySonghay','lateTimbuktu','lateDjenne'],townLearning,[
  [1454,cut,L('Торговый город перед завоеванием','A trading town before conquest','Каратылганга чейинки соода шаары'),L('Городские власти управляют рынками и отношениями с соседями. Вскоре город войдёт в державу Сонни Али.','Urban authorities manage markets and relations with neighbours. The town will soon enter Sonni Ali’s empire.','Шаар бийлиги базарларды жана коңшулар менен байланышты башкарат. Көп өтпөй шаар Сонни Алинин мамлекетине кирет.'),'previous','settlement'],
  [cut,1591,L('Город Сонгайской державы','A city of the Songhay realm','Сонгай мамлекетиндеги шаар'),L('Город входит в державу Сонгая. Торговля, рукописные книги и исламское образование связывают его с другими центрами Судана и Сахары.','The town belongs to the Songhay realm. Trade, manuscripts and Islamic education link it to other Sudanese and Saharan centres.','Шаар Сонгай мамлекетине кирет. Соода, кол жазмалар жана ислам билими аны Судан менен Сахаранын башка борборлоруна байланыштырат.'),'previous','settlement',{area:{color:'#b8a379'}}],
  [1591,1601,L('Марокканские гарнизоны и местное общество','Moroccan garrisons and local society','Марокко гарнизондору жана жергиликтүү коом'),L('После вторжения марокканские гарнизоны действуют среди местных правителей и торговых общин. Война нарушает прежние связи, но городская жизнь продолжается.','After the invasion Moroccan garrisons coexist with local rulers and trading communities. Warfare disrupts older connections, but urban life continues.','Басып кирүүдөн кийин Марокко гарнизондору жергиликтүү башкаруучулар жана соода жамааттары менен катар жашайт. Согуш эски байланыштарды бузат, бирок шаар турмушу уланат.'),'previous','settlement',{area:{color:'#ba9b74'}}]
 ]);

 const chadLearning=learn(L('Маи и династия Сайфава опираются на военную и областную администрацию.','The mai and Sayfawa dynasty rely on military and provincial administration.','Маи жана Сайфава династиясы аскердик жана аймактык башкарууга таянат.'),L('Земледелие, скотоводство и караванные пути через Сахару.','Farming, herding and trans-Saharan caravan routes.','Дыйканчылык, мал чарбачылыгы жана Сахара аркылуу өткөн кербен жолдору.'),L('Исламские учёные, городские ремесленники и сельские общины.','Islamic scholars, urban craftspeople and rural communities.','Ислам аалымдары, шаар усталары жана айыл жамааттары.'));
 D('kanem',null,null,['lateKanem','earlyBornu','earlyAfricaV'],learn(L('Местные правители и соперничество с Борну.','Local rulers and rivalry with Bornu.','Жергиликтүү башкаруучулар жана Борну менен атаандаштык.'),chadLearning.economy,chadLearning.society),[
  [1454,1500,L('Булала в Канеме','Bulala in Kanem','Канемдеги Булала'),L('Булала удерживают земли к востоку от озера Чад. Сайфава в Борну стремятся восстановить влияние в прежнем центре.','The Bulala hold lands east of Lake Chad. The Sayfawa of Bornu seek influence in their former centre.','Булала Чад көлүнүн чыгышындагы жерлерди кармайт. Борнудогу Сайфава мурдагы борбордо таасирин калыбына келтирүүгө умтулат.'),'previous','polity'],
  [1500,1601,L('Канем между Булала и Борну','Kanem between the Bulala and Bornu','Булала менен Борнунун ортосундагы Канем'),L('В XVI веке Борну возвращается в Канем военными походами. Местные Булала сохраняют собственные центры; степень зависимости меняется.','During the sixteenth century Bornu campaigns return to Kanem. Bulala rulers retain local centres as relationships of dependence change.','XVI кылымда Борну аскердик жортуулдар менен Канемге кайтып келет. Көз карандылык өзгөрүп турганда Булала жергиликтүү борборлорун сактайт.'),[[15.3,12.8],[17.7,12.5],[18.1,14.7],[17,15.8],[15.4,14.9]],'influence',{phase:{approx:true}}]
 ]);
 D('bornu-late',null,null,['earlyBornu','earlyAfricaV'],chadLearning,[
  [1454,1500,L('Борну и новая столица','Bornu and a new capital','Борну жана жаңы борбор'),L('Сайфава укрепляют Борну. В конце XV века Нгазаргаму становится укреплённым центром двора и управления.','The Sayfawa consolidate Bornu. In the late fifteenth century Ngazargamu becomes a fortified centre of court and government.','Сайфава Борнуну бекемдейт. XV кылымдын аягында Нгазаргаму сарайдын жана башкаруунун чептүү борборуна айланат.'),'previous','polity'],
  [1500,1564,L('Возвращение влияния к озеру Чад','Renewed influence around Lake Chad','Чад көлүндөгү таасирдин калыбына келиши'),L('Борну расширяет влияние вокруг озера и возобновляет борьбу за Канем. Столица остаётся на западе, в Нгазаргаму.','Bornu expands around the lake and renews its struggle for Kanem. The capital remains west of the lake at Ngazargamu.','Борну көлдүн айланасында таасирин кеңейтип, Канем үчүн күрөштү кайра баштайт. Борбор көлдүн батышындагы Нгазаргамуда калат.'),[[10.5,11],[12.4,10.6],[14.6,11.7],[15.2,14.7],[13.1,15.8],[10.3,14]],'influence',{phase:{coord:[12.46,13.06],approx:true}}],
  [1564,1601,L('Борну во времена Идриса Алумы','Bornu in the age of Idris Alauma','Идрис Алума доорундагы Борну'),L('Идрис Алума развивает армию и исламское управление. Хроника Ибн Фурту описывает его походы; посольства связывают Борну с Османской державой.','Idris Alauma develops the army and Islamic administration. Ibn Furtu chronicles his campaigns; embassies connect Bornu with the Ottoman Empire.','Идрис Алума аскерди жана исламдык башкарууну өнүктүрөт. Ибн Фурту анын жортуулдарын жазат; элчиликтер Борнуну Осмон мамлекети менен байланыштырат.'),[[9.8,11.3],[12.3,10.5],[14.8,11.6],[15.3,15.3],[13.3,17],[10.4,15.2]],'influence',{phase:{coord:[12.46,13.06],approx:true}}]
 ]);

 const nileLearning=learn(L('Местные властители и общины долины Нила.','Local rulers and communities of the Nile valley.','Нил өрөөнүндөгү жергиликтүү башкаруучулар жана жамааттар.'),L('Пойменное земледелие, скот и речные перевозки.','Floodplain farming, livestock and river transport.','Жайылмадагы дыйканчылык, мал жана дарыя ташуулары.'),L('Нубийские традиции и распространение исламских институтов.','Nubian traditions and the spread of Islamic institutions.','Нубиялык салттар жана исламдык институттардын жайылышы.'));
 D('dongola',null,null,['lateDongola','earlyFunj'],nileLearning,[[1454,1601,L('Донгола после средневекового царства','Dongola after the medieval kingdom','Орто кылымдагы падышалыктан кийинки Донгола'),L('Донгола остаётся населённым центром Нильской долины. Мусульманские дома и местные власти сменяют прежнюю царскую среду.','Dongola remains an inhabited Nile centre. Muslim households and local authorities replace the former royal setting.','Донгола Нил өрөөнүндөгү калктуу борбор бойдон калат. Мусулман үй-бүлөлөрү жана жергиликтүү бийлик мурдагы падышалык чөйрөнү алмаштырат.'),'previous','settlement']]);
 D('alwa',null,null,['earlyFunj','lateGHA'],nileLearning,[[1454,1504,L('Поздняя Алва и Соба','Late Alwa and Soba','Соңку Алва жана Соба'),L('Царство в районе Собы ослабевает. К началу XVI века политический центр перемещается к новым объединениям долины Нила.','The kingdom around Soba weakens. By the early sixteenth century new Nile coalitions replace the old political centre.','Собанын айланасындагы падышалык алсырайт. XVI кылымдын башында Нилдеги жаңы бирикмелер эски саясий борборду алмаштырат.'),'previous','influence',{phase:{approx:true}}]]);
 D('early-funj',L('Султанат Фундж · Сеннар','Funj Sultanate · Sennar','Фунж султандыгы · Сеннар'),[33.57,13.55],['earlyFunj'],learn(L('Султаны Фундж и зависимые местные правители.','Funj sultans and subordinate local rulers.','Фунж султандары жана аларга баш ийген жергиликтүү башкаруучулар.'),nileLearning.economy,nileLearning.society),[[1504,1601,L('Сеннар становится центром власти','Sennar becomes a centre of power','Сеннар бийлик борборуна айланат'),L('Традиционная хронология относит основание султаната к 1504 году. Фундж строят власть на Голубом Ниле и связях с правителями северных областей.','The conventional chronology dates the sultanate to 1504. The Funj build power on the Blue Nile and alliances with northern regional rulers.','Салттуу жылнаама султандыктын түзүлүшүн 1504-жылга таандык кылат. Фунж Көк Нилде жана түндүктөгү башкаруучулар менен байланыш аркылуу бийлик түзөт.'),[[31,12.2],[33.6,11.9],[35,13.6],[34.5,16.2],[32,17],[30.8,15.5]],'influence',{phase:{approx:true}}]],{color:'#809ca5'});

 const mamlukLearning=learn(L('Султан, эмиры и военные хозяйства мамлюков.','Sultan, amirs and Mamluk military households.','Султан, эмирлер жана мамлюктардын аскердик чарбалары.'),L('Нил, ремесло Каира и торговля между Красным и Средиземным морями.','The Nile, Cairo crafts and trade between the Red Sea and Mediterranean.','Нил, Каирдин кол өнөрчүлүгү жана Кызыл деңиз менен Жер Ортолук деңиздин ортосундагы соода.'),L('Медресе, вакфы, рынки и городские общины.','Madrasas, endowments, markets and urban communities.','Медреселер, вакфтар, базарлар жана шаар жамааттары.'));
 const egypt=[[25.2,31.5],[29.8,31.7],[31.8,31.5],[34.2,31.1],[34.9,29.5],[34,27.6],[35.1,24],[33,22],[30,22],[27.5,24.3],[26.2,28]];
 const sham=[[34.2,31.1],[35.2,33],[35.7,35],[35.3,36.6],[36.7,36.8],[38.3,35.8],[39,34.5],[37.3,32.2],[36,30],[34.9,29.5]];
 D('mamluk-late',null,null,['earlyOttomanAfrica'],mamlukLearning,[
  [1454,1516,L('Поздний Мамлюкский султанат','The later Mamluk Sultanate','Соңку Мамлюк султандыгы'),L('Каир управляет Египтом и аш-Шамом. Мамлюкские султаны поддерживают военную элиту, торговлю и строительство; на севере усиливается османское давление.','Cairo governs Egypt and al-Sham. Mamluk sultans support a military elite, commerce and building while Ottoman pressure grows in the north.','Каир Египетти жана аш-Шамды башкарат. Мамлюк султандары аскердик төбөлдөрдү, сооданы жана курулушту колдойт; түндүктө Осмон кысымы күчөйт.'),'previous','polity'],
  [1516,1517,L('Последний год мамлюкского Египта','The final year of Mamluk Egypt','Мамлюк Египетинин акыркы жылы'),L('После поражения при Мардж-Дабике аш-Шам переходит к Селиму I. Туман-бай продолжает сопротивление в Египте.','After Marj Dabiq, al-Sham passes to Selim I. Tuman Bay continues resistance in Egypt.','Марж Дабыктагы жеңилүүдөн кийин аш-Шам Селим Iге өтөт. Туман-бай Египетте каршылыгын улантат.'),egypt,'polity']
 ]);
 const ottomanLearning=learn(L('Османские наместники взаимодействуют с местными военными и городской знатью.','Ottoman governors work with local military households and urban notables.','Осмон башкаруучулары жергиликтүү аскер төбөлдөрү жана шаар аксакалдары менен иштейт.'),L('Налоги, земледелие, портовая торговля и караваны.','Taxation, farming, port trade and caravans.','Салыктар, дыйканчылык, порт соодасы жана кербендер.'),L('Местные общины продолжают жить при смене верховной власти.','Local communities continue through changes of imperial authority.','Жогорку бийлик алмашса да, жергиликтүү жамааттар жашоосун улантат.'));
 D('early-ottoman-egypt-sham',L('Османские Египет и аш-Шам','Ottoman Egypt and al-Sham','Осмон Египети жана аш-Шам'),[36.3,33.51],['earlyOttomanAfrica'],ottomanLearning,[
  [1516,1517,L('Османское управление в аш-Шаме','Ottoman rule in al-Sham','Аш-Шамдагы Осмон бийлиги'),L('Победа Селима I открывает путь к Дамаску. Сирийские области входят в Османскую державу раньше Египта.','Selim I’s victory opens the road to Damascus. The Syrian provinces enter the Ottoman Empire before Egypt.','Селим Iнин жеңиши Дамаскка жол ачат. Сирия аймактары Осмон мамлекетине Египеттен мурда кирет.'),sham,'polity'],
  [1517,1601,L('Провинции единой Османской державы','Provinces of the Ottoman Empire','Бирдиктүү Осмон мамлекетинин облустары'),L('Селим I завоёвывает Египет. Каир и Дамаск становятся центрами османских провинций; мамлюкские военные семьи сохраняют влияние в Египте.','Selim I conquers Egypt. Cairo and Damascus become Ottoman provincial centres; Mamluk military households retain influence in Egypt.','Селим I Египетти каратат. Каир жана Дамаск Осмон облустарынын борборлоруна айланат; мамлюк аскер үй-бүлөлөрү Египетте таасирин сактайт.'),[egypt,sham],'polity',{phase:{coord:[31.24,30.04]}}]
 ],{kind:'region',color:OTTOMAN});
 D('cairo',null,null,['earlyOttomanAfrica'],mamlukLearning,[
  [1454,1517,L('Каир мамлюкских султанов','Cairo of the Mamluk sultans','Мамлюк султандарынын Каири'),L('Каир остаётся столицей султаната и большим рынком. Вакфы содержат школы, мечети и общественные здания.','Cairo remains the sultanate’s capital and a major market. Endowments maintain schools, mosques and public buildings.','Каир султандыктын борбору жана ири базар бойдон калат. Вакфтар мектептерди, мечиттерди жана коомдук имараттарды камсыздайт.'),null],
  [1517,1601,L('Каир при османском управлении','Cairo under Ottoman rule','Осмон бийлигиндеги Каир'),L('Город сохраняет роль центра Египта, торговли и учёности после утраты статуса столицы самостоятельного султаната.','After losing its role as an independent sultanate’s capital, Cairo remains Egypt’s centre of commerce and learning.','Өз алдынча султандыктын борбору болбой калгандан кийин да Каир Египеттин соода жана илим борбору бойдон калат.'),null]
 ]);

 const maghrebLearning=learn(L('Династический двор, городские элиты и союзы с племенами.','Dynastic court, urban elites and tribal alliances.','Династиялык сарай, шаар төбөлдөрү жана уруулар менен союздар.'),L('Зерно, ремесло, порты и транссахарские связи.','Grain, crafts, ports and trans-Saharan connections.','Дан, кол өнөрчүлүк, порттор жана Сахара аркылуу байланыштар.'),L('Мечети, медресе и суфийские центры связывают город и сельскую округу.','Mosques, madrasas and Sufi centres connect towns and countryside.','Мечиттер, медреселер жана сопулук борборлор шаар менен айылды байланыштырат.'));
 const moroccoNorth=[[-8,32.2],[-6.8,34.8],[-5.4,35.7],[-2.1,35.1],[-1.8,32.5],[-4.5,31.7],[-6.4,31.8]];
 const moroccoSouth=[[-9.8,29.5],[-9.3,32.1],[-8,32.2],[-6.4,31.8],[-4.5,31.7],[-4.3,30.2],[-7,28.9]];
 const moroccoFull=[[-9.8,29.5],[-9.3,32.1],[-6.8,34.8],[-5.4,35.7],[-2.1,35.1],[-1.8,32.5],[-4.3,30.2],[-7,28.9]];
 D('marinid',null,null,['earlyMorocco'],maghrebLearning,[[1454,1465,L('Последние Мариниды','The last Marinids','Акыркы Мариниддер'),L('Власть последнего маринидского султана ограничена придворной борьбой и самостоятельностью местных сил. Восстание в Фесе в 1465 году прекращает династию.','Court rivalry and local autonomy constrain the last Marinid sultan. The 1465 revolt in Fez ends the dynasty.','Сарайдагы күрөш жана жергиликтүү күчтөрдүн өз алдынчалыгы акыркы Маринид султанынын бийлигин чектейт. Фестеги 1465-жылкы көтөрүлүш династияны аяктатат.'),'previous','influence']]);
 D('early-fez',L('Фес · местная власть','Fez · local rule','Фес · жергиликтүү бийлик'),[-5,34.04],['earlyMorocco'],maghrebLearning,[[1465,1472,L('Фес после Маринидов','Fez after the Marinids','Мариниддерден кийинки Фес'),L('После восстания городом правит местная шарифская власть. Ваттасиды овладевают Фесом в 1472 году.','After the revolt Fez has local sharifian rule. The Wattasids take the city in 1472.','Көтөрүлүштөн кийин Фести жергиликтүү шариф бийлиги башкарат. Ваттасиддер шаарды 1472-жылы алат.'),box(-5,34.04,.8,.5),'polity']],{color:'#a58585',kind:'city'});
 D('early-wattasid',L('Султанат Ваттасидов','Wattasid Sultanate','Ваттасид султандыгы'),[-5,34.04],['earlyMorocco'],maghrebLearning,[
  [1472,1524,L('Ваттасиды в Фесе','The Wattasids in Fez','Фестеги Ваттасиддер'),L('Ваттасиды утверждаются в Фесе. Их власть особенно сильна на севере; португальские крепости контролируют отдельные прибрежные пункты.','The Wattasids establish themselves in Fez. Their power is strongest in the north; Portuguese forts control separate coastal positions.','Ваттасиддер Фесте бекемделет. Алардын бийлиги түндүктө күчтүү; португал чептери жээктеги айрым пункттарды кармайт.'),moroccoNorth,'influence'],
  [1524,1549,L('Север против Саадитов','The north and the Saadian challenge','Түндүк жана Саадиддердин күчөшү'),L('После взятия Марракеша Саадиты соперничают с Ваттасидами. Фес переходит к Саадитам в 1549 году; краткое возвращение Ваттасидов в 1554 году не закрепится.','After taking Marrakesh the Saadians challenge the Wattasids. Fez falls in 1549; a brief Wattasid return in 1554 will not last.','Марракешти алгандан кийин Саадиддер Ваттасиддерге атаандашат. Фес 1549-жылы алынат; Ваттасиддердин 1554-жылкы кыска кайтып келиши бекемделбейт.'),moroccoNorth,'polity']
 ],{color:'#a58585'});
 D('early-saadi',L('Саадитский султанат','Saadian Sultanate','Саадид султандыгы'),[-9.4,30.4],['earlyMorocco','earlySonghay'],maghrebLearning,[
  [1509,1524,L('Саадиты в Сусе','The Saadians in the Sous','Сустагы Саадиддер'),L('Саадитское движение формирует власть на юге Марокко и выступает против португальского присутствия.','The Saadian movement builds power in southern Morocco and opposes Portuguese expansion.','Саадид кыймылы Марокконун түштүгүндө бийлик түзүп, португалдардын кеңейишине каршы чыгат.'),[[-9.8,29.5],[-9.4,31],[-7.8,31],[-7,28.9]],'influence',{phase:{approx:true}}],
  [1524,1549,L('Марракеш и южное Марокко','Marrakesh and southern Morocco','Марракеш жана түштүк Марокко'),L('Саадиты занимают Марракеш и расширяют южные владения. В 1541 году они отвоёвывают Агадир у Португалии.','The Saadians take Marrakesh and expand in the south. In 1541 they capture Agadir from Portugal.','Саадиддер Марракешти ээлеп, түштүктө кеңейет. 1541-жылы Агадирди Португалиядан кайтарып алат.'),moroccoSouth,'polity',{phase:{coord:[-7.98,31.63]}}],
  [1549,1578,L('Фес и объединение Марокко','Fez and the unification of Morocco','Фес жана Марокконун биригиши'),L('Взятие Феса усиливает Саадитов. В 1554 году Ваттасиды ненадолго возвращаются с османской поддержкой, но Саадиты восстанавливают власть в том же году.','Taking Fez strengthens Saadian rule. An Ottoman-backed Wattasid restoration in 1554 is reversed by the Saadians within the same year.','Фестин алынышы Саадид бийлигин күчөтөт. 1554-жылы Осмон колдогон Ваттасиддер кыска мөөнөткө кайтып келет, бирок ошол эле жылы Саадиддер бийлигин калыбына келтирет.'),moroccoFull,'polity',{phase:{coord:[-7.98,31.63]}}],
  [1578,1601,L('Ахмад аль-Мансур','Ahmad al-Mansur','Ахмад аль-Мансур'),L('Победа при аль-Каср-аль-Кабире останавливает португальское вторжение. Ахмад аль-Мансур укрепляет султанат и в 1591 году направляет войско против Сонгая.','Victory at al-Qasr al-Kabir stops the Portuguese invasion. Ahmad al-Mansur strengthens the sultanate and sends an army against Songhay in 1591.','Аль-Каср-аль-Кабирдеги жеңиш португал басып кирүүсүн токтотот. Ахмад аль-Мансур султандыкты бекемдеп, 1591-жылы Сонгайга аскер жөнөтөт.'),moroccoFull,'polity',{phase:{coord:[-7.98,31.63]}}]
 ],{color:'#ba9b74'});
 D('zayyanid',null,null,['earlyAlgiers','earlyMorocco'],maghrebLearning,[
  [1454,1516,L('Тлемсен и поздние Зайяниды','Tlemcen and the later Zayyanids','Тлемсен жана соңку Зайяниддер'),L('Тлемсен сохраняет двор и торговые связи. Власть династии не равна контролю над всей территорией современного Алжира.','Tlemcen retains its court and trade connections. Dynastic authority does not cover all of modern Algeria.','Тлемсен сарайын жана соода байланыштарын сактайт. Династиянын бийлиги азыркы Алжирдин бүт аймагын камтыбайт.'),[[-2.1,35.1],[.2,35.7],[1.7,35.2],[1,33.6],[-1.8,32.5]],'influence'],
  [1516,1554,L('Тлемсен между соперниками','Tlemcen between rival powers','Атаандаш күчтөрдүн ортосундагы Тлемсен'),L('Местные претенденты ищут поддержку у испанцев и османов. В 1554 году Зайянидская династия окончательно теряет власть.','Local claimants seek Spanish or Ottoman support. In 1554 the Zayyanid dynasty finally loses power.','Жергиликтүү талапкерлер испандардан же осмондордон колдоо издейт. 1554-жылы Зайянид династиясы бийлигин биротоло жоготот.'),box(-1.32,34.88,.85,.7),'influence']
 ]);
 const algiersCore=[[.1,35.7],[2.7,36.8],[4.5,36.8],[5.4,36.2],[4.3,34.7],[1.8,34.4]];
 const algiersWide=[[-2.1,35.1],[.1,35.7],[2.7,36.8],[4.5,36.8],[7.7,37],[8.2,35.4],[6.8,34.2],[3.2,33.8],[.8,33.1],[-1.8,32.5]];
 D('early-algiers',L('Алжир · османский Магриб','Algiers · Ottoman Maghreb','Алжир · Осмон Магриби'),[3.06,36.75],['earlyAlgiers'],ottomanLearning,[
  [1516,1519,L('Братья Барбаросса в Алжире','The Barbarossa brothers in Algiers','Алжирдеги Барбаросса бир туугандар'),L('Арудж занимает Алжир. После его гибели в 1518 году Хайр ад-Дин укрепляет военную власть и ищет поддержку османского султана.','Aruj takes Algiers. After his death in 1518, Khayr al-Din strengthens military authority and seeks Ottoman support.','Аруж Алжирди ээлейт. Ал 1518-жылы өлгөндөн кийин Хайр ад-Дин аскердик бийликти бекемдеп, Осмон султанынын колдоосун издейт.'),box(3.06,36.55,.8,.4),'influence',{area:{color:'#a68c66'}}],
  [1519,1529,L('Османский союз и борьба за город','Ottoman allegiance and the struggle for the city','Осмонго баш ийүү жана шаар үчүн күрөш'),L('Хайр ад-Дин признаёт османское верховенство. Местное соперничество временно лишает его Алжира; возвращение и взятие испанского Пеньона завершают этот этап к 1529 году.','Khayr al-Din accepts Ottoman sovereignty. Local rivalry temporarily displaces him; his return and capture of the Spanish Peñón complete this phase by 1529.','Хайр ад-Дин Осмондун жогорку бийлигин тааныйт. Жергиликтүү атаандаштык аны шаардан убактылуу кетирет; кайтып келиши жана испан Пеньонунун алынышы бул баскычты 1529-жылы аяктатат.'),box(3.06,36.55,.8,.4),'influence'],
  [1529,1554,L('Османский центр в Алжире','An Ottoman centre at Algiers','Алжирдеги Осмон борбору'),L('Захват Пеньона укрепляет гавань. Алжир становится базой османского флота и региональной власти; горные сообщества сохраняют самостоятельность.','Capturing the Peñón secures the harbour. Algiers becomes an Ottoman naval and regional centre; mountain communities retain autonomy.','Пеньондун алынышы портту бекемдейт. Алжир Осмон флотунун жана аймактык бийликтин борборуна айланат; тоолуу жамааттар өз алдынчалыгын сактайт.'),algiersCore,'influence'],
  [1554,1601,L('Алжир и Тлемсен','Algiers and Tlemcen','Алжир жана Тлемсен'),L('Устранение Зайянидов расширяет османскую сферу на запад. Испанский Оран и автономные горные области не становятся обычными провинциальными землями.','The end of Zayyanid rule extends the Ottoman sphere westward. Spanish Oran and autonomous mountain districts remain distinct.','Зайянид бийлигинин аякташы Осмон таасирин батышка кеңейтет. Испан Ораны жана өз алдынча тоолуу аймактар өзгөчө абалын сактайт.'),algiersWide,'influence']
 ],{kind:'region',color:OTTOMAN});
 const tunis=[[8.2,35.4],[7.7,37],[10.2,37.2],[11.1,35.7],[10,34],[10.6,33.2],[8.7,33],[7.5,34.2]];
 D('hafsid',null,null,['earlyTunis'],maghrebLearning,[
  [1454,1534,L('Поздние Хафсиды в Ифрикии','The later Hafsids in Ifriqiya','Ифрикиянын соңку Хафсиддери'),L('Тунис остаётся центром Хафсидов, а власть над дальними областями ослабевает. Прибрежные города вовлечены в средиземноморскую торговлю и войны.','Tunis remains the Hafsid centre as control over distant provinces weakens. Coastal towns participate in Mediterranean commerce and warfare.','Тунис Хафсиддердин борбору бойдон калат, алыскы облустардагы бийлик алсырайт. Жээк шаарлары Жер Ортолук деңиздеги соодага жана согуштарга катышат.'),tunis,'influence'],
  [1535,1569,L('Хафсиды под испанской защитой','Hafsids under Spanish protection','Испан коргоосундагы Хафсиддер'),L('После похода Карла V Хафсиды возвращаются в Тунис под испанским покровительством. Ла-Гулет удерживает испанский гарнизон.','Charles V’s expedition restores the Hafsids under Spanish protection. A Spanish garrison holds La Goulette.','Карл Vнин жортуулу Хафсиддерди испан коргоосу алдында Туниске кайтарат. Ла-Гулетте испан гарнизону турат.'),tunis,'influence'],
  [1573,1574,L('Последнее восстановление Хафсидов','The final Hafsid restoration','Хафсиддердин акыркы кайтып келиши'),L('Испанский захват города позволяет ненадолго восстановить зависимую Хафсидскую власть. В 1574 году османы берут Тунис окончательно.','The Spanish capture briefly restores dependent Hafsid rule. The Ottomans take Tunis definitively in 1574.','Испандардын шаарды алышы көз каранды Хафсид бийлигин кыска убакытка калыбына келтирет. 1574-жылы осмондор Тунисти биротоло алат.'),tunis,'influence']
 ]);
 D('early-ottoman-tunis',L('Османский Тунис','Ottoman Tunis','Осмон Туниси'),[10.18,36.8],['earlyTunis'],ottomanLearning,[
  [1534,1535,L('Первое османское взятие Туниса','The first Ottoman capture of Tunis','Тунистин Осмон тарабынан биринчи алынышы'),L('Хайр ад-Дин занимает Тунис. В следующем году город будет потерян после экспедиции Карла V.','Khayr al-Din takes Tunis. Charles V’s expedition will reverse the conquest the following year.','Хайр ад-Дин Тунисти алат. Кийинки жылы Карл Vнин жортуулунан соң шаар кайра жоголот.'),tunis,'polity'],
  [1569,1573,L('Новое османское занятие','A renewed Ottoman occupation','Осмондордун кайра ээлеши'),L('Улудж Али занимает Тунис, но испанцы удерживают Ла-Гулет. Борьба за город продолжается.','Uluj Ali takes Tunis while Spain retains La Goulette. The struggle for the city continues.','Улуж Али Тунисти алат, бирок испандар Ла-Гулетти сактайт. Шаар үчүн күрөш уланат.'),tunis,'polity'],
  [1574,1601,L('Тунис в составе Османской державы','Tunis in the Ottoman Empire','Осмон мамлекетинин курамындагы Тунис'),L('Османы берут Тунис и Ла-Гулет. Регион становится османской провинцией со своими военными и административными учреждениями.','The Ottomans take Tunis and La Goulette. The region becomes an Ottoman province with local military and administrative institutions.','Осмондор Тунисти жана Ла-Гулетти алат. Аймак жергиликтүү аскердик жана башкаруу мекемелери бар Осмон облусуна айланат.'),tunis,'polity']
 ],{kind:'region',color:OTTOMAN});
 D('early-tripoli',L('Триполи','Tripoli','Триполи'),[13.19,32.89],['earlyOttomanAfrica','earlyTunis'],ottomanLearning,[
  [1454,1510,L('Триполи и местные власти','Tripoli and local authorities','Триполи жана жергиликтүү бийлик'),L('Порт связывает морскую торговлю с караванами внутренней Африки. Местное управление действует в меняющейся сфере Хафсидов.','The port connects shipping with caravans from inland Africa. Local government operates within the changing Hafsid sphere.','Порт деңиз соодасын Африканын ички аймактарындагы кербендер менен байланыштырат. Жергиликтүү бийлик өзгөрүп турган Хафсид таасиринде иштейт.'),box(13.19,32.6,.8,.4),'influence',{area:{color:'#b7866a'}}],
  [1510,1530,L('Испанский гарнизон Триполи','The Spanish garrison of Tripoli','Триполидеги испан гарнизону'),L('Испанцы захватывают укреплённый порт. Их прибрежный опорный пункт не означает завоевания всей Ливии.','Spain captures the fortified port. Its coastal stronghold does not represent the conquest of all Libya.','Испандар чептүү портту алат. Бул жээктеги таяныч бүт Ливиянын каратылганын билдирбейт.'),box(13.19,32.75,.25,.17),'settlement',{area:{color:'#aaa077'}}],
  [1530,1551,L('Триполи под властью госпитальеров','Tripoli under the Hospitallers','Госпитальерлердин бийлигиндеги Триполи'),L('Карл V передаёт Триполи ордену Святого Иоанна. Гарнизон удерживает порт до османского завоевания.','Charles V transfers Tripoli to the Order of St John. Its garrison holds the port until the Ottoman conquest.','Карл V Триполини Ыйык Иоанн орденине берет. Гарнизон портту Осмон каратканга чейин кармайт.'),box(13.19,32.75,.25,.17),'settlement',{area:{color:'#a69b86'}}],
  [1551,1601,L('Османская провинция Триполи','The Ottoman province of Tripoli','Триполи Осмон облусу'),L('Османское завоевание меняет управление портом. Наместники расширяют связи с племенными властями внутренних районов.','Ottoman conquest changes the port’s government. Governors develop relationships with tribal authorities in the interior.','Осмон каратуусу порттун башкаруусун өзгөртөт. Башкаруучулар ички аймактардагы уруу бийликтери менен байланыштарын кеңейтет.'),[[11.5,32.8],[13.2,33],[15.2,32.3],[15.7,31],[13.4,30.5],[11.6,31.1]],'influence']
 ],{kind:'region',color:OTTOMAN});
 for(const [id,t,x] of [
  ['marrakesh',L('Марракеш при Саадитах','Marrakesh in the Saadian age','Саадид доорундагы Марракеш'),L('Город вновь становится важной столицей при Саадитах. Двор поддерживает медресе, рынки и дворцовое строительство.','The Saadians make the city a major capital again. The court supports madrasas, markets and palace construction.','Саадиддер шаарды кайрадан маанилүү борборго айлантат. Сарай медреселерди, базарларды жана хан сарай курулушун колдойт.')],
  ['kairouan',L('Кайруан в меняющейся Ифрикии','Kairouan in a changing Ifriqiya','Өзгөрүп турган Ифрикиядагы Кайруан'),L('Кайруан сохраняет религиозную и ремесленную жизнь при ослаблении Хафсидов и переходе Ифрикии к османскому управлению.','Kairouan retains religious and craft life as Hafsid authority weakens and Ifriqiya passes to Ottoman rule.','Хафсид бийлиги алсырап, Ифрикия Осмон башкаруусуна өткөндө да Кайруанда диний жана кол өнөрчүлүк турмушу уланат.')]
 ])D(id,null,null,[id==='marrakesh'?'earlyMorocco':'earlyTunis'],maghrebLearning,id==='marrakesh'?[
  [1454,1524,L('Марракеш и местные правители','Marrakesh and local rulers','Марракеш жана жергиликтүү башкаруучулар'),L('Марракеш сохраняет рынки, ремесло и самостоятельную городскую политику при ослаблении северных династий.','Marrakesh retains markets, crafts and a distinct urban political life as the northern dynasties weaken.','Түндүктөгү династиялар алсыраганда Марракеш базарларын, кол өнөрчүлүгүн жана өз алдынча шаар саясатын сактайт.'),null],
  [1524,1601,t,x,null]
 ]:[[1454,1601,t,x,null]]);
 D('ceuta-late',null,null,['lateCeuta','earlyMorocco'],maghrebLearning,[[1454,1601,L('Португальская Сеута','Portuguese Ceuta','Португал Сеутасы'),L('Сеута остаётся португальской крепостью у пролива. После объединения корон в 1580 году город сохраняет португальское управление в монархии Габсбургов.','Ceuta remains a Portuguese fortress by the strait. After the 1580 union of crowns it retains Portuguese administration within the Habsburg monarchy.','Сеута кысыктагы португал чеби бойдон калат. 1580-жылы таажылар бириккенден кийин Габсбург монархиясында португал башкаруусун сактайт.'),'previous','settlement']],{color:PORTUGAL});

 // The Horn: conquest overlays describe military influence, not permanent state
 // boundaries; Oromo communities are cultural regions with no invented route.
 const hornLearning=learn(L('Двор, областные властители и военные союзы.','Court, regional rulers and military alliances.','Сарай, аймактык башкаруучулар жана аскердик союздар.'),L('Высокогорное земледелие, скот и торговые пути к Красному морю.','Highland agriculture, livestock and routes to the Red Sea.','Бийик тоолуу дыйканчылык, мал жана Кызыл деңизге чыккан жолдор.'),L('Христианские и мусульманские общины, монастыри и города.','Christian and Muslim communities, monasteries and towns.','Христиан жана мусулман жамааттары, монастырлар жана шаарлар.'));
 const ethiopiaNorth=[[36,10.5],[38.3,10.3],[39.2,11.7],[39.6,13.9],[38.2,14.7],[36.7,13.4],[35.8,11.8]];
 D('ethiopia',null,null,['earlyHorn','earlyOromo'],hornLearning,[
  [1454,1529,L('Соломонова династия','The Solomonic dynasty','Соломон династиясы'),L('Христианские цари правят высокогорными областями через двор и региональную знать. Отношения с мусульманскими соседями включают торговлю и войны.','Christian kings govern the highlands through the court and regional nobles. Relations with Muslim neighbours include trade and warfare.','Христиан падышалар тоолуу аймактарды сарай жана жергиликтүү төбөлдөр аркылуу башкарат. Мусулман коңшулар менен байланышта соода да, согуш да бар.'),'previous','influence'],
  [1529,1543,L('Война с Ахмадом ибн Ибрахимом','War with Ahmad ibn Ibrahim','Ахмад ибн Ибрахим менен согуш'),L('Войска Ахмада занимают значительную часть высокогорья. Царский двор отступает, а в 1541 году получает португальскую военную помощь.','Ahmad’s forces occupy much of the highlands. The royal court retreats and receives Portuguese military assistance in 1541.','Ахмаддын аскерлери тоолуу аймактын чоң бөлүгүн ээлейт. Падыша сарайы чегинип, 1541-жылы португал аскердик жардамын алат.'),[[36,11.1],[37.1,10.6],[38.1,11.5],[38.5,13],[37.4,14],[36.5,13.2]],'influence'],
  [1543,1559,L('Восстановление царской власти','Restoration of royal authority','Падышалык бийликтин калыбына келиши'),L('После гибели Ахмада при Вайна-Дага Гэлаудэуос восстанавливает власть над значительной частью страны. Войны на востоке продолжаются.','After Ahmad’s death at Wayna Daga, Gelawdewos restores royal authority over much of the country. Warfare continues in the east.','Ахмад Вайна-Дагада өлгөндөн кийин Гэлаудэуос өлкөнүн чоң бөлүгүндө падыша бийлигин калыбына келтирет. Чыгыштагы согуштар уланат.'),ethiopiaNorth,'influence'],
  [1559,1601,L('Северное царство и новые соседи','The northern kingdom and new neighbours','Түндүк падышалык жана жаңы коңшулар'),L('Расширение оромо меняет политическую географию южных областей. Царская власть опирается преимущественно на северные высокогорные центры.','Oromo expansion changes the political geography of southern districts. Royal power relies increasingly on northern highland centres.','Оромонун кеңейиши түштүк аймактардын саясий географиясын өзгөртөт. Падыша бийлиги көбүнчө түндүктөгү тоолуу борборлорго таянат.'),ethiopiaNorth,'influence']
 ]);
 const adalCore=[[41,8.8],[43.3,8.7],[44.1,9.8],[43.6,11.5],[42.7,11.4],[41.7,10.1]];
 D('adal-late',null,null,['earlyHorn','earlyHarar'],hornLearning,[
  [1454,1529,L('Адал и восточные торговые пути','Adal and eastern trade routes','Адал жана чыгыш соода жолдору'),L('Мусульманские правители Адала связывают внутренние районы с портом Зейла. Харар становится важным политическим центром.','Adal’s Muslim rulers connect inland districts with the port of Zeila. Harar becomes an important political centre.','Адалдын мусулман башкаруучулары ички аймактарды Зейла порту менен байланыштырат. Харар маанилүү саясий борборго айланат.'),adalCore,'influence'],
  [1529,1531,L('Походы Ахмада ибн Ибрахима','Ahmad ibn Ibrahim’s campaigns','Ахмад ибн Ибрахимдин жортуулдары'),L('Победа при Шымбра-Куре открывает наступление на христианское высокогорье. Походы сопровождаются разорением и перемещением жителей.','Victory at Shimbra Kure opens the advance into the Christian highlands. Campaigns bring destruction and displacement.','Шымбра-Куредеги жеңиш христиан тоолуу аймагына жылууга жол ачат. Жортуулдар кыйроого жана калктын көчүшүнө алып келет.'),[[38.3,8],[40.5,7.8],[43.4,8.8],[44.1,9.8],[43.6,11.5],[41,10.7],[39,10]],'influence',{phase:{coord:[42.13,9.31]}}],
  [1531,1543,L('Военная сфера Ахмада в высокогорье','Ahmad’s highland military sphere','Ахмаддын тоолуу аймактагы аскердик таасири'),L('Армия Адала занимает широкую часть высокогорья. Здесь показана область военного влияния в ходе войны, завершившейся гибелью Ахмада в 1543 году.','Adal’s army occupies extensive highland areas. This is a wartime sphere of military influence ending with Ahmad’s death in 1543.','Адалдын аскери тоолуу аймактын кең бөлүгүн ээлейт. Бул — Ахмаддын 1543-жылкы өлүмү менен аяктаган согуштагы аскердик таасир аймагы.'),[[37.2,8],[40.5,7.8],[43.4,8.8],[44.1,9.8],[43.6,11.5],[41,11.2],[40.1,14.2],[38.3,14.5],[37.8,12],[37,10]],'influence',{phase:{coord:[42.13,9.31]}}],
  [1543,1577,L('Харар после большой войны','Harar after the great war','Чоң согуштан кийинки Харар'),L('Адал теряет завоёванное высокогорье. Харар сохраняет правителей и укрепления; войны и расширение оромо меняют его окружение.','Adal loses its highland conquests. Harar retains rulers and defences while warfare and Oromo expansion reshape its surroundings.','Адал каратылган тоолуу жерлеринен ажырайт. Харар башкаруучуларын жана чептерин сактайт; согуштар менен оромонун кеңейиши анын айланасын өзгөртөт.'),[[41.5,8.9],[43.1,8.9],[43.4,10.1],[42.4,10.7],[41.3,10]],'influence',{phase:{coord:[42.13,9.31]}}]
 ]);
 D('early-awsa',L('Авса и Харар','Awsa and Harar','Авса жана Харар'),[41.44,11.57],['earlyHarar'],hornLearning,[[1577,1601,L('Перенос политического центра в Авсу','The political centre moves to Awsa','Саясий борбордун Авсага көчүшү'),L('В 1577 году резиденция правителя переносится из Харара в Авсу. Харар продолжает жить как укреплённый мусульманский город.','In 1577 the ruler’s seat moves from Harar to Awsa. Harar continues as a fortified Muslim town.','1577-жылы башкаруучунун ордосу Харардан Авсага көчөт. Харар чептүү мусулман шаары катары жашоосун улантат.'),[box(41.44,11.57,.75,.5),box(42.13,9.31,.4,.3)],'influence']],{color:'#8ea95d'});
 D('early-oromo',L('Общины оромо','Oromo communities','Оромо жамааттары'),[38.8,6.5],['earlyOromo'],learn(L('Система гадаа организует смену поколений и общественную власть.','The gadaa system organizes generational succession and public authority.','Гадаа системасы муундардын алмашуусун жана коомдук бийликти уюштурат.'),L('Скотоводство, земледелие и обмен с соседями.','Herding, farming and exchange with neighbours.','Мал чарбачылыгы, дыйканчылык жана коңшулар менен алмашуу.'),L('Разные группы образуют союзы и включают новые общины.','Different groups form alliances and incorporate new communities.','Ар түрдүү топтор союз түзүп, жаңы жамааттарды кошот.')),[
  [1454,1559,L('Оромо южных высокогорий','Oromo of the southern highlands','Түштүк тоолуу аймактардагы оромо'),L('Оромо участвуют в жизни южных районов задолго до больших перемещений XVI века. Это область общин, а не единое централизованное государство.','Oromo communities are part of southern regional life before the major sixteenth-century movements. This is a community region, not one centralized state.','Оромо жамааттары XVI кылымдагы ири көчүүлөргө чейин эле түштүк аймактарда жашайт. Бул — бирдиктүү борборлошкон мамлекет эмес, жамааттардын аймагы.'),[[36.7,5],[39,4.4],[40.8,5.7],[40.5,7.7],[38.6,8.3],[36.8,7.1]],'cultural',{phase:{approx:true}}],
  [1559,1601,L('Расширение и новые союзы оромо','Oromo expansion and new alliances','Оромонун кеңейиши жана жаңы союздар'),L('Разные группы расширяют присутствие в центральных и восточных областях. Гадаа, союзы и включение соседей участвуют в формировании нового общества.','Different groups expand into central and eastern districts. Gadaa institutions, alliances and incorporation of neighbours shape new communities.','Ар түрдүү топтор борбордук жана чыгыш аймактарга жайылат. Гадаа, союздар жана коңшулардын кошулушу жаңы коомдорду калыптандырат.'),[[35.5,6],[37.5,5],[40,5.4],[42,7.6],[42.4,9.9],[40,10.6],[37.3,9.7],[35.5,8.7]],'cultural',{phase:{coord:[39,8.7],approx:true}}]
 ],{kind:'culture',color:'#a39563'});
 D('lalibela',null,null,['earlyHorn','lateGHA'],hornLearning,[[1454,1601,L('Лалибэла как религиозный центр','Lalibela as a religious centre','Лалибэла диний борбор катары'),L('Скальные церкви сохраняют значение места богослужения и паломничества. История города продолжается после ухода прежней царской династии.','The rock-hewn churches retain their role in worship and pilgrimage. The town’s history continues after its former royal dynasty.','Аскадан оюлган чиркөөлөр сыйынуу жана зыярат жайы бойдон калат. Мурдагы падышалык династия кеткенден кийин да шаардын тарыхы уланат.'),null]]);

 const swahiliLearning=learn(L('Султаны и городские купеческие семьи.','Sultans and urban merchant families.','Султандар жана шаардагы соодагер үй-бүлөлөр.'),L('Морская торговля, земледельческая округа и обмен с внутренней Африкой.','Maritime commerce, surrounding farms and exchange with inland Africa.','Деңиз соодасы, айланадагы дыйканчылык жана ички Африка менен алмашуу.'),L('Суахилийские города, мечети и связи через Индийский океан.','Swahili towns, mosques and Indian Ocean connections.','Суахили шаарлары, мечиттер жана Инди океаны аркылуу байланыштар.'));
 D('kilwa',null,null,['earlySwahili','earlyKilwaFort'],swahiliLearning,[
  [1454,1505,L('Килва и океанская торговля','Kilwa and ocean trade','Килва жана океан соодасы'),L('Килва остаётся суахилийским султанатом и портом. Купцы связывают побережье с золотом внутренних областей и рынками Индийского океана.','Kilwa remains a Swahili sultanate and port. Merchants connect the coast to inland gold and Indian Ocean markets.','Килва суахили султандыгы жана порт бойдон калат. Соодагерлер жээкти ички аймактардын алтыны жана Инди океанынын базарлары менен байланыштырат.'),'previous','polity'],
  [1505,1512,L('Португальский форт в Килве','A Portuguese fort at Kilwa','Килвадагы португал чеби'),L('Экспедиция Франсишку де Алмейды занимает город и строит форт. Португальский гарнизон покинет его в 1512 году.','Francisco de Almeida’s expedition occupies the town and builds a fort. The Portuguese garrison will leave in 1512.','Франсишку де Алмейданын экспедициясы шаарды ээлеп, чеп курат. Португал гарнизону аны 1512-жылы таштап кетет.'),'previous','settlement',{area:{color:PORTUGAL}}],
  [1512,1601,L('Килва после ухода гарнизона','Kilwa after the garrison leaves','Гарнизон кеткенден кийинки Килва'),L('Уход гарнизона возвращает местное управление. Торговля приспосабливается к португальскому контролю отдельных портов и изменению путей.','The garrison’s departure restores local government. Commerce adapts to Portuguese control of selected ports and changing routes.','Гарнизондун кетиши жергиликтүү башкарууну кайтарат. Соода португалдардын айрым портторду кармашына жана жолдордун өзгөрүшүнө ыңгайлашат.'),'previous','polity',{area:{color:'#bc8568'}}]
 ]);
 D('gedi',null,null,['earlySwahili'],swahiliLearning,[[1454,1601,L('Геди в XV–XVI веках','Gedi in the fifteenth and sixteenth centuries','XV–XVI кылымдардагы Геди'),L('Каменный город достигает расцвета и затем сокращается. Его окончательное оставление относится к следующему, XVII веку.','The stone town flourishes and later contracts. Its final abandonment belongs to the following, seventeenth century.','Таш шаар гүлдөп, кийин кичирейет. Анын биротоло ташталышы кийинки XVII кылымга туура келет.'),'previous','settlement']]);
 D('mogadishu-late',null,null,['lateOceanTrade','earlyAfricaV'],swahiliLearning,[[1454,1601,L('Могадишо и города Бенадира','Mogadishu and the Benadir towns','Могадишо жана Бенадир шаарлары'),L('Могадишо сохраняет морские и внутренние торговые связи. Местные мусульманские правители и купцы участвуют в меняющемся мире Индийского океана.','Mogadishu retains maritime and inland trade connections. Local Muslim rulers and merchants participate in a changing Indian Ocean world.','Могадишо деңиз жана ички соода байланыштарын сактайт. Жергиликтүү мусулман башкаруучулар менен соодагерлер өзгөрүп турган Инди океаны дүйнөсүнө катышат.'),'previous','settlement']]);
 D('early-mombasa',L('Момбаса','Mombasa','Момбаса'),[39.67,-4.06],['earlyIndianPorts','earlyAfricaV'],swahiliLearning,[
  [1454,1505,L('Суахилийская Момбаса','Swahili Mombasa','Суахили Момбасасы'),L('Островной город служит центром торговли и местной власти на побережье.','The island town is a centre of coastal commerce and local government.','Аралдагы шаар жээк соодасынын жана жергиликтүү бийликтин борбору.'),box(39.67,-4.06,.28,.25),'polity'],
  [1505,1593,L('Момбаса и борьба за побережье','Mombasa and the struggle for the coast','Момбаса жана жээк үчүн күрөш'),L('Португальские нападения чередуются с восстановлением местной власти. Контроль над морем не означает непрерывной оккупации всех суахилийских городов.','Portuguese attacks alternate with restored local rule. Maritime power does not mean continuous occupation of every Swahili town.','Португал кол салууларынан кийин жергиликтүү бийлик кайра калыбына келет. Деңиздеги күч бардык суахили шаарларынын үзгүлтүксүз ээлеп турушун билдирбейт.'),box(39.67,-4.06,.28,.25),'influence'],
  [1593,1601,L('Строительство форта Иисус','Construction of Fort Jesus','Иисус чебинин курулушу'),L('Португальцы начинают строить форт Иисус в 1593 году. Крепость охраняет гавань и закрепляет военное присутствие в Момбасе.','The Portuguese begin Fort Jesus in 1593. The fortress guards the harbour and consolidates their military presence in Mombasa.','Португалдар Иисус чебин 1593-жылы кура баштайт. Чеп портту коргоп, Момбасадагы аскердик катышууну бекемдейт.'),box(39.67,-4.06,.28,.25),'settlement',{area:{color:PORTUGAL}}]
 ],{kind:'city',color:'#a99070'});
 D('early-mozambique',L('Остров Мозамбик','Island of Mozambique','Мозамбик аралы'),[40.74,-15.04],['earlyIndianPorts','earlyMutapa'],swahiliLearning,[
  [1454,1507,L('Остров на океанских путях','An island on ocean routes','Океан жолдорундагы арал'),L('Местный порт участвует в суахилийских и океанских торговых сетях до появления португальской фактории.','The local port participates in Swahili and oceanic trade networks before the Portuguese trading post.','Жергиликтүү порт португал факториясына чейин суахили жана океан соода тармактарына катышат.'),box(40.74,-15.04,.23,.27),'settlement'],
  [1507,1601,L('Португальская фактория на пути в Индию','A Portuguese trading post on the India route','Индия жолундагы португал факториясы'),L('На острове возникает португальский торговый и морской опорный пункт. Он связывает рейсы в Индию с восточноафриканской торговлей.','A Portuguese commercial and naval post develops on the island. It links voyages to India with East African commerce.','Аралда португал соода жана деңиз таяныч пункту түзүлөт. Ал Индияга каттамдарды Чыгыш Африка соодасы менен байланыштырат.'),box(40.74,-15.04,.23,.27),'settlement',{area:{color:PORTUGAL}}]
 ],{kind:'city',color:'#a99070'});

 const courtLearning=learn(L('Правитель, придворные должности и местные общины.','Ruler, court offices and local communities.','Башкаруучу, сарай кызматтары жана жергиликтүү жамааттар.'),L('Земледелие, ремесло и региональные рынки.','Farming, crafts and regional markets.','Дыйканчылык, кол өнөрчүлүк жана аймактык базарлар.'),L('Ритуал и история династии поддерживают общественные связи.','Ritual and dynastic history sustain social relationships.','Каада-салт жана династиянын тарыхы коомдук байланыштарды сактайт.'));
 D('ife',null,null,['lateIfe','earlyBenin'],courtLearning,[[1454,1601,L('Ифе как сакральный центр','Ife as a sacred centre','Ифе ыйык борбор катары'),L('После расцвета средневековой скульптуры Ифе сохраняет религиозное и династическое значение в мире йоруба.','After the medieval sculptural flowering, Ife retains religious and dynastic importance in the Yoruba world.','Орто кылымдагы айкелчилик гүлдөгөндөн кийин Ифе йоруба дүйнөсүндө диний жана династиялык маанисин сактайт.'),'previous','polity']]);
 D('benin',null,null,['earlyBenin'],courtLearning,[
  [1454,1486,L('Бенин после реформ Эвуаре','Benin after Ewuare’s reforms','Эвуаренин реформаларынан кийинки Бенин'),L('Двор оба расширяет влияние и развивает столицу. Дворцовые мастера работают с латунью, деревом и слоновой костью.','The oba’s court expands its influence and develops the capital. Court artists work in brass, wood and ivory.','Обанын сарайы таасирин кеңейтип, борборду өнүктүрөт. Сарай усталары жез, жыгач жана пил сөөгү менен иштейт.'),'previous','influence'],
  [1486,1504,L('Контакты с португальскими купцами','Contacts with Portuguese merchants','Португал соодагерлери менен байланыш'),L('Португальские купцы устанавливают отношения с Бенином. Двор использует новые торговые возможности, сохраняя самостоятельное управление.','Portuguese merchants establish relations with Benin. The court uses new trading opportunities while retaining independent rule.','Португал соодагерлери Бенин менен байланыш түзөт. Сарай жаңы соода мүмкүнчүлүктөрүн колдонуп, өз алдынча башкарууну сактайт.'),'previous','influence'],
  [1504,1601,L('Бенин Эсигие и его преемников','Benin under Esigie and his successors','Эсигие жана анын мураскерлеринин Бенини'),L('Эсигие укрепляет двор, дипломатию и военную власть. Изображения португальцев входят в придворное искусство, но Бенин не становится португальской колонией.','Esigie strengthens the court, diplomacy and military power. Portuguese figures enter court art, but Benin does not become a Portuguese colony.','Эсигие сарайды, дипломатияны жана аскердик бийликти бекемдейт. Португалдардын элеси сарай искусствосуна кирет, бирок Бенин Португалиянын колониясына айланбайт.'),[[3.9,5.7],[4.1,7.1],[5.6,7.8],[7.1,7.1],[7.3,6],[6.2,5.4],[5.2,5.3]],'influence']
 ]);
 D('kongo-late',null,null,['earlyKongo'],learn(L('Мвенеконго, провинциальные правители и придворные должности.','The mwenekongo, provincial governors and court offices.','Мвенеконго, облустук башкаруучулар жана сарай кызматтары.'),L('Земледелие, ткани, раковины нзимбу и атлантический обмен.','Agriculture, textiles, nzimbu shells and Atlantic exchange.','Дыйканчылык, кездемелер, нзимбу кабырчыктары жана Атлантика алмашуусу.'),L('Христианские и местные традиции взаимодействуют; работорговля вызывает конфликты.','Christian and local traditions interact; slave trading creates conflict.','Христиан жана жергиликтүү салттар өз ара таасир этет; кул соодасы жаңжалдарды жаратат.')),[
  [1454,1491,L('Конго и первые атлантические связи','Kongo and early Atlantic connections','Конго жана алгачкы Атлантика байланыштары'),L('Мбанза-Конго управляет сетью провинций. В 1480-х годах устанавливаются контакты с португальскими мореплавателями.','Mbanza Kongo governs a network of provinces. Contacts with Portuguese navigators begin in the 1480s.','Мбанза-Конго облустардын тармагын башкарат. 1480-жылдары португал деңизчилери менен байланыш түзүлөт.'),'previous','influence'],
  [1491,1601,L('Христианское королевство Конго','The Christian kingdom of Kongo','Христиан Конго падышалыгы'),L('Крещение правителя в 1491 году открывает новую религиозную и дипломатическую эпоху. При Афонсу I развиваются школы и переписка с Португалией; торговля людьми подрывает контроль двора.','The ruler’s baptism in 1491 opens a new religious and diplomatic era. Under Afonso I, schools and correspondence with Portugal develop; slave trading undermines royal control.','Башкаруучунун 1491-жылы чокунушу жаңы диний жана дипломатиялык доорду ачат. Афонсу Iнин тушунда мектептер жана Португалия менен кат алышуу өнүгөт; кул соодасы сарайдын көзөмөлүн начарлатат.'),[[12.4,-5.9],[14.5,-4.9],[16.2,-5.8],[16.5,-7.4],[14.1,-8.7],[12.7,-7.6]],'influence']
 ]);

 const southernLearning=learn(L('Двор и подчинённые вожди связывают отдельные общины.','Court and subordinate chiefs connect separate communities.','Сарай жана баш ийген көсөмдөр өзүнчө жамааттарды байланыштырат.'),L('Скот, земледелие, золото и обмен с побережьем.','Cattle, agriculture, gold and exchange with the coast.','Мал, дыйканчылык, алтын жана жээк менен алмашуу.'),L('Каменная архитектура и ритуал показывают положение правителей.','Stone architecture and ritual express rulers’ status.','Таш архитектура жана каада-салт башкаруучулардын абалын көрсөтөт.'));
 D('zimbabwe',null,null,['earlyZimbabwe'],southernLearning,[[1454,1601,L('Великое Зимбабве после политического расцвета','Great Zimbabwe after its political peak','Саясий гүлдөшүнөн кийинки Улуу Зимбабве'),L('Главные политические центры смещаются, но отдельные части старого города продолжают использоваться. Руины не обозначают прежнюю империю во всём её размере.','Major political centres shift, while parts of the old town remain in use. The site no longer represents the former empire at its height.','Башкы саясий борборлор жылат, бирок эски шаардын айрым бөлүктөрү колдонула берет. Бул жер эми мурдагы империянын эң кең аймагын билдирбейт.'),'previous','settlement']]);
 D('khami-late',null,null,['earlyZimbabwe'],southernLearning,[[1454,1601,L('Кхами и династия Торва','Khami and the Torwa dynasty','Кхами жана Торва династиясы'),L('Кхами развивается как столица Торва. Каменные платформы, ремёсла и импортные предметы показывают власть двора и дальние торговые связи.','Khami develops as the Torwa capital. Stone platforms, crafts and imported goods reveal court power and long-distance exchange.','Кхами Торванын борбору катары өнүгөт. Таш аянтчалар, кол өнөрчүлүк жана сырттан келген буюмдар сарай бийлигин жана алыскы соода байланыштарын көрсөтөт.'),'previous','influence']]);
 D('mutapa-late',null,null,['earlyMutapa','earlyZimbabwe'],southernLearning,[
  [1454,1500,L('Расширение Мвенемутапы','Expansion of Mwenemutapa','Мвенемутапанын кеңейиши'),L('Правители Мвенемутапы укрепляют власть на северо-восточном плато и связи с долиной Замбези.','Mwenemutapa rulers consolidate the northeastern plateau and connections with the Zambezi valley.','Мвенемутапа башкаруучулары түндүк-чыгыш платодогу бийлигин жана Замбези өрөөнү менен байланышын бекемдейт.'),[[29.4,-18.1],[29.9,-15.7],[32.4,-15.5],[34.4,-17],[33.6,-19],[31.1,-19]],'influence',{phase:{approx:true}}],
  [1500,1601,L('Мвенемутапа и португальские торговцы','Mwenemutapa and Portuguese traders','Мвенемутапа жана португал соодагерлери'),L('Золото и слоновая кость связывают двор с побережьем. Португальские торговцы и военные экспедиции усиливают давление, но не превращают всё государство в колонию.','Gold and ivory connect the court to the coast. Portuguese merchants and military expeditions increase pressure without turning the whole state into a colony.','Алтын жана пил сөөгү сарайды жээк менен байланыштырат. Португал соодагерлери жана аскердик экспедициялар кысымды күчөтөт, бирок бүт мамлекет колонияга айланбайт.'),'previous','influence']
 ]);
 D('madagascar',null,null,['earlyMadagascar','lateMadagascar'],learn(L('Местные правители и укреплённые центры, а не единая островная монархия.','Local rulers and fortified centres, not one island monarchy.','Бирдиктүү арал падышалыгы эмес, жергиликтүү башкаруучулар жана чептүү борборлор.'),L('Рис, скотоводство и торговые связи побережья.','Rice, livestock and coastal trading connections.','Күрүч, мал чарбачылыгы жана жээктеги соода байланыштары.'),L('Местные традиции соединяют разные исторические корни населения.','Local traditions connect the population’s varied historical roots.','Жергиликтүү салттар калктын ар түрдүү тарыхый тамырларын байланыштырат.')),[
  [1454,1500,L('Мадагаскар: прибрежные и внутренние общины','Madagascar: coastal and inland communities','Мадагаскар: жээктеги жана ички жамааттар'),L('Остров населяют разные земледельческие и торговые сообщества. Прибрежные поселения участвуют в обмене Индийского океана.','The island has diverse farming and trading communities. Coastal settlements participate in Indian Ocean exchange.','Аралда ар түрдүү дыйкан жана соодагер жамааттар жашайт. Жээк конуштары Инди океанындагы алмашууга катышат.'),'previous','settlement'],
  [1500,1601,L('Укреплённые поселения высокогорья','Fortified highland settlements','Бийик тоолордогу чептүү конуштар'),L('В центральном высокогорье развиваются укреплённые резиденции рова и рисовые террасы. Разные местные правители сохраняют самостоятельность.','Fortified rova residences and rice terraces develop in the central highlands. Different local rulers retain independence.','Борбордук бийик тоолордо рова чептүү ордолору жана күрүч террасалары өнүгөт. Ар башка жергиликтүү башкаруучулар өз алдынчалыгын сактайт.'),[[[47.7,-12.8],[49,-12],[50.4,-14.3],[49.8,-16.9],[47.7,-17],[46.3,-16.7],[47.3,-14.1]],[[46.4,-20.5],[48,-20.5],[48.7,-18.3],[47.6,-17.5],[46.5,-18.2]]],'settlement',{phase:{approx:true}}]
 ]);

 // Located milestones. No inferred migration or military itinerary is drawn.
 E('early-sonni-1464',1464,'gao','state',[-.03,16.28],L('Сонни Али приходит к власти','Sonni Ali takes power','Сонни Али бийликке келет'),L('Начало правления, с которым связано большое расширение Сонгая.','The reign associated with Songhay’s major expansion begins.','Сонгайдын чоң кеңейиши менен байланышкан башкаруу башталат.'),['earlySonghay']);
 E('early-timbuktu-1468',1468,'gao','war',[-3.006,16.773],L('Сонни Али берёт Тимбукту','Sonni Ali takes Timbuktu','Сонни Али Тимбуктуну алат'),L('Тимбукту входит в сонгайскую сферу власти.','Timbuktu enters the Songhay sphere.','Тимбукту Сонгайдын таасирине кирет.'),['earlySonghay']);
 E('early-djenne-1473',1473,'gao','war',[-4.55,13.906],L('Подчинение Дженне','The submission of Djenné','Женненин баш ийиши'),L('Длительная осада заканчивается присоединением города к Сонгаю; в источниках встречается разная датировка этого этапа.','A prolonged siege ends with Djenné’s incorporation into Songhay; sources differ on the precise dating.','Узак курчоо Женненин Сонгайга кошулушу менен аяктайт; булактарда бул баскычтын так датасы айырмаланат.'),['earlySonghay'],{approx:true});
 E('early-askia-1493',1493,'gao','state',[-.03,16.28],L('Начало династии Аския','The Askia dynasty begins','Аския династиясынын башталышы'),L('Мухаммад Туре утверждает новую династию после победы над Сонни Бару.','Muhammad Ture establishes a new dynasty after defeating Sonni Baru.','Мухаммад Туре Сонни Баруну жеңгенден кийин жаңы династияны орнотот.'),['earlySonghay']);
 E('early-tondibi-1591',1591,'gao','war',[-.22,16.63],L('Битва при Тондиби','Battle of Tondibi','Тондиби салгылашы'),L('Марокканское войско наносит поражение Сонгаю. Война приводит к распаду имперской власти и сопротивлению в Денди.','A Moroccan army defeats Songhay. Imperial authority fragments and resistance continues in Dendi.','Марокко аскери Сонгайды жеңет. Империялык бийлик ыдырап, каршылык Дендиде уланат.'),['earlySonghay']);
 E('early-bornu-envoys-1576',1576,'bornu-late','trade',[12.46,13.06],L('Борну и османская дипломатия','Bornu and Ottoman diplomacy','Борну жана Осмон дипломатиясы'),L('Османские документы фиксируют дипломатические связи с маи Идрисом в 1576–1578 годах.','Ottoman documents record diplomatic relations with Mai Idris in 1576–1578.','Осмон документтери 1576–1578-жылдары маи Идрис менен дипломатиялык байланышты каттайт.'),['earlyBornu'],{to:1578});
 E('early-funj-1504',1504,'early-funj','state',[33.57,13.55],L('Начало султаната Сеннар','The beginning of the Sennar Sultanate','Сеннар султандыгынын башталышы'),L('Традиционная дата основания государства Фундж на Голубом Ниле.','The conventional foundation date of the Funj state on the Blue Nile.','Көк Нилдеги Фунж мамлекетинин түзүлүшүнүн салттуу датасы.'),['earlyFunj'],{approx:true});
 E('early-marjdabiq-1516',1516,'early-ottoman-egypt-sham','war',[37.27,36.54],L('Битва при Мардж-Дабике','Battle of Marj Dabiq','Марж Дабык салгылашы'),L('Османы побеждают мамлюков и занимают аш-Шам.','The Ottomans defeat the Mamluks and take al-Sham.','Осмондор мамлюктарды жеңип, аш-Шамды ээлейт.'),['earlyOttomanAfrica']);
 E('early-cairo-1517',1517,'early-ottoman-egypt-sham','war',[31.24,30.04],L('Османское завоевание Египта','Ottoman conquest of Egypt','Египеттин Осмон тарабынан каратылышы'),L('Селим I занимает Каир; Мамлюкский султанат прекращает существование.','Selim I takes Cairo; the Mamluk Sultanate ends.','Селим I Каирди алат; Мамлюк султандыгы аяктайт.'),['earlyOttomanAfrica']);
 E('early-fez-1465',1465,'early-fez','state',[-5,34.04],L('Падение Маринидов','The fall of the Marinids','Мариниддердин кулашы'),L('Восстание в Фесе прекращает власть последнего Маринида.','A revolt in Fez ends the rule of the last Marinid.','Фестеги көтөрүлүш акыркы Мариниддин бийлигин аяктатат.'),['earlyMorocco']);
 E('early-saadi-fez-1549',1549,'early-saadi','war',[-5,34.04],L('Саадиты берут Фес','The Saadians take Fez','Саадиддер Фести алат'),L('Мухаммад аш-Шайх овладевает столицей Ваттасидов.','Muhammad al-Shaykh takes the Wattasid capital.','Мухаммад аш-Шайх Ваттасиддердин борборун ээлейт.'),['earlyMorocco']);
 E('early-alcacer-1578',1578,'early-saadi','war',[-5.89,35],L('Битва при аль-Каср-аль-Кабире','Battle of al-Qasr al-Kabir','Аль-Каср-аль-Кабир салгылашы'),L('Саадитская армия разгромила португальское вторжение. После сражения султаном становится Ахмад аль-Мансур.','The Saadian army defeats the Portuguese invasion. Ahmad al-Mansur becomes sultan after the battle.','Саадид аскери португал басып кирүүсүн жеңет. Салгылаштан кийин Ахмад аль-Мансур султан болот.'),['earlyMorocco']);
 E('early-algiers-1529',1529,'early-algiers','war',[3.06,36.75],L('Взятие Пеньона у Алжира','Capture of the Peñón of Algiers','Алжирдеги Пеньондун алынышы'),L('Хайр ад-Дин устраняет испанскую крепость перед гаванью.','Khayr al-Din removes the Spanish stronghold facing the harbour.','Хайр ад-Дин порттун алдындагы испан чебин алат.'),['earlyAlgiers']);
 E('early-tripoli-1551',1551,'early-tripoli','war',[13.19,32.89],L('Османы берут Триполи','The Ottomans take Tripoli','Осмондор Триполини алат'),L('Гарнизон госпитальеров уступает город османским силам.','The Hospitaller garrison yields the city to Ottoman forces.','Госпитальер гарнизону шаарды Осмон күчтөрүнө өткөрөт.'),['earlyOttomanAfrica']);
 E('early-tunis-1574',1574,'early-ottoman-tunis','war',[10.18,36.8],L('Окончательное османское взятие Туниса','The definitive Ottoman capture of Tunis','Тунистин Осмон тарабынан биротоло алынышы'),L('Османы берут Тунис и Ла-Гулет, прекращая испанское присутствие и зависимую власть Хафсидов.','The Ottomans take Tunis and La Goulette, ending Spanish occupation and dependent Hafsid rule.','Осмондор Тунисти жана Ла-Гулетти алып, испан катышуусун жана көз каранды Хафсид бийлигин аяктатат.'),['earlyTunis']);
 E('early-shimbra-1529',1529,'adal-late','war',[38.8,8.7],L('Битва при Шымбра-Куре','Battle of Shimbra Kure','Шымбра-Куре салгылашы'),L('Победа Ахмада ибн Ибрахима открывает длительную войну за высокогорье. Место отмечено в районе исторического Шэва.','Ahmad ibn Ibrahim’s victory opens a prolonged highland war. The location is shown in the historical Shewa region.','Ахмад ибн Ибрахимдин жеңиши тоолуу аймак үчүн узак согушту ачат. Орун тарыхый Шэва аймагында көрсөтүлгөн.'),['earlyHorn'],{approx:true});
 E('early-waynadaga-1543',1543,'ethiopia','war',[37.5,11.9],L('Битва при Вайна-Дага','Battle of Wayna Daga','Вайна-Дага салгылашы'),L('Эфиопско-португальские силы побеждают; Ахмад ибн Ибрахим погибает. Область события показана у озера Тана.','Ethiopian and Portuguese forces win; Ahmad ibn Ibrahim is killed. The event is located in the Lake Tana region.','Эфиопиялык жана португал күчтөрү жеңет; Ахмад ибн Ибрахим өлөт. Окуя Тана көлүнүн аймагында көрсөтүлгөн.'),['earlyHorn'],{approx:true});
 E('early-awsa-1577',1577,'early-awsa','state',[41.44,11.57],L('Перенос резиденции в Авсу','The court moves to Awsa','Ордонун Авсага көчүшү'),L('Правитель переносит резиденцию из Харара в Авсу.','The ruler transfers his residence from Harar to Awsa.','Башкаруучу ордосун Харардан Авсага көчүрөт.'),['earlyHarar']);
 E('early-kilwa-1505',1505,'kilwa','war',[39.52,-8.96],L('Португальская оккупация Килвы','Portuguese occupation of Kilwa','Килванын португалдар тарабынан ээлеши'),L('Экспедиция Алмейды занимает город и сооружает форт.','Almeida’s expedition occupies the town and constructs a fort.','Алмейданын экспедициясы шаарды ээлеп, чеп курат.'),['earlyKilwaFort']);
 E('early-kilwa-1512',1512,'kilwa','state',[39.52,-8.96],L('Уход гарнизона из Килвы','The garrison leaves Kilwa','Гарнизондун Килвадан кетиши'),L('Португальцы оставляют форт; местные правители продолжают управлять городом.','The Portuguese abandon the fort; local rulers continue governing the town.','Португалдар чепти таштайт; жергиликтүү башкаруучулар шаарды башкарууну улантат.'),['earlyKilwaFort']);
 E('early-mombasa-1593',1593,'early-mombasa','building',[39.68,-4.06],L('Начало строительства форта Иисус','Work begins on Fort Jesus','Иисус чебинин курулушунун башталышы'),L('Начинается строительство крепости для контроля гавани Момбасы.','Construction starts on the fortress controlling Mombasa’s harbour.','Момбасанын портун көзөмөлдөөчү чептин курулушу башталат.'),['earlyIndianPorts']);
 E('early-kongo-1491',1491,'kongo-late','religion',[14.24,-6.27],L('Крещение правителя Конго','The ruler of Kongo is baptized','Конго башкаруучусунун чокунушу'),L('Нзинга Нкуву принимает крещение и имя Жуан. Это начало новой придворной религиозной традиции.','Nzinga Nkuwu is baptized as João. A new courtly religious tradition begins.','Нзинга Нкуву чокунуп, Жуан атын алат. Сарайдагы жаңы диний салт башталат.'),['earlyKongo']);
 E('early-kongo-letter-1526',1526,'kongo-late','trade',[14.24,-6.27],L('Письма Афонсу I в Португалию','Afonso I’s letters to Portugal','Афонсу Iнин Португалияга каттары'),L('Афонсу обсуждает религию, помощь двору и разрушительные последствия неконтролируемой торговли людьми.','Afonso discusses religion, support for his court and the destructive effects of uncontrolled slave trading.','Афонсу динди, сарайга жардамды жана көзөмөлсүз кул соодасынын кыйратуучу кесепеттерин талкуулайт.'),['earlyKongo']);
 E('early-benin-1486',1486,'benin','trade',[5.62,6.34],L('Бенин и португальские купцы','Benin and Portuguese merchants','Бенин жана португал соодагерлери'),L('Устанавливаются торговые отношения, впоследствии отразившиеся в придворном искусстве Бенина.','Trading relations begin and later leave a distinctive mark on Benin court art.','Соода байланыштары түзүлүп, кийин Бениндин сарай искусствосунда өзгөчө из калтырат.'),['earlyBenin']);
 return c;
};
