'use strict';
module.exports=(c,H)=>{
 const {L,phase:P}=H;
 H.source('earlyTonga','Phyllis Herda. The Transformation of the Traditional Tongan Polity (1988); Aletta Biersack. Rivals and Wives: Affinal Politics and the Tongan Ramage. ANU Press.',['https://openresearch-repository.anu.edu.au/handle/1885/114091','https://press-files.anu.edu.au/downloads/press/p63701/html/ch12.html']);
 H.source('earlyMaori','Te Papa Tongarewa. Te Puawaitanga: 1500–1800; Janet Davidson. Archaeological excavations at the Station Bay pā, Motutapu Island. Tuhinga 24, 2013.',['https://collections.tepapa.govt.nz/category/59','https://collections.tepapa.govt.nz/document/5489']);
 H.source('earlyNanm','Federated States of Micronesia. Nan Madol World Heritage Nomination (2015); ICOMOS Evaluation (2016).',['https://whc.unesco.org/uploads/nominations/1503.pdf','https://whc.unesco.org/archive/2016/whc16-40com-inf8B1-en.pdf']);
 H.source('earlyIceland','Sigrún Hannesdóttir. Religious Images and Iconoclasm in Reformation Iceland. Religions 12(6), 428, 2021.',['https://www.mdpi.com/2077-1444/12/6/428']);
 H.source('earlyGuam','Guampedia / Guam Museum. Micronesia Milestones; Ancient CHamoru Fishing Practices; On the Question of Tattoo by Ancestral CHamorus.',['https://www.guampedia.com/timeline/','https://www.guampedia.com/ancient-chamorro-fishing-practices/','https://www.guampedia.com/on-the-question-of-tattoo-by-ancestral-chamorros-2/']);
 H.source('earlySolomon','O. H. K. Spate. The Spanish Lake. Chapter 5: The Southland I — Mendaña and the Bay of the Star. ANU Press.',['https://press-files.anu.edu.au/downloads/press/p66561/html/ch05s03.html']);
 H.source('earlyFrobisher','Royal Museums Greenwich. Martin Frobisher North-West Passage expedition 1576–78.',['https://www.rmg.co.uk/stories/maritime-history/martin-frobisher-north-west-passage-expedition-1576-78']);
 const prior=id=>c.entries.find(e=>e.id===id).phases.find(p=>1453>=p.from&&1453<p.to);
 const carry=(id,title,text,sources=[],options={})=>{
  const p=prior(id);H.continueEntry(id,[P(1454,1601,title||p.title,text||p.text,[...new Set([...p.sources,...sources])],{learning:p.learning,...options})]);H.area(id,1454,1601,'previous');
 };
 // Continued, named local landscapes. No new political borders are implied.
 for(const id of ['budj','kakadu','kuk','mabuyag','palau','samoa','eastpolynesia','rapanui','hawaii','thule'])carry(id);
 carry('antarctica',L('Материк без подтверждённых поселений','Continent without confirmed settlements','Ырасталган конуштары жок материк'),L('В 1454–1600 годах человеческие поселения в Антарктиде не подтверждены. Контур показывает материк.','Human settlement in Antarctica is not established for 1454–1600. The outline shows the continent.','1454–1600-жылдары Антарктидада адам конуштары ырасталган эмес. Контур материкти көрсөтөт.'));
 const n=prior('nanmadol');
 H.continueEntry('nanmadol',[
  P(1454,1500,n.title,n.text,['earlyNanm'],{learning:n.learning}),
  P(1500,1601,L('Нан-Мадол · изменение политического центра','Nan Madol · a changing political centre','Нан-Мадол · саясий борбордун өзгөрүшү'),L('Археология относит прекращение крупного строительства и изменение власти на Понпеи к широкому интервалу XVI — начала XVII века. Каменный комплекс сохраняет обрядовое значение.','Archaeology places the end of major construction and political change on Pohnpei within the broad sixteenth to early seventeenth century interval. The stone complex retains ceremonial importance.','Археология Понпеидеги ири курулуштун токтошу менен бийликтин өзгөрүшүн XVI — XVII кылымдын башындагы кеңири мезгилге таандык кылат. Таш комплекс жөрөлгөлүк маанисин сактайт.'),['earlyNanm'],{learning:{society:L('Предания и материальные памятники сохраняют память о Сауделерах.','Oral traditions and monuments preserve memories of Saudeleur rule.','Оозеки салт жана эстеликтер Сауделер бийлиги тууралуу эс-тутумду сактайт.')}})
 ]);
 H.area('nanmadol',1454,1500,'previous');H.area('nanmadol',1500,1601,'previous',{kind:'settlement'});
 const t=prior('tonga');
 H.continueEntry('tonga',[
  P(1454,1500,t.title,t.text,['earlyTonga','lateTonga'],{learning:{economy:t.learning.economy,society:t.learning.society}}),
  P(1500,1601,L('Тонга · две линии правителей','Tonga · two ruling lines','Тонга · эки башкаруучу тукум'),L('Предания относят разделение власти между сакральным туи-тонга и управляющим туи-хаатакалауа к XV веку. В XVI веке влияние правящих линий сочетается с властью местных вождей.','Traditions place the separation of sacred Tui Tonga authority and governing Tui Haatakalaua authority in the fifteenth century. In the sixteenth century ruling lineages coexist with powerful local chiefs.','Оозеки салт ыйык туи-тонга бийлиги менен башкаруучу туи-хаатакалауа бийлигинин бөлүнүшүн XV кылымга таандык кылат. XVI кылымда башкаруучу тукумдар күчтүү жергиликтүү башчылар менен катар жашайт.'),['earlyTonga'],{learning:{economy:t.learning.economy,society:t.learning.society}})
 ]);
 H.area('tonga',1454,1500,'previous');H.area('tonga',1500,1601,'previous',{kind:'influence',name:L('Тонга · Тонгатапу','Tonga · Tongatapu','Тонга · Тонгатапу')});
 const m=prior('aotearoa');
 H.continueEntry('aotearoa',[
  P(1454,1500,m.title,m.text,m.sources),
  P(1500,1601,L('Те Пуаваитанга · общества маори','Te Puawaitanga · Māori societies','Те Пуаваитанга · маори коомдору'),L('Развиваются местные общины и художественные традиции маори. Поселения, земледелие и рыболовство приспособлены к условиям разных районов; укреплённые па становятся частью обжитого ландшафта.','Māori communities and artistic traditions develop. Settlement, farming and fishing adapt to regional environments; fortified pā form part of the inhabited landscape.','Маори жамааттары жана көркөм салттары өнүгөт. Конуштар, дыйканчылык жана балык уулоо аймактын шартына ыңгайлашат; чептүү па конуштары өздөштүрүлгөн ландшафттын бөлүгүнө айланат.'),['earlyMaori'],{learning:{economy:L('В районе Мотутапу ямы для запасов и кости рыб свидетельствуют о кумаре и морском промысле.','At Motutapu, storage pits and fish remains attest kūmara cultivation and marine harvesting.','Мотутапудагы сактоо чуңкурлары жана балык калдыктары кумара өстүрүүнү жана деңиз промыселин көрсөтөт.'),society:L('Обмен связывает поселения: на Мотутапу привозили обсидиан с других островов.','Exchange links settlements: obsidian reached Motutapu from other islands.','Алмашуу конуштарды байланыштырат: Мотутапуга башка аралдардан обсидиан келген.')}})
 ]);
 H.area('aotearoa',1454,1500,'previous');H.area('aotearoa',1500,1601,'previous',{kind:'settlement'});
 H.entry('early-motutapu','oceania','community',[174.92,-36.77],L('Мотутапу · па','Motutapu · pā','Мотутапу · па'),[
  P(1500,1601,L('Укреплённое поселение','Fortified settlement','Чептүү конуш'),L('Раскопки у Стейшен-Бей показывают переход от открытого поселения к укреплённому комплексу в период примерно 1500–1800 годов. Начало этапа на карте приблизительно.','Excavation at Station Bay shows a transition from an open settlement to fortification within approximately 1500–1800. The mapped start is approximate.','Стейшен-Бейдеги казуулар болжол менен 1500–1800-жылдары ачык конуштан чептүү комплекске өтүүнү көрсөтөт. Картадагы этаптын башы болжолдуу.'),['earlyMaori'])
 ]);H.area('early-motutapu',1500,1601,[[174.87,-36.72],[174.95,-36.72],[174.98,-36.8],[174.88,-36.82]],{kind:'settlement',color:'#928968'});
 const ip=prior('iceland');
 H.continueEntry('iceland',[
  P(1454,1523,ip.title,ip.text,['lateIceland']),
  P(1523,1550,L('Исландия под датско-норвежской короной','Iceland under the Danish-Norwegian crown','Дания-Норвегия таажысынын бийлигиндеги Исландия'),L('После выхода Швеции из Кальмарской унии Исландия остаётся связана с датско-норвежской монархией. Рыбный промысел и морская торговля связывают остров с Европой.','After Sweden leaves the Kalmar Union, Iceland remains within the Danish-Norwegian monarchy. Fishing and maritime trade connect the island to Europe.','Швеция Кальмар униясынан чыккандан кийин Исландия Дания-Норвегия монархиясында калат. Балык промысели жана деңиз соодасы аралды Европа менен байланыштырат.'),['lateIceland','earlyIceland'],{approx:false}),
  P(1550,1601,L('Реформация и власть короны','Reformation and royal authority','Реформация жана таажы бийлиги'),L('После казни епископа Йоуна Арасона в 1550 году сопротивление католической церковной верхушки сломлено. Лютеранское устройство и переход церковных владений усиливают корону.','After Bishop Jón Arason’s execution in 1550, resistance by the Catholic hierarchy is broken. Lutheran institutions and transfers of church property strengthen royal authority.','Епископ Йоун Арасон 1550-жылы өлтүрүлгөндөн кийин католик чиркөөсүнүн жетекчилигинин каршылыгы сынат. Лютерандык түзүлүш жана чиркөө мүлкүнүн өтүшү таажы бийлигин күчөтөт.'),['earlyIceland'],{approx:false})
 ]);for(const [a,b] of [[1454,1523],[1523,1550],[1550,1601]])H.area('iceland',a,b,'previous');
 H.entry('early-guam','oceania','community',[144.76,13.45],L('Гуам · чаморро','Guam · CHamoru communities','Гуам · чаморро жамааттары'),[
  P(1454,1521,L('Морские общины Мариан','Mariana seafaring communities','Мариан деңизчи жамааттары'),L('Общины чаморро живут в прибрежных и внутренних поселениях. Рыболовство, земледелие и мореходство обеспечивают хозяйство и связи между островами.','CHamoru communities inhabit coastal and inland villages. Fishing, farming and skilled seafaring support subsistence and inter-island connections.','Чаморро жамааттары жээктеги жана ички айылдарда жашайт. Балык уулоо, дыйканчылык жана деңизчилик чарба менен аралдар аралык байланышты камсыз кылат.'),['earlyGuam']),
  P(1521,1601,L('Встречи с европейскими кораблями','Encounters with European ships','Европалык кемелер менен жолугушуулар'),L('Экспедиция Магеллана приходит на Марианы в 1521 году. Последующие заходы кораблей не создают постоянной испанской администрации; местные общины продолжают жить на островах.','Magellan’s expedition reaches the Marianas in 1521. Later ship visits do not establish permanent Spanish administration; local communities continue island life.','Магелландын экспедициясы 1521-жылы Мариан аралдарына жетет. Кийинки кеме сапарлары туруктуу испан бийлигин орнотпойт; жергиликтүү жамааттар аралдарда жашоону улантат.'),['earlyGuam'])
 ]);const guam=[[144.63,13.24],[144.71,13.24],[144.87,13.52],[144.89,13.65],[144.77,13.65],[144.64,13.45]];
 H.area('early-guam',1454,1521,guam,{kind:'cultural',color:'#9aa771'});H.area('early-guam',1521,1601,guam,{kind:'cultural',color:'#9aa771'});
 H.entry('early-solomons','oceania','community',[159.5,-8.0],L('Санта-Исабель · Соломоновы острова','Santa Isabel · Solomon Islands','Санта-Исабель · Соломон аралдары'),[
  P(1454,1568,L('Островные поселения','Island settlements','Арал конуштары'),L('Жители острова поддерживают поселения, земледелие и морские связи. Контур показывает район общин Санта-Исабель.','Islanders maintain settlements, agriculture and maritime connections. The outline marks the Santa Isabel community region.','Арал тургундары конуштарды, дыйканчылыкты жана деңиз байланыштарын сактайт. Контур Санта-Исабель жамааттарынын аймагын көрсөтөт.'),['earlySolomon']),
  P(1568,1601,L('Экспедиция Менданьи','Mendaña’s expedition','Менданьянын экспедициясы'),L('В 1568 году испанские корабли Менданьи достигают Санта-Исабель. Встречи, обмен и конфликты с островитянами сопровождают экспедицию; постоянной испанской колонии здесь не возникает.','In 1568 Mendaña’s Spanish ships reach Santa Isabel. Encounters, exchange and conflict with islanders accompany the expedition; no permanent Spanish colony is established here.','1568-жылы Менданьянын испан кемелери Санта-Исабелге жетет. Экспедиция арал тургундары менен жолугушуп, алмашып жана жаңжалдашат; бул жерде туруктуу испан колониясы түзүлбөйт.'),['earlySolomon'])
 ]);const santa=[[158.73,-7.35],[159.23,-7.35],[160.03,-8.25],[159.79,-8.57],[159.34,-8.24],[158.82,-7.74]];H.area('early-solomons',1454,1568,santa,{kind:'settlement',color:'#ad9978'});H.area('early-solomons',1568,1601,santa,{kind:'settlement',color:'#ad9978'});
 H.event('early-guam-1521',1521,'early-guam','culture',[144.76,13.45],L('Магеллан на Марианах','Magellan in the Marianas','Магеллан Мариан аралдарында'),L('Экспедиция встречается с чаморро. На карте отмечен Гуам; точный участок первой высадки обсуждается исследователями.','The expedition encounters CHamoru people. The map marks Guam; scholars debate the precise first landing site.','Экспедиция чаморро эли менен жолугушат. Картада Гуам белгиленген; алгачкы конгон так жер боюнча изилдөөчүлөрдүн пикири ар башка.'),['earlyGuam']);
 H.event('early-solomons-1568',1568,'early-solomons','culture',[159.5,-8],L('Менданья на Соломоновых островах','Mendaña in the Solomon Islands','Менданья Соломон аралдарында'),L('Испанская экспедиция достигает Санта-Исабель и обследует соседние острова.','The Spanish expedition reaches Santa Isabel and explores neighbouring islands.','Испан экспедициясы Санта-Исабелге жетип, коңшу аралдарды изилдейт.'),['earlySolomon']);
 H.event('early-iceland-1550',1550,'iceland','politics',[-20.53,64.13],L('Казнь Йоуна Арасона в Скаульхольте','Execution of Jón Arason at Skálholt','Йоун Арасондун Скаульхольтто өлтүрүлүшү'),L('Гибель епископа и его сыновей становится важным рубежом Реформации в Исландии.','The deaths of the bishop and his sons mark a major turning point in Iceland’s Reformation.','Епископ менен уулдарынын өлүмү Исландиядагы Реформациянын маанилүү бурулушу болот.'),['earlyIceland']);
 H.event('early-frobisher-1576',1576,'thule','culture',[-66.5,62.6],L('Фробишер в арктической Канаде','Frobisher in Arctic Canada','Фробишер Арктикалык Канадада'),L('В поисках северо-западного прохода английская экспедиция достигает Баффиновой Земли и встречается с инуитами. Эти плавания не создают постоянного английского владения.','Seeking a Northwest Passage, the English expedition reaches Baffin Island and encounters Inuit. These voyages do not establish permanent English rule.','Түндүк-батыш өтмөктү издеп, англис экспедициясы Баффин жерине жетип, инуиттерге жолугат. Бул сапарлар туруктуу англис ээлигин түзбөйт.'),['earlyFrobisher']);
 return c;
};
