// Educational expansion: island societies, northern Atlantic and Arctic, 610–1299.
// Regional outlines are schematic archaeological contexts, not modern ethnic borders.
const L=(ru,en,ky)=>[ru,en,ky];
const P=(from,to,period,title,text,sources,learning)=>({from,to,period,title,text,sources,learning});
const K=(government,economy,society)=>({government,economy,society});
module.exports=c=>{
 const arctic=c.regions.find(r=>r.id==='arctic');
 arctic.name=L('Арктика и Северная Атлантика','Arctic and North Atlantic','Арктика жана Түндүк Атлантика');
 arctic.scope=L('Гренландия, Исландия и арктические побережья','Greenland, Iceland and Arctic coasts','Гренландия, Исландия жана Арктика жээктери');
 const src=(id,title,...urls)=>c.sources[id]={title,urls};
 src('samoaMonuments','Helene Martinsson-Wallin. Samoan Archaeology and Cultural Heritage: Monuments and People, Memory and History. Archaeopress, 2016, chapter 2.','https://www.si.edu/object/siris_sil_1079003','https://www.archaeopress.com/ArchaeopressShop/DMS/C41BA6BF9C54481784B166F1AD9D30F8/Martinsson-Wallin%20contents.pdf');
 src('palauEarthworks','Annette Kühlem et al. The Monumental Landscape Transformation of the Island of Babeldaob (Republic of Palau): 3D-documentation and Geoarchaeological Investigations. Journal of Global Archaeology, 2022.','https://publications.dainst.org/journals/joga/article/view/3849','https://publications.dainst.org/journals/joga/article/download/3849/7583');
 src('palauSociety','Jolie Liston. Practical Defensive Features in Palau’s Earthwork Landscape. In: Archaeological Perspectives on Conflict and Warfare in Australia and the Pacific. ANU Press, 2022, chapter 7.','https://press-files.anu.edu.au/downloads/press/n9214/html/ch07.xhtml');
 src('palauTerraces','Palau Historic Preservation Office. Ouballang ra Ngebedech (Ngebedech Terraces). UNESCO Tentative List, 2004.','https://whc.unesco.org/en/tentativelists/1930/');
 src('icelandSettlement','Þingvellir National Park. Settlement of Iceland.','https://www.thingvellir.is/en/education/history/settlement-of-iceland/');
 src('icelandLaw','Þingvellir National Park. Lögberg; Law Council; History.','https://www.thingvellir.is/en/education/history/loegberg/','https://www.thingvellir.is/en/education/history/');
 src('icelandLife','Þingvellir National Park. Centre of Social Life.','https://www.thingvellir.is/en/education/history/centre-of-social-life/');
 src('norseLife','Greenland National Museum & Archives. Arctic Peasants — Norse Greenlanders.','https://en.nka.gl/museum/exhibitions/arctic-peasants-norse-greenlanders/');
 src('tongaHeketa','Geoffrey Clark et al. Stone Tools from the Ancient Tongan State Reveal Prehistoric Interaction Centers in the Central Pacific. PNAS 111, 2014, pp. 10491–10496.','https://pmc.ncbi.nlm.nih.gov/articles/PMC4115531/');
 const learn=(id,fn,extra=[])=>{
  const e=c.entries.find(e=>e.id===id);if(!e)throw new Error('Missing oceanic profile '+id);
  for(const p of e.phases){p.learning=typeof fn==='function'?fn(p):fn;p.sources=[...new Set([...p.sources,...extra])];}
 };
 learn('budj',K(
  L('Родовые общины поддерживают водные сооружения и передают знания о земле.','Kin-based communities maintain waterworks and transmit knowledge of Country.','Уруулук жамааттар суу курулмаларын карап, жер жөнүндөгү билимди өткөрүп берет.'),
  L('Каналы и каменные ловушки позволяют ловить и сохранять угря для питания и обмена.','Channels and stone traps supply eels for food, storage and exchange.','Каналдар менен таш тузактар жылан балыкты тамакка, сактоого жана алмашууга берет.'),
  L('Инженерные навыки соединяются с устными преданиями, плетением и сезонным знанием водоёмов.','Engineering skills accompany oral traditions, weaving and seasonal knowledge of wetlands.','Курулуш өнөрү оозеки салт, өрүү жана суулардын мезгилдик өзгөчөлүктөрүн билүү менен айкалышат.')
 ));
 learn('kakadu',K(
  L('Местные общины связаны с определёнными землями и обрядовыми местами.','Local communities are connected to particular lands and ceremonial places.','Жергиликтүү жамааттар белгилүү жерлер жана жөрөлгө жайлары менен байланышкан.'),
  L('Охота, рыболовство и собирательство используют ресурсы рек, болот и скальных плато.','Hunting, fishing and gathering draw on rivers, wetlands and rocky plateaux.','Аңчылык, балык уулоо жана теримчилик дарыя, саз жана аскалуу платолордун ресурстарын пайдаланат.'),
  L('Наскальное искусство сохраняет сведения о животных, занятиях людей и обрядах.','Rock art records animals, human activities and ceremonies.','Аска сүрөттөрү жаныбарлар, адамдардын иштери жана жөрөлгөлөр жөнүндө маалымат сактайт.')
 ));
 learn('mabuyag',K(
  L('Островные земледельцы совместно преобразуют участки склонов в террасы.','Island cultivators reshape hillsides into agricultural terraces.','Аралдык дыйкандар капталдарды дыйканчылык террасаларына айландырат.'),
  L('На участке Вага-Дагам археоботанические находки указывают на выращивание бананов.','Archaeobotanical evidence at Wagadagam identifies banana cultivation.','Вагадагамдагы археоботаникалык табылгалар банан өстүрүлгөнүн көрсөтөт.'),
  L('Торресов пролив связывает земледельческие традиции Новой Гвинеи и север Австралии.','Torres Strait connects New Guinea’s agricultural traditions with northern Australia.','Торрес кысыгы Жаңы Гвинеянын дыйканчылык салттарын түндүк Австралия менен байланыштырат.')
 ));
 learn('kuk',K(
  L('Общины нагорья организуют обработку участков и обслуживание дренажных канав.','Highland communities organise cultivation and maintain drainage ditches.','Тоолук жамааттар жер иштетүүнү уюштуруп, суу чыгарган арыктарды карайт.'),
  L('Осушение влажных земель поддерживает выращивание клубнеплодов и бананов.','Wetland drainage supports root crops and bananas.','Нымдуу жерлерди кургатуу тамыр азыктарын жана банан өстүрүүнү камсыз кылат.'),
  L('Кук — один из очагов самостоятельного возникновения земледелия; его навыки развивались тысячелетиями.','Kuk is a centre of independent agricultural development, with skills refined over millennia.','Кук — дыйканчылык өз алдынча пайда болгон борборлордун бири; анын ыкмалары миңдеген жылдарда өнүккөн.')
 ));
 learn('dorset',K(
  L('Основу поселений составляют семейные группы; сезонные собрания соединяют соседние общины.','Family groups form settlements; seasonal gatherings connect neighbouring communities.','Конуштардын негизин үй-бүлөлүк топтор түзөт; мезгилдик жыйындар коңшу жамааттарды байланыштырат.'),
  L('Охота на тюленей и моржей сочетается с обменом камнем, медью и метеоритным железом.','Seal and walrus hunting accompanies exchange in stone, copper and meteoritic iron.','Тюлень менен моржго аңчылык таш, жез жана метеориттик темир алмашуу менен айкалышат.'),
  L('Зимние полуземлянки, ряды очагов и резные фигурки показывают бытовую и обрядовую жизнь.','Winter semi-subterranean houses, hearth rows and carvings reveal domestic and ceremonial life.','Кышкы жарым жер төлөлөр, очок катарлары жана оюлган айкелчелер турмушту жана жөрөлгөлөрдү көрсөтөт.')
 ));
 learn('norse',p=>K(
  p.from<1261?L('Ведущую роль играют землевладельцы; с XI века укрепляется значение церковных центров.','Landowners lead the settlements; church centres gain importance from the eleventh century.','Конуштарды жер ээлери жетектейт; XI кылымдан чиркөө борборлорунун мааниси күчөйт.'):L('Поселения признают короля Норвегии; фермы и приходы сохраняют местную роль.','Settlements recognise Norway’s king; farms and parishes retain local roles.','Конуштар Норвегия падышасын тааныйт; чарбалар менен приходдор жергиликтүү ролун сактайт.'),
  L('Скотоводство и шерстяное ремесло дополняются морской охотой; её продукты вывозят в Скандинавию.','Livestock and wool production accompany marine hunting; hunting products reach Scandinavia.','Мал чарбачылыгы жана жүн иштетүү деңиз аңчылыгы менен айкалышат; аңчылык азыктары Скандинавияга жетет.'),
  L('Фермы расположены во фьордах. С XI века церкви дополняют морские связи с христианским Севером Европы.','Farms occupy fjords. From the eleventh century, churches complement seaborne ties with Christian northern Europe.','Чарбалар фьорддордо жайгашкан. XI кылымдан чиркөөлөр христиандык түндүк Европа менен деңиз байланыштарын толуктайт.')
 ),['norseLife']);
 const norseFirst=c.entries.find(e=>e.id==='norse').phases[0];
 norseFirst.title=L('Фермы и атлантическая торговля','Farms and Atlantic trade','Чарбалар жана Атлантика соодасы');
 for(const a of c.areas.filter(a=>a.entry==='norse'&&a.from===985))a.title=norseFirst.title;
 learn('thule',K(
  L('Прибрежные общины объединяют людей для морской охоты и дальних переходов.','Coastal communities organise marine hunting and long-distance movement.','Жээк жамааттары деңиз аңчылыгын жана алыскы көчүүнү уюштурат.'),
  L('Морские животные дают пищу и сырьё; лодки и собачьи упряжки расширяют доступ к ресурсам.','Marine animals provide food and materials; boats and dog sledges extend access to resources.','Деңиз жаныбарлары азык жана материал берет; кайыктар менен ит чана ресурстарга жетүүнү кеңейтет.'),
  L('Каяки, умиаки и тёплая одежда обеспечивают жизнь и передвижение в арктических условиях.','Kayaks, umiaks and warm clothing sustain life and travel in Arctic conditions.','Каяк, умиак жана жылуу кийим Арктикада жашоону жана жол жүрүүнү камсыз кылат.')
 ),['thuleArrival']);
 learn('tonga',p=>K(
  p.from<1200?L('Островные общины развиваются в системе местных вождей и морских связей.','Island communities develop through local leadership and maritime connections.','Арал жамааттары жергиликтүү жетекчилик жана деңиз байланыштары аркылуу өнүгөт.'):L('Линия туи-тонга сосредоточивает власть; ранний монументальный центр находится в Хекета.','The Tuʻi Tonga lineage concentrates authority; Heketa is the early monumental centre.','Туи-Тонга тукуму бийликти топтойт; алгачкы монументалдуу борбор — Хекета.'),
  L('Земледелие сочетается с мореходством. Каменные орудия свидетельствуют о связях между архипелагами.','Farming accompanies seafaring. Stone tools reveal connections between archipelagos.','Дыйканчылык деңизчилик менен айкалышат. Таш куралдар архипелагдар аралык байланышты көрсөтөт.'),
  p.from<1200?L('Навыки плавания поддерживают общение с другими обществами западной Полинезии.','Navigation skills maintain contact with other western Polynesian societies.','Деңизде багыт табуу көндүмдөрү батыш Полинезия коомдору менен байланышты сактайт.'):L('Монументальные сооружения выражают положение правящего рода и способность объединять труд.','Monuments express the ruling lineage’s standing and ability to mobilise labour.','Монументалдуу курулуштар башкаруучу тукумдун ордун жана эмгекти бириктирүү жөндөмүн көрсөтөт.')
 ),['tongaHeketa']);
 const tong=c.entries.find(e=>e.id==='tonga').phases.find(p=>p.from===1200);
 tong.coord=[-175.048,-21.137];
 tong.text=L('В XIII веке Хекета на Тонгатапу становится монументальным центром туи-тонга. Каменные орудия показывают морские связи с Самоа. Расцвет больших гробниц Лапаха относится к следующему этапу.','In the thirteenth century Heketa on Tongatapu becomes a monumental centre of the Tuʻi Tonga. Stone tools show maritime connections with Samoa. The great Lapaha tombs flourish in the following period.','XIII кылымда Тонгатапудагы Хекета Туи-Тонганын монументалдуу борборуна айланат. Таш куралдар Самоа менен деңиз байланышын көрсөтөт. Лапаханын чоң күмбөздөрү кийинки мезгилде гүлдөйт.');
 for(const a of c.areas.filter(a=>a.entry==='tonga'&&a.from===1200)){a.text=tong.text;a.sources=tong.sources;}
 learn('nanmadol',K(
  L('Сауделеры создают церемониальный центр правящей династии на юго-востоке Понпеи.','The Saudeleurs establish a dynastic ceremonial centre in southeastern Pohnpei.','Сауделерлер Понпеинин түштүк-чыгышында династиялык жөрөлгө борборун түзөт.'),
  L('Строители доставляют базальтовые колонны из других частей острова и возводят искусственные островки.','Builders transport basalt columns from elsewhere on the island and construct artificial islets.','Куруучулар аралдын башка бөлүктөрүнөн базальт мамыларды ташып, жасалма аралчаларды курат.'),
  L('Каменные жилые, погребальные и обрядовые комплексы разделяют функции и общественные роли.','Stone residential, burial and ritual complexes distinguish functions and social roles.','Таш турак жайлар, көрүстөн жана жөрөлгө комплекстери милдеттерди жана коомдук ролдорду бөлөт.')
 ));

 c.entries.push({id:'samoa',region:'oceania',kind:'community',coord:[-172.269,-13.743],name:L('Самоа · Палаули','Samoa · Palauli','Самоа · Палаули'),phases:[
  P(610,1100,L('VII–XI века','7th–11th centuries','VII–XI кылымдар'),L('Поселения юга Савайи','Southern Savaiʻi settlements','Савайинин түштүгүндөгү конуштар'),L('В районе Палаули жители обустраивают поселения задолго до возведения большого сооружения Пулемелей. Археологи различают ранний жилой этап и последующее монументальное строительство.','People settle Palauli before the great Pulemelei structure is built. Archaeology distinguishes an early residential phase from later monumental construction.','Палаулиде адамдар чоң Пулемелей курулушуна чейин эле отурукташкан. Археология алгачкы турак жай мезгилин кийинки монументалдуу курулуштан айырмалайт.'),['samoaMonuments'],K(
   L('Поселение состоит из жилых участков островной общины.','Residential areas form an island community.','Турак жай тилкелери аралдык жамаатты түзөт.'),L('Домашние хозяйства готовят пищу в земляных печах.','Households prepare food in earth ovens.','Үй чарбалары жер мештерде тамак даярдайт.'),L('Слои поселения позволяют проследить жизнь людей до появления монумента.','Settlement layers trace daily life before the monument.','Конуш катмарлары монументке чейинки күнүмдүк жашоону көрсөтөт.'))),
  P(1100,1300,L('ок. 1100–1299 · начало строительства','c. 1100–1299 · early construction','болж. 1100–1299 · курулуштун башталышы'),L('Возведение Пулемелей','Building Pulemelei','Пулемелейдин курулушу'),L('В Палаули начинается создание крупной каменной платформы Пулемелей. Исследования относят её строительство к широкому интервалу 1100–1400 годов; в XIII веке показан ранний этап этого процесса.','A major stone platform develops at Pulemelei in Palauli. Research places construction within the broad interval 1100–1400; the thirteenth-century view represents the early part of that process.','Палаулиде Пулемелейдин чоң таш платформасы курула баштайт. Изилдөөлөр курулушту 1100–1400-жылдарга таандык кылат; XIII кылымдагы көрүнүш бул процесстин алгачкы бөлүгүн көрсөтөт.'),['samoaMonuments'],K(
   L('Крупное строительство требует организации труда нескольких групп.','Large-scale building requires coordinated group labour.','Ири курулуш топтордун эмгегин уюштурууну талап кылат.'),L('Каменную платформу окружают жилые площадки и хозяйственные сооружения.','House platforms and domestic features surround the stone monument.','Таш монументти үй аянтчалары жана чарбалык курулмалар курчайт.'),L('Монумент становится частью устроенного людьми ландшафта Палаули.','The monument becomes part of Palauli’s constructed cultural landscape.','Монумент Палаулинин адамдар түзгөн маданий ландшафтынын бөлүгүнө айланат.')))
 ]});
 c.entries.push({id:'palau',region:'oceania',kind:'landscape',coord:[134.493,7.437],name:L('Палау · Бабелдаоб','Palau · Babeldaob','Палау · Бабелдаоб'),phases:[
  P(610,750,L('VII–середина VIII века','7th–mid-8th centuries','VII–VIII кылымдын ортосу'),L('Общества земляных террас','Earthwork societies','Топурак террасалар коомдору'),L('Холмы Бабелдаоба преобразованы в террасы, площадки и рвы. Эти комплексы соединяют жильё, выращивание растений, обряды и выражение общественного положения.','Babeldaob’s hills are reshaped into terraces, platforms and ditches. These complexes combine residence, cultivation, ceremony and displays of social standing.','Бабелдаобдун дөбөлөрү терраса, аянтча жана орлорго айландырылган. Комплекстер турак жайды, өсүмдүк өстүрүүнү, жөрөлгөнү жана коомдук даражаны бириктирет.'),['palauEarthworks','palauSociety','palauTerraces'],K(
   L('Разные комплексы связаны с местными группами и их руководителями.','Distinct complexes are associated with local groups and leaders.','Өзүнчө комплекстер жергиликтүү топтор жана жетекчилер менен байланышкан.'),L('Террасы и водоотводы поддерживают выращивание растений и устойчивость склонов.','Terraces and drainage support cultivation and slope stability.','Террасалар менен суу чыгаргычтар өсүмдүк өстүрүүнү жана капталдардын туруктуулугун камсыз кылат.'),L('Масштаб сооружений делает социальный статус заметным в самом ландшафте.','The scale of earthworks makes social standing visible in the landscape.','Курулуштардын көлөмү коомдук даражаны ландшафтта көрүнүктүү кылат.'))),
  P(750,1250,L('ок. 750–1250','c. 750–1250','болж. 750–1250'),L('Изменение расселения','Changing settlement patterns','Конуштардын өзгөрүшү'),L('После основного этапа строительства использование крупных внутренних комплексов сокращается. Этот длительный переход меняет устройство поселений Палау.','After the main construction period, use of large inland complexes declines. This prolonged transition changes Palau’s settlement pattern.','Негизги курулуш мезгилинен кийин ички аймактагы чоң комплекстерди пайдалануу азаят. Узак өтүү мезгили Палаунун конуш түзүлүшүн өзгөртөт.'),['palauEarthworks'],K(
   L('Прежние центры земляной архитектуры утрачивают часть своего значения.','Older centres of earth architecture lose some of their importance.','Топурак архитектурасынын эски борборлору маанисинин бир бөлүгүн жоготот.'),L('Следы деятельности во внутренних районах становятся менее многочисленными.','Evidence of activity in the island interior becomes less frequent.','Аралдын ички бөлүгүндө ишмердиктин издери сейректейт.'),L('Изменение происходит на протяжении столетий, с разным ритмом на отдельных участках.','Change unfolds over centuries, with local differences in pace.','Өзгөрүү кылымдар бою жүрөт; айрым жерлерде анын ыргагы башкача.'))),
  P(1250,1300,L('ок. 1250–1299','c. 1250–1299','болж. 1250–1299'),L('Прибрежные каменные поселения','Coastal stonework settlements','Жээктеги таш конуштар'),L('Развивается этап каменных поселений. Жилые площадки и террасы всё больше связаны с прибрежными районами Бабелдаоба.','The stonework settlement period develops. House platforms and terraces increasingly relate to Babeldaob’s coastal areas.','Таш конуштар мезгили өнүгөт. Үй аянтчалары менен террасалар Бабелдаобдун жээк аймактарына көбүрөөк байланышат.'),['palauEarthworks'],K(
   L('Поселения образуют местные общественные центры.','Settlements form local community centres.','Конуштар жергиликтүү коомдук борборлорду түзөт.'),L('Обустраиваются прибрежные жилые участки и прилегающие террасы.','Coastal residential areas and adjacent terraces are developed.','Жээктеги турак жай тилкелери жана жанаша террасалар өздөштүрүлөт.'),L('Каменная архитектура постепенно меняет облик поселений.','Stone architecture gradually changes the form of settlements.','Таш архитектура конуштардын көрүнүшүн акырындык менен өзгөртөт.')))
 ]});
 c.entries.push({id:'iceland',region:'arctic',kind:'state',coord:[-21.129,64.256],name:L('Исландия','Iceland','Исландия'),phases:[
  P(870,930,L('ок. 870–930','c. 870–930','болж. 870–930'),L('Заселение Исландии','Settlement of Iceland','Исландиянын отурукташуусу'),L('Переселенцы из Скандинавии и с Британских островов создают хозяйства в Исландии. По мере роста поселений появляются местные собрания для решения споров.','Settlers from Scandinavia and the British Isles establish households in Iceland. Growing settlements develop local assemblies to resolve disputes.','Скандинавия жана Британ аралдарынан көчкөндөр Исландияда чарбаларды түзөт. Конуштар өскөндө талаштарды чечүүчү жергиликтүү жыйындар пайда болот.'),['icelandSettlement'],K(
   L('Местные вожди и окружные собрания организуют общественную жизнь.','Local chieftains and district assemblies organise public affairs.','Жергиликтүү башчылар менен округ жыйындары коомдук иштерди уюштурат.'),L('Переселенцы занимают земли и основывают хозяйства.','Settlers take up land and establish farms.','Көчүп келгендер жер ээлеп, чарбаларды негиздейт.'),L('Морские переселения связывают остров с северной Атлантикой.','Seaborne migration connects the island with the North Atlantic.','Деңиз аркылуу көчүү аралды Түндүк Атлантика менен байланыштырат.'))),
  P(930,1262,L('930–1262','930–1262','930–1262'),L('Исландское народовластие и альтинг','Icelandic Commonwealth and Alþing','Исландиянын эркин коомчулугу жана альтинг'),L('Общее собрание — альтинг — собирается в Тингведлире. Здесь обсуждают законы, рассматривают споры и объявляют решения; остров объединён общим правовым порядком.','The general assembly, the Alþing, meets at Þingvellir. Laws, disputes and rulings are addressed here, connecting the island through a shared legal order.','Жалпы жыйын — альтинг — Тингведлирде чогулат. Бул жерде мыйзамдар, талаштар жана чечимдер каралып, арал жалпы укуктук тартип менен биригет.'),['icelandLaw','icelandLife'],K(
   L('Совет законов и законоговоритель действуют на ежегодном альтинге.','The Law Council and Lawspeaker act at the annual Alþing.','Мыйзам кеңеши жана мыйзам айтуучу жыл сайынкы альтингде иштейт.'),L('Съезд привлекает торговцев, ремесленников и людей, ищущих работу.','The assembly attracts merchants, craftspeople and people seeking work.','Жыйын соодагерлерди, кол өнөрчүлөрдү жана жумуш издегендерди тартат.'),L('Участники живут во временных жилищах; собрание служит обмену новостями и общественным связям.','Participants use temporary lodgings; the gathering circulates news and builds social ties.','Катышуучулар убактылуу жайларда жашайт; жыйын кабар таратып, коомдук байланышты бекемдейт.'))),
  P(1262,1300,L('1262–1299','1262–1299','1262–1299'),L('Признание норвежского короля','Allegiance to Norway’s king','Норвегия падышасын таануу'),L('С 1262 года Исландия переходит под власть норвежской короны. Альтинг продолжает собираться, но его положение в системе власти меняется.','From 1262 Iceland passes under the Norwegian crown. The Alþing continues to meet, with a changed place in the political order.','1262-жылдан Исландия Норвегия таажысынын бийлигине өтөт. Альтинг чогулууну улантат, бирок бийлик тутумундагы орду өзгөрөт.'),['icelandLaw'],K(
   L('Норвежский король становится верховным правителем острова.','Norway’s king becomes the island’s sovereign.','Норвегия падышасы аралдын жогорку башкаруучусу болот.'),L('Хозяйства острова сохраняют связи с морским миром северной Атлантики.','Island households remain connected to the seaborne North Atlantic world.','Аралдын чарбалары Түндүк Атлантиканын деңиз дүйнөсү менен байланышын сактайт.'),L('Тингведлир остаётся местом собраний при новом политическом устройстве.','Þingvellir remains an assembly place under the new political arrangement.','Тингведлир жаңы саясий түзүлүштө жыйын өткөрүүчү жай бойдон калат.')))
 ]});
 const A=(entry,from,to,kind,color,polygons,name)=>{
  const e=c.entries.find(e=>e.id===entry),p=e.phases.find(p=>p.from<=from&&p.to>from);
  c.areas.push({id:entry+'-'+from,entry,from,to,kind,color,polygons,points:polygons[0],name:name||e.name,title:p.title,text:p.text,sources:p.sources,approx:true,geometry:'schematic-regional-outline'});
 };
 const palauli=[[[-172.36,-13.84],[-172.16,-13.84],[-172.16,-13.65],[-172.36,-13.65]]];
 A('samoa',610,1100,'settlement','#b3a775',palauli);
 A('samoa',1100,1300,'settlement','#b69a61',palauli,L('Палаули · Пулемелей','Palauli · Pulemelei','Палаули · Пулемелей'));
 const babeldaob=[[[134.43,7.34],[134.61,7.36],[134.68,7.57],[134.64,7.74],[134.49,7.66],[134.43,7.49]]];
 A('palau',610,750,'landscape','#a49470',babeldaob);
 A('palau',750,1250,'landscape','#aaa184',babeldaob);
 A('palau',1250,1300,'settlement','#a2ae86',[[[134.43,7.34],[134.61,7.36],[134.6,7.48],[134.48,7.49]]],L('Палау · прибрежные поселения','Palau · coastal settlements','Палау · жээк конуштары'));
 A('iceland',870,930,'settlement','#a49f83',[[[-24.1,64],[-22.6,63.3],[-20,63.4],[-20.7,65.2],[-23.8,65.8]]]);
 const island=[[[-24.6,63.5],[-21,63.3],[-16.1,63.7],[-13.4,65.1],[-14.5,66.7],[-20.5,66.7],[-24.8,66.1]]];
 A('iceland',930,1262,'polity','#a5a584',island,L('Исландское народовластие','Icelandic Commonwealth','Исландиянын эркин коомчулугу'));
 A('iceland',1262,1300,'polity','#9b8195',island,L('Исландия · Норвежская корона','Iceland · Norwegian crown','Исландия · Норвегия таажысы'));
 const E=(id,year,from,to,entry,kind,title,text,sources,approx=false)=>{const e=c.entries.find(e=>e.id===entry);c.events.push({id,year,from,to,entry,kind,region:e.region,coord:e.coord,title,text,sources,approx});};
 E('iceland-althing',930,930,930,'iceland','politics',L('Учреждение альтинга в Тингведлире','Establishment of the Alþing at Þingvellir','Тингведлирде альтингдин түзүлүшү'),c.entries.find(e=>e.id==='iceland').phases[1].text,['icelandSettlement','icelandLaw']);
 E('iceland-norway',1262,1262,1262,'iceland','diplomacy',L('Исландия признаёт норвежскую корону','Iceland accepts the Norwegian crown','Исландия Норвегия таажысын тааныйт'),c.entries.find(e=>e.id==='iceland').phases[2].text,['icelandLaw']);
 // Construction ranges wider than 1299 stay in prose; event ranges fit this atlas interval.
 E('pulemelei-construction',1100,1100,1299,'samoa','politics',L('Начало монументального строительства Пулемелей','Early monumental construction at Pulemelei','Пулемелейдеги монументалдуу курулуштун башталышы'),c.entries.find(e=>e.id==='samoa').phases[1].text,['samoaMonuments'],true);
 return c;
};
