// Educational additions checked against archaeology and institutional publications.
// Regional outlines locate documented centres; they are not surveyed state borders.
const L=(ru,en,ky)=>[ru,en,ky];
module.exports=c=>{
 const source=(id,title,...urls)=>c.sources[id]={title,urls};
 source('beninArchaeology','Caleb Folorunso et al. MOWAA Archaeology Project: enhancing understanding of Benin City’s historic urban development and heritage through pre-construction archaeology. Antiquity 100 (409), 2026.','https://doi.org/10.15184/aqy.2025.10189');
 source('beninDynasty','Yemisi Shyllon Museum of Art, Pan-Atlantic University. 11 Facts You Need to Know About Benin Art.','https://artsandculture.google.com/incognito/story/iAXxMDvz38PV8Q');
 source('gaoExcavation','Mamadou Cissé et al. Excavations at Gao Saney: New Evidence for Settlement Growth, Trade, and Interaction on the Niger Bend in the First Millennium CE. Journal of African Archaeology 11 (1), 2013, pp. 9–37.','https://doi.org/10.3213/2191-5784-10233');
 source('gaoPalace','Shoichiro Takezawa and Mamadou Cissé. Discovery of the earliest royal palace in Gao and its implications for the history of West Africa. Cahiers d’études africaines 208, 2012, pp. 813–844.','https://journals.openedition.org/etudesafricaines/17167');
 source('gaoRoyalDiscovery','Soichiro Takezawa and Mamadou Cissé. The First Discovery of the Royal Palace of “Medieval” West Africa. Journal of African Studies 73, 2008, pp. 31–46.','https://www.jstage.jst.go.jp/article/africa1964/2008/73/2008_73_31/_article');
 source('gediHeritage','UNESCO. The Historic Town and Archaeological Site of Gedi.','https://whc.unesco.org/en/list/1720');
 source('swahiliDevelopment','V. V. Matveiev. The development of Swahili civilization. In D. T. Niane (ed.), General History of Africa IV: Africa from the Twelfth to the Sixteenth Century. UNESCO, 1984, chapter 18.','https://unesdoc.unesco.org/in/rest/annotationSVC/DownloadWatermarkedAttachment/attach_import_e8290e53-1c69-4eee-83ac-fe9540a692fb?_=184287engo.pdf&from=479&to=504');
 source('sossoMemory','UNESCO. Cultural space of Sosso-Bala.','https://ich.unesco.org/en/RL/cultural-space-of-sosso-bala-00009');
 source('maliFormation','Ann Kordas et al. World History, Volume 1: to 1500. Section 15.2, Medieval Sub-Saharan Africa. OpenStax / Rice University, 2023.','https://openstax.org/books/world-history-volume-1/pages/15-2-medieval-sub-saharan-africa');
 const phase=(from,to,title,text,sources,learning)=>({from,to,period:L('ок. '+from+'–'+(to===1300?'1299':to),'c. '+from+'–'+(to===1300?'1299':to),'болж. '+from+'–'+(to===1300?'1299':to)),title,text,sources,...(learning?{learning}:{})});
 const add=(id,kind,coord,name,phases)=>c.entries.push({id,region:'africa',kind,coord,name,phases});
 add('benin','state',[5.62,6.34],L('Царство Бенин','Kingdom of Benin','Бенин падышалыгы'),[
  phase(1200,1300,L('Царский центр народа эдо','An Edo royal centre','Эдо элинин падышалык борбору'),L('Около 1200 года Бенин становится центром царства эдо. Раскопки выявляют ранние слои городской и дворцовой застройки XIII–XIV веков. На карте отмечены Бенин-Сити и ближайшая округа.','Around 1200 Benin emerges as an Edo royal centre. Excavations reveal early urban and palace layers of the thirteenth–fourteenth centuries. The map locates Benin City and its immediate surroundings.','Болжол менен 1200-жылы Бенин эдо падышалыгынын борборуна айланат. Казуулар XIII–XIV кылымдардагы шаар жана сарай катмарларын ачат. Картада Бенин-Сити жана анын жакынкы аймагы белгиленген.'),['beninArchaeology','beninDynasty'],{
   government:L('Династическая традиция связывает начало власти оба с Эвекой I.','Dynastic tradition associates the beginning of the oba dynasty with Eweka I.','Династиялык салт оба бийлигинин башталышын Эвека I менен байланыштырат.'),
   society:L('Население эдо; царский двор становится центром политической жизни.','An Edo population; the royal court becomes a focus of political life.','Эдо калкы; падыша сарайы саясий турмуштун борборуна айланат.')})]);
 add('gao','city',[-.03,16.28],L('Гао · Кавкав','Gao · Kawkaw','Гао · Кавкав'),[
  phase(700,900,L('Поселения и торговля на Нигере','Settlement and trade on the Niger','Нигердеги конуштар жана соода'),L('С VIII века Гао-Саней развивается как поселение ремесленников и торговцев. Находки стеклянных бус и меди показывают связи через Сахару.','From the eighth century Gao Saney develops as a settlement of craftspeople and traders. Glass beads and copper reveal connections across the Sahara.','VIII кылымдан Гао-Саней кол өнөрчүлөрдүн жана соодагерлердин конушу катары өсөт. Айнек шурулар жана жез Сахара аркылуу байланыштарды көрсөтөт.'),['gaoExcavation'],{
   economy:L('Ремесленные мастерские, речной обмен и дальняя торговля.','Craft workshops, river exchange and long-distance trade.','Кол өнөрчүлүк устаканалары, дарыя аркылуу алмашуу жана алыскы соода.'),
   society:L('Жилые кварталы и мастерские образуют разные части поселения.','Homes and workshops occupy distinct parts of the settlement.','Турак жайлар менен устаканалар конуштун өзүнчө бөлүктөрүндө жайгашат.') }),
  phase(900,1100,L('Царский и торговый центры','Royal and trading centres','Падышалык жана соода борборлору'),L('В X веке Гао объединяет царский центр и торговое поселение. Каменные здания Гао-Ансьен исследователи связывают с резиденцией правителя.','In the tenth century Gao combines a royal centre and a trading settlement. Researchers interpret stone buildings at Gao Ancien as a ruler’s residence.','X кылымда Гао падышалык борбор менен соода конушун бириктирет. Изилдөөчүлөр Гао-Ансьендеги таш имараттарды өкүмдардын резиденциясы деп чечмелейт.'),['gaoPalace','gaoExcavation'],{
   government:L('Арабские географы описывают царство Кавкав.','Arabic geographers describe the kingdom of Kawkaw.','Араб географтары Кавкав падышалыгын сүрөттөйт.') }),
  phase(1100,1300,L('Гао и мусульманские династии','Gao and Muslim dynasties','Гао жана мусулман династиялары'),L('Арабские надгробные надписи XI–XIII веков сохраняют имена местных мусульманских правителей. Гао остаётся важным городским узлом Нигера.','Arabic funerary inscriptions of the eleventh–thirteenth centuries preserve names of local Muslim rulers. Gao remains an important urban node on the Niger.','XI–XIII кылымдардагы араб мүрзө жазуулары жергиликтүү мусулман өкүмдарлардын ысымдарын сактайт. Гао Нигердеги маанилүү шаардык түйүн бойдон калат.'),['gaoPalace'])]);
 add('gedi','city',[40.018,-3.307],L('Геди','Gedi','Геди'),[
  phase(900,1200,L('Суахилийское поселение побережья','A Swahili coastal settlement','Жээктеги суахили конушу'),L('С X века Геди входит в сеть поселений восточноафриканского побережья. Морская торговля связывает местные общества с портами Индийского океана.','From the tenth century Gedi belongs to the East African coastal settlement network. Maritime trade connects local societies with Indian Ocean ports.','X кылымдан Геди Чыгыш Африка жээгиндеги конуштар тармагына кирет. Деңиз соодасы жергиликтүү коомдорду Инди океанынын порттору менен байланыштырат.'),['gediHeritage'],{
   society:L('Городская культура суахили развивается на африканском побережье.','Swahili urban culture develops on the African coast.','Суахили шаар маданияты Африка жээгинде өнүгөт.') }),
  phase(1200,1300,L('Город в торговле Индийского океана','A town in Indian Ocean trade','Инди океанынын соодасындагы шаар'),L('В XIII веке Геди участвует в морском обмене. Привозная керамика, включая селадон, связывает его с торговыми путями Персидского залива и Азии.','In the thirteenth century Gedi participates in maritime exchange. Imported ceramics, including celadon, connect it with Persian Gulf and Asian trade networks.','XIII кылымда Геди деңиз соодасына катышат. Сырттан келген керамика, анын ичинде селадон, аны Перс булуңунун жана Азиянын соода тармактары менен байланыштырат.'),['swahiliDevelopment','gediHeritage'],{
   economy:L('Прибрежная торговля и импорт керамики из дальних регионов.','Coastal trade and ceramics imported from distant regions.','Жээк соодасы жана алыскы аймактардан келген керамика.') })]);
 const area=(id,from,to,kind,color,points,name)=>{
  const e=c.entries.find(e=>e.id===id),p=e.phases.find(p=>p.from<=from&&p.to>from);
  c.areas.push({id:id+'-'+from,entry:id,from,to,kind,color,points,polygons:[points],name:name||e.name,title:p.title,text:p.text,sources:p.sources,approx:true,geometry:'schematic-regional-outline'});
 };
 area('benin',1200,1300,'polity','#b78c61',[[5.25,6.09],[5.38,6.65],[5.81,6.71],[6.01,6.31],[5.79,6.04]]);
 area('gao',700,900,'settlement','#b8a379',[[-.2,16.06],[.22,16.07],[.27,16.46],[-.15,16.49]]);
 area('gao',900,1100,'polity','#ad9266',[[-.45,15.92],[.29,15.93],[.48,16.37],[.2,16.68],[-.39,16.55]],L('Гао · царское ядро','Gao · royal core','Гао · падышалык өзөк'));
 area('gao',1100,1300,'settlement','#b8a379',[[-.45,15.92],[.29,15.93],[.48,16.37],[.2,16.68],[-.39,16.55]],L('Гао · городской узел','Gao · urban node','Гао · шаардык түйүн'));
 area('gedi',900,1200,'settlement','#b59b7f',[[39.96,-3.38],[40.07,-3.38],[40.07,-3.25],[39.96,-3.25]]);
 area('gedi',1200,1300,'settlement','#b78d70',[[39.96,-3.38],[40.07,-3.38],[40.07,-3.25],[39.96,-3.25]]);
 const event=(id,year,entry,coord,title,text,sources,kind='politics')=>c.events.push({id,from:year,to:year,year,approx:true,region:'africa',kind,entry,coord,title,text,sources});
 event('gao-royal-centre',900,'gao',[-.03,16.28],L('Рост царского центра Гао','Growth of Gao’s royal centre','Гаонун падышалык борборунун өсүшү'),L('Около начала X века в Гао-Ансьен возводятся крупные каменные здания, связанные исследователями с царской властью.','Around the beginning of the tenth century, large stone buildings interpreted as royal structures appear at Gao Ancien.','X кылымдын башына жакын Гао-Ансьенде изилдөөчүлөр падыша бийлиги менен байланыштырган ири таш имараттар курулат.'),['gaoRoyalDiscovery']);
 event('benin-royal-centre',1200,'benin',[5.62,6.34],L('Становление царства Бенин','Emergence of the Benin kingdom','Бенин падышалыгынын калыптанышы'),L('Начало царства Бенин принято относить примерно к 1200 году; его центром становится город народа эдо.','The Benin kingdom is conventionally dated from around 1200, with its centre in the Edo city.','Бенин падышалыгынын башталышы болжол менен 1200-жылга таандык; анын борбору эдо шаары болот.'),['beninArchaeology']);
 event('sosso-defeat',1235,'mali',[-9.7,12.3],L('Сундиата побеждает Сосо','Sunjata defeats Sosso','Сундиата Сосону жеңет'),L('Около 1235 года союз земель манден во главе с Сундиатой побеждает Сосо. Победа открывает путь росту Мали. На карте обозначен Манден.','Around 1235 a Manden alliance under Sunjata defeats Sosso, opening the way for Mali’s growth. The map marks the Manden region.','Болжол менен 1235-жылы Сундиата жетектеген манден жерлеринин союзу Сосону жеңет. Жеңиш Малинин өсүшүнө жол ачат. Картада Манден аймагы белгиленген.'),['maliFormation','sossoMemory'],'war');
 const mali=c.entries.find(e=>e.id==='mali');
 mali.phases[0].learning={
  government:L('В 1230-х годах Сундиата объединяет земли манден; победа над Сосо относится примерно к 1235 году.','During the 1230s Sunjata unites Manden territories; the victory over Sosso is dated to approximately 1235.','1230-жылдары Сундиата манден жерлерин бириктирет; Сосону жеңүү болжол менен 1235-жылга таандык.'),
  society:L('Память о Сумаоро Канте и Сундиате сохраняют поколения гриотов.','Generations of griots preserve accounts of Sumaoro Kanté and Sunjata.','Гриоттордун муундары Сумаоро Канте менен Сундиата тууралуу баяндарды сактайт.')};
 mali.phases[0].sources=[...new Set([...mali.phases[0].sources,'maliFormation','sossoMemory'])];
 const kilwa=c.entries.find(e=>e.id==='kilwa');
 for(const p of kilwa.phases.filter(p=>p.from>=1200))p.learning={
  economy:L('Золото и слоновая кость внутренних земель обмениваются на товары Индийского океана.','Hinterland gold and ivory are exchanged for Indian Ocean goods.','Ички аймактардын алтыны менен пил сөөгү Инди океанынын товарларына алмаштырылат.'),
  society:L('Килва чеканит собственные монеты; мечети формируют городской центр.','Kilwa mints its own coins; mosques shape the urban centre.','Килва өз тыйындарын чыгарат; мечиттер шаар борборун түзөт.')};
 const mapungubwe=c.entries.find(e=>e.id==='mapungubwe');
 for(const p of mapungubwe.phases)p.learning={
  government:L('Правящая элита живёт на холме отдельно от остальных жителей.','The ruling elite lives on the hill apart from other residents.','Башкаруучу катмар башка тургундардан өзүнчө дөбөдө жашайт.'),
  economy:L('Золото и слоновая кость связывают внутренние земли с торговлей через восточное побережье.','Gold and ivory connect the interior with trade through the eastern coast.','Алтын менен пил сөөгү ички аймактарды чыгыш жээк аркылуу соодага байланыштырат.')};
 return c;
};
