// Editorial expansion, 610–1299 CE. Approximate periods are not exact founding dates.
const L=(ru,en,ky)=>[ru,en,ky];
module.exports=c=>{
const src=(id,title,url)=>c.sources[id]={title,urls:[url]};
src('mayaPolitics','James Doyle. A Maya Game of Thrones and Artistic Innovation in Golden Kingdoms. Metropolitan Museum of Art, 2018.','https://www.metmuseum.org/pt/perspectives/golden-kingdoms-calakmul-palenque-maya-game-of-thrones');
src('quirigua','Matthew G. Looper. New Perspectives on the Late Classic Political History of Quirigua, Guatemala. Ancient Mesoamerica 10, 1999.','https://www.cambridge.org/core/journals/ancient-mesoamerica/article/abs/new-perspectives-on-the-late-classic-political-history-of-quirigua-guatemala/9A982EE91C0D4963789ACE976CFEE096');
src('hohokam','National Park Service. The Ancestral Sonoran Desert People.','https://www.nps.gov/cagr/learn/historyculture/the-ancestral-sonoran-desert-people.htm');
src('paquime','INAH. Estudio genético descarta la inmigración a gran escala como causa del auge de Paquimé, 2025.','https://www.inah.gob.mx/boletines/estudio-genetico-descarta-la-inmigracion-a-gran-escala-como-causa-del-auge-de-paquime');
src('effigy','National Park Service. Effigy Mounds: Archeology.','https://www.nps.gov/efmo/learn/historyculture/archeology.htm');
src('caribbean','Metropolitan Museum of Art. Central America and the Caribbean, 1000–1400 A.D.; Arte del mar: Artistic Exchange in the Caribbean.','https://82nd-and-fifth.metmuseum.org/toah/ht/07/cac.html');
src('vinland','Margot Kuitems et al. Evidence for European presence in the Americas in AD 1021. Nature 601, 2022, pp. 388–391.','https://www.nature.com/articles/s41586-021-03972-8');
src('norse','National Museum of Denmark. Prehistory of Greenland: Norse.','https://natmus.dk/organisation/forskning-og-kulturarv/nyere-tid-og-verdens-kulturer/etnografisk-samling/arktisk-forskning/prehistory-of-greenland/norse/');
src('dorset','National Museum of Denmark. Prehistory of Greenland: Late Dorset.','https://natmus.dk/organisation/forskning-og-kulturarv/nyere-tid-og-verdens-kulturer/etnografisk-samling/arktisk-forskning/prehistory-of-greenland/late-dorset/');
src('thule','National Museum of Denmark. Prehistory of Greenland: Thule.','https://natmus.dk/organisation/forskning-og-kulturarv/nyere-tid-og-verdens-kulturer/etnografisk-samling/arktisk-forskning/prehistory-of-greenland/thule/');
src('marajoPolitics','Denise Pahl Schaan. The Camutins Chiefdom: Rise and Development of Social Complexity on Marajó Island, Brazilian Amazon. University of Pittsburgh, 2004.','https://d-scholarship.pitt.edu/9161/');
src('muisca','Universidad Pedagógica y Tecnológica de Colombia. Parque Museo Arqueológico de Tunja: periodización Herrera, Muisca Temprano y Muisca Tardío.','https://dsp.uptc.edu.co/sitio/portal/sitios/universidad/vic_inv_ext/ext_univ/unidades/redmuseos/muartun/');
src('northAndes','Metropolitan Museum of Art. Northern Andes, 1000–1400 A.D.','https://82nd-and-fifth.metmuseum.org/toah/ht/07/san.html');
src('sanAgustin','UNESCO. San Agustín Archaeological Park.','https://whc.unesco.org/en/list/744/');
src('pitren','Museo Chileno de Arte Precolombino. Olla-challa Pitrén, 400–1000 DC.','https://museo.precolombino.cl/olla-challa-pitren/');
src('vergel','Comisión Verdad Histórica y Nuevo Trato. Informe, Parte I: historia de los pueblos indígenas. Biblioteca Nacional de Chile.','https://www.memoriachilena.gob.cl/602/articles-122901_recurso_7.pdf');
src('kairouan','UNESCO. Kairouan.','https://whc.unesco.org/en/list/499/');
src('marrakesh','UNESCO. Medina of Marrakesh.','https://whc.unesco.org/en/list/331/');
src('cairo','UNESCO. Historic Cairo.','https://whc.unesco.org/en/list/89/');
src('nubiaTreaty','Geoffrey Khan. Arabic Documents from Medieval Nubia. Open Book Publishers, 2021.','https://tile.loc.gov/storage-services/master/gdc/gdcebookspublic/20/21/38/88/69/2021388869/2021388869.pdf');
src('ethiopia','Metropolitan Museum of Art. African Christianity in Ethiopia.','https://www.metmuseum.org/fr/essays/african-christianity-in-ethiopia');
src('kanem','OpenStax / Rice University. World History, Volume 2, §3.4: The Trans-Saharan Slave Trade — The Role of Kanem-Bornu.','https://openstax.org/books/world-history-volume-2/pages/3-4-the-trans-saharan-slave-trade');
src('ife','British Museum. Figure, Ife; collection Af1959,20.1.','https://www.britishmuseum.org/collection/object/E_Af1959-20-1');
src('igbo','Metropolitan Museum of Art. Igbo-Ukwu (ca. 9th Century).','https://www.metmuseum.org/de/essays/igbo-ukwu-ca-9th-century');
src('djenne','UNESCO. Old Towns of Djenné.','https://whc.unesco.org/en/list/116/');
src('madagascar','Alison Crowther et al. Ancient crops provide first archaeological signature of the westward Austronesian expansion. PNAS 113, 2016, pp. 6635–6640.','https://doi.org/10.1073/pnas.1522714113');
src('islandAfrica','Collagen fingerprinting traces the introduction of caprines to island Eastern Africa. Royal Society Open Science, 2021.','https://pmc.ncbi.nlm.nih.gov/articles/PMC8316820/');
src('kuk','UNESCO. Kuk Early Agricultural Site.','https://whc.unesco.org/en/list/887/');
src('polynesia','Janet M. Wilmshurst et al. High-precision radiocarbon dating shows recent and rapid initial human colonization of East Polynesia. PNAS 108, 2011, pp. 1815–1820.','https://pmc.ncbi.nlm.nih.gov/articles/PMC3033267/');
src('aotearoa','John Wilson. History: Māori arrival and settlement. Te Ara — The Encyclopedia of New Zealand.','https://teara.govt.nz/en/history/page-1');
src('tonga','UNESCO. Cultural Landscapes of the Pacific, 2007: Tonga.','https://whc.unesco.org/document/10062');
src('nanmadol','UNESCO. Nan Madol: Ceremonial Centre of Eastern Micronesia.','https://whc.unesco.org/en/list/1503/');
src('antarctica','British Antarctic Territory. History of the Territory. Australian Antarctic Program. Exploration and expeditions: from sealers to science.','https://www.britishantarcticterritory.org.uk/heritage/history-of-the-territory/');
src('japan','Metropolitan Museum of Art. Heian Period (794–1185). Princeton University Art Museum. Japan: History.','https://www.metmuseum.org/ja/essays/heian-period-794-1185');
src('korea','Metropolitan Museum of Art. Korea, 500–1000 A.D.; The Arts of Korea: A Resource for Educators.','https://82nd-and-fifth.metmuseum.org/toah/ht/06/eak.html');
src('angkor','UNESCO. Angkor.','https://whc.unesco.org/en/list/668/');
src('bagan','UNESCO. Bagan.','https://whc.unesco.org/en/list/1588/');
src('borobudur','UNESCO. Borobudur Temple Compounds.','https://whc.unesco.org/en/list/592/');
src('chola','Smithsonian National Museum of Asian Art. Chola dynasty.','https://asia.si.edu/glossary/chola-dynasty/');
src('hastings','English Heritage. The 1066 Battlefield.','https://www.english-heritage.org.uk/visit/places/1066-battle-of-hastings-abbey-and-battlefield/things-to-do/the-1066-battlefield/');
src('vikings','National Museum of Denmark. The Viking Age.','https://en.natmus.dk/historical-knowledge/denmark/prehistoric-period-until-1050-ad/the-viking-age/');
c.regions.unshift({id:'eurasia',name:L('Евразия','Eurasia','Евразия'),scope:L('Европа и Азия','Europe and Asia','Европа жана Азия'),view:[70,35,1.5]});
c.regions.push(
 {id:'arctic',name:L('Гренландия и Арктика','Greenland and the Arctic','Гренландия жана Арктика'),scope:L('Северная Атлантика и полярные побережья','North Atlantic and polar coasts','Түндүк Атлантика жана уюл жээктери'),view:[-48,69,2.7]},
 {id:'oceania',name:L('Океания','Oceania','Океания'),scope:L('Новая Гвинея и острова Тихого океана','New Guinea and the Pacific islands','Жаңы Гвинея жана Тынч океан аралдары'),view:[155,-12,1.45]},
 {id:'antarctica',name:L('Антарктида','Antarctica','Антарктида'),scope:L('Южный полярный материк','Southern polar continent','Түштүк уюл материги'),view:[0,-75,1.35]}
);
const period=(a,b)=>L('ок. '+a+'–'+b,'c. '+a+'–'+b,'болж. '+a+'–'+b);
const p=(from,to,title,text,sources,date)=>({from,to,title,text,sources,period:date||period(from,to)});
const add=(id,region,kind,coord,name,phases)=>c.entries.push({id,region,kind,coord,name,phases});
add('palenque','north','state',[-92.05,17.48],L('Паленке · Баакуль','Palenque · Baakal','Паленке · Баакуль'),[
 p(610,615,L('Нападения Калакмуля','Calakmul attacks','Калакмулдун кол салуулары'),L('Война с Калакмулем ослабляет царский двор Паленке.','War with Calakmul weakens Palenque’s royal court.','Калакмул менен согуш Паленкенин падышалык бийлигин алсыратат.'),['mayaPolitics']),
 p(615,900,L('Династия Пакаля','Pakal’s dynasty','Пакалдын династиясы'),L('Пакаль и его преемники укрепляют царскую власть и перестраивают столицу.','Pakal and his successors strengthen kingship and rebuild the capital.','Пакаль жана анын мураскерлери падышалык бийликти чыңдап, борборду кайра курат.'),['mayaPolitics'])]);
add('calakmul','north','state',[-89.81,18.11],L('Калакмуль · Кануль','Calakmul · Kaanul','Калакмуль · Кануль'),[
 p(610,695,L('Сеть союзов Кануль','Kaanul alliance network','Кануль союздар тармагы'),L('Правители Кануль соперничают с Тикалем за союзников и зависимые города.','Kaanul rulers compete with Tikal for allies and subordinate cities.','Кануль башкаруучулары Тикаль менен союздаштар жана көз каранды шаарлар үчүн атаандашат.'),['mayaPolitics']),
 p(695,900,L('После поражения от Тикаля','After defeat by Tikal','Тикалдан жеңилгенден кийин'),L('Победа Тикаля в 695 году меняет соотношение сил между царствами майя.','Tikal’s victory in 695 changes the balance between Maya kingdoms.','695-жылы Тикалдын жеңиши майя падышалыктарынын күчтөр тең салмагын өзгөртөт.'),['mayaPolitics'])]);
add('quirigua','north','state',[-89.04,15.27],L('Киригуа','Quiriguá','Киригуа'),[
 p(610,738,L('В орбите Копана','Within Copán’s orbit','Копандын таасиринде'),L('Город долины Мотагуа связан с более могущественным Копаном.','The Motagua Valley city is tied to the stronger kingdom of Copán.','Мотагуа өрөөнүндөгү шаар күчтүү Копан падышалыгы менен байланышкан.'),['quirigua']),
 p(738,850,L('Самостоятельное царство','Independent kingdom','Өз алдынча падышалык'),L('После победы над Копаном Киригуа становится самостоятельным центром власти.','After defeating Copán, Quiriguá becomes an independent seat of power.','Копанды жеңгенден кийин Киригуа өз алдынча бийлик борборуна айланат.'),['quirigua'])]);
add('hohokam','north','culture',[-111.82,33.18],L('Хохокам · долины Хила и Солт','Hohokam · Gila and Salt valleys','Хохокам · Хила жана Солт өрөөндөрү'),[
 p(600,1100,L('Каналы и земледельческие селения','Canals and farming villages','Каналдар жана дыйкан айылдары'),L('Общины расширяют оросительные сети в пустынных долинах.','Communities expand irrigation networks through desert valleys.','Жамааттар чөл өрөөндөрүндө сугат тармактарын кеңейтет.'),['hohokam']),
 p(1100,1300,L('Классический период','Classic period','Классикалык доор'),L('Крупные поселения с платформами связывают земледелие, ремесло и обмен.','Large platform-mound settlements connect agriculture, crafts and exchange.','Чоң дөбө платформалуу конуштар дыйканчылыкты, кол өнөрчүлүктү жана сооданы байланыштырат.'),['hohokam'])]);
add('paquime','north','city',[-107.96,30.37],L('Касас-Грандес · Пакиме','Casas Grandes · Paquimé','Касас-Грандес · Пакиме'),[
 p(700,1200,L('Ранние поселения','Early villages','Алгачкы айылдар'),L('Поселения периода Вьехо предшествуют большому центру Пакиме.','Viejo-period villages precede the large centre of Paquimé.','Вьехо доорундагы айылдар ири Пакиме борборунан мурда болгон.'),['paquime']),
 p(1200,1300,L('Политический и церемониальный центр','Political and ceremonial centre','Саясий жана жөрөлгөлүк борбор'),L('Пакиме вырастает в многоэтажный глинобитный город со связями между Мезоамерикой и севером.','Paquimé grows into a multistorey adobe town linking Mesoamerica and the north.','Пакиме Мезоамерика менен түндүктү байланыштырган көп кабаттуу чопо шаарга айланат.'),['paquime'])]);
add('effigy','north','culture',[-91.18,43.09],L('Верхняя Миссисипи · фигурные насыпи','Upper Mississippi · effigy mounds','Жогорку Миссисипи · сөлөкөт дөбөлөр'),[p(650,1200,L('Церемониальные ландшафты','Ceremonial landscapes','Жөрөлгөлүк ландшафттар'),L('Общины сооружают земляные насыпи в форме животных и птиц.','Communities build earthen mounds shaped as animals and birds.','Жамааттар жаныбар жана куш сөлөкөтүндөгү топурак дөбөлөрдү курат.'),['effigy'])]);
add('taino','north','community',[-69.8,18.9],L('Большие Антильские острова · таино','Greater Antilles · Taíno','Чоң Антиль аралдары · таино'),[p(1000,1300,L('Касики и островные связи','Caciques and island networks','Касиктер жана аралдык байланыштар'),L('Объединения общин под властью касиков связаны морским обменом и церемониальными центрами.','Chief-led communities are linked by maritime exchange and ceremonial centres.','Касиктер башкарган жамааттар деңиз соодасы жана жөрөлгөлүк борборлор аркылуу байланышат.'),['caribbean'])]);
add('chincha','south','state',[-76.17,-13.45],L('Царство Чинча','Chincha kingdom','Чинча падышалыгы'),[p(1150,1300,L('Ла-Сентинела и сеть долины','La Centinela and its valley network','Ла-Сентинела жана өрөөн тармагы'),L('Ла-Сентинела — столица богатого прибрежного царства, связанная дорогами с подчинёнными центрами.','La Centinela is a wealthy coastal kingdom’s capital, linked by roads to subordinate centres.','Ла-Сентинела — көз каранды борборлорго жолдор менен байланышкан бай жээк падышалыгынын борбору.'),['andes'])]);
add('ichma','south','state',[-76.86,-12.26],L('Ичма · Пачакамак','Ichma · Pachacamac','Ичма · Пачакамак'),[p(1000,1300,L('Власть в долинах Лурин и Римак','Power in the Lurín and Rímac valleys','Лурин жана Римак өрөөндөрүндөгү бийлик'),L('Местные правители строят пирамиды с пандусами; Пачакамак сохраняет значение святилища.','Local rulers build ramped pyramids; Pachacamac remains an important sanctuary.','Жергиликтүү башкаруучулар пандустуу пирамидаларды курат; Пачакамак маанилүү ыйык жай бойдон калат.'),['andes'])]);
add('muisca','south','community',[-73.37,5.54],L('Муиска · Восточные Кордильеры','Muisca · Eastern Cordillera','Муиска · Чыгыш Кордильера'),[
 p(800,1200,L('Ранний период муиска','Early Muisca period','Муисканын алгачкы доору'),L('На высокогорном плато развиваются земледельческие общины и местные центры.','Farming communities and local centres develop on the high plateau.','Бийик платодо дыйкан жамааттары жана жергиликтүү борборлор өнүгөт.'),['muisca']),
 p(1200,1300,L('Поздний период муиска','Late Muisca period','Муисканын кийинки доору'),L('Усиливается социальное расслоение и складываются более крупные объединения общин.','Social differentiation grows and larger chief-led communities develop.','Коомдук катмарлашуу күчөп, ири жамааттык бирикмелер түзүлөт.'),['muisca','northAndes'])]);
add('sanagustin','south','culture',[-76.29,1.89],L('Сан-Агустин','San Agustín','Сан-Агустин'),[
 p(610,800,L('Монументальные погребальные центры','Monumental funerary centres','Монументалдуу көрүстөн борборлору'),L('Общины северных Анд возводят курганы и каменные статуи.','Northern Andean communities build burial mounds and stone statues.','Түндүк Анд жамааттары көрүстөн дөбөлөрүн жана таш айкелдерди курат.'),['sanAgustin']),
 p(800,1300,L('Поселения после монументального расцвета','Settlements after the monumental peak','Монументалдуу гүлдөшүнөн кийинки конуштар'),L('Заселение области продолжается после главного периода создания статуй.','Occupation continues after the principal period of statue production.','Айкел жасоонун негизги доорунан кийин да аймакта жашоо уланат.'),['sanAgustin'])]);
add('araucania','south','culture',[-72.6,-38.7],L('Юг Чили · Питрен и Эль-Верхель','Southern Chile · Pitrén and El Vergel','Түштүк Чили · Питрен жана Эль-Верхель'),[
 p(610,1000,L('Традиция Питрен','Pitrén tradition','Питрен салты'),L('Общины юга Чили объединяют родственные гончарные и погребальные традиции.','Southern Chilean communities share pottery and burial traditions.','Түштүк Чили жамааттарын окшош карапачылык жана сөөк коюу салттары байланыштырат.'),['pitren']),
 p(1000,1300,L('Развитие Эль-Верхель','El Vergel develops','Эль-Верхель өнүгөт'),L('В северной Араукании распространяются новые формы керамики и поселений.','New pottery and settlement traditions spread in northern Araucanía.','Түндүк Арауканияда карапа жана конуштардын жаңы салттары тарайт.'),['vergel'])]);
add('kairouan','africa','state',[10.10,35.68],L('Ифрикия · Кайруан','Ifriqiya · Kairouan','Ифрикия · Кайруан'),[
 p(670,800,L('База исламского Магриба','Centre of the early Islamic Maghreb','Алгачкы ислам Магрибинин борбору'),L('Кайруан становится опорным городом исламской власти в Ифрикии.','Kairouan becomes a base of Islamic rule in Ifriqiya.','Кайруан Ифрикиядагы ислам бийлигинин таяныч шаарына айланат.'),['kairouan']),
 p(800,909,L('Аглабиды','Aghlabids','Аглабиддер'),L('Аглабидские правители развивают столицу, мечети и водоснабжение.','Aghlabid rulers develop the capital, mosques and water supply.','Аглабид башкаруучулары борборду, мечиттерди жана суу камсыздоону өнүктүрөт.'),['kairouan']),
 p(909,1300,L('Религиозный и учёный центр','Religious and scholarly centre','Диний жана илимий борбор'),L('При смене династий и столиц Кайруан сохраняет значение центра исламской учёности.','Through changes of dynasty and capital, Kairouan remains a centre of Islamic learning.','Династиялар жана борборлор алмашса да, Кайруан ислам илиминин борбору бойдон калат.'),['kairouan'])]);
add('marrakesh','africa','state',[-7.98,31.63],L('Магриб · Марракеш','Maghreb · Marrakesh','Магриб · Марракеш'),[
 p(1070,1147,L('Альморавиды · аль-Мурабитун','Almoravids · al-Murabitun','Альморавиддер · аль-Мурабитун'),L('Марракеш становится столицей державы, объединяющей земли Магриба и аль-Андалуса.','Marrakesh becomes the capital of a realm linking the Maghreb and al-Andalus.','Марракеш Магриб менен аль-Андалустун жерлерин бириктирген мамлекеттин борборуна айланат.'),['marrakesh']),
 p(1147,1269,L('Альмохады · аль-Муваххидун','Almohads · al-Muwahhidun','Альмохаддар · аль-Муваххидун'),L('Альмохады захватывают столицу и создают новую державу в западном исламском мире.','The Almohads capture the capital and establish a new western Islamic empire.','Альмохаддар борборду алып, батыш ислам дүйнөсүндө жаңы мамлекет түзөт.'),['marrakesh']),
 p(1269,1300,L('Мариниды','Marinids','Мариниддер'),L('Марракеш переходит под власть Маринидов; политическое первенство принадлежит Фесу.','Marrakesh passes to Marinid rule; Fez holds political primacy.','Марракеш Мариниддерге өтөт; саясий башкы орун Феске таандык.'),['marrakesh'])]);
add('cairo','africa','state',[31.26,30.05],L('Миср · Каир','Misr · Cairo','Миср · Каир'),[
 p(969,1171,L('Фатимидская столица','Fatimid capital','Фатимиддердин борбору'),L('Аль-Кахира становится столицей Фатимидов и крупным центром торговли и учёности.','Al-Qahira becomes the Fatimid capital and a major centre of trade and learning.','Аль-Кахира Фатимиддердин борбору жана ири соода-илим шаары болот.'),['cairo']),
 p(1171,1250,L('Айюбиды','Ayyubids','Айюбиддер'),L('Салах ад-Дин прекращает Фатимидский халифат; Египтом правят Айюбиды.','Salah al-Din ends the Fatimid caliphate; the Ayyubids rule Egypt.','Салах ад-Дин Фатимид халифатын токтотот; Египетти Айюбиддер башкарат.'),['cairo']),
 p(1250,1300,L('Мамлюкский султанат','Mamluk sultanate','Мамлюк султандыгы'),L('Каир становится столицей мамлюкских султанов Египта и аш-Шама.','Cairo becomes the capital of the Mamluk sultans of Egypt and al-Sham.','Каир Египет жана аш-Шам мамлюк султандарынын борборуна айланат.'),['cairo'])]);
add('kanem','africa','state',[15.3,14.5],L('Канем · озеро Чад','Kanem · Lake Chad','Канем · Чад көлү'),[
 p(900,1087,L('Царство к северо-востоку от Чада','Kingdom northeast of Lake Chad','Чад көлүнүн түндүк-чыгышындагы падышалык'),L('Правители Канема укрепляют контроль над караванными путями.','Kanem’s rulers consolidate control over caravan routes.','Канем башкаруучулары кербен жолдорун көзөмөлдөөнү бекемдейт.'),['kanem']),
 p(1087,1200,L('Мусульманская династия Сайфава','Muslim Sayfawa dynasty','Мусулман Сайфава династиясы'),L('Хуммай и его преемники связывают царскую власть с исламом и торговлей через Сахару.','Hummai and his successors link kingship with Islam and trans-Saharan trade.','Хуммай жана мураскерлери падышалык бийликти ислам жана Сахара соодасы менен байланыштырат.'),['kanem']),
 p(1200,1300,L('Экспансия при Дунаме Диббалеми','Expansion under Dunama Dabbalemi','Дунама Диббалеминин тушундагы кеңейүү'),L('В XIII веке конные войска расширяют влияние Канема к Феццану; развиваются связи с Тунисом.','In the thirteenth century cavalry extends Kanem’s influence toward Fezzan; ties with Tunis develop.','XIII кылымда атчан аскерлер Канемдин таасирин Феццанга кеңейтет; Тунис менен байланыш өсөт.'),['kanem'])]);
add('ife','africa','state',[4.56,7.49],L('Иле-Ифе','Ile-Ife','Иле-Ифе'),[
 p(800,1100,L('Развитие городского центра','Growth of an urban centre','Шаардык борбордун өсүшү'),L('Ифе развивается как центр ремесла, ритуала и политической власти йоруба.','Ife develops as a Yoruba centre of craft, ritual and political authority.','Ифе йорубалардын кол өнөрчүлүк, жөрөлгө жана саясий бийлик борбору катары өнүгөт.'),['ife']),
 p(1100,1300,L('Царский двор и искусство','Royal court and art','Падышалык сарай жана искусство'),L('Правители и придворные мастера создают выдающиеся терракотовые и металлические скульптуры.','Rulers and court artists commission exceptional terracotta and metal sculpture.','Башкаруучулар менен сарай чеберлери терракота жана металл айкелдерин жасатат.'),['ife'])]);
add('igbo','africa','culture',[7.02,6.02],L('Игбо-Укву','Igbo-Ukwu','Игбо-Укву'),[p(800,1000,L('Металлургия и дальние связи','Metalwork and distant connections','Металл иштетүү жана алыскы байланыштар'),L('Богатые погребения и бронзовые изделия свидетельствуют о специализированном ремесле и обмене.','Rich burials and bronze objects reveal specialised crafts and exchange.','Бай көрүстөндөр жана коло буюмдар адистешкен кол өнөрчүлүктү жана сооданы көрсөтөт.'),['igbo'])]);
add('djenne','africa','city',[-4.55,13.9],L('Дженне-Джено · Внутренняя дельта Нигера','Djenné-Djeno · Inland Niger Delta','Женне-Жено · Нигердин ички дельтасы'),[p(610,1300,L('Городские сети Нигера','Niger urban networks','Нигердин шаардык тармактары'),L('Городские поселения дельты связывают земледелие, рыболовство и региональную торговлю.','Delta towns connect farming, fishing and regional trade.','Дельтанын шаарлары дыйканчылыкты, балыкчылыкты жана аймактык сооданы байланыштырат.'),['djenne'])]);
add('madagascar','africa','community',[49.7,-13.3],L('Мадагаскар и Коморы','Madagascar and the Comoros','Мадагаскар жана Комор аралдары'),[
 p(800,1000,L('Земледельческие и торговые поселения','Farming and trading settlements','Дыйканчылык жана соода конуштары'),L('Появляются поселения, связанные с Африкой и морскими миграциями из Юго-Восточной Азии.','Settlements connect African communities with maritime migration from Southeast Asia.','Конуштар Африка жамааттарын Түштүк-Чыгыш Азиядан келген деңиз көчтөрү менен байланыштырат.'),['islandAfrica']),
 p(1000,1300,L('Обмен в Индийском океане','Indian Ocean exchange','Инди океанындагы соода'),L('Азиатские культурные растения и африканские связи участвуют в формировании островных обществ.','Asian crops and African connections shape island societies.','Азиялык өсүмдүктөр жана африкалык байланыштар арал коомдорунун калыптанышына катышат.'),['madagascar'])]);
add('ethiopia','africa','state',[39.3,11.7],L('Эфиопское нагорье · аль-Хабаша','Ethiopian highlands · al-Habasha','Эфиопия тоолору · аль-Хабаша'),[
 p(900,1150,L('После Аксумского царства','After the Aksumite kingdom','Аксум падышалыгынан кийин'),L('Политические и церковные центры смещаются в глубь нагорья.','Political and ecclesiastical centres shift into the highlands.','Саясий жана чиркөө борборлору тоолуу аймактын ичине жылат.'),['ethiopia']),
 p(1150,1270,L('Загве','Zagwe','Загве'),L('Правители Загве поддерживают христианские центры и строительство скальных церквей.','Zagwe rulers support Christian centres and rock-hewn churches.','Загве башкаруучулары христиан борборлорун жана аска чиркөөлөрүн колдойт.'),['ethiopia']),
 p(1270,1300,L('Начало Соломоновой династии','Rise of the Solomonic dynasty','Сулайман династиясынын башталышы'),L('Новая династия сменяет Загве; перестраиваются связи царской власти и церкви.','A new dynasty replaces the Zagwe and reshapes relations between monarchy and church.','Жаңы династия Загвени алмаштырып, падышалык менен чиркөөнүн байланышын өзгөртөт.'),['ethiopia'])]);
add('greenland','arctic','landscape',[-43,74],L('Гренландия','Greenland','Гренландия'),[p(610,800,L('Между археологическими фазами','Between archaeological phases','Археологиялык доорлордун аралыгы'),L('Для этого промежутка устойчивое заселение острова пока не подтверждено; поздний Дорсет появляется около 800 года.','Sustained occupation in this interval is not established; Late Dorset appears around 800.','Бул аралыкта аралдагы туруктуу конуштар ырасталган эмес; кийинки Дорсет болжол менен 800-жылы пайда болот.'),['dorset'],L('610–ок. 800','610–c. 800','610–болж. 800'))]);
add('dorset','arctic','culture',[-66,78],L('Поздний Дорсет · север Гренландии','Late Dorset · northern Greenland','Кийинки Дорсет · түндүк Гренландия'),[p(800,1300,L('Морские охотники Арктики','Arctic maritime hunters','Арктиканын деңиз аңчылары'),L('Общины позднего Дорсета живут на северных побережьях и охотятся на морских животных.','Late Dorset communities inhabit northern coasts and hunt marine animals.','Кийинки Дорсет жамааттары түндүк жээктерде жашап, деңиз жаныбарларына аңчылык кылат.'),['dorset'])]);
add('norse','arctic','community',[-45.52,61.16],L('Скандинавские поселения Гренландии','Norse Greenland settlements','Гренландиядагы скандинав конуштары'),[
 p(985,1261,L('Фермы, церкви и атлантическая торговля','Farms, churches and Atlantic trade','Чарбалар, чиркөөлөр жана Атлантика соодасы'),L('Переселенцы из Исландии обосновываются в юго-западных фьордах. Вожди-землевладельцы организуют хозяйство и торговлю.','Icelandic settlers establish farms in southwestern fjords. Elite landowners organise farming and trade.','Исландиядан көчкөндөр түштүк-батыш фьорддорунда отурукташат. Жер ээлери чарбаны жана сооданы уюштурат.'),['norse']),
 p(1261,1300,L('Под властью норвежской короны','Under the Norwegian crown','Норвегия таажысынын бийлигинде'),L('Скандинавские поселения признают норвежского короля; их власть не распространяется на весь остров.','The Norse settlements accept Norwegian royal authority; this does not cover the whole island.','Скандинав конуштары Норвегия падышасын тааныйт; бул бийлик бүт аралды камтыбайт.'),['norse'])]);
add('thule','arctic','culture',[-155,71],L('Туле · предки инуитов','Thule · Inuit ancestors','Туле · инуиттердин ата-бабалары'),[
 p(1000,1200,L('Северная Аляска и движение на восток','Northern Alaska and eastward movement','Түндүк Аляска жана чыгышка жылуу'),L('Морские охотники культуры туле распространяются вдоль арктических побережий.','Thule maritime hunters spread along Arctic coasts.','Туле маданиятынын деңиз аңчылары Арктика жээктери боюнча тарайт.'),['thule']),
 {...p(1200,1300,L('Приход в Гренландию','Arrival in Greenland','Гренландияга келүү'),L('Предки инуитов достигают Гренландии с запада и осваивают новые прибрежные районы.','Inuit ancestors reach Greenland from the west and settle new coastal areas.','Инуиттердин ата-бабалары батыштан Гренландияга жетип, жаңы жээк аймактарына жайгашат.'),['thule']),coord:[-69,77]}
]);
add('kuk','oceania','landscape',[144.33,-5.78],L('Новая Гвинея · Кук','New Guinea · Kuk','Жаңы Гвинея · Кук'),[p(610,1300,L('Длительная земледельческая традиция','Long agricultural continuity','Узак дыйканчылык салты'),L('Общины нагорья продолжают многотысячелетнюю обработку влажных земель с помощью дренажных канав.','Highland communities continue millennia of wetland cultivation using drainage ditches.','Тоолук жамааттар нымдуу жерлерди дренаж арыктары менен иштетүүнүн миң жылдык салтын улантат.'),['kuk'],L('В течение 610–1299','Throughout 610–1299','610–1299 бою'))]);
add('tonga','oceania','community',[-175.14,-21.14],L('Тонга · островные общества','Tonga · island societies','Тонга · арал коомдору'),[
 p(610,1200,L('Земледелие и морские связи','Farming and maritime connections','Дыйканчылык жана деңиз байланыштары'),L('Островные общины Тонга поддерживают земледелие и связи в западной Полинезии.','Tongan island communities maintain farming and western Polynesian connections.','Тонга аралдарынын жамааттары дыйканчылыкты жана батыш Полинезия менен байланышты сактайт.'),['tonga']),
 p(1200,1300,L('Власть туи-тонга','Tuʻi Tonga authority','Туи-тонга бийлиги'),L('Крупные погребальные комплексы отражают власть правящей линии и развитие морских связей.','Large tomb complexes express ruling-lineage authority and maritime connections.','Ири көрүстөн комплекстери башкаруучу тукумдун бийлигин жана деңиз байланыштарын көрсөтөт.'),['tonga'])]);
add('nanmadol','oceania','state',[158.33,6.84],L('Понпеи · Нан-Мадол','Pohnpei · Nan Madol','Понпеи · Нан-Мадол'),[p(1200,1300,L('Центр власти Сауделеров','Saudeleur seat of power','Сауделер бийлигинин борбору'),L('На искусственных островках возводятся дворцы, храмы и гробницы правителей.','Palaces, temples and rulers’ tombs rise on artificial islets.','Жасалма аралчаларда сарайлар, ибадатканалар жана башкаруучулардын күмбөздөрү курулат.'),['nanmadol'])]);
add('eastpolynesia','oceania','community',[-149.4,-17.65],L('Восточная Полинезия','East Polynesia','Чыгыш Полинезия'),[p(1025,1300,L('Освоение островов','Settlement of the islands','Аралдардын өздөштүрүлүшү'),L('Мореходы заселяют острова Общества; позднее расселение достигает удалённых архипелагов.','Voyagers settle the Society Islands; later dispersal reaches distant archipelagos.','Деңизчилер Коом аралдарына жайгашат; кийин алыскы архипелагдарга тарайт.'),['polynesia'])]);
add('rapanui','oceania','community',[-109.35,-27.12],L('Рапа-Нуи','Rapa Nui','Рапа-Нуи'),[p(1200,1300,L('Раннее полинезийское заселение','Early Polynesian settlement','Алгачкы полинезиялык конуштар'),L('Полинезийские мореходы заселяют удалённый остров юго-восточной части Тихого океана.','Polynesian voyagers settle the remote southeastern Pacific island.','Полинезиялык деңизчилер Тынч океандын түштүк-чыгышындагы алыскы аралга отурукташат.'),['polynesia'])]);
add('hawaii','oceania','community',[-155.6,19.6],L('Гавайские острова','Hawaiian Islands','Гавай аралдары'),[p(1200,1300,L('Полинезийские поселения','Polynesian settlements','Полинезиялык конуштар'),L('В XIII веке полинезийские общины уже осваивают Гавайский архипелаг.','By the thirteenth century Polynesian communities are settling the Hawaiian archipelago.','XIII кылымда полинезиялык жамааттар Гавай архипелагын өздөштүрүп жатат.'),['polynesia'])]);
add('aotearoa','oceania','community',[173.8,-41.5],L('Аотеароа · Новая Зеландия','Aotearoa · New Zealand','Аотеароа · Жаңы Зеландия'),[p(1250,1300,L('Приход предков маори','Arrival of Māori ancestors','Маорилердин ата-бабаларынын келиши'),L('Между 1250 и 1300 годами переселенцы из Восточной Полинезии начинают заселять Аотеароа.','Between 1250 and 1300 settlers from East Polynesia begin settling Aotearoa.','1250–1300-жылдар аралыгында Чыгыш Полинезиядан келгендер Аотеароага отурукташа баштайт.'),['aotearoa'],L('ок. 1250–1300 · интервал заселения','c. 1250–1300 · settlement interval','болж. 1250–1300 · отурукташуу аралыгы'))]);
add('antarctica','antarctica','uninhabited',[0,-78],L('Антарктида','Antarctica','Антарктида'),[p(610,1300,L('Материк без подтверждённых поселений людей','Continent without confirmed human settlement','Адам конуштары ырасталбаган материк'),L('В 610–1299 годах человеческие поселения и государства здесь не известны. Документированное открытие материка относится к 1820 году.','No human settlements or states are known here in 610–1299. Documented sightings of the continent date to 1820.','610–1299-жылдары бул жерде адам конуштары жана мамлекеттер белгилүү эмес. Материктин документтелген ачылышы 1820-жылга таандык.'),['antarctica'],L('610–1299','610–1299','610–1299'))]);
add('japan','eurasia','state',[135.77,35.01],L('Япония · императорский двор и сёгунат','Japan · imperial court and shogunate','Жапония · император сарайы жана сёгундук'),[
 p(794,1185,L('Хэйан','Heian','Хэйан'),L('Двор в Хэйан-кё развивает аристократическую культуру; постепенно усиливаются военные дома.','The Heian-kyō court develops aristocratic culture while warrior houses gain strength.','Хэйан-кё сарайында аристократтык маданият өнүгүп, аскердик үйлөр күчөйт.'),['japan'],L('794–1185','794–1185','794–1185')),
 {...p(1185,1300,L('Камакура','Kamakura','Камакура'),L('Военное правительство в Камакуре сосуществует с императорским двором Киото.','The military government at Kamakura coexists with the imperial court in Kyoto.','Камакурадагы аскердик өкмөт Киотодогу император сарайы менен катар жашайт.'),['japan'],L('с 1185 · до конца шкалы','from 1185 · to timeline end','1185-жылдан · шкаланын аягына чейин')),coord:[139.55,35.32]}
]);
add('korea','eurasia','state',[129.22,35.85],L('Корея · Силла и Корё','Korea · Silla and Goryeo','Корея · Силла жана Корё'),[
 p(610,676,L('Три царства и войны с Тан','Three Kingdoms and wars involving Tang','Үч падышалык жана Тан катышкан согуштар'),L('Силла, Пэкче и Когурё борются за полуостров; в войнах участвует Тан.','Silla, Baekje and Goguryeo compete for the peninsula; Tang intervenes in the wars.','Силла, Пэкче жана Когурё жарым арал үчүн күрөшөт; согушка Тан катышат.'),['korea']),
 p(676,918,L('Объединённая Силла','Unified Silla','Бириккен Силла'),L('Силла контролирует большую часть полуострова; на севере существует отдельная политическая история.','Silla controls much of the peninsula; the north follows a separate political history.','Силла жарым аралдын көп бөлүгүн көзөмөлдөйт; түндүктүн өзүнчө саясий тарыхы бар.'),['korea']),
 {...p(918,1300,L('Возникновение и развитие Корё','Rise and development of Goryeo','Корёнун пайда болушу жана өнүгүшү'),L('Ван Гон основывает Корё. Объединение завершается в 936 году; XIII век приносит монгольское давление.','Wang Geon founds Goryeo. Unification is completed in 936; Mongol pressure follows in the thirteenth century.','Ван Гон Корёну негиздейт. Биригүү 936-жылы аяктайт; XIII кылымда монгол кысымы келет.'),['korea']),coord:[126.55,37.97]}
]);
add('angkor','eurasia','state',[103.86,13.44],L('Кхмерское государство · Ангкор','Khmer state · Angkor','Кхмер мамлекети · Ангкор'),[p(800,1300,L('Царская власть и водная система','Kingship and water systems','Падышалык бийлик жана суу тутумдары'),L('Столицы кхмерских царей связаны храмами, водохранилищами и земледельческими территориями.','Khmer royal capitals link temples, reservoirs and agricultural territories.','Кхмер падышаларынын борборлору ибадатканалар, суу сактагычтар жана дыйкан жерлери менен байланышкан.'),['angkor'])]);
add('bagan','eurasia','state',[94.86,21.17],L('Паган / Баган','Pagan / Bagan','Паган / Баган'),[p(1000,1300,L('Держава долины Иравади','Irrawaddy Valley empire','Иравади өрөөнүнүн мамлекети'),L('Царская власть и буддийские учреждения объединяют крупный центр долины Иравади.','Kingship and Buddhist institutions sustain a major Irrawaddy Valley centre.','Падышалык бийлик жана буддалык мекемелер Иравади өрөөнүндөгү ири борборду бириктирет.'),['bagan'])]);
add('java','eurasia','state',[110.2,-7.61],L('Центральная Ява · Шайлендры','Central Java · Shailendras','Борбордук Ява · Шайлендралар'),[p(700,900,L('Строительство Боробудура','Construction of Borobudur','Боробудурдун курулушу'),L('Правители Шайлендра поддерживают создание монументального буддийского комплекса.','Shailendra rulers support the construction of the monumental Buddhist complex.','Шайлендра башкаруучулары монументалдуу буддалык комплекстин курулушун колдойт.'),['borobudur'])]);
add('chola','eurasia','state',[79.14,10.79],L('Чола · Южная Индия','Chola · South India','Чола · Түштүк Индия'),[p(850,1280,L('Держава тамильского юга','Empire of the Tamil south','Тамил түштүгүнүн мамлекети'),L('Династия управляет через региональных правителей; храмы служат крупными хозяйственными и культурными центрами.','The dynasty governs through regional rulers; temples are major economic and cultural centres.','Династия аймактык башкаруучулар аркылуу бийлейт; храмдар ири чарбалык жана маданий борборлор болот.'),['chola'])]);
// Political detail for earlier profiles; retain their established dating.
const get=id=>c.entries.find(e=>e.id===id);
get('wari').kind='state';get('chimu').kind='state';get('ghana').kind='state';get('mali').kind='state';get('dongola').kind='state';get('mapungubwe').kind='state';
get('marajo').phases[0].text=L('Поселения на искусственных насыпях образуют сложные общества. По реконструкции Дениз Шаан, объединения под властью вождей соперничали за ресурсы и влияние.','Mound settlements form complex societies. Denise Schaan reconstructs chief-led communities competing for resources and influence.','Жасалма дөбөлөрдөгү конуштар татаал коомдорду түзөт. Дениз Шаандын реконструкциясында башчылар башкарган бирикмелер ресурстар жана таасир үчүн атаандашкан.');
get('marajo').phases[0].sources.push('marajoPolitics');
return require('./chronology.cjs')(c);
};
