'use strict';
module.exports=(c,H)=>{
 const {L,phase:P}=H;
 H.source('lateNorse','National Museum of Denmark. Norse; Norse Greenland: archaeology and radiocarbon chronology.',['https://natmus.dk/organisation/forskning-og-kulturarv/nyere-tid-og-verdens-kulturer/etnografisk-samling/arktisk-forskning/prehistory-of-greenland/norse/']);
 H.source('lateIceland','Alþingi. The History of Althingi.',['https://www.althingi.is/pdf/Althingi2013_enska.pdf']);
 H.source('lateTonga','Geoffrey Clark et al. Chiefly Tombs, Lineage History, and the Ancient Tongan State.',['https://openresearch-repository.anu.edu.au/items/681998ec-d804-4c6a-accf-611dcb3ce0dc']);
 H.source('lateMaori','Museum of New Zealand Te Papa Tongarewa. Te Tipunga: 1300–1500.',['https://collections.tepapa.govt.nz/category/58']);
 H.source('lateHawaii','National Park Service. Hawaiʻi: Food, Subsistence, & Agriculture.',['https://www.nps.gov/locations/hawaii/food.htm']);
 const current=id=>c.entries.find(e=>e.id===id).phases.at(-1);
 const carry=(id,title,text,extraSources=[])=>{
  const p=current(id);H.continueEntry(id,[P(1300,1454,title||p.title,text||p.text,[...new Set([...p.sources,...extraSources])],{learning:p.learning})]);
  H.area(id,1300,1454,'previous');
 };
 // These are named cultural landscapes, never political borders of whole continents.
 for(const id of ['budj','kakadu','kuk','mabuyag'])carry(id);
 carry('antarctica',L('Материк без подтверждённых поселений','Continent without confirmed settlements','Ырасталган конуштары жок материк'),L('Для 1300–1453 годов поселения людей в Антарктиде не подтверждены. На карте выделен сам материк.','No human settlements in Antarctica are established for 1300–1453. The map outlines the continent itself.','1300–1453-жылдары Антарктидада адам конуштары ырасталган эмес. Картада материктин өзү белгиленген.'));
 carry('nanmadol',L('Каменный центр Сауделеров','Saudeleur stone-built centre','Сауделерлердин таш борбору'),L('Нан-Мадол развивается как династический и церемониальный центр на искусственных островках. Комплекс дворцов, погребальных и жилых сооружений строился между XIII и XV веками.','Nan Madol develops as a dynastic and ceremonial centre on artificial islets. Its palaces, mortuary and residential compounds were built between the thirteenth and fifteenth centuries.','Нан-Мадол жасалма аралчалардагы династиялык жана жөрөлгө борбору катары өнүгөт. Сарай, көрүстөн жана турак жай комплекстери XIII–XV кылымдарда курулган.'));
 carry('palau',L('Каменные деревни Бабелдаоба','Babeldaob stone villages','Бабелдаобдун таш айылдары'),L('Жизнь местных общин сосредоточена в прибрежных деревнях. Каменные платформы и террасы образуют жилые и общественные пространства.','Local communities live in coastal villages. Stone platforms and terraces form residential and communal spaces.','Жергиликтүү жамааттар жээктеги айылдарда жашайт. Таш платформалар менен террасалар турак жана коомдук жайларды түзөт.'));
 carry('samoa',L('Поселения и монументальные платформы','Settlements and monumental platforms','Конуштар жана монументалдуу платформалар'),L('На Савайи поселения связаны с каменными платформами, включая Пулемелей. Дома, дороги и земледельческие участки образуют освоенный ландшафт.','On Savaii, settlements are associated with stone platforms including Pulemelei. Houses, paths and cultivated plots form an inhabited landscape.','Савайиде конуштар Пулемелей сыяктуу таш платформалар менен байланышкан. Үйлөр, жолдор жана эгин тилкелери өздөштүрүлгөн ландшафтты түзөт.'));
 carry('eastpolynesia',L('Островные общины и морские связи','Island communities and maritime connections','Арал жамааттары жана деңиз байланыштары'),L('На островах Общества живут земледельческие и рыболовные общины. Межостровные плавания поддерживают обмен, родственные и обрядовые связи.','Farming and fishing communities inhabit the Society Islands. Inter-island voyaging sustains exchange, kinship and ceremonial connections.','Коом аралдарында дыйкан жана балыкчы жамааттар жашайт. Аралдар аралык сүзүүлөр алмашууну, туугандык жана жөрөлгөлүк байланыштарды колдойт.'));
 carry('rapanui',L('Общины, аху и моаи','Communities, ahu and moai','Жамааттар, аху жана моаи'),L('На Рапа-Нуи общины возводят церемониальные платформы аху и каменные изваяния моаи. Земледелие и морские ресурсы обеспечивают жизнь островитян.','Rapa Nui communities build ceremonial ahu platforms and stone moai figures. Agriculture and marine resources sustain island life.','Рапа-Нуи жамааттары аху жөрөлгө платформаларын жана моаи таш айкелдерин курат. Дыйканчылык менен деңиз ресурстары арал турмушун камсыз кылат.'));
 carry('hawaii',L('Земледельческие общества Гавайев','Hawaiian agricultural societies','Гавайинин дыйканчылык коомдору'),L('Островные общины развивают выращивание таро и других культур, рыболовство и обмен. Орошение, террасы и каменные сооружения преобразуют долины. Единого государства всего архипелага ещё нет.','Island communities develop taro and other crops, fishing and exchange. Irrigation, terraces and stone structures reshape valleys. There is no single state ruling the entire archipelago.','Арал жамааттары таро жана башка өсүмдүктөрдү өстүрүүнү, балык уулоону жана алмашууну өнүктүрөт. Сугат, террасалар жана таш курулуштар өрөөндөрдү өзгөртөт. Бүт архипелагды башкарган бирдиктүү мамлекет азырынча жок.'),['lateHawaii']);
 const tp=current('tonga');
 H.continueEntry('tonga',[P(1300,1454,L('Туи-Тонга · центр в Лапаха','Tui Tonga · centre at Lapaha','Туи-Тонга · Лапахадагы борбор'),L('Правящая линия Туи-Тонга опирается на церемониальный центр Лапаха. Монументальные гробницы и привозные каменные орудия показывают организацию труда и связи с другими архипелагами.','The Tui Tonga ruling line is associated with the ceremonial centre of Lapaha. Monumental tombs and imported stone tools show organised labour and connections with other archipelagos.','Туи-Тонга башкаруучу тукуму Лапаха жөрөлгө борборуна таянат. Чоң күмбөздөр жана сырттан келген таш шаймандар уюшкан эмгекти жана башка архипелагдар менен байланышты көрсөтөт.'),[...tp.sources,'lateTonga'],{learning:tp.learning,coord:[-175.12,-21.18]})]);
 H.area('tonga',1300,1454,'previous',{kind:'polity',name:L('Туи-Тонга · Тонгатапу','Tui Tonga · Tongatapu','Туи-Тонга · Тонгатапу')});
 const mp=current('aotearoa');
 H.continueEntry('aotearoa',[P(1300,1454,L('Те Типунга · развитие общин маори','Te Tipunga · developing Māori communities','Те Типунга · маори жамааттарынын өнүгүшү'),L('Общины маори осваивают побережья и внутренние районы Аотеароа. Местные условия формируют земледелие, рыболовство, обработку камня и связи между поселениями. Этот этап музейная периодизация называет Те Типунга — «рост».','Māori communities develop coastal and inland settlement in Aotearoa. Local environments shape farming, fishing, stoneworking and connections between communities. Te Papa calls this period Te Tipunga, meaning growth.','Маори жамааттары Аотеароанын жээктерин жана ички аймактарын өздөштүрөт. Жергиликтүү шарттар дыйканчылыкты, балык уулоону, таш иштетүүнү жана конуштардын байланышын аныктайт. Те-Папа музейи бул доорду Те Типунга — «өсүү» деп атайт.'),[...mp.sources,'lateMaori'],{learning:mp.learning})]);
 H.area('aotearoa',1300,1454,'previous',{kind:'settlement'});
 const ip=current('iceland');
 H.continueEntry('iceland',[
  P(1300,1397,L('Исландия под норвежской короной','Iceland under the Norwegian crown','Норвегия таажысынын бийлигиндеги Исландия'),ip.text,[...ip.sources,'lateIceland'],{learning:ip.learning,approx:false}),
  P(1397,1454,L('Кальмарская уния','The Kalmar Union','Кальмар униясы'),L('Исландия входит в объединённую монархию Скандинавии как владение норвежской короны. Альтинг сохраняет судебные и законодательные функции в изменившейся системе власти.','Iceland belongs to the Scandinavian union monarchy through the Norwegian crown. The Alþing retains judicial and legislative functions within the changed political order.','Исландия Норвегия таажысынын ээлиги катары Скандинавиянын бириккен монархиясына кирет. Альтинг өзгөргөн бийлик тутумунда соттук жана мыйзамдык милдеттерин сактайт.'),['lateIceland'],{learning:ip.learning,approx:false})]);
 H.area('iceland',1300,1397,'previous');H.area('iceland',1397,1454,'previous');
 const np=current('norse'),oldNorse=c.areas.filter(a=>a.entry==='norse').at(-1).polygons;
 H.continueEntry('norse',[
  P(1300,1350,L('Два скандинавских поселения','Two Norse settlements','Эки скандинав конуш аймагы'),L('Фермы Восточного и Западного поселений сохраняют связи с североатлантическим миром. Скандинавское расселение ограничено фьордами юго-запада острова.','Farms in the Eastern and Western Settlements remain connected to the North Atlantic world. Norse settlement is confined to fjords in southwestern Greenland.','Чыгыш жана Батыш конуштарынын чарбалары Түндүк Атлантика дүйнөсү менен байланышта. Скандинав конуштары аралдын түштүк-батыш фьорддорунда гана жайгашкан.'),['lateNorse','norseLife'],{learning:np.learning}),
  P(1350,1450,L('Последние поколения Восточного поселения','Last generations of the Eastern Settlement','Чыгыш конушунун акыркы муундары'),L('Западное поселение оставлено примерно к середине XIV века. Восточное существует дольше: письменное свидетельство 1408 года и археология показывают жизнь здесь до середины XV века.','The Western Settlement is abandoned around the mid-fourteenth century. The Eastern Settlement lasts longer: a record from 1408 and archaeology attest occupation into the mid-fifteenth century.','Батыш конушу болжол менен XIV кылымдын орто ченинде ташталган. Чыгыш конушу узагыраак жашаган: 1408-жылкы жазма жана археология бул жерде XV кылымдын ортосуна чейин турмуш болгонун көрсөтөт.'),['lateNorse'],{learning:np.learning})]);
 H.area('norse',1300,1350,oldNorse,{kind:'settlement'});H.area('norse',1350,1450,[oldNorse[0]],{kind:'settlement'});
 const th=current('thule'),oldThule=c.areas.filter(a=>a.entry==='thule').at(-1).polygons;
 H.continueEntry('thule',[P(1300,1454,L('Инуитские общества Арктики','Inuit societies of the Arctic','Арктиканын инуит коомдору'),L('Потомки переселенцев культуры Туле обживают арктические побережья и Гренландию. Каяки, умиаки и собачьи упряжки связывают сезонные поселения; охота на морских животных поддерживает их хозяйство.','Descendants of Thule migrants inhabit Arctic coasts and Greenland. Kayaks, umiaks and dog sledges connect seasonal settlements, whose economy draws on marine hunting.','Туле көчмөндөрүнүн урпактары Арктика жээктери менен Гренландияны байырлайт. Каяк, умиак жана ит чаналары мезгилдик конуштарды байланыштырат; деңиз аңчылыгы чарбанын негизин түзөт.'),th.sources,{learning:th.learning,coord:[-55,70]})]);
 H.area('thule',1300,1454,[...oldThule,[[-63,74],[-54,70],[-50,66],[-47,61],[-43,60],[-44,64],[-48,69],[-57,75]]],{kind:'cultural'});
 H.event('late-norse-west',1350,'norse','migration',[-50.7,64.2],L('Оставление Западного поселения Гренландии','Abandonment of Greenland’s Western Settlement','Гренландиянын Батыш конушунун ташталышы'),L('К середине XIV века скандинавское Западное поселение перестаёт существовать. Восточное поселение продолжает жить.','By the mid-fourteenth century the Norse Western Settlement ceases to be occupied. The Eastern Settlement continues.','XIV кылымдын орто ченинде скандинавдардын Батыш конушунда жашоо токтойт. Чыгыш конушу жашоосун улантат.'),['lateNorse'],{approx:true});
 H.event('late-norse-record',1408,'norse','culture',[-45.78,60.83],L('Последнее письменное свидетельство скандинавской Гренландии','Last written record of Norse Greenland','Скандинав Гренландиясынын акыркы жазма күбөлүгү'),L('Письменное свидетельство 1408 года подтверждает жизнь Восточного поселения. Оно не означает, что все поселения были оставлены именно в этом году.','A written record from 1408 confirms life in the Eastern Settlement. It does not date the abandonment of every settlement to that year.','1408-жылкы жазма Чыгыш конушунда турмуш уланып жатканын ырастайт. Бул бардык конуштар дал ошол жылы ташталган дегенди билдирбейт.'),['lateNorse']);
 H.event('late-iceland-union',1397,'iceland','politics',[-21.129,64.256],L('Исландия в Кальмарской унии','Iceland within the Kalmar Union','Кальмар униясынын курамындагы Исландия'),L('Исландия связана с Кальмарской унией через норвежскую корону. Местный Альтинг продолжает работу.','Iceland is linked to the Kalmar Union through the Norwegian crown. The local Alþing continues to function.','Исландия Норвегия таажысы аркылуу Кальмар униясына байланышат. Жергиликтүү Альтинг ишин улантат.'),['lateIceland']);
 return c;
};
