// Eurasia, 1300–1453. Regional cores are editorial schematics, not surveyed borders.
// Annual snapshots show the situation reached during a year; intervals are half-open.
module.exports=(c,H)=>{
 const {L,source,phase,entry,continueEntry,area,event}=H;
 const S=(id,title,...urls)=>source(id,title,urls);
 S('lateOttoman','Kate Fleet (ed.). The Cambridge History of Turkey, vol. 1: Byzantium to Turkey, 1071–1453, chapter “Anatolia, 1300–1451”; OpenStax, World History, vol. 1, “The Ottomans and the Mongols”.','https://www.cambridge.org/core/books/abs/cambridge-history-of-turkey/anatolia-13001451/71691A45EAABF8F09B64EB28C1C680EB','https://openstax.org/books/world-history-volume-1/pages/17-1-the-ottomans-and-the-mongols');
 S('lateYuan','The Metropolitan Museum of Art. Yuan Dynasty (1271–1368); Arts of the Ming Dynasty: China’s Age of Brilliance; Defining Yongle.','https://www.metmuseum.org/essays/yuan-dynasty-1271-1368','https://www.metmuseum.org/exhibitions/listings/2009/arts-of-the-ming-dynasty','https://www.metmuseum.org/exhibitions/listings/2005/yongle-imperial-art');
 S('lateIlkhan','Reuven Amitai. Il-Khanids i. Dynastic History. Encyclopaedia Iranica.','https://www.iranicaonline.org/articles/il-khanids-i-dynastic-history/');
 S('lateIranCourts','Peter Jackson. Jalayerids; C. E. Bosworth. Mozaffarids. Encyclopaedia Iranica.','https://www.iranicaonline.org/articles/jalayerids/','https://www.iranicaonline.org/articles/mozaffarids/');
 S('lateTimur','Linda Komaroff and Suzan Yalman. The Art of the Timurid Period (ca. 1370–1507). The Metropolitan Museum of Art; Bertold Spuler. Central Asia v. In the Mongol and Timurid Periods. Encyclopaedia Iranica.','https://www.metmuseum.org/essays/the-art-of-the-timurid-period-ca-1370-1507','https://www.iranicaonline.org/articles/central-asia-v/');
 S('lateJochi','Peter Jackson. Golden Horde. Encyclopaedia Iranica.','https://www.iranicaonline.org/articles/golden-horde/');
 S('lateChagatai','Peter Jackson. Chaghatay Dynasty i. History. Encyclopaedia Iranica.','https://www.iranicaonline.org/articles/chaghatay-dynasty/i-history/');
 S('lateKyrgyz','Сун Лянь и др. 《元史》 «Юань ши», цзюань 63 (география), 128 (биография Тутухи), 18 (анналы Чэн-цзуна).','https://zh.wikisource.org/wiki/元史/卷063','https://zh.wikisource.org/wiki/元史/卷128','https://zh.wikisource.org/wiki/元史/卷018');
 S('lateTurkmen','Rosemarie Quiring-Zoche. Aq Qoyunlu; Peter Jackson. Jalayerids. Encyclopaedia Iranica.','https://www.iranicaonline.org/articles/aq-qoyunlu-confederation/','https://www.iranicaonline.org/articles/jalayerids/');
 S('lateDelhi','Encyclopaedia Iranica. Delhi Sultanate i. Political and Cultural History; The Metropolitan Museum of Art. South Asia, 1400–1600; Islamic Art of the Deccan.','https://www.iranicaonline.org/articles/delhi-sultanate/delhi-sultanate-i-political-and-cultural-history/','https://82nd-and-fifth.metmuseum.org/toah/ht/08/ssa.html','https://www.metmuseum.org/essays/islamic-art-of-the-deccan');
 S('lateDeccan','UNESCO. Group of Monuments at Hampi; Encyclopaedia Iranica. Bahmanid Dynasty; Gulbarga; Bidar.','https://whc.unesco.org/en/list/241/','https://www.iranicaonline.org/articles/bahmanid-dynasty-a-dynasty-founded-in-748-1347-in-the-deccan-sanskrit-daksia-lit/','https://www.iranicaonline.org/articles/gulbarga/','https://www.iranicaonline.org/articles/bidar-indian-city/');
 S('lateJapan','The Metropolitan Museum of Art. Muromachi Period (1392–1573); Sonia Coman. Nanbokuchō and Muromachi Periods, an Introduction. Smarthistory.','https://www.metmuseum.org/essays/muromachi-period-1392-1573','https://smarthistory.org/nanbokucho-and-muromachi-periods/');
 S('lateKorea','Soyoung Lee (ed.). Art of the Korean Renaissance, 1400–1600. The Metropolitan Museum of Art.','https://www.metmuseum.org/exhibitions/listings/2009/korean-renaissance','https://resources.metmuseum.org/resources/metpublications/pdf/Art_of_the_Korean_Renaissance_1400_1600.pdf');
 S('lateAngkor','Alison K. Carter et al. Temple Occupation and the Tempo of Collapse at Angkor Wat, Cambodia. PNAS 116 (2019); UNESCO. Historic City of Ayutthaya.','https://doi.org/10.1073/pnas.1821879116','https://whc.unesco.org/en/list/576/');
 S('lateJava','Ministry of Culture and Tourism of Indonesia. Trowulan — Former Capital City of Majapahit Kingdom. UNESCO Tentative List submission.','https://whc.unesco.org/en/tentativelists/5466/');
 S('lateFrance','The Metropolitan Museum of Art. France, 1400–1600; Royal Armouries. The Hundred Years’ War 1337–1453; The National Archives. Medieval and Early Modern Soldiers.','https://82nd-and-fifth.metmuseum.org/toah/ht/08/euwf.html','https://royalarmouries.org/objects-and-stories/stories/the-hundred-years-war-1337-1453','https://www.nationalarchives.gov.uk/help-with-your-research/research-guides/medieval-early-modern-soldiers/');
 S('lateEmpire','Charles IV. The Golden Bull (1356). German History in Documents and Images; Austrian Commission for UNESCO. The Golden Bull.','https://germanhistorydocs.org/en/from-the-reformations-to-the-thirty-years-war-1500-1648/the-golden-bull-1356','https://www.unesco.at/en/communication/documentary-heritage/memory-of-the-world-in-austria/the-golden-bull');
 S('lateNasrid','The Metropolitan Museum of Art. The Art of the Nasrid Period (1232–1492).','https://www.metmuseum.org/essays/the-art-of-the-nasrid-period-1232-1492');
 S('lateLithuania','UNESCO. Vilnius Historic Centre: Nomination Dossier, History of Vilnius.','https://whc.unesco.org/document/140380');
 S('lateMoscow','UNESCO. Kremlin and Red Square, Moscow.','https://whc.unesco.org/en/list/545/');
 S('lateMingYunnan','Liu Xin. 明初云南的边防建设 (Frontier Defence in Early Ming Yunnan). Yunnan Academy of Social Sciences.','https://www.sky.yn.gov.cn/xsyj/zgsd/2064359992836409611');
 S('lateHerat','Encyclopaedia Iranica. Herat iii. History, Medieval Period.','https://www.iranicaonline.org/articles/herat-iii/');
 S('lateThessalonica','Municipality of Thessaloniki. Ottoman Period.','https://thessaloniki.gr/i-want-to-know-the-city/moments-in-history/ottoman-period/?lang=en');

 const learn=(government,economy,society)=>({learning:{government,economy,society}});
 const ph=(a,b,t,x,s,extra={})=>phase(a,b,t,x,Array.isArray(s)?s:[s],extra);
 // Each row carries its own geometry; a previous phase is never extended automatically.
 const add=(id,name,coord,src,color,rows,kind='state')=>{
  entry(id,'eurasia',kind,coord,name,rows.map(r=>ph(r[0],r[1],r[2],r[3],src,r[5]||{})));
  rows.forEach(r=>area(id,r[0],r[1],r[4],{kind:r[6]||'polity',color,sources:Array.isArray(src)?src:[src]}));
 };
 const more=(id,src,color,rows)=>{
  continueEntry(id,rows.map(r=>ph(r[0],r[1],r[2],r[3],src,r[5]||{})));
  rows.forEach(r=>area(id,r[0],r[1],r[4],{kind:r[6]||'polity',color,sources:Array.isArray(src)?src:[src]}));
 };

 const osmanCore=[[29.1,39.5],[30.9,39.3],[31,40.5],[29.5,40.6]];
 const osmanBursa=[[28.2,39.2],[30.9,39.3],[31.6,40.7],[29.1,41.1],[28.6,40.4]];
 const osmanBalkan=[[22.5,40.3],[24,39.5],[26,40],[26.7,40.8],[28.2,41.2],[28.2,42.5],[27,43.3],[24.3,43.8],[22.5,42.6]];
 const gallipoli=[[26.15,40.25],[26.7,40.25],[27.15,40.8],[26.45,41.15],[26.05,40.7]];
 const osmanThrace=[[25.5,40.65],[27.6,40.7],[28.2,41.15],[27.8,42.35],[25.5,42.5],[24.65,41.5]];
 const osmanAnatolia=[[26.5,38.1],[29.7,37.2],[31.2,38.2],[33.2,39.1],[35.6,39.1],[36.3,40.1],[34.6,41.5],[30,41.6],[28,40.3]];
 add('late-ottoman',L('Османское государство','Ottoman state','Осмон мамлекети'),[29.06,40.19],'lateOttoman','#bc815a',[
  [1300,1326,L('Бейлик Османа','Osman’s principality','Осмондун бейлиги'),L('На северо-западе Анатолии владения Османа растут у границы ар-Рума.','Osman’s domain grows along the frontier of al-Rum in northwestern Anatolia.','Анатолиянын түндүк-батышында Осмондун ээлиги ар-Рум чек арасында өсөт.'),osmanCore],
  [1326,1354,L('Бурса и Вифиния','Bursa and Bithynia','Бурса жана Вифиния'),L('Завоевание Бурсы укрепляет османский центр; затем переходят Никея и Никомедия.','The capture of Bursa strengthens the Ottoman centre; Nicaea and Nicomedia follow.','Бурсанын алынышы Осмон борборун бекемдейт; кийин Никея менен Никомедия алынат.'),osmanBursa],
  [1354,1362,L('Плацдарм в Галлиполи','Foothold at Gallipoli','Галлиполидеги таяныч'),L('Османы закрепляются на европейском берегу Дарданелл. Галлиполи открывает путь во Фракию.','The Ottomans establish a foothold on the European side of the Dardanelles. Gallipoli opens the way into Thrace.','Осмондор Дарданеллдин Европа жээгинде бекемделет. Галлиполи Фракияга жол ачат.'),[osmanBursa,gallipoli]],
  [1362,1389,L('Эдирне и Фракия','Edirne and Thrace','Эдирне жана Фракия'),L('Эдирне становится османским столичным центром. Владения расширяются во Фракии; Константинополь остаётся у ар-Рума.','Edirne becomes an Ottoman capital. The domain expands in Thrace; Constantinople remains with al-Rum.','Эдирне Осмон борборуна айланат. Ээликтер Фракияда кеңейет; Константинополь ар-Румда калат.'),[osmanBursa,osmanThrace],{approx:true}],
  [1389,1402,L('Расширение на Балканах','Expansion in the Balkans','Балкандардагы кеңейүү'),L('При Мураде I и Баязиде I расширяются балканские владения и сеть вассалов. Константинополь ещё не взят.','Under Murad I and Bayezid I, Balkan domains and the network of vassals expand. Constantinople has not yet been taken.','Мурад I менен Баязид Iнин тушунда Балкан ээликтери жана вассалдар тармагы кеңейет. Константинополь али алына элек.'),[osmanBursa,osmanBalkan],{},'influence'],
  [1402,1413,L('Междуцарствие после Анкары','Interregnum after Ankara','Анкарадан кийинки так талаш'),L('Тимур разбивает Баязида I. Османские князья борются за престол; ряд анатолийских бейликов восстанавливается.','Timur defeats Bayezid I. Ottoman princes contest the throne and several Anatolian principalities reappear.','Тимур Баязид Iди жеңет. Осмон ханзадалары так үчүн күрөшүп, Анатолиянын айрым бейликтери кайра түзүлөт.'),[osmanBursa,osmanBalkan],{},'influence'],
  [1413,1430,L('Восстановление султаната','Reunification of the sultanate','Султандыктын кайра биригиши'),L('Мехмед I завершает междуцарствие. Бурса и Эдирне вновь входят в единый султанат.','Mehmed I ends the interregnum. Bursa and Edirne again belong to one sultanate.','Мехмед I так талашты аяктатат. Бурса менен Эдирне кайра бир султандыкка кирет.'),[osmanBursa,osmanBalkan]],
  [1430,1453,L('Мурад II и укрепление владений','Murad II and consolidation','Мурад II жана ээликтердин бекемделиши'),L('При Мураде II османы укрепляют власть в западной Анатолии и на Балканах. В 1430 году взяты Фессалоники.','Under Murad II, the Ottomans consolidate western Anatolian and Balkan domains. Thessalonica is taken in 1430.','Мурад IIнин тушунда осмондор батыш Анатолия менен Балкандарда бийлигин бекемдейт. 1430-жылы Фессалоники алынат.'),[osmanAnatolia,osmanBalkan]],
  [1453,1454,L('Взятие Константинополя','Capture of Constantinople','Константинополдун алынышы'),L('Мехмед II берёт Константинополь. Город у Босфора становится османской столицей.','Mehmed II takes Constantinople. The city on the Bosporus becomes the Ottoman capital.','Мехмед II Константинополду алат. Босфордогу шаар Осмон борборуна айланат.'),[osmanAnatolia,[[22.5,40.3],[24,39.5],[26,40],[27,40.6],[29.2,40.8],[29.1,41.3],[28.2,42.5],[27,43.3],[24.3,43.8],[22.5,42.6]]]]
 ]);
 const rumThrace=[[26.2,40.5],[28.95,40.9],[29,41.2],[27.6,42.1],[26.4,41.8]];
 const morea=[[21.3,36.8],[22.9,36.3],[23.1,37.5],[22.3,38.2],[21.1,37.7]];
 add('late-rum',L('Римская империя · ар-Рум','Roman Empire · al-Rum','Рим империясы · ар-Рум'),[28.97,41.01],'lateOttoman','#9687b5',[
  [1300,1354,L('Поздняя империя Палеологов','Late Palaiologan empire','Палеологдордун соңку империясы'),L('Ар-Рум удерживает Константинополь, владения во Фракии и Морее. Гражданские войны ослабляют императорскую власть.','Al-Rum retains Constantinople and domains in Thrace and the Morea. Civil wars weaken imperial authority.','Ар-Рум Константинополду, Фракия менен Мореядагы ээликтерин сактайт. Ички согуштар император бийлигин алсыратат.'),[rumThrace,morea]],
  [1354,1453,L('Константинополь и Морея','Constantinople and the Morea','Константинополь жана Морея'),L('Османское окружение сужает владения императоров до отдельных областей. Морейский деспотат продолжает существовать после 1453 года.','Ottoman expansion confines imperial territory to separated domains. The Despotate of the Morea survives beyond 1453.','Осмон кеңейиши императордун ээликтерин өзүнчө аймактарга кыскартат. Морея деспотаты 1453-жылдан кийин да жашайт.'),[[[28.6,40.85],[29.04,40.9],[29.06,41.22],[28.7,41.3]],morea]]
 ]);
 add('late-morea',L('Морейский деспотат','Despotate of the Morea','Морея деспотаты'),[22.37,37.07],'lateOttoman','#9687b5',[[1453,1454,L('После падения столицы','After the capital falls','Борбор алынгандан кийин'),L('Палеологи сохраняют владения в Пелопоннесе; их история не заканчивается одновременно с падением Константинополя.','The Palaiologoi retain their Peloponnesian domains after Constantinople falls.','Палеологдор Константинополь алынгандан кийин Пелопоннестеги ээликтерин сактайт.'),morea]]);

 const chinaCore=[[103,22],[108,20.5],[112,21],[118,24],[121,28],[121.6,31],[119,34],[121,37],[119,40],[114,41],[108,39],[104,35],[102,29]];
 const chinaEarlyMing=[[107,25],[108,21.5],[112,21],[118,24],[121,28],[121.6,31],[119,34],[121,37],[119,40],[114,41],[108,39],[106,35],[106,29]];
 const mongolia=[[91,45],[97,42],[111,42],[120,46],[119,50],[111,53],[101,52],[93,49]];
 add('late-yuan',L('Великая Юань · ас-Син','Great Yuan · al-Sin','Улуу Юань · ас-Син'),[116.4,39.9],'lateYuan','#ba8c56',[[1300,1368,L('Монгольская династия в Китае','Mongol dynasty in China','Кытайдагы монгол династиясы'),L('Юань управляет Китаем и Монголией из Даду. Восстания XIV века заканчиваются утратой китайской столицы в 1368 году.','The Yuan rule China and Mongolia from Dadu. Fourteenth-century rebellions culminate in the loss of their Chinese capital in 1368.','Юань Кытай менен Монголияны Дадудан башкарат. XIV кылымдагы көтөрүлүштөрдөн кийин 1368-жылы Кытайдагы борбор жоголот.'),[chinaCore,mongolia],learn(L('Император и провинциальные учреждения.','Emperor and provincial administrations.','Император жана аймактык мекемелер.'),L('Земледелие, ремесло и дальняя торговля.','Farming, crafts and long-distance trade.','Дыйканчылык, кол өнөрчүлүк жана алыскы соода.'),L('Монгольская элита правит многоязычным обществом.','A Mongol elite rules a multilingual society.','Монгол элитасы көп тилдүү коомду башкарат.'))]]);
 add('late-ming',L('Империя Мин · ас-Син','Ming empire · al-Sin','Мин империясы · ас-Син'),[118.8,32.06],['lateYuan','lateMingYunnan'],'#d0ad67',[
  [1368,1382,L('Мин и столица в Нанкине','Ming rule from Nanjing','Борбору Нанкин болгон Мин'),L('Чжу Юаньчжан основывает Мин. Китайский императорский аппарат восстанавливается; на севере остаются монгольские соперники.','Zhu Yuanzhang establishes the Ming. Imperial administration is rebuilt while Mongol rivals remain to the north.','Чжу Юаньчжан Минди негиздейт. Императордук башкаруу калыбына келип, түндүктө монгол атаандаштары калат.'),chinaEarlyMing],
  [1382,1421,L('Расширение в Юньнань','Expansion into Yunnan','Юньнанга кеңейүү'),L('После завоевания Юньнани Мин создаёт там военные и административные учреждения. Нанкин остаётся столицей.','Following the conquest of Yunnan, the Ming establish military and administrative institutions there. Nanjing remains the capital.','Юньнань каратылгандан кийин Мин ал жерде аскердик жана башкаруу мекемелерин түзөт. Нанкин борбор бойдон калат.'),chinaCore],
  [1421,1454,L('Пекин и морские экспедиции','Beijing and maritime expeditions','Бээжин жана деңиз экспедициялары'),L('Столица перенесена в Пекин. Экспедиции Чжэн Хэ связывают двор Мин с портами Индийского океана.','The capital moves to Beijing. Zheng He’s expeditions connect the Ming court with Indian Ocean ports.','Борбор Бээжинге көчүрүлөт. Чжэн Хэнин экспедициялары Мин сарайын Инд океанынын порттору менен байланыштырат.'),chinaCore,{coord:[116.4,39.9]}]
 ]);
 add('late-mongol',L('Монголия после Юань','Mongolia after the Yuan','Юандан кийинки Монголия'),[102.82,47.2],['lateYuan','lateChagatai'],'#af8662',[[1368,1454,L('Ханы и ойратские объединения','Khans and Oirat groupings','Хандар жана ойрот бирикмелери'),L('Монгольские правители продолжают борьбу за власть в степи после ухода двора Юань из Китая. Их земли не входят в Мин.','Mongol rulers continue their steppe power struggles after the Yuan court leaves China. Their lands remain outside Ming rule.','Юань сарайы Кытайдан кеткенден кийин монгол башкаруучулары талаада бийлик үчүн күрөшөт. Алардын жерлери Минге кирбейт.'),mongolia,{},'influence']]);

 const iran=[[44,30],[49,28],[54,27],[60,28.5],[63,32],[61,36],[56,38],[52,37],[49,39],[45,40],[43,37]];
 add('late-ilkhan',L('Государство Хулагу · Ильханат','Hulagu’s state · Ilkhanate','Хулагу мамлекети · Илханат'),[46.3,38.08],'lateIlkhan','#b49a63',[[1300,1335,L('Ильханы Ирана и Ирака','Ilkhans of Iran and Iraq','Иран менен Ирактын илхандары'),L('Наследники Хулагу управляют Ираном и Ираком. Смерть Абу Саида в 1335 году открывает борьбу эмиров и распад государства.','Hulagu’s heirs rule Iran and Iraq. Abu Sa‘id’s death in 1335 opens competition among amirs and the state’s fragmentation.','Хулагунун мураскерлери Иран менен Иракты башкарат. Абу Саиддин 1335-жылдагы өлүмүнөн кийин эмирлер күрөшүп, мамлекет ыдырайт.'),iran]]);
 add('late-iran-successors',L('Наследники Ильханата','Successor courts of the Ilkhanate','Илханаттан кийинки сарайлар'),[52.58,29.61],'lateIranCourts','#b99579',[[1335,1393,L('Чобаниды, Джалаириды, Музаффариды','Chobanids, Jalayirids and Muzaffarids','Чобаниддер, Жалаириддер жана Музаффариддер'),L('Иран и Ирак разделены между соперничающими династиями. Багдад, Тебриз и Шираз остаются центрами власти и книжного искусства.','Rival dynasties divide Iran and Iraq. Baghdad, Tabriz and Shiraz remain centres of government and book arts.','Иран менен Ирак атаандаш династияларга бөлүнөт. Багдад, Тебриз жана Шираз бийликтин жана китеп өнөрүнүн борборлору бойдон калат.'),iran,{},'cultural']]);
 const transox=[[62,37],[66,36.5],[70,37.4],[72,40],[69,42],[65,42],[62,40]];
 const eastChag=[[72,40],[76,38],[83,37],[90,40],[89,45],[83,48],[76,47],[73,44]];
 add('late-chagatai',L('Улус Чагатая','Chagatai Ulus','Чагатай улусу'),[80.45,43.84],'lateChagatai','#89996c',[[1300,1347,L('Мавераннахр и восточные области','Transoxiana and the eastern domains','Мавераннахр жана чыгыш аймактар'),L('Чагатаиды владеют оазисами Мавераннахра и пастбищами восточнее. Соперничество ханов и эмиров ведёт к разделению улуса.','Chagatai rulers hold Transoxianan oases and pasturelands farther east. Rivalry among khans and amirs divides the ulus.','Чагатайлар Мавераннахр оазистерин жана чыгыштагы жайыттарды ээлейт. Хандар менен эмирлердин атаандаштыгы улусту бөлөт.'),[transox,eastChag]]]);
 add('late-transoxiana',L('Мавераннахр · власть эмиров','Transoxiana · rule of the amirs','Мавераннахр · эмирлердин бийлиги'),[66.96,39.65],'lateChagatai','#9d9b71',[[1347,1370,L('Западная часть улуса','Western part of the ulus','Улустун батыш бөлүгү'),L('В Мавераннахре реальная власть переходит к эмирам. Из этой борьбы возвышается Тимур.','Amirs hold effective power in Transoxiana. Timur rises from their rivalry.','Мавераннахрда чыныгы бийлик эмирлерге өтөт. Ушул күрөштөн Тимур көтөрүлөт.'),transox]]);
 add('late-moghulistan',L('Могулистан','Moghulistan','Моголстан'),[80.45,43.84],'lateChagatai','#83946d',[[1347,1454,L('Восточное Чагатайское ханство','Eastern Chagatai khanate','Чыгыш Чагатай хандыгы'),L('Туглук-Тимур возглавляет восточную часть улуса. Ханы и эмиры Дуглатов соперничают за Семиречье и оазисы Кашгарии.','Tughluq Timur leads the eastern ulus. Khans and Dughlat amirs compete over Semirechye and the Kashgarian oases.','Тоглук-Тимур улустун чыгышын жетектейт. Хандар менен Дуглат эмирлери Жети-Суу жана Кашкар оазистери үчүн атаандашат.'),eastChag,learn(L('Ханы Чагатаиды и влиятельные эмиры.','Chagatai khans and influential amirs.','Чагатай хандары жана таасирдүү эмирлер.'),L('Пастбища связаны с городскими оазисами.','Pasturelands connect with urban oases.','Жайыттар шаардык оазистер менен байланышат.'),L('Название государства не означает единую этническую группу.','The state’s name does not denote a single ethnic group.','Мамлекеттин аталышы бир гана этносту билдирбейт.'))]]);
 const yenisei=[[88,51.5],[91,50.8],[94,51.6],[94.7,54],[91.8,55.4],[88.5,54.4]];
 add('late-kyrgyz',L('Кыргызские общины Енисея','Kyrgyz communities of the Yenisei','Энесайдагы кыргыз жамааттары'),[91.4,53.7],'lateKyrgyz','#84a092',[
  [1300,1368,L('Кыргызские земли в системе Юань','Kyrgyz lands within the Yuan system','Юань тутумундагы кыргыз жерлери'),L('«Юань ши» описывает кыргызские земли, гарнизоны, земледелие и переселение отдельных групп. Здесь показан енисейский район общин.','The Yuan shi describes Kyrgyz lands, garrisons, farming and the resettlement of particular groups. The map marks the Yenisei community region.','«Юань ши» кыргыз жерлерин, аскер бөлүктөрүн, дыйканчылыкты жана айрым топтордун көчүрүлүшүн баяндайт. Картада Энесайдагы жамааттардын аймагы берилген.'),yenisei,{},'cultural'],
  [1368,1454,L('Енисей и южносибирские связи','Yenisei and southern Siberian connections','Энесай жана Түштүк Сибирь байланыштары'),L('Общины южной Сибири сохраняют местные связи после Юань. Контур обозначает исторический район кыргызов, а не границу нового каганата.','Southern Siberian communities retain local connections after the Yuan. The outline marks the historic Kyrgyz region, not a new khaganate.','Юандан кийин Түштүк Сибирь жамааттары жергиликтүү байланыштарын сактайт. Контур жаңы каганатты эмес, кыргыздардын тарыхый аймагын көрсөтөт.'),yenisei,{},'cultural']
 ],'community');
 const timurWide=[[44,30],[49,28],[56,28],[62,29],[66,33],[71,36],[72,40],[69,43],[62,43],[59,39],[53,38],[48,41],[43,39]];
 const timurEast=[[52,31],[58,28],[63,30],[67,34],[71,36],[72,40],[69,43],[62,43],[60,38],[55,37]];
 add('late-timurid',L('Держава Тимура и Тимуридов','Timur and the Timurids','Тимур жана Тимурийлер мамлекети'),[66.96,39.65],['lateTimur','lateHerat'],'#b08774',[
  [1370,1381,L('Самарканд и Мавераннахр','Samarkand and Transoxiana','Самарканд жана Мавераннахр'),L('Тимур утверждает власть в Мавераннахре и делает Самарканд столицей.','Timur establishes power in Transoxiana and makes Samarkand his capital.','Тимур Мавераннахрда бийлик орнотуп, Самаркандды борбор кылат.'),transox],
  [1381,1393,L('Герат и продвижение в Иран','Herat and expansion into Iran','Герат жана Иранга кеңейүү'),L('В 1381 году Герат подчиняется Тимуру. Походы в Хорасан становятся этапом дальнейшего завоевания Ирана.','Herat submits to Timur in 1381. Campaigns into Khorasan precede further conquests in Iran.','1381-жылы Герат Тимурга баш иет. Хорасандагы жортуулдар Иранды андан ары каратууга жол ачат.'),[[58,33],[62,32.4],[66,34],[70,37],[72,40],[69,42],[65,42],[60,38]]],
  [1393,1405,L('Держава завоеваний','An empire of conquests','Жортуулдар менен кеңейген мамлекет'),L('Владения включают Иран и Среднюю Азию. Походы в Индию, Сирию и Анатолию не означают постоянного управления всеми разорёнными землями.','The realm spans Iran and Central Asia. Campaigns in India, Syria and Anatolia do not imply permanent rule over every devastated land.','Мамлекет Иран менен Борбордук Азияны камтыйт. Индия, Сирия жана Анатолия жортуулдары бардык талкаланган жерлердин туруктуу башкарылганын билдирбейт.'),timurWide],
  [1405,1447,L('Шахрух и Улугбек','Shah Rukh and Ulugh Beg','Шахрух жана Улукбек'),L('После смерти Тимура главными центрами становятся Герат и Самарканд. Дворы поддерживают архитектуру, рукописную книгу и астрономию.','After Timur’s death, Herat and Samarkand become leading centres. Their courts support architecture, manuscripts and astronomy.','Тимур өлгөндөн кийин Герат менен Самарканд башкы борборлорго айланат. Сарайлар архитектураны, кол жазмаларды жана астрономияны колдойт.'),timurEast,{coord:[62.2,34.35]}],
  [1447,1454,L('Борьба наследников','Rivalry among the heirs','Мураскерлердин күрөшү'),L('После смерти Шахруха Тимуриды борются за отдельные владения. Герат и Самарканд остаются крупными культурными центрами.','After Shah Rukh’s death, Timurid princes contest separate domains. Herat and Samarkand remain major cultural centres.','Шахрух өлгөндөн кийин Тимурий ханзадалары өзүнчө ээликтер үчүн күрөшөт. Герат менен Самарканд ири маданий борборлор бойдон калат.'),timurEast,{},'influence']
 ]);
 const jochi=[[32,46],[39,44.7],[45,45],[50,46],[53,49],[61,48],[68,49],[69,53],[60,55],[50,54],[45,51],[37,50]];
 add('late-jochi',L('Улус Джучи · Дешт-и Кыпчак','Jochi Ulus · Dasht-i Qipchaq','Жучу улусу · Дешт-и Кыпчак'),[45.4,47.2],'lateJochi','#b5a165',[
  [1300,1359,L('Сарай и степная держава','Sarai and the steppe realm','Сарай жана талаа мамлекети'),L('Ханы правят из Нижнего Поволжья. При Узбек-хане ислам укрепляется при дворе; русские княжества платят дань, сохраняя своих князей.','The khans rule from the lower Volga. Islam strengthens at court under Özbeg; Rus principalities pay tribute while retaining their princes.','Хандар Төмөнкү Эдилден башкарат. Өзбек хандын тушунда ислам сарайда бекемделет; Русь княздыктары өз княздарын сактап, салык төлөйт.'),jochi],
  [1359,1380,L('Борьба за ханский престол','Contests for the khanate','Хандык так үчүн күрөш'),L('После прекращения линии Бату соперничают несколько правителей. Степные владения не образуют единую устойчивую администрацию.','After Batu’s line ends, rival rulers contest power. The steppe domains lack a single stable administration.','Батунун тукумунун бийлиги бүткөндөн кийин башкаруучулар атаандашат. Талаа ээликтеринде туруктуу бирдиктүү башкаруу жок.'),jochi,{},'influence'],
  [1380,1395,L('Объединение при Тохтамыше','Reunification under Tokhtamysh','Токтомуштун тушунда биригүү'),L('Тохтамыш объединяет значительную часть улуса. Его войны с Тимуром завершаются разрушительными поражениями.','Tokhtamysh reunites much of the ulus. His wars against Timur end in devastating defeats.','Токтомуш улустун чоң бөлүгүн бириктирет. Тимур менен согуштары оор жеңилүү менен аяктайт.'),jochi],
  [1395,1454,L('Разделение джучидских владений','Fragmenting Jochid domains','Жучу ээликтеринин бөлүнүшү'),L('После походов Тимура власть дробится между ханами и эмирами. В XV веке возникают отдельные ханства.','After Timur’s campaigns, power fragments among khans and amirs. Separate khanates emerge in the fifteenth century.','Тимурдун жортуулдарынан кийин бийлик хандар менен эмирлерге бөлүнөт. XV кылымда өзүнчө хандыктар пайда болот.'),jochi,{},'influence']
 ]);
 add('late-qaraqoyunlu',L('Кара-Коюнлу','Qara Qoyunlu','Кара-Коюнлу'),[46.3,38.08],'lateTurkmen','#938482',[[1410,1454,L('Тебриз и Ирак','Tabriz and Iraq','Тебриз жана Ирак'),L('Кара-Коюнлу вытесняют Джалаиридов и укрепляют власть в Азербайджане и Ираке, соперничая с Тимуридами.','The Qara Qoyunlu displace the Jalayirids and consolidate power in Azerbaijan and Iraq, competing with the Timurids.','Кара-Коюнлу Жалаириддерди сүрүп, Азербайжан менен Иракта бийлигин бекемдейт жана Тимурийлер менен атаандашат.'),[[43.2,31],[47.5,30.5],[50.5,34],[49.2,39],[46,40.5],[43,38.7]]]]);
 add('late-aqqoyunlu',L('Ак-Коюнлу','Aq Qoyunlu','Ак-Коюнлу'),[40.23,37.91],'lateTurkmen','#b4a089',[[1400,1454,L('Туркменское объединение Диярбакыра','Turkmen confederation of Diyar Bakr','Диярбакырдагы түркмөн бирикмеси'),L('Ак-Коюнлу опираются на Диярбакыр и пастбища восточной Анатолии. Их большие завоевания в Иране относятся к следующему периоду.','The Aq Qoyunlu are based in Diyar Bakr and eastern Anatolian pastures. Their great Iranian conquests belong to the next period.','Ак-Коюнлу Диярбакырга жана чыгыш Анатолиянын жайыттарына таянат. Ирандагы чоң жортуулдары кийинки мезгилге таандык.'),[[38.8,37.4],[41,36.9],[43,38.7],[42.1,40.6],[39.8,40.4]],{},'influence']]);

 const delhiNorth=[[71,26],[73,24],[78,24],[82,25],[86,26],[85,28],[80,30],[76,32],[73,31]];
 const delhiExtended=[[71,25],[74,21],[74,17],[77,16],[81,18],[82,22],[86,25],[87,27],[81,29],[76,32],[72,30]];
 const delhiReduced=[[74,27],[77,26],[80,27],[80,29.2],[77,30],[74,29.5]];
 add('late-delhi',L('Делийский султанат','Delhi Sultanate','Дели султандыгы'),[77.2,28.6],'lateDelhi','#729c83',[
  [1300,1320,L('Халджи и походы на юг','Khalji campaigns to the south','Халжийлердин түштүк жортуулдары'),L('Халджи расширяют султанат и совершают походы в Декан. Сбор дани на юге отличается от прямого управления.','The Khaljis enlarge the sultanate and campaign in the Deccan. Southern tribute relationships differ from direct rule.','Халжийлер султандыкты кеңейтип, Деканга жортуул жасайт. Түштүктөгү салык алуу түз башкаруудан айырмаланат.'),delhiNorth],
  [1320,1347,L('Расширение при Туглаках','Expansion under the Tughluqs','Туглактардын тушунда кеңейүү'),L('Туглаки распространяют власть глубже в Декан. Восстания и отделение провинций вскоре сокращают владения Дели.','The Tughluqs extend power deeper into the Deccan. Rebellions and provincial secession soon reduce Delhi’s domains.','Туглактар бийлигин Деканга терең жайылтат. Көтөрүлүштөр жана аймактардын бөлүнүшү Дели ээликтерин азайтат.'),delhiExtended,{},'influence'],
  [1347,1398,L('Сокращение власти Дели','Decline of Delhi’s reach','Дели бийлигинин кыскарышы'),L('Бахманийский султанат и другие региональные государства становятся самостоятельными. Дели сохраняет опору в северной Индии.','The Bahmani sultanate and other regional states become independent. Delhi retains a northern Indian base.','Бахмани султандыгы жана башка аймактык мамлекеттер өз алдынча болот. Дели Түндүк Индиядагы таянычын сактайт.'),delhiNorth],
  [1398,1451,L('После похода Тимура','After Timur’s invasion','Тимурдун жортуулунан кийин'),L('Разорение Дели в 1398 году ускоряет распад державы. С 1414 года Сайиды правят значительно меньшим султанатом.','The sack of Delhi in 1398 accelerates fragmentation. From 1414 the Sayyids rule a much smaller sultanate.','1398-жылы Делинин талкаланышы мамлекеттин ыдырашын тездетет. 1414-жылдан Сайиддер кыйла чакан султандыкты башкарат.'),delhiReduced],
  [1451,1454,L('Начало династии Лоди','Beginning of Lodi rule','Лоди династиясынын башталышы'),L('Бахлул Лоди занимает престол Дели. Расширение нового султаната продолжится во второй половине XV века.','Bahlul Lodi takes Delhi’s throne. The new dynasty’s expansion continues in the later fifteenth century.','Бахлул Лоди Дели тактысына отурат. Жаңы династиянын кеңейиши XV кылымдын экинчи жарымында уланат.'),delhiReduced]
 ]);
 const vijayaCore=[[74,12],[76,11],[79,12],[79,15],[77.5,16],[75,15.5]];
 add('late-vijayanagara',L('Виджаянагара','Vijayanagara','Вижаянагара'),[76.46,15.34],['lateDeccan','lateDelhi'],'#b69963',[
  [1336,1400,L('Царство на Тунгабхадре','Kingdom on the Tungabhadra','Тунгабхадрадагы падышалык'),L('Виджаянагара становится центром нового южноиндийского царства. Храмы, укрепления и орошение поддерживают столицу.','Vijayanagara becomes the centre of a new south Indian kingdom. Temples, fortifications and irrigation sustain the capital.','Вижаянагара Түштүк Индиядагы жаңы падышалыктын борбору болот. Ибадатканалар, чептер жана сугат борборду камсыз кылат.'),vijayaCore],
  [1400,1454,L('Южноиндийская держава','South Indian power','Түштүк Индиядагы күчтүү мамлекет'),L('Государство расширяется в южной Индии и соперничает с Бахмани за земли Декана. Хампи соединяет царские, торговые и храмовые кварталы.','The state expands in southern India and competes with the Bahmanis over Deccan lands. Hampi combines royal, commercial and temple districts.','Мамлекет Түштүк Индияда кеңейип, Декан жерлери үчүн Бахмани менен атаандашат. Хампиде падышалык, соода жана ибадаткана кварталдары бар.'),[[73.7,13],[76.1,10],[78,9.4],[80,12],[80.5,15.5],[78,17],[75,16.2]]]
 ]);
 add('late-bahmani',L('Бахманийский султанат','Bahmani Sultanate','Бахмани султандыгы'),[76.83,17.33],'lateDeccan','#739998',[
  [1347,1429,L('Султанат с центром в Гулбарге','Sultanate centred on Gulbarga','Борбору Гулбарга болгон султандык'),L('После восстания против Дели возникает Бахманийский султанат. Гулбарга становится его столицей и центром персидской придворной культуры.','A rebellion against Delhi produces the Bahmani Sultanate. Gulbarga becomes its capital and a centre of Persian court culture.','Делиге каршы көтөрүлүштөн кийин Бахмани султандыгы түзүлөт. Гулбарга анын борбору жана перс сарай маданиятынын очогу болот.'),[[73.8,17],[77.5,16.2],[79.5,17.8],[79,20.8],[76,21],[74,19.8]]],
  [1429,1454,L('Столица в Бидаре','Capital at Bidar','Борбор Бидарда'),L('Двор переезжает в Бидар. Государство участвует в торговле Декана и борьбе с южными соседями.','The court moves to Bidar. The state participates in Deccan commerce and struggles with its southern neighbours.','Сарай Бидарга көчөт. Мамлекет Декан соодасына жана түштүк коңшулары менен күрөшкө катышат.'),[[73.8,17],[77.5,16.2],[79.5,17.8],[79,20.8],[76,21],[74,19.8]],{coord:[77.52,17.91]}]
 ]);

 const japaneseCore=[[[130.2,31.4],[131.4,31.4],[131.8,33.8],[130.8,34.1],[129.6,33.2]],[[132,33.1],[134.7,33.1],[134.9,34.1],[132.6,34.4]],[[131.8,34],[135.5,33.5],[139.6,34.7],[141,37],[141.6,40.8],[140.3,41.4],[139.7,38.3],[137.3,37.2],[134,35.4]]];
 more('japan','lateJapan','#b79886',[
  [1300,1333,L('Последние годы Камакуры','Final years of Kamakura','Камакуранын соңку жылдары'),L('Военное правительство Камакуры действует рядом с императорским двором. В 1333 году оно теряет власть.','Kamakura’s military government operates alongside the imperial court. It loses power in 1333.','Камакура аскер өкмөтү император сарайы менен катар иштейт. 1333-жылы ал бийлигин жоготот.'),japaneseCore],
  [1333,1392,L('Реставрация и соперничающие дворы','Restoration and rival courts','Калыбына келтирүү жана атаандаш сарайлар'),L('Краткая реставрация императорской власти сменяется сёгунатом Асикага. Северный и Южный дворы оспаривают законность друг друга.','A brief imperial restoration gives way to the Ashikaga shogunate. Northern and Southern courts contest legitimacy.','Император бийлигинин кыска калыбына келишинен кийин Асикага сёгунаты түзүлөт. Түндүк жана Түштүк сарайлар мыйзамдуулук үчүн талашат.'),japaneseCore,{},'influence'],
  [1392,1454,L('Муромати','Muromachi','Муромати'),L('Дворы объединены; сёгуны Асикага правят из Киото. Областные военные правители сохраняют большую самостоятельность.','The courts are reunited and Ashikaga shoguns rule from Kyoto. Provincial military lords retain considerable autonomy.','Сарайлар биригип, Асикага сёгундары Киотодон башкарат. Аймактык аскер башкаруучулары кеңири өз алдынчалыкты сактайт.'),japaneseCore,learn(L('Сёгун, императорский двор и даймё.','Shogun, imperial court and daimyo.','Сёгун, император сарайы жана даймё.'),L('Развиваются рынки и транспортные связи.','Markets and transport networks develop.','Базарлар жана унаа байланыштары өнүгөт.'),L('Дзэн, театр но и искусство чаепития.','Zen, Noh theatre and tea culture.','Дзэн, но театры жана чай маданияты.'))]
 ]);
 const korea=[[125,34.4],[127,34.4],[129.4,36],[129.4,39.2],[127.5,41],[125,39.8],[124.6,37.8]];
 more('korea','lateKorea','#8aa79e',[[1300,1392,L('Позднее Корё','Late Goryeo','Соңку Корё'),L('Корё переживает ослабление связи с Юань и внутреннюю борьбу элит. В 1392 году к власти приходит новая династия.','Goryeo experiences loosening Yuan ties and rivalry among elites. A new dynasty takes power in 1392.','Корёдо Юань менен байланыш алсырап, элиталар күрөшөт. 1392-жылы жаңы династия бийликке келет.'),korea]]);
 add('late-joseon',L('Чосон · Корея','Joseon · Korea','Чосон · Корея'),[126.98,37.57],'lateKorea','#77a397',[[1392,1454,L('Новое королевство Чосон','New Joseon kingdom','Жаңы Чосон падышалыгы'),L('Ли Сонге основывает Чосон. Неоконфуцианские учёные участвуют в управлении; двор поддерживает новые формы искусства и письменности.','Yi Seonggye founds Joseon. Neo-Confucian scholars participate in government; the court supports new art and writing.','Ли Сонге Чосонду негиздейт. Неоконфуций окумуштуулары башкарууга катышат; сарай жаңы өнөрдү жана жазууну колдойт.'),[[125,34.4],[127,34.4],[129.4,36],[129.4,39.2],[130.5,42.2],[128,41.6],[125,40],[124.6,37.8]]]]);
 const angkorCore=[[103.1,12],[105.6,12],[106.2,14],[104.8,15],[102.5,14.2]];
 more('angkor','lateAngkor','#aaa269',[
  [1300,1431,L('Ангкор в меняющемся регионе','Angkor in a changing region','Өзгөргөн аймактагы Ангкор'),L('Ангкор остаётся населённым центром. Изменения водной системы и соперничество с Аюттхаей сопровождают постепенное смещение власти на юг.','Angkor remains inhabited. Water-system changes and rivalry with Ayutthaya accompany a gradual southward shift of power.','Ангкор эл жашаган борбор бойдон калат. Суу тутумундагы өзгөрүүлөр жана Аюттхая менен атаандаштык бийликтин түштүккө жылышы менен коштолот.'),angkorCore],
  [1431,1454,L('Кхмерские центры на юге','Khmer centres farther south','Түштүктөгү кхмер борборлору'),L('Политический центр смещается к нижнему Меконгу. Ангкор сохраняет религиозную жизнь; дата 1431 не означает полного исчезновения населения.','Political power shifts towards the lower Mekong. Religious life continues at Angkor; 1431 does not mark the disappearance of its people.','Саясий борбор төмөнкү Меконгго жылат. Ангкордо диний жашоо уланат; 1431-жыл калктын толук жоголушун билдирбейт.'),[[103.2,10.6],[105.6,10.7],[106.3,12.5],[105.5,14],[103.3,13.2]],{coord:[104.92,11.56],approx:true}]
 ]);
 add('late-ayutthaya',L('Аюттхая','Ayutthaya','Аюттхая'),[100.56,14.35],'lateAngkor','#98a981',[[1350,1454,L('Государство в долине Чаупхраи','State in the Chao Phraya valley','Чаупхрая өрөөнүндөгү мамлекет'),L('Аюттхая становится столичным и торговым центром около 1350 года. Речные пути соединяют её с морем.','Ayutthaya becomes a capital and commercial centre around 1350. River routes connect it to the sea.','Болжол менен 1350-жылы Аюттхая борбор жана соода очогу болот. Дарыя жолдору аны деңиз менен байланыштырат.'),[[99,13],[100.8,12.8],[102,14.5],[101.2,16.4],[99,16.6]]]]);
 add('late-majapahit',L('Маджапахит · Ява','Majapahit · Java','Мажапахит · Ява'),[112.38,-7.55],'lateJava','#969c74',[[1300,1454,L('Яванский двор и сеть обмена','Javanese court and exchange networks','Ява сарайы жана соода тармактары'),L('Тровулан служит столичным центром Маджапахита. Города и порты Явы участвуют в морском обмене; заморские притязания отличаются от прямой власти.','Trowulan is Majapahit’s royal centre. Javanese towns and ports engage in maritime exchange; overseas claims differ from direct rule.','Тровулан Мажапахиттин падышалык борбору. Ява шаарлары менен порттору деңиз соодасына катышат; деңиздин ары жагындагы дооматтар түз бийликтен айырмаланат.'),[[110,-7],[113,-6.8],[114.4,-7.7],[113.8,-8.6],[111,-8.3],[109.6,-7.8]]]]);
 S('lateMalacca','UNESCO. Melaka and George Town, Historic Cities of the Straits of Malacca.','https://whc.unesco.org/en/list/1223/');
 add('late-malacca',L('Малакка','Malacca','Малакка'),[102.25,2.2],'lateMalacca','#73a6a3',[[1400,1454,L('Торговый центр у пролива','Trading centre at the strait','Кысыктагы соода борбору'),L('В начале XV века складывается Малаккский султанат. Порт связывает купцов Малайского мира, Индии и Китая.','The Malacca Sultanate emerges in the early fifteenth century. Its port connects merchants from the Malay world, India and China.','XV кылымдын башында Малакка султандыгы түзүлөт. Порт Малай дүйнөсүнүн, Индиянын жана Кытайдын соодагерлерин байланыштырат.'),[[101.5,2.1],[102.2,1.8],[102.9,2.4],[102.5,3.3],[101.8,3.1]],{approx:true}]]);

 S('lateIberia','The Metropolitan Museum of Art. Iberian Peninsula, 1400–1600.','https://82nd-and-fifth.metmuseum.org/toah/ht/08/eusi.html');
 const castile=[[-8.9,42.1],[-8.8,43.4],[-3,43.4],[-2,41.8],[-1.5,39.5],[-1,38],[-2.4,37.3],[-4.7,37.4],[-5.5,36.2],[-7.4,37.2],[-7,39.5],[-6.6,41.5]];
 add('late-castile',L('Кастильская корона','Crown of Castile','Кастилия таажысы'),[-4.73,41.65],'lateIberia','#b09a6e',[[1300,1454,L('Кастилия и Леон','Castile and León','Кастилия жана Леон'),L('Кастилия и Леон объединены одной короной. На юге сохраняется граница с Гранадой, на востоке — отдельная Арагонская корона.','Castile and León share one crown. Granada remains across the southern frontier; the Crown of Aragon is separate to the east.','Кастилия менен Леон бир таажыга бириккен. Түштүктө Гранада менен чек ара, чыгышта өзүнчө Арагон таажысы бар.'),castile]]);
 const aragon=[[0.5,42.8],[3.2,42.4],[3.1,41.6],[0.8,40.5],[0,38.7],[-0.8,38.7],[-1.6,40.1],[-1.8,41.8]];
 add('late-aragon',L('Арагонская корона','Crown of Aragon','Арагон таажысы'),[2.17,41.39],'lateIberia','#a78f7b',[[1300,1454,L('Королевства и средиземноморские связи','Kingdoms and Mediterranean connections','Падышалыктар жана Жер Ортолук деңиз байланыштары'),L('Арагон, Каталония и Валенсия сохраняют собственные учреждения под одной короной. Их порты связаны со средиземноморской торговлей.','Aragon, Catalonia and Valencia retain their institutions under one crown. Their ports participate in Mediterranean trade.','Арагон, Каталония жана Валенсия бир таажынын алдында өз мекемелерин сактайт. Порттору Жер Ортолук деңиз соодасына катышат.'),aragon]]);
 add('late-portugal',L('Португалия','Portugal','Португалия'),[-9.14,38.72],'lateIberia','#7f9f9d',[[1300,1454,L('Атлантическое королевство','Atlantic kingdom','Атлантика падышалыгы'),L('Самостоятельное королевство развивает атлантические порты. В XV веке усиливаются морские экспедиции и заморская экспансия.','The independent kingdom develops Atlantic ports. Maritime expeditions and overseas expansion intensify in the fifteenth century.','Өз алдынча падышалык Атлантика портторун өнүктүрөт. XV кылымда деңиз экспедициялары жана тышкы кеңейүү күчөйт.'),[[-9.5,37],[-7.4,37.2],[-7,39.5],[-6.6,41.5],[-8.1,42.1],[-8.9,41.7],[-9.2,39.7]]]]);
 add('late-navarre',L('Наварра','Navarre','Наварра'),[-1.65,42.81],'lateIberia','#af9276',[[1300,1454,L('Пиренейское королевство','Pyrenean kingdom','Пиреней падышалыгы'),L('Наварра сохраняет собственную корону между Кастилией, Арагоном и Францией.','Navarre retains its crown between Castile, Aragon and France.','Наварра Кастилия, Арагон жана Франциянын ортосунда өз таажысын сактайт.'),[[-2.4,42],[-1,42],[0,42.8],[-1.2,43.4],[-2.1,43.3]]]]);
 add('late-granada',L('Насридский эмират Гранады','Nasrid Emirate of Granada','Гранада Насрид эмирлиги'),[-3.6,37.18],'lateNasrid','#69978e',[[1300,1454,L('Аль-Андалус Насридов','Nasrid al-Andalus','Насриддердин аль-Андалусу'),L('Гранада, Малага и Альмерия составляют ядро эмирата. При дворе развиваются литература, шелкоткачество и архитектура Альгамбры.','Granada, Málaga and Almería form the emirate’s core. Its court supports literature, silk weaving and the architecture of the Alhambra.','Гранада, Малага жана Альмерия эмирликтин өзөгүн түзөт. Сарайда адабият, жибек токуу жана Альгамбра архитектурасы өнүгөт.'),[[-5.3,36.2],[-4.4,36.5],[-2.2,36.7],[-1.8,37.3],[-2.5,37.8],[-4.3,37.8],[-5.3,37.1]]]]);

 const france=[[-4.8,48.2],[-1.5,49.7],[1.6,50.7],[4.5,49.6],[5.7,47.2],[5.3,44.5],[3.1,43.3],[0.5,42.8],[-1.5,43.3],[-1.1,46.2]];
 const franceValois=[[-1.5,47.6],[1,47.8],[3.6,47.3],[4.5,46],[4.8,44],[2.8,43.2],[0.4,42.9],[-0.5,44.5]];
 const gascony=[[-1.5,43.3],[0.4,42.9],[1.4,44.3],[0,45.7],[-1.2,45.5]];
 const normandy=[[-1.8,48.6],[0.7,48.6],[2.7,49],[2.1,50.3],[0,49.8],[-1.8,49.7]];
 add('late-france',L('Королевство Франция','Kingdom of France','Франция падышалыгы'),[2.35,48.86],'lateFrance','#8495b4',[
  [1300,1337,L('Капетинги и начало Валуа','Capetians and the early Valois','Капетингдер жана алгачкы Валуа'),L('Королевская власть соседствует с крупными княжескими владениями. Спор о наследовании и английских землях во Франции ведёт к войне.','Royal power coexists with great princely domains. Disputes over succession and English holdings in France lead to war.','Падышалык бийлик ири княздык ээликтер менен катар жашайт. Мурас жана Франциядагы англис жерлери тууралуу талаш согушка алып келет.'),france,{},'influence'],
  [1337,1420,L('Столетняя война','Hundred Years’ War','Жүз жылдык согуш'),L('Французские и английские короли борются за престол и территории. Владения переходят из рук в руки; походы разоряют сельские земли.','French and English kings contest the crown and territory. Possessions change hands, and campaigns devastate rural districts.','Француз жана англис падышалары так менен жер үчүн күрөшөт. Ээликтер колдон колго өтүп, жортуулдар айылдарды талкалайт.'),france,{},'influence'],
  [1420,1450,L('Разделённое королевство и возвращение земель','Divided kingdom and reconquest','Бөлүнгөн падышалык жана жерлердин кайтарылышы'),L('Англичане удерживают значительные северные владения. Сторонники Карла VII восстанавливают власть на севере и юго-западе.','The English hold substantial northern domains. Charles VII’s supporters restore his authority in the north and southwest.','Англистер түндүктөгү ири ээликтерди кармайт. Карл VIIнин тарапкерлери түндүк менен түштүк-батышта бийлигин калыбына келтирет.'),franceValois],
  [1450,1453,L('Возвращение Нормандии','Recovery of Normandy','Нормандиянын кайтарылышы'),L('Карл VII восстанавливает власть в Нормандии. Борьба за Гасконь продолжается.','Charles VII restores his authority in Normandy. The contest for Gascony continues.','Карл VII Нормандиядагы бийлигин калыбына келтирет. Гасконь үчүн күрөш уланат.'),[franceValois,normandy]],
  [1453,1454,L('Завершение основных боевых действий','End of the main fighting','Негизги салгылашуулардын аякташы'),L('Победа французов завершает Столетнюю войну. Из прежних французских владений английская корона удерживает Кале.','French victory ends the Hundred Years’ War. Of its former French possessions, the English crown retains Calais.','Француздардын жеңиши Жүз жылдык согушту аяктатат. Англис таажысы мурдагы француз ээликтеринен Калени сактайт.'),france,{},'influence']
 ]);
 const england=[[-5.6,50],[-3.6,51.2],[-5.2,51.7],[-4.7,53.3],[-3.1,53.5],[-3,54.9],[-2,55.5],[0,53.9],[1.8,52.8],[1.2,51.1],[-1.5,50.5]];
 add('late-england',L('Королевство Англия','Kingdom of England','Англия падышалыгы'),[-0.13,51.51],'lateFrance','#b77f83',[
  [1300,1420,L('Англия и война во Франции','England and war in France','Англия жана Франциядагы согуш'),L('Английская корона удерживает Уэльс и владения в Гаскони. Военные походы требуют налогов и согласования с парламентом.','The English crown holds Wales and lands in Gascony. Campaigns require taxation and negotiation with Parliament.','Англис таажысы Уэльсти жана Гасконь жерлерин кармайт. Жортуулдар салыкты жана парламент менен макулдашууну талап кылат.'),[england,gascony]],
  [1420,1450,L('Английские владения во Франции','English possessions in France','Франциядагы англис ээликтери'),L('Английская власть распространяется на Нормандию и части севера Франции. К середине XV века эти владения теряются.','English rule extends over Normandy and parts of northern France. These domains are lost by the mid-fifteenth century.','Англис бийлиги Нормандияга жана Франциянын түндүгүнүн бир бөлүгүнө жайылат. XV кылымдын ортосуна чейин бул ээликтер жоголот.'),[england,gascony,normandy]],
  [1450,1453,L('Утрата Нормандии','Loss of Normandy','Нормандиянын жоголушу'),L('Французы возвращают Нормандию. Последние крупные английские позиции на континенте остаются в Гаскони.','The French recover Normandy. The last major English continental positions remain in Gascony.','Француздар Нормандияны кайтарат. Континенттеги акыркы ири англис ээликтери Гаскондо калат.'),[england,gascony]],
  [1453,1454,L('После поражения во Франции','After defeat in France','Франциядагы жеңилүүдөн кийин'),L('После утраты Гаскони английская корона сохраняет Кале. Длительная война меняет финансы и политическую жизнь королевства.','After losing Gascony, the English crown retains Calais. The long war reshapes royal finances and political life.','Гасконду жоготкондон кийин англис таажысы Калени сактайт. Узак согуш каржы менен саясий жашоону өзгөртөт.'),[england,[[1.6,50.7],[2.1,50.7],[2.1,51.1],[1.6,51.1]]]]
 ]);
 const empire=[[5.2,50],[6.8,47.2],[9.5,46],[12,46],[15.3,46.7],[16.8,48.8],[15.7,51.2],[14.5,53.7],[10.7,54.5],[7.2,53.5]];
 add('late-hre',L('Священная Римская империя','Holy Roman Empire','Ыйык Рим империясы'),[11.08,49.45],'lateEmpire','#b0a37f',[
  [1300,1356,L('Империя князей и городов','Empire of princes and towns','Княздар менен шаарлардын империясы'),L('Императорская власть сосуществует с княжествами, епископствами и вольными городами. Контур показывает центральноевропейское ядро империи.','Imperial authority coexists with principalities, bishoprics and free cities. The outline shows the empire’s central European core.','Император бийлиги княздыктар, епископтуктар жана эркин шаарлар менен катар жашайт. Контур империянын Борбордук Европадагы өзөгүн көрсөтөт.'),empire,{},'influence'],
  [1356,1454,L('Золотая булла и курфюрсты','Golden Bull and prince-electors','Алтын булла жана курфюрсттар'),L('Золотая булла закрепляет порядок выбора короля семью курфюрстами. Империя сохраняет множество политических центров.','The Golden Bull codifies election of the king by seven prince-electors. The empire retains many political centres.','Алтын булла падышаны жети курфюрст шайлоо тартибин бекитет. Империя көп саясий борборлорун сактайт.'),empire,{},'influence']
 ]);
 S('lateBaltic','National Museum — Palace of the Grand Dukes of Lithuania. Important Dates; Vytautas the Great with Anna and Other European Rulers.','https://www.valdovurumai.lt/en/palace-history/i/5363/important-dates/','https://www.valdovurumai.lt/lt/parodos/i/5260/vytautas-didysis-su-ona-ir-kiti-europos-valdovai-xvi-a-pradzios-akvarelese/');
 add('late-lithuania',L('Великое княжество Литовское','Grand Duchy of Lithuania','Улуу Литва княздыгы'),[25.28,54.69],['lateLithuania','lateBaltic'],'#9ba575',[
  [1300,1386,L('Вильнюс и владения Гедиминовичей','Vilnius and the Gediminid domains','Вильнюс жана Гедимин тукумунун ээликтери'),L('Вильнюс становится столичным центром. Князья объединяют литовские и русские земли через завоевания, союзы и династические связи.','Vilnius becomes a capital. Princes bring Lithuanian and Rus lands together through conquest, alliances and dynastic ties.','Вильнюс борборго айланат. Княздар Литва жана Русь жерлерин жортуул, союз жана династиялык байланыш аркылуу бириктирет.'),[[22,54],[24,52.2],[29,51.5],[31.5,53],[30,55.8],[25.5,56.4],[22.5,56]]],
  [1386,1454,L('Династический союз с Польшей','Dynastic union with Poland','Польша менен династиялык союз'),L('Ягайло становится королём Польши; княжество сохраняет свои учреждения. При Витовте продолжается укрепление власти и борьба с Тевтонским орденом.','Jogaila becomes king of Poland; the duchy retains its institutions. Vytautas consolidates power and fights the Teutonic Order.','Ягайло Польша падышасы болот; княздык өз мекемелерин сактайт. Витовт бийликти бекемдеп, Тевтон ордени менен күрөшөт.'),[[22,54],[24,51],[27,48.5],[31,48.5],[34,51.5],[32,55],[28,56],[23,56.2]]]
 ]);
 add('late-poland',L('Королевство Польша','Kingdom of Poland','Польша падышалыгы'),[19.94,50.06],'lateBaltic','#a6807b',[[1300,1454,L('Краков и королевская власть','Kraków and royal power','Краков жана падышалык бийлик'),L('Польская корона объединяет региональные земли. С конца XIV века её связывает с Литвой династический союз, а не полное слияние государств.','The Polish crown unites regional lands. From the late fourteenth century a dynastic union links it to Lithuania without fully merging the states.','Польша таажысы аймактык жерлерди бириктирет. XIV кылымдын аягынан Литва менен толук биригүү эмес, династиялык союз түзүлөт.'),[[16,50.4],[19,49.4],[23.7,49.5],[24.4,51],[22,53.5],[18.5,53.5],[16,52.4]]]]);
 const muscovy=[[35.2,54.2],[38.9,53.7],[41.1,55.1],[40,57.2],[37,57.8],[35,56.4]];
 add('late-moscow',L('Московское княжество','Principality of Moscow','Москва княздыгы'),[37.62,55.75],['lateMoscow','lateJochi'],'#8c9ab1',[[1300,1454,L('Рост княжеского центра','Growth of a princely centre','Княздык борбордун өсүшү'),L('Москва становится важным княжеским и церковным центром Северо-Восточной Руси. Князья укрепляют Кремль и соперничают с соседями под властью Орды.','Moscow grows as a princely and religious centre in northeastern Rus. Its princes fortify the Kremlin and rival neighbouring rulers under Horde overlordship.','Москва Түндүк-Чыгыш Русьтагы маанилүү княздык жана диний борборго айланат. Княздары Кремлди бекемдеп, Ордо үстөмдүгүндө коңшулар менен атаандашат.'),muscovy]]);
 S('lateNovgorod','UNESCO. Historic Monuments of Novgorod and Surroundings.','https://whc.unesco.org/en/list/604/');
 add('late-novgorod',L('Новгородская республика','Novgorod Republic','Новгород республикасы'),[31.28,58.52],'lateNovgorod','#7da39d',[[1300,1454,L('Торговля и городская республика','Trade and an urban republic','Соода жана шаардык республика'),L('Новгород сохраняет самостоятельные учреждения и торговые связи с Балтикой. На карте выделено ядро вокруг Ильменя и Волхова.','Novgorod retains its own institutions and Baltic trade links. The map highlights its core around Lake Ilmen and the Volkhov.','Новгород өз мекемелерин жана Балтика менен соода байланыштарын сактайт. Картада Ильмень менен Волховдун айланасындагы өзөгү белгиленет.'),[[29,57.5],[33.5,57.3],[35.5,59],[34,61],[30.3,60.5],[28.5,59]]]]);

 S('lateYemen','Peter B. Golden. Rasulid Hexaglot. Encyclopaedia Iranica.','https://www.iranicaonline.org/articles/rasulid-hexaglot/');
 add('late-rasulid',L('Расулиды Йемена','Rasulids of Yemen','Йемендеги Расулиддер'),[44.02,13.58],'lateYemen','#85a08b',[[1300,1454,L('Таиз, Тихама и южный Йемен','Ta‘izz, Tihama and southern Yemen','Таиз, Тихама жана түштүк Йемен'),L('Расулиды правят из Таиза, опираясь на Тихаму и южный Йемен. Северные Зейдитские имамы сохраняют отдельную власть.','The Rasulids rule from Ta‘izz, with a base in Tihama and southern Yemen. Northern Zaydi imams retain separate authority.','Расулиддер Тихама менен түштүк Йеменге таянып, Таизден башкарат. Түндүктөгү зейдит имамдары өз бийлигин сактайт.'),[[42.8,12.6],[45.3,12.5],[47,14.1],[46,15.5],[43.4,15.8],[42.7,14.6]],learn(L('Султанский двор в Таизе.','Sultan’s court at Ta‘izz.','Таиздеги султан сарайы.'),L('Земледелие и морская торговля.','Agriculture and maritime commerce.','Дыйканчылык жана деңиз соодасы.'),L('При дворе составляют научные и многоязычные труды.','Scholarly and multilingual works are compiled at court.','Сарайда илимий жана көп тилдүү эмгектер түзүлөт.'))]]);
 S('lateMecca','John L. Meloy. Imperial Power and Maritime Trade: Mecca and Cairo in the Later Middle Ages. Chicago Studies on the Middle East.','https://chicagostudiesonthemiddleeast.uchicago.edu/mecca.html');
 add('late-mecca',L('Шарифы Мекки · Хиджаз','Sharifs of Mecca · Hijaz','Мекке шарифтери · Хижаз'),[39.86,21.42],'lateMecca','#a3a67e',[[1300,1454,L('Священный город и порт Джидды','Holy city and the port of Jeddah','Ыйык шаар жана Жидда порту'),L('Шарифы управляют Меккой в отношениях зависимости и соперничества с Каиром. Хадж и торговля через Джидду связывают Хиджаз с исламским миром.','Sharifs govern Mecca in a relationship of dependence and rivalry with Cairo. Pilgrimage and commerce through Jeddah connect the Hijaz to the Islamic world.','Шарифтер Каирге көз карандылык жана атаандаштык мамиледе Меккени башкарат. Ажылык менен Жидда аркылуу соода Хижазды ислам дүйнөсүнө байланыштырат.'),[[39,20.5],[40.8,20.7],[41,22.7],[39.4,23.3],[38.8,21.7]],{},'influence']]);

 // Named events carry city or battlefield coordinates, not fabricated travel routes.
 const E=(id,y,e,kind,coord,title,text,s)=>event(id,y,e,kind==='state'?'politics':kind,coord,title,text,Array.isArray(s)?s:[s]);
 E('late-bursa-1326',1326,'late-ottoman','war',[29.06,40.19],L('Взятие Бурсы','Capture of Bursa','Бурсанын алынышы'),L('Бурса становится главным османским центром.','Bursa becomes the leading Ottoman centre.','Бурса башкы Осмон борборуна айланат.'),'lateOttoman');
 E('late-gallipoli-1354',1354,'late-ottoman','war',[26.67,40.41],L('Османы в Галлиполи','Ottomans at Gallipoli','Осмондор Галлиполиде'),L('Закрепление у Дарданелл открывает путь дальнейшему расширению в Румелии.','A foothold at the Dardanelles enables further expansion into Rumelia.','Дарданеллдеги таяныч Румелиге кеңейүүгө жол ачат.'),'lateOttoman');
 E('late-ankara-1402',1402,'late-ottoman','war',[32.86,40.15],L('Битва при Анкаре','Battle of Ankara','Анкара салгылашуусу'),L('Победа Тимура над Баязидом I вызывает османское междуцарствие.','Timur’s victory over Bayezid I triggers the Ottoman interregnum.','Тимурдун Баязид Iди жеңиши Осмондордогу так талашка алып келет.'),['lateOttoman','lateTimur']);
 E('late-constantinople-1453',1453,'late-ottoman','war',[28.97,41.01],L('Завоевание Константинополя','Conquest of Constantinople','Константинополдун каратылышы'),L('29 мая войска Мехмеда II берут столицу ар-Рума.','On 29 May, Mehmed II’s forces take the capital of al-Rum.','29-майда Мехмед IIнин аскерлери ар-Румдун борборун алат.'),'lateOttoman');
 E('late-ilkhan-1335',1335,'late-ilkhan','state',[46.3,38.08],L('Распад Ильханата','Fragmentation of the Ilkhanate','Илханаттын ыдырашы'),L('Смерть Абу Саида без наследника усиливает борьбу эмиров за власть.','Abu Sa‘id’s death without an heir intensifies the amirs’ struggle for power.','Абу Саиддин мураскерсиз өлүмү эмирлердин бийлик күрөшүн күчөтөт.'),'lateIlkhan');
 E('late-ming-1368',1368,'late-ming','state',[118.8,32.06],L('Основание Мин','Foundation of the Ming','Миндин негизделиши'),L('Чжу Юаньчжан провозглашает новую династию; двор Юань отступает на север.','Zhu Yuanzhang proclaims a new dynasty; the Yuan court withdraws north.','Чжу Юаньчжан жаңы династияны жарыялайт; Юань сарайы түндүккө чегинет.'),'lateYuan');
 E('late-beijing-1421',1421,'late-ming','state',[116.4,39.9],L('Столица Мин в Пекине','Ming capital at Beijing','Мин борбору Бээжинде'),L('Пекин становится главным столичным центром империи.','Beijing becomes the empire’s principal capital.','Бээжин империянын башкы борборуна айланат.'),'lateYuan');
 E('late-timur-1370',1370,'late-timurid','state',[66.96,39.65],L('Возвышение Тимура','Rise of Timur','Тимурдун көтөрүлүшү'),L('Тимур утверждает власть в Мавераннахре и избирает Самарканд столицей.','Timur establishes power in Transoxiana and chooses Samarkand as his capital.','Тимур Мавераннахрда бийлигин бекемдеп, Самаркандды борбор кылат.'),'lateTimur');
 E('late-delhi-1398',1398,'late-delhi','war',[77.2,28.6],L('Поход Тимура на Дели','Timur’s attack on Delhi','Тимурдун Делиге жортуулу'),L('Разгром войск султаната сопровождается разорением Дели и гибелью населения.','The defeat of the sultanate’s army is followed by the devastation of Delhi and loss of civilian lives.','Султандыктын аскерлери жеңилгенден кийин Дели талкаланып, калк кырылат.'),['lateDelhi','lateTimur']);
 E('late-joseon-1392',1392,'late-joseon','state',[126.55,37.97],L('Основание Чосона','Foundation of Joseon','Чосондун негизделиши'),L('Ли Сонге заменяет династию Корё новой королевской династией.','Yi Seonggye replaces Goryeo with a new royal dynasty.','Ли Сонге Корёну жаңы падышалык династия менен алмаштырат.'),'lateKorea');
 E('late-hundred-years-1337',1337,'late-france','war',[2.35,48.86],L('Начало Столетней войны','Beginning of the Hundred Years’ War','Жүз жылдык согуштун башталышы'),L('Начинается длительная борьба английской и французской корон.','A prolonged struggle between the English and French crowns begins.','Англис жана француз таажыларынын узак күрөшү башталат.'),'lateFrance');
 E('late-agincourt-1415',1415,'late-france','war',[2.14,50.46],L('Битва при Азенкуре','Battle of Agincourt','Азенкур салгылашуусу'),L('Английская армия Генриха V наносит тяжёлое поражение французским войскам.','Henry V’s English army inflicts a major defeat on French forces.','Генрих Vнин англис аскерлери француз аскерлерин оор жеңилүүгө учуратат.'),'lateFrance');
 E('late-france-1453',1453,'late-france','war',[-0.04,44.85],L('Победа при Кастийоне','Victory at Castillon','Кастийондогу жеңиш'),L('Французская победа ведёт к возвращению Гаскони и завершению Столетней войны.','French victory leads to the recovery of Gascony and the end of the Hundred Years’ War.','Француздардын жеңиши Гасконду кайтарууга жана Жүз жылдык согуштун бүтүшүнө алып келет.'),'lateFrance');
 E('late-bull-1356',1356,'late-hre','state',[11.08,49.45],L('Золотая булла','Golden Bull','Алтын булла'),L('Карл IV закрепляет порядок королевских выборов в империи.','Charles IV codifies royal elections in the empire.','Карл IV империядагы падышалык шайлоонун тартибин бекитет.'),'lateEmpire');
 E('late-grunwald-1410',1410,'late-lithuania','war',[20.12,53.49],L('Грюнвальд · Жальгирис','Grunwald · Žalgiris','Грюнвальд · Жальгирис'),L('Войска Ягайло и Витовта побеждают Тевтонский орден.','The forces of Jogaila and Vytautas defeat the Teutonic Order.','Ягайло менен Витовттун аскерлери Тевтон орденин жеңет.'),'lateBaltic');
 S('lateKyrgyzLater','T. Tchoroev (Chorotegin). The Kyrgyz. In: History of Civilizations of Central Asia, vol. V. UNESCO, 2003, pp. 110–112.','https://unesdoc.unesco.org/ark:/48223/pf0000135091','https://turuz.com/storage/Turkologi/Tarix/2015/History_Of_Civilizations_Of_Central_Asia_5.pdf');
 const kyrgyz=c.entries.find(e=>e.id==='late-kyrgyz');
 kyrgyz.phases[1].sources=['lateKyrgyzLater'];
 c.areas.find(a=>a.entry==='late-kyrgyz'&&a.from===1368).sources=['lateKyrgyzLater'];
 add('late-kyrgyz-tianshan',L('Кыргызы Тянь-Шаня','Kyrgyz of the Tian Shan','Теңир-Тоодогу кыргыздар'),[74.5,41.5],'lateKyrgyzLater','#80a78c',[[1300,1454,L('Общины в мире ханств','Communities among the khanates','Хандыктардагы жамааттар'),L('В XIV–XV веках кыргызские группы западного Тянь-Шаня включены в ханства-наследники Чингисидов. Выделен район, а не отдельное государство или точный маршрут переселения.','In the fourteenth–fifteenth centuries, western Tian Shan Kyrgyz groups belong to Chinggisid successor khanates. The outline marks a region, not a separate state or exact migration route.','XIV–XV кылымдарда батыш Теңир-Тоодогу кыргыз топтору Чыңгыз тукумунун мураскер хандыктарына кирген. Контур өзүнчө мамлекетти же так көчүү жолун эмес, аймакты көрсөтөт.'),[[72,40.7],[74,40.4],[76.5,41.2],[77,42.3],[74.3,43],[72,42.2]],{approx:true},'cultural']],'community');
 for(const id of ['late-chagatai','late-transoxiana','late-moghulistan','late-timurid','late-jochi','late-kyrgyz','late-kyrgyz-tianshan'])c.entries.find(e=>e.id===id).centralAsia=true;
 for(const id of ['late-kyrgyz','late-kyrgyz-tianshan'])c.entries.find(e=>e.id===id).kyrgyzHistory=true;

 S('lateSEAsia','The Metropolitan Museum of Art. Southeast Asia, 1000–1400; Southeast Asia, 1400–1600.','https://82nd-and-fifth.metmuseum.org/toah/ht/07/sse.html','https://82nd-and-fifth.metmuseum.org/toah/ht/08/sse.html');
 S('lateViet','UNESCO. Central Sector of the Imperial Citadel of Thang Long — Hanoi; Citadel of the Ho Dynasty.','https://whc.unesco.org/en/list/1328/','https://whc.unesco.org/en/list/1358/');
 const viet=[[104.5,21.9],[106.5,22],[107.7,21],[106.3,19.6],[106.8,17.8],[105.5,18],[104.1,20]];
 add('late-daiviet',L('Дайвьет','Đại Việt','Дайвьет'),[105.84,21.03],['lateViet','lateSEAsia'],'#7eaa8a',[
  [1300,1400,L('Династия Чан','Trần dynasty','Чан династиясы'),L('Династия Чан правит из Тханглонга. Дельта Красной реки остаётся политическим и земледельческим ядром.','The Trần dynasty rules from Thăng Long. The Red River delta remains the political and agricultural core.','Чан династиясы Тханглонгдон башкарат. Кызыл дарыянын дельтасы саясий жана дыйканчылык өзөк бойдон калат.'),viet],
  [1400,1407,L('Династия Хо','Hồ dynasty','Хо династиясы'),L('Династия Хо сменяет Чан. Новый укреплённый центр находится в Тханьхоа.','The Hồ dynasty replaces the Trần. Its new fortified centre is in Thanh Hóa.','Хо династиясы Чанды алмаштырат. Жаңы чептүү борбор Тханьхоада жайгашат.'),viet,{coord:[105.6,20.08]}],
  [1407,1428,L('Власть Мин','Ming occupation','Мин бийлиги'),L('Завоевание Мин прерывает самостоятельность государства. Сопротивление приводит к восстановлению местной династии.','The Ming conquest interrupts the state’s independence. Resistance leads to the restoration of a local dynasty.','Миндин басып алышы мамлекеттин өз алдынчалыгын токтотот. Каршылык жергиликтүү династиянын калыбына келишине алып келет.'),viet,{},'influence'],
  [1428,1454,L('Ранняя династия Ле','Early Lê dynasty','Алгачкы Ле династиясы'),L('Ле Лой учреждает новую династию после окончания минской оккупации. Тханглонг снова становится столичным центром.','Lê Lợi establishes a new dynasty after the Ming occupation ends. Thăng Long again becomes the capital.','Мин баскынчылыгы аяктагандан кийин Ле Лой жаңы династияны негиздейт. Тханглонг кайра борборго айланат.'),viet]
 ]);
 add('late-lanxang',L('Лансанг','Lan Xang','Лансанг'),[102.14,19.88],'lateSEAsia','#94a58a',[[1353,1454,L('Государство на Меконге','Kingdom on the Mekong','Меконгдогу падышалык'),L('Фа Нгум основывает Лансанг. Двор поддерживает буддизм тхеравады и связывает долины Меконга.','Fa Ngum founds Lan Xang. The court supports Theravada Buddhism and connects Mekong valleys.','Фа Нгум Лансангды негиздейт. Сарай тхеравада буддизмин колдоп, Меконг өрөөндөрүн байланыштырат.'),[[100.6,18],[102.5,17.6],[104,18.7],[103.9,21],[101.8,21.5],[100.7,20]]]]);
 add('late-sukhothai',L('Сукхотай','Sukhothai','Сукхотай'),[99.7,17.01],'lateSEAsia','#b3ab78',[[1300,1438,L('Тайское государство и керамика','Thai kingdom and ceramics','Тай мамлекети жана карапа'),L('Сукхотай остаётся центром тайской государственности и производства керамики. Его политическая самостоятельность постепенно уступает Аюттхае.','Sukhothai remains a centre of Thai kingship and ceramic production. Its political autonomy gradually yields to Ayutthaya.','Сукхотай тай мамлекеттүүлүгүнүн жана карапа өндүрүшүнүн борбору бойдон калат. Анын өз алдынчалыгы бара-бара Аюттхаяга өтөт.'),[[98.5,16.3],[100.7,16.4],[101,18.1],[99.4,18.4],[98.3,17.6]]]]);
 add('late-burma',L('Государства Иравади','States of the Irrawaddy','Иравади мамлекеттери'),[96.02,21.86],'lateSEAsia','#ab927f',[[1300,1454,L('После Пагана','After Bagan','Пагандан кийин'),L('После распада Пагана несколько дворов соперничают в долинах Иравади. Верхняя и Нижняя Бирма не составляют единого государства.','After Bagan fragments, several courts compete in the Irrawaddy valleys. Upper and Lower Burma do not form a single state.','Паган ыдырагандан кийин Иравади өрөөндөрүндө бир нече сарай атаандашат. Жогорку жана Төмөнкү Бирма бир мамлекет эмес.'),[[94.5,18],[96.2,17.4],[97.3,20],[96.8,23.5],[94.5,23.3],[94,20]],{},'cultural']],'region');
 E('late-le-1428',1428,'late-daiviet','state',[105.84,21.03],L('Восстановление самостоятельности Дайвьета','Restoration of Đại Việt’s independence','Дайвьеттин өз алдынчалыгынын калыбына келиши'),L('После сопротивления Мин начинается правление династии Ле.','Resistance to the Ming is followed by the Lê dynasty.','Минге каршы күрөштөн кийин Ле династиясынын бийлиги башталат.'),['lateSEAsia','lateViet']);
 E('late-sukhothai-1438',1438,'late-ayutthaya','state',[99.7,17.01],L('Сукхотай входит в Аюттхаю','Sukhothai incorporated into Ayutthaya','Сукхотай Аюттхаяга кошулат'),L('Прежний тайский центр переходит под власть Аюттхаи.','The earlier Thai centre comes under Ayutthaya’s rule.','Мурдагы тай борбору Аюттхаянын бийлигине өтөт.'),'lateSEAsia');
 const ottoman1430=c.entries.find(e=>e.id==='late-ottoman').phases.find(p=>p.from===1430);
 ottoman1430.sources.push('lateThessalonica');
 c.areas.find(a=>a.entry==='late-ottoman'&&a.from===1430).sources.push('lateThessalonica');
 const notes=(id,from,learning)=>Object.assign(c.entries.find(e=>e.id===id).phases.find(p=>p.from===from),learning);
 notes('late-kyrgyz',1300,learn(
  L('Источники описывают местные общины и юаньские гарнизоны.','The sources describe local communities and Yuan garrisons.','Булактар жергиликтүү жамааттарды жана Юань аскер бөлүктөрүн сүрөттөйт.'),
  L('В енисейском районе сочетались скотоводство и земледелие.','Herding and farming coexisted in the Yenisei region.','Энесай аймагында мал чарбачылык менен дыйканчылык айкалышкан.'),
  L('Переселение отдельных групп не означает исчезновения всех кыргызов с Енисея.','Resettling particular groups does not mean all Kyrgyz disappeared from the Yenisei.','Айрым топтордун көчүрүлүшү Энесайдагы бардык кыргыздар жоголгонун билдирбейт.')));
 notes('late-timurid',1405,learn(
  L('Династические владения связывают Герат и Самарканд.','Dynastic domains connect Herat and Samarkand.','Династиялык ээликтер Герат менен Самаркандды байланыштырат.'),
  L('Дворы заказывают здания и рукописи, поддерживая труд мастеров.','Court commissions sustain builders and manuscript artisans.','Сарайдын буюртмалары куруучулар менен кол жазма усталарын колдойт.'),
  L('Самарканд Улугбека становится центром математической астрономии.','Ulugh Beg’s Samarkand becomes a centre of mathematical astronomy.','Улукбектин Самарканды математикалык астрономиянын борборуна айланат.')));
 notes('late-vijayanagara',1400,learn(
  L('Столичный двор связан с храмами и провинциальными правителями.','The capital’s court connects with temples and provincial rulers.','Борбордук сарай ибадатканалар жана аймактык башкаруучулар менен байланышат.'),
  L('Рынки, орошаемые земли и водные сооружения поддерживают столицу.','Markets, irrigated fields and waterworks sustain the capital.','Базарлар, сугат жерлер жана суу курулмалары борборду камсыздайт.'),
  L('Археология Хампи раскрывает городскую жизнь через дома, храмы и дороги.','Hampi’s archaeology reveals urban life through houses, temples and roads.','Хампинин археологиясы үйлөр, ибадатканалар жана жолдор аркылуу шаар жашоосун ачат.')));
 notes('late-majapahit',1300,learn(
  L('Центр двора находится в Тровулане на Яве.','The court is centred at Trowulan on Java.','Сарайдын борбору Явадагы Тровуланда жайгашат.'),
  L('Поселения связаны с земледельческими районами и портами.','Settlements connect with agricultural districts and ports.','Конуштар дыйканчылык аймактар жана порттор менен байланышат.'),
  L('Кирпичные сооружения, керамика и водоёмы сохраняют следы столичной жизни.','Brick structures, pottery and reservoirs preserve traces of life in the capital.','Кыш курулмалар, карапа жана суу сактагычтар борбордогу жашоонун изин сактайт.')));
 return c;
};
