// Africa, 1300–1453. Dates are half-open; polygons describe schematic historical cores.
// Evidence and decisions are recorded in LATE_AFRICA_RESEARCH.md.
module.exports=(c,H)=>{
 const {L,source,phase,entry,continueEntry,area,event}=H;
 const P=(a,b,t,x,s,learning={},extra={})=>phase(a,b,t,x,s,{learning,...extra});
 const colors={'mamluk-late':'#bb9850','bornu-late':'#b97b50','ifat-late':'#58a78e','adal-late':'#8ea95d','kongo-late':'#8972b3','mutapa-late':'#ac8157','khami-late':'#aa7091','ceuta-late':'#7d99bb','timbuktu-late':'#baaa77','djenne-late':'#ae9b78','mogadishu-late':'#5faba0'};
 const A=(id,a,b,p,kind='polity',extra={})=>area(id,a,b,p,{kind,color:colors[id],...extra});
 const E=(id,y,place,kind,coord,t,x,s,extra={})=>event(id,y,place,kind,coord,t,x,s,extra);
 source('lateMamluk','Suzan Yalman. The Art of the Mamluk Period (1250–1517). The Metropolitan Museum of Art, 2001.',['https://www.metmuseum.org/essays/the-art-of-the-mamluk-period-1250-1517']);
 source('lateKanem','Dierk Lange. L’Eviction des Sēfuwa du Kānem et l’origine des Bulāla. The Journal of African History, 1982.',['https://www.cambridge.org/core/journals/journal-of-african-history/article/abs/leviction-des-sefuwa-du-kanem-et-lorigine-des-bulala/622B2FD9FFD57C38B1C12ABCB64818D1']);
 source('lateDongola','Polish Centre of Mediterranean Archaeology, University of Warsaw. Dongola.',['https://pcma.uw.edu.pl/en/2019/04/02/dongola-2/']);
 source('lateHorn','Timothy Insoll. The archaeology of complexity and cosmopolitanism in medieval Ethiopia: an introduction. Antiquity, 2021.',['https://www.cambridge.org/core/journals/antiquity/article/archaeology-of-complexity-and-cosmopolitanism-in-medieval-ethiopia-an-introduction/4F3CD1227F4A53E7732F4DAD9BE21F30']);
 source('lateEthiopiaWars','Bertrand Hirsch. Le récit des guerres du roi ʿAmda Ṣeyon contre les sultanats islamiques, fiction épique du XVe siècle. Annales d’Éthiopie, 2020.',['https://www.researchgate.net/publication/348879933_Le_recit_des_guerres_du_roi_Amda_Seyon_contre_les_sultanats_islamiques_fiction_epique_du_xve_siecle']);
 source('lateAfricaHistory','Roland Oliver (ed.). The Cambridge History of Africa, Volume 3: c. 1050–c. 1600. Cambridge University Press, 1977.',['https://sahistory.org.za/archive/cambridge-history-africa-volume-3']);
 source('lateGHA','D. T. Niane (ed.). General History of Africa, Volume IV: Africa from the Twelfth to the Sixteenth Century. UNESCO, 1984.',['https://sahistory.org.za/archive/general-history-africa-collection']);
 source('lateMaghreb','Museum With No Frontiers. Discover Islamic Art: Historical Timeline, Algeria, 1300–1400.',['https://islamicart.museumwnf.org/hcr.php?begin=0&country=dz&id=object%3BISL%3Buk%3BMus04%3B40%3Bar&start_date=1300']);
 source('lateHafsid','William Caferro and Mohammed Allehbi. “They are like your Arabs”: Giovanni Villani on Ibn Khaldūn’s Tunis (The Ḥafṣid Civil War). Renaissance Quarterly 78, 2025.',['https://www.journals.uchicago.edu/doi/full/10.1017/rqx.2025.23']);
 source('lateKhaldun','Ibn Khaldūn. The Muqaddimah, translated by Franz Rosenthal: Translator’s Introduction.',['https://ignca.gov.in/Asi_data/16173.pdf']);
 source('lateKhami','UNESCO. Khami Ruins National Monument — Statement of Outstanding Universal Value.',['https://whc.unesco.org/en/list/365/']);
 source('lateTimbuktu','UNESCO. Timbuktu — Statement of Outstanding Universal Value.',['https://whc.unesco.org/en/list/119/']);
 source('lateBenin','Art Institute of Chicago. Benin: Kings and Rituals — Oba Ewuare and the Portuguese.',['https://archive.artic.edu/benin/oba/']);
 source('lateIfe','Alice Apley. Ife Terracottas (1000–1400 A.D.). The Metropolitan Museum of Art, 2001.',['https://www.metmuseum.org/essays/ife-terracottas-1000-1400-a-d']);
 source('lateKongo','Royal Museum for Central Africa. The Kongo kingdom.',['https://www.afrikamuseum.be/en/discover/history_articles/kongo-kingdom']);
 source('lateMadagascar','David A. Burney. Finding the Connections: Paleoecology and Ethnobotany in Madagascar. Ethnobotany Research and Applications 3, 2005.',['https://ethnobotanyjournal.org/index.php/era/article/download/94/81/334']);
 source('lateMaliTravels','Ibn Battuta. Travels in Asia and Africa, translated by H. A. R. Gibb. 1929; extracts in the Internet Medieval Sourcebook, Fordham University.',['https://sourcebooks.web.fordham.edu/source/1354-ibnbattuta.asp']);
 source('lateOceanTrade','Graham Connah. African Civilizations: An Archaeological Perspective. Chapter 8: Indian Ocean networks — the East African coast and islands. Cambridge University Press, 2015.',['https://www.cambridge.org/core/books/abs/african-civilizations/indian-ocean-networks-the-east-african-coast-and-islands/90D2611A7386C1FCB020045EBB98B4D9']);
 source('lateCeuta','Museu de Marinha. Efeméride: Tomada de Ceuta.',['https://cultura.marinha.pt/pt/museumarinha_web/multimedia_web/Paginas/efemeride-tomada-de-ceuta-21ago20.aspx']);
 source('lateSis','Gohar Grigoryan Savary. Armenian Colophons on the Takeover of Sis (1375). University of Fribourg.',['https://sonar.ch/documents/324316/files/armenian_colophons_on_the_takeover_of_si.pdf']);
 source('lateDjenne','Susan Keech McIntosh et al. Results of recent excavations at Jenné-jeno and Djenné, Mali. Rice University.',['https://anthropology.rice.edu/sites/g/files/bxs3341/files/inline-files/djennemuseumsite.pdf']);

 // Western Sudan: a large empire and its cities, followed by loss of peripheral control.
 continueEntry('mali',[
  P(1300,1400,L('Мали: мансы и торговые пути','Mali: mansas and trade routes','Мали: мансалар жана соода жолдору'),L('Мали объединяет земли манден и контролирует важные пути к Нигеру и Сахаре. Хадж Мансы Мусы в 1324 году укрепляет связи с Египтом и Хиджазом.','Mali unites Manden lands and controls important routes to the Niger and Sahara. Mansa Musa’s 1324 pilgrimage strengthens ties with Egypt and the Hijaz.','Мали манден жерлерин бириктирип, Нигерге жана Сахарага чыккан маанилүү жолдорду көзөмөлдөйт. Манса Мусанын 1324-жылдагы ажылыгы Египет жана Хижаз менен байланышты бекемдейт.'),['mali','maliFormation'],{government:L('Манса опирается на местных правителей и сбор дани.','The mansa relies on local rulers and tribute.','Манса жергиликтүү башкаруучуларга жана алымга таянат.'),economy:L('Золото, соль, речные рынки и караваны.','Gold, salt, river markets and caravans.','Алтын, туз, дарыя базарлары жана кербендер.')}),
  P(1400,1454,L('Мали и самостоятельные соседи','Mali and independent neighbours','Мали жана өз алдынча коңшулар'),L('Мали сохраняется в западной части Судана, но его власть над северными и восточными городами ослабевает. Гао и Тимбукту имеют собственную политическую историю.','Mali survives in the western Sudan, but its authority over northern and eastern cities weakens. Gao and Timbuktu follow distinct political trajectories.','Мали Батыш Суданда сакталат, бирок түндүк жана чыгыш шаарларындагы бийлиги начарлайт. Гао менен Тимбуктунун өз алдынча саясий тарыхы калыптанат.'),['lateGHA'],{society:L('Города, земледельческие общины и кочевники связаны обменом.','Towns, farming communities and pastoralists remain linked by exchange.','Шаарлар, дыйкан жамааттары жана көчмөндөр товар алмашат.')},{approx:true})
 ]);
 A('mali',1300,1400,[[[-13.9,12],[-13.5,15],[-10,17],[-5.7,17.4],[-2.3,16.8],[0.4,16.4],[-.4,14.3],[-4.3,12],[-7.6,10.2],[-11.2,10.4]]],'influence');
 A('mali',1400,1454,[[[-13.4,12],[-12.6,14.9],[-8,15.8],[-5.5,15],[-4.4,12.3],[-7.6,10.2],[-11.2,10.4]]],'influence');
 continueEntry('gao',[
  P(1300,1400,L('Гао в политическом мире Мали','Gao in Mali’s political world','Гао Малинин саясий чөйрөсүндө'),L('Город на Нигере связывает Сахару с речной торговлей. В XIV веке он входит в орбиту Мали, сохраняя местных правителей.','This Niger city connects Saharan and river trade. During the fourteenth century it lies within Mali’s orbit while retaining local rulers.','Нигердеги шаар Сахара менен дарыя соодасын байланыштырат. XIV кылымда жергиликтүү башкаруучуларын сактап, Малинин таасиринде болот.'),['lateGHA']),
  P(1400,1454,L('Гао · возвышение Сонгая','Gao · the rise of Songhay','Гао · Сонгайдын көтөрүлүшү'),L('Гао становится центром самостоятельной силы Сонгая. Большие завоевания Сонни Али начнутся уже после 1464 года.','Gao becomes the centre of an independent Songhay power. Sonni Ali’s large conquests begin only after 1464.','Гао өз алдынча Сонгай бийлигинин борборуна айланат. Сонни Алинин чоң жортуулдары 1464-жылдан кийин башталат.'),['lateGHA','mali'],{economy:L('Нигер обеспечивает перевозки, рыболовство и обмен.','The Niger sustains transport, fishing and exchange.','Нигер ташууну, балыкчылыкты жана сооданы камсыздайт.')},{approx:true})
 ]);
 A('gao',1300,1400,'previous','settlement');
 A('gao',1400,1454,[[[-1.8,15],[-1.9,16.9],[-.4,17.1],[1.1,16.3],[.8,14.7],[-.3,14.3]]],'polity');
 entry('timbuktu-late','africa','city',[-3.006,16.773],L('Тимбукту','Timbuktu','Тимбукту'),[
  P(1300,1454,L('Город торговли и учёности','A city of commerce and learning','Соода жана илим шаары'),L('У южной кромки Сахары растёт город караванов и мечетей. Строительство Джингеребера связано с Мансой Мусой; в XV веке расширяется роль исламской учёности.','At the Sahara’s southern edge a city of caravans and mosques grows. Djingareyber’s construction is associated with Mansa Musa; Islamic scholarship expands during the fifteenth century.','Сахаранын түштүк четинде кербендер менен мечиттердин шаары өсөт. Жингеребердин курулушу Манса Муса менен байланышат; XV кылымда ислам илиминин ролу кеңейет.'),['lateTimbuktu'],{economy:L('Здесь встречаются караванные и речные торговые сети.','Caravan and river trading networks meet here.','Бул жерде кербен жана дарыя соода тармактары жолугат.')})
 ]);
 A('timbuktu-late',1300,1454,[[[-3.6,16.3],[-3.6,17.1],[-2.5,17.1],[-2.5,16.3]]],'settlement');
 continueEntry('djenne',[P(1300,1400,L('Последний период Дженне-Джено','Djenné-Djeno’s final occupation','Женне-Женонун акыркы жашоо доору'),L('Старый город постепенно теряет жителей. Примерно к 1400 году Дженне-Джено оставлен; соседний Дженне продолжает развиваться.','The old town gradually loses residents. By around 1400 Djenné-Djeno is abandoned; nearby Djenné continues to grow.','Эски шаардын тургундары акырындап азаят. Болжол менен 1400-жылы Женне-Жено ташталат; коңшу Женне өнүгүүсүн улантат.'),['lateDjenne'],{}, {approx:true})]);
 A('djenne',1300,1400,'previous','settlement');
 entry('djenne-late','africa','city',[-4.55,13.906],L('Дженне','Djenné','Женне'),[P(1300,1454,L('Дженне: город внутренней дельты','Djenné: an inland delta town','Женне: ички дельтадагы шаар'),L('К XIV веку соседний со старым Дженне-Джено город участвует в обширной торговле. Дженне становится центром исламской учёности и сохраняется после оставления старого поселения.','By the fourteenth century this town near old Djenné-Djeno participates in extensive trade. Djenné becomes an Islamic scholarly centre and survives the old settlement’s abandonment.','XIV кылымда эски Женне-Женонун жанындагы шаар кеңири соодага катышат. Женне ислам илиминин борборуна айланып, эски конуш ташталгандан кийин да жашайт.'),['djenne','lateDjenne'],{society:L('Городская жизнь зависит от сезонного разлива Нигера.','Urban life depends on the Niger’s seasonal flood.','Шаар турмушу Нигердин мезгилдүү ташкынына байланыштуу.')})]);
 A('djenne-late',1300,1454,[[[-4.9,13.5],[-4.9,14.3],[-4.2,14.3],[-4.2,13.5]]],'settlement');

 // Lake Chad: the dynasty moves west; the old province remains inhabited and governed.
 continueEntry('kanem',[
  P(1300,1385,L('Канем и Борну под властью Сайфава','Kanem and Bornu under the Sayfawa','Сайфава бийлигиндеги Канем жана Борну'),L('Династия Сайфава правит по обе стороны озера Чад. Борну уже стало важной частью её владений; войны в Канеме усиливают западное направление политики.','The Sayfawa rule on both sides of Lake Chad. Bornu is already an important part of their realm; wars in Kanem strengthen the court’s western orientation.','Сайфава династиясы Чад көлүнүн эки тарабын башкарат. Борну алардын маанилүү ээлигине айланган; Канемдеги согуштар батыш багытын күчөтөт.'),['lateKanem']),
  P(1385,1454,L('Канем под властью Булала','Kanem under the Bulala','Булала бийлигиндеги Канем'),L('В конце XIV века Булала вытесняют Сайфава из Канема. Династия Сайфава продолжает править в Борну, к западу от озера.','In the late fourteenth century the Bulala displace the Sayfawa from Kanem. The Sayfawa dynasty continues in Bornu west of the lake.','XIV кылымдын аягында Булала Сайфаваларды Канемден сүрүп чыгарат. Сайфава династиясы көлдүн батышындагы Борнуда бийлигин улантат.'),['lateKanem'],{}, {approx:true})
 ]);
 A('kanem',1300,1385,[[[12.2,11.8],[14.3,11.9],[16.7,13.2],[18,15.5],[16.4,17],[14.3,16.3],[12.4,14.5]]],'influence');
 A('kanem',1385,1454,[[[14.6,13.3],[17.3,12.8],[18.1,15.5],[16.5,16.7],[14.7,15.5]]]);
 entry('bornu-late','africa','state',[12.7,12.8],L('Борну · Сайфава','Bornu · Sayfawa','Борну · Сайфава'),[P(1385,1454,L('Западный центр державы','The dynasty’s western centre','Династиянын батыш борбору'),L('После утраты Канема Сайфава опираются на Борну. Двор и местные правители контролируют населённые земли и пути к странам хауса.','After losing Kanem, the Sayfawa rely on Bornu. The court and local rulers control settled lands and routes towards the Hausa states.','Канемден ажырагандан кийин Сайфава Борнуга таянат. Сарай жана жергиликтүү башкаруучулар калктуу жерлерди, хауса өлкөлөрүнө чыккан жолдорду көзөмөлдөйт.'),['lateKanem','kanem'],{economy:L('Земледелие сочетается с региональной и сахарской торговлей.','Farming combines with regional and Saharan trade.','Дыйканчылык аймактык жана Сахара соодасы менен айкалышат.')},{approx:true})]);
 A('bornu-late',1385,1454,[[[10.8,11.2],[12.5,10.8],[14.2,11.6],[14.2,14.8],[12.3,15],[10.6,13.2]]]);

 // Nile: retain Nubian communities after a court moves and after a mosque is founded.
 continueEntry('dongola',[
  P(1300,1317,L('Поздняя Макурия','Late Makuria','Кийинки Макурия'),L('Донгола остаётся царским городом Нубии. Борьба за престол и вмешательство Египта ослабляют царство.','Dongola remains a Nubian royal city. Succession struggles and Egyptian intervention weaken the kingdom.','Донгола Нубиянын падышалык шаары бойдон калат. Так талаш жана Египеттин кийлигишүүсү падышалыкты начарлатат.'),['lateDongola','lateAfricaHistory']),
  P(1317,1364,L('Донгола: дворец становится мечетью','Dongola: a palace becomes a mosque','Донгола: сарай мечитке айланат'),L('В 1317 году тронный зал превращён в мечеть. Христианские общины продолжают существовать; история населения не заканчивается сменой религии правителей.','In 1317 the throne hall is converted into a mosque. Christian communities continue; a change in rulers’ religion does not end the population’s history.','1317-жылы так залы мечитке айланат. Христиан жамааттары жашоосун улантат; өкүмдарлардын дини өзгөргөндө калктын тарыхы токтобойт.'),['lateDongola']),
  P(1364,1454,L('Донгола после ухода царского двора','Dongola after the royal court’s departure','Падыша сарайы кеткенден кийинки Донгола'),L('Царский двор покидает Донголу в 1364 году. Город и долина Нила продолжают жить, а политическая власть становится более раздробленной.','The royal court leaves Dongola in 1364. The town and Nile valley remain inhabited as political authority becomes more fragmented.','Падыша сарайы 1364-жылы Донголадан кетет. Шаар менен Нил өрөөнүндө турмуш уланып, саясий бийлик майда бөлүктөргө ажырайт.'),['lateDongola'])
 ]);
 A('dongola',1300,1317,'previous');
 A('dongola',1317,1364,[[[29.6,17],[30.5,17],[31.1,18.5],[30.5,20.3],[29.7,20],[29.3,18.6]]],'influence');
 A('dongola',1364,1454,[[[29.7,17.3],[30.5,17.3],[30.9,18.6],[30.3,19.1],[29.7,18.5]]],'settlement');
 continueEntry('alwa',[P(1300,1454,L('Алва · Соба на Голубом Ниле','Alwa · Soba on the Blue Nile','Алва · Көк Нилдеги Соба'),L('Алва сохраняет христианскую традицию южной Нубии. Соба остаётся важным центром у слияния нильских путей; позднесредневековая политическая история известна фрагментарно.','Alwa preserves southern Nubia’s Christian tradition. Soba remains an important centre near converging Nile routes; its late medieval political history is fragmentary.','Алва түштүк Нубиянын христиан салтын сактайт. Соба Нил жолдору кошулган жердеги маанилүү борбор; кийинки орто кылымдагы саясий тарыхы үзүндүлүү белгилүү.'),['alwa','lateAfricaHistory'])]);
 A('alwa',1300,1454,'previous','influence');

 const mamlukCore=[[[25.2,31.5],[29.8,31.7],[31.8,31.5],[34.2,31.1],[35.2,33],[35.7,35],[36,36.6],[37.2,36.8],[38.3,35.8],[39,34.5],[37.3,32.2],[36,30],[34.9,29.5],[34,27.6],[35.1,24],[33,22],[30,22],[27.5,24.3],[26.2,28]]];
 entry('mamluk-late','africa','state',[31.24,30.04],L('Мамлюкский султанат Египта и аш-Шама','Mamluk Sultanate of Egypt and al-Sham','Египет жана аш-Шам Мамлюк султандыгы'),[
  P(1300,1382,L('Бахритские мамлюки','Bahri Mamluks','Бахри мамлюктары'),L('Султаны Каира правят Египтом и аш-Шамом. Военная элита мамлюков защищает торговые пути и покровительствует мечетям, медресе и больницам.','Cairo’s sultans govern Egypt and al-Sham. The Mamluk military elite protects trading routes and supports mosques, madrasas and hospitals.','Каир султандары Египет менен аш-Шамды башкарат. Мамлюктардын аскердик катмары соода жолдорун коргоп, мечиттерди, медреселерди жана ооруканаларды колдойт.'),['lateMamluk'],{economy:L('Нильское земледелие и торговля между Средиземноморьем и Индийским океаном.','Nile agriculture and trade between the Mediterranean and Indian Ocean.','Нилдеги дыйканчылык, Жер Ортолук деңиз менен Инди океанынын ортосундагы соода.')}),
  P(1382,1454,L('Бурджитские мамлюки','Burji Mamluks','Буржи мамлюктары'),L('С воцарением Баркука начинается бурджитский период. Султанат переживает борьбу эмиров, эпидемии и вторжение Тимура в аш-Шам, сохраняя власть в Египте.','Barquq’s accession begins the Burji period. The sultanate endures conflicts among emirs, epidemics and Timur’s invasion of al-Sham while retaining Egypt.','Баркук такка келгенде Буржи доору башталат. Султандык эмирлердин тирешин, жугуштуу ооруларды жана Тимурдун аш-Шамга басып киришин баштан өткөрүп, Египеттеги бийлигин сактайт.'),['lateMamluk'])
 ]);
 A('mamluk-late',1300,1375,mamlukCore);
 const mamlukNorth=JSON.parse(JSON.stringify(mamlukCore)); mamlukNorth[0].splice(6,1,[35.3,36.6],[34.7,36.8],[35.2,37.3],[36.7,37.3]);
 A('mamluk-late',1375,1382,mamlukNorth,'polity',{sources:['lateMamluk','lateSis']});
 A('mamluk-late',1382,1454,mamlukNorth,'polity',{sources:['lateMamluk','lateSis']});
 continueEntry('cairo',[P(1300,1454,L('Каир · столица мамлюков','Cairo · Mamluk capital','Каир · Мамлюк борбору'),L('Каир — столица султаната, центр ремёсел, исламской учёности и благотворительных учреждений. Нил связывает его с сельскохозяйственными районами Египта.','Cairo is the sultanate’s capital and a centre of crafts, Islamic learning and charitable institutions. The Nile links it with Egypt’s farming regions.','Каир — султандыктын, кол өнөрчүлүктүн, ислам илиминин жана кайрымдуулук мекемелеринин борбору. Нил аны Египеттин дыйканчылык аймактары менен байланыштырат.'),['cairo','lateMamluk'])]);

 // Horn of Africa: neighbouring states and political cores, not modern national borders.
 continueEntry('ethiopia',[
  P(1300,1314,L('Соломонова династия · аль-Хабаша','Solomonic dynasty · al-Habasha','Сулайман династиясы · аль-Хабаша'),L('Христианское царство укрепляется в Эфиопском нагорье. Его правители соперничают с соседними мусульманскими султанатами за дань и торговые пути.','The Christian kingdom consolidates in the Ethiopian highlands. Its rulers compete with neighbouring Muslim sultanates over tribute and trade routes.','Христиан падышалыгы Эфиопия тоолорунда бекемделет. Өкүмдарлары коңшу мусулман султандыктары менен алым жана соода жолдору үчүн атаандашат.'),['ethiopia','lateHorn']),
  P(1314,1434,L('Расширение царства Эфиопии','Expansion of the Ethiopian kingdom','Эфиопия падышалыгынын кеңейиши'),L('При Амдэ-Сыйоне и его преемниках усиливается влияние царства к югу от прежнего ядра. Войны с Ифатом чередуются с подчинением местных правителей и торговыми связями.','Under Amda Seyon and his successors the kingdom extends influence south of its older core. Warfare with Ifat alternates with local submission and commercial contacts.','Амдэ-Сыйондун жана анын мураскерлеринин тушунда падышалыктын таасири түштүккө жайылат. Ифат менен согуштар жергиликтүү өкүмдарлардын баш ийиши жана соода байланыштары менен алмашат.'),['lateEthiopiaWars','lateHorn']),
  P(1434,1454,L('Зара-Якоб и царская власть','Zara Yaqob and royal authority','Зара-Якоб жана падышалык бийлик'),L('Зара-Якоб укрепляет монархию и церковную организацию. На восточной границе продолжаются столкновения с султанатом Адаль.','Zara Yaqob strengthens the monarchy and church organisation. Conflict with the Adal sultanate continues on the eastern frontier.','Зара-Якоб падышалык бийликти жана чиркөө уюмун бекемдейт. Чыгыш чек арада Адаль султандыгы менен кагылышуулар уланат.'),['lateGHA','ethiopia'])
 ]);
 A('ethiopia',1300,1314,'previous');
 A('ethiopia',1314,1434,[[[36.2,8.6],[38.2,8.1],[39.6,9.5],[39.6,11.5],[39.8,14.2],[38.3,14.8],[36.7,13.3],[35.7,10.7]]],'influence');
 A('ethiopia',1434,1454,[[[36.2,8.6],[38.2,8.1],[39.6,9.5],[39.6,11.5],[39.8,14.2],[38.3,14.8],[36.7,13.3],[35.7,10.7]]],'influence');
 entry('ifat-late','africa','state',[39.75,9.65],L('Султанат Ифат','Sultanate of Ifat','Ифат султандыгы'),[P(1300,1376,L('Ифат · Валашма','Ifat · Walasma','Ифат · Валашма'),L('Мусульманская династия Валашма контролирует земли восточной окраины нагорья и торговые связи к Зейле. Ифат соперничает с христианским царством Эфиопии.','The Muslim Walasma dynasty controls lands on the highlands’ eastern edge and commercial links towards Zeila. Ifat competes with the Christian Ethiopian kingdom.','Мусулман Валашма династиясы тоолордун чыгыш четин жана Зейлага кеткен соода байланыштарын көзөмөлдөйт. Ифат Эфиопиянын христиан падышалыгы менен атаандашат.'),['lateHorn','lateEthiopiaWars'])]);
 A('ifat-late',1300,1376,[[[39.4,8.8],[40.5,8.9],[41.1,10.2],[40.2,11.1],[39.4,10.4]]],'influence');
 entry('adal-late','africa','state',[42.5,9.8],L('Адаль · Валашма','Adal · Walasma','Адаль · Валашма'),[P(1376,1454,L('Восточный центр власти Валашма','The eastern centre of Walasma power','Валашма бийлигинин чыгыш борбору'),L('В конце XIV–XV веках центры власти Валашма смещаются на восток, в область Адаля. Султаны опираются на мусульманские города и связи с портом Зейла.','In the late fourteenth and fifteenth centuries Walasma power shifts east into Adal. Its sultans rely on Muslim towns and connections with the port of Zeila.','XIV кылымдын аягы менен XV кылымда Валашма бийлиги чыгыштагы Адаль аймагына жылат. Султандар мусулман шаарларына жана Зейла порту менен байланышка таянат.'),['lateHorn','lateGHA'],{economy:L('Караванные пути соединяют внутренние земли с Аденским заливом.','Caravan routes link the interior with the Gulf of Aden.','Кербен жолдору ички аймактарды Аден булуңуна байланыштырат.')},{approx:true})]);
 A('adal-late',1376,1454,[[[41,8.8],[43.3,8.7],[44.1,9.8],[43.6,11.5],[42.7,11.4],[41.7,10.1]]],'influence');
 continueEntry('lalibela',[P(1300,1454,L('Лалибэла · место паломничества','Lalibela · a pilgrimage centre','Лалибэла · зыярат борбору'),L('После смены династии скальные церкви сохраняют значение. Лалибэла остаётся религиозным центром Эфиопии.','After the dynastic change the rock-hewn churches retain their importance. Lalibela remains an Ethiopian religious centre.','Династия алмашкандан кийин аска чиркөөлөрүнүн мааниси сакталат. Лалибэла Эфиопиянын диний борбору бойдон калат.'),['lalibela'])]);

 // Indian Ocean ports and southern African centres.
 continueEntry('kilwa',[P(1300,1454,L('Килва · султан и морская торговля','Kilwa · sultan and maritime trade','Килва · султан жана деңиз соодасы'),L('Килва достигает большого расцвета в XIV веке. Каменные мечети и дворец Хусуни-Кубва отражают богатство султанского города.','Kilwa reaches great prosperity in the fourteenth century. Stone mosques and Husuni Kubwa palace reflect the wealth of this sultan’s city.','Килва XIV кылымда чоң гүлдөөгө жетет. Таш мечиттер жана Хусуни-Кубва сарайы султан шаарынын байлыгын көрсөтөт.'),['kilwa'],{economy:L('Золото и слоновая кость поступают к морским рынкам через прибрежные связи.','Gold and ivory reach maritime markets through coastal connections.','Алтын менен пил сөөгү жээк байланыштары аркылуу деңиз базарларына жетет.')})]);
 A('kilwa',1300,1454,'previous','polity');
 continueEntry('gedi',[P(1300,1454,L('Геди · рост суахилийского города','Gedi · a growing Swahili town','Геди · өсүп жаткан суахили шаары'),L('Геди расширяется как город суахили. Каменные дома, мечети и колодцы отражают развитие городской жизни и торговли Индийского океана.','Gedi expands as a Swahili town. Stone houses, mosques and wells reflect urban development and Indian Ocean trade.','Геди суахили шаары катары кеңейет. Таш үйлөр, мечиттер жана кудуктар шаар турмушунун жана Инди океаны соодасынын өнүгүшүн көрсөтөт.'),['gediHeritage'])]);
 A('gedi',1300,1454,'previous','settlement');
 entry('mogadishu-late','africa','city',[45.34,2.04],L('Могадишо · Макадишу','Mogadishu · Maqadishu','Могадишо · Макадишу'),[P(1300,1454,L('Город на путях Индийского океана','An Indian Ocean trading city','Инди океанынын жолдорундагы шаар'),L('Могадишо — мусульманский порт с собственным правителем, рынками и ремеслом. Морские связи соединяют побережье с Аравией и Индией.','Mogadishu is a Muslim port with its own ruler, markets and crafts. Maritime routes connect the coast with Arabia and India.','Могадишо — өз өкүмдары, базарлары жана кол өнөрчүлүгү бар мусулман порту. Деңиз жолдору жээкти Аравия жана Индия менен байланыштырат.'),['lateOceanTrade'])]);
 A('mogadishu-late',1300,1454,[[[44.7,1.3],[45.1,2.6],[45.9,3],[46.2,2.4],[45.4,1.7]]],'settlement');
 continueEntry('zimbabwe',[
  P(1300,1450,L('Великий Зимбабве · столица царства','Great Zimbabwe · a kingdom’s capital','Улуу Зимбабве · падышалыктын борбору'),L('В XIV веке возводится Большая ограда. Город служит центром государства, связанного с золотом плато и торговлей восточного побережья.','The Great Enclosure is built in the fourteenth century. The city is a state centre connected with plateau gold and eastern coastal trade.','XIV кылымда Чоң коргон курулат. Шаар платонун алтыны жана чыгыш жээктин соодасы менен байланышкан мамлекеттин борбору болот.'),['zimbabwe'],{society:L('Каменные ограды организуют пространство элиты; большинство домов построено из глины и дерева.','Stone enclosures organise elite space; most houses are built of earth and wood.','Таш коргондор ак сөөктөрдүн мейкиндигин бөлөт; көпчүлүк үйлөр топурак жана жыгачтан курулат.')}),
  P(1450,1454,L('Смена политических центров','Changing political centres','Саясий борборлордун алмашуусу'),L('Около середины XV века значение прежней столицы уменьшается. Усиливаются Хами на западе и власть Мвенемутапы на севере.','Around the mid-fifteenth century the old capital loses importance. Khami rises in the west and Mwenemutapa power develops in the north.','XV кылымдын ортосунда эски борбордун мааниси төмөндөйт. Батышта Хами, түндүктө Мвенемутапа бийлиги күчөйт.'),['zimbabwe','lateKhami','lateGHA'],{}, {approx:true})
 ]);
 A('zimbabwe',1300,1430,[[[28.7,-19.7],[29.5,-18.1],[31.5,-17.8],[33,-19],[32.5,-21.4],[30.3,-22.3],[28.8,-21.2]]],'influence');
 A('zimbabwe',1430,1450,[[[29.8,-19.2],[31.8,-19],[32.5,-20],[32,-21.4],[30.3,-21.8],[29.5,-20.8]]],'influence');
 A('zimbabwe',1450,1454,[[[30.4,-20.8],[31.4,-20.8],[31.5,-19.9],[30.5,-19.7]]],'settlement');
 entry('mutapa-late','africa','state',[31.55,-16.7],L('Мвенемутапа · северное плато','Mwenemutapa · northern plateau','Мвенемутапа · түндүк плато'),[P(1430,1454,L('Возникновение северного царства','Emergence of a northern kingdom','Түндүк падышалыктын пайда болушу'),L('В XV веке к югу от Замбези формируется власть Мвенемутапы. Предания связывают её начало с Мутотой; показано северное ядро, а не владения поздней империи.','In the fifteenth century Mwenemutapa authority develops south of the Zambezi. Traditions associate its beginnings with Mutota; the map shows the northern core, before later imperial expansion.','XV кылымда Замбезинин түштүгүндө Мвенемутапа бийлиги түзүлөт. Салттуу баяндар анын башталышын Мутота менен байланыштырат; картада кийинки империя эмес, түндүктөгү өзөгү көрсөтүлгөн.'),['lateGHA','lateAfricaHistory'],{}, {approx:true})]);
 A('mutapa-late',1430,1454,[[[30.2,-17.9],[30.5,-16],[32,-15.7],[33.1,-16.7],[32.3,-18.3]]],'influence');
 entry('khami-late','africa','state',[28.42,-20.16],L('Хами · Торва','Khami · Torwa','Хами · Торва'),[P(1450,1454,L('Возвышение Хами','The rise of Khami','Хаминин көтөрүлүшү'),L('Около середины XV века Хами становится новым политическим центром на западе плато. Каменные террасы и торговые находки характеризуют развитие города.','Around the mid-fifteenth century Khami becomes a new political centre in the western plateau. Stone terraces and trade finds characterise the town’s development.','XV кылымдын ортосунда Хами платонун батышындагы жаңы саясий борбор болот. Таш тектирлер жана соода табылгалары шаардын өнүгүшүн көрсөтөт.'),['lateKhami'],{}, {approx:true})]);
 A('khami-late',1450,1454,[[[27.5,-20.9],[27.4,-19.6],[28.7,-19.2],[29.4,-20.1],[28.8,-21.2]]],'influence');
 continueEntry('madagascar',[P(1300,1454,L('Мадагаскар · порты и внутренние общины','Madagascar · ports and inland communities','Мадагаскар · порттор жана ички жамааттар'),L('Прибрежные поселения участвуют в торговле Индийского океана. Земледелие и скотоводство меняют внутренние ландшафты; единого островного государства ещё нет.','Coastal settlements participate in Indian Ocean trade. Farming and pastoralism reshape inland landscapes; there is no unified island state.','Жээк конуштары Инди океанынын соодасына катышат. Дыйканчылык жана мал чарбачылыгы ички ландшафттарды өзгөртөт; аралда бирдиктүү мамлекет али жок.'),['lateMadagascar','madagascar'],{society:L('Местные общины связаны морскими и внутренними путями.','Local communities are connected by maritime and inland routes.','Жергиликтүү жамааттар деңиз жана ички жолдор менен байланышат.')})]);
 A('madagascar',1300,1454,'previous','settlement');

 // Gulf of Guinea and Congo: states continue independently of the Sahel empires.
 continueEntry('ife',[
  P(1300,1400,L('Ифе · искусство и царская власть','Ife · art and royal authority','Ифе · искусство жана падышалык бийлик'),L('Ифе — городской и сакральный центр йоруба. Терракоты и металлическая скульптура отражают царскую власть, ритуалы и мастерство ремесленников.','Ife is an urban and sacred Yoruba centre. Terracotta and metal sculpture reflect kingship, ritual and skilled craftsmanship.','Ифе — йорубалардын шаардык жана ыйык борбору. Терракота жана металл айкелдер падышалык бийликти, ырымдарды жана усталардын чеберчилигин көрсөтөт.'),['lateIfe','ife']),
  P(1400,1454,L('Ифе · продолжающийся сакральный центр','Ife · an enduring sacred centre','Ифе · сакталып калган ыйык борбор'),L('Ифе сохраняет религиозный и династический авторитет среди обществ йоруба. Городская жизнь продолжается после основного периода знаменитой средневековой скульптуры.','Ife retains religious and dynastic authority among Yoruba societies. Urban life continues after the main period of its celebrated medieval sculpture.','Ифе йоруба коомдорунун арасында диний жана династиялык кадыр-баркын сактайт. Атактуу орто кылымдык айкелдердин негизги доорунан кийин да шаар турмушу уланат.'),['ife','lateGHA'])
 ]);
 A('ife',1300,1400,'previous');
 A('ife',1400,1454,'previous');
 continueEntry('benin',[
  P(1300,1440,L('Бенин · город и двор оба','Benin · town and the oba’s court','Бенин · шаар жана оба сарайы'),L('Бенин развивается как политический центр эдо. Двор оба, ремесло и окружающие земледельческие поселения образуют основу царства.','Benin develops as an Edo political centre. The oba’s court, crafts and surrounding farming settlements form the kingdom’s foundation.','Бенин эдо элинин саясий борбору катары өнүгөт. Оба сарайы, кол өнөрчүлүк жана айланадагы дыйкан конуштары падышалыктын негизин түзөт.'),['beninArchaeology','beninDynasty']),
  P(1440,1454,L('Эвуаре · укрепление царства','Ewuare · strengthening the kingdom','Эвуаре · падышалыктын бекемделиши'),L('Около 1440 года начинается правление Эвуаре. С ним связывают укрепление царской власти, перестройку столицы и расширение влияния Бенина.','Ewuare’s reign begins around 1440. He is associated with stronger royal authority, rebuilding the capital and expanding Benin’s influence.','Болжол менен 1440-жылы Эвуаренин башкаруусу башталат. Анын ысымы падышалык бийликтин бекемделиши, борбордун кайра курулушу жана Бениндин таасиринин кеңейиши менен байланышат.'),['lateBenin'],{}, {approx:true})
 ]);
 A('benin',1300,1440,'previous');
 A('benin',1440,1454,[[[4.5,5.7],[4.5,6.8],[5.9,7.2],[6.7,6.5],[6.2,5.4],[5.2,5.3]]],'influence');
 entry('kongo-late','africa','state',[14.24,-6.27],L('Царство Конго','Kingdom of Kongo','Конго падышалыгы'),[P(1400,1454,L('Конго · объединение вокруг Мбанза-Конго','Kongo · unification around Mbanza Kongo','Конго · Мбанза-Конгонун айланасында биригүү'),L('В конце XIV века складывается царство Конго. Союзы правящих групп объединяют территории к югу от нижнего Конго вокруг будущей столицы.','The Kongo kingdom takes shape in the late fourteenth century. Alliances among ruling groups unite lands south of the lower Congo around the emerging capital.','XIV кылымдын аягында Конго падышалыгы калыптанат. Башкаруучу топтордун союздары төмөнкү Конгонун түштүгүндөгү жерлерди жаңы борбордун айланасына бириктирет.'),['lateKongo'],{government:L('Власть царя связана с провинциальными и местными правителями.','Royal authority is linked to provincial and local rulers.','Падышанын бийлиги аймактык жана жергиликтүү башкаруучулар менен байланышат.')},{approx:true})]);
 A('kongo-late',1400,1454,[[[12.7,-5.9],[14.4,-5.2],[15.6,-5.8],[15.8,-7.2],[14,-8],[12.5,-7.2]]],'influence');

 // Maghreb: conquest does not silently leave the defeated polity on the same ground.
 const morocco=[[[-9.8,29.5],[-9.3,32.1],[-6.9,34.9],[-5.3,35.85],[-2.1,35.1],[-1.8,32.5],[-4.3,30.2],[-7,28.9]]];
 const tlemcen=[[[-2.1,35.1],[.2,36.1],[2.9,36.8],[4.8,36.5],[4.1,34.2],[1.5,32.9],[-1.8,32.5]]];
 const ifriqiya=[[[4.8,36.5],[7.7,37],[10.2,37.2],[11.1,35.7],[10,34],[11.5,33],[13.5,32.8],[14.6,31.4],[12.1,30.6],[8.7,31.5],[6.3,33],[4.1,34.2]]];
 continueEntry('marinid',[P(1300,1415,L('Мариниды · борьба за Магриб','Marinids · contest for the Maghreb','Мариниддер · Магриб үчүн күрөш'),L('Мариниды правят из Феса. В XIV веке их походы временно подчиняют Тлемсен и Тунис; восстановить долговременное единство Магриба не удаётся.','The Marinids rule from Fez. Their fourteenth-century campaigns temporarily subdue Tlemcen and Tunis, but lasting Maghreb unity is not restored.','Мариниддер Фестен башкарат. XIV кылымдагы жортуулдары Тлемсен менен Тунисти убактылуу багынтат, бирок Магрибдин туруктуу биримдиги калыбына келбейт.'),['lateMaghreb','lateHafsid'],{society:L('Султанские медресе поддерживают учёность и городской престиж.','Sultanic madrasas support scholarship and urban prestige.','Султандык медреселер илимди жана шаардын кадыр-баркын колдойт.')}),P(1415,1454,L('Мариниды после потери Сеуты','Marinids after the loss of Ceuta','Сеутадан ажыраган Мариниддер'),L('В 1415 году Португалия захватывает Сеуту. Маринидское государство сохраняется, но власть султанов всё сильнее зависит от визирей и региональных сил.','Portugal captures Ceuta in 1415. The Marinid state survives, but sultanic power increasingly depends on viziers and regional forces.','1415-жылы Португалия Сеутаны басып алат. Маринид мамлекети сакталат, бирок султандардын бийлиги вазирлерге жана аймактык күчтөргө көбүрөөк көз каранды болот.'),['lateAfricaHistory'])]);
 const zText=L('Зайяниды правят Тлемсеном, важным узлом средиземноморской и сахарской торговли. Их самостоятельность прерывают маринидские завоевания.','The Zayyanids rule Tlemcen, a node of Mediterranean and Saharan commerce. Marinid conquests interrupt their independence.','Зайяниддер Жер Ортолук деңиз жана Сахара соодасынын түйүнү Тлемсенди башкарат. Маринид жортуулдары алардын өз алдынчалыгын үзгүлтүккө учуратат.');
 continueEntry('zayyanid',[[1300,1337],[1348,1352],[1359,1454]].map(([a,b])=>P(a,b,L('Зайянидский Тлемсен','Zayyanid Tlemcen','Зайяниддик Тлемсен'),zText,['lateMaghreb','lateAfricaHistory'])));
 const hText=L('Хафсидские правители опираются на Тунис и города Ифрикии. Торговля связывает их с Сахарой и Средиземноморьем; единство владений меняется из-за династических войн.','Hafsid rulers rely on Tunis and Ifriqiyan cities. Commerce links them to the Sahara and Mediterranean; dynastic wars change the unity of their domains.','Хафсид өкүмдарлары Туниске жана Ифрикия шаарларына таянат. Соода аларды Сахара жана Жер Ортолук деңиз менен байланыштырат; династиялык согуштар ээликтердин биримдигин өзгөртөт.');
 continueEntry('hafsid',[[1300,1347],[1348,1357],[1358,1370],[1370,1454]].map(([a,b])=>P(a,b,a>=1370?L('Восстановление Хафсидской Ифрикии','Recovery of Hafsid Ifriqiya','Хафсид Ифрикиясын калыбына келтирүү'):L('Хафсиды · Тунис и Ифрикия','Hafsids · Tunis and Ifriqiya','Хафсиддер · Тунис жана Ифрикия'),hText,['lateHafsid','lateKhaldun'])));
 const maghrebFrames=[[1300,1337,false,false],[1337,1347,true,false],[1347,1348,true,true],[1348,1352,false,false],[1352,1357,true,false],[1357,1358,true,true],[1358,1359,true,false],[1359,1370,false,false],[1370,1415,false,false],[1415,1454,false,false]];
 // Adjacent regional outlines are joined into one exterior ring under one ruler.
 const maghrebOutline=(z,h)=>!z?morocco:[[
  ...morocco[0].slice(0,5),...tlemcen[0].slice(1,4),
  ...(h?ifriqiya[0].slice(1):[tlemcen[0][4]]),
  tlemcen[0][5],...morocco[0].slice(5)
 ]];
 for(const [a,b,z,h] of maghrebFrames){A('marinid',a,b,maghrebOutline(z,h));if(!z)A('zayyanid',a,b,tlemcen);if(!h)A('hafsid',a,b,ifriqiya);}
 continueEntry('marrakesh',[P(1300,1454,L('Марракеш при Маринидах','Marrakesh under the Marinids','Мариниддер тушундагы Марракеш'),L('Марракеш сохраняет рынки, мечети и региональное значение, хотя главный двор Маринидов находится в Фесе.','Marrakesh retains markets, mosques and regional importance, although the main Marinid court resides in Fez.','Марракеш базарларын, мечиттерин жана аймактык маанисин сактайт, бирок Мариниддердин негизги сарайы Фесте жайгашат.'),['marrakesh','maghreb'])]);
 continueEntry('kairouan',[P(1300,1454,L('Кайруан · учёность и региональные связи','Kairouan · scholarship and regional links','Кайруан · илим жана аймактык байланыштар'),L('Кайруан сохраняет религиозное значение в Ифрикии. Его история связана с Хафсидами, городскими общинами и племенами внутренних районов.','Kairouan retains religious importance in Ifriqiya. Its history involves Hafsid rulers, urban communities and inland tribes.','Кайруан Ифрикиядагы диний маанисин сактайт. Анын тарыхы Хафсиддер, шаар жамааттары жана ички аймактардын уруулары менен байланышат.'),['kairouan','lateKhaldun'])]);
 entry('ceuta-late','africa','city',[-5.32,35.89],L('Сеута · Сабта','Ceuta · Sabta','Сеута · Сабта'),[P(1415,1454,L('Португальский опорный город','A Portuguese stronghold','Португалиянын таяныч шаары'),L('Захват Сеуты в 1415 году создаёт португальский плацдарм у Гибралтарского пролива. За городом продолжаются земли мусульманского Магриба.','The capture of Ceuta in 1415 creates a Portuguese foothold at the Strait of Gibraltar. The Muslim Maghreb continues beyond the city.','1415-жылы Сеутанын алынышы Гибралтар кысыгында Португалиянын таяныч жерин түзөт. Шаардан ары мусулман Магрибинин жерлери уланат.'),['lateCeuta'])]);
 A('ceuta-late',1415,1454,[[[-5.43,35.8],[-5.43,35.96],[-5.24,35.96],[-5.24,35.8]]],'settlement');

 // Events are placed where they happened, or explicitly identified as regional markers.
 E('late-musa-hajj',1324,'mali','diplomacy',[31.24,30.04],L('Манса Муса в Каире','Mansa Musa in Cairo','Манса Муса Каирде'),L('По пути в Мекку правитель Мали посещает Каир. Его паломничество делает державу Мали широко известной в исламском мире.','Travelling to Mecca, Mali’s ruler visits Cairo. His pilgrimage brings Mali widespread recognition in the Islamic world.','Меккеге бара жатып Малинин өкүмдары Каирге келет. Анын ажылыгы Мали мамлекетин ислам дүйнөсүнө кеңири таанытат.'),['mali']);
 E('late-battuta-mali',1352,'mali','culture',[-8.5,12],L('Ибн Баттута в Мали','Ibn Battuta in Mali','Ибн Баттута Малиде'),L('Путешественник посещает Мали в 1352–1353 годах и описывает двор и повседневную жизнь. На карте отмечена область Манден; точное местоположение посещённой столицы обсуждается.','The traveller visits Mali in 1352–1353 and describes the court and daily life. The marker identifies Manden; the precise location of the capital he visited is debated.','Саякатчы 1352–1353-жылдары Малиге барып, сарайды жана күнүмдүк турмушту сүрөттөйт. Белги Манден аймагын көрсөтөт; ал барган борбордун так орду талкууланат.'),['lateMaliTravels'],{to:1353});
 E('late-dongola-mosque',1317,'dongola','culture',[30.44,18.22],L('Мечеть в тронном зале Донголы','A mosque in Dongola’s throne hall','Донголанын так залындагы мечит'),L('Тронный зал старого дворца переоборудован в мечеть. Это датированное свидетельство изменения религиозной жизни города.','The old palace’s throne hall is converted into a mosque, a dated witness to changing religious life in the town.','Эски сарайдын так залы мечитке айландырылат. Бул шаардын диний турмушундагы өзгөрүүнүн даталанган далили.'),['lateDongola']);
 E('late-dongola-court',1364,'dongola','politics',[30.44,18.22],L('Царский двор покидает Донголу','The royal court leaves Dongola','Падыша сарайы Донголадан кетет'),L('Уход двора меняет политическую роль города. Жизнь населения Нубии продолжается.','The court’s departure changes the town’s political role. Nubian communities continue their history.','Сарайдын кетиши шаардын саясий ролун өзгөртөт. Нубия жамааттарынын турмушу уланат.'),['lateDongola']);
 E('late-kanem-bornu',1385,'bornu-late','politics',[14.2,13.4],L('Сайфава теряют Канем','The Sayfawa lose Kanem','Сайфава Канемден ажырайт'),L('В 1380-х годах давление Булала вынуждает Сайфава оставить Канем и опереться на Борну западнее озера Чад.','In the 1380s Bulala pressure forces the Sayfawa to leave Kanem and rely on Bornu west of Lake Chad.','1380-жылдары Булаланын кысымы Сайфаваны Канемди таштап, Чад көлүнүн батышындагы Борнуга таянууга мажбурлайт.'),['lateKanem'],{approx:true,route:[[16,14.5],[14.7,13.3],[12.7,12.8]]});
 E('late-kilwa-battuta',1331,'kilwa','culture',[39.52,-8.96],L('Ибн Баттута посещает Килву','Ibn Battuta visits Kilwa','Ибн Баттута Килвага келет'),L('Путешественник описывает Килву во время её торгового расцвета. Визит относят к 1331–1332 годам.','The traveller describes Kilwa during its commercial flourishing. His visit is dated to 1331–1332.','Саякатчы Килваны соодасы гүлдөгөн учурда сүрөттөйт. Сапары 1331–1332-жылдарга таандык.'),['kilwa'],{to:1332});
 E('late-tlemcen-capture',1337,'marinid','war',[-1.32,34.88],L('Мариниды берут Тлемсен','Marinids take Tlemcen','Мариниддер Тлемсенди алат'),L('Тлемсен переходит под маринидскую власть. Государство Зайянидов временно теряет самостоятельность.','Tlemcen comes under Marinid rule. The Zayyanid state temporarily loses independence.','Тлемсен Маринид бийлигине өтөт. Зайянид мамлекети убактылуу өз алдынчалыгын жоготот.'),['lateMaghreb']);
 E('late-tunis-capture',1347,'marinid','war',[10.18,36.8],L('Абу-ль-Хасан вступает в Тунис','Abu al-Hasan enters Tunis','Абу-ль-Хасан Туниске кирет'),L('Маринидский султан завоёвывает Тунис в ходе хафсидской междоусобицы. Его власть в Ифрикии оказывается кратковременной.','The Marinid sultan takes Tunis during Hafsid civil war. His control of Ifriqiya proves short-lived.','Маринид султаны Хафсиддердин ички согушунда Тунисти басып алат. Ифрикиядагы бийлиги кыска убакытка созулат.'),['lateHafsid']);
 E('late-kairouan-defeat',1348,'marinid','war',[10.1,35.68],L('Поражение Маринидов у Кайруана','Marinid defeat near Kairouan','Кайруандын жанындагы Маринид жеңилүүсү'),L('Войско Абу-ль-Хасана терпит поражение от местных арабских племён. Хафсидские правители возвращают города Ифрикии.','Abu al-Hasan’s army is defeated by local Arab tribes. Hafsid rulers recover Ifriqiyan cities.','Абу-ль-Хасандын аскери жергиликтүү араб урууларынан жеңилет. Хафсид өкүмдарлары Ифрикия шаарларын кайтарат.'),['lateKhaldun']);
 E('late-barquq',1382,'mamluk-late','politics',[31.24,30.04],L('Баркук становится султаном','Barquq becomes sultan','Баркук султан болот'),L('Возведение Баркука на престол открывает бурджитский период Мамлюкского султаната.','Barquq’s accession opens the Burji period of the Mamluk sultanate.','Баркуктун такка келиши Мамлюк султандыгынын Буржи доорун ачат.'),['lateMamluk']);
 E('late-timur-damascus',1401,'mamluk-late','war',[36.3,33.51],L('Тимур захватывает Дамаск','Timur captures Damascus','Тимур Дамаскты басып алат'),L('Поход Тимура разоряет Дамаск. После ухода его войск мамлюкская власть в аш-Шаме восстанавливается.','Timur’s campaign devastates Damascus. Mamluk rule in al-Sham is restored after his forces depart.','Тимурдун жортуулу Дамаскты кыйратат. Аскери кеткенден кийин аш-Шамда Мамлюк бийлиги калыбына келет.'),['lateMamluk','lateAfricaHistory']);
 E('late-ceuta-capture',1415,'ceuta-late','war',[-5.32,35.89],L('Португалия захватывает Сеуту','Portugal captures Ceuta','Португалия Сеутаны басып алат'),L('Португальское войско берёт порт на африканском берегу Гибралтарского пролива.','A Portuguese army takes the port on the African shore of the Strait of Gibraltar.','Португалия аскери Гибралтар кысыгынын Африка жээгиндеги портту басып алат.'),['lateCeuta']);
 E('late-ewuare',1440,'benin','politics',[5.62,6.34],L('Начало правления Эвуаре','Beginning of Ewuare’s reign','Эвуаренин бийлигинин башталышы'),L('Эвуаре связывают с преобразованием столицы и усилением царства Бенин. Начало его правления датируется приблизительно.','Ewuare is associated with reshaping the capital and strengthening Benin. The beginning of his reign is approximately dated.','Эвуаре борбордун өзгөрүшү жана Бенин падышалыгынын күчөшү менен байланышат. Бийлигинин башталышы болжолдуу даталанат.'),['lateBenin'],{approx:true});
 E('late-khami-rise',1450,'khami-late','politics',[28.42,-20.16],L('Хами становится политическим центром','Khami becomes a political centre','Хами саясий борборго айланат'),L('Около середины XV века на западе плато усиливается Хами, связанный с династией Торва.','Around the mid-fifteenth century Khami, associated with the Torwa dynasty, rises in the western plateau.','XV кылымдын ортосунда платонун батышындагы Торва династиясы менен байланышкан Хами күчөйт.'),['lateKhami'],{approx:true});
 return c;
};
