'use strict';
module.exports=(c,H)=>{
 const {L,phase:P}=H;
 H.source('to1789Australia','National Museum of Australia. Convict cargo; The First Fleet arrives at Sydney Cove; Dirk Hartog lands off Western Australia.',['https://www.nma.gov.au/defining-moments/resources/convict-cargo','https://digital-classroom.nma.gov.au/defining-moments/first-fleet-arrives-sydney-cove','https://www.nma.gov.au/defining-moments/resources/dirk-hartog-lands-off-western-australia']);
 H.source('to1789Sydney','State Library of New South Wales. Eora: Mapping Aboriginal Sydney, 1770–1850; William Bradley, A Voyage to New South Wales; Arthur Phillip, Journal, 1788.',['https://www2.sl.nsw.gov.au/archive/events/exhibitions/2006/eora/docs/eora-captions.pdf','https://acms.sl.nsw.gov.au/_transcript/2007/D00007/a138.html','https://transcripts.sl.nsw.gov.au/page/extracts-journal-sailing-kings-birthday-1788-arthur-phillip-13-may-1787-4-june-1788-series-0']);
 H.source('to1789Janszoon','Australian National Maritime Museum. 1606: Contact at Cape Keerweer.','https://www.sea.museum/1606-contact-at-cape-keerweer');
 H.source('to1789Tasmania','National Museum of Australia. Separation of Tasmania; The Black Line.',['https://www.nma.gov.au/defining-moments/resources/separation-of-tasmania','https://www.nma.gov.au/defining-moments/resources/the-black-line']);
 H.source('to1789NZ','Manatū Taonga. Te Ara: The arrival of Europeans; Early mappers, 1642–1800; New Zealand History: Early meetings between peoples.',['https://teara.govt.nz/en/maori/page-3','https://teara.govt.nz/mi/early-mapping/page-1','https://nzhistory.govt.nz/comment/16703']);
 H.source('to1789Tonga','Aletta Biersack. Rivals and Wives: Affinal Politics and the Tongan Ramage; ANU Press. Contested Terrain: Reconceptualising Security in the Pacific, chapter 5.',['https://press-files.anu.edu.au/downloads/press/p63701/html/ch12.html','https://press-files.anu.edu.au/downloads/press/n5924/html/ch05.xhtml']);
 H.source('to1789Guam','Guampedia. Hagåtña; José de Quiroga y Losada; Transmission of Christianity into CHamoru Culture.',['https://www.guampedia.com/hagatna/','https://www.guampedia.com/jose-de-quiroga-y-losada/','https://www.guampedia.com/transmission-of-christianity-into-chamorro-culture/']);
 H.source('to1789Hawaii','U.S. National Park Service. Cook Landing Site; Kamehameha the Great.',['https://www.nps.gov/places/cook-landing-site.htm','https://www.nps.gov/people/kamehameha-the-great.htm']);
 H.source('to1789Tahiti','National Museum of Australia. Voyages: Cook and Forster; Royal Museums Greenwich. Chart of part of the South Sea, 1765–1769.',['https://www.nma.gov.au/explore/features/cook_forster/background/voyages','https://www.rmg.co.uk/collections/objects/rmgc-object-153930']);
 H.source('to1789Rapa','ICOMOS. Rapa Nui National Park: Advisory Body Evaluation, 1995; National Park nomination.',['https://whc.unesco.org/archive/advisory_body_evaluation/715.pdf','https://whc.unesco.org/document/154091']);
 H.source('to1789Greenland','Thomas N. Krabbe. Grønland — dets natur, beboere og historie (1929), plate 113; National Museum of Denmark. Frederik 4.; Greenland National Museum, Sisimiut World Heritage proposal.',['https://samlinger.natmus.dk/es/asset/115264','https://natmus.dk/historisk-viden/temaer/kongeraekken/frederik-4/','https://en.nka.gl/fileadmin/user_upload/Cruise_Ship_Resources/2013/201304_1.pdf']);
 H.source('to1789Iceland','Gísli Gunnarsson. Monopoly Trade and Economic Stagnation: Studies in the Foreign Trade of Iceland, 1602–1787; Smithsonian Institution. Global Volcanism Program: Grímsvötn and Laki.',['https://uni.hi.is/gisligu/','https://volcano.si.edu/volcano.cfm?vn=373010']);
 H.source('to1789Kodiak','U.S. National Park Service. Three Saints Bay Site National Historic Landmark.','https://www.nps.gov/places/three-saints-bay-site.htm');
 H.source('to1789Antarctic','Royal Museums Greenwich. History of Antarctic explorers; British Antarctic Territory. UK Antarctic Timeline.',['https://www.rmg.co.uk/stories/maritime-history/history-antarctic-explorers','https://www.britishantarcticterritory.org.uk/heritage/uk-antarctic-timeline/']);
 const prior=id=>c.entries.find(e=>e.id===id).phases.find(p=>p.from<=1600&&p.to>1600);
 const cont=(id,rows)=>{H.continueEntry(id,rows.map(r=>P(r[0],r[1],r[2],r[3],r[4],r[5]||{})));for(const r of rows)H.area(id,r[0],r[1],r[6]||'previous',r[7]||{});};
 const carry=id=>{const p=prior(id);cont(id,[[1601,1790,p.title,p.text,p.sources,{learning:p.learning}]]);};
 // The dated extension records continuity; 1601 is an editorial boundary, not a founding date.
 for(const id of ['budj','kakadu','kuk','mabuyag','palau','samoa','early-motutapu'])carry(id);
 const solomons=prior('early-solomons');
 cont('early-solomons',[[1601,1790,L('Общества Соломоновых островов','Societies of the Solomon Islands','Соломон аралдарынын коомдору'),L('Местные сообщества поддерживают земледелие, рыболовство и межостровной обмен. Европейские плавания не заменяют местную власть постоянным колониальным управлением.','Local communities sustain farming, fishing and inter-island exchange. European voyages do not replace local authority with permanent colonial administration.','Жергиликтүү жамааттар дыйканчылыкты, балык уулоону жана арал аралык алмашууну улантат. Европа саякаттары жергиликтүү бийликти туруктуу колониялык башкарууга алмаштырбайт.'),solomons.sources,{learning:solomons.learning}]]);
 const th=prior('thule');
 cont('thule',[[1601,1721,L('Инуитские общества Арктики','Inuit societies of the Arctic','Арктиканын инуит коомдору'),L('Прибрежные инуитские общества продолжают морскую охоту и сезонные перемещения. Местные сообщества связаны обменом и родством; культурная область не образует единого государства.','Coastal Inuit societies continue marine hunting and seasonal movement. Local communities are linked by exchange and kinship; the cultural region is not a single state.','Жээктеги инуит коомдору деңиз аңчылыгын жана мезгилдик көчүүнү улантат. Жамааттарды алмашуу жана туугандык байланыштырат; маданий аймак бирдиктүү мамлекет эмес.'),th.sources,{learning:th.learning},null,{name:L('Инуитские общества','Inuit societies','Инуит коомдору')}],
 [1721,1790,L('Инуиты и новые торговые поселения','Inuit and new trading settlements','Инуиттер жана жаңы соода конуштары'),L('На западном побережье Гренландии появляются датско-норвежские миссии и торговые пункты. Они взаимодействуют с инуитскими общинами; остальная культурная область продолжает самостоятельную жизнь.','Danish-Norwegian missions and trading posts appear on Greenland’s west coast. They interact with Inuit communities while the wider cultural region retains independent local life.','Гренландиянын батыш жээгинде Дания-Норвегия миссиялары жана соода жайлары пайда болот. Алар инуит жамааттары менен байланышат; кеңири маданий аймакта жергиликтүү жашоо уланат.'),[...th.sources,'to1789Greenland'],{learning:th.learning},null,{name:L('Инуитские общества','Inuit societies','Инуит коомдору')}]]);
 cont('nanmadol',[[1601,1790,L('Понпеи · местные вождества','Pohnpei · local chiefdoms','Понпеи · жергиликтүү башчылыктар'),L('Изменение власти и роли Нан-Мадола относится к широкому интервалу XVI–XVII веков. Понпеи остаётся обитаемым островом с местными вождями; каменный комплекс сохраняет обрядовое значение.','Political change and Nan Madol’s changing role belong to the broad sixteenth–seventeenth century interval. Pohnpei remains inhabited under local chiefs, while the stone complex retains ceremonial importance.','Бийликтин жана Нан-Мадолдун ролунун өзгөрүшү XVI–XVII кылымдардагы кеңири аралыкка таандык. Понпеиде жергиликтүү башчыларга караган калк жашайт; таш комплекс жөрөлгөлүк маанисин сактайт.'),['earlyNanm'],{learning:prior('nanmadol').learning},null,{kind:'cultural'}]]);
 const tongLearning={government:L('Сакральный ранг туи-тонга сочетается с властью линий туи-хаатакалауа и туи-канокуполу.','The sacred rank of the Tui Tonga coexists with the authority of the Tui Haatakalaua and Tui Kanokupolu lines.','Туи-тонганын ыйык даражасы туи-хаатакалауа жана туи-канокуполу тукумдарынын бийлиги менен катар жашайт.'),economy:prior('tonga').learning.economy,society:L('Родословные, браки и обмен дарами связывают правящие семьи и островные общины.','Genealogy, marriage and gift exchange connect chiefly families and island communities.','Санжыра, нике жана белек алмашуу башкаруучу үй-бүлөлөрдү жана арал жамааттарын байланыштырат.')};
 cont('tonga',[[1601,1773,L('Тонга · соперничающие правящие линии','Tonga · competing ruling lines','Тонга · атаандаш башкаруучу тукумдар'),L('В XVII веке к прежним правящим линиям добавляется туи-канокуполу. Власть и обрядовый ранг распределены между несколькими центрами; мореходство поддерживает связи островов.','During the seventeenth century the Tui Kanokupolu line joins the older chiefly lines. Political power and ceremonial rank are distributed among several centres; seafaring maintains island connections.','XVII кылымда мурдагы башкаруучу тукумдарга туи-канокуполу кошулат. Саясий бийлик жана жөрөлгөлүк даража бир нече борборго бөлүнөт; деңизчилик арал байланыштарын сактайт.'),['to1789Tonga'],{learning:tongLearning}],
 [1773,1790,L('Тонга и путешествия Кука','Tonga and Cook’s voyages','Тонга жана Куктун саякаттары'),L('Кук посещает острова в 1773, 1774 и 1777 годах. Обмен с моряками происходит при местных правителях; эти посещения не учреждают британскую колонию.','Cook visits in 1773, 1774 and 1777. Exchanges with sailors occur under local rulers; these visits do not establish a British colony.','Кук аралдарга 1773, 1774 жана 1777-жылдары келет. Деңизчилер менен алмашуу жергиликтүү башкаруучулар тушунда жүрөт; бул сапарлар британ колониясын түзбөйт.'),['to1789Tonga'],{learning:tongLearning}]]);
 const nzLearn={government:L('Иви и хапу объединяют родственные группы; власть вождей связана с родословной и поддержкой общин.','Iwi and hapū unite related groups; chiefly authority depends on descent and community support.','Иви жана хапу тууган топторду бириктирет; башчылардын бийлиги тегине жана жамааттын колдоосуна байланыштуу.'),...prior('aotearoa').learning};
 cont('aotearoa',[[1601,1642,L('Маори · иви, хапу и укреплённые па','Māori · iwi, hapū and fortified pā','Маори · иви, хапу жана чептүү па'),L('Местные общества развивают земледелие, рыбный промысел и укреплённые поселения. Союзы и соперничество связывают разные общины.','Local societies develop cultivation, fishing and fortified settlements. Alliances and rivalries connect different communities.','Жергиликтүү коомдор дыйканчылыкты, балык уулоону жана чептүү конуштарды өнүктүрөт. Ар башка жамааттарды союздар жана атаандаштык байланыштырат.'),['earlyMaori','to1789NZ'],{learning:nzLearn}],
 [1642,1769,L('Встреча с Тасманом и местная преемственность','Tasman encounter and local continuity','Тасман менен жолугушуу жана жергиликтүү улануу'),L('В декабре 1642 года корабли Тасмана входят в Мохуа. После столкновения с маори экспедиция уходит. Постоянное европейское поселение не возникает.','In December 1642 Tasman’s ships enter Mohua. Following a confrontation with Māori, the expedition leaves. No permanent European settlement is established.','1642-жылдын декабрында Тасмандын кемелери Мохуага кирет. Маори менен кагылышуудан кийин экспедиция кетет. Туруктуу европалык конуш түзүлбөйт.'),['to1789NZ'],{learning:nzLearn}],
 [1769,1790,L('Маори и новые морские контакты','Māori and new maritime contacts','Маори жана жаңы деңиз байланыштары'),L('Экспедиции Кука обследуют побережья. Встречи включают обмен и насилие; Тупайя помогает общению. Местные иви и хапу сохраняют власть над своими общинами.','Cook’s expeditions chart the coasts. Encounters include exchange and violence, with Tupaia assisting communication. Local iwi and hapū retain authority over their communities.','Куктун экспедициялары жээктерди картага түшүрөт. Жолугушууларда алмашуу да, зомбулук да болот; Тупайя сүйлөшүүгө жардам берет. Жергиликтүү иви жана хапу өз жамааттарында бийлигин сактайт.'),['to1789NZ'],{learning:nzLearn}]]);
 cont('early-guam',[[1601,1668,L('Гуам · общины чаморро','Guam · CHamoru communities','Гуам · чаморро жамааттары'),L('Морские общины ведут земледелие, рыболовство и межостровной обмен. Остановки галеонов связывают остров с тихоокеанскими путями.','Maritime communities farm, fish and exchange between islands. Galleon visits connect Guam with Pacific routes.','Деңиз жамааттары дыйканчылык, балык уулоо жана аралдар аралык алмашуу менен жашайт. Галеондордун токтошу Гуамды Тынч океан жолдору менен байланыштырат.'),['earlyGuam','to1789Guam']],
 [1668,1695,L('Испанская миссия и сопротивление чаморро','Spanish mission and CHamoru resistance','Испан миссиясы жана чаморро каршылыгы'),L('Постоянная миссия и испанская администрация возникают в 1668 году. Военное подчинение встречает сопротивление; войны и переселения меняют жизнь Мариан.','A permanent mission and Spanish administration begin in 1668. Military subjugation encounters resistance; wars and relocation transform life in the Marianas.','Туруктуу миссия жана испан башкаруусу 1668-жылы пайда болот. Аскердик баш ийдирүү каршылыкка учурайт; согуштар жана көчүрүү Мариан аралдарынын жашоосун өзгөртөт.'),['to1789Guam'],{approx:false},null,{kind:'influence',color:'#c89d60',name:L('Гуам · испанское влияние','Guam · Spanish influence','Гуам · испан таасири')}],
 [1695,1790,L('Гуам под испанским управлением','Guam under Spanish administration','Испан башкаруусундагы Гуам'),L('После основных войн Мариан Гуам становится центром колониального управления. Население сосредотачивают в новых деревнях; земледелие и снабжение галеонов обеспечивают хозяйство.','After the major Mariana wars, Guam becomes a colonial administrative centre. People are concentrated in reorganised villages; cultivation and galleon provisioning support the economy.','Мариан аралдарындагы негизги согуштардан кийин Гуам колониялык башкаруу борборуна айланат. Калкты кайра уюштурулган айылдарга топтошот; дыйканчылык жана галеондорду жабдуу чарбаны камсыз кылат.'),['to1789Guam'],{approx:false,learning:{government:L('Хагатна — место испанской администрации.','Hagåtña is the seat of Spanish administration.','Хагатна — испан башкаруусунун орду.'),economy:L('Сельское хозяйство и ежегодные заходы галеонов связывают остров с Манилой и Новой Испанией.','Farming and annual galleon visits connect the island with Manila and New Spain.','Дыйканчылык жана галеондордун жылдык келиши аралды Манила жана Жаңы Испания менен байланыштырат.'),society:L('Католические приходы и принудительное переселение преобразуют общины чаморро.','Catholic parishes and forced relocation reshape CHamoru communities.','Католик чиркөө жамааттары жана мажбурлап көчүрүү чаморро коомдорун өзгөртөт.')}},null,{kind:'polity',color:'#c89d60',name:L('Гуам · Испания','Guam · Spain','Гуам · Испания')}]]);
 const hiLearning={government:L('Несколько алии правят отдельными островами и областями; общегавайское королевство ещё не создано.','Several aliʻi rule separate islands and districts; a kingdom uniting all Hawaiʻi does not yet exist.','Бир нече алии өзүнчө аралдарды жана аймактарды башкарат; бүткүл Гавайини бириктирген падышалык али жок.'),economy:L('Орошаемые поля таро, сухое земледелие и рыбные пруды поддерживают население и дворы вождей.','Irrigated taro, dryland cultivation and fishponds support communities and chiefly courts.','Сугат таросу, кайрак дыйканчылык жана балык көлмөлөрү жамааттарды жана башчылардын ордолорун камсыз кылат.'),society:L('Ранг, обрядовые обязанности и отношения с землёй организуют общество.','Rank, ritual obligations and relationships with land organise society.','Даража, жөрөлгөлүк милдеттер жана жер менен байланыш коомду уюштурат.')};
 cont('hawaii',[[1601,1778,L('Гавайи · владения алии','Hawaiʻi · domains of the aliʻi','Гавайи · алиилердин ээликтери'),L('Земледельческие общества связаны властью местных вождей. Между островными правителями происходят союзы и войны.','Farming societies are organised under local chiefs. Island rulers form alliances and wage wars.','Дыйканчылык коомдор жергиликтүү башчылардын бийлиги астында уюшулат. Арал башкаруучулары союз түзүп, согушат.'),['lateHawaii','to1789Hawaii'],{learning:hiLearning},null,{kind:'cultural'}],
 [1778,1782,L('Гавайи · прибытие Кука','Hawaiʻi · Cook’s arrival','Гавайи · Куктун келиши'),L('Кук прибывает на Кауаи в 1778 году. При возвращении на остров Гавайи в 1779 году он погибает в столкновении у Кеалакекуа после попытки захватить Каланиопуу.','Cook arrives on Kauaʻi in 1778. Returning to Hawaiʻi Island in 1779, he is killed in a confrontation at Kealakekua after attempting to seize Kalaniʻōpuʻu.','Кук 1778-жылы Кауаиге келет. 1779-жылы Гавайи аралына кайтып, Каланиопууну кармоого аракеттенгенден кийин Кеалакекуадагы кагылышууда өлөт.'),['to1789Hawaii'],{learning:hiLearning},null,{kind:'cultural'}],
 [1782,1790,L('Борьба за наследство Каланиопуу','Contests over Kalaniʻōpuʻu’s succession','Каланиопуунун мурасы үчүн күрөш'),L('После смерти Каланиопуу начинается борьба за власть на острове Гавайи. Камехамеха побеждает Кивалао при Мокуохаи в 1782 году, но объединение всех островов относится к следующему периоду.','Kalaniʻōpuʻu’s death opens a struggle for power on Hawaiʻi Island. Kamehameha defeats Kīwalaʻō at Mokuʻōhai in 1782, but unification of all the islands belongs to a later period.','Каланиопуу өлгөндөн кийин Гавайи аралында бийлик үчүн күрөш башталат. Камехамеха 1782-жылы Мокуохаиде Кивалаону жеңет, бирок бардык аралдардын биригиши кийинки мезгилге таандык.'),['to1789Hawaii'],{learning:hiLearning},null,{kind:'cultural'}]]);
 cont('eastpolynesia',[[1601,1767,prior('eastpolynesia').title,prior('eastpolynesia').text,['polynesia']],
 [1767,1790,L('Таити · правители и заморские корабли','Tahiti · rulers and overseas ships','Таити · башкаруучулар жана алыскы кемелер'),L('Уоллис прибывает в 1767 году, Кук — в 1769. Моряки обмениваются припасами с местными обществами; на Таити наблюдают прохождение Венеры. Острова сохраняют собственных правителей.','Wallis arrives in 1767 and Cook in 1769. Sailors exchange provisions with local societies; observers record the transit of Venus on Tahiti. The islands retain their own rulers.','Уоллис 1767-жылы, Кук 1769-жылы келет. Деңизчилер жергиликтүү коомдор менен азык-түлүк алмашат; Таитиде Венеранын Күндүн алдынан өтүшү байкалат. Аралдар өз башкаруучуларын сактайт.'),['to1789Tahiti']]]);
 cont('rapanui',[[1601,1722,prior('rapanui').title,prior('rapanui').text,['polynesia']],
 [1722,1790,L('Рапа-Нуи · контакты с мореплавателями','Rapa Nui · encounters with voyagers','Рапа-Нуи · деңизчилер менен байланыштар'),L('Экспедиция Роггевена посещает остров в 1722 году; за ней следуют другие мореплаватели. Местные общины продолжают обрабатывать землю и поддерживать собственные обряды. Посещения не создают постоянной европейской колонии.','Roggeveen’s expedition visits in 1722, followed by other voyagers. Local communities continue cultivation and their own ceremonial practices. These visits do not establish a permanent European colony.','Роггевендин экспедициясы 1722-жылы аралга келет; андан кийин башка деңизчилер келет. Жергиликтүү жамааттар жер иштетип, өз жөрөлгөлөрүн улантат. Сапарлар туруктуу европалык колония түзбөйт.'),['to1789Rapa']]]);
 const ice=prior('iceland');
 cont('iceland',[[1601,1602,ice.title,ice.text,ice.sources],
 [1602,1783,L('Исландия · датская торговая монополия','Iceland · Danish trade monopoly','Исландия · Даниянын соода монополиясы'),L('Корона ограничивает внешнюю торговлю монопольной системой. Сельские хозяйства и рыболовство обеспечивают жизнь острова; Исландия остаётся частью датско-норвежской монархии.','The crown restricts overseas trade through a monopoly system. Farming and fishing sustain the island, which remains part of the Danish-Norwegian monarchy.','Таажы тышкы сооданы монополиялык система менен чектейт. Дыйканчылык жана балык уулоо аралдын жашоосун камсыз кылат; Исландия Дания-Норвегия монархиясында калат.'),['to1789Iceland'],{approx:false}],
 [1783,1787,L('Извержение Лаки и кризис хозяйства','Laki eruption and economic crisis','Лакинин атылышы жана чарба кризиси'),L('Извержение 1783–1784 годов разрушает хозяйство и вызывает тяжёлый кризис на острове. Торговая монополия сохраняется до 1787 года.','The 1783–1784 eruption devastates livelihoods and causes a severe island crisis. The trade monopoly remains until 1787.','1783–1784-жылдардагы атылуу чарбаны кыйратып, аралда оор кризис жаратат. Соода монополиясы 1787-жылга чейин сакталат.'),['to1789Iceland'],{approx:false}],
 [1787,1790,L('Завершение торговой монополии','End of the trade monopoly','Соода монополиясынын аякташы'),L('Монопольная система торговли заканчивается. Политически остров остаётся под датско-норвежской короной.','The trade monopoly ends. Politically the island remains under the Danish-Norwegian crown.','Соода монополиясы аяктайт. Саясий жактан арал Дания-Норвегия таажысынын бийлигинде калат.'),['to1789Iceland'],{approx:false}]]);
 cont('antarctica',[[1601,1773,L('Антарктида · необитаемый материк','Antarctica · an uninhabited continent','Антарктида · эл жашабаган материк'),L('На материке нет подтверждённых человеческих поселений. Европейские карты ещё изображают предположительные южные земли.','No human settlements are established on the continent. European maps still depict conjectural southern lands.','Материкте адам конуштары ырасталган эмес. Европа карталарында түштүктөгү божомол жерлер дагы эле көрсөтүлөт.'),['antarctica','to1789Antarctic']],
 [1773,1790,L('Плавания за Южным полярным кругом','Voyages beyond the Antarctic Circle','Түштүк уюл тегерегинен аркы саякаттар'),L('Экспедиция Кука пересекает Южный полярный круг в 1773 году и достигает более южных широт в 1774. Моряки не видят материк; поселения и политические владения здесь не возникают.','Cook’s expedition crosses the Antarctic Circle in 1773 and reaches farther south in 1774. The crew does not see the mainland; no settlements or political domains are established here.','Куктун экспедициясы 1773-жылы Түштүк уюл тегерегинен өтүп, 1774-жылы андан ары түштүккө жетет. Деңизчилер материкти көрбөйт; бул жерде конуштар жана саясий ээликтер пайда болбойт.'),['to1789Antarctic']]]);
 // Compact new local areas; colonial claims are not drawn as continental control.
 const small=(id,region,kind,coord,name,rows,color,areaKind)=>{
  H.entry(id,region,kind,coord,name,rows.map(r=>P(r[0],r[1],r[2],r[3],r[4],r[5]||{})));
  for(const r of rows)H.area(id,r[0],r[1],r[6],{color,kind:areaKind||'settlement'});
 };
 const cadigal=[[151.07,-33.82],[151.29,-33.82],[151.3,-33.98],[151.1,-33.98]];
 small('1789-cadigal','australia','community',[151.2,-33.9],L('Гадигал · Варран','Gadigal · Warrane','Гадигал · Варран'),[
 [1601,1788,L('Общины гавани Варран','Communities of Warrane harbour','Варран булуңунун жамааттары'),L('Гадигал и соседние общины связаны с землями и водами Порт-Джексона. Рыболовство, собирательство и родственные связи поддерживают их жизнь.','Gadigal and neighbouring communities maintain relationships with the lands and waters of Port Jackson. Fishing, gathering and kinship sustain their lives.','Гадигал жана коңшу жамааттар Порт-Жексондун жери жана суулары менен байланышкан. Балык уулоо, теримчилик жана туугандык алардын жашоосун камсыз кылат.'),['to1789Sydney'],{},cadigal],
 [1788,1790,L('Гадигал и основание колонии','Gadigal and the founding of the colony','Гадигал жана колониянын негизделиши'),L('Британское поселение занимает Варран. Вырубка, занятие земли и вооружённые столкновения меняют жизнь местных жителей; общины не исчезают с основанием колонии.','British settlement occupies Warrane. Clearance, land occupation and armed encounters transform local life; the communities do not disappear when the colony is founded.','Британ конушу Варранды ээлейт. Токой кыюу, жер басып алуу жана куралдуу кагылышуулар жергиликтүү жашоону өзгөртөт; колония түзүлгөндө жамааттар жок болуп кетпейт.'),['to1789Sydney'],{approx:false},cadigal]],'#a4936b','cultural');
 small('1789-sydney','australia','city',[151.21,-33.86],L('Сидней-Ков · британское поселение','Sydney Cove · British settlement','Сидней-Ков · британ конушу'),[
 [1788,1790,L('Начало колонии Новый Южный Уэльс','Beginning of the New South Wales colony','Жаңы Түштүк Уэльс колониясынын башталышы'),L('26 января 1788 года Первый флот начинает поселение в Сидней-Ков. Военная администрация использует труд каторжников; небольшой занятый район показан отдельно от обширных притязаний британской короны.','On 26 January 1788 the First Fleet begins a settlement at Sydney Cove. Military administration uses convict labour; the small occupied district is distinct from the British crown’s extensive claims.','1788-жылдын 26-январында Биринчи флот Сидней-Ковдо конушту баштайт. Аскердик башкаруу сүргүнгө айдалгандардын эмгегин колдонот; чакан ээлеген аймак британ таажысынын кеңири дооматтарынан өзүнчө көрсөтүлөт.'),['to1789Australia','to1789Sydney'],{approx:false,learning:{government:L('Колонией руководят губернатор и морские пехотинцы.','A governor and marines administer the colony.','Колонияны губернатор жана деңиз жөө аскерлери башкарат.'),economy:L('Труд заключённых создаёт жильё, склады и первые посевы; снабжение зависит от морских поставок.','Convict labour builds housing, stores and initial crops; supplies depend on shipping.','Абактагылардын эмгеги турак жай, кампа жана алгачкы эгиндерди түзөт; камсыздоо деңизден келген жүккө көз каранды.'),society:L('В поселении живут заключённые, военные и их семьи на занятой земле гадигал.','Convicts, soldiers and their families live on occupied Gadigal land.','Конушта гадигалдын ээлеп алынган жеринде абактагылар, аскерлер жана алардын үй-бүлөлөрү жашайт.')}},[[151.18,-33.84],[151.24,-33.84],[151.24,-33.89],[151.18,-33.89]]]],'#b68671');
 const tas=[[144.6,-40.7],[148.2,-40.8],[148.2,-43.6],[146.1,-43.7],[144.6,-42.1]];
 small('1789-tasmania','australia','community',[147.2,-42.0],L('Тасмания · коренные общества','Tasmania · Aboriginal societies','Тасмания · түпкү коомдор'),[
 [1601,1642,L('Общины Тасмании','Tasmanian communities','Тасмания жамааттары'),L('Местные общества связаны с охотничьими и прибрежными угодьями. Морские ресурсы, сезонные переходы и обмен поддерживают жизнь острова.','Local societies maintain relationships with hunting grounds and coastal areas. Marine resources, seasonal movement and exchange sustain island life.','Жергиликтүү коомдор аңчылык жана жээк жерлери менен байланышкан. Деңиз ресурстары, мезгилдик көчүү жана алмашуу аралдын жашоосун камсыз кылат.'),['to1789Tasmania'],{},tas],
 [1642,1772,L('Берега на картах Тасмана','Coasts on Tasman’s charts','Тасмандын карталарындагы жээктер'),L('Тасман обследует часть побережья в 1642 году. На острове продолжают жить коренные общества; голландского поселения не возникает.','Tasman charts part of the coast in 1642. Aboriginal societies continue island life; no Dutch settlement is established.','Тасман 1642-жылы жээктин бөлүгүн картага түшүрөт. Аралда түпкү коомдор жашоосун улантат; голланд конушу түзүлбөйт.'),['to1789Tasmania'],{},tas],
 [1772,1790,L('Первые документированные встречи','First documented encounters','Алгачкы документтешкен жолугушуулар'),L('В 1772 году происходит первая документированная встреча европейцев с коренными жителями Тасмании. Постоянная британская колонизация острова начнётся уже в следующем периоде.','In 1772 Europeans have their first documented encounter with Aboriginal Tasmanians. Permanent British colonisation of the island begins in a later period.','1772-жылы европалыктар менен Тасманиянын түпкү тургундарынын алгачкы документтешкен жолугушуусу болот. Аралды туруктуу британ колониялаштыруусу кийинки мезгилде башталат.'),['to1789Tasmania'],{},tas]],'#a68f6e','cultural');
 small('1789-greenland-posts','arctic','city',[-52.1,64.13],L('Гренландия · миссия и торговля','Greenland · mission and trade','Гренландия · миссия жана соода'),[
 [1721,1728,L('Поселение на Хобетс-Э','Settlement on Håbets Ø','Хобетс-Эдеги конуш'),L('Экспедиция Ханса Эгеде основывает миссию и торговое поселение у входа в фьорд Нуук. Оно возникает рядом с инуитскими общинами, а не на месте действующей скандинавской колонии.','Hans Egede’s expedition establishes a mission and trading settlement near the entrance to Nuuk fjord. It is founded among Inuit communities, not as the continuation of an existing Norse colony.','Ханс Эгеденин экспедициясы Нуук фьордунун кире беришине жакын миссия жана соода конушун түзөт. Ал иштеп жаткан скандинав колониясынын уландысы эмес, инуит жамааттарынын арасында пайда болот.'),['to1789Greenland'],{approx:false},[[-52.2,64.08],[-52.02,64.08],[-52.02,64.19],[-52.2,64.19]]],
 [1728,1790,L('Готхоб · Нуук','Godthåb · Nuuk','Готхоб · Нуук'),L('Поселение переносится в Готхоб, нынешний Нуук. Миссия и торговля становятся опорой датско-норвежского присутствия на западном побережье; контур обозначает местный район поселения.','The settlement moves to Godthåb, present-day Nuuk. Mission and trade anchor the Danish-Norwegian presence on the west coast; the outline represents a local settlement district.','Конуш азыркы Нуук болгон Готхобго көчөт. Миссия жана соода батыш жээктеги Дания-Норвегия катышуусунун таянычына айланат; контур жергиликтүү конуш аймагын көрсөтөт.'),['to1789Greenland'],{approx:false,coord:[-51.74,64.18]},[[-51.85,64.12],[-51.63,64.12],[-51.63,64.25],[-51.85,64.25]]]],'#9b8195');
 small('1789-kodiak','arctic','city',[-153.48,57.13],L('Кадьяк · Трёхсвятительская гавань','Kodiak · Three Saints Bay','Кадьяк · Үч Ыйыктын булуңу'),[
 [1784,1790,L('Русское поселение на Кадьяке','Russian settlement on Kodiak','Кадьяктагы орус конушу'),L('Шелихов основывает поселение в 1784 году. Оно служит опорой промысла морских зверей и дальнейшей экспансии. Показан район поселения, а не вся Аляска; коренное население острова сохраняется.','Shelikhov establishes the settlement in 1784. It supports marine fur exploitation and further expansion. The map marks the settlement district, not all Alaska; the island’s Indigenous people remain present.','Шелихов 1784-жылы конуш түзөт. Ал деңиз жаныбарларынын терисин алуу жана кийинки кеңейүүнүн таянычы болот. Карта бүт Алясканы эмес, конуш аймагын көрсөтөт; аралдын түпкү калкы сакталат.'),['to1789Kodiak'],{approx:false},[[-153.61,57.05],[-153.36,57.05],[-153.36,57.21],[-153.61,57.21]]]],'#9f9783');
 const cape=[[141.45,-13.4],[142.1,-13.4],[142.1,-14.3],[141.45,-14.3]];
 small('1789-cape-york','australia','community',[141.7,-13.96],L('Кейп-Йорк · западные прибрежные общины','Cape York · western coastal communities','Кейп-Йорк · батыш жээк жамааттары'),[
 [1601,1606,L('Коренные общества побережья','Indigenous coastal societies','Жээктеги түпкү коомдор'),L('Прибрежные общины полуострова используют морские и наземные ресурсы. Контур обозначает район у мыса Кервер, а не границу единого государства.','Coastal communities of the peninsula use marine and land resources. The outline represents the Cape Keerweer district, not a unified state boundary.','Жарым аралдын жээк жамааттары деңиз жана жер ресурстарын пайдаланат. Контур бирдиктүү мамлекеттин чек арасын эмес, Кервер тумшугунун аймагын көрсөтөт.'),['to1789Janszoon'],{},cape],
 [1606,1790,L('После встречи с кораблём «Дёйфкен»','After the Duyfken encounter','«Дёйфкен» кемеси менен жолугушуудан кийин'),L('Корабль Янсзона приходит в 1606 году; столкновение не приводит к постоянной колонии. Местные общества продолжают жизнь на своих землях.','Janszoon’s ship arrives in 1606; the confrontation does not lead to a permanent colony. Local societies continue life on their lands.','Янсзондун кемеси 1606-жылы келет; кагылышуу туруктуу колонияга алып келбейт. Жергиликтүү коомдор өз жерлеринде жашоосун улантат.'),['to1789Janszoon'],{},cape]],'#a6a07e','cultural');
 const event=(id,y,e,kind,coord,title,text,src,options={})=>H.event('1789-'+id+'-'+y,y,e,kind,coord,title,text,[src],options);
 event('keerweer',1606,'1789-cape-york','culture',[141.7,-13.96],L('Экспедиция Янсзона у мыса Кервер','Janszoon’s expedition at Cape Keerweer','Янсзондун Кервер тумшугундагы экспедициясы'),L('Первый документированный контакт европейских моряков с коренными жителями Австралии сопровождается конфликтом. Поселение здесь не учреждается.','The first documented European encounter with First Nations Australians involves conflict. No settlement is established here.','Европалык деңизчилердин Австралиянын түпкү тургундары менен алгачкы документтешкен жолугушуусу кагылышуу менен коштолот. Бул жерде конуш түзүлбөйт.'),'to1789Janszoon');
 event('tasman',1642,'aotearoa','culture',[172.88,-40.82],L('Тасман в Мохуа','Tasman at Mohua','Тасман Мохуада'),L('Встреча кораблей с маори в Мохуа заканчивается столкновением; экспедиция покидает залив.','The encounter between the ships and Māori at Mohua ends in conflict; the expedition leaves the bay.','Мохуада кемелердин маори менен жолугушуусу кагылышуу менен аяктап, экспедиция булуңдан кетет.'),'to1789NZ');
 event('guam',1668,'early-guam','politics',[144.75,13.48],L('Испанская миссия в Хагатне','Spanish mission at Hagåtña','Хагатнадагы испан миссиясы'),L('Начинаются постоянная миссия и колониальное управление; чаморро оказывают сопротивление подчинению.','A permanent mission and colonial administration begin; CHamoru resist subjugation.','Туруктуу миссия жана колониялык башкаруу башталат; чаморро баш ийдирүүгө каршылык көрсөтөт.'),'to1789Guam');
 event('greenland',1721,'1789-greenland-posts','politics',[-52.1,64.13],L('Эгеде основывает поселение в Гренландии','Egede establishes a Greenland settlement','Эгеде Гренландияда конуш түзөт'),L('Датско-норвежская миссия и торговый пункт возникают на Хобетс-Э у фьорда Нуук.','A Danish-Norwegian mission and trading post are established on Håbets Ø near Nuuk fjord.','Нуук фьордуна жакын Хобетс-Эде Дания-Норвегия миссиясы жана соода жайы түзүлөт.'),'to1789Greenland');
 event('rapanui',1722,'rapanui','culture',[-109.35,-27.12],L('Роггевен на Рапа-Нуи','Roggeveen at Rapa Nui','Роггевен Рапа-Нуиде'),L('Экспедиция встречает жителей острова; плавание не создаёт постоянной колонии.','The expedition encounters islanders; the voyage does not establish a permanent colony.','Экспедиция аралдыктарга жолугат; саякат туруктуу колония түзбөйт.'),'to1789Rapa');
 event('venus',1769,'eastpolynesia','culture',[-149.49,-17.5],L('Наблюдение Венеры на Таити','Observing Venus from Tahiti','Таитиде Венераны байкоо'),L('Участники экспедиции Кука наблюдают прохождение Венеры на фоне Солнца; научная работа соединяется с морскими исследованиями.','Cook’s expedition observes the transit of Venus across the Sun; scientific work accompanies maritime exploration.','Куктун экспедициясы Венеранын Күндүн алдынан өтүшүн байкайт; илимий иш деңиз изилдөөсү менен айкалышат.'),'to1789Tahiti');
 event('cook-nz',1769,'aotearoa','culture',[178.02,-38.69],L('Кук и Тупайя в Турангануи','Cook and Tupaia at Tūranganui','Кук жана Тупайя Турангануиде'),L('Прибытие экспедиции открывает новую полосу контактов маори с европейскими моряками.','The expedition’s arrival opens a new period of encounters between Māori and European sailors.','Экспедициянын келиши маори менен европалык деңизчилердин байланыштарынын жаңы мезгилин ачат.'),'to1789NZ');
 event('antarctic',1773,'antarctica','culture',[39.6,-66.6],L('Пересечение Южного полярного круга','Crossing the Antarctic Circle','Түштүк уюл тегерегинен өтүү'),L('Корабли Кука проходят за Южный полярный круг. Отмечена морская область плавания; сам материк экспедиция не увидела.','Cook’s ships cross the Antarctic Circle. The marker indicates the sea area of the voyage; the expedition did not see the continent itself.','Куктун кемелери Түштүк уюл тегерегинен өтөт. Белги саякаттын деңиз аймагын көрсөтөт; экспедиция материктин өзүн көргөн эмес.'),'to1789Antarctic',{approx:false,coordApprox:true});
 event('hawaii',1778,'hawaii','culture',[-159.67,21.96],L('Кук на Кауаи','Cook on Kauaʻi','Кук Кауаиде'),L('Корабли экспедиции прибывают к устью реки Ваимеа; начинаются документированные встречи с гавайцами.','The expedition’s ships arrive near the Waimea River mouth, beginning documented encounters with Hawaiians.','Экспедициянын кемелери Ваимеа дарыясынын куймасына келет; гавайлыктар менен документтешкен жолугушуулар башталат.'),'to1789Hawaii');
 event('mokuohai',1782,'hawaii','war',[-155.88,19.43],L('Битва при Мокуохаи','Battle of Mokuʻōhai','Мокуохаи салгылашуусу'),L('Камехамеха побеждает Кивалао в борьбе за наследство Каланиопуу.','Kamehameha defeats Kīwalaʻō in the struggle over Kalaniʻōpuʻu’s succession.','Камехамеха Каланиопуунун мурасы үчүн күрөштө Кивалаону жеңет.'),'to1789Hawaii',{approx:false,coordApprox:true});
 event('laki',1783,'iceland','nature',[-18.2,64.07],L('Начало извержения Лаки','Laki eruption begins','Лакинин атылышынын башталышы'),L('Продолжительное извержение изменяет ландшафт юга Исландии и тяжело воздействует на хозяйство.','The prolonged eruption transforms southern Iceland’s landscape and severely affects livelihoods.','Узак атылуу түштүк Исландиянын ландшафтын өзгөртүп, чарбага оор таасир этет.'),'to1789Iceland',{to:1784});
 event('kodiak',1784,'1789-kodiak','politics',[-153.48,57.13],L('Русское поселение в Трёхсвятительской гавани','Russian settlement at Three Saints Bay','Үч Ыйыктын булуңундагы орус конушу'),L('На Кадьяке появляется опорное поселение Шелихова для морского промысла и дальнейших экспедиций.','Shelikhov establishes a Kodiak base for marine exploitation and further expeditions.','Шелихов Кадьякта деңиз промысели жана кийинки экспедициялар үчүн таяныч конуш түзөт.'),'to1789Kodiak');
 event('sydney',1788,'1789-sydney','politics',[151.21,-33.86],L('Первый флот в Сидней-Ков','First Fleet at Sydney Cove','Биринчи флот Сидней-Ковдо'),L('Британское каторжное поселение основывается на земле гадигал у гавани Варран.','A British convict settlement is founded on Gadigal land at Warrane harbour.','Варран булуңундагы гадигал жеринде британ сүргүн конушу түзүлөт.'),'to1789Australia');
 return c;
};
