'use strict';
module.exports=(c,H)=>{
 const T=s=>s.split('|'),ids=[],refs=s=>s.map(x=>'to1789'+x);
 const G=id=>structuredClone(c.areas.find(a=>a.entry===id&&a.from<=1600&&a.to>1600).polygons);
 H.source('to1789EuropeTransitions','German History in Documents and Images. The Partitions of Poland. Die Welt der Habsburger. The War of Austrian Succession; Tuscany as a Habsburg secundogeniture. RiMe. Naples during the Austrian viceroyalty, 1707–1734.',['https://germanhistorydocs.org/en/the-holy-roman-empire-1648-1815/the-partitions-of-poland-1772-1795','https://www.habsburger.net/en/chapter/war-austrian-succession','https://www.habsburger.net/en/chapter/tuscany-habsburg-secundogeniture','https://rime.cnr.it/index.php/rime/article/view/175']);
 function put(id,s,color,rr,meta){const old=c.entries.find(e=>e.id===id),coord=old?.coord||meta.coord;const pp=rr.map(r=>H.phase(r[0],r[1],T(r[2]),T(r[3]),refs(s),{coord}));if(old)H.continueEntry(id,pp);else H.entry(id,'eurasia',meta.kind||'state',coord,T(meta.name),pp);ids.push(id);for(const r of rr)H.area(id,r[0],r[1],r[4]||G(id),{color:r[5]||color,kind:r[6]||'polity',name:id==='1789-prussia'?T(r[0]<1618?'Бранденбург|Brandenburg|Бранденбург':r[0]<1701?'Бранденбург — Пруссия|Brandenburg–Prussia|Бранденбург — Пруссия':'Королевство Пруссия|Kingdom of Prussia|Пруссия падышалыгы'):c.entries.find(e=>e.id===id).name,sources:refs(s)});}
 const royal=G('early-royal-hungary'),austria=G('early-austria'),venice=G('early-venice'),otto=G('late-ottoman'),poland=G('early-commonwealth');
 // Keep the Polish crown north/east of Silesia; do not paint Wroclaw twice.
 poland[0]=[[16,52],[16,52.4],[18.5,53.5],[22,53.5],[24.4,51],[23.7,49.5],[19,49.4],[18.5,50.3],[18,51.5]];
 const rigaCore=[[23.85,56.8],[24.5,56.8],[24.5,57.3],[23.85,57.3]],krakow=[[19.8,49.99],[19.99,49.99],[19.99,50.18],[19.8,50.18]];
 const galicia=[[20,49],[23,48.5],[26,48.3],[26,49.7],[23,50.5],[20,50.2]],belarus=[[29.5,53],[32,53],[32.2,55.5],[29.5,55.7]],danzig=[[18.45,54.2],[18.8,54.2],[18.8,54.5],[18.45,54.5]];
 const latgale=[[26.2,55.65],[27.8,55.65],[28.25,57.1],[27.1,57.35],[26.3,56.65]];
 const reduced=[poland[0],[[22,54],[24,51],[27,48.5],[30.3,49],[30,52],[31.5,54.8],[28,56],[23,56.2]],galicia,danzig,latgale];
 const after1772=[[[18.5,50.3],[20,50.2],[23,50.6],[24,51.2],[22,53.5],[19,53.5],[17.5,52.5],[17.5,51.7],[18,51.5]],[[22,54],[24,51.2],[27,50],[29,50],[29.3,54.8],[26,55.8],[23,56]],danzig,krakow];
 const silesia=[[15,50.4],[17,49.8],[18.5,50.3],[18,51.5],[16,52],[14.8,51.5]],brandenburg=[[11.5,51.5],[14.8,51.4],[15.5,53],[13.8,53.8],[11.4,53]],eastPrussia=[[19.5,53.5],[22.8,53.4],[23,55],[21,55.5],[19.5,54.7]],westPrussia=[[17,53.2],[18.8,53.25],[19.5,53.7],[19.5,54.2],[18.2,54.1],[17,54.4]];
 put('early-commonwealth',['Poland','EuropeTransitions'],'#9b9580',[
 [1601,1621,'Речь Посполитая и Рига|The Commonwealth and Riga|Речь Посполита жана Рига','Рига входит в состав Речи Посполитой до шведского захвата в 1621 году.|Riga remains part of the Commonwealth until its capture by Sweden in 1621.|Рига 1621-жылы Швеция басып алганга чейин Речь Посполитанын курамында калат.',[...poland,galicia,danzig,latgale,rigaCore]],
 [1621,1667,'Речь Посполитая: выборная монархия|Commonwealth: elective monarchy|Речь Посполита: шайланма монархия','Король, сейм и магнаты управляют составным государством. Восстания и войны меняют восточное пограничье.|King, Sejm and magnates govern a composite state. Uprisings and wars transform its eastern frontier.|Король, сейм жана магнаттар курама мамлекетти башкарат. Көтөрүлүштөр менен согуштар чыгыш чек араны өзгөртөт.',[...poland,galicia,danzig,latgale]],
 [1667,1772,'После Андрусовского перемирия|After the Truce of Andrusovo|Андрусово жарашуусунан кийин','Смоленск и Левобережье Днепра отходят России. Речь Посполитая сохраняется, но центральная власть ослабевает.|Smolensk and the Dnieper left bank pass to Russia. The Commonwealth survives, but central authority weakens.|Смоленск менен Днепрдин сол жээги Орусияга өтөт. Речь Посполита сакталат, бирок борбордук бийлик алсырайт.',reduced],
 [1772,1790,'После первого раздела|After the first partition|Биринчи бөлүштүрүүдөн кийин','Россия, Пруссия и Австрия присоединяют части страны. Речь Посполитая продолжает существовать; Гданьск и Торунь остаются в её составе.|Russia, Prussia and Austria annex parts of the country. The Commonwealth survives; Gdańsk and Toruń remain within it.|Орусия, Пруссия жана Австрия өлкөнүн бөлүктөрүн кошуп алат. Речь Посполита сакталат; Гданьск менен Торунь анын курамында калат.',after1772]]);
 put('early-royal-hungary',['Habsburg','Ottoman'],'#baa780',[
 [1601,1686,'Королевская Венгрия|Royal Hungary|Королдук Венгрия','Габсбургские владения на западе и севере соседствуют с османской центральной Венгрией.|Habsburg lands in the west and north border Ottoman central Hungary.|Батыш менен түндүктөгү Габсбург ээликтери борбордук Венгриядагы Осмон жерлерине чектеш.',royal],
 [1686,1699,'Взятие Буды|Capture of Buda|Буданын алынышы','Войска Священной лиги берут Буду. Продолжающаяся война меняет власть в центральной Венгрии.|Holy League forces capture Buda. Continuing war changes control in central Hungary.|Ыйык лига аскерлери Буданы алат. Уланган согуш борбордук Венгриядагы бийликти өзгөртөт.',[...royal,otto[9]]],
 [1699,1790,'Венгрия под короной Габсбургов|Hungary under the Habsburg crown|Габсбург таажысы алдындагы Венгрия','Карловицкий мир закрепляет основные завоевания. Королевство сохраняет сословные учреждения; Банат переходит Габсбургам позднее, в 1718 году.|Karlowitz confirms the main conquests. Hungary retains estate institutions; the Banat passes to the Habsburgs later, in 1718.|Карловиц тынчтыгы негизги басып алууларды бекитет. Венгрия сословие мекемелерин сактайт; Банат Габсбургдарга кийин, 1718-жылы өтөт.',[...royal,otto[9]]]]);
 put('early-transylvania',['Habsburg','Ottoman'],'#8fa19a',[
 [1601,1691,'Княжество между двумя державами|Principality between two powers|Эки державанын ортосундагы княздык','Князья и сословия маневрируют между османским верховенством и Габсбургами.|Princes and estates manoeuvre between Ottoman suzerainty and the Habsburgs.|Княздар менен сословиелер Осмон үстөмдүгү жана Габсбургдар ортосунда саясат жүргүзөт.'],
 [1691,1790,'Трансильвания при Габсбургах|Transylvania under the Habsburgs|Габсбургдар тушундагы Трансильвания','Диплом Леопольда закрепляет новое управление и местные сословные права. Область сохраняет отдельные учреждения.|Leopold’s Diploma establishes the new government and local estate rights. The region retains separate institutions.|Леопольддун диплому жаңы башкарууну жана жергиликтүү сословие укуктарын бекитет. Аймак өзүнчө мекемелерин сактайт.',null,'#baa780']]);
 put('early-austria',['Habsburg','EuropeTransitions','Poland'],'#baa780',[
 [1601,1742,'Австрийские и богемские земли|Austrian and Bohemian lands|Австрия жана Богемия жерлери','Монархия Габсбургов опирается на династию и отдельные земельные учреждения. Войны усиливают значение армии и налогов.|The Habsburg monarchy rests on dynasty and distinct provincial institutions. Wars increase the importance of armies and taxes.|Габсбург монархиясы династияга жана өзүнчө жердик мекемелерге таянат. Согуштар аскер менен салыктын маанисин күчөтөт.',[...austria,silesia]],
 [1742,1772,'Реформы и потеря Силезии|Reforms and loss of Silesia|Реформалар жана Силезиянын жоголушу','Пруссия получает большую часть Силезии. Мария Терезия перестраивает управление и налоги.|Prussia receives most of Silesia. Maria Theresa reorganises government and taxation.|Пруссия Силезиянын көп бөлүгүн алат. Мария Терезия башкаруу менен салыкты өзгөртөт.',austria],
 [1772,1790,'Присоединение Галиции|Annexation of Galicia|Галициянын кошулушу','Первый раздел Речи Посполитой добавляет Галицию к владениям Габсбургов. Следуют реформы Иосифа II.|The first partition of the Commonwealth adds Galicia to Habsburg possessions. Joseph II’s reforms follow.|Речь Посполитанын биринчи бөлүштүрүлүшү Галицияны Габсбург ээликтерине кошот. Андан кийин Иосиф IIнин реформалары жүрөт.',[...austria,galicia]]]);
 put('1789-prussia',['Europe','EuropeTransitions','Poland'],'#8897ac',[
 [1601,1618,'Бранденбургские владения|Brandenburg possessions|Бранденбург ээликтери','Курфюрст управляет бранденбургским ядром внутри Священной Римской империи.|The elector governs the Brandenburg core within the Holy Roman Empire.|Курфюрст Ыйык Рим империясынын ичиндеги Бранденбург өзөгүн башкарат.',[brandenburg]],
 [1618,1701,'Бранденбург и герцогство Пруссия|Brandenburg and the Duchy of Prussia|Бранденбург жана Пруссия герцогдугу','Династическая уния объединяет раздельные владения. Прусское герцогство зависит от польской короны до договоров 1657 года.|A dynastic union joins separate possessions. The Prussian duchy remains under Polish suzerainty until the treaties of 1657.|Династиялык уния бөлөк ээликтерди бириктирет. Пруссия герцогдугу 1657-жылкы келишимдерге чейин поляк таажысына көз каранды.',[brandenburg,eastPrussia]],
 [1701,1742,'Королевство Пруссия|Kingdom of Prussia|Пруссия падышалыгы','Коронация 1701 года создаёт королевский титул. Армия и управление связывают раздельные провинции.|The coronation of 1701 creates the royal title. Army and administration connect separate provinces.|1701-жылкы таажы кийүү падышалык наамды жаратат. Аскер менен башкаруу бөлөк провинцияларды байланыштырат.',[brandenburg,eastPrussia]],
 [1742,1772,'Пруссия с большей частью Силезии|Prussia with most of Silesia|Силезиянын көп бөлүгү кошулган Пруссия','Первая Силезская война меняет границы. Соперничество с Австрией продолжается.|The First Silesian War changes borders. Rivalry with Austria continues.|Биринчи Силезия согушу чек араны өзгөртөт. Австрия менен атаандаштык уланат.',[brandenburg,eastPrussia,silesia]],
 [1772,1790,'Западная Пруссия после раздела|West Prussia after the partition|Бөлүштүрүүдөн кийинки Батыш Пруссия','Первый раздел соединяет восточные и западные владения. Гданьск и Торунь ещё не принадлежат Пруссии.|The first partition connects eastern and western possessions. Gdańsk and Toruń do not yet belong to Prussia.|Биринчи бөлүштүрүү чыгыш жана батыш ээликтерин байланыштырат. Гданьск менен Торунь Пруссияга азырынча кирбейт.',[brandenburg,eastPrussia,silesia,westPrussia]]],{coord:[13.4,52.52],name:'Бранденбург — Пруссия|Brandenburg–Prussia|Бранденбург — Пруссия'});
 put('1789-belarus-russia',['Poland','EuropeTransitions'],'#96a6b8',[[1772,1790,'Российские приобретения первого раздела|Russian acquisitions in the first partition|Биринчи бөлүштүрүүдө Орусия алган жерлер','Восточные белорусские земли и Латгалия переходят к Российской империи. Местные города и общества сохраняются при новом управлении.|Eastern Belarusian lands and Latgale pass to the Russian Empire. Local towns and communities continue under new administration.|Чыгыш белорус жерлери менен Латгалия Орусия империясына өтөт. Жергиликтүү шаарлар менен коомдор жаңы башкаруу алдында сакталат.',[belarus,latgale]]],{coord:[30.33,53.9],name:'Восточная Беларусь и Латгалия · Российская империя|Eastern Belarus and Latgale · Russian Empire|Чыгыш Беларусь жана Латгалия · Орусия империясы',kind:'region'});
 put('early-venice',['Italy','Ottoman'],'#a38588',[
 [1601,1687,'Венецианская республика|Republic of Venice|Венеция республикасы','Сенат и патрицианские семьи управляют республикой. Войны с Османами меняют её морские владения.|The Senate and patrician families govern the republic. Wars with the Ottomans change its maritime possessions.|Сенат менен патриций үй-бүлөлөрү республиканы башкарат. Осмондор менен согуштар анын деңиздеги ээликтерин өзгөртөт.',venice],
 [1687,1715,'Венецианская Морея|Venetian Morea|Венециялык Морея','Завоевание Мореи расширяет владения республики. Османское возвращение в 1715 году завершает этот этап.|The conquest of the Morea expands the republic’s possessions. The Ottoman return in 1715 ends this phase.|Мореянын каратылышы республиканын ээликтерин кеңейтет. 1715-жылы Осмондордун кайтышы бул этапты аяктатат.',[...venice,otto[3]]],
 [1715,1790,'Венеция после утраты Мореи|Venice after losing the Morea|Мореяны жоготкондон кийинки Венеция','Республика сохраняет материковое ядро и часть морских владений. Торговля, ремесло и печать поддерживают город.|The republic retains its mainland core and some maritime possessions. Commerce, crafts and printing support the city.|Республика материктик өзөгүн жана деңиздеги ээликтеринин бир бөлүгүн сактайт. Соода, кол өнөрчүлүк жана басма шаарды камсыздайт.',venice]]);
 put('early-milan',['Italy','Habsburg'],'#91a496',[
 [1601,1706,'Милан под испанской короной|Milan under the Spanish crown|Испан таажысы алдындагы Милан','Герцогство связывает итальянские владения Габсбургов с альпийскими путями.|The duchy connects Habsburg Italian possessions with Alpine routes.|Герцогдук Габсбургдардын Италиядагы ээликтерин Альпы жолдоруна байланыштырат.'],
 [1706,1714,'Австрийское занятие Милана|Austrian occupation of Milan|Миландын Австрия тарабынан алынышы','В ходе войны за наследство австрийские силы занимают Милан; международное соглашение последует позже.|During the succession war Austrian forces occupy Milan; the international settlement follows later.|Мурас согушунда Австрия күчтөрү Миланды ээлейт; эл аралык келишим кийин түзүлөт.',null,'#baa780'],
 [1714,1790,'Милан австрийских Габсбургов|Milan of the Austrian Habsburgs|Австрия Габсбургдарынын Миланы','Мирное урегулирование закрепляет австрийское владение. Реформы меняют кадастр, налоги и учреждения.|The peace settlement confirms Austrian possession. Reforms change land surveys, taxation and institutions.|Тынчтык келишими Австриянын ээлигин бекитет. Реформалар жер эсепти, салыкты жана мекемелерди өзгөртөт.',null,'#baa780']]);
 put('early-florence',['Italy','EuropeTransitions'],'#b18f76',[
 [1601,1737,'Тоскана при Медичи|Tuscany under the Medici|Медичилер тушундагы Тоскана','Великое герцогство объединяет Флоренцию и тосканские города. Двор поддерживает искусство и научные занятия.|The grand duchy links Florence with Tuscan towns. The court supports art and scientific work.|Улуу герцогдук Флоренция менен Тоскана шаарларын бириктирет. Сарай искусство менен илимди колдойт.'],
 [1737,1790,'Тоскана Лотарингского дома|Tuscany of the House of Lorraine|Лотарингия үйүнүн Тосканасы','После пресечения Медичи герцогство переходит Францу Стефану Лотарингскому. Его преемники проводят хозяйственные и правовые реформы.|After the Medici line ends the duchy passes to Francis Stephen of Lorraine. His successors introduce economic and legal reforms.|Медичи тукуму аяктаганда герцогдук Франц Стефан Лотарингиялыкка өтөт. Анын мураскерлери чарбалык жана укуктук реформаларды жүргүзөт.',null,'#baa780']]);
 put('early-papal',['Italy'],'#b2a480',[[1601,1790,'Папское государство|Papal States|Папа мамлекети','Рим остаётся центром папской власти. Папские учреждения и местные элиты управляют городами и сельскими округами центральной Италии.|Rome remains the centre of papal power. Papal institutions and local elites govern towns and rural districts of central Italy.|Рим папа бийлигинин борбору бойдон калат. Папа мекемелери менен жергиликтүү төбөлдөр борбордук Италиянын шаарларын жана айыл аймактарын башкарат.']]);
 put('early-naples',['Italy','Habsburg','EuropeTransitions'],'#b89d77',[
 [1601,1707,'Неаполь испанской монархии|Naples of the Spanish monarchy|Испан монархиясынын Неаполу','Вице-король представляет испанскую корону. Город, землевладельцы и сельские общины связаны налогами и снабжением.|A viceroy represents the Spanish crown. City, landholders and rural communities are linked through taxes and provisioning.|Вице-король испан таажысын билдирет. Шаар, жер ээлери жана айыл жамааттары салык менен камсыздоо аркылуу байланышат.'],
 [1707,1734,'Австрийский вице-королевский период|Austrian viceregal period|Австриянын вице-королдук мезгили','Австрийские Габсбурги сменяют испанское управление в ходе войны за наследство.|The Austrian Habsburgs replace Spanish rule during the succession war.|Мурас согушунда Австрия Габсбургдары испан башкаруусун алмаштырат.',null,'#baa780'],
 [1734,1790,'Бурбонское королевство Неаполь|Bourbon Kingdom of Naples|Бурбондордун Неаполь падышалыгы','Карл Бурбон завоёвывает королевство. В Неаполе появляется собственный королевский двор.|Charles of Bourbon conquers the kingdom. Naples gains a resident royal court.|Карл Бурбон падышалыкты басып алат. Неаполдо өз падышалык сарайы пайда болот.']]);
 const dk=G('early-denmark-norway'),skane=[[12.7,55.35],[14.4,55.4],[14.7,56.25],[13.15,56.55],[12.45,56.1]],islands=[[11,54.6],[12.5,54.7],[12.7,55.7],[12.3,56.1],[11.2,56.2]],finland=[[21,60],[25,59.8],[29,61],[29,65],[26,67],[23,65],[21,62]];
 const swedenCore=[[12,56.8],[14.3,56.6],[16.5,57],[18.8,60],[17,63],[14,64],[12,61.5]];
 const finlandOld=[[21,60],[25,59.8],[29.9,60.3],[30.1,61.5],[29,65],[26,67],[23,65],[21,62]],finland1743=[[21,60],[25,59.8],[26.5,60.1],[26.7,61.2],[28.6,61.5],[29,65],[26,67],[23,65],[21,62]];
 const estonia=[[23.5,58.65],[25.7,58.7],[26.5,58.95],[28.3,59.15],[28.3,59.6],[24,59.65],[23.4,59.1]];
 const livonia=[[23.5,56.8],[24.6,56.65],[26.2,56.9],[27.3,57.6],[27.5,58.65],[26.5,58.95],[25.7,58.7],[23.5,58.65]];
 const ingria=[[28.3,59.15],[30,58.4],[32,59.1],[31.5,60.2],[29.7,60.2],[28.3,59.6]],ingria1703=[[28.3,59.15],[30,58.4],[31,58.8],[30.6,59.5],[29.6,59.6],[28.3,59.6]];
 H.source('to1789BalticAudit','Latvian Ministry of Foreign Affairs. History of Polish-Latvian Relations. Ajalooline Ajakiri. The capitulation of Tallinn and the Harju-Viru knighthood to Sweden in 1561. National Archives of Estonia. Tallinn’s Swedish garrison.',['https://www2.mfa.gov.lv/en/poland/embassy-of-latvia/history-of-polish-latvian-relations','https://ojs.utlib.ee/index.php/EAA/article/view/AA.2017.1.02','https://tuna.ra.ee/tallinna-sojalised-kohustused-ja-rootsi-garnison-16-sajandi-lopul-ja-17-sajandi-esimesel-kolmandikul-lk-9-36/']);
 put('early-denmark-norway',['Scandinavia'],'#9b8699',[
 [1601,1658,'Дания и Норвегия до Роскилле|Denmark–Norway before Roskilde|Роскиллеге чейинки Дания–Норвегия','Общая монархия контролирует датские проливы и норвежские морские связи. Войны со Швецией меняют границы.|The shared monarchy controls the Danish straits and Norwegian maritime links. Wars with Sweden change borders.|Жалпы монархия Дания кысыктарын жана Норвегиянын деңиз байланыштарын көзөмөлдөйт. Швеция менен согуштар чек араны өзгөртөт.',[dk[0],islands,dk[2],skane]],
 [1658,1790,'После утраты Сконе|After the loss of Scania|Сконени жоготкондон кийин','Роскилльский мир передаёт Сконе Швеции. Датско-норвежская монархия сохраняется; с 1660 года усиливается королевская власть.|The Treaty of Roskilde transfers Scania to Sweden. The Danish–Norwegian monarchy survives; royal power strengthens from 1660.|Роскилле тынчтыгы Сконени Швецияга берет. Дания–Норвегия монархиясы сакталат; 1660-жылдан падышалык бийлик күчөйт.',[dk[0],islands,dk[2]]]]);
 put('early-sweden',['Scandinavia','Russia','BalticAudit'],'#b0a178',[
 [1601,1617,'Швеция, Финляндия и Эстляндия|Sweden, Finland and Estonia|Швеция, Финляндия жана Эстляндия','Корона объединяет шведские и финляндские земли и северную Эстляндию. Таллин находится под шведской властью с 1561 года.|The crown links Swedish and Finnish lands with northern Estonia. Tallinn has been under Swedish rule since 1561.|Таажы швед жана фин жерлерин түндүк Эстляндия менен бириктирет. Таллин 1561-жылдан Швециянын бийлигинде.',[swedenCore,finlandOld,estonia]],
 [1617,1621,'Приобретение Ингрии|Acquisition of Ingria|Ингриянын алынышы','Столбовский мир передаёт Ингрию Швеции. Корона расширяет контроль над побережьем Финского залива.|The Treaty of Stolbovo transfers Ingria to Sweden. The crown expands control along the Gulf of Finland.|Столбово тынчтыгы Ингрияны Швецияга берет. Таажы Фин булуңунун жээгиндеги көзөмөлүн кеңейтет.',[swedenCore,finlandOld,estonia,ingria]],
 [1621,1629,'Взятие Риги|Capture of Riga|Риганын алынышы','Шведские войска берут Ригу в 1621 году. Борьба за остальные земли Лифляндии продолжается.|Swedish troops take Riga in 1621. Fighting over the remaining Livonian lands continues.|Швед аскерлери Риганы 1621-жылы алат. Лифляндиянын калган жерлери үчүн күрөш уланат.',[swedenCore,finlandOld,estonia,ingria,rigaCore]],
 [1629,1658,'Шведская балтийская держава|Swedish Baltic power|Швециянын Балтика державасы','Альтмаркское перемирие закрепляет Ригу и большую часть Лифляндии за Швецией. Латгалия остаётся в Речи Посполитой.|Altmark confirms Riga and most of Livonia under Sweden. Latgale remains in the Commonwealth.|Альтмарк жарашуусу Рига менен Лифляндиянын көп бөлүгүн Швецияга бекитет. Латгалия Речь Посполитада калат.',[swedenCore,finlandOld,estonia,livonia,ingria]],
 [1658,1703,'Приобретение Сконе и Северная война|Acquisition of Scania and the Great Northern War|Сконенин алынышы жана Түндүк согуш','Сконе переходит Швеции. Великая Северная война с 1700 года ставит под угрозу её господство в восточной Балтике.|Scania passes to Sweden. The Great Northern War from 1700 threatens its eastern Baltic dominance.|Сконе Швецияга өтөт. 1700-жылдан Улуу Түндүк согуш анын чыгыш Балтикадагы үстөмдүгүнө коркунуч жаратат.',[swedenCore,finlandOld,skane,estonia,livonia,ingria]],
 [1703,1710,'Потеря невского устья|Loss of the Neva mouth|Неванын куймасынын жоголушу','Россия занимает невское устье и основывает Петербург. Шведские гарнизоны ещё удерживают Ригу, Ревель и Выборг.|Russia takes the Neva mouth and establishes Saint Petersburg. Swedish garrisons still hold Riga, Reval and Vyborg.|Орусия Неванын куймасын алып, Петербургду негиздейт. Швед гарнизондору Риганы, Ревелди жана Выборгду дагы кармап турат.',[swedenCore,finlandOld,skane,estonia,livonia,ingria1703]],
 [1710,1721,'Потеря прибалтийских крепостей|Loss of the Baltic fortresses|Балтика чептеринин жоголушу','Российские войска берут Ригу, Ревель и Выборг. Военные потери закрепляются Ништадтским миром в 1721 году.|Russian troops take Riga, Reval and Vyborg. Nystad confirms the wartime losses in 1721.|Орус аскерлери Риганы, Ревелди жана Выборгду алат. Аскердик жоготуулар 1721-жылкы Ништадт тынчтыгы менен бекитилет.',[swedenCore,finland,skane]],
 [1721,1743,'Швеция после Ништадта|Sweden after Nystad|Ништадттан кийинки Швеция','Балтийские провинции уступлены России. Швеция сохраняет большую часть Финляндии и Сконе; роль сословного парламента возрастает.|The Baltic provinces are ceded to Russia. Sweden retains most of Finland and Scania; the estate parliament gains influence.|Балтика провинциялары Орусияга берилет. Швеция Финляндиянын көп бөлүгүн жана Сконени сактайт; сословие парламентинин ролу өсөт.',[swedenCore,finland,skane]],
 [1743,1790,'После Абоского мира|After the Treaty of Åbo|Або тынчтыгынан кийин','Новая война заканчивается уступкой России части юго-восточной Финляндии. Остальные финляндские земли остаются шведскими.|Another war ends with the cession of part of southeastern Finland to Russia. The remaining Finnish lands stay Swedish.|Жаңы согуш түштүк-чыгыш Финляндиянын бир бөлүгүн Орусияга берүү менен аяктайт. Калган фин жерлери Швецияда калат.',[swedenCore,finland1743,skane]]]);
 c.sources.to1789BalticAudit.title += ' National Archives of Finland. Vanha Suomi. Lund University Library. De la Gardie archive guide.';
 c.sources.to1789BalticAudit.urls.push('https://portti.kansallisarkisto.fi/arkistojen-portti/vanha-suomi','https://www.alvin-portal.org/alvin/attachment/document/alvin-record%3A80347/ATTACHMENT-0002.pdf');
 H.event('1789-first-partition',1772,'early-commonwealth','politics',[21.01,52.23],T('Первый раздел Речи Посполитой|First partition of the Commonwealth|Речь Посполитанын биринчи бөлүштүрүлүшү'),T('Три соседние монархии присоединяют части страны. Карта показывает приобретения и сохраняющееся государство.|Three neighbouring monarchies annex parts of the country. The map shows the acquisitions and the surviving state.|Үч коңшу монархия өлкөнүн бөлүктөрүн кошуп алат. Карта алынган жерлерди жана сакталып калган мамлекетти көрсөтөт.'),refs(['Poland','EuropeTransitions']));
 if(c.to1789EurasiaDecisions){c.to1789EurasiaDecisions.continued.push(...ids.filter(id=>id.startsWith('early-')));c.to1789EurasiaDecisions.newEntries.push(...ids.filter(id=>id.startsWith('1789-')));c.to1789EurasiaDecisions.unhandled=c.to1789EurasiaDecisions.unhandled.filter(id=>!ids.includes(id));}
 const economic={
  italy:T('Городские ремёсла, земледелие и средиземноморская торговля связывают города с сельскими округами.|Urban crafts, agriculture and Mediterranean trade connect towns with rural districts.|Шаар кол өнөрчүлүгү, дыйканчылык жана Жер Ортолук деңиз соодасы шаарларды айыл аймактарына байланыштырат.'),
  north:T('Морская торговля, рыболовство, лес и металлы связывают северные области с европейскими рынками.|Maritime trade, fishing, timber and metals connect northern regions with European markets.|Деңиз соодасы, балыкчылык, жыгач жана металлдар түндүк аймактарды Европа базарларына байланыштырат.'),
  central:T('Земледельческие имения, ремесленные города и региональные рынки обеспечивают хозяйство и государственные доходы.|Agricultural estates, craft towns and regional markets support the economy and public revenue.|Дыйканчылык ээликтери, кол өнөрчүлүк шаарлары жана аймактык базарлар чарба менен мамлекеттик кирешелерди камсыздайт.')
 };
 for(const id of ids)for(const p of c.entries.find(e=>e.id===id).phases.filter(p=>p.from>=1601)){
  const group=/venice|milan|florence|papal|naples/.test(id)?'italy':/sweden|denmark/.test(id)?'north':'central';
  p.learning={government:p.text,economy:economic[group],society:T('Положение человека зависит от сословия, места жительства и местных учреждений; городские и сельские общины сохраняют свои обычаи.|A person’s position depends on social estate, residence and local institutions; urban and rural communities maintain their customs.|Адамдын абалы сословиесине, жашаган жерине жана жергиликтүү мекемелерге байланыштуу; шаар жана айыл жамааттары өз салттарын сактайт.')};
 }
 return c;
};
