'use strict';
module.exports=(c,{G,set,source,event,box})=>{
 source('Tasmania','University of Tasmania. The Companion to Tasmanian History: John Bowen.',['https://www.utas.edu.au/library/companion_to_tasmanian_history/B/John%20Bowen.htm']);
 source('CreekWar','National Park Service. Fort Mims; Horseshoe Bend National Military Park.',['https://www.nps.gov/places/fort-mims.htm','https://www.nps.gov/hobe/learn/historyculture/index.htm']);
 set('1789-tasmania',[[1790,1803,'Тасмания · коренные общества|Tasmania · Indigenous societies|Тасмания · түпкү коомдор','Общины используют прибрежные, лесные и внутренние земли острова; постоянных британских поселений ещё нет.|Communities use coastal, forest and inland environments; there are no permanent British settlements yet.|Жамааттар аралдын жээк, токой жана ички жерлерин пайдаланат; туруктуу британ конуштары али жок.'],[1803,1816,'Тасмания · коренные общества и колонизация|Tasmania · Indigenous societies and colonisation|Тасмания · түпкү коомдор жана колониялаштыруу','Поселения на Деруэнте и Тамаре занимают часть местных земель. Контакты сопровождаются вооружённым насилием и изменением доступа к ресурсам.|Settlements on the Derwent and Tamar occupy some Indigenous lands. Contact brings armed violence and changes access to resources.|Деруэнт менен Тамардагы конуштар түпкү элдин жеринин бир бөлүгүн ээлейт. Байланыштар куралдуу зомбулукка жана ресурстарга жетүүнүн өзгөрүшүнө алып келет.']],{sources:['to1815Tasmania']});
 set('1815-hobart',[[1803,1804,'Рисдон-Ков · британское поселение|Risdon Cove · British settlement|Рисдон-Ков · британ конушу','Отряд Джона Боуэна основывает поселение на восточном берегу Деруэнта.|John Bowen’s party establishes a settlement on the eastern bank of the Derwent.|Жон Боуэндин тобу Деруэнттин чыгыш жээгинде конуш негиздейт.',box(147.32,-42.84,147.38,-42.8),'settlement',null,[147.35,-42.82]],[1804,1816,'Хобарт · британская колония|Hobart · British colony|Хобарт · британ колониясы','Дэвид Коллинз обосновывается в Салливанс-Ков. Хобарт становится центром колониального управления на юге острова.|David Collins settles at Sullivans Cove. Hobart becomes the centre of colonial government in the island’s south.|Дэвид Коллинз Салливанс-Ковдо жайгашат. Хобарт аралдын түштүгүндөгү колониялык башкаруунун борбору болот.',box(147.25,-42.95,147.38,-42.85),'settlement',null,[147.33,-42.88]]],{region:'australia',kind:'city',coord:[147.35,-42.82],sources:['to1815Tasmania']});
 set('1789-mobile',[[1790,1813,'Мобил · Испания|Mobile · Spain|Мобил · Испания','Испанский порт контролирует выход реки Мобил к Мексиканскому заливу.|The Spanish port controls the Mobile River’s outlet to the Gulf of Mexico.|Испан порту Мобил дарыясынын Мексика булуңуна чыгышын көзөмөлдөйт.'],[1813,1816,'Мобил · Соединённые Штаты|Mobile · United States|Мобил · Америка Кошмо Штаттары','Американские войска занимают Мобил в апреле 1813 года; испанское управление прекращается.|US forces occupy Mobile in April 1813, ending Spanish administration.|АКШ аскерлери 1813-жылдын апрелинде Мобилди ээлеп, испан башкаруусун токтотот.',null,'settlement','#859dae']]);
 set('1789-muscogee',[[1790,1813,'Мускоги · союз городов|Muscogee · alliance of towns|Мускоги · шаарлар союзу','Советы городов поддерживают союзы и торговлю; давление США и разногласия о новых порядках усиливаются.|Town councils maintain alliances and trade; US pressure and disagreements over new ways intensify.|Шаар кеңештери союздарды жана сооданы сактайт; АКШнын басымы жана жаңы тартип тууралуу пикир келишпестиктер күчөйт.'],[1813,1814,'Мускоги · Крикская война|Muscogee · Creek War|Мускоги · Крик согушу','Красные Палки противостоят силам США и их союзникам, включая другие группы мускоги. Война раскалывает союз городов.|The Red Sticks oppose US forces and their allies, including other Muscogee groups. War divides the alliance of towns.|Кызыл Таяктар АКШ күчтөрүнө жана анын союздаштарына, анын ичинде башка мускоги топторуна каршы турат. Согуш шаарлар союзун бөлөт.'],[1814,1816,'Мускоги после договора Форт-Джексон|Muscogee after Fort Jackson|Форт-Жексон келишиминен кийинки мускоги','После поражения при Хорсшу-Бенд договор Форт-Джексон отнимает обширные земли, в том числе у союзников США. Общины продолжают жить на оставшейся территории.|After defeat at Horseshoe Bend, the Treaty of Fort Jackson takes extensive lands, including those of US allies. Communities continue on the remaining territory.|Хорсшу-Бенддеги жеңилүүдөн кийин Форт-Жексон келишими АКШнын союздаштарынын да кеңири жерлерин тартып алат. Жамааттар калган аймакта жашоосун улантат.',[[[-86.3,32.4],[-85.9,34],[-84.5,34],[-84.8,32.4]]],'influence']],{sources:['to1815CreekWar']});
 event('horseshoe',1814,'1789-muscogee','Сражение при Хорсшу-Бенд|Battle of Horseshoe Bend|Хорсшу-Бенд салгылашуусу','Поражение Красных Палок предшествует принудительной уступке земель по договору Форт-Джексон.|The Red Sticks’ defeat precedes the forced land cession at Fort Jackson.|Кызыл Таяктардын жеңилиши Форт-Жексон келишими менен жерди мажбурлап өткөрүүгө алып келет.',[-85.73,32.97],'war');
 // This island was absent from the earlier mainland Naples core. Keep its own crown visible.
 set('1815-sicily',[[1790,1806,'Королевство Сицилия|Kingdom of Sicily|Сицилия падышалыгы','Бурбонский монарх правит Сицилией и Неаполем как отдельными королевствами.|The Bourbon monarch rules Sicily and Naples as separate kingdoms.|Бурбон монархы Сицилия менен Неаполду өзүнчө падышалыктар катары башкарат.',[[[12.4,37.7],[13,38.2],[15.6,38.3],[15.2,36.7],[14,37],[12.4,37.7]]]],[1806,1816,'Сицилия · Бурбоны|Sicily · Bourbons|Сицилия · Бурбондор','После французского завоевания Неаполя Бурбоны сохраняют Сицилию при британской поддержке. В 1812 году принимается конституция.|After the French conquest of Naples, the Bourbons retain Sicily with British support. A constitution is adopted in 1812.|Француздар Неаполду алгандан кийин Бурбондор Британиянын колдоосу менен Сицилияны сактайт. 1812-жылы конституция кабыл алынат.',[[[12.4,37.7],[13,38.2],[15.6,38.3],[15.2,36.7],[14,37],[12.4,37.7]]]]],{region:'eurasia',coord:[13.36,38.12],sources:['to1815Napoleon','to1815Vienna'],color:'#b89d77'});
 // Calabria is part of the mainland kingdom; its tip must not be clipped away.
 for(const a of c.areas.filter(a=>a.entry==='early-naples'&&a.from>=1790)) {a.polygons=G('early-naples');a.points=a.polygons[0];}
 // Generic eighteenth-century continuation cards must not promise colonisation still in the future.
 const refresh=(id,name,body)=>set(id,[[1790,1816,name,body]]);
 refresh('tonga','Тонга · соперничество династий|Tonga · dynastic rivalry|Тонга · династиялардын атаандаштыгы','Власть распределена между династическими линиями и островными руководителями. С конца 1790-х годов войны меняют политические союзы.|Power is shared between dynastic lines and island chiefs. From the late 1790s, wars reshape political alliances.|Бийлик династиялык бутактар менен арал башчыларынын ортосунда бөлүштүрүлгөн. 1790-жылдардын аягынан согуштар саясий союздарды өзгөртөт.');
 refresh('early-motutapu','Мотутапу · поселения маори|Motutapu · Māori settlements|Мотутапу · маори конуштары','Островные общины связаны с земледелием, рыболовством и укреплёнными поселениями залива Хаураки.|Island communities are connected through farming, fishing and fortified settlements of the Hauraki Gulf.|Арал жамааттары дыйканчылык, балык уулоо жана Хаураки булуңундагы чептүү конуштар аркылуу байланышат.');
 c.sources.to1815Vienna.title='Fondation Napoléon. The Congress of Vienna; Europe in 1815.';
 c.sources.to1815China.title='Library of Congress. China: a country study. Historical setting.';
 c.sources.to1815Java={title:'Library of Congress. Indonesia: a country study. Historical setting.',urls:['https://tile.loc.gov/storage-services/master/frd/frdcstdy/in/indonesiacountry00fred/indonesiacountry00fred.pdf']};
 source('Sikh','Sikh Research Journal. Life at the Lahore Darbār: 1799–1839.',['https://sikhresearchjournal.org/index.php/srj/article/view/122']);
 for(const p of c.entries.find(e=>e.id==='1815-sikh').phases)p.sources=['to1815Sikh'];
 for(const a of c.areas.filter(a=>a.entry==='1815-sikh'))a.sources=['to1815Sikh'];
 set('early-milan',[
 [1790,1796,'Милан · Габсбурги|Milan · Habsburg rule|Милан · Габсбург бийлиги','Миланское герцогство находится под властью Габсбургов до похода Бонапарта.|The Duchy of Milan is under Habsburg rule until Bonaparte’s campaign.|Милан герцогдугу Бонапарттын жортуулуна чейин Габсбург бийлигинде болот.'],
 [1796,1797,'Милан · французское управление|Milan · French administration|Милан · француз башкаруусу','После вступления французской армии вводится временное управление.|A provisional administration follows the arrival of the French army.|Француз аскерлери келгенден кийин убактылуу башкаруу киргизилет.',null,'polity','#a38b81'],
 [1797,1799,'Цизальпийская республика|Cisalpine Republic|Цизальпия республикасы','Создаётся республика под французским покровительством со столицей в Милане.|A republic under French protection is established with Milan as its capital.|Франциянын колдоосунда борбору Миландагы республика түзүлөт.',null,'polity','#a38b81'],
 [1799,1800,'Милан · австрийское возвращение|Milan · Austrian return|Милан · Австриянын кайтышы','Поход армий коалиции прерывает существование республики и возвращает австрийское управление.|The coalition campaign interrupts the republic and restores Austrian administration.|Коалициянын жортуулу республиканы токтотуп, Австрия башкаруусун кайтарат.',null,'polity','#baa780'],
 [1800,1802,'Восстановленная Цизальпийская республика|Restored Cisalpine Republic|Калыбына келген Цизальпия республикасы','Победа Бонапарта при Маренго позволяет восстановить республику.|Bonaparte’s victory at Marengo enables the restoration of the republic.|Бонапарттын Маренгодогу жеңиши республиканы калыбына келтирет.',null,'polity','#a38b81'],
 [1802,1805,'Итальянская республика|Italian Republic|Италия республикасы','Новая конституция преобразует Цизальпийскую республику в Итальянскую; Бонапарт становится президентом.|A new constitution transforms the Cisalpine Republic into the Italian Republic, with Bonaparte as president.|Жаңы конституция Цизальпия республикасын Италия республикасына өзгөртүп, Бонапарт президент болот.',null,'polity','#a38b81'],
 [1805,1814,'Наполеоновское королевство Италия|Napoleonic Kingdom of Italy|Наполеондун Италия падышалыгы','Наполеон принимает итальянскую корону; Милан служит столицей королевства.|Napoleon takes the Italian crown; Milan is the kingdom’s capital.|Наполеон Италия таажысын алат; Милан падышалыктын борбору болот.',null,'polity','#a38b81'],
 [1814,1816,'Милан · Австрия|Milan · Austria|Милан · Австрия','Австрийская власть возвращается. В 1815 году Ломбардия входит в новое Ломбардо-Венецианское королевство.|Austrian rule returns. In 1815 Lombardy enters the new Kingdom of Lombardy-Venetia.|Австрия бийлиги кайтып келет. 1815-жылы Ломбардия жаңы Ломбардия-Венеция падышалыгына кирет.',null,'polity','#baa780']
 ],{sources:['to1815Napoleon','to1815Vienna']});
 // The western Galician core changes hands with the Duchy of Warsaw in 1809.
 function eastOf(ring,x){
  const out=[];for(let i=0;i<ring.length;i++){
   const a=ring[i],b=ring[(i+1)%ring.length],ai=a[0]>=x,bi=b[0]>=x;
   if(ai)out.push(a);if(ai!==bi)out.push([x,a[1]+(b[1]-a[1])*(x-a[0])/(b[0]-a[0])]);
  }return out;
 }
 const austria=G('early-austria'),westGalicia=box(19,50.25,22.5,51.5);
 set('early-austria',[
 [1790,1795,'Габсбургская монархия|Habsburg monarchy|Габсбург монархиясы','Габсбурги управляют составной монархией и участвуют в войнах с революционной Францией.|The Habsburgs govern a composite monarchy and join the wars against revolutionary France.|Габсбургдар курама монархияны башкарып, революциялык Францияга каршы согуштарга катышат.'],
 [1795,1804,'Габсбурги · Галиция и австрийские земли|Habsburgs · Galicia and Austrian lands|Габсбургдар · Галиция жана Австрия жерлери','Третий раздел Речи Посполитой добавляет западногалицийские земли.|The third partition of the Commonwealth adds western Galician lands.|Речь Посполитанын үчүнчү бөлүштүрүлүшү батыш Галиция жерлерин кошот.',[...austria,...westGalicia]],
 [1804,1809,'Австрийская империя|Austrian Empire|Австрия империясы','Франц принимает титул императора Австрии. Войны с Наполеоном изменяют положение державы.|Francis takes the title Emperor of Austria. Wars with Napoleon reshape the state’s position.|Франц Австрия императору наамын алат. Наполеон менен согуштар мамлекеттин абалын өзгөртөт.',[...austria,...westGalicia]],
 [1809,1815,'Австрийская империя после Шёнбрунна|Austrian Empire after Schönbrunn|Шёнбрунндан кийинки Австрия империясы','Поражение 1809 года ведёт к территориальным уступкам. Западная Галиция переходит Варшавскому герцогству.|Defeat in 1809 brings territorial cessions. Western Galicia passes to the Duchy of Warsaw.|1809-жылкы жеңилүү жерди өткөрүүгө алып келет. Батыш Галиция Варшава герцогдугуна өтөт.',[...austria.slice(0,2),eastOf(austria[2],22.5)]],
 [1815,1816,'Австрийская империя · Венское урегулирование|Austrian Empire · Vienna settlement|Австрия империясы · Венадагы жөнгө салуу','Венское урегулирование укрепляет Австрию. Ломбардия и Венеция образуют отдельное королевство под властью Габсбургов; Краков становится вольным городом.|The Vienna settlement strengthens Austria. Lombardy and Venetia form a separate Habsburg kingdom; Kraków becomes a free city.|Венадагы жөнгө салуу Австрияны күчөтөт. Ломбардия менен Венеция Габсбургдардын өзүнчө падышалыгын түзөт; Краков эркин шаар болот.',austria]
 ],{sources:['to1815Napoleon','to1815Vienna']});
 for(const p of c.entries.find(e=>e.id==='hawaii').phases.filter(p=>p.from>=1795))p.kind='state';
};
