'use strict';
// Replace dated continuations: a polity's last eighteenth-century description is
// not evidence that its rulers, colonial status or territory stayed unchanged.
module.exports=(c,{G,set,source,event,box})=>{
 source('Removal','National Park Service. Muscogee (Creek) Removal.',['https://www.nps.gov/ocmu/learn/historyculture/upload/Accessible-Muscogee-Creek-Removal.pdf']);
 source('Emancipation','The National Archives. British transatlantic slave trade records.',['https://www.nationalarchives.gov.uk/help-with-your-research/research-guides/british-transatlantic-slave-trade-records/']);
 source('Caucasus','Encyclopaedia Iranica. Erevan.',['https://www.iranicaonline.org/articles/erevan-1/']);
 source('Kazakh','Қазақстан тарихы. 1822–1824 жылдардағы реформалар.',['https://e-history.kz/kz/history-of-kazakhstan/show/8612']);
 source('Burma','National Army Museum. A timeline of Burma and the Army.',['https://www.nam.ac.uk/explore/timeline-burma-army']);
 source('Melaka','Kerajaan Negeri Melaka. Sejarah Melaka.',['https://www.melaka.gov.my/kerajaan/info-negeri/sejarah.html']);
 source('Tripoli','Library of Congress, Federal Research Division. Libya: a country study. Historical setting.',['https://www.loc.gov/item/88600480/']);
 source('Tahiti','National Library of New Zealand. Confederation and Annexation: papers respecting the Pacific Islands, 1884.',['https://paperspast.natlib.govt.nz/parliamentary/AJHR1884-II.2.1.2.4']);
 source('Champa','Po Dharma. The Nguyen and Champa. Champaka, 5.',['https://champa.one/files/Champa_Heritage/Champaka5/Champaka_5_putra.pdf']);
 const put=(id,rows,sources)=>set(id,rows,sources?{sources}:{});
 const refresh=(id,name,body,sources)=>put(id,[[1816,1849,name,body]],sources);
 set('1815-tambora',[]);
 for(const id of ['early-st-augustine','1789-gulf-florida']){
  const n=id==='early-st-augustine'?'Сан-Агустин|St Augustine|Сан-Агустин':'Пенсакола|Pensacola|Пенсакола';
  put(id,[[1816,1821,n,'Испанская администрация удерживает прибрежный центр Флориды.|Spanish administration holds this coastal centre in Florida.|Испан башкаруусу Флоридадагы бул жээк борборун кармайт.'],[1821,1849,n.split('|').map((x,i)=>x+' · '+['США','USA','АКШ'][i]).join('|'),'Испания передаёт Флориду Соединённым Штатам по договору Адамса — Ониса, вступившему в силу в 1821 году.|Spain transfers Florida to the United States under the Adams–Onís Treaty, effective in 1821.|1821-жылы күчүнө кирген Адамс — Онис келишими боюнча Испания Флориданы АКШга берет.',null,'settlement','#859dae']],['to1848USMexico','to1789Gulf']);
 }
 refresh('1789-usa','Соединённые Штаты|United States|Америка Кошмо Штаттары','Федерация расширяется на запад. Каналы, фабрики и торговля растут; распространение рабства и захват земель коренных народов усиливают политические конфликты.|The federation expands westward. Canals, factories and trade grow; slavery’s expansion and Indigenous land dispossession intensify political conflict.|Федерация батышка кеңейет. Каналдар, фабрикалар жана соода өсөт; кулчулуктун жайылышы жана түпкү элдин жеринин тартылышы саясий жаңжалдарды күчөтөт.');
 put('1789-muscogee',[[1816,1836,'Мускоги · оставшиеся восточные земли|Muscogee · remaining eastern lands|Мускоги · калган чыгыш жерлери','После Крикской войны общины восстанавливают хозяйство, но новые уступки земли сокращают их территорию.|After the Creek War, communities rebuild livelihoods, but further land cessions reduce their territory.|Крик согушунан кийин жамааттар чарбасын калыбына келтирет, бирок жаңы жер өткөрүүлөр аймагын кыскартат.'],[1836,1838,'Мускоги · принудительное переселение|Muscogee · forced removal|Мускоги · мажбурлап көчүрүү','В 1836–1837 годах тысячи людей принудительно отправлены на Индейскую территорию к западу от Миссисипи. Болезни и тяжёлые условия приводят к многочисленным смертям.|In 1836–1837 thousands are forcibly taken to Indian Territory west of the Mississippi. Disease and harsh conditions cause many deaths.|1836–1837-жылдары миңдеген адам Миссисипинин батышындагы Индей аймагына мажбурлап жөнөтүлөт. Оору жана оор шарт көп өлүмгө алып келет.',[...G('1789-muscogee'),...box(-96.7,34.8,-95,36.1)],'cultural'],[1838,1849,'Мускоги · Индейская территория|Muscogee · Indian Territory|Мускоги · Индей аймагы','Переселённые общины создают новые поселения и восстанавливают управление на западе; часть мускоги остаётся на юго-востоке.|Removed communities establish new settlements and rebuild government in the west; some Muscogee remain in the southeast.|Көчүрүлгөн жамааттар батышта жаңы конуштарды түзүп, башкарууну калыбына келтирет; мускогилердин бир бөлүгү түштүк-чыгышта калат.',[...box(-96.7,34.8,-95,36.1),...box(-87.7,31,-87.4,31.2)],'cultural',null,[-95.98,35.62]]],['to1848Removal']);
 for(const id of ['1789-jamaica','1789-cape']){
  const name=id==='1789-jamaica'?'Ямайка · британская колония|Jamaica · British colony|Ямайка · британ колониясы':'Капская колония · Британия|Cape Colony · Britain|Кап колониясы · Британия';
  put(id,[[1816,1834,name,'Колониальная экономика использует рабский труд. Свободные жители и порабощённые люди имеют неравные права.|The colonial economy uses enslaved labour. Free and enslaved people have unequal rights.|Колониялык чарба кул эмгегин колдонот. Эркин жана кул адамдардын укуктары тең эмес.'],[1834,1838,name,'Отмена рабства сопровождается обязательным переходным трудом бывших рабов — системой «ученичества».|Abolition is followed by compulsory transitional labour for formerly enslaved people under the apprenticeship system.|Кулчулук жоюлгандан кийин мурдагы кулдар «шакирттик» системасында милдеттүү өткөөл эмгекти аткарат.'],[1838,1849,name,'Система «ученичества» прекращена. Бывшие рабы добиваются земли и самостоятельного заработка в условиях колониального неравенства.|Apprenticeship ends. Formerly enslaved people seek land and independent livelihoods amid colonial inequality.|«Шакирттик» системасы токтойт. Мурдагы кулдар колониялык теңсиздик шартында жерге жана өз алдынча кирешеге умтулат.']],['to1848Emancipation']);
 }
 for(const id of ['sican','lucre','wanka','early-chimu-communities','early-chincha-valley']){
  const e=c.entries.find(e=>e.id===id),p=e.phases.find(p=>p.from===1816);
  put(id,[[1816,1824,p.name,p.text],[1824,1849,p.name,'Общины продолжают земледелие, ремесло и обмен в независимом Перу. Смена государственного строя не отменяет земельные споры и социальное неравенство.|Communities continue farming, crafts and trade in independent Peru. Political change does not end land disputes or social inequality.|Жамааттар көз карандысыз Перуда дыйканчылык, кол өнөрчүлүк жана сооданы улантат. Мамлекеттик түзүлүштүн өзгөрүшү жер талашын жана социалдык теңсиздикти жойбойт.']],['to1848Peru']);
 }
 refresh('yucatan-late','Майя Юкатана|Maya of Yucatán|Юкатан майялары','Общины сохраняют языки, земледелие и местные институты. Споры о земле и налогах приводят в 1847 году к масштабному восстанию — Кастовой войне.|Communities maintain languages, farming and local institutions. Disputes over land and taxation lead to the large uprising of 1847 known as the Caste War.|Жамааттар тилдерин, дыйканчылыгын жана жергиликтүү институттарын сактайт. Жер жана салык талаштары 1847-жылы Касталык согуш деп аталган чоң көтөрүлүшкө алып келет.');
 const erivan=box(43.9,39.8,45.2,40.6),nakh=box(44.8,38.9,46,39.6),iran=G('1789-qajar'),russia=G('1789-russian-empire');
 put('1789-qajar',[[1816,1828,'Каджарский Иран|Qajar Iran|Кажар Ираны','После Гюлистанского мира Иран сохраняет Эриванское и Нахичеванское ханства. Новая война с Россией начинается в 1826 году.|After the Treaty of Gulistan, Iran retains the khanates of Erevan and Nakhchivan. War with Russia resumes in 1826.|Гүлстан келишиминен кийин Иран Эриван жана Нахичеван хандыктарын сактайт. Орусия менен жаңы согуш 1826-жылы башталат.',[...iran,...erivan,...nakh]],[1828,1849,'Каджарский Иран · после Туркманчая|Qajar Iran · after Turkmenchay|Кажар Ираны · Түркмөнчайдан кийин','Туркманчайский договор передаёт Эриванское и Нахичеванское ханства России. Каджарская монархия сохраняет власть в Иране.|The Treaty of Turkmenchay cedes the khanates of Erevan and Nakhchivan to Russia. The Qajar monarchy continues in Iran.|Түркмөнчай келишими Эриван жана Нахичеван хандыктарын Орусияга берет. Кажар монархиясы Иранда бийлигин сактайт.',iran]],['to1848Caucasus']);
 put('1789-russian-empire',[[1816,1828,'Российская империя|Russian Empire|Орусия империясы','Империя удерживает приобретения Венского урегулирования и Гюлистанского мира. На Кавказе завоевание встречает длительное сопротивление.|The empire retains the gains of Vienna and Gulistan. Conquest in the Caucasus faces prolonged resistance.|Империя Венадагы жөнгө салуу жана Гүлстан келишими менен алган ээликтерин сактайт. Кавказды басып алуу узак каршылыкка туш болот.',russia],[1828,1849,'Россия · приобретения по Туркманчаю|Russia · gains at Turkmenchay|Орусия · Түркмөнчайдагы ээликтер','Эриванское и Нахичеванское ханства переходят России. Кавказская война продолжается; независимые горские общества не равны покорённым областям.|Erevan and Nakhchivan pass to Russia. The Caucasian War continues; independent mountain societies remain distinct from conquered districts.|Эриван менен Нахичеван Орусияга өтөт. Кавказ согушу уланат; көз карандысыз тоолук коомдор басып алынган аймактардан айырмаланат.',[...russia,...erivan,...nakh]]],['to1848Caucasus','to1815Vienna']);
 put('early-kazakh',[[1816,1822,'Казахские жузы и ханская власть|Kazakh zhuzes and khans|Казак жүздөрү жана хан бийлиги','Жузы и местные объединения сохраняют собственных руководителей. Отношения с Россией, Цин и Кокандом различаются по регионам.|Zhuzes and local groupings retain their leaders. Relations with Russia, Qing and Kokand differ by region.|Жүздөр жана жергиликтүү бирикмелер өз башчыларын сактайт. Орусия, Цин жана Кокон менен мамилелер аймакка жараша айырмаланат.'],[1822,1849,'Казахские земли · реформы и сопротивление|Kazakh lands · reforms and resistance|Казак жерлери · реформалар жана каршылык','Российские реформы 1822 и 1824 годов упраздняют ханскую власть в Среднем и Младшем жузах. Местные общества, султаны и движения сопротивления сохраняются.|Russian reforms of 1822 and 1824 abolish khanly government in the Middle and Junior zhuzes. Local societies, sultans and resistance movements continue.|Орусиянын 1822 жана 1824-жылкы реформалары Орто жана Кичүү жүздөрдөгү хан бийлигин жоёт. Жергиликтүү коомдор, султандар жана каршылык кыймылдары сакталат.',null,'influence']],['to1848Kazakh']);
 refresh('early-bukhara','Бухарский эмират · Мангиты|Emirate of Bukhara · Manghits|Бухара эмираты · Мангыттар','Эмиры Хайдар, затем Насрулла укрепляют власть. Соперничество с Кокандом и Хивой связано с караванными путями, городами и оазисами.|Emirs Haydar and later Nasrullah consolidate rule. Rivalry with Kokand and Khiva concerns caravan routes, towns and oases.|Эмирлер Хайдар, андан кийин Насрулла бийликти бекемдейт. Кокон жана Хива менен атаандаштык кербен жолдоруна, шаарларга жана оазистерге байланышат.');
 refresh('early-khwarazm','Хивинское ханство · Кунграты|Khanate of Khiva · Qungrats|Хива хандыгы · Коңураттар','Кунгратские ханы правят из Хивы. Орошаемое земледелие, караванная торговля и отношения с туркменскими и казахскими объединениями определяют жизнь ханства.|Qungrat khans rule from Khiva. Irrigated farming, caravan trade and relations with Turkmen and Kazakh groupings shape the khanate.|Коңурат хандары Хивадан башкарат. Сугат дыйканчылыгы, кербен соодасы жана түркмөн, казак бирикмелери менен мамилелер хандыкка таасир этет.');
 put('1789-dutch-malacca',[[1816,1818,'Малакка · Британия|Malacca · Britain|Малакка · Британия','Британская администрация действует после наполеоновских войн.|British administration remains after the Napoleonic wars.|Наполеон согуштарынан кийин британ башкаруусу иштейт.'],[1818,1824,'Малакка · Нидерланды|Malacca · Netherlands|Малакка · Нидерланд','Малакка возвращена Нидерландам.|Malacca returns to Dutch rule.|Малакка Нидерланд башкаруусуна кайтарылат.'],[1824,1849,'Малакка · Британия|Malacca · Britain|Малакка · Британия','Англо-нидерландский договор передаёт Малакку Британии; с 1826 года она входит в Стрейтс-Сетлментс.|The Anglo-Dutch Treaty transfers Malacca to Britain; it joins the Straits Settlements in 1826.|Англия-Нидерланд келишими Малакканы Британияга берет; 1826-жылы Стрейтс-Сетлментске кирет.']],['to1848Melaka']);
 put('early-champa',[[1816,1832,'Пандуранга · чамская автономия|Panduranga · Cham autonomy|Пандуранга · чам автономиясы','Южное чамское княжество сохраняет местных правителей при верховенстве Нгуен.|The southern Cham principality retains local rulers under Nguyen supremacy.|Түштүк чам княздыгы Нгуендин үстөмдүгүндө жергиликтүү башкаруучуларын сактайт.'],[1832,1849,'Чамские общины · Вьетнам|Cham communities · Vietnam|Чам жамааттары · Вьетнам','Минь Манг упраздняет автономное княжество. Чамские общины сохраняют язык, религиозные традиции и хозяйство; сопротивление продолжается.|Minh Mang abolishes the autonomous principality. Cham communities retain language, religious traditions and livelihoods; resistance continues.|Минь Манг автономиялуу княздыкты жоёт. Чам жамааттары тилин, диний салттарын жана чарбасын сактайт; каршылык уланат.',null,'cultural']],['to1848Champa']);
 put('1789-konbaung',[[1816,1826,'Конбаун|Konbaung|Конбаун','Династия правит из бирманских столиц и расширяется на запад. Первая война с Британией начинается в 1824 году.|The dynasty rules from Burmese capitals and expands west. The first war with Britain begins in 1824.|Династия бирма борборлорунан башкарып, батышка кеңейет. Британия менен биринчи согуш 1824-жылы башталат.'],[1826,1849,'Конбаун · после Яндабо|Konbaung · after Yandabo|Конбаун · Яндабодон кийин','Яндабоский договор передаёт Аракан и Тенассерим Британии. Династия сохраняет центральную долину Иравади и Нижнюю Бирму.|The Treaty of Yandabo cedes Arakan and Tenasserim to Britain. The dynasty retains the central Irrawaddy valley and Lower Burma.|Яндабо келишими Аракан менен Тенассеримди Британияга берет. Династия Иравадинин борбордук өрөөнүн жана Төмөнкү Бирманы сактайт.']],['to1848Burma']);
 set('1848-burmese-coast',[[1826,1849,'Аракан и Тенассерим · Британия|Arakan and Tenasserim · Britain|Аракан жана Тенассерим · Британия','Прибрежные области переданы Ост-Индской компании после Первой англо-бирманской войны.|Coastal provinces pass to the East India Company after the First Anglo-Burmese War.|Биринчи англо-бирма согушунан кийин жээк аймактары Ост-Индия компаниясына өтөт.',[...box(92.5,19,94,21),...box(97.5,12,98.7,16)],'influence']],{region:'eurasia',coord:[92.9,20.15],sources:['to1848Burma']});
 refresh('1789-tayson','Вьетнам · династия Нгуен|Vietnam · Nguyen dynasty|Вьетнам · Нгуен династиясы','Двор в Хюэ укрепляет провинциальное управление. При Минь Манге проводится централизация, растут конфликты с местными обществами и миссионерами.|The court at Hue strengthens provincial government. Minh Mang centralises administration, with growing conflicts involving local societies and missionaries.|Хюэдеги сарай провинциялык башкарууну бекемдейт. Минь Манг башкарууну борборлоштуруп, жергиликтүү коомдор жана миссионерлер менен жаңжалдар күчөйт.');
 put('early-tripoli',[[1816,1835,'Триполи · Караманли|Tripoli · Karamanlis|Триполи · Караманлилер','Наследственная династия правит при номинальном османском верховенстве. Финансовые трудности и междоусобицы ослабляют власть.|The hereditary dynasty rules under nominal Ottoman supremacy. Financial troubles and internal conflict weaken government.|Мураскер династия Осмондун номиналдуу үстөмдүгүндө башкарат. Каржы кыйынчылыктары жана ички күрөш бийликти алсыратат.'],[1835,1849,'Триполи · османское управление|Tripoli · Ottoman rule|Триполи · Осмон башкаруусу','Османская экспедиция прекращает власть Караманли и восстанавливает прямое управление. Подчинение внутренних областей встречает сопротивление.|An Ottoman expedition ends Karamanli rule and restores direct government. Subjugation of inland districts meets resistance.|Осмон экспедициясы Караманли бийлигин токтотуп, түз башкарууну кайтарат. Ички аймактарды баш ийдирүү каршылыкка туш болот.']],['to1848Tripoli']);
 refresh('1789-oyo','Ойо · распад прежней державы|Oyo · fragmentation of the old empire|Ойо · мурдагы державанын ыдырашы','Внутренние войны и новые политические центры разрушают прежнюю систему дани. Йорубские города и общины продолжают собственную историю.|Internal wars and new political centres dismantle the former tribute system. Yoruba towns and communities continue their own histories.|Ички согуштар жана жаңы саясий борборлор мурдагы салык системасын бузат. Йоруба шаарлары жана жамааттары өз тарыхын улантат.');
 refresh('1789-dahomey','Дагомея · Абомей|Dahomey · Abomey|Дагомея · Абомей','При Гезо усиливаются армия и самостоятельность двора. Земледелие и ремесло существуют рядом с принудительным трудом и работорговлей.|Under Ghezo, the army and the court’s autonomy grow. Farming and crafts coexist with forced labour and the slave trade.|Гезонун тушунда аскер жана сарайдын өз алдынчалыгы күчөйт. Дыйканчылык жана кол өнөрчүлүк мажбур эмгек жана кул соодасы менен катар жашайт.');
 for(const id of ['thule','1789-greenland-posts'])refresh(id,id==='thule'?'Инуитские общества|Inuit societies|Инуит коомдору':'Гренландия · датские посты|Greenland · Danish posts|Гренландия · даниялык бекеттер','Инуитские общества поддерживают морское хозяйство и местные связи. Датские торговые пункты и миссии действуют на части гренландского побережья.|Inuit societies maintain maritime livelihoods and local connections. Danish trading posts and missions operate on parts of Greenland’s coast.|Инуит коомдору деңиз чарбасын жана жергиликтүү байланыштарын сактайт. Даниянын соода бекеттери менен миссиялары Гренландиянын жээгинин бир бөлүгүндө иштейт.');
 refresh('1815-rangihoua','Рангихоуа · маори и миссия|Rangihoua · Māori and the mission|Рангихоуа · маори жана миссия','После смерти Руатары в 1815 году отношения с местными руководителями остаются основой работы миссии. Маори участвуют в торговле и обмене знаниями.|After Ruatara’s death in 1815, relations with local leaders remain central to the mission. Māori participate in trade and exchanges of knowledge.|Руатара 1815-жылы өлгөндөн кийин жергиликтүү башчылар менен мамиле миссиянын ишинин негизи бойдон калат. Маори соодага жана билим алмашууга катышат.');
 set('1848-tahiti',[[1816,1842,'Таити · династия Помаре|Tahiti · Pomare dynasty|Таити · Помаре династиясы','Монархия Помаре укрепляет островное управление. Миссии и морская торговля меняют общественную жизнь.|The Pomare monarchy strengthens island government. Missions and maritime trade transform social life.|Помаре монархиясы арал башкаруусун бекемдейт. Миссиялар жана деңиз соодасы коомдук турмушту өзгөртөт.',box(-149.7,-17.85,-149.1,-17.45)],[1842,1849,'Таити · французский протекторат|Tahiti · French protectorate|Таити · француз протектораты','Франция устанавливает протекторат при сохранении монархии Помаре. Вооружённое сопротивление продолжается до 1847 года.|France establishes a protectorate while retaining the Pomare monarchy. Armed resistance continues until 1847.|Франция Помаре монархиясын сактап, протекторат орнотот. Куралдуу каршылык 1847-жылга чейин уланат.',box(-149.7,-17.85,-149.1,-17.45),'influence']],{region:'oceania',coord:[-149.57,-17.54],sources:['to1848Tahiti']});
 // A regional cultural layer must not claim that all Polynesian islands share Tahiti's status.
 refresh('eastpolynesia','Восточная Полинезия · островные общества|Eastern Polynesia · island societies|Чыгыш Полинезия · арал коомдору','Островные общества имеют разных правителей и самостоятельные традиции. Морская торговля, миссии и иностранное вмешательство меняют отношения между островами.|Island societies have different rulers and distinct traditions. Maritime trade, missions and foreign intervention reshape inter-island relations.|Арал коомдорунун ар башка башкаруучулары жана өз салттары бар. Деңиз соодасы, миссиялар жана чет элдик кийлигишүү аралдар аралык мамилени өзгөртөт.');
 event('muscogee',1836,'1789-muscogee','Принудительное переселение мускоги|Forced removal of the Muscogee|Мускогилерди мажбурлап көчүрүү','Военные конвои уводят общины на запад; многие переселенцы погибают в дороге.|Military escorts force communities west; many die during removal.|Аскер коштоосу жамааттарды батышка мажбурлап алып кетет; көптөр жолдо өлөт.',[-85.6,32.5],'migration');
 event('turkmenchay',1828,'1789-qajar','Туркманчайский договор|Treaty of Turkmenchay|Түркмөнчай келишими','Договор завершает русско-иранскую войну и передаёт России Эривань и Нахичевань.|The treaty ends the Russo-Iranian war and cedes Erevan and Nakhchivan to Russia.|Келишим орус-иран согушун аяктап, Эриван менен Нахичеванды Орусияга берет.',[47.4,37.6],'diplomacy');
};
