'use strict';
module.exports=(c,{G,set,source,event,T})=>{
 source('Europe','Eric Hobsbawm. The Age of Revolution: 1789–1848; Deutsches Historisches Museum. Vormärz und Revolution.',['https://www.dhm.de/lemo/kapitel/vormaerz-und-revolution/der-deutsche-bund']);
 source('Belgium','Belgium.be. Belgium’s independence; Belgian Foreign Affairs. Treaties of 1831 and 1839.',['https://www.belgium.be/en/about_belgium/country/history/belgium_from_1830','https://diplomatie.belgium.be/nl/beleid/beleidsthemas/uitgelicht/cijfer-van-april-2025-onze-fod-bewaart-alle-8100-verdragen-die-belgie-sedert-1830-afgesloten-heeft']);
 source('Greece','Hellenic Parliament. Constitutional History.',['https://www.hellenicparliament.gr/Vouli-ton-Ellinon/To-Politevma/Syntagmatiki-Istoria']);
 source('Reform','UK Parliament. The Reform Act 1832.',['https://www.parliament.uk/about/living-heritage/evolutionofparliament/houseofcommons/reformacts/overview/reformact1832/']);
 const put=(id,rows,meta={})=>set(id,rows,{sources:['to1848Europe'],...meta});
 put('late-france',[
 [1816,1830,'Франция · Реставрация|France · Bourbon Restoration|Франция · Бурбондордун кайтышы','Людовик XVIII и Карл X правят при Хартии 1814 года. Споры о королевской власти и представительстве ведут к Июльской революции.|Louis XVIII and Charles X rule under the Charter of 1814. Conflict over royal power and representation leads to the July Revolution.|Людовик XVIII жана Карл X 1814-жылкы Хартия боюнча башкарат. Падышалык бийлик жана өкүлчүлүк тууралуу талаш Июль революциясына алып келет.'],
 [1830,1848,'Франция · Июльская монархия|France · July Monarchy|Франция · Июль монархиясы','Луи-Филипп становится королём. Промышленность и города растут, но избирательное право остаётся ограниченным имущественным цензом.|Louis-Philippe becomes king. Industry and cities grow, but voting remains restricted by property qualifications.|Луи-Филипп падыша болот. Өнөр жай жана шаарлар өсөт, бирок шайлоо укугу мүлктүк талаптар менен чектелет.'],
 [1848,1849,'Франция · Вторая республика|France · Second Republic|Франция · Экинчи республика','Февральская революция свергает монархию. Вводится всеобщее мужское избирательное право; Июньское восстание рабочих подавлено.|The February Revolution overthrows the monarchy. Universal male suffrage is introduced; the June workers’ uprising is suppressed.|Февраль революциясы монархияны кулатат. Эркектерге жалпы шайлоо укугу берилет; июндагы жумушчулардын көтөрүлүшү басылат.']]);
 put('early-netherlands',[[1816,1830,'Королевство Нидерландов · юг|Kingdom of the Netherlands · south|Нидерланд падышалыгы · түштүк','Южные провинции входят в объединённое королевство Виллема I. Религиозные, языковые и политические противоречия усиливают оппозицию.|The southern provinces belong to William I’s united kingdom. Religious, linguistic and political tensions strengthen opposition.|Түштүк провинциялар Виллем Iнин бириккен падышалыгына кирет. Диний, тилдик жана саясий карама-каршылыктар оппозицияны күчөтөт.'],[1830,1831,'Бельгия · независимость|Belgium · independence|Бельгия · көз карандысыздык','Восстание в Брюсселе приводит к провозглашению независимости и избранию Национального конгресса.|The Brussels revolt leads to a declaration of independence and the election of a National Congress.|Брюсселдеги көтөрүлүш көз карандысыздыкты жарыялоого жана Улуттук конгрессти шайлоого алып келет.',null,'polity','#b19b69'],[1831,1849,'Королевство Бельгия|Kingdom of Belgium|Бельгия падышалыгы','Конституционная монархия Леопольда I развивает промышленность и железные дороги. Нидерланды признают независимость по Лондонскому договору 1839 года.|Leopold I’s constitutional monarchy develops industry and railways. The Netherlands recognises independence in the London treaty of 1839.|Леопольд Iнин конституциялык монархиясында өнөр жай жана темир жолдор өнүгөт. Нидерланд 1839-жылкы Лондон келишими менен көз карандысыздыкты тааныйт.',null,'polity','#b19b69']],{sources:['to1848Belgium']});
 put('early-dutch',[[1816,1830,'Королевство Нидерландов · север|Kingdom of the Netherlands · north|Нидерланд падышалыгы · түндүк','Гаага и Амстердам связаны с объединённым королевством и морской торговлей.|The Hague and Amsterdam are centres of the united kingdom and maritime trade.|Гаага менен Амстердам бириккен падышалыктын жана деңиз соодасынын борборлору.'],[1830,1849,'Королевство Нидерландов|Kingdom of the Netherlands|Нидерланд падышалыгы','После отделения Бельгии сохраняется северное королевство. Конституционная реформа 1848 года усиливает парламентское управление.|The northern kingdom survives Belgian separation. The constitutional reform of 1848 strengthens parliamentary government.|Бельгия бөлүнгөндөн кийин түндүк падышалык сакталат. 1848-жылкы конституциялык реформа парламенттик башкарууну күчөтөт.']]);
 put('late-hre',[[1816,1848,'Германский союз|German Confederation|Герман союзу','Союзный сейм заседает во Франкфурте. Австрия и Пруссия соперничают; промышленность, таможенные союзы и либеральные движения меняют германские государства.|The federal diet meets in Frankfurt. Austria and Prussia compete as industry, customs unions and liberal movements transform the German states.|Союздук сейм Франкфуртта иштейт. Австрия менен Пруссия атаандашат; өнөр жай, бажы бирликтер жана либералдык кыймылдар герман мамлекеттерин өзгөртөт.'],[1848,1849,'Германские государства · революция|German states · revolution|Герман мамлекеттери · революция','Во Франкфурте собирается Национальное собрание, обсуждающее объединение и конституцию. Монархии и их армии сохраняют силу.|A National Assembly meets in Frankfurt to debate unity and a constitution. Monarchies and their armies retain power.|Франкфурттагы Улуттук жыйын биригүү жана конституцияны талкуулайт. Монархиялар менен алардын аскерлери күчүн сактайт.']]);
 put('1789-great-britain',[[1816,1832,'Соединённое Королевство · индустриализация|United Kingdom · industrialisation|Бириккен Падышалык · индустриялашуу','Фабричное производство, уголь и транспорт меняют хозяйство. Движение за парламентскую реформу требует представительства промышленных городов.|Factories, coal and transport reshape the economy. Parliamentary reformers demand representation for industrial towns.|Фабрикалар, көмүр жана транспорт чарбаны өзгөртөт. Реформаторлор өнөр жай шаарларынын парламентте өкүл болушун талап кылат.'],[1832,1849,'Соединённое Королевство · реформы|United Kingdom · reform|Бириккен Падышалык · реформалар','Реформа 1832 года перераспределяет места в парламенте и расширяет электорат. Рабочие чартисты требуют дальнейших политических прав.|The 1832 reform redistributes parliamentary seats and enlarges the electorate. Working-class Chartists demand further political rights.|1832-жылкы реформа парламенттеги орундарды бөлүштүрүп, шайлоочулардын санын көбөйтөт. Жумушчу чартисттер кошумча саясий укуктарды талап кылат.']],{sources:['to1848Europe','to1848Reform']});
 for(const id of ['early-naples','1815-sicily'])put(id,[[1816,1848,'Королевство Обеих Сицилий|Kingdom of the Two Sicilies|Эки Сицилия падышалыгы','Неаполь и Сицилия объединены в одно Бурбонское королевство. Конституционное восстание 1820–1821 годов подавлено при австрийском вмешательстве.|Naples and Sicily are united in one Bourbon kingdom. The constitutional revolt of 1820–21 is suppressed with Austrian intervention.|Неаполь менен Сицилия бир Бурбон падышалыгына биригет. 1820–1821-жылкы конституциялык көтөрүлүш Австриянын кийлигишүүсү менен басылат.'],[1848,1849,id==='1815-sicily'?'Сицилия · революционное правительство|Sicily · revolutionary government|Сицилия · революциялык өкмөт':'Неаполь · конституционный кризис|Naples · constitutional crisis|Неаполь · конституциялык кризис','Революция начинается в Палермо. Сицилия отделяется от неаполитанского правительства; на материке король подавляет выступления.|Revolution begins in Palermo. Sicily separates from the Neapolitan government; on the mainland the king suppresses opposition.|Революция Палермодо башталат. Сицилия Неаполь өкмөтүнөн бөлүнөт; материкте падыша каршылыкты басат.']]);
 put('1815-warsaw',[[1816,1830,'Царство Польское · конституционная уния|Kingdom of Poland · constitutional union|Польша падышалыгы · конституциялык уния','Российский император одновременно является польским королём. Отдельная конституция, сейм и армия сосуществуют с растущими ограничениями.|The Russian emperor is also king of Poland. A separate constitution, diet and army coexist with growing restrictions.|Орус императору Польшанын да падышасы. Өзүнчө конституция, сейм жана аскер өсүп жаткан чектөөлөр менен катар жашайт.'],[1830,1832,'Польша · Ноябрьское восстание|Poland · November Uprising|Польша · Ноябрь көтөрүлүшү','Восстание начинается в Варшаве в ноябре 1830 года. Российская армия подавляет его в 1831 году.|An uprising begins in Warsaw in November 1830. The Russian army suppresses it in 1831.|Көтөрүлүш 1830-жылдын ноябрында Варшавада башталат. Орус аскерлери аны 1831-жылы басат.'],[1832,1849,'Царство Польское · Российская империя|Kingdom of Poland · Russian Empire|Польша падышалыгы · Россия империясы','Органический статут заменяет конституцию; польские сейм и армия упразднены. Участники восстания эмигрируют.|The Organic Statute replaces the constitution; the Polish diet and army are abolished. Participants in the uprising emigrate.|Органикалык статут конституцияны алмаштырат; поляк сейми менен аскери жоюлат. Көтөрүлүшчүлөрдүн бир бөлүгү эмиграцияга кетет.']]);
 const greek=[[[21.3,36.8],[22.9,36.3],[23.3,37.5],[24,38],[23.4,38.8],[21.1,39],[20.8,38.3],[21.4,37.8]]];
 put('1848-greece',[[1821,1830,'Греция · война за независимость|Greece · war of independence|Греция · көз карандысыздык согушу','Повстанцы и османско-египетские войска борются за Пелопоннес и центральную Грецию. Контур показывает основной район войны.|Insurgents and Ottoman-Egyptian forces contest the Peloponnese and central Greece. The outline marks the main war zone.|Көтөрүлүшчүлөр менен осмон-мисир аскерлери Пелопоннес жана борбордук Греция үчүн күрөшөт. Контур негизги согуш аймагын көрсөтөт.',greek,'influence'],[1830,1832,'Независимая Греция|Independent Greece|Көз карандысыз Греция','Лондонский протокол признаёт независимость. Новое государство занимает лишь часть грекоязычного мира.|The London Protocol recognises independence. The new state covers only part of the Greek-speaking world.|Лондон протоколу көз карандысыздыкты тааныйт. Жаңы мамлекет грек тилдүү дүйнөнүн бир бөлүгүн гана камтыйт.',greek],[1832,1849,'Королевство Греция|Kingdom of Greece|Греция падышалыгы','При Оттоне формируется королевство; Афины становятся столицей в 1834 году. После выступления 1843 года принята Конституция 1844 года.|A kingdom forms under Otto; Athens becomes the capital in 1834. The rising of 1843 leads to the constitution of 1844.|Оттондун тушунда падышалык түзүлөт; Афины 1834-жылы борбор болот. 1843-жылкы көтөрүлүштөн кийин 1844-жылкы конституция кабыл алынат.',greek]],{region:'eurasia',coord:[23.72,37.98],sources:['to1848Greece','to1848Europe'],color:'#8ba9ad'});
 event('france-1830',1830,'late-france','Июльская революция|July Revolution|Июль революциясы','Восстание в Париже свергает Карла X; власть переходит к Луи-Филиппу.|The Paris uprising overthrows Charles X; Louis-Philippe takes the throne.|Париждеги көтөрүлүш Карл Xти кулатат; такка Луи-Филипп келет.',[2.35,48.86]);
 event('belgium',1830,'early-netherlands','Независимость Бельгии|Belgian independence|Бельгиянын көз карандысыздыгы','В Брюсселе провозглашено независимое государство.|An independent state is proclaimed in Brussels.|Брюсселде көз карандысыз мамлекет жарыяланат.',[4.35,50.85]);
 event('greece',1830,'1848-greece','Признание независимости Греции|Greek independence recognised|Грециянын көз карандысыздыгы таанылат','Лондонский протокол закрепляет независимость после войны, начавшейся в 1821 году.|The London Protocol recognises independence after the war begun in 1821.|Лондон протоколу 1821-жылы башталган согуштан кийин көз карандысыздыкты тааныйт.',[22.8,37.57],'diplomacy');
 event('reform',1832,'1789-great-britain','Парламентская реформа|Parliamentary reform|Парламенттик реформа','Британский парламент меняет представительство городов и правила допуска избирателей.|Britain’s Parliament changes town representation and voter qualifications.|Британия парламенти шаарлардын өкүлчүлүгүн жана шайлоочуларга коюлган талаптарды өзгөртөт.',[-.12,51.5]);
 event('france-1848',1848,'late-france','Февральская революция|February Revolution|Февраль революциясы','После падения Июльской монархии провозглашена республика.|The fall of the July Monarchy is followed by proclamation of a republic.|Июль монархиясы кулагандан кийин республика жарыяланат.',[2.35,48.86]);
 event('frankfurt',1848,'late-hre','Франкфуртское национальное собрание|Frankfurt National Assembly|Франкфурт улуттук жыйыны','Депутаты собираются в церкви Святого Павла, чтобы обсудить устройство объединённой Германии.|Deputies meet in St Paul’s Church to debate a united Germany’s institutions.|Депутаттар Ыйык Павел чиркөөсүндө бириккен Германиянын түзүлүшүн талкуулайт.',[8.68,50.11]);
};
