'use strict';
module.exports=(c,{G,set,source,event,box})=>{
 source('Hawaii','National Park Service. Kamehameha the Great; Puʻukoholā Heiau: Stories.',['https://www.nps.gov/people/kamehameha-the-great.htm','https://www.nps.gov/puhe/learn/historyculture/stories.htm']);
 source('Australia','National Museum of Australia. Blue Mountains crossing; Founding of Bathurst.',['https://www.nma.gov.au/defining-moments/resources/blue-mountains','https://www.nma.gov.au/defining-moments/resources/founding-of-bathurst']);
 source('Rangihoua','Manatū Taonga. Māori intermediaries: Ruatara.',['https://nzhistory.govt.nz/culture/maori-european-contact-before-1840/ruatara']);
 source('Sitka','National Park Service. Old Sitka; The Battle of 1804.',['https://www.nps.gov/places/old-sitka.htm','https://www.nps.gov/sitk/learn/historyculture/battle1804.htm']);
 source('Tambora','Smithsonian Institution. Global Volcanism Program: Tambora.',['https://volcano.si.edu/volcano.cfm?vn=264040']);
 const islands=G('hawaii');
 set('hawaii',[[1790,1795,'Гавайи · соперничество правителей|Hawaiʻi · rival rulers|Гавайи · башкаруучулардын атаандаштыгы','Камехамеха расширяет власть военными походами; правители разных островов ещё сохраняют самостоятельность.|Kamehameha expands his power through warfare; rulers of different islands still retain independence.|Камехамеха аскердик жортуулдар менен бийлигин кеңейтет; ар башка аралдардын башкаруучулары өз алдынчалыгын сактайт.',null,'cultural'],[1795,1810,'Королевство Гавайи|Kingdom of Hawaiʻi|Гавайи падышалыгы','После победы при Нууану Камехамеха объединяет главные острова, кроме Кауаи и Ниихау.|After victory at Nuʻuanu, Kamehameha unites the main islands except Kauaʻi and Niʻihau.|Нууану жеңишинен кийин Камехамеха Кауаи менен Ниихаудан башка негизги аралдарды бириктирет.',islands.slice(1),'polity'],[1810,1816,'Объединённое королевство Гавайи|United Kingdom of Hawaiʻi|Бириккен Гавайи падышалыгы','Каумуалии признаёт верховную власть Камехамехи над Кауаи и Ниихау, сохраняя местное управление. Объединение завершается соглашением.|Kaumualiʻi recognises Kamehameha’s supremacy over Kauaʻi and Niʻihau while retaining local rule. An agreement completes unification.|Каумуалии жергиликтүү башкарууну сактап, Камехамеханын Кауаи менен Ниихаудагы жогорку бийлигин тааныйт. Биригүү келишим менен аяктайт.',islands,'polity']],{sources:['to1815Hawaii']});
 set('1815-kauai',[[1795,1810,'Кауаи · Каумуалии|Kauaʻi · Kaumualiʻi|Кауаи · Каумуалии','Кауаи и Ниихау сохраняют отдельного правителя до соглашения с Камехамехой в 1810 году.|Kauaʻi and Niʻihau retain a separate ruler until the agreement with Kamehameha in 1810.|Кауаи менен Ниихау 1810-жылы Камехамеха менен келишимге чейин өзүнчө башкаруучусун сактайт.',[islands[0]],'polity']],{region:'oceania',coord:[-159.5,22],sources:['to1815Hawaii']});
 set('1789-sydney',[[1790,1813,'Новый Южный Уэльс · Сидней|New South Wales · Sydney|Жаңы Түштүк Уэльс · Сидней','Каторжный труд и хозяйства вокруг Сиднея обеспечивают рост колонии. Захват земли и столкновения затрагивают местные общины.|Convict labour and farms around Sydney sustain colonial growth. Land seizure and conflict affect local communities.|Каторга эмгеги жана Сиднейдин айланасындагы чарбалар колонияны өстүрөт. Жерди ээлөө менен кагылыштар жергиликтүү жамааттарга таасир этет.'],[1813,1816,'Новый Южный Уэльс · путь за горы|New South Wales · route beyond the mountains|Жаңы Түштүк Уэльс · тоолордун ары жагына жол','В 1813 году колонисты пересекают Голубые горы. Дорога 1814–1815 годов открывает путь к Батерсту на землях вираджури.|In 1813 colonists cross the Blue Mountains. A road built in 1814–1815 opens the way to Bathurst on Wiradjuri lands.|1813-жылы колонисттер Көгүлтүр тоолордон өтөт. 1814–1815-жылдары курулган жол вираджури жериндеги Батерстке жол ачат.']],{sources:['to1815Australia']});
 set('1815-bathurst',[[1815,1816,'Батерст · британское поселение|Bathurst · British settlement|Батерст · британ конушу','Губернатор Маккуори основывает поселение на землях вираджури. Оно становится опорой дальнейшего продвижения скотоводов.|Governor Macquarie establishes a settlement on Wiradjuri lands. It becomes a base for further pastoral expansion.|Губернатор Маккуори вираджури жеринде конуш негиздейт. Ал малчылардын андан аркы жайылышына таяныч болот.',box(149.45,-33.48,149.75,-33.28),'settlement']],{region:'australia',kind:'city',coord:[149.58,-33.42],sources:['to1815Australia']});
 set('aotearoa',[[1790,1814,'Аотеароа · иви и хапу маори|Aotearoa · Māori iwi and hapū|Аотеароа · маори иви жана хапу','Местные общества управляют своими землями и торгуют с приходящими судами. Контакты приносят новые растения, изделия, оружие и конфликты.|Local societies govern their lands and trade with visiting ships. Contacts bring new crops, goods, weapons and conflicts.|Жергиликтүү коомдор жерлерин башкарып, келген кемелер менен соода кылат. Байланыштар жаңы өсүмдүктөрдү, буюмдарды, куралдарды жана чыр-чатактарды алып келет.'],[1814,1816,'Аотеароа · маори и миссия Рангихоуа|Aotearoa · Māori and Rangihoua mission|Аотеароа · маори жана Рангихоуа миссиясы','Руатара покровительствует миссии в Рангихоуа. Иви и хапу сохраняют власть над землёй; миссия существует по соглашению с местными руководителями.|Ruatara hosts the Rangihoua mission. Iwi and hapū retain authority over land; the mission operates by agreement with local leaders.|Руатара Рангихоуа миссиясына колдоо көрсөтөт. Иви менен хапу жерге бийлигин сактайт; миссия жергиликтүү жетекчилердин макулдугу менен иштейт.']],{sources:['to1815Rangihoua']});
 set('1815-rangihoua',[[1814,1816,'Рангихоуа · миссия под покровительством Руатары|Rangihoua · mission hosted by Ruatara|Рангихоуа · Руатара колдогон миссия','В декабре 1814 года прибывают миссионеры. Поселение связано с обменом знаниями, земледелием и посредничеством маори.|Missionaries arrive in December 1814. The settlement centres on exchange of knowledge, agriculture and Māori mediation.|Миссионерлер 1814-жылдын декабрында келет. Конуш билим алмашуу, дыйканчылык жана маори ортомчулугу менен байланышат.',box(174.14,-35.2,174.21,-35.15),'settlement']],{region:'oceania',kind:'city',coord:[174.17,-35.18],sources:['to1815Rangihoua']});
 set('1815-sitka',[[1799,1802,'Ситка · русский торговый пост|Sitka · Russian trading post|Ситка · орус соода жайы','Форт Святого Михаила основан на землях тлинкитов; отношения с местными жителями переходят в конфликт.|Fort St Michael is founded on Tlingit land; relations with local people develop into conflict.|Ыйык Михаил чеби тлинкит жеринде курулат; жергиликтүү эл менен мамиле кагылышка айланат.',box(-135.42,57.1,-135.32,57.17),'settlement',null,[-135.37,57.14]],[1802,1804,'Ситка · тлинкиты|Sitka · Tlingit|Ситка · тлинкиттер','Тлинкиты уничтожают русский пост и возвращают контроль над местом. У устья Индиан-Ривер строится укрепление.|The Tlingit destroy the Russian post and recover control. A fort is built at the mouth of the Indian River.|Тлинкиттер орус жайын талкалап, жерди кайра көзөмөлдөйт. Индиан-Ривердин куймасында чеп курулат.',box(-135.42,57,-135.29,57.17),'settlement'],[1804,1816,'Ново-Архангельск · Русская Америка|Novo-Arkhangelsk · Russian America|Ново-Архангельск · Орус Америкасы','После сражения 1804 года русские основывают Ново-Архангельск. Тлинкиты продолжают жить в регионе и сопротивляться расширению колонии.|After the battle of 1804 Russians establish Novo-Arkhangelsk. Tlingit communities remain in the region and resist colonial expansion.|1804-жылкы салгылашуудан кийин орустар Ново-Архангельскти негиздейт. Тлинкиттер аймакта жашап, колониянын кеңейишине каршылык көрсөтөт.',box(-135.36,57.02,-135.28,57.08),'settlement',null,[-135.33,57.05]]],{region:'arctic',kind:'city',coord:[-135.37,57.14],sources:['to1815Sitka']});
 set('antarctica',[[1790,1816,'Антарктида · необитаемый материк|Antarctica · uninhabited continent|Антарктида · эл жашабаган материк','Материк не имеет постоянного населения или государств. Плавания в Южном океане предшествуют документированным наблюдениям континента в 1820 году.|The continent has no permanent population or states. Southern Ocean voyages precede documented sightings of the continent in 1820.|Материкте туруктуу калк же мамлекеттер жок. Түштүк океандагы сүзүүлөр континенттин 1820-жылкы документтелген байкалышынан мурда жүрөт.']]);
 set('1815-tambora',[[1815,1816,'Тамбора · извержение|Tambora · eruption|Тамбора · атылуу','Извержение апреля 1815 года разрушает окрестные поселения на Сумбаве. Пепел и вулканические аэрозоли распространяются далеко за пределы острова.|The April 1815 eruption destroys nearby settlements on Sumbawa. Ash and volcanic aerosols spread far beyond the island.|1815-жылдын апрелиндеги атылуу Сумбавадагы жакынкы конуштарды талкалайт. Күл менен жанар тоо аэрозолдору аралдан алыска тарайт.',box(117.7,-8.6,118.25,-8),'landscape']],{region:'eurasia',kind:'landscape',coord:[118,-8.25],sources:['to1815Tambora']});
 for(const [id,y,entry,title,body,coord,kind] of [
 ['hawaii',1810,'hawaii','Объединение Гавайских островов|Unification of the Hawaiian Islands|Гавайи аралдарынын биригиши','Каумуалии признаёт власть Камехамехи, сохраняя управление Кауаи.|Kaumualiʻi recognises Kamehameha’s authority while retaining government of Kauaʻi.|Каумуалии Кауаини башкарууну сактап, Камехамеханын бийлигин тааныйт.',[-159.5,22],'diplomacy'],
 ['bathurst',1815,'1815-bathurst','Основание Батерста|Founding of Bathurst|Батерсттин негизделиши','Британское поселение появляется за Голубыми горами на землях вираджури.|A British settlement is established beyond the Blue Mountains on Wiradjuri lands.|Вираджури жеринде Көгүлтүр тоолордун ары жагында британ конушу түзүлөт.',[149.58,-33.42],'politics'],
 ['rangihoua',1814,'1815-rangihoua','Миссия в Рангихоуа|Mission at Rangihoua|Рангихоуадагы миссия','Руатара принимает миссионеров у своего поселения.|Ruatara hosts missionaries beside his settlement.|Руатара өз конушунун жанында миссионерлерди кабыл алат.',[174.17,-35.18],'culture'],
 ['sitka',1804,'1815-sitka','Сражение при Ситке|Battle of Sitka|Ситка салгылашуусу','Русско-алеутские силы атакуют укрепление тлинкитов; после сопротивления защитники отходят.|Russian and Aleut forces attack the Tlingit fort; after resistance the defenders withdraw.|Орус-алеут күчтөрү тлинкит чебине чабуул коёт; каршылыктан кийин коргоочулар чегинет.',[-135.31,57.04],'war'],
 ['tambora',1815,'1815-tambora','Извержение Тамборы|Eruption of Tambora|Тамборанын атылышы','Кульминация извержения приходится на 10–11 апреля 1815 года.|The eruption culminates on 10–11 April 1815.|Атылуу 1815-жылдын 10–11-апрелинде туу чокусуна жетет.',[118,-8.25],'nature']])event(id,y,entry,title,body,coord,kind);
};
