'use strict';
module.exports=(c,{T,G,set,source,event,box})=>{
 source('Napoleon','Fondation Napoléon. Cartes de l’Europe en 1812 et en 1815 après le Congrès de Vienne.',['https://www.napoleon.org/histoire-des-2-empires/cartes/carte-de-leurope-en-1812/','https://www.napoleon.org/en/histoire-des-2-empires/cartes/carte-de-leurope-en-1815-apres-le-congres-de-vienne/']);
 source('Revolution','William Doyle. The Oxford History of the French Revolution.',['https://global.oup.com/academic/product/the-oxford-history-of-the-french-revolution-9780198804932']);
 source('Vienna','Final Act of the Congress of Vienna, 9 June 1815.',['https://www.napoleon.org/en/history-of-the-two-empires/paintings/the-congress-of-vienna/']);
 const S=['to1815Napoleon','to1815Vienna'],french='#a38b81',russian='#96a6b8',austrian='#baa780';
 const put=(id,rows,meta={})=>set(id,rows,{sources:S,...meta});
 put('late-france',[
 [1790,1792,'Французская монархия|French monarchy|Француз монархиясы','Учредительное собрание преобразует управление; Конституция 1791 года ограничивает власть короля.|The Constituent Assembly reorganises government; the constitution of 1791 limits royal power.|Уюштуруучу жыйын башкарууну өзгөртөт; 1791-жылкы конституция падышанын бийлигин чектейт.'],
 [1792,1804,'Французская республика|French Republic|Француз республикасы','Монархия упразднена. Революционные войны, Террор, Директория и Консульство последовательно меняют политический строй.|The monarchy is abolished. Revolutionary wars, the Terror, the Directory and the Consulate successively reshape government.|Монархия жоюлат. Революциялык согуштар, Террор, Директория жана Консулдук саясий түзүлүштү өзгөртөт.'],
 [1804,1814,'Французская империя|French Empire|Француз империясы','Наполеон становится императором. Кодексы и администрация закрепляют реформы; войны распространяют французское господство по Европе.|Napoleon becomes emperor. Codes and administration consolidate reforms; wars extend French power across Europe.|Наполеон император болот. Кодекстер менен башкаруу реформаларды бекемдейт; согуштар Франциянын үстөмдүгүн Европага жайылтат.'],
 [1814,1816,'Франция · Бурбоны и Сто дней|France · Bourbons and Hundred Days|Франция · Бурбондор жана Жүз күн','Бурбоны возвращаются в 1814 году. В 1815 году Наполеон ненадолго восстанавливает власть, терпит поражение при Ватерлоо; монархия восстановлена.|The Bourbons return in 1814. Napoleon briefly regains power in 1815, loses at Waterloo, and the monarchy is restored.|Бурбондор 1814-жылы кайтып келет. Наполеон 1815-жылы кыска убакытка бийликти алып, Ватерлоодо жеңилет; монархия калыбына келет.']
 ],{sources:['to1815Revolution',...S]});
 put('early-netherlands',[
 [1790,1791,'Южные Нидерланды · восстание|Southern Netherlands · revolt|Түштүк Нидерланд · көтөрүлүш','Брабантская революция создаёт недолговечные Соединённые Бельгийские Штаты; австрийская власть возвращается к концу года.|The Brabant Revolution creates the short-lived United Belgian States; Austrian rule returns by the end of the year.|Брабант революциясы кыска мөөнөттүү Бириккен Бельгия штаттарын түзөт; жыл аягында Австрия бийлиги кайтып келет.'],
 [1791,1795,'Австрийские Нидерланды|Austrian Netherlands|Австриялык Нидерланд','Война с Францией сопровождается сменой военного контроля; французское завоевание 1794 года предшествует аннексии.|War with France brings changing military control; the French conquest of 1794 precedes annexation.|Франция менен согушта аскердик көзөмөл алмашат; 1794-жылкы француз басып алуусу аннексияга жол ачат.'],
 [1795,1814,'Франция · бельгийские земли|France · Belgian lands|Франция · Бельгия жерлери','Южные Нидерланды включены во французскую систему департаментов.|The southern Netherlands are incorporated into the French departmental system.|Түштүк Нидерланд Франциянын департаменттик түзүлүшүнө киргизилет.',null,'polity',french],
 [1814,1815,'Бельгийские земли · союзники|Belgian lands · Allied administration|Бельгия жерлери · союздаштар','После ухода французов территория находится под союзным управлением.|After the French withdrawal, the territory is under Allied administration.|Француздар кеткенден кийин аймак союздаштардын башкаруусунда болот.'],
 [1815,1816,'Королевство Нидерландов · юг|Kingdom of the Netherlands · south|Нидерланд падышалыгы · түштүк','Венское урегулирование объединяет северные и южные Нидерланды под властью Виллема I.|The Vienna settlement unites the northern and southern Netherlands under William I.|Венадагы жөнгө салуу түндүк жана түштүк Нидерландды Виллем Iнин бийлигине бириктирет.',null,'polity','#879d87']]);
 put('early-dutch',[
 [1790,1795,'Нидерландская республика|Dutch Republic|Нидерланд республикасы','Штатгальтер и провинциальные учреждения сохраняются до прихода французских войск и Батавской революции.|The stadtholder and provincial institutions endure until French troops arrive and the Batavian Revolution begins.|Штатгальтер жана провинциялык мекемелер француз аскерлери келип, Батавия революциясы башталганга чейин сакталат.'],
 [1795,1806,'Батавская республика|Batavian Republic|Батавия республикасы','Союзная Франции республика проводит централизацию и конституционные преобразования.|The republic allied to France centralises government and introduces constitutional reforms.|Францияга союздаш республика башкарууну борборлоштуруп, конституциялык реформаларды жүргүзөт.'],
 [1806,1810,'Королевство Голландия|Kingdom of Holland|Голландия падышалыгы','Людовик Бонапарт правит королевством, зависимым от наполеоновской системы.|Louis Bonaparte rules a kingdom within the Napoleonic system.|Луи Бонапарт Наполеондун тутумундагы падышалыкты башкарат.'],
 [1810,1814,'Франция · Голландия|France · Holland|Франция · Голландия','Наполеон аннексирует Голландию; французская власть прекращается после поражений 1813 года.|Napoleon annexes Holland; French rule ends after the defeats of 1813.|Наполеон Голландияны аннексиялайт; француз бийлиги 1813-жылкы жеңилүүлөрдөн кийин бүтөт.',null,'polity',french],
 [1814,1815,'Нидерланды · Оранский дом|Netherlands · House of Orange|Нидерланд · Оранж үйү','Оранская династия возвращается; формируется новая конституционная монархия.|The Orange dynasty returns and a new constitutional monarchy takes shape.|Оранж династиясы кайтып, жаңы конституциялык монархия түзүлөт.'],
 [1815,1816,'Королевство Нидерландов · север|Kingdom of the Netherlands · north|Нидерланд падышалыгы · түндүк','Виллем I становится королём объединённых Нидерландов.|William I becomes king of the united Netherlands.|Виллем I бириккен Нидерланддын падышасы болот.',null,'polity','#879d87']]);
 put('late-hre',[
 [1790,1806,'Священная Римская империя|Holy Roman Empire|Ыйык Рим империясы','Княжества и имперские учреждения переживают революционные войны. Секуляризация 1803 года перераспределяет церковные владения.|Principalities and imperial institutions face the Revolutionary Wars. Secularisation in 1803 redistributes ecclesiastical territories.|Княздыктар жана империялык мекемелер революциялык согуштарды баштан өткөрөт. 1803-жылкы секуляризация чиркөө ээликтерин кайра бөлүштүрөт.'],
 [1806,1813,'Рейнский союз · германские княжества|Confederation of the Rhine · German states|Рейн союзу · герман княздыктары','Священная Римская империя прекращает существование. Рейнский союз объединяет союзные Наполеону государства; Пруссия и Австрия в него не входят.|The Holy Roman Empire ends. The Confederation of the Rhine comprises states allied to Napoleon; Prussia and Austria are outside it.|Ыйык Рим империясы жоюлат. Рейн союзу Наполеонго союздаш мамлекеттерден түзүлөт; Пруссия менен Австрия ага кирбейт.',[[[7,48],[10,47.5],[13.5,48.5],[14,51],[11,52.5],[7,51.5]]],'influence'],
 [1813,1815,'Германские государства · коалиция|German states · coalition|Герман мамлекеттери · коалиция','После Лейпцига Рейнский союз распадается, германские правители переходят на сторону коалиции.|After Leipzig, the Confederation of the Rhine dissolves and German rulers join the coalition.|Лейпцигден кийин Рейн союзу тарайт, герман башкаруучулары коалицияга өтөт.',[[[7,48],[10,47.5],[13.5,48.5],[14,51],[11,52.5],[7,51.5]]],'influence'],
 [1815,1816,'Германский союз|German Confederation|Герман союзу','В Вене учреждён союз 39 государств. Это объединение суверенных монархий и свободных городов, а не единое национальное государство.|Vienna establishes a confederation of 39 states: sovereign monarchies and free cities rather than one national state.|Венада 39 мамлекеттин союзу түзүлөт: ал эгемен монархиялар менен эркин шаарларды бириктирет.',G('late-hre'),'influence']]);
 const prussia=G('1789-prussia'),warsaw=[[[17.4,51.5],[19,50.3],[22,51],[22.5,53],[20,54],[18,53.5]]],rhine=[[[6,49.5],[8,49.5],[9,51.5],[8,53],[6.2,52]]];
 put('1789-prussia',[
 [1790,1793,'Королевство Пруссия|Kingdom of Prussia|Пруссия падышалыгы','Пруссия сохраняет владения, приобретённые к концу XVIII века, и участвует в войне против революционной Франции.|Prussia retains its late eighteenth-century possessions and joins the war against revolutionary France.|Пруссия XVIII кылымдын аягындагы ээликтерин сактап, революциялык Францияга каршы согушка катышат.'],
 [1793,1795,'Пруссия · второй раздел Польши|Prussia · second partition of Poland|Пруссия · Польшанын экинчи бөлүнүшү','Пруссия аннексирует Гданьск, Торунь и Великую Польшу.|Prussia annexes Gdańsk, Toruń and Greater Poland.|Пруссия Гданьск, Торунь жана Улуу Польшаны аннексиялайт.',[...prussia,...box(16,51.5,19,54.5)]],
 [1795,1807,'Пруссия · Варшава и польские земли|Prussia · Warsaw and Polish lands|Пруссия · Варшава жана поляк жерлери','Третий раздел добавляет Варшаву и другие польские земли; поражение от Наполеона ведёт к их утрате.|The third partition adds Warsaw and other Polish lands; defeat by Napoleon leads to their loss.|Үчүнчү бөлүштүрүү Варшаваны жана башка поляк жерлерин кошот; Наполеондон жеңилүү аларды жоготууга алып келет.',[...prussia,...warsaw,...box(16,51.5,19,54.5)]],
 [1807,1815,'Пруссия после Тильзита|Prussia after Tilsit|Тильзиттен кийинки Пруссия','Тильзитский мир резко сокращает государство. Армейские и административные реформы сопровождают подготовку к новым войнам.|Tilsit sharply reduces the state. Army and administrative reforms accompany preparations for further wars.|Тильзит келишими мамлекетти кескин кичирейтет. Аскердик жана башкаруу реформалары жаңы согуштарга даярдык менен коштолот.',prussia.filter((_,i)=>i!==3)],
 [1815,1816,'Пруссия после Венского конгресса|Prussia after Vienna|Вена конгрессинен кийинки Пруссия','Пруссия получает Рейнские земли и часть Саксонии, возвращает часть польских владений.|Prussia gains Rhenish territories and part of Saxony and recovers some Polish possessions.|Пруссия Рейн жерлерин жана Саксониянын бир бөлүгүн алып, поляк ээликтеринин бир бөлүгүн кайтарат.',[...prussia,...rhine,...box(11.5,50.5,14,52),...box(16,51.5,18,53.5)]]]);
 put('early-commonwealth',[
 [1790,1793,'Речь Посполитая|Polish–Lithuanian Commonwealth|Речь Посполита','Конституция 3 мая 1791 года реформирует государство. Российское вмешательство и Тарговицкая конфедерация срывают реформы.|The constitution of 3 May 1791 reforms the state. Russian intervention and the Targowica Confederation overturn the reforms.|1791-жылдын 3-майындагы конституция мамлекетти реформалайт. Орусиянын кийлигишүүсү жана Тарговица конфедерациясы реформаларды токтотот.'],
 [1793,1795,'Речь Посполитая после второго раздела|Commonwealth after the second partition|Экинчи бөлүштүрүүдөн кийинки Речь Посполита','Восстание Костюшко 1794 года пытается сохранить независимость; третий раздел 1795 года ликвидирует государство.|Kościuszko’s uprising in 1794 attempts to preserve independence; the third partition in 1795 abolishes the state.|1794-жылкы Костюшко көтөрүлүшү көз карандысыздыкты сактоого умтулат; 1795-жылкы үчүнчү бөлүштүрүү мамлекетти жоёт.',[[[19,50],[21.8,50.7],[24,52],[24.5,55],[23,55.6],[21,53]]]]]);
 put('1815-warsaw',[
 [1807,1809,'Герцогство Варшавское|Duchy of Warsaw|Варшава герцогдугу','Тильзитский мир создаёт герцогство под властью саксонского короля и при французском покровительстве.|Tilsit creates a duchy under the Saxon king and French protection.|Тильзит келишими саксон падышасы башкарган, Франция колдогон герцогдукту түзөт.',warsaw],
 [1809,1813,'Расширенное герцогство Варшавское|Expanded Duchy of Warsaw|Кеңейген Варшава герцогдугу','После войны с Австрией герцогство получает Краков и западногалицийские земли.|After war with Austria the duchy gains Kraków and western Galician lands.|Австрия менен согуштан кийин герцогдук Краковду жана батыш Галиция жерлерин алат.',[...warsaw,...box(19,49.8,22.5,51.5)]],
 [1813,1815,'Варшава · российская оккупация|Warsaw · Russian occupation|Варшава · Орусиянын оккупациясы','Российские войска занимают герцогство; его дальнейшая судьба решается на Венском конгрессе.|Russian troops occupy the duchy; its future is settled at Vienna.|Орус аскерлери герцогдукту ээлейт; анын кийинки тагдыры Вена конгрессинде чечилет.',[...warsaw,...box(19,49.8,22.5,51.5)],'polity',russian],
 [1815,1816,'Царство Польское · Российская империя|Kingdom of Poland · Russian Empire|Польша падышалыгы · Орусия империясы','Большая часть герцогства становится конституционным царством в личной унии с российским императором.|Most of the duchy becomes a constitutional kingdom in personal union with the Russian emperor.|Герцогдуктун көп бөлүгү орус императору менен жеке униядагы конституциялык падышалык болот.',[[[18,51],[20,50],[23,50.8],[23.7,53],[22.8,54.2],[20,53.5]]],'polity',russian]
 ],{region:'eurasia',coord:[21.01,52.23],color:'#9b9580'});
 const southFinland=G('early-sweden')[1];
 put('early-sweden',[[1790,1809,'Королевство Швеция|Kingdom of Sweden|Швеция падышалыгы','Швеция сохраняет Финляндию до поражения в войне с Россией 1808–1809 годов.|Sweden retains Finland until its defeat in the war with Russia of 1808–1809.|Швеция Финляндияны 1808–1809-жылдары Орусиядан жеңилгенге чейин сактайт.'],[1809,1816,'Швеция|Sweden|Швеция','Финляндия переходит России. В 1814 году возникает шведско-норвежская уния; Норвегия сохраняет собственную конституцию.|Finland passes to Russia. A Swedish–Norwegian union forms in 1814; Norway retains its own constitution.|Финляндия Орусияга өтөт. 1814-жылы Швеция–Норвегия униясы түзүлөт; Норвегия өз конституциясын сактайт.',G('early-sweden').filter((_,i)=>i!==1)]]);
 put('1815-finland',[[1809,1816,'Великое княжество Финляндское|Grand Duchy of Finland|Финляндия улуу княздыгы','Финляндия становится автономным великим княжеством в Российской империи, сохраняя отдельные законы и учреждения.|Finland becomes an autonomous grand duchy in the Russian Empire, retaining distinct laws and institutions.|Финляндия өз мыйзамдарын жана мекемелерин сактаган Орусия империясындагы автономиялуу улуу княздык болот.',[southFinland],'polity',russian]],{region:'eurasia',coord:[24.95,60.17]});
 put('early-denmark-norway',[[1790,1814,'Дания и Норвегия|Denmark and Norway|Дания жана Норвегия','Датская корона правит двумя королевствами. Наполеоновские войны и британская блокада тяжело влияют на торговлю.|The Danish crown rules both kingdoms. The Napoleonic Wars and British blockade severely affect trade.|Дания таажысы эки падышалыкты башкарат. Наполеон согуштары жана британ блокадасы соодага катуу таасир этет.'],[1814,1816,'Дания|Denmark|Дания','Кильский мир отделяет Норвегию. Исландия, Гренландия и Фарерские острова остаются под датской короной.|The Treaty of Kiel separates Norway. Iceland, Greenland and the Faroes remain under the Danish crown.|Киль келишими Норвегияны бөлөт. Исландия, Гренландия жана Фарер аралдары Дания таажысында калат.',G('early-denmark-norway').slice(0,2)]]);
 put('1815-norway',[[1814,1816,'Норвегия · уния со Швецией|Norway · union with Sweden|Норвегия · Швеция менен уния','После принятия конституции в Эйдсволле и короткой войны Норвегия вступает в личную унию со Швецией.|After adopting the Eidsvoll constitution and a short war, Norway enters a personal union with Sweden.|Эйдсволл конституциясы кабыл алынып, кыска согуштан кийин Норвегия Швеция менен жеке унияга кирет.',[G('early-denmark-norway')[2]]]],{region:'eurasia',coord:[10.75,59.91]});
 put('1789-great-britain',[[1790,1801,'Великобритания|Great Britain|Улуу Британия','Парламентская монархия ведёт войны с Францией; фабрики и угольные районы растут вместе с морской торговлей.|The parliamentary monarchy fights France; factories and coalfields grow alongside maritime trade.|Парламенттик монархия Франция менен согушат; фабрикалар, көмүр аймактары жана деңиз соодасы өсөт.'],[1801,1816,'Соединённое Королевство|United Kingdom|Бириккен Падышалык','Уния Великобритании и Ирландии создаёт Соединённое Королевство. Закон 1807 года запрещает британскую работорговлю, но ещё не отменяет рабство.|The union of Great Britain and Ireland creates the United Kingdom. The 1807 act prohibits the British slave trade but does not yet abolish slavery.|Улуу Британия менен Ирландиянын униясы Бириккен Падышалыкты түзөт. 1807-жылкы мыйзам британ кул соодасына тыюу салат, бирок кулчулукту жойбойт.',[...G('1789-great-britain'),...box(-10.5,51.5,-6,55.3)]]]);
 put('1789-spain',[[1790,1808,'Испанская монархия|Spanish monarchy|Испан монархиясы','Бурбонская монархия переживает войны и кризис финансов; морское поражение при Трафальгаре ослабляет флот.|The Bourbon monarchy faces wars and financial crisis; defeat at Trafalgar weakens the fleet.|Бурбон монархиясы согуштарды жана каржы кризисин баштан өткөрөт; Трафальгардагы жеңилүү флотту алсыратат.'],[1808,1814,'Испания · война за независимость|Spain · Peninsular War|Испания · көз карандысыздык согушу','Жозеф Бонапарт, местные хунты и союзные армии борются за власть. Кадисские кортесы принимают Конституцию 1812 года.|Joseph Bonaparte, local juntas and Allied armies contest power. The Cádiz Cortes adopts the constitution of 1812.|Жозеф Бонапарт, жергиликтүү хунталар жана союздаш аскерлер бийлик үчүн күрөшөт. Кадис кортестери 1812-жылкы конституцияны кабыл алат.',null,'influence'],[1814,1816,'Испания · Фердинанд VII|Spain · Ferdinand VII|Испания · Фердинанд VII','Фердинанд VII возвращается и отменяет конституцию; войны в американских владениях продолжаются.|Ferdinand VII returns and abolishes the constitution; wars continue in the American possessions.|Фердинанд VII кайтып келип конституцияны жоёт; Америкадагы ээликтерде согуштар уланат.']]);
 put('late-portugal',[[1790,1807,'Португалия|Portugal|Португалия','Монархия Браганса опирается на атлантическую торговлю и союз с Британией.|The Braganza monarchy relies on Atlantic trade and its British alliance.|Браганса монархиясы Атлантика соодасына жана Британия менен союзга таянат.'],[1807,1811,'Португалия · французские вторжения|Portugal · French invasions|Португалия · француз баскынчылыгы','Двор переезжает в Бразилию. Французские вторжения встречают сопротивление португальско-британских войск.|The court moves to Brazil. French invasions meet resistance from Portuguese and British forces.|Сарай Бразилияга көчөт. Француз баскынчылыгына португал жана британ аскерлери каршы турат.',null,'influence'],[1811,1816,'Португалия · регентство|Portugal · regency|Португалия · регенттик','После изгнания французов действует регентство; королевский двор остаётся в Рио-де-Жанейро.|After the French expulsion a regency governs; the royal court remains in Rio de Janeiro.|Француздар чыгарылгандан кийин регенттик башкарат; падыша сарайы Рио-де-Жанейродо калат.']]);
 // Italian states: ownership changes in their existing regional cores.
 for(const [id,until,between,after] of [['early-venice',1797,'Австрия · Венеция|Austria · Venice|Австрия · Венеция','Австрия · Ломбардия-Венеция|Austria · Lombardy-Venetia|Австрия · Ломбардия-Венеция'],['early-milan',1796,'Цизальпийская республика|Cisalpine Republic|Цизальпия республикасы','Австрия · Ломбардия-Венеция|Austria · Lombardy-Venetia|Австрия · Ломбардия-Венеция']]){
  const old=c.entries.find(e=>e.id===id).name;
  put(id,[[1790,until,old,'Сохраняются прежние органы власти до французского похода в Италию.|Existing institutions remain until the French campaign in Italy.|Франциянын Италияга жортуулуна чейин мурдагы бийлик мекемелери сакталат.'],[until,1805,between,'Итальянские войны меняют правителей и устройство областей северной Италии.|The Italian wars change rulers and government in northern Italy.|Италия согуштары түндүктөгү аймактардын башкаруучуларын жана түзүлүшүн өзгөртөт.',null,'polity',id==='early-venice'?austrian:french],[1805,1814,'Наполеоновское королевство Италия|Napoleonic Kingdom of Italy|Наполеондун Италия падышалыгы','Североитальянские области включены в королевство под властью Наполеона; местное управление перестраивается.|Northern Italian regions enter Napoleon’s kingdom and local administration is reorganised.|Түндүк Италия аймактары Наполеондун падышалыгына кирип, жергиликтүү башкаруу өзгөрөт.',null,'polity',french],[1814,1816,after,'Австрийское управление возвращается; в 1815 году оформляется Ломбардо-Венецианское королевство.|Austrian administration returns; the Kingdom of Lombardy-Venetia is established in 1815.|Австрия башкаруусу кайтып, 1815-жылы Ломбардия-Венеция падышалыгы түзүлөт.',null,'polity',austrian]]);
 }
 put('early-papal',[[1790,1798,'Папская область|Papal States|Папа мамлекети','Папская власть сохраняется до французского занятия Рима.|Papal government continues until the French occupation of Rome.|Римди француздар ээлегенге чейин папанын бийлиги сакталат.'],[1798,1800,'Римская республика|Roman Republic|Рим республикасы','При французской поддержке провозглашена республика; папа удалён из Рима.|A republic is proclaimed with French support and the pope is removed from Rome.|Франциянын колдоосу менен республика жарыяланып, папа Римден чыгарылат.',null,'polity',french],[1800,1809,'Восстановленная Папская область|Restored Papal States|Калыбына келген Папа мамлекети','Пий VII восстанавливает папское управление, затем сталкивается с наполеоновской аннексией.|Pius VII restores papal government before facing Napoleonic annexation.|Пий VII папалык башкарууну калыбына келтирет, андан соң Наполеондун аннексиясына туш болот.'],[1809,1814,'Франция · Рим|France · Rome|Франция · Рим','Рим и папские земли аннексированы Французской империей.|Rome and papal lands are annexed by the French Empire.|Рим жана папа жерлери Француз империясына кошулат.',null,'polity',french],[1814,1816,'Папская область|Papal States|Папа мамлекети','После падения Наполеона папское государство восстанавливается.|The papal state is restored after Napoleon’s fall.|Наполеон кулагандан кийин папа мамлекети калыбына келет.']]);
 put('early-florence',[[1790,1801,'Великое герцогство Тосканское|Grand Duchy of Tuscany|Тоскана улуу герцогдугу','Габсбург-Лотарингская династия правит Тосканой; революционные войны нарушают прежний порядок.|The Habsburg-Lorraine dynasty rules Tuscany; Revolutionary Wars disrupt the old order.|Габсбург-Лотарингия династиясы Тоскананы башкарат; революциялык согуштар мурдагы тартипти бузат.'],[1801,1808,'Королевство Этрурия|Kingdom of Etruria|Этрурия падышалыгы','Тосканское ядро переходит Бурбонам в наполеоновской системе зависимых государств.|The Tuscan core passes to the Bourbons within the Napoleonic system of dependent states.|Тоскана өзөгү Наполеондун көз каранды мамлекеттер тутумунда Бурбондорго өтөт.'],[1808,1814,'Франция · Тоскана|France · Tuscany|Франция · Тоскана','Тоскана включена во Французскую империю и её систему департаментов.|Tuscany is incorporated into the French Empire and its departmental system.|Тоскана Француз империясына жана анын департаменттик түзүлүшүнө кирет.',null,'polity',french],[1814,1816,'Восстановленное герцогство Тоскана|Restored Grand Duchy of Tuscany|Калыбына келген Тоскана герцогдугу','Фердинанд III возвращается; Венское урегулирование подтверждает восстановление династии.|Ferdinand III returns and the Vienna settlement confirms dynastic restoration.|Фердинанд III кайтып, Венадагы жөнгө салуу династиянын калыбына келишин бекитет.']]);
 put('early-naples',[[1790,1806,'Неаполитанское королевство|Kingdom of Naples|Неаполь падышалыгы','Бурбоны удерживают королевство; краткая Партенопейская республика 1799 года подавлена.|The Bourbons retain the kingdom; the short-lived Parthenopean Republic of 1799 is suppressed.|Бурбондор падышалыкты сактайт; 1799-жылкы кыска Партенопея республикасы басылат.'],[1806,1815,'Неаполь · Бонапарт и Мюрат|Naples · Bonaparte and Murat|Неаполь · Бонапарт жана Мюрат','На материке правят Жозеф Бонапарт, затем Иоахим Мюрат. Бурбоны сохраняют Сицилию.|Joseph Bonaparte and then Joachim Murat rule the mainland; the Bourbons retain Sicily.|Материкти Жозеф Бонапарт, андан кийин Иоахим Мюрат башкарат; Бурбондор Сицилияны сактайт.',G('early-naples').filter(r=>Math.max(...r.map(p=>p[1]))>38.5),'polity',french],[1815,1816,'Неаполь · возвращение Бурбонов|Naples · Bourbon restoration|Неаполь · Бурбондордун кайтышы','Мюрат терпит поражение, и Бурбоны возвращают материковое королевство.|Murat is defeated and the Bourbons recover the mainland kingdom.|Мюрат жеңилип, Бурбондор материктеги падышалыкты кайтарат.']]);
 for(const [id,year,title,entry,coord,body,kind] of [
 ['republic',1792,'Провозглашение Французской республики|French Republic proclaimed|Француз республикасынын жарыяланышы','late-france',[2.35,48.86],'Конвент упраздняет монархию 21 сентября.|The Convention abolishes the monarchy on 21 September.|Конвент 21-сентябрда монархияны жоёт.','politics'],
 ['austerlitz',1805,'Битва при Аустерлице|Battle of Austerlitz|Аустерлиц салгылашуусу','late-france',[16.77,49.14],'Наполеон побеждает русско-австрийскую армию 2 декабря.|Napoleon defeats the Russian-Austrian army on 2 December.|Наполеон 2-декабрда орус-австрия аскерлерин жеңет.','war'],
 ['borodino',1812,'Бородинское сражение|Battle of Borodino|Бородино салгылашуусу','1789-russian-empire',[35.82,55.53],'Крупное сражение французской и российской армий предшествует занятию Москвы и отступлению Наполеона.|A major battle between French and Russian armies precedes the occupation of Moscow and Napoleon’s retreat.|Француз жана орус аскерлеринин чоң салгылашуусунан кийин Москва ээленип, Наполеон артка чегинет.','war'],
 ['leipzig',1813,'Битва при Лейпциге|Battle of Leipzig|Лейпциг салгылашуусу','late-hre',[12.37,51.34],'Коалиция побеждает Наполеона; французская власть в германских землях рушится.|The coalition defeats Napoleon and French power in the German lands collapses.|Коалиция Наполеонду жеңет; герман жерлериндеги француз бийлиги кулайт.','war'],
 ['vienna',1815,'Венский конгресс|Congress of Vienna|Вена конгресси','early-austria',[16.37,48.21],'Заключительный акт 9 июня закрепляет новое европейское урегулирование.|The Final Act of 9 June establishes the new European settlement.|9-июндагы корутунду акт Европадагы жаңы тартипти бекитет.','diplomacy'],
 ['waterloo',1815,'Битва при Ватерлоо|Battle of Waterloo|Ватерлоо салгылашуусу','late-france',[4.41,50.68],'18 июня армии Веллингтона и Блюхера наносят Наполеону окончательное поражение.|On 18 June Wellington’s and Blücher’s armies inflict Napoleon’s final defeat.|18-июнда Веллингтон менен Блюхердин аскерлери Наполеонду акыркы жолу жеңет.','war']])event(id,year,entry,title,body,coord,kind,{sources:S});
};
