'use strict';
module.exports=(c,{G,set,source,event,box})=>{
 source('Waitangi','Manatū Taonga. Treaty events 1800–49; Department of Conservation. Te Maiki / Flagstaff Hill.',['https://nzhistory.govt.nz/page/treaty-events-1800-49','https://www.doc.govt.nz/parks-and-recreation/places-to-go/northland/places/russell-area/heritage-sites/te-maiki-flagstaff-hill/']);
 source('AustralianColonies','National Museum of Australia. Founding of Perth; Colonial Australia; State Records of South Australia. Immigration passenger lists.',['https://www.nma.gov.au/defining-moments/resources/founding-of-perth','https://digital-classroom.nma.gov.au/learning-modules/colonial-australia-defining-moments-1788-1900/1-quiz','https://www.archives.sa.gov.au/finding-information/discover-our-collection/migration-and-crew/immigration-passenger-lists']);
 source('Tasmania','University of Tasmania. The Companion to Tasmanian History: Frontier Conflict.',['https://www.utas.edu.au/library/companion_to_tasmanian_history/F/Frontier%20Conflict.htm']);
 source('Hawaii','National Park Service. Keonehelelei: Hawaiian land tenure and the Māhele.',['https://www.nps.gov/havo/learn/historyculture/upload/20060908_Keonehelelei_508.pdf']);
 source('Antarctic','Royal Museums Greenwich. History of Antarctic explorers; HMS Terror and Erebus.',['https://www.rmg.co.uk/stories/maritime-history/history-antarctic-explorers','https://www.rmg.co.uk/stories/maritime-history/hms-terror-erebus-history-franklin-lost-expedition']);
 source('Franklin','Parks Canada. Inuit traditional knowledge: Wrecks of HMS Erebus and HMS Terror.',['https://www.parcs.canada.ca/lhn-nhs/nu/epaveswrecks/culture/inuit/qaujimajatuqangit']);
 source('Iceland','Þingvellir National Park. Independence Campaign; Alþingi. Alþingistíðindi 1845–1873.',['https://www.thingvellir.is/en/education/history/independence-campaign/','https://www.althingi.is/thingstorf/leidbeiningar-og-yfirlit/althingistidindi/1845-1873/']);
 const put=(id,rows,src,meta={})=>set(id,rows,{sources:src.map(s=>'to1848'+s),...meta});
 put('aotearoa',[[1816,1835,'Аотеароа · общества маори|Aotearoa · Māori societies|Аотеароа · маори коомдору','Иви и хапу управляют своими землями. Торговля, новые культуры растений и огнестрельное оружие меняют хозяйство и войны.|Iwi and hapū govern their lands. Trade, new crops and firearms transform livelihoods and warfare.|Иви менен хапу өз жерлерин башкарат. Соода, жаңы өсүмдүктөр жана ок атуучу куралдар чарба менен согушту өзгөртөт.'],[1835,1840,'Аотеароа · декларация независимости|Aotearoa · declaration of independence|Аотеароа · көз карандысыздык декларациясы','Северные вожди подписывают Хе Вакапутанга, утверждая свою власть. Соглашение не объединяет все маорийские общества в единое государство.|Northern chiefs sign He Whakaputanga, asserting their authority. The declaration does not unite all Māori societies into one state.|Түндүк башчылар Хе Вакапутанганы кабыл алып, өз бийлигин ырастайт. Декларация бардык маори коомун бир мамлекетке бириктирбейт.'],[1840,1849,'Аотеароа · маори и британская колония|Aotearoa · Māori and the British colony|Аотеароа · маори жана британ колониясы','Договор Вайтанги подписан многими вождями; тексты по-разному выражают передачу власти. Британские притязания сосуществуют с широким фактическим управлением маори.|Many chiefs sign the Treaty of Waitangi; its texts express the transfer of authority differently. British claims coexist with extensive effective Māori government.|Вайтанги келишимине көп башчылар кол коёт; тексттер бийликтин өткөрүлүшүн ар башка берет. Британиянын доолору маорилердин кеңири иш жүзүндөгү башкаруусу менен катар жашайт.',null,'cultural']],['Waitangi']);
 put('1848-auckland',[[1840,1849,'Окленд · британский колониальный центр|Auckland · British colonial centre|Окленд · британ колониялык борбору','Поселение на землях Нгати Фатуа становится столицей колонии. Земельные сделки и иммиграция меняют местное общество.|The settlement on Ngāti Whātua land becomes the colonial capital. Land transactions and immigration transform local society.|Нгати Фатуа жериндеги конуш колониянын борборуна айланат. Жер келишимдери жана иммиграция жергиликтүү коомду өзгөртөт.',box(174.6,-36.97,174.9,-36.72),'settlement']],['Waitangi'],{region:'oceania',kind:'city',coord:[174.76,-36.85],color:'#859dae'});
 put('hawaii',[[1816,1840,'Королевство Гавайи|Kingdom of Hawaiʻi|Гавайи падышалыгы','Монархия сохраняет единство островов. Контакты с миссионерами, купцами и моряками меняют религиозную и хозяйственную жизнь.|The monarchy maintains island unity. Contacts with missionaries, traders and sailors change religious and economic life.|Монархия аралдардын биримдигин сактайт. Миссионерлер, соодагерлер жана деңизчилер менен байланыш динди жана чарбаны өзгөртөт.'],[1840,1848,'Гавайи · конституционная монархия|Hawaiʻi · constitutional monarchy|Гавайи · конституциялык монархия','Камехамеха III вводит письменную конституцию. Монархия, вожди и представительные учреждения участвуют в управлении.|Kamehameha III introduces a written constitution. The monarchy, chiefs and representative institutions share government.|Камехамеха III жазуу жүзүндөгү конституция киргизет. Монархия, башчылар жана өкүлчүлүктүү мекемелер башкарууга катышат.'],[1848,1849,'Гавайи · земельный раздел Махеле|Hawaiʻi · Māhele land division|Гавайи · Махеле жер бөлүштүрүүсү','Махеле разделяет земельные права короля и вождей. Последующие законы меняют доступ простых жителей к оформлению владений.|The Māhele divides the king’s and chiefs’ land interests. Subsequent laws alter ordinary residents’ access to formal title.|Махеле падыша менен башчылардын жер укуктарын бөлүштүрөт. Кийинки мыйзамдар карапайым элдин жерин расмий каттоо мүмкүнчүлүгүн өзгөртөт.']],['Hawaii']);
 for(const [id,y,name,coord,shape] of [
 ['perth',1829,'Перт · колония Суон-Ривер|Perth · Swan River Colony|Перт · Суон-Ривер колониясы',[115.86,-31.95],box(115.7,-32.2,116.2,-31.8)],
 ['melbourne',1835,'Мельбурн · Порт-Филлип|Melbourne · Port Phillip|Мельбурн · Порт-Филлип',[144.96,-37.81],box(144.7,-38,145.2,-37.6)],
 ['adelaide',1836,'Аделаида · Южная Австралия|Adelaide · South Australia|Аделаида · Түштүк Австралия',[138.6,-34.93],box(138.45,-35.2,138.85,-34.65)]])put('1848-'+id,[[y,1849,name,'Новое британское поселение расширяется на землях коренных народов. Показан местный колониальный центр, а не всё заявленное колонией пространство.|A new British settlement expands on Indigenous land. The outline marks the local colonial centre, not the colony’s full territorial claim.|Жаңы британ конушу түпкү элдердин жеринде кеңейет. Контур колониянын бүт доосун эмес, жергиликтүү борборун көрсөтөт.',shape,'settlement']],['AustralianColonies'],{region:'australia',kind:'city',coord,color:'#859dae'});
 put('1789-tasmania',[[1816,1832,'Тасмания · колонизация и сопротивление|Tasmania · colonisation and resistance|Тасмания · колониялаштыруу жана каршылык','Захват земель сопровождается вооружённым сопротивлением и насилием колонистов. Кампания «Чёрная линия» 1830 года направлена против коренных жителей.|Land seizure brings armed resistance and settler violence. The 1830 Black Line campaign targets Indigenous inhabitants.|Жер басып алуу куралдуу каршылык жана колонисттердин зомбулугу менен коштолот. 1830-жылкы Кара сызык өнөктүгү түпкү элге багытталган.'],[1832,1847,'Тасманийские аборигены · насильственное перемещение|Aboriginal Tasmanians · forced displacement|Тасманиянын түпкү эли · мажбурлап көчүрүү','Многих выживших перемещают на остров Флиндерс, где болезни и условия заключения приводят к новым смертям. Другие семьи остаются в регионе.|Many survivors are removed to Flinders Island, where disease and confinement cause further deaths. Other families remain in the region.|Тирүү калгандардын көбү Флиндерс аралына көчүрүлүп, оорудан жана камак шартынан дагы өлүмгө учурайт. Башка үй-бүлөлөр аймакта калат.',[...G('1789-tasmania'),...box(147.7,-40.2,148.3,-39.8)],'cultural'],[1847,1849,'Тасманийские аборигены · Ойстер-Ков и острова|Aboriginal Tasmanians · Oyster Cove and islands|Тасманиянын түпкү эли · Ойстер-Ков жана аралдар','Оставшихся обитателей Уайбаленны переводят в Ойстер-Ков. Тасманийские аборигенные семьи и их потомки продолжают свою историю.|The remaining Wybalenna residents are moved to Oyster Cove. Aboriginal Tasmanian families and descendants continue their history.|Уайбаленнанын калган жашоочулары Ойстер-Ковго көчүрүлөт. Тасманиянын түпкү үй-бүлөлөрү жана урпактары тарыхын улантат.',[...box(147.1,-43.25,147.5,-43),...box(147.7,-40.2,148.3,-39.8)],'cultural',null,[147.24,-43.11]]],['Tasmania']);
 put('antarctica',[[1816,1820,'Антарктида · необитаемый материк|Antarctica · uninhabited continent|Антарктида · адам жашабаган материк','Постоянных человеческих поселений нет. Морские экспедиции исследуют южные океаны.|There are no permanent human settlements. Maritime expeditions explore southern oceans.|Адамдардын туруктуу конуштары жок. Деңиз экспедициялары түштүк океандарды изилдейт.'],[1820,1849,'Антарктида · наблюдения и морские экспедиции|Antarctica · sightings and maritime expeditions|Антарктида · байкоолор жана деңиз экспедициялары','Экспедиции Беллинсгаузена и Брансфилда наблюдают антарктические берега в 1820 году. Последующие плавания уточняют карту; постоянных поселений нет.|Bellingshausen’s and Bransfield’s expeditions observe Antarctic coasts in 1820. Later voyages improve mapping; there are no permanent settlements.|Беллинсгаузен менен Брансфилддин экспедициялары 1820-жылы Антарктида жээктерин көрөт. Кийинки саякаттар картаны тактайт; туруктуу конуштар жок.']],['Antarctic']);
 put('1848-ross-sea',[[1841,1844,'Море Росса · исследовательские плавания|Ross Sea · exploratory voyages|Росс деңизи · изилдөө сапарлары','Экспедиция Джеймса Кларка Росса исследует море, ледяной барьер и берега Земли Виктории. Это область наблюдений, без постоянного поселения.|James Clark Ross’s expedition explores the sea, ice barrier and Victoria Land coast. This is an area of observation without permanent settlement.|Жеймс Кларк Росстун экспедициясы деңизди, муз тосмосун жана Виктория жеринин жээгин изилдейт. Бул туруктуу конушсуз байкоо аймагы.',box(165,-78,179,-71),'landscape']],['Antarctic'],{region:'antarctica',kind:'landscape',coord:[172,-75],color:'#9daeb0'});
 put('iceland',[[1816,1845,'Исландия · датская монархия|Iceland · Danish monarchy|Исландия · Дания монархиясы','Датские учреждения управляют островом; движение за исландское представительство усиливается.|Danish institutions govern the island while a movement for Icelandic representation grows.|Аралды Даниянын мекемелери башкарат; исланд өкүлчүлүгү үчүн кыймыл күчөйт.'],[1845,1849,'Исландия · восстановленный альтинг|Iceland · restored Alþingi|Исландия · калыбына келген альтинг','Альтинг вновь собирается в Рейкьявике как совещательный орган при датском короле.|The Alþingi meets again in Reykjavík as an advisory body to the Danish king.|Альтинг Рейкьявикте Дания падышасына кеңеш берүүчү орган катары кайра чогулат.']],['Iceland']);
 put('1848-franklin',[[1846,1849,'Остров Кинг-Уильям · экспедиция Франклина|King William Island · Franklin expedition|Кинг-Уильям аралы · Франклин экспедициясы','Корабли зажаты льдом с 1846 года; в апреле 1848 года экипажи покидают их. Инуитские свидетельства впоследствии помогают установить судьбу экспедиции.|The ships are trapped in ice from 1846; crews abandon them in April 1848. Inuit testimony later helps establish the expedition’s fate.|Кемелер 1846-жылдан музга камалат; экипаждар 1848-жылдын апрелинде аларды таштайт. Инуиттердин күбөлүктөрү кийин экспедициянын тагдырын аныктоого жардам берет.',box(-100,68.5,-97,70),'landscape']],['Franklin'],{region:'arctic',kind:'landscape',coord:[-98.5,69.3],color:'#a7b4b3'});
 event('perth',1829,'1848-perth','Основание Перта|Founding of Perth|Перттин негизделиши','Колониальное поселение создаётся на землях ваджук-нунгар.|A colonial settlement is established on Whadjuk Noongar country.|Важук-нунгар жеринде колониялык конуш түзүлөт.',[115.86,-31.95],'migration');
 event('waitangi',1840,'aotearoa','Договор Вайтанги|Treaty of Waitangi|Вайтанги келишими','Подписание начинается в Вайтанги 6 февраля; затем копии договора передаются в другие районы.|Signing begins at Waitangi on 6 February; copies then circulate to other regions.|Кол коюу 6-февралда Вайтангиде башталып, кийин көчүрмөлөр башка аймактарга жөнөтүлөт.',[174.08,-35.27],'diplomacy');
 event('hawaii',1840,'hawaii','Конституция Гавайского королевства|Constitution of the Hawaiian Kingdom|Гавайи падышалыгынын конституциясы','Письменная конституция закрепляет устройство королевства.|A written constitution establishes the kingdom’s institutions.|Жазуу жүзүндөгү конституция падышалыктын түзүлүшүн бекитет.',[-156.68,20.88]);
 event('antarctica',1820,'antarctica','Наблюдения антарктических берегов|Sightings of Antarctic coasts|Антарктида жээктеринин көрүлүшү','Русская и британская экспедиции наблюдают антарктические берега. Отмечен район наблюдения Брансфилда у Антарктического полуострова.|Russian and British expeditions sight Antarctic coasts. The marked location is Bransfield’s observation area near the Antarctic Peninsula.|Орус жана британ экспедициялары Антарктида жээктерин көрөт. Белги Антарктида жарым аралындагы Брансфилддин байкоо аймагын көрсөтөт.',[-60.8,-63.3],'culture',{approx:true});
 event('iceland',1845,'iceland','Альтинг вновь собирается|Alþingi reconvenes|Альтинг кайра чогулат','В Рейкьявике начинает работу восстановленное собрание.|The restored assembly begins work in Reykjavík.|Рейкьявикте калыбына келген жыйын иштей баштайт.',[-21.94,64.15]);
 event('franklin',1848,'1848-franklin','Экипажи покидают «Эребус» и «Террор»|Crews abandon Erebus and Terror|Экипаждар «Эребус» менен «Террорду» таштайт','Сохранившаяся записка сообщает об уходе экипажей с зажатых льдом кораблей.|A surviving note records the crews’ departure from the icebound ships.|Сакталган жазуу экипаждардын музга камалган кемелерден кеткенин билдирет.',[-98.5,69.3],'culture');
};
