'use strict';
module.exports=(c,{G,set,source,event,link,geo})=>{
 source('Africa','National Army Museum. Soldiers of the 4th King’s African Rifles in Abyssinia, 1941; United States Holocaust Memorial Museum. Allied Military Operations in North Africa.',['https://collection.nam.ac.uk/detail.php?acc=1996-08-388-25','https://encyclopedia.ushmm.org/content/en/article/allied-military-operations-in-north-africa']);
 source('Atlantic','Office of the Historian. Lend-Lease and Military Aid to the Allies; United States Relations with Iceland; Foreign Relations of the United States, 1941, Greenland.',['https://history.state.gov/milestones/1937-1945/lend-lease','https://history.state.gov/countries/iceland','https://history.state.gov/historicaldocuments/frus1941v02']);
 source('Americas','Foreign Relations of the United States, 1942, The American Republics; 1945, The American Republics; National WWII Museum. Brazil in World War II.',['https://history.state.gov/historicaldocuments/frus1942v05','https://history.state.gov/historicaldocuments/frus1945v09','https://www.nationalww2museum.org/war/articles/brazil-world-war-ii']);
 source('Oceania','Australian War Memorial. Second World War, 1939–45; New Zealand History. The War in the Pacific.',['https://www.awm.gov.au/articles/second-world-war','https://nzhistory.govt.nz/war/war-in-the-pacific']);
 source('Antarctica','British Antarctic Survey. Operation Tabarin: first bases; First Report on the Work of Operation Tabarin, 1944.',['https://www.bas.ac.uk/about/history/operation-tabarin/','https://www.bas.ac.uk/wp-content/uploads/2019/01/ad6_1a_1944_a.pdf']);
 source('UN','Charter of the United Nations, 1945; United Nations. History of the United Nations.',['https://www.un.org/en/about-us/un-charter','https://www.un.org/en/about-us/history-of-the-un']);
 const P=(id,rows,src)=>set(id,rows,{sources:[src]});
 const liberation='В 1941 году союзные войска и эфиопское сопротивление прекращают итальянскую оккупацию; Хайле Селассие возвращается на престол.|In 1941 Allied forces and Ethiopian resistance end Italian occupation; Haile Selassie returns to the throne.|1941-жылы союздаштар жана эфиопиялык каршылык италиялык оккупацияны токтотуп, Хайле Селассие такка кайтат.';
 for(const id of ['ethiopia','lalibela','early-oromo','early-awsa','1789-harar']){const n=c.entries.find(e=>e.id===id).phases.at(-1).name;P(id,[[1940,1941,n,'Итальянская оккупация.|Italian occupation.|Италиялык оккупация.'],[1941,1946,n.map((s,i)=>id==='ethiopia'?['Эфиопская империя','Ethiopian Empire','Эфиопия империясы'][i]:s),liberation]],'Africa');link('1914-italy',id,1940,1941,'occupation',false);if(id!=='ethiopia')link('ethiopia',id,1941,1946,'province',false);}
 P('1914-eritrea',[[1940,1941,'Эритрея · итальянская колония|Eritrea · Italian colony|Эритрея · Италия колониясы','Италия использует колонию как базу в Восточной Африке.|Italy uses the colony as an East African base.|Италия колонияны Чыгыш Африкадагы база катары колдонот.'],[1941,1946,'Эритрея · британская военная администрация|Eritrea · British military administration|Эритрея · британ аскердик администрациясы','После разгрома итальянских войск установлена британская военная администрация.|British military administration follows the defeat of Italian forces.|Италиялык күчтөр жеңилгенден кийин британ аскердик администрациясы орнойт.']],'Africa');link('1914-italy','1914-eritrea',1940,1941);link('1789-great-britain','1914-eritrea',1941,1946,'administration',false);
 P('early-tripoli',[[1940,1943,'Ливия · война в пустыне|Libya · Desert War|Ливия · чөл согушу','Британские силы и войска Оси неоднократно меняют линию фронта в Киренаике и Триполитании.|British and Axis forces repeatedly shift the front in Cyrenaica and Tripolitania.|Британ жана Ось күчтөрү Киренаика менен Триполитаниядагы фронтту бир нече жолу өзгөртөт.',G('early-tripoli'),'influence'],[1943,1946,'Ливия · союзное военное управление|Libya · Allied military administration|Ливия · союздаштардын аскердик башкаруусу','Триполитания и Киренаика находятся под британским, Феццан — под французским управлением.|Britain administers Tripolitania and Cyrenaica; France administers Fezzan.|Триполитания менен Киренаиканы Британия, Феццанды Франция башкарат.',G('early-tripoli'),'influence']],'Africa');link('1914-italy','early-tripoli',1940,1943,'administration',false);
 for(const id of ['early-algiers','1789-alawite','early-ottoman-tunis']){const n=c.entries.find(e=>e.id===id).phases.at(-1).name;P(id,[[1940,1942,n,'Французская колониальная администрация подчиняется Виши.|French colonial administration is aligned with Vichy.|Француз колониялык администрациясы Вишиге баш иет.'],[1942,1943,n,'После операции «Факел» Северная Африка становится ареной союзного наступления; в Тунисе продолжаются бои.|After Operation Torch, North Africa becomes the theatre of an Allied advance; fighting continues in Tunisia.|«Факел» операциясынан кийин Түндүк Африка союздаштардын чабуул аймагына айланып, Тунисте согуш уланат.',null,'influence'],[1943,1946,n,'Колониальные владения служат базой союзников; движения за независимость усиливаются.|Colonial territories become Allied bases; independence movements grow.|Колониялык ээликтер союздаштардын базасына айланып, көз карандысыздык кыймылдары күчөйт.']],'Africa');}
 P('iceland',[[1940,1941,'Исландия · британские войска|Iceland · British forces|Исландия · британ аскерлери','Британские войска высаживаются в мае 1940 года; сохраняется местное управление.|British forces land in May 1940; local government continues.|Британ аскерлери 1940-жылдын майында түшөт; жергиликтүү бийлик сакталат.'],[1941,1944,'Исландия · американская оборона|Iceland · American defence|Исландия · америкалык коргоо','По соглашению оборону острова принимают США.|The United States takes over defence by agreement.|Келишим боюнча аралды коргоону АКШ кабыл алат.'],[1944,1946,'Республика Исландия|Republic of Iceland|Исландия Республикасы','Республика провозглашена 17 июня 1944 года; уния с Данией прекращена.|The republic is proclaimed on 17 June 1944, ending the union with Denmark.|1944-жылдын 17-июнунда республика жарыяланып, Дания менен уния токтотулат.']],'Atlantic');
 P('1789-greenland-posts',[[1940,1941,'Гренландия · местное управление|Greenland · local administration|Гренландия · жергиликтүү башкаруу','После оккупации Дании связь с метрополией прерывается.|Denmark’s occupation cuts links with the metropolitan government.|Дания оккупациялангандан кийин борбордук бийлик менен байланыш үзүлөт.'],[1941,1946,'Гренландия · соглашение об обороне с США|Greenland · US defence agreement|Гренландия · АКШ менен коргонуу келишими','Соглашение 1941 года позволяет США строить оборонные объекты; Гренландия не становится американской территорией.|The 1941 agreement allows US defence installations; Greenland does not become US territory.|1941-жылкы келишим АКШга коргонуу жайларын курууга мүмкүндүк берет; Гренландия АКШ аймагына айланбайт.']],'Atlantic');
 P('1789-usa',[[1940,1941,'Соединённые Штаты Америки|United States of America|Америка Кошмо Штаттары','США наращивают оборонное производство и поддержку союзников.|The US expands defence production and support for the Allies.|АКШ коргонуу өндүрүшүн жана союздаштарга колдоосун кеңейтет.'],[1941,1945,'США · Вторая мировая война|USA · Second World War|АКШ · Экинчи дүйнөлүк согуш','После нападения на Пёрл-Харбор США вступают в войну и воюют на европейском и тихоокеанском направлениях.|After Pearl Harbor, the US enters the war in Europe and the Pacific.|Пёрл-Харбордон кийин АКШ согушка кирип, Европа менен Тынч океанда салгылашат.'],[1945,1946,'Соединённые Штаты Америки|United States of America|Америка Кошмо Штаттары','Победа союзников; США участвуют в создании ООН и послевоенном устройстве.|Allied victory; the US helps establish the UN and the postwar settlement.|Союздаштардын жеңиши; АКШ БУУну түзүүгө жана согуштан кийинки тартипке катышат.']],'Atlantic');
 P('early-portuguese-brazil',[[1940,1942,'Бразилия · Новое государство|Brazil · Estado Novo|Бразилия · Жаңы мамлекет','Авторитарный режим Жетулиу Варгаса.|Getúlio Vargas’s authoritarian government.|Жетулиу Варгастын авторитардык өкмөтү.'],[1942,1945,'Бразилия · война на стороне союзников|Brazil · Allied belligerent|Бразилия · союздаштар тарабындагы согуш','Бразилия вступает в войну в 1942 году; экспедиционный корпус воюет в Италии с 1944 года.|Brazil enters the war in 1942; its expeditionary force fights in Italy from 1944.|Бразилия 1942-жылы согушка кирип, экспедициялык корпусу 1944-жылдан Италияда согушат.'],[1945,1946,'Бразилия · конец Нового государства|Brazil · end of Estado Novo|Бразилия · Жаңы мамлекеттин аягы','Варгас отстранён в октябре; проходят президентские выборы.|Vargas is removed in October; presidential elections follow.|Варгас октябрда кызматтан алынып, президенттик шайлоо өтөт.']],'Americas');
 for(const id of ['1914-australian-colonies','1914-new-zealand']){const n=c.entries.find(e=>e.id===id).phases.at(-1).name;P(id,[[1940,1942,n,'Участие в войне на стороне союзников в Европе, Средиземноморье и Северной Африке.|Participation in the Allied war in Europe, the Mediterranean and North Africa.|Европада, Жер Ортолук деңизде жана Түндүк Африкада союздаштар тарабында согушка катышуу.'],[1942,1946,n,'Тихоокеанская война: мобилизация, базы союзников и бои против японских сил.|Pacific war: mobilisation, Allied bases and fighting against Japanese forces.|Тынч океан согушу: мобилизация, союздаштардын базалары жана япон күчтөрүнө каршы салгылашуулар.']],'Oceania');}
 for(const id of ['1918-new-guinea','early-solomons']){const n=c.entries.find(e=>e.id===id).phases.at(-1).name;P(id,[[1940,1942,n,'Местные общества живут под колониальным управлением.|Local societies live under colonial administration.|Жергиликтүү коомдор колониялык башкарууда жашайт.'],[1942,1945,n,'Японское вторжение и союзное контрнаступление; жители участвуют в перевозках, разведке и спасении людей.|Japanese invasion and Allied counter-offensives; residents assist transport, intelligence and rescue.|Япон басып кирүүсү жана союздаштардын каршы чабуулдары; тургундар ташууга, чалгындоого жана куткарууга катышат.',null,'influence'],[1945,1946,n,'После войны возобновляется колониальная администрация.|Colonial administration resumes after the war.|Согуштан кийин колониялык администрация кайра иштейт.']],'Oceania');}
 for(const[id,change]of [['palau',1945],['nanmadol',1945]]){const n=c.entries.find(e=>e.id===id).phases.at(-1).name;P(id,[[1940,change,n,'Острова затронуты войной на Тихом океане; действуют японские гарнизоны.|The Pacific war affects the islands, with Japanese garrisons present.|Тынч океан согушу аралдарга таасир этип, япон гарнизондору жайгашат.',null,'influence'],[change,1946,(id==='palau'?['Палау','Palau','Палау']:['Понпеи','Pohnpei','Понпеи']).map((name,i)=>name+[' · управление США',' · US administration',' · АКШ башкаруусу'][i]),'После боёв или капитуляции японских сил устанавливается американское военное управление.|American military administration follows fighting or the surrender of Japanese forces.|Салгылашуулардан же япон аскерлери багынгандан кийин америкалык аскердик башкаруу орнойт.',null,'influence']],'Oceania');link('japan',id,1940,change,'administration',false);link('1789-usa',id,change,1946,'administration',false);}
 P('early-guam',[[1940,1941,'Гуам · США|Guam · USA|Гуам · АКШ','Американское управление.|American administration.|Америкалык башкаруу.'],[1941,1944,'Гуам · японская оккупация|Guam · Japanese occupation|Гуам · япон оккупациясы','Япония захватывает остров в декабре 1941 года.|Japan captures the island in December 1941.|Япония аралды 1941-жылдын декабрында басып алат.',null,'influence'],[1944,1946,'Гуам · США|Guam · USA|Гуам · АКШ','Американские силы возвращают остров летом 1944 года.|US forces retake the island in summer 1944.|АКШ күчтөрү аралды 1944-жылдын жайында кайтарып алат.']],'Oceania');link('1789-usa','early-guam',1940,1941,'province',false);link('japan','early-guam',1941,1944,'occupation',false);link('1789-usa','early-guam',1944,1946,'province',false);
 P('antarctica',[[1940,1944,'Антарктида · экспедиции и притязания|Antarctica · expeditions and claims|Антарктида · экспедициялар жана дооматтар','Исследования продолжаются; постоянного коренного населения нет.|Exploration continues; there is no permanent indigenous population.|Изилдөөлөр уланат; туруктуу жергиликтүү калк жок.'],[1944,1946,'Антарктида · операция «Табарин»|Antarctica · Operation Tabarin|Антарктида · «Табарин» операциясы','В 1944 году созданы британские базы на острове Десепшен и в Порт-Локрое; в 1945 году — в заливе Хоуп.|British bases open on Deception Island and at Port Lockroy in 1944, and at Hope Bay in 1945.|1944-жылы Десепшен аралында жана Порт-Локройдо, 1945-жылы Хоуп булуңунда британ базалары ачылат.']],'Antarctica');
 event('ethiopia',1941,'ethiopia','Освобождение Эфиопии|Liberation of Ethiopia|Эфиопияны бошотуу','Итальянская оккупация прекращена; император возвращается.|Italian occupation ends; the emperor returns.|Италиялык оккупация аяктап, император кайтат.',[38.75,9.03],['Africa'],'war');
 event('alamein',1942,'early-ottoman-egypt-sham','Эль-Аламейн|El Alamein|Эль-Аламейн','Осенью британская 8-я армия оттесняет войска Оси из Египта.|In autumn the British Eighth Army drives Axis forces out of Egypt.|Күзүндө британ 8-армиясы Ось күчтөрүн Мисирден сүрүп чыгарат.',[28.95,30.83],['Africa'],'war');
 event('tabarin',1944,'antarctica','Основание Порт-Локроя|Port Lockroy established|Порт-Локройдун негизделиши','Одна из баз операции «Табарин».|One of Operation Tabarin’s bases.|«Табарин» операциясынын базаларынын бири.',[-63.5,-64.83],['Antarctica'],'culture');
 event('un',1945,'1789-usa','Создание ООН|United Nations founded|БУУнун түзүлүшү','Устав подписан в Сан-Франциско 26 июня и вступает в силу 24 октября.|The Charter is signed in San Francisco on 26 June and enters into force on 24 October.|Уставга 26-июнда Сан-Францискодо кол коюлуп, 24-октябрда күчүнө кирет.',[-122.42,37.78],['UN'],'diplomacy');
};
