'use strict';
module.exports=(c,{T,G,set,end,source,event,ring,box,before,link,geo})=>{
 const coast=require('./to1939-coasts.json');
 source('Africa','UNESCO. General History of Africa, Volume VII: Africa under Colonial Domination, 1880–1935; Volume VIII: Africa since 1935.','https://www.unesco.org/en/general-history-africa');
 source('MandatesAfrica','The National Archives. Colonial Administration Records: Tanganyika; League of Nations. Mandates annual reports.','https://www.nationalarchives.gov.uk/co-691-and-east-africa/');
 source('Ethiopia','National Army Museum. Defence of the British Legation, Addis Ababa, 1936; UNESCO. General History of Africa, Volume VIII.','https://collection.nam.ac.uk/detail.php?acc=2002-04-847--1');
 source('Americas','Foreign Relations of the United States, 1938, Volume V: The American Republics; Treaty of Peace, Friendship and Boundaries between Bolivia and Paraguay, 1938.',['https://history.state.gov/historicaldocuments/frus1938v05','https://history.state.gov/historicaldocuments/frus1938v05/d153']);
 source('Depression','Office of the Historian. The Great Depression and U.S. Foreign Policy; New Deal Trade Policy, 1934.',['https://history.state.gov/milestones/1921-1936/great-depression','https://history.state.gov/milestones/1921-1936/export-import-bank']);
 source('Caribbean','Foreign Relations of the United States, 1934, Volume V; Office of the Historian. Good Neighbor Policy, 1933.',['https://history.state.gov/historicaldocuments/frus1934v05','https://history.state.gov/milestones/1921-1936/good-neighbor']);
 source('Pacific','Manatū Taonga. New Zealand’s Administration of Samoa, 1920–1935; Black Saturday.',['https://nzhistory.govt.nz/politics/samoa','https://nzhistory.govt.nz/politics/samoa/black-saturday']);
 source('Antarctica','Australian Antarctic Division. Australian Antarctic Territory; Australian Antarctic Territory Acceptance Act, 1933.','https://www.antarctica.gov.au/magazine/issue-14-2008/in-brief/in-brief/');
 source('Commonwealth','Statute of Westminster, 1931. UK Parliament.','https://www.legislation.gov.uk/ukpga/Geo5/22-23/4/contents');
 const put=(id,rows,src,meta={})=>set(id,rows,{...meta,sources:[src]});
 put('early-ottoman-egypt-sham',[[1919,1922,'Египет · британский протекторат|Egypt · British protectorate|Мисир · британ протектораты','Национальное движение поднимает восстание 1919 года.|The nationalist movement launches the 1919 uprising.|Улуттук кыймыл 1919-жылы көтөрүлүшкө чыгат.',coast.Egypt,'influence'],[1922,1940,'Королевство Египет|Kingdom of Egypt|Мисир королдугу','Британия признаёт независимость, сохраняя военное присутствие и особые права.|Britain recognises independence while retaining troops and reserved rights.|Британия көз карандысыздыкты таанып, аскерлерин жана өзгөчө укуктарын сактайт.',coast.Egypt]],'Africa');link('1789-great-britain','early-ottoman-egypt-sham',1919,1922,'dependency');link('early-ottoman-egypt-sham','cairo');
 put('ethiopia',[[1919,1935,'аль-Хабаша · Эфиопская империя|Al-Habasha · Ethiopian Empire|Ал-Хабаша · Эфиопия империясы','Независимая империя вступает в Лигу Наций в 1923 году.|The independent empire joins the League of Nations in 1923.|Көз карандысыз империя 1923-жылы Улуттар Лигасына кирет.',coast.Ethiopia],[1935,1936,'аль-Хабаша · итальянское вторжение|Al-Habasha · Italian invasion|Ал-Хабаша · Италиянын басып кириши','В октябре 1935 года Италия начинает войну против Эфиопии.|Italy invades Ethiopia in October 1935.|Италия 1935-жылдын октябрында Эфиопияга кол салат.',coast.Ethiopia,'influence'],[1936,1940,'Эфиопия · итальянская оккупация|Ethiopia · Italian occupation|Эфиопия · италиялык оккупация','Италия занимает Аддис-Абебу и объявляет аннексию; эфиопское сопротивление продолжается.|Italy takes Addis Ababa and proclaims annexation; Ethiopian resistance continues.|Италия Аддис-Абебаны алып, аннексия жарыялайт; эфиопиялык каршылык уланат.',coast.Ethiopia,'influence']],'Ethiopia');link('1914-italy','ethiopia',1936,1940,'occupation');
 for(const id of ['lalibela','1789-harar','early-oromo','early-awsa']){link('ethiopia',id,1919,1940,'province',false);}
 put('early-tripoli',[[1919,1932,'Ливия · итальянское завоевание|Libya · Italian conquest|Ливия · италиялык басып алуу','Война против местного сопротивления расширяет итальянский контроль за пределы побережья.|War against local resistance extends Italian control beyond the coast.|Жергиликтүү каршылыкка каршы согуш италиялык көзөмөлдү жээктен ары кеңейтет.',null,'influence'],[1932,1940,'Ливия · итальянская колония|Libya · Italian colony|Ливия · италиялык колония','После подавления основного сопротивления Италия объединяет колониальное управление в 1934 году.|After suppressing the main resistance, Italy unifies colonial administration in 1934.|Негизги каршылыкты баскандан кийин Италия 1934-жылы колониялык башкарууну бириктирет.',coast.Libya]],'Africa');link('1914-italy','early-tripoli',1919,1932,'occupation');link('1914-italy','early-tripoli',1932);
 put('1914-eritrea',[[1919,1940,'Эритрея · итальянская колония|Eritrea · Italian colony|Эритрея · Италиянын колониясы','Эритрея служит базой итальянского наступления на Эфиопию.|Eritrea serves as a base for Italy’s invasion of Ethiopia.|Эритрея Италиянын Эфиопияга чабуулунун базасы болот.',coast.Eritrea]],'Africa');
 for(const[id,name,poly,coord,owner]of [
 ['1914-german-east','Танганьика · британский мандат|Tanganyika · British mandate|Танганьика · британ мандаты',coast.Tanzania,[39.28,-6.82],'1789-great-britain'],
 ['1914-namibia','Юго-Западная Африка · южноафриканский мандат|South West Africa · South African mandate|Түштүк-Батыш Африка · Түштүк Африканын мандаты',coast.Namibia,[17.08,-22.56],'1914-south-africa'],
 ['1939-ruanda','Руанда-Урунди · бельгийский мандат|Ruanda-Urundi · Belgian mandate|Руанда-Урунди · бельгиялык мандат',geo.merge([geo.union(coast.Rwanda),geo.union(coast.Burundi)]),[29.36,-3.38],'early-netherlands']
 ]){put(id,[[1919,1922,name,'Послевоенное управление бывшими германскими владениями переходит к союзникам.|The Allies administer former German territories after the war.|Согуштан кийин мурдагы герман ээликтерин союздаштар башкарат.',poly,'influence'],[1922,1940,name,'Территория управляется по мандату Лиги Наций.|The territory is administered under a League of Nations mandate.|Аймак Улуттар Лигасынын мандаты боюнча башкарылат.',poly,'influence']],'MandatesAfrica',{coord,region:'africa'});link(owner,id,1919,1940,'administration');}
 put('kilwa',[[1919,1940,'Килва · Танганьика|Kilwa · Tanganyika|Килва · Танганьика','Прибрежный центр Танганьики под британским управлением.|A Tanganyikan coastal centre under British administration.|Британия башкарган Танганьиканын жээк борбору.']],'MandatesAfrica');link('1914-german-east','kilwa',1919,1940,'province',false);
 put('1914-kenya',[[1919,1920,'Британская Восточная Африка|British East Africa|Британ Чыгыш Африкасы','Британский протекторат с растущей переселенческой экономикой.|A British protectorate with a growing settler economy.|Көчүп келгендердин чарбасы өскөн британ протектораты.',coast.Kenya,'influence'],[1920,1940,'Кения · британская колония и протекторат|Kenya · British colony and protectorate|Кения · британ колониясы жана протектораты','Внутренние районы становятся колонией; прибрежная полоса сохраняет статус протектората.|The interior becomes a colony; the coastal strip remains a protectorate.|Ички аймактар колония болот; жээк тилкеси протекторат бойдон калат.',coast.Kenya,'influence']],'Africa');link('1789-great-britain','1914-kenya',1919,1940,'administration');
 // Mainland colonial extents replace isolated administrative-centre patches.
 for(const[id,name,poly,coord,owner]of [
 ['1939-french-west','Французская Западная Африка|French West Africa|Француз Батыш Африкасы',geo.merge(['Senegal','Mali','Mauritania','Benin','Niger','Côte d\'Ivoire','Guinea','Burkina Faso'].map(n=>geo.union(coast[n]))),[-17.45,14.7],'late-france'],
 ['1939-french-equatorial','Французская Экваториальная Африка|French Equatorial Africa|Француз Экватордук Африкасы',geo.merge(['Chad','Central African Rep.','Congo','Gabon'].map(n=>geo.union(coast[n]))),[15.28,-4.27],'late-france'],
 ['1939-nigeria','Нигерия · британская колония и протекторат|Nigeria · British colony and protectorate|Нигерия · британ колониясы жана протектораты',coast.Nigeria,[3.4,6.45],'1789-great-britain'],
 ['1939-angola','Ангола · Португалия|Angola · Portugal|Ангола · Португалия',coast.Angola,[13.23,-8.83],'late-portugal'],
 ['1939-mozambique','Мозамбик · Португалия|Mozambique · Portugal|Мозамбик · Португалия',coast.Mozambique,[32.57,-25.97],'late-portugal'],
 ['1939-madagascar','Мадагаскар · французская колония|Madagascar · French colony|Мадагаскар · француз колониясы',coast.Madagascar,[47.51,-18.91],'late-france']
 ]){put(id,[[1919,1940,name,'Колониальная администрация управляет через округа, местных посредников и транспортные сети.|Colonial administration governs through districts, local intermediaries and transport networks.|Колониялык администрация округдар, жергиликтүү өкүлдөр жана транспорт тармактары аркылуу башкарат.',poly]],'Africa',{region:'africa',coord});link(owner,id);}
 for(const[owner,ids]of [['1939-french-west','mali gao timbuktu-late djenne-late early-songhay-dendi 1789-segou 1789-cayor 1789-jolof 1789-futa-toro 1789-futa-jallon 1789-dahomey'],['1939-french-equatorial','kanem'],['1939-nigeria','ife benin 1789-oyo 1815-sokoto'],['1939-angola','1789-luanda 1789-benguela 1789-matamba kongo-late'],['1939-mozambique','early-mozambique'],['1939-madagascar','1789-imerina 1789-sakalava']])for(const id of ids.split(' '))link(owner,id,1919,1940,'province',false);
 put('1914-congo',[[1919,1940,'Бельгийское Конго|Belgian Congo|Бельгия Конгосу','Колония поставляет минералы и сельскохозяйственное сырьё; трудовая мобилизация ограничивает местные общества.|The colony supplies minerals and agricultural commodities; coerced labour constrains local societies.|Колония минералдарды жана айыл чарба сырьёсун берет; мажбурланган эмгек жергиликтүү коомдорду чектейт.',coast['Dem. Rep. Congo']]],'Africa');link('early-netherlands','1914-congo');for(const id of ['1789-luba','1789-kuba'])link('1914-congo',id,1919,1940,'province',false);
 put('1789-usa',[[1919,1929,'Соединённые Штаты Америки|United States of America|Америка Кошмо Штаттары','Рост промышленности и массового потребления сопровождается социальным неравенством.|Industrial growth and mass consumption coexist with social inequality.|Өнөр жай жана массалык керектөө өсүп, социалдык теңсиздик сакталат.'],[1929,1933,'США · Великая депрессия|USA · Great Depression|АКШ · Улуу депрессия','Финансовый крах и спад производства вызывают массовую безработицу.|Financial collapse and falling output cause mass unemployment.|Каржы кыйроосу жана өндүрүштүн төмөндөшү массалык жумушсуздукту жаратат.'],[1933,1940,'США · Новый курс|USA · New Deal|АКШ · Жаңы багыт','Правительство Рузвельта проводит экономические и социальные реформы.|Roosevelt’s administration pursues economic and social reforms.|Рузвельттин өкмөтү экономикалык жана социалдык реформаларды жүргүзөт.']],'Depression');
 put('early-portuguese-brazil',[[1919,1930,'Бразильская республика|Brazilian Republic|Бразилия Республикасы','Экспортная экономика и региональные элиты определяют политическую жизнь.|An export economy and regional elites shape politics.|Экспорттук экономика жана аймактык элита саясатты аныктайт.',coast.Brazil],[1930,1937,'Бразилия · правление Варгаса|Brazil · Vargas government|Бразилия · Варгастын бийлиги','Революция 1930 года приводит Жетулиу Варгаса к власти.|The 1930 revolution brings Getúlio Vargas to power.|1930-жылкы революция Жетулиу Варгасты бийликке алып келет.',coast.Brazil],[1937,1940,'Бразилия · Новое государство|Brazil · Estado Novo|Бразилия · Жаңы мамлекет','Варгас устанавливает авторитарное Новое государство.|Vargas establishes the authoritarian Estado Novo.|Варгас авторитардык Жаңы мамлекетти орнотот.',coast.Brazil]],'Americas');
 const chaco=ring([[-62.6,-22],[-60.6,-19.3],[-58,-20],[-57.4,-22.3],[-58.2,-25.2],[-60,-24],[-62.6,-22.3]]);
 for(const[id,name,poly]of [['1815-paraguay','Республика Парагвай|Republic of Paraguay|Парагвай Республикасы',coast.Paraguay],['1815-upper-peru','Республика Боливия|Republic of Bolivia|Боливия Республикасы',coast.Bolivia]])put(id,[[1919,1932,name,'Спор за Гран-Чако обостряет отношения Боливии и Парагвая.|The Gran Chaco dispute strains Bolivian-Paraguayan relations.|Гран-Чако талашы Боливия менен Парагвайдын мамилесин курчутат.'],[1932,1938,name,'Чакская война идёт в 1932–1935 годах; затем продолжаются мирные переговоры.|The Chaco War lasts from 1932 to 1935, followed by peace negotiations.|Чако согушу 1932–1935-жылдары жүрүп, андан кийин тынчтык сүйлөшүүлөрү уланат.'],[1938,1940,name,'Договор 1938 года завершает пограничный спор; большая часть спорного Чако остаётся Парагваю.|The 1938 treaty settles the border dispute; Paraguay retains most of the disputed Chaco.|1938-жылкы келишим чек ара талашын аяктайт; талаштуу Чаконун көбү Парагвайда калат.',poly]],'Americas');
 put('1939-chaco',[[1932,1936,'Гран-Чако · район войны|Gran Chaco · war zone|Гран-Чако · согуш аймагы','Боливия и Парагвай ведут войну за этот регион.|Bolivia and Paraguay fight over this region.|Боливия менен Парагвай бул аймак үчүн согушат.',chaco,'influence']],'Americas',{coord:[-59.5,-21.3],region:'south'});
 for(const[id,finish,name]of [['1789-saint-domingue',1934,'Республика Гаити|Republic of Haiti|Гаити Республикасы'],['1848-dominican',1924,'Доминиканская Республика|Dominican Republic|Доминикан Республикасы']]){const b=before.get(id);put(id,[[1919,finish,b.phase.name,'Американская военная оккупация продолжается.|US military occupation continues.|АКШнын аскердик оккупациясы уланат.',null,'influence'],[finish,1940,name,'Американские войска выведены; внутреннее управление возвращается национальному правительству.|US troops withdraw; domestic administration returns to the national government.|АКШнын аскерлери чыгарылып, ички башкаруу улуттук өкмөткө кайтарылат.']],'Caribbean');}
 for(const id of ['early-manila','early-cebu'])put(id,[[1919,1935,'Филиппины · США|Philippines · USA|Филиппиндер · АКШ','Американское управление сохраняется при расширении местного самоуправления.|US rule continues while local self-government expands.|Жергиликтүү өзүн-өзү башкаруу кеңейип, АКШнын бийлиги сакталат.'],[1935,1940,'Содружество Филиппин|Commonwealth of the Philippines|Филиппин Шериктештиги','Создано Содружество с избранным президентом; независимость ещё не наступила.|A Commonwealth with an elected president is established; independence has not yet arrived.|Шайланган президенти бар Шериктештик түзүлөт; көз карандысыздык али келе элек.']],'Caribbean');
 for(const[id,name]of [['1914-western-samoa','Западное Самоа · новозеландский мандат|Western Samoa · New Zealand mandate|Батыш Самоа · Жаңы Зеландиянын мандаты'],['1918-new-guinea','Новая Гвинея · австралийский мандат|New Guinea · Australian mandate|Жаңы Гвинея · Австралиянын мандаты'],['palau','Палау · японский мандат|Palau · Japanese mandate|Палау · япон мандаты'],['nanmadol','Понпеи · японский мандат|Pohnpei · Japanese mandate|Понпеи · япон мандаты']]){put(id,[[1919,1920,before.get(id).phase.name,'После войны сохраняется военная администрация.|Military administration continues after the war.|Согуштан кийин аскердик администрация сакталат.',null,'influence'],[1920,1940,name,'Лига Наций закрепляет мандатное управление бывшими германскими островами.|The League of Nations establishes mandatory administration of former German islands.|Улуттар Лигасы мурдагы герман аралдарында мандаттык башкарууну бекитет.',null,'influence']],'Pacific');link(id==='1914-western-samoa'?'1914-new-zealand':id==='1918-new-guinea'?'1914-australian-colonies':'japan',id,1919,1940,'administration');}
 for(const id of ['1789-canada','1914-south-africa']){const b=before.get(id);put(id,[[1919,1931,b.phase.name,'Самоуправляющийся доминион Британской империи.|A self-governing dominion of the British Empire.|Британ империясынын өзүн-өзү башкарган доминиону.'],[1931,1940,b.phase.name,'Вестминстерский статут закрепляет законодательную самостоятельность доминиона.|The Statute of Westminster confirms the dominion’s legislative autonomy.|Вестминстер статуту доминиондун мыйзам чыгаруудагы өз алдынчалыгын бекитет.']],'Commonwealth');}
 put('antarctica',[[1919,1940,'Антарктида · исследования и территориальные притязания|Antarctica · exploration and territorial claims|Антарктида · изилдөөлөр жана аймактык дооматтар','Экспедиции используют авиацию; государства заявляют территориальные притязания. Постоянного коренного населения нет.|Expeditions use aircraft and states advance territorial claims. There is no permanent Indigenous population.|Экспедициялар авиацияны колдонот, мамлекеттер аймактык дооматтарды билдирет. Туруктуу түпкү калк жок.']],'Antarctica');
 event('depression',1929,'1789-usa','Начало Великой депрессии|Great Depression begins|Улуу депрессиянын башталышы','Биржевой крах в Нью-Йорке сопровождает начало мирового экономического кризиса.|The New York stock market crash accompanies the onset of a global economic crisis.|Нью-Йорктогу биржанын кыйроосу дүйнөлүк экономикалык кризистин башталышы менен коштолот.',[-74,40.71],['Depression']);
 event('chaco',1932,'1939-chaco','Чакская война|Chaco War|Чако согушу','Боливия и Парагвай начинают полномасштабную войну.|Bolivia and Paraguay enter full-scale war.|Боливия менен Парагвай кеңири согушка кирет.',[-59.5,-21.3],['Americas'],'war');
 event('ethiopia',1935,'ethiopia','Вторжение Италии в Эфиопию|Italian invasion of Ethiopia|Италиянын Эфиопияга басып кириши','Итальянские войска наступают из Эритреи и Сомали.|Italian forces advance from Eritrea and Somalia.|Италия аскерлери Эритреядан жана Сомалиден чабуул коёт.',[38.73,14.12],['Ethiopia'],'war');
 event('samoa',1929,'1914-western-samoa','Чёрная суббота на Самоа|Black Saturday in Samoa|Самоадагы Кара ишемби','Полиция открывает огонь по демонстрации движения Мау в Апиа.|Police fire on a Mau demonstration in Apia.|Полиция Апиа шаарындагы Мау кыймылынын демонстрациясына ок чыгарат.',[-171.75,-13.83],['Pacific']);
 event('antarctica',1936,'antarctica','Австралийское притязание в Антарктиде|Australian Antarctic claim|Австралиянын Антарктидадагы дооматы','Вступает в силу акт об Австралийской антарктической территории.|The Australian Antarctic Territory Acceptance Act comes into effect.|Австралиянын Антарктика аймагы жөнүндө акт күчүнө кирет.',[142.67,-67.01],['Antarctica'],'diplomacy');
 // Close remaining wartime captions and add explicit political transitions.
 put('1914-italy',[[1919,1922,'Королевство Италия|Kingdom of Italy|Италия королдугу','Италия получает территории на севере и востоке по послевоенным договорам.|Italy gains northern and eastern territories under postwar treaties.|Италия согуштан кийинки келишимдер боюнча түндүк жана чыгыш аймактарды алат.'],[1922,1940,'Италия · фашистский режим|Italy · Fascist regime|Италия · фашисттик режим','Муссолини приходит к власти в 1922 году; режим ведёт колониальные войны.|Mussolini comes to power in 1922; the regime wages colonial wars.|Муссолини 1922-жылы бийликке келет; режим колониялык согуштарды жүргүзөт.']],'Africa');
 put('1914-albania',[[1919,1928,'Албания|Albania|Албания','Государственность восстанавливается после военных оккупаций.|State institutions recover after wartime occupations.|Аскердик оккупациялардан кийин мамлекеттик түзүлүш калыбына келет.'],[1928,1939,'Королевство Албания|Kingdom of Albania|Албания королдугу','Ахмет Зогу становится королём.|Ahmet Zogu becomes king.|Ахмет Зогу король болот.'],[1939,1940,'Албания · итальянская оккупация|Albania · Italian occupation|Албания · италиялык оккупация','Италия вторгается в апреле и устанавливает контроль.|Italy invades in April and establishes control.|Италия апрелде кирип, көзөмөл орнотот.',null,'influence']],'Peace');link('1914-italy','1914-albania',1939,1940,'occupation');
 put('1789-bangkok',[[1919,1932,'Королевство Сиам|Kingdom of Siam|Сиам королдугу','Независимая монархия между британскими и французскими владениями.|An independent monarchy between British and French possessions.|Британ жана француз ээликтеринин ортосундагы көз карандысыз монархия.'],[1932,1939,'Сиам · конституционная монархия|Siam · constitutional monarchy|Сиам · конституциялык монархия','Революция 1932 года ограничивает королевскую власть.|The 1932 revolution limits royal power.|1932-жылкы революция королдун бийлигин чектейт.'],[1939,1940,'Таиланд|Thailand|Таиланд','В 1939 году государство переименовано в Таиланд.|The state is renamed Thailand in 1939.|1939-жылы мамлекет Таиланд деп аталат.']],'India');
};
