'use strict';
module.exports=(c,{T,G,set,end,source,event,ring,box,before,link,geo})=>{
 source('Turkey','Türkiye Büyük Millet Meclisi. Kurtuluş Savaşı Müzesi; TDV İslâm Ansiklopedisi. Suriye.',['https://www.tbmm.gov.tr/Sayfa/KurtulusSavasiMuzesi','https://islamansiklopedisi.org.tr/suriye']);
 source('Mandates','League of Nations. The Mandates System; Mandate for Palestine, 1922.',['https://www.un.org/unispal/document/auto-insert-176218/','https://www.un.org/unispal/document/auto-insert-201057/']);
 source('Iraq','TDV İslâm Ansiklopedisi. Irak; United Nations. The Origins and Evolution of the Palestine Problem, Part I.',['https://islamansiklopedisi.org.tr/irak--ulke','https://www.un.org/unispal/document/auto-insert-199840/']);
 source('Arabia','TDV İslâm Ansiklopedisi. Suudi Arabistan; Suûdîler.',['https://islamansiklopedisi.org.tr/suudi-arabistan','https://islamansiklopedisi.org.tr/suudiler']);
 source('Kyrgyz','Мэрия Бишкека. История города; Национальный статистический комитет Кыргызской Республики. История государственности.',['https://www.bishkek.gov.kg/ru/history','https://www.stat.gov.kg/ru/news/nacstatkom-pozdravlyaet-sootechestvennikov-s-25-letiem-dnya-nezavisimosti-kyrgyzstana/']);
 source('CentralAsia','Library of Congress. Kazakstan, Kyrgyzstan, Tajikistan, Turkmenistan, and Uzbekistan: Country Studies, 1997; Tajikistan: Country Profile, 2007.',['https://www.loc.gov/item/97005110/','https://tile.loc.gov/storage-services/master/frd/copr/Tajikistan.pdf']);
 source('Mongolia','Library of Congress. Mongolia: A Country Study; Р. Ш. Харунов. Формирование интеллигенции в Тувинской Народной Республике (1921–1944 гг.).',['https://tile.loc.gov/storage-services/master/frd/frdcstdy/mo/mongoliacountrys00word_0/mongoliacountrys00word_0.pdf','https://www.prlib.ru/item/389189']);
 source('China','Foreign Relations of the United States. The Far East, 1937; Office of the Historian. The Mukden Incident of 1931 and the Stimson Doctrine.',['https://history.state.gov/historicaldocuments/frus1937v03/d484','https://history.state.gov/milestones/1921-1936/mukden-incident']);
 source('India','Library of Congress. India: A Country Study, 1995; Government of India Act, 1935.','https://www.loc.gov/item/96019266/');
 source('Iran','TDV İslâm Ansiklopedisi. İran: Tarih; Afganistan: Tarih.',['https://islamansiklopedisi.org.tr/iran','https://islamansiklopedisi.org.tr/afganistan']);
 const put=(id,rows,src,meta={})=>set(id,rows,{...meta,sources:[src]});
 const anatolia=ring([[26,39],[27,36.6],[30.5,36],[32.8,36.1],[35.8,36.7],[37,36.7],[40,37.1],[42.4,37.2],[44.8,37.2],[44.5,39.4],[43.5,41.4],[41.5,41.5],[39,41],[36,41.5],[32,42],[29,41],[27,40.5]]),thrace=ring([[26,40.7],[26.4,41.7],[27.5,42],[29.1,41.2],[28,40.9]]),hatay=ring([[35.8,35.8],[36.4,35.9],[36.6,36.7],[36.1,36.9],[35.7,36.2]]);
 put('late-ottoman',[[1919,1923,'Османское государство · конец султаната|Ottoman state · end of the sultanate|Осмон мамлекети · султандыктын аягы','Стамбульское правительство соперничает с национальным движением в Анкаре. Султанат упразднён в ноябре 1922 года.|The Istanbul government rivals the national movement in Ankara. The sultanate is abolished in November 1922.|Стамбул өкмөтү Анкарадагы улуттук кыймыл менен атаандашат. Султандык 1922-жылдын ноябрында жоюлат.',geo.merge([anatolia,thrace]),'influence']],'Turkey');
 put('1939-turkey',[[1923,1939,'Турецкая Республика|Republic of Türkiye|Түркия Республикасы','Лозаннский договор закрепляет новый порядок; 29 октября провозглашена республика. Халифат упразднён в 1924 году.|Lausanne establishes a new settlement; the republic is proclaimed on 29 October. The caliphate is abolished in 1924.|Лозанна жаңы тартипти бекитет; 29-октябрда республика жарыяланат. Халифат 1924-жылы жоюлат.',geo.merge([anatolia,thrace])],[1939,1940,'Турецкая Республика · Хатай|Republic of Türkiye · Hatay|Түркия Республикасы · Хатай','Хатай присоединён к Турции в 1939 году.|Hatay joins Türkiye in 1939.|Хатай 1939-жылы Түркияга кошулат.',geo.merge([anatolia,thrace,hatay])]],'Turkey',{coord:[32.85,39.93],color:'#a48157'});
 // Former Ottoman Arab provinces acquire separate administrations.
 const syria=ring([[35.7,32.7],[36.9,32.3],[38.8,33.4],[41,34.5],[42.4,37.2],[40,37.1],[37,36.7],[36.6,36.7],[36.4,35.9],[35.9,35.7],[36.2,34.6],[35.7,33.4]]);
 put('1815-sham',[[1919,1920,'Аш-Шам · арабская администрация|Al-Sham · Arab administration|Аш-Шам · араб башкаруусу','Правительство Фейсала действует в Дамаске.|Faisal’s government operates in Damascus.|Файсалдын өкмөтү Дамаскта иштейт.',syria,'influence'],[1920,1940,'Сирия · французский мандат|Syria · French mandate|Сирия · француз мандаты','После сражения при Майсалуне Франция устанавливает контроль; мандат утверждён в 1922 году.|France establishes control after Maysalun; the mandate is approved in 1922.|Майсалундагы салгылашуудан кийин Франция көзөмөл орнотот; мандат 1922-жылы бекитилет.',syria,'influence']],'Mandates');link('late-france','1815-sham',1920,1940,'administration');
 for(const[id,name,coord,poly,from,owner,text]of [
 ['lebanon','Ливан · французский мандат|Lebanon · French mandate|Ливан · француз мандаты',[35.5,33.89],[[35.1,33.1],[35.7,33.4],[36.2,34.6],[35.9,34.7],[35.5,34.1]],1920,'late-france','В 1920 году создан Большой Ливан под французским управлением.|Greater Lebanon is created under French administration in 1920.|1920-жылы француз башкаруусунда Улуу Ливан түзүлөт.'],
 ['palestine','Палестина · британское управление|Palestine · British administration|Палестина · Британиянын башкаруусу',[35.23,31.78],[[34.25,31.3],[34.9,29.5],[35.2,31],[35.6,32.5],[35.6,33.3],[35.1,33.1]],1919,'1789-great-britain','Военная администрация сменяется гражданской в 1920 году; мандат утверждён в 1922 году.|Civil administration replaces military rule in 1920; the mandate is approved in 1922.|1920-жылы аскердик башкаруу жарандыкка алмашат; мандат 1922-жылы бекитилет.'],
 ['transjordan','Трансиордания · эмират|Transjordan · emirate|Трансиордания · эмирлик',[35.93,31.95],[[35.2,29.4],[36.1,29.2],[38,31.5],[39.3,32.2],[38.8,33.4],[36.9,32.3],[35.6,32.5],[35.2,31]],1921,'1789-great-britain','Эмир Абдаллах правит при британском мандатном контроле.|Emir Abdullah rules under British mandatory supervision.|Эмир Абдаллах британ мандатынын көзөмөлүндө башкарат.']
 ]){put('1939-'+id,[[from,1940,name,text,ring(poly),'influence']],'Mandates',{coord});link(owner,'1939-'+id,from,1940,'administration');}
 const iraq=ring([[38.8,33.4],[39.3,32.2],[42,29.5],[44.7,29.2],[46.5,29.1],[48.5,30],[47.8,31.8],[46,33],[45,35],[44.8,37.2],[42.4,37.2],[41,34.5]]);
 put('1939-iraq',[[1919,1921,'Ирак · британская администрация|Iraq · British administration|Ирак · британ администрациясы','Британское управление сталкивается с восстанием 1920 года.|British administration faces the 1920 revolt.|Британ башкаруусу 1920-жылдагы көтөрүлүшкө туш болот.',iraq,'influence'],[1921,1932,'Королевство Ирак · британское влияние|Kingdom of Iraq · British supervision|Ирак королдугу · британ көзөмөлү','Фейсал становится королём; договоры закрепляют британское влияние.|Faisal becomes king; treaties maintain British influence.|Файсал король болот; келишимдер британ таасирин сактайт.',iraq,'influence'],[1932,1940,'Королевство Ирак|Kingdom of Iraq|Ирак королдугу','Ирак вступает в Лигу Наций как независимое государство.|Iraq enters the League of Nations as an independent state.|Ирак Улуттар Лигасына көз карандысыз мамлекет катары кирет.',iraq]],'Iraq',{coord:[44.37,33.32]});link('1789-great-britain','1939-iraq',1919,1932,'administration');
 end('1918-medina',1919);
 put('late-mecca',[[1919,1924,'Королевство Хиджаз|Kingdom of Hejaz|Хижаз королдугу','Хашимитская монархия управляет Меккой и Мединой.|The Hashemite monarchy governs Mecca and Medina.|Хашимит монархиясы Мекке менен Мединаны башкарат.'],[1924,1926,'Хиджаз · саудовское завоевание|Hejaz · Saudi conquest|Хижаз · Сауд басып алуусу','Войска Ибн Сауда занимают Мекку в 1924 году, Медину и Джидду — в 1925 году.|Ibn Saud’s forces take Mecca in 1924 and Medina and Jeddah in 1925.|Ибн Сауддун аскери 1924-жылы Меккени, 1925-жылы Медина менен Жидданы алат.',null,'influence'],[1926,1940,'Хиджаз · владения Ибн Сауда|Hejaz · Ibn Saud’s domains|Хижаз · Ибн Сауддун ээликтери','Хиджаз находится под властью Абд аль-Азиза ибн Сауда.|Hejaz is ruled by Abd al-Aziz ibn Saud.|Хижазды Абд ал-Азиз ибн Сауд башкарат.']],'Arabia');
 const arabia=ring([[34.6,28],[36,26],[38,22],[41,18],[43,16.5],[46,17],[51.5,18],[55,22],[51,24],[50,27],[48,29],[44.7,29.2],[42,31],[39.3,32.2],[38,31.5],[36.1,29.2]]);
 put('1789-diriyah',[[1919,1926,'Неджд · держава Ибн Сауда|Najd · Ibn Saud’s state|Нажд · Ибн Сауддун мамлекети','В 1921 году завоёван Хаиль, затем начинается борьба за Хиджаз.|Ha’il is conquered in 1921, followed by the struggle for Hejaz.|1921-жылы Хаиль алынат, андан соң Хижаз үчүн күрөш башталат.'],[1926,1932,'Хиджаз и Неджд|Hejaz and Najd|Хижаз жана Нажд','Два королевства объединены властью одного монарха.|Two kingdoms share one monarch.|Эки королдук бир монархтын бийлигинде биригет.',arabia],[1932,1940,'Королевство Саудовская Аравия|Kingdom of Saudi Arabia|Сауд Арабия королдугу','В 1932 году объявлено единое королевство; Таифский договор 1934 года завершает войну с Йеменом.|A united kingdom is proclaimed in 1932; the 1934 Treaty of Taif ends war with Yemen.|1932-жылы бирдиктүү королдук жарыяланат; 1934-жылкы Таиф келишими Йемен менен согушту аяктайт.',arabia]],'Arabia');link('1789-diriyah','late-mecca',1926,1940,'province',false);
 put('1789-qasimid',[[1919,1940,'Йеменское Мутаваккилийское королевство|Mutawakkilite Kingdom of Yemen|Йемен Мутаваккилит королдугу','Имам Яхья возглавляет независимое государство после ухода османов.|Imam Yahya heads an independent state after the Ottoman withdrawal.|Осмондор кеткенден кийин имам Яхья көз карандысыз мамлекетти жетектейт.']],'Arabia');
 put('1789-qajar',[[1919,1925,'Иран · Каджары|Iran · Qajar dynasty|Иран · Кажарлар','Слабость центральной власти и переворот 1921 года открывают путь Реза-хану.|Weak central authority and the 1921 coup open the way for Reza Khan.|Борбордук бийликтин алсыздыгы жана 1921-жылкы төңкөрүш Реза ханга жол ачат.'],[1925,1940,'Иран · Пехлеви|Iran · Pahlavi dynasty|Иран · Пехлевилер','Реза-шах начинает централизацию и государственные реформы.|Reza Shah pursues centralisation and state reforms.|Реза шах борборлоштурууну жана мамлекеттик реформаларды жүргүзөт.']],'Iran');
 put('1789-durrani',[[1919,1926,'Эмират Афганистан · независимость|Emirate of Afghanistan · independence|Афганстан эмирлиги · көз карандысыздык','Война 1919 года завершает британский контроль внешней политики.|The 1919 war ends British control of foreign affairs.|1919-жылкы согуш тышкы саясаттагы британ көзөмөлүн токтотот.'],[1926,1929,'Королевство Афганистан · Аманулла|Kingdom of Afghanistan · Amanullah|Афганстан королдугу · Аманулла','Аманулла принимает королевский титул и проводит реформы.|Amanullah takes the royal title and pursues reforms.|Аманулла король наамын алып, реформаларды жүргүзөт.'],[1929,1940,'Королевство Афганистан|Kingdom of Afghanistan|Афганстан королдугу','После Гражданской войны 1929 года власть переходит к Надир-шаху, затем к Захир-шаху.|After the civil war of 1929, Nadir Shah and then Zahir Shah rule.|1929-жылкы Жарандык согуштан кийин Надир шах, андан соң Захир шах бийлик кылат.']],'Iran');
 const kg=ring([[69.2,39.8],[70.5,39.5],[72,39.4],[73.9,39.5],[75.7,40.3],[76.5,41.2],[78.4,41.7],[80.2,42.2],[80,42.9],[76.8,42.8],[74.5,43.2],[72.5,42.7],[70.9,42.2],[71.6,41.5],[70.4,40.8],[69.2,40.1]]);
 const kgrows=[[1919,1924,'Кыргызские земли · Туркестанская АССР|Kyrgyz lands · Turkestan ASSR|Кыргыз жерлери · Түркстан АССРи','Восстановление после Үркүн и Гражданской войны проходит в составе Туркестанской АССР.|Recovery from Urkun and civil war takes place within the Turkestan ASSR.|Үркүндөн жана Жарандык согуштан кийинки калыбына келүү Түркстан АССРинин ичинде жүрөт.'],[1924,1925,'Кара-Кыргызская автономная область|Kara-Kyrgyz Autonomous Region|Кара-Кыргыз автономиялуу облусу','В октябре 1924 года образована автономная область в составе РСФСР.|An autonomous region within the RSFSR is created in October 1924.|1924-жылдын октябрында РСФСРдин курамында автономиялуу облус түзүлөт.'],[1925,1926,'Кыргызская автономная область|Kyrgyz Autonomous Region|Кыргыз автономиялуу облусу','В 1925 году из названия области убрано слово «Кара».|The word “Kara” is removed from the region’s name in 1925.|1925-жылы облустун аталышынан «Кара» сөзү алынат.'],[1926,1936,'Кыргызская АССР|Kyrgyz ASSR|Кыргыз АССРи','Автономная республика в составе РСФСР; столица переименована во Фрунзе.|An autonomous republic within the RSFSR; the capital is renamed Frunze.|РСФСРдин курамындагы автономиялуу республика; борбору Фрунзе деп аталат.'],[1936,1940,'Кыргызская ССР|Kyrgyz SSR|Кыргыз ССРи','Кыргызстан становится союзной республикой СССР 5 декабря 1936 года.|Kyrgyzstan becomes a union republic of the USSR on 5 December 1936.|Кыргызстан 1936-жылдын 5-декабрында СССРдин союздук республикасы болот.']].map(r=>[...r,kg]);
 put('late-kyrgyz-tianshan',kgrows,'Kyrgyz',{coord:[74.6,42.87],centralAsia:true});link('1939-ussr','late-kyrgyz-tianshan',1922,1940,'province',false);
 put('1848-pishpek',[[1919,1926,'Пишпек|Pishpek|Пишпек','В 1924 году город становится административным центром кыргызской автономии.|In 1924 the city becomes the administrative centre of Kyrgyz autonomy.|1924-жылы шаар кыргыз автономиясынын башкаруу борбору болот.'],[1926,1940,'Фрунзе|Frunze|Фрунзе','Пишпек переименован во Фрунзе в мае 1926 года.|Pishpek is renamed Frunze in May 1926.|Пишпек 1926-жылдын майында Фрунзе деп өзгөртүлөт.']],'Kyrgyz');link('1939-ussr','1848-pishpek',1922,1940,'province',false);
 for(const[id,newname]of [['early-bukhara','Бухарская народная советская республика|Bukharan People’s Soviet Republic|Бухара Эл Совет Республикасы'],['early-khwarazm','Хорезмская народная советская республика|Khorezm People’s Soviet Republic|Хорезм Эл Совет Республикасы']]){const b=before.get(id);put(id,[[1919,1920,b.phase.name,'Монархия сохраняется до наступления Красной армии 1920 года.|The monarchy survives until the Red Army offensive of 1920.|Монархия Кызыл Армиянын 1920-жылкы чабуулуна чейин сакталат.'],[1920,1924,newname,'После свержения монархии создаётся советская республика; в 1924 году её земли разделены при национальном размежевании.|A soviet republic follows the monarchy; its lands are divided in the 1924 national delimitation.|Монархия кулатылып, советтик республика түзүлөт; 1924-жылы жерлери улуттук бөлүштүрүүдө бөлүнөт.']],'CentralAsia');}
 end('1914-tashkent',1924);end('1789-kokand',1924);
 put('early-kazakh',[[1919,1920,'Казахские земли · Алаш и Гражданская война|Kazakh lands · Alash and Civil War|Казак жерлери · Алаш жана Жарандык согуш','Гражданская война меняет власть в степи.|Civil war changes authority across the steppe.|Жарандык согуш талаадагы бийликти өзгөртөт.',null,'influence'],[1920,1936,'Казахская автономия в РСФСР|Kazakh autonomy within the RSFSR|РСФСРдеги казак автономиясы','Автономная республика учреждена в 1920 году; до 1925 года официально называется Киргизской АССР.|The autonomous republic is established in 1920; its official name until 1925 is Kirghiz ASSR.|Автономиялуу республика 1920-жылы түзүлөт; 1925-жылга чейин расмий аталышы Киргиз АССРи болгон.'],[1936,1940,'Казахская ССР|Kazakh SSR|Казак ССРи','В 1936 году Казахстан становится союзной республикой.|Kazakhstan becomes a union republic in 1936.|1936-жылы Казакстан союздук республика болот.']],'CentralAsia');link('1939-ussr','early-kazakh',1922,1940,'province',false);
 const uz=ring([[56,41],[58,45.5],[62,45.5],[64,42],[69,41.7],[71,41.2],[73,40.8],[72,40],[70,40],[68.5,39.5],[68,37.3],[66.5,37.1],[63,39],[60,41]]),tm=ring([[52.5,37.2],[54,42],[58,42],[60,41],[63,39],[66.5,37.1],[63,35.2],[60,35.5],[57,37.8]]),tj=ring([[67.4,37],[69.5,36.8],[71.5,36.7],[73,37.1],[75,37.4],[74.8,39],[73.9,39.5],[72,39.4],[70.5,39.5],[69.2,39.8],[68.5,39.5]]);
 for(const[id,name,coord,poly]of [['uzbek','Узбекская ССР|Uzbek SSR|Өзбек ССРи',[69.24,41.3],uz],['turkmen','Туркменская ССР|Turkmen SSR|Түркмөн ССРи',[58.38,37.96],tm]]){put('1939-'+id,[[1924,1940,name,'Республика создана при национальном размежевании Центральной Азии.|The republic is formed during Central Asia’s national delimitation.|Республика Борбордук Азияны улуттук бөлүштүрүүдө түзүлөт.',poly]],'CentralAsia',{coord,centralAsia:true});link('1939-ussr','1939-'+id,1924,1940,'province',false);}
 put('1939-tajik',[[1924,1929,'Таджикская АССР|Tajik ASSR|Тажик АССРи','Автономная республика в составе Узбекской ССР.|An autonomous republic within the Uzbek SSR.|Өзбек ССРинин курамындагы автономиялуу республика.',tj],[1929,1940,'Таджикская ССР|Tajik SSR|Тажик ССРи','Таджикистан становится союзной республикой в 1929 году.|Tajikistan becomes a union republic in 1929.|Тажикстан 1929-жылы союздук республика болот.',tj]],'CentralAsia',{coord:[68.78,38.56],centralAsia:true});link('1939-ussr','1939-tajik',1924,1940,'province',false);
 put('1914-mongolia',[[1919,1921,'Монголия · китайская оккупация|Mongolia · Chinese occupation|Монголия · кытай оккупациясы','Китайские войска ликвидируют автономию в 1919 году.|Chinese troops abolish autonomy in 1919.|Кытай аскерлери 1919-жылы автономияны жоёт.',null,'influence'],[1921,1924,'Монголия · народное правительство|Mongolia · people’s government|Монголия · элдик өкмөт','Революция 1921 года создаёт новое правительство при сохранении Богдо-хана.|The 1921 revolution creates a new government while retaining the Bogd Khan.|1921-жылкы революция Богдо ханды сактап, жаңы өкмөт түзөт.'],[1924,1940,'Монгольская Народная Республика|Mongolian People’s Republic|Монгол Эл Республикасы','После смерти Богдо-хана провозглашена республика, тесно связанная с СССР.|After the Bogd Khan’s death, a republic closely linked to the USSR is proclaimed.|Богдо хан өлгөндөн кийин СССР менен тыгыз байланышкан республика жарыяланат.']],'Mongolia');
 put('cartography-tuva',[[1919,1921,'Тува · борьба за власть|Tuva · struggle for power|Тува · бийлик үчүн күрөш','Местные, русские и китайские силы борются за контроль.|Local, Russian and Chinese forces contest control.|Жергиликтүү, орус жана кытай күчтөрү көзөмөл үчүн күрөшөт.',null,'influence'],[1921,1940,'Тувинская Народная Республика|Tuvan People’s Republic|Тыва Эл Республикасы','В 1921 году создана республика; в состав СССР она ещё не входит.|A republic is established in 1921; it is not yet part of the USSR.|1921-жылы республика түзүлөт; ал СССРдин курамына али кирбейт.',null,'polity']],'Mongolia');
 const manchuria=ring([[119.9,49.5],[120.7,53.4],[124,53.5],[127,50],[130.7,48],[134.6,48.4],[134.8,47.3],[133,45],[131.1,44],[130.7,42.5],[129.8,42.9],[128.1,41.3],[126.6,41.8],[124.4,39.8],[122.2,39.1],[120,40.5],[119,43],[117,48]]);
 const china=G('1789-qing'),unoccupied=geo.difference(china,manchuria);
 put('1789-qing',[[1919,1928,'Китайская республика · милитаристы|Republic of China · warlord era|Кытай Республикасы · аскер башчылары','Региональные военные правители оспаривают власть центральных правительств.|Regional military rulers contest central governments’ authority.|Аймактык аскер башчылары борбордук өкмөттөрдүн бийлигине атаандашат.',china,'influence'],[1928,1932,'Китайская республика · Нанкин|Republic of China · Nanjing|Кытай Республикасы · Нанкин','Северный поход усиливает нанкинское правительство; региональные армии сохраняются.|The Northern Expedition strengthens Nanjing; regional armies remain.|Түндүк жортуул Нанкин өкмөтүн бекемдейт; аймактык аскерлер сакталат.',china,'influence'],[1932,1937,'Китайская республика|Republic of China|Кытай Республикасы','Маньчжурия отделена японским вторжением; продолжается конфликт националистов и коммунистов.|Japanese invasion separates Manchuria; Nationalist-Communist conflict continues.|Япон басып кирүүсү Маньчжурияны бөлөт; улутчулдар менен коммунисттердин жаңжалы уланат.',unoccupied,'influence'],[1937,1940,'Китай · война с Японией|China · war with Japan|Кытай · Япония менен согуш','Полномасштабная война начинается в 1937 году. Япония занимает крупные города и транспортные коридоры на востоке.|Full-scale war begins in 1937. Japan occupies major eastern cities and transport corridors.|1937-жылы кеңири согуш башталат. Япония чыгыштагы ири шаарларды жана транспорт жолдорун ээлейт.',unoccupied,'influence']],'China');
 put('1939-manchukuo',[[1932,1940,'Маньчжоу-го · зависимость от Японии|Manchukuo · Japanese dependency|Маньчжоу-го · Японияга көз карандылык','Созданное после японского вторжения государство контролируется японской армией.|The state created after the Japanese invasion is controlled by Japan’s army.|Япон басып кирүүсүнөн кийин түзүлгөн мамлекет япон аскеринин көзөмөлүндө.',manchuria,'influence']],'China',{coord:[125.32,43.9],color:'#a2ad82'});link('japan','1939-manchukuo',1932,1940,'dependency');
 const occupiedNorth=ring([[115.5,39.8],[117,40.8],[120,40.5],[122,39],[119.5,37.5],[121.5,37.3],[120.3,35.5],[117,34.5],[115,36]]),yangtze=ring([[114,30.2],[118,30.7],[121.5,30.8],[121.8,32],[118.5,32.5],[116,31.5],[114,31]]);
 put('1939-china-occupation',[[1937,1938,'Китай · японские зоны оккупации|China · Japanese occupation zones|Кытай · япон оккупация аймактары','Пекин, Шанхай и Нанкин захвачены в 1937 году.|Beijing, Shanghai and Nanjing fall in 1937.|1937-жылы Бээжин, Шанхай жана Нанкин алынат.',geo.merge([occupiedNorth,box(118,30.7,121.8,32.5)]),'influence'],[1938,1940,'Китай · японские зоны оккупации|China · Japanese occupation zones|Кытай · япон оккупация аймактары','В 1938 году захвачены Ухань и Гуанчжоу; контроль в сельской местности остаётся неоднородным.|Wuhan and Guangzhou fall in 1938; rural control remains uneven.|1938-жылы Ухань менен Гуанчжоу алынат; айыл жерлеринде көзөмөл бирдей эмес.',geo.merge([occupiedNorth,yangtze,box(112.9,22.6,113.9,23.5)]),'influence']],'China',{coord:[118.8,32.06]});link('japan','1939-china-occupation',1937,1940,'occupation');
 link('1789-qing','1914-xinjiang',1919,1940,'dependency',false);
 put('early-mughal',[[1919,1940,'Дели · Британская Индия|Delhi · British India|Дели · Британ Индиясы','Национальное движение добивается самоуправления; в 1931 году торжественно открыт новый столичный комплекс Нью-Дели.|The national movement seeks self-government; New Delhi is inaugurated as capital in 1931.|Улуттук кыймыл өзүн-өзү башкарууну талап кылат; Нью-Дели 1931-жылы расмий борбор катары ачылат.']],'India');
 for(const id of ['1789-konbaung','1848-burmese-coast']){const b=before.get(id);put(id,[[1919,1937,b.phase.name,'Бирма остаётся частью Британской Индии.|Burma remains part of British India.|Бирма Британ Индиясынын бөлүгү бойдон калат.'],[1937,1940,'Бирма · отдельная британская колония|Burma · separate British colony|Бирма · өзүнчө британ колониясы','В 1937 году Бирма административно отделена от Индии.|Burma is administratively separated from India in 1937.|1937-жылы Бирма административдик жактан Индиядан бөлүнөт.']],'India');}
 event('turkey',1923,'1939-turkey','Провозглашение Турецкой Республики|Turkish Republic proclaimed|Түркия Республикасынын жарыяланышы','29 октября парламент провозглашает республику.|Parliament proclaims the republic on 29 October.|29-октябрда парламент республиканы жарыялайт.',[32.85,39.93],['Turkey']);
 event('kyrgyz',1924,'late-kyrgyz-tianshan','Кыргызская автономия|Kyrgyz autonomy|Кыргыз автономиясы','14 октября образована Кара-Кыргызская автономная область.|The Kara-Kyrgyz Autonomous Region is formed on 14 October.|14-октябрда Кара-Кыргыз автономиялуу облусу түзүлөт.',[74.6,42.87],['Kyrgyz']);
 event('kyrgyz-ssr',1936,'late-kyrgyz-tianshan','Кыргызская ССР|Kyrgyz SSR|Кыргыз ССРи','Кыргызстан получает статус союзной республики.|Kyrgyzstan receives union-republic status.|Кыргызстан союздук республика макамын алат.',[74.6,42.87],['Kyrgyz']);
 event('mukden',1931,'1789-qing','Японское вторжение в Маньчжурию|Japanese invasion of Manchuria|Япониянын Маньчжурияга басып кириши','Мукденский инцидент становится поводом для вторжения.|The Mukden Incident provides a pretext for invasion.|Мукден окуясы басып кирүүгө шылтоо болот.',[123.43,41.8],['China'],'war');
 event('china-war',1937,'1789-qing','Начало полномасштабной войны в Китае|Full-scale war begins in China|Кытайда кеңири согуштун башталышы','Столкновение у моста Лугоуцяо приводит к расширению войны.|The clash at Marco Polo Bridge leads to widening war.|Лугоуцяо көпүрөсүндөгү кагылыш согуштун кеңейишине алып келет.',[116.21,39.85],['China'],'war');
};
