'use strict';
module.exports=(c,{G,set,source,event,box,before})=>{
 source('Australia','National Museum of Australia. Federation; Australian Gold Rushes.',['https://www.nma.gov.au/defining-moments/resources/federation','https://www.nma.gov.au/defining-moments/resources/gold-rushes']);
 source('NZ','Manatū Taonga. New Zealand Wars; Dominion Status; Women and the Vote.',['https://nzhistory.govt.nz/war-and-society','https://nzhistory.govt.nz/page/dominion-status','https://nzhistory.govt.nz/politics/womens-suffrage']);
 source('Hawaii','Office of the Historian. Annexation of Hawaii, 1898; National Archives. Joint Resolution to Provide for Annexing the Hawaiian Islands (1898).',['https://history.state.gov/milestones/1866-1898/hawaii','https://www.archives.gov/milestone-documents/joint-resolution-for-annexing-the-hawaiian-islands']);
 source('Pacific','The Cambridge History of the Pacific Ocean; Manatū Taonga. Samoa and New Zealand.',['https://nzhistory.govt.nz/politics/samoa']);
 source('Alaska','Office of the Historian. Purchase of Alaska, 1867.',['https://history.state.gov/milestones/1866-1898/alaska-purchase']);
 source('Polar','British Antarctic Survey. South Pole Conquered 100 Years Ago Today; Scott Polar Research Institute. The Terra Nova Expedition.',['https://www.bas.ac.uk/news/south-pole-conquered-100-years-ago-today/','https://www.bas.ac.uk/news/this-week-is-the-centenary-of-captain-robert-falcon-scotts-expedition-to-the-south-pole/']);
 source('Arctic','National Museum of Denmark. Greenland; Alþingi. A Brief History of Althingi.',['https://www.althingi.is/english/about-the-parliament/history-of-althingi/']);
 const put=(id,rows,s,meta={})=>set(id,rows,{sources:['to1914'+s],...meta});
 const australia=[[[113,-22],[114,-25],[115,-29],[116,-34],[119,-35],[123,-34],[129,-32],[134,-33],[138,-35],[141,-38],[146,-39],[150,-37],[153,-29],[153,-25],[149,-20],[145,-15],[142,-11],[140,-17],[137,-16],[136,-12],[131,-12],[129,-15],[125,-14],[121,-18],[116,-20]]],tasmania=[[[144.5,-40.5],[148.5,-40.5],[148,-43.5],[146,-43.6],[144.5,-41.5]]];
 put('1914-australian-colonies',[[1849,1901,'Австралия · британские колонии|Australia · British colonies|Австралия · британ колониялары','Британские колонии расширяют хозяйство и управление. Золотые лихорадки с 1851 года ускоряют миграцию; коренные народы сталкиваются с захватом земель.|British colonies expand settlement and government. Gold rushes from 1851 accelerate migration; Indigenous peoples face dispossession.|Британ колониялары чарбасын жана башкаруусун кеңейтет. 1851-жылдан алтын дүрбөлөңү көчүүнү тездетет; түпкү элдер жерлеринен ажыратылат.',[...australia,...tasmania],'influence'],[1901,1915,'Австралийский Союз|Commonwealth of Australia|Австралия Союзу','Шесть колоний образуют федерацию. Политика «белой Австралии» ограничивает иммиграцию; коренные народы испытывают дискриминацию.|Six colonies form a federation. The White Australia policy restricts immigration; Indigenous peoples face discrimination.|Алты колония федерация түзөт. «Ак Австралия» саясаты иммиграцияны чектейт; түпкү элдер басмырлоого туш болот.',[...australia,...tasmania]]],'Australia',{region:'australia',coord:[134,-26],color:'#a8916d'});
 for(const id of ['1789-sydney','1815-bathurst','1815-hobart','1848-perth','1848-melbourne','1848-adelaide']){const n=before.get(id).phase.name.map(s=>s.split(' · ')[0]);put(id,[[1849,1901,n,'Колониальный город растёт вместе с торговлей, миграцией и транспортом.|The colonial town grows through trade, migration and transport.|Колониялык шаар соода, көчүү жана транспорт менен бирге өсөт.',null,'settlement'],[1901,1915,n.map((s,i)=>s+[' · Австралийский Союз',' · Commonwealth of Australia',' · Австралия Союзу'][i]),'Город входит в федерацию Австралии; управление штата сохраняется.|The city belongs to the Australian federation; state government continues.|Шаар Австралия федерациясына кирет; штаттык башкаруу сакталат.',null,'settlement']],'Australia');}
 put('aotearoa',[[1849,1860,'Аотеароа · маори и колония|Aotearoa · Māori and colony|Аотеароа · маори жана колония','Разногласия о земле и суверенитете усиливаются; в 1858 году возникает движение Кингитанга.|Disputes over land and sovereignty intensify; the Kīngitanga movement begins in 1858.|Жер жана эгемендик тууралуу талаштар күчөйт; 1858-жылы Кингитанга кыймылы пайда болот.',null,'cultural'],[1860,1872,'Аотеароа · Новозеландские войны|Aotearoa · New Zealand Wars|Аотеароа · Жаңы Зеландия согуштары','Британские и колониальные силы воюют с рядом маорийских объединений; конфискации изменяют землевладение.|British and colonial forces fight several Māori groupings; confiscations transform landholding.|Британ жана колониялык күчтөр маори бирикмелери менен согушат; конфискациялар жер ээлигин өзгөртөт.',null,'cultural'],[1872,1915,'Маори · общины и земельные движения|Māori · communities and land movements|Маори · жамааттар жана жер кыймылдары','Общины сохраняют общественные связи и сопротивляются дальнейшей утрате земель.|Communities maintain social networks and resist further land loss.|Жамааттар коомдук байланыштарын сактап, жерлердин андан ары жоголушуна каршы турат.',null,'cultural']],'NZ');
 const nz=[[[172.6,-34.4],[175,-36],[178.5,-37.6],[177,-39.5],[175.3,-41.6],[173.8,-39],[174,-36.5]],[[172.9,-40.6],[174.4,-41.6],[172.8,-43.4],[170.3,-45.8],[168.2,-46.6],[166.4,-45.9],[168,-43.9],[170.5,-42.2]]];
 put('1914-new-zealand',[[1849,1907,'Новая Зеландия · британская колония|New Zealand · British colony|Жаңы Зеландия · британ колониясы','Колония получает ответственное правительство в 1856 году. В 1893 году женщины получают право голосовать на парламентских выборах.|The colony gains responsible government in 1856. Women gain the parliamentary vote in 1893.|Колония 1856-жылы жооптуу өкмөт түзөт. 1893-жылы аялдар парламенттик шайлоодо добуш берүү укугун алат.',nz,'influence'],[1907,1915,'Доминион Новая Зеландия|Dominion of New Zealand|Жаңы Зеландия доминиону','Колония получает название доминиона; парламентское самоуправление продолжает развиваться в составе Британской империи.|The colony takes the title of dominion; parliamentary self-government continues within the British Empire.|Колония доминион деп аталат; Британ империясынын ичинде парламенттик өз алдынча башкаруу уланат.',nz]],'NZ',{region:'oceania',coord:[173.5,-41.5],color:'#a8916d'});
 put('hawaii',[[1849,1893,'Гавайское королевство|Hawaiian Kingdom|Гавай падышалыгы','Независимая монархия ведёт международную дипломатию; сахарные плантации усиливают влияние иностранных предпринимателей.|The independent monarchy conducts international diplomacy; sugar plantations strengthen foreign business influence.|Көз карандысыз монархия эл аралык дипломатия жүргүзөт; кант плантациялары чет ишкерлердин таасирин күчөтөт.'],[1893,1894,'Гавайи · свержение монархии|Hawaiʻi · overthrow of the monarchy|Гавай · монархиянын кулатылышы','Королева Лилиуокалани свергнута; установлено временное правительство.|Queen Liliʻuokalani is overthrown; a provisional government takes power.|Ханыша Лилиуокалани кулатылат; убактылуу өкмөт бийликке келет.'],[1894,1898,'Республика Гавайи|Republic of Hawaiʻi|Гавай Республикасы','Правительство республики добивается присоединения к США.|The republican government seeks annexation by the USA.|Республикалык өкмөт АКШга кошулууга умтулат.'],[1898,1915,'Гавайи · США|Hawaiʻi · USA|Гавай · АКШ','США аннексируют острова в 1898 году; территориальное управление оформлено в 1900 году.|The USA annexes the islands in 1898; territorial government is established in 1900.|АКШ аралдарды 1898-жылы аннексиялайт; 1900-жылы аймактык башкаруу түзүлөт.',null,'polity','#ad9566']],'Hawaii');
 put('1848-tahiti',[[1849,1880,'Таити · французский протекторат|Tahiti · French protectorate|Таити · француз протектораты','Династия Помаре сохраняет монархию под французской защитой.|The Pōmare dynasty retains a monarchy under French protection.|Помаре династиясы француз коргоосунда монархияны сактайт.'],[1880,1915,'Таити · французская колония|Tahiti · French colony|Таити · француз колониясы','Помаре V уступает суверенитет Франции.|Pōmare V cedes sovereignty to France.|Помаре V эгемендикти Францияга өткөрөт.',null,'polity','#889ab0']],'Pacific');
 put('tonga',[[1849,1875,'Королевство Тонга|Kingdom of Tonga|Тонга падышалыгы','Тупоу I укрепляет единую монархию.|Tupou I consolidates a unified monarchy.|Тупоу I бирдиктүү монархияны бекемдейт.'],[1875,1900,'Тонга · конституционная монархия|Tonga · constitutional monarchy|Тонга · конституциялык монархия','Конституция 1875 года закрепляет устройство королевства.|The 1875 constitution establishes the kingdom’s institutions.|1875-жылкы конституция падышалыктын түзүлүшүн бекитет.'],[1900,1915,'Тонга · британская защита|Tonga · British protection|Тонга · британ коргоосу','Договор устанавливает британскую защиту; местная монархия сохраняется.|A treaty establishes British protection; the local monarchy survives.|Келишим британ коргоосун орнотот; жергиликтүү монархия сакталат.',null,'influence']],'Pacific',{phaseKind:'state'});
 put('samoa',[[1849,1899,'Самоа · местные правительства|Samoa · local governments|Самоа · жергиликтүү башкаруу','Соперничество местных правителей сопровождается вмешательством Германии, Британии и США.|Rival local rulers face intervention by Germany, Britain and the USA.|Жергиликтүү башкаруучулардын атаандаштыгына Германия, Британия жана АКШ кийлигишет.',null,'cultural']],'Pacific');
 put('1914-western-samoa',[[1899,1914,'Западное Самоа · Германия|Western Samoa · Germany|Батыш Самоа · Германия','После соглашения о разделе Германия устанавливает колониальное управление на западных островах в 1900 году.|Following the partition agreement, Germany establishes colonial administration on the western islands in 1900.|Бөлүштүрүү келишиминен кийин Германия 1900-жылы батыш аралдарда колониялык башкаруу орнотот.',box(-172.9,-14.1,-171.3,-13.3),'influence'],[1914,1915,'Западное Самоа · новозеландская оккупация|Western Samoa · New Zealand occupation|Батыш Самоа · Жаңы Зеландия оккупациясы','Новозеландские войска занимают германскую колонию в августе 1914 года.|New Zealand troops occupy the German colony in August 1914.|Жаңы Зеландия аскерлери герман колониясын 1914-жылдын августунда ээлейт.',box(-172.9,-14.1,-171.3,-13.3),'influence']],'Pacific',{region:'oceania',coord:[-171.8,-13.8],color:'#9b8e77'});
 put('1914-american-samoa',[[1899,1915,'Восточное Самоа · США|Eastern Samoa · USA|Чыгыш Самоа · АКШ','США получают восточную сферу по соглашению 1899 года; договоры уступки подписаны в 1900 и 1904 годах.|The USA gains the eastern sphere in the 1899 agreement; deeds of cession follow in 1900 and 1904.|1899-жылкы келишим АКШга чыгыш чөйрөсүн берет; өткөрүү актылары 1900 жана 1904-жылдары түзүлөт.',box(-170.9,-14.5,-169.3,-14.1),'influence']],'Pacific',{region:'oceania',coord:[-170.7,-14.3],color:'#ad9566'});
 put('rapanui',[[1849,1888,'Рапануи · островное общество|Rapa Nui · island society|Рапануи · арал коому','Работорговые набеги 1860-х годов и болезни резко сокращают население.|Slave raids in the 1860s and disease drastically reduce the population.|1860-жылдардагы кул соодагерлердин кол салуулары жана оорулар калкты кескин азайтат.',null,'cultural'],[1888,1915,'Рапануи · чилийская аннексия|Rapa Nui · Chilean annexation|Рапануи · Чили аннексиясы','Чили аннексирует остров; управление пастбищами ограничивает доступ жителей к земле.|Chile annexes the island; ranching administration restricts inhabitants’ access to land.|Чили аралды аннексиялайт; мал чарба башкаруусу тургундардын жерге жетүүсүн чектейт.',null,'cultural']],'Pacific');
 for(const id of ['1789-kodiak','1815-sitka']){const n=id==='1815-sitka'?'Ситка|Sitka|Ситка':'Кадьяк|Kodiak|Кадьяк';put(id,[[1849,1867,n.split('|').map((s,i)=>s+[' · Русская Америка',' · Russian America',' · Орус Америкасы'][i]),'Российско-американская компания управляет поселением и торговлей.|The Russian-American Company administers the settlement and trade.|Орус-Америка компаниясы конушту жана сооданы башкарат.'],[1867,1915,n.split('|').map((s,i)=>s+[' · Аляска, США',' · Alaska, USA',' · Аляска, АКШ'][i]),'После продажи Аляски управление переходит США.|After Alaska’s sale, administration passes to the USA.|Аляска сатылгандан кийин башкаруу АКШга өтөт.']],'Alaska');}
 put('1914-alaska',[[1867,1915,'Аляска · США|Alaska · USA|Аляска · АКШ','Россия уступает Аляску США. Коренные народы сохраняют общества и территории проживания при меняющемся колониальном управлении.|Russia cedes Alaska to the USA. Indigenous peoples maintain communities and homelands under changing colonial administration.|Россия Алясканы АКШга берет. Колониялык башкаруу алмашса да түпкү элдер коомдорун жана жашаган аймактарын сактайт.',[[[-168,65],[-164,70],[-155,71.5],[-145,70],[-141,69.7],[-141,60],[-136,59],[-130,54.7],[-135,57],[-147,60],[-154,57],[-160,55],[-164,55],[-160,59],[-166,61]]],'influence']],'Alaska',{region:'arctic',coord:[-151,64],color:'#ad9566'});
 put('iceland',[[1849,1874,'Исландия · датская монархия|Iceland · Danish monarchy|Исландия · Дания монархиясы','Альтинг действует как совещательный орган; движение за самоуправление растёт.|The Alþingi serves as an advisory body; the movement for self-government grows.|Альтинг кеңеш берүүчү орган катары иштейт; өз алдынча башкаруу кыймылы күчөйт.'],[1874,1904,'Исландия · конституция|Iceland · constitution|Исландия · конституция','Конституция расширяет полномочия Альтинга.|A constitution expands the Alþingi’s powers.|Конституция Альтингдин ыйгарым укуктарын кеңейтет.'],[1904,1915,'Исландия · самоуправление|Iceland · Home Rule|Исландия · өз алдынча башкаруу','Министр по делам Исландии отвечает перед Альтингом и находится в Рейкьявике.|The minister for Iceland is based in Reykjavík and accountable to the Alþingi.|Исландиянын министри Рейкьявикте иштеп, Альтингге жооп берет.']],'Arctic');
 set('1848-franklin',[]);
 put('antarctica',[[1849,1895,'Антарктида · морские исследования|Antarctica · maritime exploration|Антарктида · деңиз изилдөөлөрү','Континент не имеет постоянного населения; морские экспедиции исследуют его побережья.|The continent has no permanent population; maritime expeditions explore its coasts.|Континенттин туруктуу калкы жок; деңиз экспедициялары жээктерин изилдейт.'],[1895,1915,'Антарктида · экспедиции и зимовки|Antarctica · expeditions and wintering|Антарктида · экспедициялар жана кыштоолор','Экспедиции создают временные базы и продвигаются вглубь континента. В 1911 и 1912 годах партии Амундсена и Скотта достигают Южного полюса.|Expeditions establish temporary bases and travel inland. Amundsen’s and Scott’s parties reach the South Pole in 1911 and 1912.|Экспедициялар убактылуу базаларды түзүп, континенттин ичине барат. Амундсен менен Скоттун топтору Түштүк уюлга 1911 жана 1912-жылдары жетет.']],'Polar');
 put('1914-ross-expeditions',[[1901,1915,'Море Росса · полярные экспедиции|Ross Sea · polar expeditions|Росс деңизи · уюл экспедициялары','Зимовочные базы у моря Росса служат отправными пунктами исследований и походов к полюсу.|Wintering bases by the Ross Sea support exploration and journeys to the pole.|Росс деңизинин жээгиндеги кыштоолор изилдөөлөрдүн жана уюлга жортуулдардын баштапкы жайлары болот.',box(162,-84,175,-76),'landscape']],'Polar',{region:'antarctica',kind:'landscape',coord:[166.7,-77.8],color:'#8c9eaa'});
 for(const [id,y,entry,title,text,coord,kind] of [
 ['gold',1851,'1914-australian-colonies','Золотые лихорадки Австралии|Australian gold rushes|Австралиядагы алтын дүрбөлөңү','Открытия золота вызывают массовую миграцию в колонии.|Gold discoveries trigger mass migration to the colonies.|Алтындын табылышы колонияларга массалык көчүүнү пайда кылат.',[143.85,-37.56],'migration'],
 ['australia',1901,'1914-australian-colonies','Федерация Австралии|Australian Federation|Австралия федерациясы','Создан Австралийский Союз из шести колоний.|The Commonwealth of Australia is formed from six colonies.|Алты колониядан Австралия Союзу түзүлөт.',[151.2,-33.86],'politics'],
 ['nz-vote',1893,'1914-new-zealand','Женское избирательное право|Women’s suffrage|Аялдардын шайлоо укугу','Женщины Новой Зеландии получают право голосовать на парламентских выборах.|Women in New Zealand gain the right to vote in parliamentary elections.|Жаңы Зеландиянын аялдары парламенттик шайлоодо добуш берүү укугун алат.',[174.78,-41.29],'politics'],
 ['alaska',1867,'1914-alaska','Передача Аляски|Transfer of Alaska|Алясканын өткөрүлүшү','В Ситке происходит передача управления от России США.|Administration is transferred from Russia to the USA at Sitka.|Ситкада башкаруу Россиядан АКШга өткөрүлөт.',[-135.33,57.05],'diplomacy'],
 ['pole',1911,'1914-ross-expeditions','Амундсен достигает Южного полюса|Amundsen reaches the South Pole|Амундсен Түштүк уюлга жетет','Норвежская партия достигает географического Южного полюса 14 декабря 1911 года.|The Norwegian party reaches the geographical South Pole on 14 December 1911.|Норвегиялык топ географиялык Түштүк уюлга 1911-жылдын 14-декабрында жетет.',[0,-90],'culture'],
 ['scott',1912,'1914-ross-expeditions','Скотт на Южном полюсе|Scott at the South Pole|Скотт Түштүк уюлда','Британская партия достигает полюса 17 января; пятеро участников погибают на обратном пути.|The British party reaches the pole on 17 January; all five members die on the return journey.|Британ тобу уюлга 17-январда жетет; беш катышуучу тең кайтып келе жатып каза болот.',[0,-90],'culture']])event(id,y,entry,title,text,coord,kind);
};
