'use strict';
module.exports=(c,{G,set,source,ring,before,link,geo})=>{
 const coast=require('./to1939-coasts.json'),U=n=>geo.union(coast[n]);
 const put=(id,rows,src,meta={})=>set(id,rows,{...meta,sources:[src]});
 const phase=id=>c.entries.find(e=>e.id===id).phases.filter(p=>p.from>=1919);
 // A common envelope makes the imperial system legible; cards distinguish Crown provinces and princely states.
 const india=geo.merge(['India','Pakistan','Bangladesh'].map(U));
 put('1939-india',[[1919,1937,'Британская Индия · провинции и княжества|British India · provinces and princely states|Британ Индиясы · провинциялар жана княздыктар','Британские провинции и княжества под верховенством короны образуют общую политическую систему. Бирма входит в её состав до 1937 года.|British provinces and princely states under Crown paramountcy form a common political system. Burma remains within it until 1937.|Британ провинциялары менен таажынын үстөмдүгүндөгү княздыктар жалпы саясий тутумду түзөт. Бирма 1937-жылга чейин анын курамында болот.',geo.merge([india,U('Myanmar')]),'influence'],[1937,1940,'Британская Индия · провинции и княжества|British India · provinces and princely states|Британ Индиясы · провинциялар жана княздыктар','Бирма отделена в самостоятельную британскую колонию. В Индии расширена провинциальная автономия, национальное движение требует независимости.|Burma becomes a separate British colony. Provincial autonomy expands in India while the national movement demands independence.|Бирма өзүнчө британ колониясы болот. Индияда провинциялардын автономиясы кеңейип, улуттук кыймыл көз карандысыздыкты талап кылат.',india,'influence']],'India',{coord:[78,24],color:'#b99875'});
 link('1789-great-britain','1939-india',1919,1940,'administration');
 for(const id of ['early-mughal','1789-company-bengal','1789-awadh','1789-gujarat-regional','1789-maratha','1789-south-indian-courts'])link('1939-india',id,1919,1940,'province',false);
 for(const id of ['1789-hyderabad','1789-mysore','1848-kashmir'])link('1939-india',id,1919,1940,'dependency',false);
 put('1789-mysore',[[1919,1940,'Майсур · княжество|Mysore · princely state|Майсур · княздык','Династия Водеяров управляет княжеством под британским верховенством; развиваются образование, гидроэнергетика и промышленность.|The Wodeyar dynasty governs under British paramountcy; education, hydroelectric power and industry develop.|Водеяр династиясы британ үстөмдүгүндө княздыкты башкарат; билим берүү, гидроэнергетика жана өнөр жай өнүгөт.']],'India');
 const sudan=geo.merge([U('Sudan'),U('S. Sudan')]);
 put('1939-sudan',[[1919,1940,'Англо-Египетский Судан|Anglo-Egyptian Sudan|Англия-Мисир Суданы','Кондоминиум Великобритании и Египта находится под преимущественно британским управлением. Северные и южные районы управляются различными административными порядками.|The British-Egyptian condominium is administered predominantly by Britain. Northern and southern districts operate under different administrative arrangements.|Британия менен Мисирдин кондоминионун негизинен Британия башкарат. Түндүк жана түштүк округдарда ар башка административдик тартип колдонулат.',sudan,'influence']],'Africa',{region:'africa',coord:[32.56,15.5]});link('1789-great-britain','1939-sudan',1919,1940,'administration');
 for(const id of ['dongola','early-funj'])link('1939-sudan',id,1919,1940,'province',false);
 for(const[id,n]of [['1914-south-africa','South Africa'],['1914-uganda','Uganda'],['early-algiers','Algeria']]){
  const rows=phase(id).map(p=>[p.from,p.to,p.name,p.text,U(n)]);put(id,rows,'Africa');
 }
 link('1914-south-africa','1848-zulu',1919,1940,'province',false);
 put('1848-ndebele',[[1919,1923,'Южная Родезия · управление компании|Southern Rhodesia · company administration|Түштүк Родезия · компаниянын башкаруусу','Британская Южно-Африканская компания управляет территорией; переселенцы контролируют значительную часть земель.|The British South Africa Company administers the territory; settlers control much of the land.|Британ Түштүк Африка компаниясы аймакты башкарат; жердин кыйла бөлүгүн көчүп келгендер көзөмөлдөйт.',U('Zimbabwe')],[1923,1940,'Южная Родезия · самоуправляющаяся колония|Southern Rhodesia · self-governing colony|Түштүк Родезия · өзүн-өзү башкарган колония','В 1923 году управление компании сменяется самоуправлением поселенческой колонии под британской короной.|In 1923 company administration gives way to settler-colony self-government under the British Crown.|1923-жылы компаниянын башкаруусун британ таажысына караган көчмөндөр колониясынын өз алдынча башкаруусу алмаштырат.',U('Zimbabwe')]],'Africa');link('1789-great-britain','1848-ndebele',1919,1940,'dependency');
 put('1914-namibia',[[1919,1920,'Юго-Западная Африка · южноафриканское управление|South West Africa · South African administration|Түштүк-Батыш Африка · Түштүк Африканын башкаруусу','После войны сохраняется южноафриканское управление бывшей германской колонией.|South African administration of the former German colony continues after the war.|Согуштан кийин мурдагы герман колониясын Түштүк Африка башкарууну улантат.',U('Namibia'),'influence'],[1920,1940,'Юго-Западная Африка · южноафриканский мандат|South West Africa · South African mandate|Түштүк-Батыш Африка · Түштүк Африканын мандаты','Лига Наций утверждает южноафриканский мандат в декабре 1920 года.|The League of Nations approves the South African mandate in December 1920.|Улуттар Лигасы 1920-жылдын декабрында Түштүк Африканын мандатын бекитет.',U('Namibia'),'influence']],'MandatesAfrica');
 for(const id of ['1914-german-east','1939-ruanda']){
  const p=phase(id)[0];p.name=p.name.map(s=>s.replace('мандат','управление').replace('mandate','administration').replace('мандаты','башкаруусу'));p.title=p.name;
  c.areas.find(a=>a.entry===id&&a.from===1919).name=p.name;
 }
 // Close captions inherited from the civil-war year once Soviet administration is established.
 for(const id of ['early-siberian-forts','1789-yenisei-communities','1789-siberian-tatar','1789-siberian-river-centres']){
  const b=before.get(id);put(id,[[1919,1923,b.phase.name,b.phase.text],[1923,1940,b.phase.name,'Сибирские общества входят в советскую административную систему. Коллективизация и промышленное освоение конца 1920-х и 1930-х годов меняют хозяйство и расселение.|Siberian societies enter the Soviet administrative system. Collectivisation and industrial development in the late 1920s and 1930s reshape livelihoods and settlement.|Сибирь коомдору советтик башкаруу тутумуна кирет. 1920-жылдардын аягындагы жана 1930-жылдардагы коллективдештирүү менен өнөр жайды өнүктүрүү чарбаны жана отурукташууну өзгөртөт.']],'USSR');
 }
 const thrace=ring([[24.3,40.85],[25.7,40.8],[26.1,41.3],[25.4,41.7],[24.3,41.5]]),bulgaria=geo.difference(G('1914-bulgaria'),thrace);
 put('1914-bulgaria',[[1919,1940,'Царство Болгария|Tsardom of Bulgaria|Болгария падышалыгы','Нёйиский договор 1919 года лишает Болгарию Западной Фракии и выхода к Эгейскому морю. Южная Добруджа остаётся румынской до 1940 года.|The 1919 Treaty of Neuilly removes Western Thrace and Bulgaria’s Aegean access. Southern Dobruja remains Romanian until 1940.|1919-жылкы Нёйи келишими Болгарияны Батыш Фракиядан жана Эгей деңизине чыгуудан ажыратат. Түштүк Добружа 1940-жылга чейин Румынияда калат.',bulgaria]],'Peace');
 const greece=geo.merge([G('1848-greece'),thrace]);
 put('1848-greece',[[1919,1920,'Королевство Греция|Kingdom of Greece|Греция королдугу','Греческая армия высаживается в Смирне в мае 1919 года; начинается война в Анатолии.|The Greek army lands at Smyrna in May 1919; war begins in Anatolia.|Грек аскерлери 1919-жылдын майында Смирнага түшүп, Анадолуда согуш башталат.'],[1920,1924,'Королевство Греция|Kingdom of Greece|Греция королдугу','Западная Фракия переходит Греции. Поражение в Анатолии в 1922 году завершает греческое продвижение на восток.|Western Thrace passes to Greece. Defeat in Anatolia in 1922 ends the Greek eastward advance.|Батыш Фракия Грецияга өтөт. 1922-жылы Анадолудагы жеңилүү гректердин чыгышка жылышын токтотот.',greece],[1924,1935,'Греческая республика|Greek Republic|Грек Республикасы','В 1924 году провозглашена республика; общество переживает последствия войны и обмена населением.|A republic is proclaimed in 1924; society faces the aftermath of war and the population exchange.|1924-жылы республика жарыяланат; коом согуштун жана калкты алмаштыруунун кесепеттерин баштан өткөрөт.',greece],[1935,1940,'Королевство Греция|Kingdom of Greece|Греция королдугу','Монархия восстановлена в 1935 году; с 1936 года действует диктатура Метаксаса.|The monarchy is restored in 1935; Metaxas establishes a dictatorship in 1936.|Монархия 1935-жылы калыбына келет; 1936-жылы Метаксастын диктатурасы орнойт.',greece]],'Peace');
 // Alsace-Lorraine is returned to France under the Versailles settlement.
 const france=geo.merge([G('late-france'),ring([[6.2,49.5],[7.2,49.2],[8.2,49],[7.8,48],[7.6,47.5],[6.9,47.6],[7,48.5],[6,49]])]);
 put('late-france',[[1919,1940,'Французская республика|French Republic|Француз Республикасы','Третья республика восстанавливается после войны; Эльзас и Лотарингия возвращены Франции. В 1930-е годы экономический кризис усиливает политические конфликты.|The Third Republic rebuilds after the war; Alsace-Lorraine returns to France. Economic crisis intensifies political conflict in the 1930s.|Үчүнчү республика согуштан кийин калыбына келет; Эльзас менен Лотарингия Францияга кайтарылат. 1930-жылдардагы экономикалык кризис саясий жаңжалдарды күчөтөт.',france]],'Peace');
};
