'use strict';
module.exports=(c,{G,set,source,event,box,before,T})=>{
 source('Pecos','Pueblo of Jemez. Pecos; National Park Service. Ancestral Sites Tour: Epilogue.',['https://www.jemezpueblo.org/places/pecos/','https://www.nps.gov/places/ancestral-sites-tour-epilogue.htm']);
 source('Johor','National Library Board Singapore. Mother Island: Finding Singapore’s Past in Pulau Lingga; Sejarah Kesultanan Johor.',['https://biblioasia.nlb.gov.sg/all-sections/vol-17-issue-4-jan-to-mar-2022-pulau-lingga/','https://kemahkotaan.johor.gov.my/pengenalan/sejarah-kesultanan-johor/']);
 source('Afghanistan','National Army Museum. Second Afghan War; Encyclopaedia Iranica. Afghanistan X. Political History.',['https://www.nam.ac.uk/explore/second-afghan-war','https://www.iranicaonline.org/articles/afghanistan-x-political-history/']);
 const put=(id,rows,s,meta={})=>set(id,rows,{sources:['to1914'+s],...meta});
 const one=(id,name,text,s='Africa',kind,geometry)=>put(id,[[1849,1915,name,text,geometry,kind]],s);
 one('1789-great-britain','Соединённое Королевство|United Kingdom|Бириккен Падышалык','Промышленность, морская торговля и колониальная империя расширяются. Парламентские реформы 1867 и 1884 годов увеличивают число избирателей.|Industry, maritime trade and the colonial empire expand. Parliamentary reforms in 1867 and 1884 enlarge the electorate.|Өнөр жай, деңиз соодасы жана колониялык империя кеңейет. 1867 жана 1884-жылкы парламенттик реформалар шайлоочулардын санын көбөйтөт.','Europe');
 one('early-netherlands','Королевство Бельгия|Kingdom of Belgium|Бельгия падышалыгы','Развиваются металлургия, угольная промышленность и железные дороги. В августе 1914 года германская армия вторгается в нейтральную Бельгию.|Metallurgy, coal mining and railways develop. In August 1914 the German army invades neutral Belgium.|Металлургия, көмүр өнөр жайы жана темир жолдор өнүгөт. 1914-жылдын августунда герман аскери бейтарап Бельгияга басып кирет.','Europe');
 one('early-dutch','Королевство Нидерландов|Kingdom of the Netherlands|Нидерланд падышалыгы','Конституционная монархия развивает торговлю и промышленность; колониальная экономика связана с Ост-Индией.|The constitutional monarchy develops commerce and industry; its colonial economy is tied to the East Indies.|Конституциялык монархия сооданы жана өнөр жайды өнүктүрөт; колониялык экономика Ост-Индия менен байланышкан.','Europe');
 put('early-sweden',[[1849,1905,'Швеция · уния с Норвегией|Sweden · union with Norway|Швеция · Норвегия менен уния','Общая монархия связывает два государства с отдельными институтами.|A shared monarchy links two states with separate institutions.|Жалпы монархия өзүнчө мекемелери бар эки мамлекетти байланыштырат.'],[1905,1915,'Королевство Швеция|Kingdom of Sweden|Швеция падышалыгы','После мирного расторжения унии Швеция и Норвегия имеют отдельных монархов.|After peaceful dissolution of the union, Sweden and Norway have separate monarchs.|Уния тынч жол менен токтогондон кийин Швеция менен Норвегиянын өзүнчө монархтары болот.']],'Europe');
 one('early-denmark-norway','Королевство Дания|Kingdom of Denmark|Дания падышалыгы','Конституция 1849 года ограничивает монархию. В войне 1864 года утрачены герцогства Шлезвиг, Гольштейн и Лауэнбург.|The 1849 constitution limits the monarchy. The war of 1864 costs the duchies of Schleswig, Holstein and Lauenburg.|1849-жылкы конституция монархияны чектейт. 1864-жылкы согушта Шлезвиг, Гольштейн жана Лауэнбург герцогдуктары жоголот.','Europe');
 put('1789-russian-empire',[[1849,1861,'Российская империя · Николай I и Александр II|Russian Empire · Nicholas I and Alexander II|Россия империясы · Николай I жана Александр II','Крымская война 1853–1856 годов завершается поражением; начинается подготовка реформ.|The Crimean War of 1853–56 ends in defeat; preparations for reform begin.|1853–1856-жылкы Крым согушу жеңилүү менен аяктайт; реформаларга даярдык башталат.'],[1861,1905,'Российская империя · реформы и расширение|Russian Empire · reform and expansion|Россия империясы · реформалар жана кеңейүү','Крепостное право отменено. Строительство железных дорог и территориальные завоевания меняют хозяйство и общество.|Serfdom is abolished. Railway construction and territorial conquests transform economy and society.|Крепостнойлук жоюлат. Темир жол куруу жана аймактык басып алуулар чарба менен коомду өзгөртөт.'],[1905,1915,'Российская империя · Дума и монархия|Russian Empire · Duma and monarchy|Россия империясы · Дума жана монархия','Революция 1905 года приводит к созданию Государственной думы; император сохраняет широкие полномочия.|The 1905 revolution leads to the State Duma; the emperor retains extensive powers.|1905-жылкы революция Мамлекеттик Думанын түзүлүшүнө алып келет; император кеңири ыйгарым укуктарын сактайт.']],'Europe');
 put('1815-warsaw',[[1849,1863,'Польские земли · Российская империя|Polish lands · Russian Empire|Поляк жерлери · Россия империясы','Имперское управление ограничивает польские политические институты.|Imperial government restricts Polish political institutions.|Империялык башкаруу поляк саясий мекемелерин чектейт.'],[1863,1915,'Польские земли · восстание и русификация|Polish lands · uprising and Russification|Поляк жерлери · көтөрүлүш жана орусташтыруу','Январское восстание подавлено; усиливаются административная интеграция и русификация.|The January Uprising is suppressed; administrative integration and Russification intensify.|Январь көтөрүлүшү басылат; административдик бириктирүү жана орусташтыруу күчөйт.']],'Europe');
 put('1815-finland',[[1849,1906,'Великое княжество Финляндское|Grand Duchy of Finland|Финляндия улуу княздыгы','Финляндия сохраняет отдельные учреждения в Российской империи; ограничения автономии вызывают сопротивление.|Finland retains separate institutions in the Russian Empire; restrictions on autonomy provoke resistance.|Финляндия Россия империясында өзүнчө мекемелерин сактайт; автономиянын чектелиши каршылык жаратат.'],[1906,1915,'Финляндия · парламентская реформа|Finland · parliamentary reform|Финляндия · парламенттик реформа','Учреждён однопалатный парламент с равным избирательным правом мужчин и женщин.|A unicameral parliament is established with equal voting rights for men and women.|Эркектер менен аялдардын тең шайлоо укугу бар бир палаталуу парламент түзүлөт.']],'Europe');
 const greek=G('1848-greece'),thessaly=[[[20.9,39],[22.5,38.8],[23,39.7],[22.3,40.1],[21,40]]],macedonia=[[[20.2,39.5],[20,40.2],[20.6,40.9],[22.5,40.9],[24,41.4],[26,41.3],[26,40.7],[23,39.8],[21.3,39]]];
 put('1848-greece',[[1849,1881,'Королевство Греция|Kingdom of Greece|Греция падышалыгы','В 1863 году королём становится Георг I; Ионические острова присоединены в 1864 году.|George I becomes king in 1863; the Ionian Islands join in 1864.|1863-жылы Георг I падыша болот; 1864-жылы Иония аралдары кошулат.'],[1881,1913,'Греция · Фессалия|Greece · Thessaly|Греция · Фессалия','К Греции переходит большая часть Фессалии и район Арты.|Most of Thessaly and the Arta district pass to Greece.|Фессалиянын көбү жана Арта району Грецияга өтөт.',[...greek,...thessaly]],[1913,1915,'Греция · после Балканских войн|Greece · after the Balkan Wars|Греция · Балкан согуштарынан кийин','Греция получает южную Македонию, южный Эпир и Крит.|Greece gains southern Macedonia, southern Epirus and Crete.|Греция түштүк Македонияны, түштүк Эпирди жана Критти алат.',[...greek,...thessaly,...macedonia,...box(23.5,34.8,26.4,35.7)]]],'Berlin');
 put('1914-bosnia',[[1878,1908,'Босния и Герцеговина · австро-венгерская оккупация|Bosnia and Herzegovina · Austro-Hungarian occupation|Босния жана Герцеговина · Австрия-Венгрия оккупациясы','Австро-Венгрия управляет провинциями при сохраняющемся формальном османском суверенитете.|Austria-Hungary administers the provinces under continuing formal Ottoman sovereignty.|Австрия-Венгрия провинцияларды формалдуу осмон эгемендиги сакталган шартта башкарат.',G('late-ottoman').slice(4,5),'influence'],[1908,1915,'Босния и Герцеговина · Австро-Венгрия|Bosnia and Herzegovina · Austria-Hungary|Босния жана Герцеговина · Австрия-Венгрия','Аннексия 1908 года вызывает международный кризис. В Сараеве в 1914 году убит эрцгерцог Франц Фердинанд.|Annexation in 1908 triggers an international crisis. Archduke Franz Ferdinand is assassinated in Sarajevo in 1914.|1908-жылкы аннексия эл аралык кризис жаратат. 1914-жылы Сараеводо эрцгерцог Франц Фердинанд өлтүрүлөт.',G('late-ottoman').slice(4,5)]],'Berlin',{region:'eurasia',coord:[18.4,43.9],color:'#8b9ba1'});
 put('1914-albania',[[1912,1915,'Албания · независимость|Albania · independence|Албания · көз карандысыздык','Независимость провозглашена во Влёре в 1912 году; международные решения 1913 года устанавливают княжество.|Independence is proclaimed at Vlorë in 1912; international decisions in 1913 establish a principality.|Көз карандысыздык 1912-жылы Влёрада жарыяланат; 1913-жылкы эл аралык чечимдер княздык түзөт.',[[[19.4,42.5],[20.4,42.5],[20.9,41],[20.1,39.7],[19.5,40],[19.4,41.5]]],'influence']],'Berlin',{region:'eurasia',coord:[19.8,41.3],color:'#a58276'});
 put('1914-montenegro',[[1849,1878,'Черногория · княжество|Montenegro · principality|Черногория · княздык','Местное правление сохраняется в горном ядре вокруг Цетине; с 1852 года княжество светское.|Local rule persists around the mountain core of Cetinje; the principality becomes secular in 1852.|Цетиненин айланасындагы тоолуу өзөктө жергиликтүү бийлик сакталат; 1852-жылы княздык светтик болот.',box(18.6,42.3,19.4,43)],[1878,1910,'Независимая Черногория|Independent Montenegro|Көз карандысыз Черногория','Берлинский договор признаёт независимость и территориальные приобретения.|The Treaty of Berlin recognises independence and territorial gains.|Берлин келишими көз карандысыздыкты жана аймактык кеңейүүнү тааныйт.',box(18.5,41.9,20,43.4)],[1910,1915,'Королевство Черногория|Kingdom of Montenegro|Черногория падышалыгы','Провозглашено королевство; оно участвует в Балканских войнах.|A kingdom is proclaimed; it participates in the Balkan Wars.|Падышалык жарыяланат; ал Балкан согуштарына катышат.',box(18.5,41.9,20,43.4)]],'Berlin',{region:'eurasia',coord:[19,42.6],color:'#a59078'});
 put('1789-durrani',[[1849,1880,'Афганистан · Баракзаи|Afghanistan · Barakzais|Ооганстан · Баракзайлар','Дост Мухаммад и его преемники объединяют афганские владения. Вторая англо-афганская война начинается в 1878 году.|Dost Mohammad and his successors unite Afghan domains. The Second Anglo-Afghan War begins in 1878.|Дост Мухаммад жана мураскорлору ооган ээликтерин бириктирет. Экинчи англо-ооган согушу 1878-жылы башталат.'],[1880,1915,'Эмират Афганистан|Emirate of Afghanistan|Ооганстан эмирлиги','Абд ар-Рахман, затем Хабибулла укрепляют центральную власть; внешние сношения ограничены соглашениями с Британией.|Abdur Rahman and then Habibullah strengthen central rule; agreements with Britain restrict foreign relations.|Абд ар-Рахман, андан кийин Хабибулла борбордук бийликти күчөтөт; Британия менен келишимдер тышкы байланыштарды чектейт.']],'Afghanistan');
 one('1789-south-indian-courts','Южная Индия · княжества и британские округа|South India · princely states and British districts|Түштүк Индия · княздыктар жана британ округдары','Британские округа и зависимые княжества имеют разные формы управления; земледелие, ремесло и портовая торговля поддерживают регион.|British districts and dependent princely states have different governments; agriculture, crafts and port trade sustain the region.|Британ округдары менен көз каранды княздыктардын башкаруусу ар башка; аймакты дыйканчылык, кол өнөрчүлүк жана порт соодасы камсыздайт.','India','influence');
 one('1789-hyderabad','Хайдарабад · княжество|Hyderabad · princely state|Хайдарабад · княздык','Низам сохраняет внутреннюю власть при британском верховенстве.|The nizam retains internal authority under British paramountcy.|Низам британ үстөмдүгүндө ички бийлигин сактайт.','India','influence');
 one('1789-mysore','Майсур · княжество|Mysore · princely state|Майсур · княздык','Британское комиссарское управление продолжается до возвращения управления Водеярам в 1881 году.|British commissioner administration continues until government is restored to the Wodeyars in 1881.|Британ комиссарларынын башкаруусу 1881-жылы башкаруу Водеярларга кайтарылганга чейин созулат.','India','influence');
 one('1848-kashmir','Джамму и Кашмир · Догры|Jammu and Kashmir · Dogras|Жамму жана Кашмир · Догралар','Догрские махараджи управляют княжеством при британском верховенстве.|Dogra maharajas govern the princely state under British paramountcy.|Догра махаражалары княздыкты британ үстөмдүгүндө башкарат.','India','influence');
 put('early-johor',[[1849,1855,'Джохор · султан и теменггонг|Johor · sultan and temenggong|Жохор · султан жана теменггонг','Султан и теменггонг соперничают за управление полуостровной частью прежнего султаната.|The sultan and temenggong contest administration of the old sultanate’s peninsular lands.|Султан менен теменггонг мурдагы султандыктын жарым аралдагы жерлерин башкаруу үчүн атаандашат.',box(102.3,1.2,104.3,2.5)],[1855,1914,'Джохор · династия теменггонгов|Johor · temenggong dynasty|Жохор · теменггонгдор династиясы','Теменггонг Ибрахим получает основную часть Джохора; Абу Бакар укрепляет управление и принимает султанский титул в 1885 году.|Temenggong Ibrahim acquires most of Johor; Abu Bakar consolidates government and takes the sultan’s title in 1885.|Теменггонг Ибрахим Жохордун негизги бөлүгүн алат; Абу Бакар башкарууну бекемдеп, 1885-жылы султан наамын алат.',box(102.3,1.2,104.3,2.5)],[1914,1915,'Джохор · британский советник|Johor · British adviser|Жохор · британ кеңешчиси','Султан принимает британского генерального советника.|The sultan accepts a British general adviser.|Султан британ башкы кеңешчисин кабыл алат.',box(102.3,1.2,104.3,2.5),'influence']],'Johor');
 put('1914-riau',[[1849,1911,'Султанат Риау-Линга|Riau-Lingga Sultanate|Риау-Линга султандыгы','Островной султанат существует под голландским влиянием отдельно от Джохора.|The island sultanate exists under Dutch influence, separate from Johor.|Арал султандыгы голланд таасиринде Жохордон өзүнчө жашайт.',box(104,.1,105.1,1.1),'influence'],[1911,1915,'Риау-Линга · Нидерландская Ост-Индия|Riau-Lingga · Netherlands East Indies|Риау-Линга · Нидерланд Ост-Индиясы','Голландские власти низлагают султана и упраздняют султанат.|Dutch authorities depose the sultan and abolish the sultanate.|Голланд бийлиги султанды тактан түшүрүп, султандыкты жоёт.',box(104,.1,105.1,1.1)]],'Johor',{region:'eurasia',coord:[104.5,.5],color:'#a59672'});
 one('1789-bangkok','Королевство Сиам|Kingdom of Siam|Сиам падышалыгы','Монгкут и Чулалонгкорн проводят реформы. Сиам сохраняет независимость, уступая периферийные владения Франции и Британии.|Mongkut and Chulalongkorn pursue reforms. Siam retains independence while ceding peripheral territories to France and Britain.|Монгкут менен Чулалонгкорн реформаларды жүргүзөт. Сиам четки ээликтерин Франция менен Британияга берип, көз карандысыздыгын сактайт.','Indochina');
 put('1789-qasimid',[[1849,1872,'Йемен · османское возвращение и имамы|Yemen · Ottoman return and imams|Йемен · осмондордун кайтышы жана имамдар','Османы возвращаются на побережье; имамы и местные правители сохраняют влияние в горах.|Ottomans return to the coast; imams and local rulers retain influence in the highlands.|Осмондор жээкке кайтып келет; имамдар менен жергиликтүү башкаруучулар тоолордо таасирин сактайт.',null,'influence'],[1872,1911,'Йемен · османское управление и сопротивление|Yemen · Ottoman government and resistance|Йемен · осмон башкаруусу жана каршылык','Османы занимают Сану; зейдитские имамы сопротивляются центральному управлению.|Ottomans occupy Sanaa; Zaydi imams resist central administration.|Осмондор Сананы ээлейт; зайдий имамдар борбордук башкарууга каршы турат.',null,'influence'],[1911,1915,'Йемен · османско-имамское соглашение|Yemen · Ottoman-imam agreement|Йемен · осмон-имам келишими','Договор в Даане закрепляет особые полномочия имама Яхьи в зейдитских районах.|The Treaty of Daan recognises Imam Yahya’s special authority in Zaydi districts.|Даан келишими зайдий райондордо имам Яхьянын өзгөчө бийлигин бекитет.',null,'influence']],'Arabia');
 one('1789-oman','Оман · Аль Бу-Саид|Oman · Al Bu Said|Оман · Ал Бу-Саид','После разделения с Занзибаром в 1861 году Маскат остаётся центром оманского султаната; внутренние области сохраняют собственные силы и союзы.|After separation from Zanzibar in 1861, Muscat remains the sultanate’s centre; inland districts retain local powers and alliances.|1861-жылы Занзибар бөлүнгөндөн кийин Маскат Оман султандыгынын борбору бойдон калат; ички аймактарда жергиликтүү күчтөр жана союздар сакталат.','Arabia');
 for(const id of ['early-manila','early-cebu']){const n=id==='early-manila'?'Манила|Manila|Манила':'Себу|Cebu|Себу';put(id,[[1849,1898,n.split('|').map((s,i)=>s+[' · испанские Филиппины',' · Spanish Philippines',' · испан Филиппини'][i]),'Испанская администрация сталкивается с реформаторскими и революционными движениями.|Spanish administration faces reformist and revolutionary movements.|Испан башкаруусу реформатордук жана революциялык кыймылдарга туш болот.'],[1898,1915,n.split('|').map((s,i)=>s+[' · американские Филиппины',' · American Philippines',' · америкалык Филиппин'][i]),'Испания уступает Филиппины США; филиппинское сопротивление приводит к войне, начавшейся в 1899 году.|Spain cedes the Philippines to the USA; Filipino resistance leads to war beginning in 1899.|Испания Филиппинди АКШга берет; филиппиндердин каршылыгы 1899-жылы башталган согушка алып келет.']],'Caribbean');}
 put('early-guam',[[1849,1898,'Гуам · Испания|Guam · Spain|Гуам · Испания','Колониальное управление связано с местными общинами чаморро.|Colonial administration coexists with local Chamorro communities.|Колониялык башкаруу жергиликтүү чаморро жамааттары менен катар жашайт.',null,'cultural'],[1898,1915,'Гуам · США|Guam · USA|Гуам · АКШ','Испания уступает остров США; устанавливается военно-морская администрация.|Spain cedes the island to the USA; naval administration is established.|Испания аралды АКШга берет; деңиз аскердик башкаруу орнотулат.',null,'influence']],'Caribbean');
 one('cairo','Каир · Мисир|Cairo · Misr|Каир · Мисир','Каир остаётся центром египетского правительства, образования и торговли; после 1882 года находится под британской оккупацией.|Cairo remains the centre of Egyptian government, education and trade; from 1882 it is under British occupation.|Каир Мисирдин өкмөт, билим берүү жана соода борбору бойдон калат; 1882-жылдан британ оккупациясында.','Egypt','settlement');
 put('bornu-late',[[1849,1893,'Борну · аль-Канеми|Bornu · al-Kanemi|Борну · ал-Канеми','Династия аль-Канеми управляет Борну и караванными связями.|The al-Kanemi dynasty governs Bornu and its caravan connections.|Ал-Канеми династиясы Борну менен кербен байланыштарын башкарат.'],[1893,1900,'Борну · Рабих аз-Зубайр|Bornu · Rabih al-Zubayr|Борну · Рабих аз-Зубайр','Рабих завоёвывает Борну и создаёт военную державу в бассейне озера Чад.|Rabih conquers Bornu and establishes a military power in the Lake Chad basin.|Рабих Борнуну басып алып, Чад көлүнүн алабында аскердик держава түзөт.'],[1900,1915,'Борну · колониальный раздел|Bornu · colonial partition|Борну · колониялык бөлүштүрүү','После гибели Рабиха регион разделён между колониальными державами; власть шеху восстанавливается под их контролем.|After Rabih’s death, colonial powers partition the region; the shehu’s authority is restored under their control.|Рабих өлгөндөн кийин колониялык державалар аймакты бөлүшөт; шехунун бийлиги алардын көзөмөлүндө калыбына келет.',null,'influence']],'Africa');
 const transfer=(id,at,after,s='Africa')=>{const b=before.get(id),name=b.phase.name||b.entry.name;put(id,[[1849,at,name,'Местные правители и общины сохраняют управление и региональные связи.|Local rulers and communities retain government and regional networks.|Жергиликтүү башкаруучулар менен жамааттар башкарууну жана аймактык байланыштарды сактайт.'],[at,1915,after,'Колониальная власть изменяет управление и землепользование; местные общества продолжают свою историю.|Colonial rule changes administration and land use; local societies continue their history.|Колониялык бийлик башкарууну жана жер пайдаланууну өзгөртөт; жергиликтүү коомдор тарыхын улантат.',null,'influence'] ],s);};
 transfer('mali',1898,'Манден · Французский Судан|Manden · French Sudan|Манден · Француз Суданы');
 transfer('kanem',1900,'Канем · французское продвижение|Kanem · French expansion|Канем · француз кеңейиши');
 transfer('1789-rozvi',1890,'Шона · колониальное завоевание|Shona · colonial conquest|Шона · колониялык басып алуу');
 transfer('1789-xhosa',1879,'Коса · Капская колония|Xhosa · Cape Colony|Коса · Кап колониясы');
 transfer('1789-sakalava',1896,'Сакалава · французский Мадагаскар|Sakalava · French Madagascar|Сакалава · француз Мадагаскары');
 transfer('1789-luba',1891,'Луба · колониальное продвижение|Luba · colonial expansion|Луба · колониялык кеңейүү');
 transfer('1789-lunda',1891,'Лунда · колониальный раздел|Lunda · colonial partition|Лунда · колониялык бөлүштүрүү');
 transfer('1789-kuba',1900,'Куба · колониальное подчинение|Kuba · colonial subordination|Куба · колониялык баш ийүү');
 transfer('mogadishu-late',1892,'Могадишо · итальянское управление|Mogadishu · Italian administration|Могадишо · Италия башкаруусу');
 transfer('early-mombasa',1895,'Момбаса · Британская Восточная Африка|Mombasa · British East Africa|Момбаса · Британ Чыгыш Африкасы');
 transfer('kilwa',1891,'Килва · Германская Восточная Африка|Kilwa · German East Africa|Килва · Герман Чыгыш Африкасы');
 for(const id of ['1789-matamba','mutapa-late'])one(id,id==='1789-matamba'?'Матамба · местные общества и португальское продвижение|Matamba · local societies and Portuguese expansion|Матамба · жергиликтүү коомдор жана португал кеңейиши':'Северное плато · общины у Замбези|Northern plateau · Zambezi communities|Түндүк плато · Замбези жамааттары','Местные центры власти и общины сталкиваются с военным и хозяйственным продвижением колониальных держав.|Local centres of authority and communities face military and economic expansion by colonial powers.|Жергиликтүү бийлик борборлору менен жамааттар колониялык державалардын аскердик жана чарбалык кеңейишине туш болот.','Africa','cultural');
 one('kongo-late','Конго · монархия и португальское управление|Kongo · monarchy and Portuguese administration|Конго · монархия жана португал башкаруусу','Монархия сохраняется при возрастающем португальском вмешательстве; восстание 1913–1914 годов завершает прежнюю политическую систему.|The monarchy survives under increasing Portuguese intervention; the 1913–14 uprising ends the previous political system.|Монархия португал кийлигишүүсү күчөгөн шартта сакталат; 1913–1914-жылкы көтөрүлүш мурдагы саясий түзүлүштү аяктатат.','Africa','influence');
 for(const id of ['1789-luanda','1789-benguela','early-mozambique'])one(id,(before.get(id).phase.name||before.get(id).entry.name).map((s,i)=>s.split(' · ')[0]+[' · португальское управление',' · Portuguese administration',' · португал башкаруусу'][i]),'Порт служит колониальным административным и торговым центром; внутренние области подчиняются в ходе военных кампаний.|The port serves as a colonial administrative and commercial centre; inland districts are subdued through military campaigns.|Порт колониялык башкаруу жана соода борбору болот; ички аймактар аскердик жортуулдарда баш ийдирилет.','Africa','settlement');
 one('madagascar','Мадагаскар и Коморы · островные общества|Madagascar and the Comoros · island societies|Мадагаскар жана Комор · арал коомдору','Французское колониальное расширение меняет политическую власть; местные общества сохраняют языки, религиозные и хозяйственные традиции.|French colonial expansion changes political authority; local societies retain languages, religious and economic traditions.|Француз колониялык кеңейиши саясий бийликти өзгөртөт; жергиликтүү коомдор тилдерин, диний жана чарбалык салттарын сактайт.','Africa','cultural');
 one('pecos','Пекос · родовой исторический центр|Pecos · ancestral historic place|Пекос · ата-бабалардын тарыхый жайы','Последние жители переселились в Хемес в 1838 году. Потомки сохраняют связь с Пекосом и его традициями.|The last residents moved to Jemez in 1838. Descendants maintain ties to Pecos and its traditions.|Акыркы тургундар 1838-жылы Хемеске көчкөн. Урпактары Пекос жана анын салттары менен байланышын сактайт.','Pecos','landscape');
 one('riogrande-pueblos','Пуэбло Рио-Гранде|Rio Grande Pueblos|Рио-Гранде пуэблолору','Общины сохраняют традиции и земельные права в условиях американского управления.|Communities maintain traditions and land claims under US administration.|Жамааттар АКШнын башкаруусунда салттарын жана жер укуктарын сактайт.','Indigenous','cultural');
 for(const id of ['early-purepecha-communities','early-tlaxcala','early-itza','mixtec','cholula'])one(id,before.get(id).phase.name||before.get(id).entry.name,'Общины участвуют в жизни независимой Мексики; реформы собственности и политические конфликты меняют их положение.|Communities participate in independent Mexico; property reforms and political conflicts reshape their position.|Жамааттар көз карандысыз Мексиканын жашоосуна катышат; менчик реформалары жана саясий жаңжалдар алардын абалын өзгөртөт.','Mexico',id==='cholula'?'settlement':'cultural');
 one('caddo','Каддо · переселение и общины|Caddo · relocation and communities|Каддо · көчүрүү жана жамааттар','Давление поселенцев ведёт к переселению из Техаса на Индейскую территорию в 1859 году.|Settler pressure leads to removal from Texas to Indian Territory in 1859.|Конушчулардын басымы 1859-жылы Техастан Индей аймагына көчүрүүгө алып келет.','Indigenous','cultural');
 put('caddo',[[1849,1859,'Каддо · Техас|Caddo · Texas|Каддо · Техас','Общины сталкиваются с давлением поселенцев.|Communities face settler pressure.|Жамааттар конушчулардын басымына туш болот.',null,'cultural'],[1859,1915,'Каддо · Индейская территория|Caddo · Indian Territory|Каддо · Индей аймагы','Каддо переселены из Техаса в район Уошито; общественная и культурная жизнь продолжается.|Caddo people are removed from Texas to the Washita region; social and cultural life continues.|Каддо эли Техастан Уошито аймагына көчүрүлөт; коомдук жана маданий жашоо уланат.',box(-98.8,34.8,-98,35.6),'cultural',null,[-98.4,35.2]]],'Indigenous');
 for(const id of ['1789-usa','1789-canada','1914-australian-colonies']){const entry=c.entries.find(e=>e.id===id);for(const p of entry.phases.filter(p=>p.from>=1849))p.learning={government:T('Власть и участие: сопоставьте государственное устройство с тем, кто имел право голоса.|Power and participation: compare government institutions with who was entitled to vote.|Бийлик жана катышуу: мамлекеттик түзүлүштү добуш берүү укугу кимде болгону менен салыштырыңыз.'),economy:T('Железные дороги, переселение и земельная политика меняли расположение городов и хозяйственные связи.|Railways, migration and land policy reshaped towns and economic connections.|Темир жолдор, көчүү жана жер саясаты шаарлардын жайгашуусун жана чарбалык байланыштарды өзгөрткөн.'),society:T('Политические границы не означали исчезновения коренных народов и их общин.|Political boundaries did not mean the disappearance of Indigenous peoples and communities.|Саясий чек аралар түпкү элдер менен алардын жамааттарынын жоголушун билдирген эмес.')};}
 // Political status follows the phase, rather than an archaeological entry's old category.
 for(const e of c.entries)for(const p of e.phases.filter(p=>p.from>=1849)){
  const area=c.areas.find(a=>a.entry===e.id&&a.from===p.from);
  if(area?.kind==='cultural')p.kind='community';
  if(['pecos','1914-ross-expeditions'].includes(e.id))p.kind='landscape';
 }
};
