'use strict';
module.exports=(c,{T,G,set,source,event,ring,box,before})=>{
 source('Revolution','Президентская библиотека. 1917 год: документы революции.','https://www.prlib.ru/collection_1917');
 source('CivilWar','Foreign Relations of the United States, 1918, Russia, Volume II: Siberia and Allied intervention.','https://history.state.gov/historicaldocuments/frus1918Russiav02/ch1');
 source('Habsburg','Schloß Schönbrunn. Die Welt der Habsburger: The End of the War; Decline and Fall.',['https://ww1.habsburger.net/en/stories/end-war','https://www.habsburger.net/en/stories/decline-and-fall']);
 source('Finland','National Library of Finland. The Finnish Civil War and Independence.','https://www.kansalliskirjasto.fi/en/content/finnish-civil-war-and-independence');
 source('Poland','Institute of National Remembrance. Fighting Poland: independence and the Versailles order.','https://ipn.gov.pl/download/1/374532/RzeczpospolitaWalczacawIIwojnieEN.pdf');
 source('Latvia','Ministry of Foreign Affairs of Latvia. Independent Latvia, 1918–1940.','https://www.mfa.gov.lv/lv/media/2001/download');
 source('WesternFront','National Army Museum. First World War: Western Front; Imperial War Museums. First World War Galleries.',['https://ww1.nam.ac.uk/learning/western-front/','https://www.iwm.org.uk/sites/default/files/files/2023-10/first_world_war_large_print_guide.pdf']);
 const put=(id,rows,src,meta={})=>set(id,rows,{...meta,sources:[...new Set([...(before.get(id)?.phase.sources||[]),'to1918'+src])]});
 const empire='Российская империя|Russian Empire|Россия империясы',russianWar='Война истощает экономику и армию. В 1915 году Польша и часть западных губерний заняты Центральными державами.|War strains the economy and army. In 1915 the Central Powers occupy Poland and parts of the western provinces.|Согуш экономика менен армияны алсыратат. 1915-жылы Борбордук державалар Польшаны жана батыш губерниялардын бир бөлүгүн ээлейт.';
 put('1789-russian-empire',[[1915,1917,empire,russianWar],[1917,1918,'Россия · революции 1917 года|Russia · revolutions of 1917|Россия · 1917-жылдагы революциялар','Николай II отрекается в марте. Временное правительство сменяется большевистским Совнаркомом в ноябре. Возникают национальные правительства и вооружённые центры власти.|Nicholas II abdicates in March. The Provisional Government is displaced by the Bolshevik Council of People’s Commissars in November. National governments and armed centres of power emerge.|Николай II мартта тактан баш тартат. Ноябрда Убактылуу өкмөттү большевиктик Эл комиссарлар кеңеши алмаштырат. Улуттук өкмөттөр жана куралдуу бийлик борборлору пайда болот.',ring([[29,59],[33,61],[44,61],[50,57],[50,51],[43,48],[36,50],[31,54]]),'influence']],'Revolution');
 put('1918-soviet-russia',[[1918,1919,'Советская Россия · центральные области|Soviet Russia · central regions|Советтик Россия · борбордук аймактар','Брестский мир выводит Россию из мировой войны. Правительство переносится в Москву; Красная армия борется с антибольшевистскими силами. Область показывает центральное ядро советской власти в ходе войны.|The Treaty of Brest-Litovsk takes Russia out of the world war. The government moves to Moscow; the Red Army fights anti-Bolshevik forces. The area marks the central base of Soviet power during the war.|Брест тынчтыгы Россияны дүйнөлүк согуштан чыгарат. Өкмөт Москвага көчөт; Кызыл армия большевиктерге каршы күчтөр менен согушат. Аймак согуштагы совет бийлигинин борбордук өзөгүн көрсөтөт.',ring([[28.2,59.3],[30,61],[36,62.5],[43,61],[50,58],[51,54],[49,50],[43,48],[38,49],[33,52],[31,55]]),'influence','#a76b63']],'Revolution',{coord:[37.62,55.75]});
 put('1918-siberia',[[1918,1919,'Сибирь · антибольшевистские правительства|Siberia · anti-Bolshevik governments|Сибирь · большевиктерге каршы өкмөттөр','После выступления Чехословацкого корпуса меняется контроль над Транссибирской магистралью. В Омске сменяются Сибирское правительство, Директория и с ноября власть Колчака. На Дальнем Востоке действуют союзные войска и самостоятельные вооружённые группы.|The Czechoslovak Legion’s uprising changes control of the Trans-Siberian Railway. Omsk passes through the Siberian government and Directory to Kolchak’s rule in November. Allied troops and independent armed groups operate in the Far East.|Чехословак корпусунун көтөрүлүшүнөн кийин Транссибирь темир жолундагы көзөмөл өзгөрөт. Омскиде Сибирь өкмөтүн Директория, ноябрда Колчактын бийлиги алмаштырат. Ыраакы Чыгышта союздаш аскерлер жана өз алдынча куралдуу топтор аракеттенет.',ring([[58,57],[70,58],[85,58],[100,57],[114,54],[130,52],[137,50],[131,43],[120,49.5],[110,49],[102,50.5],[92,52],[82,51],[73,53],[65,54],[59,54]]),'influence','#8393a4']],'CivilWar',{coord:[73.37,54.99]});
 for(const id of ['early-siberian-forts','1789-siberian-tatar','1789-siberian-river-centres','1789-yenisei-communities']){const b=before.get(id);put(id,[[1915,1917,b.phase.name.join('|'),b.phase.text.join('|')],[1917,1919,b.phase.name.map(n=>n.replace(' · Russian Empire','').replace(' · Российская империя','').replace(' · Россия империясы','')).join('|'),'Смена власти, мобилизации и Гражданская война затрагивают города, речные поселения и местные общества.|Changes of power, mobilisation and civil war affect towns, river settlements and local societies.|Бийликтин алмашуусу, мобилизация жана Жарандык согуш шаарларга, дарыя боюндагы конуштарга жана жергиликтүү коомдорго таасир этет.',null,'cultural']],'CivilWar');}
 put('1815-finland',[[1915,1917,'Великое княжество Финляндское|Grand Duchy of Finland|Финляндия улуу княздыгы','Финляндия сохраняет особое положение в составе России.|Finland retains its distinct position within Russia.|Финляндия Россиянын курамында өзгөчө макамын сактайт.'],[1917,1918,'Финляндия · независимость|Finland · independence|Финляндия · көз карандысыздык','6 декабря парламент принимает декларацию независимости.|Parliament adopts the declaration of independence on 6 December.|6-декабрда парламент көз карандысыздык декларациясын кабыл алат.'],[1918,1919,'Финляндия · Гражданская война|Finland · Civil War|Финляндия · Жарандык согуш','В январе–мае воюют красные и белые. Победа белых сопровождается репрессиями и лагерями; государственное устройство остаётся предметом спора.|Reds and Whites fight from January to May. White victory is followed by repression and prison camps; the form of government remains contested.|Январь–майда кызылдар менен актар согушат. Актардын жеңишинен кийин репрессиялар жана лагерлер орун алат; мамлекеттик түзүлүш боюнча талаш уланат.']],'Finland');
 put('1815-warsaw',[[1915,1918,'Польские земли · германская и австрийская оккупация|Polish lands · German and Austrian occupation|Поляк жерлери · герман жана австрия оккупациясы','После русского отступления польские земли управляются оккупационными властями; в 1916 году провозглашено подконтрольное королевство.|After the Russian retreat, occupation authorities govern the Polish lands; a dependent kingdom is proclaimed in 1916.|Орус аскерлери чегингенден кийин поляк жерлерин оккупациялык бийликтер башкарат; 1916-жылы көз каранды падышалык жарыяланат.',null,'influence','#8c8498'],[1918,1919,'Польша · восстановление государства|Poland · restored state|Польша · мамлекеттин калыбына келиши','В ноябре формируется независимая польская власть. Варшава и Краков становятся центрами объединения; границы ещё определяются войнами и переговорами.|Independent Polish authority takes shape in November. Warsaw and Kraków become centres of unification; borders are still being decided through war and negotiation.|Ноябрда көз карандысыз поляк бийлиги түзүлөт. Варшава менен Краков биригүүнүн борборлору болот; чек аралар согуш жана сүйлөшүүлөр аркылуу аныкталат.',ring([[18.3,53],[21.5,53.7],[23.8,53],[23.5,51],[22,49.4],[19,49.5],[18.2,51]]),'influence','#b38d83']],'Poland');
 put('1789-belarus-russia',[[1915,1918,'Литва и Беларусь · война и оккупация|Lithuania and Belarus · war and occupation|Литва жана Беларусь · согуш жана оккупация','Фронт и оккупационные режимы разделяют регион; в 1917 году возникают национальные советы.|The front and occupation regimes divide the region; national councils emerge in 1917.|Фронт жана оккупациялык режимдер аймакты бөлөт; 1917-жылы улуттук кеңештер пайда болот.',null,'influence'],[1918,1919,'Беларусь · провозглашение БНР|Belarus · BNR declaration|Беларусь · БЭРдин жарыяланышы','Белорусская Народная Республика провозглашает независимость в марте при германской оккупации. Собственный контроль над территорией ограничен; в конце года наступают советские силы.|The Belarusian Democratic Republic declares independence in March under German occupation. Its territorial control is limited; Soviet forces advance late in the year.|Беларусь Эл Республикасы мартта герман оккупациясынын тушунда көз карандысыздык жарыялайт. Анын аймактык көзөмөлү чектелүү; жыл аягында совет аскерлери чабуул коёт.',box(25.8,52,30.5,55.5),'influence']],'Revolution');
 const formation='После распада имперского порядка создаются национальные органы власти. Провозглашение государства сопровождается войной за фактический контроль.|National institutions form as the imperial order collapses. State proclamation is accompanied by war over effective control.|Империялык түзүлүш кулагандан кийин улуттук бийлик органдары түзүлөт. Мамлекет жарыялоо аймакты иш жүзүндө көзөмөлдөө үчүн согуш менен коштолот.';
 for(const [id,name,coord,poly] of [['estonia','Эстония|Estonia|Эстония',[24.75,59.44],[[23,57.6],[27.5,57.6],[28,59.6],[23,59.8]]],['latvia','Латвия|Latvia|Латвия',[24.1,56.95],[[21,56.1],[24,56],[27.7,55.7],[28.1,57],[26,57.9],[23,57.8],[21,57.5]]],['lithuania','Литва|Lithuania|Литва',[25.28,54.68],[[22.7,54.4],[25.8,54.1],[26.5,55.6],[25,56.2],[22,56.3],[21.2,55.8]]]])put('1918-'+id,[[1918,1919,name,formation,ring(poly),'influence']],id==='latvia'?'Latvia':'Poland',{coord});
 put('late-hre',[[1915,1918,'Германская империя|German Empire|Герман империясы','Германия воюет на Западном и Восточном фронтах. Блокада, потери и нехватка продовольствия усиливают кризис.|Germany fights on the Western and Eastern fronts. Blockade, losses and food shortages deepen the crisis.|Германия Батыш жана Чыгыш фронттордо согушат. Блокада, жоготуулар жана азык-түлүк тартыштыгы кризисти күчөтөт.'],[1918,1919,'Германия · революция и перемирие|Germany · revolution and armistice|Германия · революция жана жарашуу','В ноябре монархия падает и провозглашается республика. Перемирие 11 ноября прекращает боевые действия на Западном фронте; мирный договор ещё не подписан.|The monarchy falls and a republic is proclaimed in November. The armistice of 11 November ends fighting on the Western Front; the peace treaty has not yet been signed.|Ноябрда монархия кулап, республика жарыяланат. 11-ноябрдагы жарашуу Батыш фронтундагы салгылашууну токтотот; тынчтык келишимине али кол коюла элек.']],'WesternFront');
 for(const id of ['early-austria','early-royal-hungary','early-transylvania']){const b=before.get(id);put(id,[[1915,1918,b.phase.name.join('|'),'Война усиливает продовольственный кризис и национальные движения в монархии.|War intensifies the food crisis and national movements in the monarchy.|Согуш монархиядагы азык-түлүк кризисин жана улуттук кыймылдарды күчөтөт.']],'Habsburg');}
 const newStates=[['austria','Австрия · республика|Austria · republic|Австрия · республика',[16.37,48.21],[[9.6,47],[12,47],[13.8,46.6],[16.1,46.7],[16.9,48],[15.7,48.8],[13.7,48.7],[12,47.7],[10,47.6]]],['hungary','Венгрия · республика|Hungary · republic|Венгрия · республика',[19.04,47.5],[[16.5,46.1],[18,45.8],[20.5,46],[22.7,47.7],[21,48.5],[18.8,48.1],[16.8,48]]],['czechoslovakia','Чехословакия · образование|Czechoslovakia · formation|Чехословакия · түзүлүшү',[14.42,50.08],[[12.1,50],[14.5,51],[16.6,50.4],[18.3,49.5],[18,48.6],[16,48.6],[14.5,48.5],[12.7,49]]]];
 for(const [id,name,coord,poly] of newStates)put('1918-'+id,[[1918,1919,name,'Осенью 1918 года возникают новые правительства. Показано региональное ядро; спорные области и окончательные границы определяются после войны.|New governments emerge in autumn 1918. The regional core is shown; disputed areas and final borders are settled after the war.|1918-жылдын күзүндө жаңы өкмөттөр түзүлөт. Аймактын өзөгү көрсөтүлгөн; талаштуу жерлер жана акыркы чек аралар согуштан кийин аныкталат.',ring(poly),'influence']],'Habsburg',{coord});
 put('1914-serbia',[[1915,1918,'Сербия · оккупация и армия в изгнании|Serbia · occupation and army in exile|Сербия · оккупация жана сүргүндөгү армия','Центральные державы оккупируют Сербию в 1915 году. Сербская армия отступает через Албанию и возвращается на Балканы в составе союзных сил.|The Central Powers occupy Serbia in 1915. The Serbian army retreats through Albania and returns to the Balkans with Allied forces.|Борбордук державалар Сербияны 1915-жылы ээлейт. Серб аскери Албания аркылуу чегинип, союздаш күчтөрдүн курамында Балканга кайтып келет.',null,'influence']],'Habsburg');
 put('1918-scs',[[1918,1919,'Королевство сербов, хорватов и словенцев|Kingdom of Serbs, Croats and Slovenes|Сербдердин, хорваттардын жана словендердин падышалыгы','1 декабря провозглашено объединённое королевство. Южнославянские земли бывшей Австро-Венгрии объединяются с Сербией; пограничные споры продолжаются.|A united kingdom is proclaimed on 1 December. South Slav lands of former Austria-Hungary unite with Serbia; border disputes continue.|1-декабрда бириккен падышалык жарыяланат. Мурдагы Австрия-Венгриянын түштүк славян жерлери Сербия менен биригет; чек ара талаштары уланат.',ring([[13.6,45.7],[14,46.5],[16.5,46.8],[18,45.8],[20,46.2],[22.7,44.2],[22.4,42.5],[23,41.5],[22.5,40.9],[20.5,40.9],[19.5,42.5],[17.5,43],[15,44.5]]),'influence','#9d8095']],'Habsburg',{coord:[20.46,44.81]});
 for(const id of ['1914-bosnia','1914-montenegro']){const b=before.get(id);put(id,[[1915,1918,b.phase.name.join('|'),'Регион охвачен войной и военным управлением Центральных держав.|The region is affected by war and Central Powers military rule.|Аймак согушка жана Борбордук державалардын аскердик башкаруусуна туш болот.']],'Habsburg');}
 event('abdication',1917,'1789-russian-empire','Падение российской монархии|Fall of the Russian monarchy|Россия монархиясынын кулашы','В марте 1917 года Николай II отрекается от престола. Власть переходит к Временному правительству при растущем влиянии советов.|Nicholas II abdicates in March 1917. Power passes to the Provisional Government while the soviets gain influence.|1917-жылдын мартында Николай II тактан баш тартат. Советтердин таасири өсүп, бийлик Убактылуу өкмөткө өтөт.',[30.32,59.94],['Revolution']);
 event('omsk',1918,'1918-siberia','Переворот в Омске|Omsk coup|Омскидеги төңкөрүш','18 ноября Колчак становится верховным правителем после переворота. Его власть оспаривают советские силы и другие вооружённые группы.|Kolchak becomes Supreme Ruler after the coup of 18 November. Soviet forces and other armed groups challenge his authority.|18-ноябрдагы төңкөрүштөн кийин Колчак жогорку башкаруучу болот. Анын бийлигине совет күчтөрү жана башка куралдуу топтор каршы чыгат.',[73.37,54.99],['CivilWar']);
 event('armistice',1918,'late-france','Компьенское перемирие|Armistice of Compiègne|Компьен жарашуусу','11 ноября прекращаются боевые действия между Германией и союзниками на Западном фронте. Войны в Восточной Европе продолжаются.|Fighting between Germany and the Allies on the Western Front ends on 11 November. Wars in Eastern Europe continue.|11-ноябрда Германия менен союздаштардын Батыш фронтундагы согушу токтойт. Чыгыш Европада согуштар уланат.',[2.906,49.427],['WesternFront'],'diplomacy');
 event('somme',1916,'late-france','Битва на Сомме|Battle of the Somme|Сомма салгылашуусу','С июля по ноябрь британские и французские армии наступают на германские позиции. Массовые потери показывают цену войны на истощение.|British and French armies attack German positions from July to November. Heavy losses reveal the cost of attritional warfare.|Июлдан ноябрга чейин британ жана француз аскерлери герман турумдарына чабуул коёт. Чоң жоготуулар алсыратуу согушунун кесепетин көрсөтөт.',[2.7,50],['WesternFront'],'war');
};
