'use strict';
module.exports=(c,{G,set,end,source,event,ring,box,link,geo})=>{
 const coast=require('./to1945-coasts.json'),U=n=>geo.union(coast[n]),M=(...p)=>geo.merge(p),D=(a,b)=>geo.difference(a,b);
 source('Europe','United States Holocaust Memorial Museum. World War II: Key Dates; German Invasion of Western Europe; World War II in Eastern Europe.',['https://encyclopedia.ushmm.org/content/en/article/world-war-ii-key-dates','https://encyclopedia.ushmm.org/content/en/article/german-invasion-of-western-europe-may-1940','https://encyclopedia.ushmm.org/content/en/article/world-war-ii-in-eastern-europe-1942-1945']);
 source('Potsdam','Protocol of the Berlin Conference, 1945; Office of the Historian. The Potsdam Conference, 1945.',['https://history.state.gov/milestones/1937-1945/potsdam-conf']);
 source('France','Imperial War Museums. The Fall of France; D-Day and the Battle of Normandy.',['https://www.iwm.org.uk/history/the-fall-of-france','https://www.iwm.org.uk/history/the-10-things-you-need-to-know-about-d-day']);
 source('East','United States Holocaust Memorial Museum. Invasion of the Soviet Union, June 1941; The Eastern Front; The Holocaust and World War II.',['https://encyclopedia.ushmm.org/content/en/article/invasion-of-the-soviet-union-june-1941','https://encyclopedia.ushmm.org/content/en/article/the-eastern-front-the-german-war-against-the-soviet-union','https://encyclopedia.ushmm.org/content/en/article/the-holocaust-and-world-war-ii-key-dates']);
 const P=(id,rows,src='Europe',meta={})=>set(id,rows,{sources:[src],...meta});
 const normal='После освобождения восстанавливается государственное управление.|State administration is restored after liberation.|Бошотулгандан кийин мамлекеттик башкаруу калыбына келет.';
 const occupied='Германская оккупация; правительство в изгнании продолжает деятельность.|German occupation; a government in exile continues its work.|Германиянын оккупациясы; сүргүндөгү өкмөт ишин улантат.';
 for(const[id,n,country,lib]of [
  ['early-denmark-norway','Дания|Denmark|Дания','Denmark',1945],['1815-norway','Норвегия|Norway|Норвегия','Norway',1945],
  ['early-netherlands','Бельгия|Belgium|Бельгия','Belgium',1944],['early-dutch','Нидерланды|Netherlands|Нидерланддар','Netherlands',1945]
 ])P(id,[[1940,lib,n.split('|').map((x,i)=>x+[' · оккупация',' · occupation',' · оккупация'][i]),occupied,U(country),'influence'],[lib,1946,n,normal,U(country)]]);
 for(const[id,to]of [['early-denmark-norway',1945],['1815-norway',1945],['early-netherlands',1944],['early-dutch',1945]])link('late-hre',id,1940,to,'occupation',false);
 const france=U('France'),south=geo.union(require('../vendor/polygon-clipping.cjs').intersection(geo.multi(france),geo.multi(ring([[-2,43],[8,41],[8,45.7],[5.5,46.4],[3,46.7],[.5,46.2],[-.3,43]]))).flatMap(p=>p.map(r=>r.slice(0,-1))));
 P('late-france',[[1940,1942,'Франция · оккупированная зона|France · occupied zone|Франция · оккупацияланган аймак','Север и Атлантическое побережье оккупированы. Режим Виши управляет южной зоной.|The north and Atlantic coast are occupied. Vichy governs the southern zone.|Түндүк жана Атлантика жээги оккупацияланган. Түштүк аймакты Виши башкарат.',D(france,south),'influence'],[1942,1944,'Франция · оккупация|France · occupation|Франция · оккупация','В ноябре 1942 года германские и итальянские войска занимают южную зону.|German and Italian forces occupy the southern zone in November 1942.|1942-жылдын ноябрында немис жана италиялык аскерлер түштүк аймакты ээлейт.',france,'influence'],[1944,1946,'Франция · Временное правительство|France · Provisional Government|Франция · Убактылуу өкмөт','Высадки союзников и Сопротивление приводят к освобождению большей части страны в 1944 году. Отдельные прибрежные гарнизоны капитулируют в 1945 году.|Allied landings and the Resistance liberate most of the country in 1944. Some coastal garrisons surrender in 1945.|Союздаштардын десанттары жана Каршылык кыймылы 1944-жылы өлкөнүн көп бөлүгүн бошотот. Айрым жээк гарнизондору 1945-жылы багынат.',france]],'France');
 P('1945-vichy',[[1940,1942,'Виши · южная зона|Vichy · southern zone|Виши · түштүк аймак','Авторитарный режим сотрудничает с нацистской Германией.|The authoritarian regime collaborates with Nazi Germany.|Авторитардык режим нацисттик Германия менен кызматташат.',south,'influence']],'France',{coord:[3.42,46.13],color:'#b59a80'});
 link('late-hre','late-france',1940,1944,'occupation',false);
 P('late-hre',[[1940,1945,'Германский рейх|German Reich|Герман рейхи','Нацистская Германия ведёт захватническую войну и осуществляет Холокост. Оккупированные страны показаны отдельно от территории рейха.|Nazi Germany wages a war of conquest and perpetrates the Holocaust. Occupied countries are shown separately from the Reich.|Нацисттик Германия баскынчылык согуш жүргүзүп, Холокостту ишке ашырат. Оккупацияланган өлкөлөр рейхтен өзүнчө көрсөтүлөт.'],[1945,1946,'Германия · четыре зоны оккупации|Germany · four occupation zones|Германия · төрт оккупациялык аймак','После капитуляции Германия управляется четырьмя союзными державами. Земли восточнее Одера и Нейсе переданы под польское управление; север Восточной Пруссии — советской администрации.|After surrender, four Allied powers administer Germany. Lands east of the Oder–Neisse pass under Polish administration; northern East Prussia under Soviet administration.|Багынгандан кийин Германияны төрт союздаш держава башкарат. Одер–Нейседен чыгыштагы жерлер Польша, Чыгыш Пруссиянын түндүгү советтик башкарууга өтөт.',U('Germany'),'influence']],'Potsdam');
 P('1918-austria',[[1940,1945,'Австрия · Германский рейх|Austria · German Reich|Австрия · Герман рейхи','Австрийские земли включены в рейх после аннексии 1938 года.|Austrian lands remain incorporated into the Reich after the 1938 annexation.|Австриянын жерлери 1938-жылкы аннексиядан кийин рейхтин курамында.'],[1945,1946,'Австрия · восстановленная республика|Austria · restored republic|Австрия · калыбына келген республика','Республика восстановлена под оккупацией четырёх союзных держав.|The republic is restored under four-power Allied occupation.|Республика төрт союздаш державанын оккупациясынын алдында калыбына келет.',U('Austria'),'influence']],'Potsdam');link('late-hre','1918-austria',1940,1945);
 for(const id of ['1939-bohemia','1939-slovakia','1939-poland-west','1939-poland-east'])end(id,1945);
 link('late-hre','1939-bohemia',1940,1945,'occupation',false);link('late-hre','1939-slovakia',1940,1945,'dependency',false);link('late-hre','1939-poland-west',1940,1945,'occupation',false);
 P('1939-poland-east',[[1940,1941,'Восточная Польша · советская аннексия|Eastern Poland · Soviet annexation|Чыгыш Польша · советтик аннексия','Земли заняты в 1939 году и включены в советские республики.|Occupied in 1939, these lands are incorporated into Soviet republics.|1939-жылы ээлеген жерлер советтик республикаларга кошулган.'],[1941,1944,'Восточная Польша · германская оккупация|Eastern Poland · German occupation|Чыгыш Польша · немис оккупациясы',occupied,null,'influence'],[1944,1945,'Восточные польские земли · возвращение советской власти|Eastern Polish lands · Soviet rule returns|Чыгыш поляк жерлери · совет бийлигинин кайтышы','Красная армия вытесняет германские войска.|The Red Army drives out German forces.|Кызыл Армия немис аскерлерин сүрүп чыгарат.']],'East');
 link('1939-ussr','1939-poland-east',1940,1941,'province');link('late-hre','1939-poland-east',1941,1944,'occupation',false);link('1939-ussr','1939-poland-east',1944,1945,'province');
 P('1945-poland',[[1945,1946,'Польша · новые рубежи|Poland · new boundaries|Польша · жаңы чектер','Восточная граница смещена к линии Керзона; бывшие германские земли на западе переданы под польское управление. Начинаются массовые перемещения населения.|The eastern boundary shifts toward the Curzon Line; former German lands in the west pass under Polish administration. Mass population transfers follow.|Чыгыш чек Керзон сызыгына жылып, батыштагы мурдагы герман жерлери Польшанын башкаруусуна өтөт. Калк массалык түрдө көчүрүлөт.',U('Poland')]],'Potsdam',{coord:[21.01,52.23]});
 P('1945-czechoslovakia',[[1945,1946,'Чехословакия|Czechoslovakia|Чехословакия','Государство восстановлено; Закарпатье передаётся СССР по договору июня 1945 года.|The state is restored; a June 1945 treaty transfers Subcarpathian Ruthenia to the USSR.|Мамлекет калыбына келип, 1945-жылдын июнь келишими менен Закарпатье СССРге берилет.',M(U('Czechia'),U('Slovakia'))]],'Potsdam',{coord:[14.42,50.08]});
 const bess=ring([[26.5,48.2],[28.2,48.5],[30.3,46.5],[30.2,45.2],[28.2,45.4],[28.1,46.5]]),dobruja=ring([[27,44.1],[28.7,44.2],[29,43.7],[28.4,43.1],[27,43.7]]),northTrans=ring([[22,47.7],[24.2,48.1],[26.1,47.9],[25.8,46.5],[24.6,46.1],[23.4,46.8],[22.2,46.7]]);
 P('1914-romania',[[1940,1944,'Румыния · Антонеску|Romania · Antonescu|Румыния · Антонеску','В 1940 году утрачены Бессарабия, Северная Буковина, Северная Трансильвания и Южная Добруджа. С 1941 года Румыния воюет на стороне Оси.|Bessarabia, northern Bukovina, northern Transylvania and southern Dobruja are lost in 1940. Romania fights with the Axis from 1941.|1940-жылы Бессарабия, Түндүк Буковина, Түндүк Трансильвания жана Түштүк Добружа жоголот. 1941-жылдан Румыния Ось тарабында согушат.',D(G('1914-romania'),M(bess,dobruja,northTrans))],[1944,1946,'Королевство Румыния|Kingdom of Romania|Румыния королдугу','В августе 1944 года Румыния меняет сторону в войне; Северная Трансильвания возвращается под румынское управление.|Romania changes sides in August 1944; northern Transylvania returns to Romanian administration.|Румыния 1944-жылдын августунда согуштагы тарабын алмаштырат; Түндүк Трансильвания румын башкаруусуна кайтат.',U('Romania')]]);
 P('early-transylvania',[[1940,1944,'Трансильвания · раздел между Венгрией и Румынией|Transylvania · Hungarian–Romanian partition|Трансильвания · Венгрия–Румыния бөлүнүшү','Северная часть передана Венгрии в 1940 году.|The northern part is transferred to Hungary in 1940.|Түндүк бөлүгү 1940-жылы Венгрияга берилет.',G('early-transylvania'),'influence'],[1944,1946,'Трансильвания · Румыния|Transylvania · Romania|Трансильвания · Румыния',normal]]);link('1914-romania','early-transylvania',1944,1946,'province',false);
 P('1918-hungary',[[1940,1944,'Королевство Венгрия|Kingdom of Hungary|Венгрия королдугу','Венгрия получает Северную Трансильванию и участвует в войне Оси.|Hungary acquires northern Transylvania and participates in the Axis war.|Венгрия Түндүк Трансильванияны алып, Ось согушуна катышат.',M(G('1918-hungary'),northTrans)],[1944,1945,'Венгрия · германская оккупация|Hungary · German occupation|Венгрия · немис оккупациясы','Германские войска входят в марте; в октябре к власти приходит «Скрещённые стрелы».|German troops enter in March; the Arrow Cross takes power in October.|Немис аскерлери мартта кирип, октябрда «Кайчылаш жебелер» бийликке келет.',M(G('1918-hungary'),northTrans),'influence'],[1945,1946,'Венгрия · Временное правительство|Hungary · Provisional Government|Венгрия · Убактылуу өкмөт','После войны территориальные приобретения Оси утрачены.|Wartime territorial gains are lost after defeat.|Жеңилүүдөн кийин согуш учурунда алган аймактар жоголот.',U('Hungary')]]);link('late-hre','1918-hungary',1944,1945,'occupation',false);
 P('1914-bulgaria',[[1940,1944,'Царство Болгария|Tsardom of Bulgaria|Болгария падышалыгы','Южная Добруджа возвращена по Крайовскому договору. С 1941 года болгарские войска занимают части Югославии и Греции.|Southern Dobruja returns under the Treaty of Craiova. From 1941 Bulgarian forces occupy parts of Yugoslavia and Greece.|Крайова келишими боюнча Түштүк Добружа кайтарылат. 1941-жылдан болгар аскерлери Югославия менен Грециянын бөлүктөрүн ээлейт.',M(G('1914-bulgaria'),dobruja)],[1944,1946,'Болгария · Отечественный фронт|Bulgaria · Fatherland Front|Болгария · Ата Мекен фронту','В сентябре 1944 года меняется правительство; Болгария вступает в войну против Германии.|A new government takes power in September 1944 and joins the war against Germany.|1944-жылдын сентябрында өкмөт алмашып, Болгария Германияга каршы согушка кирет.',U('Bulgaria')]]);
 P('1918-scs',[[1940,1941,'Королевство Югославия|Kingdom of Yugoslavia|Югославия королдугу','Королевство сохраняется до вторжения Оси в апреле 1941 года.|The kingdom survives until the Axis invasion in April 1941.|Королдук 1941-жылдын апрелиндеги Ось басып кирүүсүнө чейин сакталат.'],[1941,1944,'Югославия · оккупация и партизанская война|Yugoslavia · occupation and partisan war|Югославия · оккупация жана партизандык согуш','Страна разделена между оккупантами и зависимыми режимами. Разворачивается партизанская война.|The country is partitioned among occupiers and dependent regimes. Partisan warfare develops.|Өлкө оккупанттар менен көз каранды режимдердин ортосунда бөлүнүп, партизандык согуш башталат.',G('1918-scs'),'influence'],[1944,1945,'Югославия · освобождение|Yugoslavia · liberation|Югославия · боштондук','Белград освобождён в октябре 1944 года; бои на севере продолжаются.|Belgrade is liberated in October 1944; fighting continues in the north.|Белград 1944-жылдын октябрында бошотулуп, түндүктө салгылашуулар уланат.',G('1918-scs'),'influence'],[1945,1946,'Федеративная Народная Республика Югославия|Federal People’s Republic of Yugoslavia|Югославия Федеративдик Эл Республикасы','Монархия упразднена в ноябре 1945 года.|The monarchy is abolished in November 1945.|Монархия 1945-жылдын ноябрында жоюлат.']]);
 for(const[id,n]of [['1848-greece','Греция|Greece|Греция'],['1914-albania','Албания|Albania|Албания']]){const start=id==='1848-greece'?1941:1940;P(id,[[1940,start,n,'Война с Италией.|War with Italy.|Италия менен согуш.'],[start,1944,n.split('|').map((s,i)=>s+[' · оккупация',' · occupation',' · оккупация'][i]),'Итальянская и германская оккупация; действует движение Сопротивления.|Italian and German occupation; resistance movements operate.|Италиялык жана немис оккупациясы; Каршылык кыймылдары иштейт.',null,'influence'],[1944,1946,n,normal]].filter(r=>r[1]>r[0]));link('late-hre',id,1943,1944,'occupation',false);}
 const italy=U('Italy'),northItaly=geo.union(require('../vendor/polygon-clipping.cjs').intersection(geo.multi(italy),geo.multi(box(5,42,20,50))).flatMap(p=>p.map(r=>r.slice(0,-1))));
 P('1914-italy',[[1940,1943,'Королевство Италия|Kingdom of Italy|Италия королдугу','Италия вступает в войну в июне 1940 года.|Italy enters the war in June 1940.|Италия 1940-жылдын июнунда согушка кирет.'],[1943,1945,'Италия · королевство и союзники|Italy · kingdom and Allies|Италия · королдук жана союздаштар','После перемирия сентября 1943 года союзники наступают с юга.|After the September 1943 armistice, the Allies advance from the south.|1943-жылдын сентябрындагы жарашуудан кийин союздаштар түштүктөн жылат.',D(italy,northItaly),'influence'],[1945,1946,'Королевство Италия|Kingdom of Italy|Италия королдугу','Освобождение завершено весной 1945 года. Республика будет провозглашена в 1946 году.|Liberation is completed in spring 1945. The republic will be established in 1946.|1945-жылдын жазында боштондук аяктайт. Республика 1946-жылы түзүлөт.',italy]]);
 P('1945-salo',[[1943,1945,'Северная Италия · Итальянская социальная республика|Northern Italy · Italian Social Republic|Түндүк Италия · Италия Социалдык Республикасы','Режим Муссолини действует под германским военным контролем. Линия фронта движется на север.|Mussolini’s regime operates under German military control. The front moves north.|Муссолининин режими немис аскердик көзөмөлүндө иштейт. Фронт түндүккө жылат.',northItaly,'influence']],'Europe',{coord:[10.5,45.6]});link('late-hre','1945-salo',1943,1945,'dependency',false);
 const karelia=ring([[27.6,60.4],[30,59.8],[32,61.3],[32.4,64],[30.3,64.2],[29.5,61.7]]),petsamo=ring([[28.4,69],[30.5,68.9],[32,69.6],[29.4,70.1],[28.4,69.8]]);
 P('1815-finland',[[1940,1941,'Финляндия · Московский мир|Finland · Moscow Peace|Финляндия · Москва тынчтыгы','Мартовский мир завершает Зимнюю войну и передаёт СССР Карельский перешеек и другие территории.|The March peace ends the Winter War, ceding the Karelian Isthmus and other territories to the USSR.|Марттагы тынчтык Кышкы согушту аяктап, Карел мойногун жана башка жерлерди СССРге берет.',D(G('1815-finland'),karelia)],[1941,1944,'Финляндия · война-продолжение|Finland · Continuation War|Финляндия · Улантуу согушу','Финская армия возвращает утраченные земли и занимает Восточную Карелию; фронт проходит восточнее довоенной границы.|Finnish forces recover lost lands and occupy East Karelia; the front lies east of the prewar boundary.|Фин аскерлери жоготкон жерлерин кайтарып, Чыгыш Карелияны ээлейт; фронт согушка чейинки чектен чыгышта.',G('1815-finland'),'influence'],[1944,1946,'Финляндская республика|Republic of Finland|Финляндия Республикасы','Сентябрьское перемирие 1944 года восстанавливает границу 1940 года и передаёт Петсамо СССР. Финляндия остаётся независимой.|The September 1944 armistice restores the 1940 boundary and cedes Petsamo to the USSR. Finland remains independent.|1944-жылдын сентябрындагы жарашуу 1940-жылкы чекти калыбына келтирип, Петсамону СССРге берет. Финляндия көз карандысыз бойдон калат.',D(G('1815-finland'),M(karelia,petsamo))]]);
 const baltic=['1918-estonia','1918-latvia','1918-lithuania'];
 for(const id of baltic){const n=c.entries.find(e=>e.id===id).name;P(id,[[1940,1941,n,'Советская оккупация и аннексия летом 1940 года.|Soviet occupation and annexation in summer 1940.|1940-жылдын жайындагы советтик оккупация жана аннексия.'],[1941,1944,n,occupied,null,'influence'],[1944,1946,n,'Советская власть восстановлена; в Курляндии германские войска удерживаются до мая 1945 года.|Soviet rule returns; German forces hold out in Courland until May 1945.|Совет бийлиги кайтып, Курляндияда немис аскерлери 1945-жылдын майына чейин карманат.']],'East');link('1939-ussr',id,1940,1941);link('late-hre',id,1941,1944,'occupation',false);link('1939-ussr',id,1944,1946);}
 const ussr=M(G('1939-ussr'),karelia,bess),west=G('1939-poland-east');
 const occupation={1941:ring([[27,59.8],[30,59.5],[32,58],[34,56.5],[36,55.7],[37,54],[38,52],[36,50],[38.5,48],[38.5,46],[35,44.5],[29,44.5],[25,48],[24,54]]),1942:ring([[27,59.8],[30,59.5],[32,58],[34,56.5],[36,55],[36,52],[40,51],[44.5,49],[44.3,46],[44,43.6],[40,43.5],[35,44.5],[29,44.5],[24,50]]),1943:ring([[27,59.8],[30,59.5],[31,57],[29,55],[30,53],[32,51],[31,50],[32,49],[34,48],[35,46],[36,44.5],[29,44.5],[24,50]]),1944:ring([[20.5,57.8],[22.5,57.8],[23.5,56.8],[21,56.3]])};
 const rows=[];for(let y=1940;y<=1945;y++){const occ=occupation[y];let poly=occ?D(ussr,occ):ussr;if(y>=1944)poly=M(poly,petsamo);if(y===1945)poly=M(poly,west,ring([[19.5,54.5],[22.8,54.3],[22.8,55.1],[20.8,55.3]]),G('cartography-tuva'),ring([[141,46],[143.4,46],[145,49.5],[144,54.5],[141.5,54.5]]));rows.push([y,y+1,y===1945?'СССР · окончание войны|USSR · end of the war|СССР · согуштун аягы':'СССР|USSR|СССР',y===1940?'В 1940 году СССР аннексирует Балтийские государства, Бессарабию и Северную Буковину.|In 1940 the USSR annexes the Baltic states, Bessarabia and northern Bukovina.|1940-жылы СССР Балтика мамлекеттерин, Бессарабияны жана Түндүк Буковинаны аннексиялайт.':y===1945?'Победа над Германией и Японией. После войны СССР получает новые территории на западе и Дальнем Востоке.|Victory over Germany and Japan. The USSR gains territories in the west and Far East after the war.|Германия менен Японияны жеңүү. Согуштан кийин СССР батышта жана Ыраакы Чыгышта жаңы жерлерге ээ болот.':'Советско-германский фронт и оккупированные области меняются в ходе войны.|The Soviet–German front and occupied regions change during the war.|Совет-немис фронту жана оккупацияланган аймактар согушта өзгөрүп турат.',poly]);}
 P('1939-ussr',rows,'East',{label:[85,61]});
 for(const[y,poly]of Object.entries(occupation))P('1945-eastern-occupation-'+y,[[+y,+y+1,'Восточный фронт · оккупация Оси|Eastern Front · Axis occupation|Чыгыш фронту · Ось оккупациясы','Показана обобщённая область оккупации к концу года; внутри неё действуют разные военные и гражданские администрации.|Generalised occupied area near year-end, containing different military and civil administrations.|Жыл аягына жакын оккупацияланган жалпы аймак; анын ичинде ар башка аскердик жана жарандык башкаруулар иштейт.',poly,'influence']],'East',{coord:+y===1944?[22,57]:[32,53],color:'#927f78'});
 for(const y of Object.keys(occupation))link('late-hre','1945-eastern-occupation-'+y,+y,+y+1,'occupation',false);
 P('cartography-tuva',[[1940,1944,'Тувинская Народная Республика|Tuvan People’s Republic|Тува Эл Республикасы','Отдельное государство до вхождения в СССР в октябре 1944 года.|A separate state until incorporation into the USSR in October 1944.|1944-жылдын октябрында СССРге киргенге чейин өзүнчө мамлекет.'],[1944,1946,'Тувинская автономная область · РСФСР|Tuvan Autonomous Oblast · RSFSR|Тува автоном облусу · РСФСР','Тува включена в РСФСР в составе СССР.|Tuva is incorporated into the RSFSR within the USSR.|Тува СССРдин курамындагы РСФСРге кошулат.']],'East');link('1939-ussr','cartography-tuva',1944,1946);
 for(const[id,y,entry,title,txt,coord,src]of [
 ['france',1940,'late-france','Падение Франции|Fall of France|Франциянын жеңилиши','Перемирие подписано 22 июня.|The armistice is signed on 22 June.|Жарашууга 22-июнда кол коюлат.',[2.82,49.42],'France'],
 ['barbarossa',1941,'1939-ussr','Нападение на СССР|Invasion of the USSR|СССРге кол салуу','22 июня начинается вторжение Германии и её союзников.|Germany and its allies invade on 22 June.|Германия жана союздаштары 22-июнда басып кирет.',[23.7,52.1],'East'],
 ['stalingrad',1943,'1939-ussr','Сталинградская битва|Battle of Stalingrad|Сталинград салгылашуусу','Окружённая германская группировка капитулирует в январе–феврале.|The encircled German force surrenders in January–February.|Курчалган немис күчтөрү январь–февралда багынат.',[44.5,48.7],'East'],
 ['normandy',1944,'late-france','Высадка в Нормандии|Normandy landings|Нормандияга десант','6 июня союзники высаживаются во Франции.|Allied troops land in France on 6 June.|Союздаш аскерлер 6-июнда Францияга түшөт.',[-.85,49.37],'France'],
 ['victory',1945,'late-hre','Капитуляция Германии|German surrender|Германиянын багынышы','Война в Европе заканчивается в мае.|The war in Europe ends in May.|Европадагы согуш майда аяктайт.',[13.4,52.5],'Potsdam']
 ])event(id,y,entry,title,txt,coord,[src],'war');
};
