'use strict';
module.exports=(c,{G,set,source,event,box})=>{
 source('Germany','Deutsches Historisches Museum. LeMO: Reichsgründung 1871; Verfassung des Norddeutschen Bundes (1867).',['https://www.dhm.de/lemo/kapitel/kaiserreich/reich/reichsgruendung']);
 source('Italy','Presidenza della Repubblica Italiana. L’Italia unita; Legge 17 marzo 1861, n. 4671.',['https://archivio.quirinale.it/aspr/gianni-bisiach/AV-002-000399/17-marzo-1861-vittorio-emanuele-ii-primo-re-ditalia','https://www.quirinale.it/allegati_statici/ebookapp/italiaunita.pdf']);
 source('Habsburg','Die Welt der Habsburger. Zwei Reichshälften: Der Ausgleich mit Ungarn.',['https://www.habsburger.net/de/kapitel/zwei-reichshaelften-der-ausgleich-mit-ungarn']);
 source('Berlin','The Treaty of Berlin (1878); William Norton Medlicott. The Congress of Berlin and After.',['https://www.loc.gov/resource/gdc.unk81055785/']);
 source('Europe','Eric Hobsbawm. The Age of Capital: 1848–1875; The Age of Empire: 1875–1914.',['https://www.penguinrandomhouse.com/books/326654/the-age-of-capital-by-eric-hobsbawm/']);
 const put=(id,rows,s='Europe',meta={})=>set(id,rows,{sources:['to1914'+s],...meta});
 put('late-france',[[1849,1852,'Франция · Вторая республика|France · Second Republic|Франция · Экинчи республика','Луи-Наполеон сосредоточивает власть и совершает переворот в 1851 году.|Louis-Napoleon consolidates power and stages a coup in 1851.|Луи-Наполеон бийлигин күчөтүп, 1851-жылы төңкөрүш жасайт.'],[1852,1870,'Франция · Вторая империя|France · Second Empire|Франция · Экинчи империя','Наполеон III правит империей; растут железные дороги и промышленность.|Napoleon III rules the empire; railways and industry expand.|Империяны Наполеон III башкарат; темир жолдор жана өнөр жай өсөт.'],[1870,1871,'Франция · республика и война|France · republic and war|Франция · республика жана согуш','После поражения при Седане провозглашена республика. Париж находится в осаде.|Defeat at Sedan is followed by a republic. Paris is besieged.|Седандагы жеңилүүдөн кийин республика жарыяланат. Париж курчоодо калат.'],[1871,1915,'Франция · Третья республика|France · Third Republic|Франция · Үчүнчү республика','Эльзас и часть Лотарингии уступлены Германии. После Парижской коммуны укрепляется парламентская республика.|Alsace and part of Lorraine are ceded to Germany. A parliamentary republic consolidates after the Paris Commune.|Эльзас жана Лотарингиянын бир бөлүгү Германияга берилет. Париж коммунасынан кийин парламенттик республика бекемделет.',[[[-4.8,48.5],[-1.5,49.7],[2.6,50.8],[4.8,49.9],[5.7,49.3],[6,48.8],[7,47.7],[6,46.3],[7.5,44.1],[7.3,43.7],[3.1,42.5],[-1.7,43.4],[-1,46.2]]]]]);
 const germanNorth=[[[6,51],[7,53.5],[9,54.8],[11,54.4],[14.5,54.8],[17.6,54.8],[20.5,55.6],[22.7,54.7],[22.8,53.4],[19,53],[18,51],[16,50.2],[14,50.8],[12.1,50.3],[10,50.2],[8,49.8],[6,50.2]]];
 const germanFull=[[[6,49],[6,51],[7,53.5],[9,54.8],[11,54.4],[14.5,54.8],[17.6,54.8],[20.5,55.6],[22.7,54.7],[22.8,53.4],[19,53],[18,51],[16,50.2],[14.5,50.8],[12.7,49.5],[13.8,48.7],[13,47.6],[10.5,47.3],[7.5,47.5],[7,47.7],[6,48.8]]];
 put('late-hre',[[1849,1866,'Германский союз|German Confederation|Герман союзу','Революция подавлена. Австрия и Пруссия соперничают за руководство германскими государствами.|The revolution is suppressed. Austria and Prussia compete for leadership of the German states.|Революция басылат. Австрия менен Пруссия герман мамлекеттеринде үстөмдүк үчүн атаандашат.'],[1866,1867,'Германские государства · распад союза|German states · dissolution of the confederation|Герман мамлекеттери · союздун тарашы','Победа Пруссии над Австрией прекращает существование Германского союза.|Prussia’s victory over Austria ends the German Confederation.|Пруссиянын Австрияны жеңиши Герман союзун жоёт.',germanNorth,'influence'],[1867,1871,'Северогерманский союз|North German Confederation|Түндүк Герман союзу','Северные германские государства образуют федерацию под руководством Пруссии.|Northern German states form a federation under Prussian leadership.|Түндүктөгү герман мамлекеттери Пруссиянын башчылыгында федерация түзөт.',germanNorth],[1871,1915,'Германская империя|German Empire|Герман империясы','Южногерманские государства входят в империю. Берлин становится центром объединённого государства.|Southern German states join the empire. Berlin becomes the centre of the united state.|Түштүктөгү герман мамлекеттери империяга кошулат. Берлин бириккен мамлекеттин борборуна айланат.',germanFull]],'Germany');
 put('1789-prussia',[[1849,1867,'Королевство Пруссия|Kingdom of Prussia|Пруссия падышалыгы','Пруссия расширяет влияние и побеждает Австрию в войне 1866 года.|Prussia extends its influence and defeats Austria in the war of 1866.|Пруссия таасирин кеңейтип, 1866-жылкы согушта Австрияны жеңет.']],'Germany');
 for(const id of ['early-austria','early-royal-hungary','early-transylvania'])put(id,[[1849,1867,id==='early-austria'?'Австрийская империя|Austrian Empire|Австрия империясы':'Венгерские земли · Австрийская империя|Hungarian lands · Austrian Empire|Венгер жерлери · Австрия империясы','После подавления революции восстанавливается власть Габсбургов.|Habsburg authority is restored after the revolution is defeated.|Революция басылгандан кийин Габсбургдардын бийлиги калыбына келет.'],[1867,1915,id==='early-austria'?'Австро-Венгрия · австрийские земли|Austria-Hungary · Austrian lands|Австрия-Венгрия · австриялык жерлер':'Австро-Венгрия · венгерские земли|Austria-Hungary · Hungarian lands|Австрия-Венгрия · венгер жерлери','Соглашение 1867 года создаёт дуалистическую монархию с общими монархом, внешней политикой и армией.|The 1867 Compromise creates a dual monarchy sharing a ruler, foreign policy and army.|1867-жылкы келишим жалпы монархы, тышкы саясаты жана аскери бар кош монархияны түзөт.']],'Habsburg');
 const piedmont=[[[6.8,44.2],[7.2,45.8],[8.4,46.4],[9,45.8],[8.7,44.2],[7.5,43.8]]],sardinia=[[[8.1,40.9],[9.3,41.2],[9.8,39.2],[8.5,38.9],[8.1,40.1]]];
 put('1914-italy',[[1849,1859,'Сардинское королевство|Kingdom of Sardinia|Сардиния падышалыгы','Пьемонт и Сардиния остаются под властью Савойской династии.|Piedmont and Sardinia remain under the House of Savoy.|Пьемонт менен Сардиния Савой династиясынын бийлигинде калат.',[...piedmont,...sardinia]],[1859,1861,'Сардинское королевство · объединение|Kingdom of Sardinia · unification|Сардиния падышалыгы · биригүү','В 1859 году присоединена Ломбардия; в 1860 году — центральные и южные области.|Lombardy is acquired in 1859; central and southern regions join in 1860.|1859-жылы Ломбардия, 1860-жылы борбордук жана түштүк аймактар кошулат.',[...piedmont,...sardinia,...G('early-milan')]],[1861,1866,'Королевство Италия|Kingdom of Italy|Италия падышалыгы','Провозглашено Королевство Италия. Рим и Венеция ещё остаются вне нового государства.|The Kingdom of Italy is proclaimed. Rome and Venice remain outside the new state.|Италия падышалыгы жарыяланат. Рим менен Венеция жаңы мамлекетке али кире элек.',[...piedmont,...sardinia,...G('early-milan'),...G('early-florence'),...G('early-naples'),...G('1815-sicily')]],[1866,1870,'Италия · присоединение Венеции|Italy · acquisition of Venetia|Италия · Венециянын кошулушу','После войны с Австрией Венеция переходит к Италии.|After the war with Austria, Venetia passes to Italy.|Австрия менен согуштан кийин Венеция Италияга өтөт.',[...piedmont,...sardinia,...G('early-milan'),...G('early-florence'),...G('early-naples'),...G('1815-sicily'),...G('early-venice')]],[1870,1915,'Королевство Италия · Рим|Kingdom of Italy · Rome|Италия падышалыгы · Рим','Итальянские войска занимают Рим; в 1871 году он становится столицей.|Italian troops take Rome; it becomes the capital in 1871.|Италия аскерлери Римди ээлейт; 1871-жылы ал борбор болот.',[...piedmont,...sardinia,...G('early-milan'),...G('early-florence'),...G('early-naples'),...G('1815-sicily'),...G('early-venice'),...G('early-papal')]]],'Italy',{region:'eurasia',coord:[12.5,42.5],color:'#7b9561'});
 for(const [id,end,name] of [['early-milan',1859,'Ломбардия · Австрия|Lombardy · Austria|Ломбардия · Австрия'],['early-florence',1860,'Великое герцогство Тосканское|Grand Duchy of Tuscany|Тоскана улуу герцогдугу'],['early-naples',1861,'Королевство Обеих Сицилий|Kingdom of the Two Sicilies|Эки Сицилия падышалыгы'],['1815-sicily',1861,'Сицилия · Бурбонская монархия|Sicily · Bourbon monarchy|Сицилия · Бурбон монархиясы'],['early-venice',1866,'Венеция · Австрия|Venetia · Austria|Венеция · Австрия'],['early-papal',1870,'Папская область|Papal States|Папа мамлекети']])put(id,[[1849,end,name,'Восстановленная после революции власть сохраняется до объединения с Италией.|Authority restored after the revolution lasts until incorporation into Italy.|Революциядан кийин калыбына келген бийлик Италияга кошулганга чейин сакталат.']],'Italy');
 put('1815-norway',[[1849,1905,'Норвегия · уния со Швецией|Norway · union with Sweden|Норвегия · Швеция менен уния','Норвегия имеет собственные конституцию и парламент при общем со Швецией монархе.|Norway has its own constitution and parliament under a monarch shared with Sweden.|Норвегия Швеция менен жалпы монархка карап, өз конституциясын жана парламентин сактайт.'],[1905,1915,'Королевство Норвегия|Kingdom of Norway|Норвегия падышалыгы','Уния со Швецией расторгнута; королём избран Хокон VII.|The union with Sweden is dissolved; Haakon VII is chosen as king.|Швеция менен уния токтойт; Хокон VII падыша болуп шайланат.']]);
 put('late-portugal',[[1849,1910,'Португалия · монархия|Portugal · monarchy|Португалия · монархия','Конституционная монархия переживает финансовые и политические кризисы.|The constitutional monarchy faces financial and political crises.|Конституциялык монархия каржылык жана саясий кризистерге туш болот.'],[1910,1915,'Португальская республика|Portuguese Republic|Португалия республикасы','Революция 1910 года свергает монархию и устанавливает республику.|The revolution of 1910 overthrows the monarchy and establishes a republic.|1910-жылкы революция монархияны кулатып, республиканы орнотот.']]);
 put('1789-spain',[[1849,1868,'Испания · Изабелла II|Spain · Isabella II|Испания · Изабелла II','Либеральные группировки и монархия борются за политическую власть.|Liberal factions and the monarchy contest political power.|Либералдык топтор менен монархия саясий бийлик үчүн күрөшөт.'],[1868,1873,'Испания · революция и новая монархия|Spain · revolution and a new monarchy|Испания · революция жана жаңы монархия','Изабелла II свергнута; после временного правительства королём становится Амадей I.|Isabella II is overthrown; a provisional government is followed by King Amadeo I.|Изабелла II кулатылат; убактылуу өкмөттөн кийин Амадей I падыша болот.'],[1873,1874,'Испания · Первая республика|Spain · First Republic|Испания · Биринчи республика','Республика сталкивается с войнами и внутренними восстаниями.|The republic faces wars and internal revolts.|Республика согуштарга жана ички көтөрүлүштөргө туш болот.'],[1874,1915,'Испания · Реставрация Бурбонов|Spain · Bourbon Restoration|Испания · Бурбондордун кайтышы','Монархия восстановлена. В 1898 году Испания теряет Кубу, Пуэрто-Рико и Филиппины.|The monarchy is restored. Spain loses Cuba, Puerto Rico and the Philippines in 1898.|Монархия калыбына келет. 1898-жылы Испания Кубадан, Пуэрто-Рикодон жана Филиппинден ажырайт.']]);
 put('1914-serbia',[[1849,1878,'Княжество Сербия · османский сюзеренитет|Principality of Serbia · Ottoman suzerainty|Сербия княздыгы · осмон үстөмдүгү','Автономное княжество расширяет самоуправление.|The autonomous principality expands its self-government.|Автономиялуу княздык өз алдынча башкаруусун кеңейтет.',box(19.4,43.4,22.4,45)],[1878,1882,'Независимое княжество Сербия|Independent Principality of Serbia|Көз карандысыз Сербия княздыгы','Берлинский договор признаёт независимость.|The Treaty of Berlin recognises independence.|Берлин келишими көз карандысыздыкты тааныйт.',box(19.4,42.4,22.9,45)],[1882,1913,'Королевство Сербия|Kingdom of Serbia|Сербия падышалыгы','Провозглашено королевство; Балканские войны приводят к расширению на юг.|A kingdom is proclaimed; the Balkan Wars bring expansion southward.|Падышалык жарыяланат; Балкан согуштары түштүккө кеңейүүгө алып келет.',box(19.4,42.4,22.9,45)],[1913,1915,'Сербия · после Балканских войн|Serbia · after the Balkan Wars|Сербия · Балкан согуштарынан кийин','Сербия управляет также Косовом и Вардарской Македонией. В 1914 году начинается война с Австро-Венгрией.|Serbia also governs Kosovo and Vardar Macedonia. War with Austria-Hungary begins in 1914.|Сербия Косово менен Вардар Македониясын да башкарат. 1914-жылы Австрия-Венгрия менен согуш башталат.',[[[19.4,45],[22.7,44.2],[22.4,42.5],[23,41.5],[22.5,40.9],[20.5,40.9],[20.6,42],[19.5,43]]]]],'Berlin',{region:'eurasia',coord:[20.5,44],color:'#a0808d'});
 put('1914-bulgaria',[[1878,1885,'Княжество Болгария|Principality of Bulgaria|Болгария княздыгы','Создано автономное княжество к северу от Балканских гор под османским сюзеренитетом.|An autonomous principality north of the Balkan Mountains remains under Ottoman suzerainty.|Балкан тоолорунун түндүгүндө осмон үстөмдүгүндөгү автономиялуу княздык түзүлөт.',box(22.5,42.8,28.5,44.2)],[1885,1908,'Болгария · объединение с Восточной Румелией|Bulgaria · union with Eastern Rumelia|Болгария · Чыгыш Румелия менен биригүү','Восточная Румелия объединяется с княжеством.|Eastern Rumelia unites with the principality.|Чыгыш Румелия княздыкка биригет.',box(22.5,41.5,28.5,44.2)],[1908,1913,'Болгарское царство|Kingdom of Bulgaria|Болгария падышалыгы','Провозглашена полная независимость от Османского государства.|Full independence from the Ottoman state is proclaimed.|Осмон мамлекетинен толук көз карандысыздык жарыяланат.',box(22.5,41.5,28.5,44.2)],[1913,1915,'Болгария · после Бухарестского мира|Bulgaria · after the Treaty of Bucharest|Болгария · Бухарест тынчтыгынан кийин','После Второй Балканской войны Южная Добруджа уступлена Румынии; сохранён выход к Эгейскому морю.|After the Second Balkan War, Southern Dobruja is ceded to Romania; access to the Aegean is retained.|Экинчи Балкан согушунан кийин Түштүк Добружа Румынияга берилет; Эгей деңизине чыгуу сакталат.',[[[22.5,44],[26.8,44],[27.9,43],[27.5,42],[26,41.8],[26,40.7],[24.7,40.8],[23,41.4],[22.5,43]]]]],'Berlin',{region:'eurasia',coord:[25,42.7],color:'#879861'});
 const romanianCore=[[[22.5,44],[24,45.5],[26.2,45.7],[26.6,47.7],[28.2,48.2],[28,46],[28.2,45.4],[29,45],[27.8,44],[25,43.6]]],dobruja=[[[28,44],[28.2,45.4],[29.7,45.2],[28.7,44],[28,44]]],southDobruja=[[[26.8,44],[28.7,44],[28.5,43.4],[27.5,43.6]]];
 put('1914-romania',[
 [1859,1878,'Объединённые княжества · Румыния|United Principalities · Romania|Бириккен княздыктар · Румыния','Молдавия и Валахия объединяются под Александру Кузой, сохраняя османский сюзеренитет.|Moldavia and Wallachia unite under Alexandru Cuza while remaining under Ottoman suzerainty.|Молдавия менен Валахия осмон үстөмдүгүн сактап, Александру Кузанын башкаруусунда биригет.',romanianCore],
 [1878,1881,'Независимая Румыния|Independent Romania|Көз карандысыз Румыния','Берлинский договор признаёт независимость; Северная Добруджа переходит Румынии.|The Treaty of Berlin recognises independence; Northern Dobruja passes to Romania.|Берлин келишими көз карандысыздыкты тааныйт; Түндүк Добружа Румынияга өтөт.',[...romanianCore,...dobruja]],
 [1881,1913,'Королевство Румыния|Kingdom of Romania|Румыния падышалыгы','Кароль I становится королём; Трансильвания остаётся в Австро-Венгрии.|Carol I becomes king; Transylvania remains in Austria-Hungary.|Кароль I падыша болот; Трансильвания Австрия-Венгрияда калат.',[...romanianCore,...dobruja]],
 [1913,1915,'Румыния · Южная Добруджа|Romania · Southern Dobruja|Румыния · Түштүк Добружа','После Второй Балканской войны присоединена Южная Добруджа.|Southern Dobruja is acquired after the Second Balkan War.|Экинчи Балкан согушунан кийин Түштүк Добружа кошулат.',[...romanianCore,...dobruja,...southDobruja]]
 ],'Berlin',{region:'eurasia',coord:[26.1,44.4],color:'#b49a5e'});
 event('germany',1871,'late-hre','Объединение Германии|German unification|Германиянын биригиши','В Версале провозглашена Германская империя.|The German Empire is proclaimed at Versailles.|Версалда Герман империясы жарыяланат.',[2.12,48.8]);
 event('italy',1861,'1914-italy','Провозглашение Италии|Proclamation of Italy|Италиянын жарыяланышы','В Турине провозглашено новое королевство.|The new kingdom is proclaimed in Turin.|Туринде жаңы падышалык жарыяланат.',[7.68,45.07]);
 event('rome',1870,'1914-italy','Взятие Рима|Capture of Rome|Римдин алынышы','Итальянская армия входит в Рим через Порта-Пиа.|The Italian army enters Rome through Porta Pia.|Италия аскери Римге Порта-Пиа аркылуу кирет.',[12.51,41.91],'war');
 event('ausgleich',1867,'early-royal-hungary','Австро-венгерское соглашение|Austro-Hungarian Compromise|Австрия-Венгрия келишими','Монархия разделена на австрийскую и венгерскую части с общими делами.|The monarchy is reorganised into Austrian and Hungarian halves with common affairs.|Монархия жалпы иштерди сактаган австриялык жана венгер бөлүктөрүнө кайра түзүлөт.',[19.04,47.5]);
 event('berlin',1878,'1914-serbia','Берлинский конгресс|Congress of Berlin|Берлин конгресси','Договор меняет устройство Балкан и признаёт независимость Сербии, Румынии и Черногории.|The treaty reorganises the Balkans and recognises Serbian, Romanian and Montenegrin independence.|Келишим Балкандагы түзүлүштү өзгөртүп, Сербиянын, Румыниянын жана Черногориянын көз карандысыздыгын тааныйт.',[13.4,52.5],'diplomacy');
 event('ww1',1914,'1914-serbia','Начало Первой мировой войны|Outbreak of the First World War|Биринчи дүйнөлүк согуштун башталышы','Австро-Венгрия объявляет войну Сербии 28 июля. Система союзов и мобилизации расширяет войну.|Austria-Hungary declares war on Serbia on 28 July. Alliances and mobilisation widen the war.|Австрия-Венгрия 28-июлда Сербияга согуш жарыялайт. Союздар жана мобилизация согушту кеңейтет.',[20.46,44.81],'war');
};
