'use strict';
module.exports=(c,{T,G,set,source,event,ring,box,before})=>{
 source('Ukraine','Український інститут національної пам’яті. Українська революція: Директорія.','https://unr.uinp.gov.ua/photohistory/derzhavne-budivnitstvo/direktoriya');
 source('Georgia','Национальный архив Грузии. Акт независимости, 26 мая 1918 года.','https://archive.gov.ge/storage/old_files/doc/2/2784.pdf');
 source('Armenia','Ministry of Foreign Affairs of Armenia. The First Republic and Soviet Rule.','https://romania.mfa.am/ro/history');
 source('Azerbaijan','Declaration of Independence of Azerbaijan, 28 May 1918.','https://tehran.mfa.gov.az/en/content/46/history');
 source('ArmenianGenocide','United States Holocaust Memorial Museum. The Armenian Genocide, 1915–1916.','https://encyclopedia.ushmm.org/content/en/article/the-armenian-genocide-1915-16-overview');
 source('Brazil','Arquivo Nacional. Primeira República, 1889–1930: cronologia.','https://mapa.arquivonacional.gov.br/index.php/assuntos/79-producao/80-cronologia/584-primeira-republica-1889-1930');
 source('Dominican','Foreign Relations of the United States, 1916: military occupation of Santo Domingo.','https://history.state.gov/historicaldocuments/frus1916/d261');
 source('Conscription','Australian War Memorial. Conscription, 1916–1917.','https://www.awm.gov.au/visit/exhibitions/anzac-voices/conscription');
 const put=(id,rows,src,meta={})=>set(id,rows,{...meta,sources:[...new Set([...(before.get(id)?.phase.sources||[]),'to1918'+src,...(['Georgia','Armenia','Azerbaijan'].includes(src)?['to1918Caucasus']:[])])]});
 const finland=ring([[20.5,69.1],[21.8,68.1],[23.4,67.6],[23.7,66.2],[24.2,65.7],[24.8,65],[23.5,63.5],[20,62.5],[19.5,60],[22,59.2],[27.7,60],[30.8,60.5],[32.7,63],[31.5,64.5],[30,65.8],[29.4,67],[29.6,68],[28.4,68.9],[29,69.05],[28.2,69.95],[27.8,70.1],[25.8,69.6]]);
 for(const a of c.areas.filter(a=>a.entry==='1815-finland'&&a.from>=1917)){a.polygons=structuredClone(finland);a.points=a.polygons[0];a.label=[26,65];}
 put('1918-ukraine',[[1917,1918,'Украина · Центральная рада|Ukraine · Central Rada|Украина · Борбордук рада','Центральная рада создаётся в Киеве. В ноябре провозглашается Украинская Народная Республика; местные центры власти соперничают между собой.|The Central Rada forms in Kyiv. The Ukrainian People’s Republic is proclaimed in November; local centres of power compete.|Киевде Борбордук рада түзүлөт. Ноябрда Украина Эл Республикасы жарыяланат; жергиликтүү бийлик борборлору атаандашат.',ring([[25,50.5],[30,52],[34,51],[36,49],[34,47],[30,46.5],[27,48]]),'influence'],[1918,1919,'Украина · УНР, гетманат и Директория|Ukraine · UNR, Hetmanate and Directory|Украина · УЭР, гетманат жана Директория','В январе УНР объявляет независимость. Германо-австрийское вмешательство, гетманат Скоропадского и восстановление УНР Директорией последовательно меняют власть в Киеве; войны продолжаются.|The UNR declares independence in January. German-Austrian intervention, Skoropadsky’s Hetmanate and the Directory’s restoration of the UNR successively change power in Kyiv; wars continue.|Январда УЭР көз карандысыздыгын жарыялайт. Германия-Австриянын кийлигишүүсү, Скоропадскийдин гетманаты жана Директориянын УЭРди калыбына келтириши Киевдеги бийликти кезек менен өзгөртөт; согуштар уланат.',ring([[25,50.5],[30,52],[34,51],[36,49],[34,47],[30,46.5],[27,48]]),'influence']],'Ukraine',{coord:[30.52,50.45],color:'#ab9b65'});
 const regions=[
 ['georgia','Грузинская Демократическая Республика|Democratic Republic of Georgia|Грузия Демократиялык Республикасы','26 мая объявлена независимость. Правительство действует в Тифлисе; германское присутствие сменяется британским после перемирия.|Independence is declared on 26 May. The government operates in Tiflis; German presence gives way to British forces after the armistice.|26-майда көз карандысыздык жарыяланат. Өкмөт Тифлисте иштейт; жарашуудан кийин герман аскерлерин британдыктар алмаштырат.',[44.8,41.72],[[41.2,42],[41.8,43.1],[44,42.8],[46.4,41.8],[45,41.1],[43,41.5]],'Georgia'],
 ['armenia','Республика Армения|Republic of Armenia|Армения Республикасы','В мае образована республика с центром в Ереване. Беженцы, голод, война и спорные границы определяют её первые месяцы.|A republic centred on Yerevan forms in May. Refugees, hunger, war and disputed borders shape its first months.|Майда борбору Ереван болгон республика түзүлөт. Качкындар, ачарчылык, согуш жана талаштуу чек аралар анын алгачкы айларын аныктайт.',[44.51,40.18],[[44,39.7],[45.1,39.8],[45.7,40.7],[44.7,41.1],[44.1,40.8]],'Armenia'],
 ['azerbaijan','Азербайджанская Демократическая Республика|Azerbaijan Democratic Republic|Азербайжан Демократиялык Республикасы','28 мая провозглашена республика. Правительство действует сначала в Гяндже, затем в Баку. Османские и британские войска участвуют в борьбе за регион.|The republic is proclaimed on 28 May. Its government operates first in Ganja, then Baku. Ottoman and British troops take part in the struggle over the region.|28-майда республика жарыяланат. Өкмөт адегенде Гянжада, кийин Бакуда иштейт. Осмон жана британ аскерлери аймак үчүн күрөшкө катышат.',[49.87,40.41],[[46.1,40.5],[47.2,41.5],[48.5,41.6],[50.3,40.5],[49.5,39.5],[47.6,39.6]],'Azerbaijan']
 ];
 for(const [id,name,body,coord,poly,src] of regions)put('1918-'+id,[[1918,1919,name,body,ring(poly),'influence']],src,{coord});
 // Do not leave old imperial dependencies alive after the respective governments fall.
 const update=(id,from,name,text,kind='influence')=>{const e=c.entries.find(e=>e.id===id),a=c.areas.find(a=>a.entry===id&&a.from<=from&&a.to>from);const p=e.phases.find(p=>p.from<=from&&p.to>from);if(p.from<from){p.to=from;a.to=from;e.phases.push({...structuredClone(p),from,to:1919,period:T(from+'–1918|'+from+'–1918|'+from+'–1918'),name:T(name),title:T(name),text:T(text)});c.areas.push({...structuredClone(a),id:id+'-'+from,from,to:1919,name:T(name),title:T(name),text:T(text),kind});}else{Object.assign(p,{name:T(name),title:T(name),text:T(text)});Object.assign(a,{name:T(name),title:T(name),text:T(text),kind});}};
 update('1914-romania',1918,'Румыния · объединения 1918 года|Romania · unions of 1918|Румыния · 1918-жылдагы биригүүлөр','Советы Бессарабии, Буковины и Трансильвании принимают решения об объединении с Румынией. Военный контроль и международное закрепление границ формируются в последующие годы.|Councils in Bessarabia, Bukovina and Transylvania vote for union with Romania. Military control and international border settlements develop in the following years.|Бессарабия, Буковина жана Трансильвания кеңештери Румыния менен биригүү чечимдерин кабыл алат. Аскердик көзөмөл жана эл аралык чек ара келишимдери кийинки жылдары калыптанат.');
 const tr=before.get('early-transylvania');put('early-transylvania',[[1915,1918,tr.phase.name.join('|'),tr.phase.text.join('|')],[1918,1919,'Трансильвания · решение об объединении с Румынией|Transylvania · vote for union with Romania|Трансильвания · Румыния менен биригүү чечими','1 декабря собрание в Алба-Юлии принимает решение об объединении. Венгерские и румынские власти оспаривают контроль над регионом.|The assembly at Alba Iulia votes for union on 1 December. Hungarian and Romanian authorities contest control of the region.|1-декабрда Алба-Юлиядагы жыйын биригүү чечимин кабыл алат. Венгер жана румын бийликтери аймакты көзөмөлдөө үчүн талашат.',null,'influence']],'Habsburg');
 event('ukraine',1918,'1918-ukraine','Независимость УНР|UNR independence|УЭРдин көз карандысыздыгы','Четвёртый Универсал объявляет Украинскую Народную Республику независимой.|The Fourth Universal declares the Ukrainian People’s Republic independent.|Төртүнчү Универсал Украина Эл Республикасын көз карандысыз деп жарыялайт.',[30.52,50.45],['Ukraine']);
 event('georgia',1918,'1918-georgia','Независимость Грузии|Georgian independence|Грузиянын көз карандысыздыгы','Национальный совет принимает акт независимости 26 мая.|The National Council adopts the Act of Independence on 26 May.|Улуттук кеңеш 26-майда көз карандысыздык актысын кабыл алат.',[44.8,41.72],['Georgia']);
 const dr=before.get('1848-dominican');put('1848-dominican',[[1915,1916,dr.phase.name.join('|'),dr.phase.text.join('|')],[1916,1919,'Доминиканская Республика · оккупация США|Dominican Republic · US occupation|Доминикан Республикасы · АКШнын оккупациясы','Американская интервенция приводит к установлению военного правительства в 1916 году. Оккупация вызывает сопротивление.|US intervention leads to a military government in 1916. The occupation provokes resistance.|АКШнын кийлигишүүсү 1916-жылы аскердик өкмөттүн түзүлүшүнө алып келет. Оккупация каршылык жаратат.',null,'influence']],'Dominican');
 event('brazil',1917,'early-portuguese-brazil','Бразилия вступает в мировую войну|Brazil enters the world war|Бразилия дүйнөлүк согушка кирет','После потопления торговых судов Бразилия признаёт состояние войны с Германией в октябре 1917 года.|After merchant ships are sunk, Brazil recognises a state of war with Germany in October 1917.|Соода кемелери чөктүрүлгөндөн кийин Бразилия 1917-жылдын октябрында Германия менен согуш абалын тааныйт.',[-43.17,-22.91],['Brazil'],'war');
 event('conscription',1916,'1914-australian-colonies','Австралийское голосование о призыве|Australian conscription vote|Австралияда аскерге алуу боюнча добуш берүү','28 октября избиратели отвергают обязательную отправку призывников за океан. В 1917 году повторное голосование также даёт отрицательный результат.|On 28 October voters reject compulsory overseas military service. A second vote in 1917 also rejects the proposal.|28-октябрда шайлоочулар аскерге алынгандарды океандын ары жагына милдеттүү жөнөтүүнү четке кагат. 1917-жылдагы экинчи добуш берүүдө да сунуш өтпөйт.',[144.96,-37.81],['Conscription']);
 event('armenian-genocide',1915,'late-ottoman','Геноцид армян|Armenian genocide|Армяндардын геноциди','Османские власти организуют массовые депортации и убийства армян. Дейр-эз-Зор и окружающая пустыня становятся одним из районов депортации и гибели людей в 1915–1916 годах.|Ottoman authorities organise mass deportations and killings of Armenians. Deir ez-Zor and the surrounding desert become one of the regions of deportation and mass death in 1915–1916.|Осмон бийликтери армяндарды массалык депортациялоону жана өлтүрүүнү уюштурат. Дейр-эз-Зор жана айланасындагы чөл 1915–1916-жылдары депортация жана массалык өлүм аймактарынын бири болот.',[40.14,35.33],['ArmenianGenocide'],'war');
};
