'use strict';
module.exports=(c,{G,set,end,source,event,ring,box,link,geo})=>{
 const coasts=require('./to1945-coasts.json'),U=n=>geo.union(coasts[n]),M=(...a)=>geo.merge(a);
 source('Pacific','National Archives. Instrument of Surrender of Japan (1945); United States Holocaust Memorial Museum. World War II in the Pacific.',['https://www.archives.gov/milestone-documents/surrender-of-japan','https://encyclopedia.ushmm.org/content/en/article/world-war-ii-in-the-pacific']);
 source('Burma','National Army Museum. The Far East Campaign; A Timeline of Burma and the Army.',['https://www.nam.ac.uk/explore/far-east-campaign','https://www.nam.ac.uk/explore/timeline-burma-and-army']);
 source('China','Foreign Relations of the United States, 1945, The Far East: China; Library of Congress. China: A Country Study.',['https://history.state.gov/historicaldocuments/frus1945v07','https://www.loc.gov/item/87600424/']);
 source('Asia','Foreign Relations of the United States, 1945, The British Commonwealth, The Far East; Office of the Historian. Occupation and Reconstruction of Japan.',['https://history.state.gov/historicaldocuments/frus1945v06','https://history.state.gov/milestones/1945-1952/japan-reconstruction']);
 source('MiddleEast','Foreign Relations of the United States, 1941, The British Commonwealth, The Near East and Africa; 1945, The Near East and Africa.',['https://history.state.gov/historicaldocuments/frus1941v03','https://history.state.gov/historicaldocuments/frus1945v08']);
 source('CentralAsia','Кыргызстан: национальная энциклопедия. Великая Отечественная война; История Кыргызской Республики.',['https://new.bizdin.kg/kniga/istoriya-kyrgyzskoy-respubliki']);
 const P=(id,rows,src='Pacific',meta={})=>set(id,rows,{...meta,sources:[src]});
 P('japan',[[1940,1945,'Японская империя|Empire of Japan|Япон империясы','Война в Китае и на Тихом океане. Колонии и оккупированные области показаны по отдельным датам.|War in China and the Pacific. Colonies and occupied regions follow their individual dates.|Кытайдагы жана Тынч океандагы согуш. Колониялар менен оккупацияланган жерлер өз даталары боюнча көрсөтүлөт.',M(U('Japan'),ring([[141.6,45.8],[143.5,46],[145,49],[144.8,50],[142,50],[141.6,48]]))],[1945,1946,'Япония · союзная оккупация|Japan · Allied occupation|Япония · союздаштардын оккупациясы','Акт о капитуляции подписан 2 сентября 1945 года. Начинается союзная оккупация; колониальная империя распадается.|The surrender instrument is signed on 2 September 1945. Allied occupation begins and the colonial empire ends.|Багынуу актысына 1945-жылдын 2-сентябрында кол коюлат. Союздаштардын оккупациясы башталып, колониялык империя жоюлат.',U('Japan'),'influence']]);
 end('1939-manchukuo',1945);end('1939-china-occupation',1945);
 P('1939-china-occupation',[[1940,1944,'Китай · японская оккупация|China · Japanese occupation|Кытай · япон оккупациясы','Япония удерживает значительные районы севера и востока. В Нанкине действует зависимое правительство Ван Цзинвэя.|Japan holds substantial northern and eastern regions. Wang Jingwei’s dependent government operates in Nanjing.|Япония түндүк жана чыгыштын кыйла бөлүгүн ээлейт. Нанкинде Ван Цзинвэйдин көз каранды өкмөтү иштейт.',G('1939-china-occupation'),'influence'],[1944,1945,'Китай · наступление Ити-Го|China · Operation Ichi-Go|Кытай · Ити-Го чабуулу','Японская армия захватывает дополнительные железнодорожные коридоры в Хэнани, Хунани и Гуанси.|Japanese forces capture additional railway corridors in Henan, Hunan and Guangxi.|Япон аскерлери Хэнань, Хунань жана Гуансиде кошумча темир жол багыттарын басып алат.',M(G('1939-china-occupation'),ring([[111,35],[114.5,35],[114.5,29],[112,25],[109,22.5],[107,22.5],[109,27],[111,30]])),'influence']],'China');link('japan','1939-china-occupation',1940,1945,'occupation',false);link('japan','1939-manchukuo',1940,1945,'dependency',false);
 const oldChina=G('1789-qing'),manchuria=G('1939-manchukuo');
 P('1789-qing',[[1940,1945,'Китайская республика · война с Японией|Republic of China · war with Japan|Кытай Республикасы · Япония менен согуш','Правительство Гоминьдана находится в Чунцине; коммунистические силы удерживают собственные базы. Японская оккупация отмечена отдельным слоем.|The Nationalist government is based in Chongqing; Communist forces hold their own bases. Japanese occupation has a separate layer.|Гоминьдан өкмөтү Чунцинде; коммунисттик күчтөр өз базаларын кармайт. Япон оккупациясы өзүнчө катмарда.'],[1945,1946,'Китайская республика · после капитуляции Японии|Republic of China · after Japan’s surrender|Кытай Республикасы · Япония багынгандан кийин','Японская оккупация заканчивается. В Маньчжурии находятся советские войска; противостояние Гоминьдана и КПК возобновляется.|Japanese occupation ends. Soviet troops occupy Manchuria; Nationalist–Communist conflict resumes.|Япон оккупациясы аяктайт. Маньчжурияда совет аскерлери турат; Гоминьдан менен ККПнын тирешүүсү кайра башталат.',M(oldChina,manchuria)]],'China');
 P('1945-manchuria',[[1945,1946,'Маньчжурия · советское военное присутствие|Manchuria · Soviet military presence|Маньчжурия · советтик аскердик катышуу','После наступления августа 1945 года советские войска остаются в Маньчжурии; территория не включена в СССР.|After the August 1945 offensive, Soviet troops remain in Manchuria; it is not annexed to the USSR.|1945-жылдын августундагы чабуулдан кийин совет аскерлери Маньчжурияда калат; аймак СССРге кошулган эмес.',manchuria,'influence']],'China',{coord:[123.4,41.8],color:'#a88984'});link('1939-ussr','1945-manchuria',1945,1946,'occupation',false);
 P('1789-taiwan-qing',[[1940,1945,'Тайвань · японская колония|Taiwan · Japanese colony|Тайвань · япон колониясы','Японское колониальное управление сохраняется до капитуляции 1945 года.|Japanese colonial administration continues until surrender in 1945.|Япон колониялык башкаруусу 1945-жылкы багынууга чейин сакталат.'],[1945,1946,'Тайвань · управление Китайской республики|Taiwan · Republic of China administration|Тайвань · Кытай Республикасынын башкаруусу','В октябре 1945 года администрация Китайской республики принимает капитуляцию японских сил на острове.|In October 1945 the Republic of China administration accepts the surrender of Japanese forces on the island.|1945-жылдын октябрында Кытай Республикасынын администрациясы аралдагы япон күчтөрүнүн багынышын кабыл алат.',U('Taiwan')]],'Asia');link('japan','1789-taiwan-qing',1940,1945);link('1789-qing','1789-taiwan-qing',1945,1946,'administration',false);
 P('late-joseon',[[1940,1945,'Корея · японская колония|Korea · Japanese colony|Корея · япон колониясы','Колониальная администрация проводит военную мобилизацию и принудительный труд.|Colonial administration imposes wartime mobilisation and forced labour.|Колониялык администрация согуштук мобилизацияны жана мажбурлап эмгектенүүнү жүргүзөт.'],[1945,1946,'Корея · освобождение и раздел управления|Korea · liberation and divided administration|Корея · боштондук жана башкаруунун бөлүнүшү','Японская власть прекращается. Севернее 38-й параллели действуют советские войска, южнее — американские. Два корейских государства ещё не образованы.|Japanese rule ends. Soviet forces administer north of the 38th parallel and US forces the south. The two Korean states have not yet been established.|Япон бийлиги аяктайт. 38-параллелдин түндүгүн совет, түштүгүн америкалык күчтөр башкарат. Эки корей мамлекети али түзүлө элек.',M(U('North Korea'),U('South Korea')),'influence']],'Asia');link('japan','late-joseon',1940,1945);
 const occupation='Японская военная оккупация; развиваются местные движения сопротивления.|Japanese military occupation; local resistance movements develop.|Япон аскердик оккупациясы; жергиликтүү каршылык кыймылдары өнүгөт.';
 const restored='После капитуляции Японии возобновляется британское управление.|British administration resumes after Japan’s surrender.|Япония багынгандан кийин британ башкаруусу кайра орнойт.';
 for(const[id,name,libSrc]of [['1789-konbaung','Бирма|Burma|Бирма','Burma'],['1848-burmese-coast','Прибрежная Бирма|Coastal Burma|Бирманын жээги','Burma'],['early-johor','Малайя|Malaya|Малайя','Burma'],['1848-singapore','Сингапур|Singapore|Сингапур','Burma'],['1789-dutch-malacca','Малакка|Malacca|Малакка','Burma'],['1848-hongkong','Гонконг|Hong Kong|Гонконг','Asia']]){
  const start=id==='1848-hongkong'?1941:1942;
  P(id,[[1940,start,name,'Британское управление.|British administration.|Британ башкаруусу.'],[start,1945,name.split('|').map((n,i)=>n+[' · японская оккупация',' · Japanese occupation',' · япон оккупациясы'][i]),occupation,null,'influence'],[1945,1946,name,restored]],libSrc);link('1789-great-britain',id,1940,start,'administration',false);link('japan',id,start,1945,'occupation',false);link('1789-great-britain',id,1945,1946,'administration',false);
 }
 for(const id of ['early-manila','early-cebu']){P(id,[[1940,1942,'Филиппины · Содружество|Philippines · Commonwealth|Филиппиндер · Шериктештик','Содружество под суверенитетом США; японское вторжение начинается в декабре 1941 года.|A commonwealth under US sovereignty; Japan invades in December 1941.|АКШнын суверенитетиндеги шериктештик; Япония 1941-жылдын декабрында басып кирет.'],[1942,1945,'Филиппины · японская оккупация|Philippines · Japanese occupation|Филиппиндер · япон оккупациясы',occupation,null,'influence'],[1945,1946,'Филиппины · восстановленное Содружество|Philippines · restored Commonwealth|Филиппиндер · калыбына келген Шериктештик','Союзники освобождают острова; независимость будет получена в 1946 году.|Allied forces liberate the islands; independence follows in 1946.|Союздаштар аралдарды бошотот; көз карандысыздык 1946-жылы алынат.']]);link('1789-usa',id,1940,1942,'dependency',false);link('japan',id,1942,1945,'occupation',false);link('1789-usa',id,1945,1946,'dependency',false);}
 for(const id of ['1789-batavia','early-java-sultanates','1914-riau']){P(id,[[1940,1942,'Нидерландская Ост-Индия|Dutch East Indies|Нидерланд Ост-Индиясы','Нидерландская колониальная администрация.|Dutch colonial administration.|Нидерланд колониялык администрациясы.'],[1942,1945,'Индонезия · японская оккупация|Indonesia · Japanese occupation|Индонезия · япон оккупациясы',occupation,null,'influence'],[1945,1946,'Индонезия · провозглашение республики|Indonesia · republic proclaimed|Индонезия · республиканын жарыяланышы','17 августа провозглашена независимость; начинается борьба с возвращающейся колониальной властью.|Independence is proclaimed on 17 August; conflict with returning colonial authorities begins.|17-августта көз карандысыздык жарыяланып, кайтып келген колониялык бийлик менен күрөш башталат.',null,'influence']],'Asia');link('early-dutch',id,1940,1942,'administration',false);link('japan',id,1942,1945,'occupation',false);}
 for(const[id,n]of [['1789-tayson','Вьетнам|Vietnam|Вьетнам'],['early-champa','Центральный Вьетнам|Central Vietnam|Борбордук Вьетнам'],['angkor','Камбоджа|Cambodia|Камбоджа'],['1789-lao-kingdoms','Лаос|Laos|Лаос']]){P(id,[[1940,1945,n+'','Французская администрация действует при японском военном присутствии, с 1940 года на севере Индокитая, с 1941 года на юге.|French administration continues under Japanese military presence, in northern Indochina from 1940 and in the south from 1941.|Француз администрациясы япон аскердик катышуусунда иштейт: 1940-жылдан түндүк Индокытайда, 1941-жылдан түштүктө.',null,'influence'],[1945,1946,n+'','Японский переворот в марте прекращает французское управление. После капитуляции Японии движения за независимость и возвращающиеся колониальные силы борются за власть.|A Japanese coup in March ends French administration. After Japan’s surrender, independence movements and returning colonial forces contest power.|Марттагы япон төңкөрүшү француз башкаруусун токтотот. Япония багынгандан кийин көз карандысыздык кыймылдары менен кайтып келген колониялык күчтөр бийлик үчүн күрөшөт.',null,'influence']],'Asia');link('japan',id,1941,1945,'occupation',false);}
 P('1789-bangkok',[[1940,1942,'Таиланд|Thailand|Таиланд','Таиланд воюет с французским Индокитаем и принимает японские войска в декабре 1941 года.|Thailand fights French Indochina and admits Japanese forces in December 1941.|Таиланд француз Индокытайы менен согушуп, 1941-жылдын декабрында япон аскерлерин киргизет.'],[1942,1945,'Таиланд · союз с Японией|Thailand · alliance with Japan|Таиланд · Япония менен союз','Правительство вступает в союз с Японией; действует движение «Свободный Таиланд».|The government allies with Japan; the Free Thai resistance operates.|Өкмөт Япония менен союз түзүп, «Эркин Таиланд» каршылык кыймылы иштейт.'],[1945,1946,'Таиланд|Thailand|Таиланд','После капитуляции Японии начинается дипломатическое урегулирование.|Diplomatic settlement begins after Japan’s surrender.|Япония багынгандан кийин дипломатиялык жөнгө салуу башталат.']],'Asia');
 P('1789-qajar',[[1940,1941,'Иран · Реза-шах|Iran · Reza Shah|Иран · Реза шах','Иран объявляет нейтралитет.|Iran declares neutrality.|Иран бейтараптыгын жарыялайт.'],[1941,1946,'Иран · союзная оккупация|Iran · Allied occupation|Иран · союздаштардын оккупациясы','Британские и советские войска вторгаются в августе 1941 года. Шах отрекается; Иран становится важным маршрутом поставок СССР.|British and Soviet forces invade in August 1941. The shah abdicates; Iran becomes a major supply route to the USSR.|Британ жана совет аскерлери 1941-жылдын августунда кирет. Шах тактан кетип, Иран СССРге жүк жеткирүүчү маанилүү жол болот.',G('1789-qajar'),'influence']],'MiddleEast');
 for(const[id,n]of [['1939-lebanon','Ливан|Lebanon|Ливан'],['1815-sham','Сирия|Syria|Сирия']]){P(id,[[1940,1941,n,'Французский мандат под администрацией Виши.|French mandate under Vichy administration.|Виши администрациясындагы француз мандаты.'],[1941,1943,n,'После союзной кампании действует администрация Свободной Франции.|Free French administration follows the Allied campaign.|Союздаштардын жортуулунан кийин Эркин Франциянын администрациясы иштейт.'],[1943,1946,n,'Национальные органы власти добиваются независимости. Иностранные войска покинут страну в 1946 году.|National authorities secure independence; foreign troops will leave in 1946.|Улуттук бийлик көз карандысыздыкка жетишет; чет элдик аскерлер 1946-жылы чыгып кетет.']],'MiddleEast');link('late-france',id,1940,1943,'administration',false);}
 P('late-kyrgyz-tianshan',[[1940,1941,'Кыргызская ССР|Kyrgyz SSR|Кыргыз ССРи','Союзная республика в составе СССР.|A union republic within the USSR.|СССРдин курамындагы союздук республика.'],[1941,1946,'Кыргызская ССР · военные годы|Kyrgyz SSR · wartime|Кыргыз ССРи · согуш жылдары','Жители республики воюют на фронтах. В Кыргызстан эвакуируются люди и предприятия; промышленность и сельское хозяйство работают для военных нужд.|Residents serve at the fronts. People and factories evacuate to Kyrgyzstan; industry and agriculture support the war effort.|Республиканын тургундары фронттордо согушат. Кыргызстанга адамдар менен ишканалар көчүрүлүп, өнөр жай жана айыл чарба согуштук муктаждыктарды камсыздайт.']],'CentralAsia');
 event('pearl-harbor',1941,'hawaii','Нападение на Пёрл-Харбор|Attack on Pearl Harbor|Пёрл-Харборго кол салуу','7 декабря японская авиация атакует американскую базу.|Japanese aircraft attack the US base on 7 December.|Япон авиациясы 7-декабрда АКШ базасына кол салат.',[-157.95,21.35],['Pacific'],'war');
 event('singapore',1942,'1848-singapore','Падение Сингапура|Fall of Singapore|Сингапурдун кулашы','Британский гарнизон капитулирует 15 февраля.|The British garrison surrenders on 15 February.|Британ гарнизону 15-февралда багынат.',[103.82,1.35],['Burma'],'war');
 event('kohima',1944,'1939-india','Импхал и Кохима|Imphal and Kohima|Импхал жана Кохима','Японское наступление в Индии остановлено.|The Japanese offensive into India is stopped.|Индиядагы япон чабуулу токтотулат.',[94.1,25.67],['Burma'],'war');
 event('surrender-japan',1945,'japan','Капитуляция Японии|Japan’s surrender|Япониянын багынышы','2 сентября подписан акт о капитуляции.|The surrender instrument is signed on 2 September.|Багынуу актысына 2-сентябрда кол коюлат.',[139.76,35.4],['Pacific'],'diplomacy');
 event('hiroshima',1945,'japan','Атомная бомбардировка Хиросимы|Atomic bombing of Hiroshima|Хиросиманы атомдук бомбалоо','6 августа США применяют атомную бомбу; 9 августа следует бомбардировка Нагасаки.|The US drops an atomic bomb on 6 August; Nagasaki is bombed on 9 August.|АКШ 6-августта атом бомбасын таштайт; 9-августта Нагасаки бомбаланат.',[132.46,34.39],['Pacific'],'war');
};
