'use strict';
module.exports=(c,{G,set,source,event,box,before})=>{
 source('Africa','UNESCO. General History of Africa, VI: Africa in the Nineteenth Century until the 1880s; VII: Africa under Colonial Domination, 1880–1935.',['https://www.unesco.org/en/general-history-africa','https://www.unesco.org/en/articles/general-history-africa-vii-africa-under-colonial-domination-1880-1935']);
 source('Egypt','National Army Museum. Egypt and Sudan.',['https://www.nam.ac.uk/explore/egypt-and-sudan']);
 source('Protectorates','Archives diplomatiques françaises. Protectorats et mandat français (1881–1956); Traité du Bardo (1881); Traité de Fès (1912).',['https://www.diplomatie.gouv.fr/fr/archives-bibliotheque/s-orienter-dans-les-fonds-et-collections/protectorats-et-mandat-francais-1881-1956']);
 source('Congo','Royal Museum for Central Africa. Colonial History: Congo Free State and Belgian Congo.',['https://www.afrikamuseum.be/en/about_us/viewpoints','https://www.africamuseum.be/publication_docs/museum%20as%20rift%20zone.pdf']);
 source('SouthAfrica','South African History Online. The Union of South Africa 1910; Anglo-Zulu Wars 1879–1896; South African Government. History.',['https://sahistory.org.za/article/union-south-africa-1910','https://sahistory.org.za/article/anglo-zulu-wars-1879-1896','https://www.gov.za/about-sa/history']);
 source('Basotho','Library of Congress. Basutoland; South African History Online. Lesotho Timeline.',['https://www.loc.gov/item/98681209/','https://sahistory.org.za/article/lesotho-timeline']);
 source('Sokoto','TDV İslâm Ansiklopedisi. Sokoto; British Library, EAP535/3/7/1: Report on Sokoto Province, 31 March 1903.',['https://islamansiklopedisi.org.tr/sokoto','https://searcharchives.bl.uk/catalog/037-002752968']);
 source('Benin','National Museum of African Art. Benin Bronzes: Ambassadors of the Oba.',['https://africa.si.edu/exhibitions/benin-bronzes-ambassadors-oba']);
 source('Namibia','Mémorial de la Shoah. Herero et Nama dans le Sud-Ouest africain allemand, 1904–1908.',['https://www.memorialdelashoah.org/evenements-expositions/expositions/archives-des-expositions/premier-genocide-xxe-siecle.html']);
 const put=(id,rows,s='Africa',meta={})=>set(id,rows,{sources:['to1914'+s],...meta}),fr='#889ab0',br='#a2916a',de='#998573';
 put('early-ottoman-egypt-sham',[[1849,1882,'Египет · династия Мухаммада Али|Egypt · Muhammad Ali dynasty|Мисир · Мухаммад Али династиясы','Наследственные правители сохраняют османский сюзеренитет. Суэцкий канал открывается в 1869 году.|Hereditary rulers retain Ottoman suzerainty. The Suez Canal opens in 1869.|Мураскор башкаруучулар осмон үстөмдүгүн сактайт. Суэц каналы 1869-жылы ачылат.'],[1882,1914,'Египет · британская оккупация|Egypt · British occupation|Мисир · британ оккупациясы','Британские войска занимают страну; хедив и формальный османский сюзеренитет сохраняются.|British troops occupy the country; the khedive and formal Ottoman suzerainty remain.|Британ аскерлери өлкөнү ээлейт; хедив жана формалдуу осмон үстөмдүгү сакталат.',null,'influence',br],[1914,1915,'Египет · британский протекторат|Egypt · British protectorate|Мисир · британ протектораты','В декабре 1914 года Британия объявляет протекторат и прекращение османского сюзеренитета.|In December 1914 Britain declares a protectorate and ends Ottoman suzerainty.|1914-жылдын декабрында Британия протекторатты жана осмон үстөмдүгүнүн токтошун жарыялайт.',null,'influence',br]],'Egypt');
 for(const id of ['early-funj','dongola'])put(id,[[1849,1885,'Судан · египетское управление|Sudan · Egyptian administration|Судан · Мисир башкаруусу','Египетское управление распространяется по долине Нила; с 1881 года развивается махдистское восстание.|Egyptian administration extends along the Nile; the Mahdist revolt develops from 1881.|Мисир башкаруусу Нил өрөөнүнө жайылат; 1881-жылдан махдисттик көтөрүлүш өсөт.'],[1885,1898,'Махдистский Судан|Mahdist Sudan|Махдисттик Судан','После взятия Хартума создаётся государство с центром в Омдурмане.|After Khartoum falls, a state centred on Omdurman is established.|Хартум алынгандан кийин борбору Омдурманда болгон мамлекет түзүлөт.',null,'polity','#7a956f'],[1898,1899,'Судан · англо-египетское завоевание|Sudan · Anglo-Egyptian conquest|Судан · англо-мисир басып алуусу','Армия Китченера побеждает при Омдурмане; махдистское сопротивление продолжается.|Kitchener’s army wins at Omdurman; Mahdist resistance continues.|Китченердин аскери Омдурманда жеңет; махдисттердин каршылыгы уланат.',null,'influence',br],[1899,1915,'Англо-Египетский Судан|Anglo-Egyptian Sudan|Англо-Мисир Суданы','Установлен кондоминиум с преобладающим британским контролем.|A condominium is established under predominant British control.|Британиянын үстөм көзөмөлүндөгү кондоминиум түзүлөт.',null,'polity',br]],'Egypt');
 for(const id of ['early-ottoman-tunis','kairouan'])put(id,[[1849,1881,'Тунис · Хусейниды|Tunis · Husaynids|Тунис · Хусейнилер','Беи сохраняют широкое самоуправление при формальном османском сюзеренитете.|The beys retain broad self-government under formal Ottoman suzerainty.|Бейлер формалдуу осмон үстөмдүгүндө кеңири өз алдынча башкарууну сактайт.'],[1881,1915,'Тунис · французский протекторат|Tunisia · French protectorate|Тунис · француз протектораты','Договор Бардо устанавливает французский протекторат; бейский престол сохраняется.|The Treaty of Bardo establishes a French protectorate; the bey’s throne remains.|Бардо келишими француз протекторатын орнотот; бейдин тактысы сакталат.',null,'influence',fr]],'Protectorates');
 for(const id of ['1789-alawite','marrakesh'])put(id,[[1849,1912,'Марокко · Алауитский султанат|Morocco · Alawite Sultanate|Марокко · Алауит султандыгы','Султанат сохраняет самостоятельность на фоне европейского давления.|The sultanate remains independent amid European pressure.|Султандык европалык басымга карабай өз алдынчалыгын сактайт.'],[1912,1915,'Марокко · французский протекторат|Morocco · French protectorate|Марокко · француз протектораты','Фесский договор устанавливает протекторат Франции. На севере и юге выделяются испанские зоны; султан сохраняет престол.|The Treaty of Fez establishes French protection. Spanish zones are designated in the north and south; the sultan retains his throne.|Фес келишими Франциянын протекторатын орнотот. Түндүктө жана түштүктө испан зоналары бөлүнөт; султан тактысын сактайт.',null,'influence',fr]],'Protectorates');
 put('early-algiers',[[1849,1871,'Алжир · французское завоевание|Algeria · French conquest|Алжир · француз басып алуусу','Французская власть расширяется в северных областях; в 1857 году завоёвана Кабилия.|French rule expands in northern districts; Kabylia is conquered in 1857.|Француз бийлиги түндүктөгү аймактарга кеңейет; 1857-жылы Кабилия алынат.'],[1871,1915,'Алжир · французская колония|Algeria · French colony|Алжир · француз колониясы','Подавление восстания 1871 года сопровождается конфискацией земель и усилением колониального управления.|Suppression of the 1871 revolt brings land confiscation and stronger colonial rule.|1871-жылкы көтөрүлүштүн басылышы жерлердин тартып алынышы жана колониялык башкаруунун күчөшү менен коштолот.',[[[-2,35],[1,36.7],[4,36.9],[7.8,37],[8.5,35],[6.5,33],[1,32],[-1.5,33]]],'polity',fr]]);
 put('early-tripoli',[[1849,1912,'Триполитания · Османское государство|Tripolitania · Ottoman state|Триполитания · Осмон мамлекети','Османское управление сохраняется до итальянского вторжения 1911 года.|Ottoman administration continues until Italy’s invasion in 1911.|Осмон башкаруусу 1911-жылкы Италиянын басып киришине чейин сакталат.'],[1912,1915,'Триполитания · итальянские прибрежные опорные пункты|Tripolitania · Italian coastal footholds|Триполитания · Италиянын жээктеги таянычтары','Османская сторона отказывается от управления; итальянский контроль ограничен прежде всего побережьем, сопротивление продолжается.|Ottoman administration is relinquished; Italian control is concentrated on the coast while resistance continues.|Осмон башкаруусу токтойт; Италиянын көзөмөлү негизинен жээкте, каршылык уланат.',[[[12,32.1],[13.5,32.9],[15.2,32.6],[15.3,31.8],[13.2,31.8]]],'influence','#819b78']]);
 put('ethiopia',[[1849,1855,'аль-Хабаша · региональные правители|Al-Habasha · regional rulers|ал-Хабаша · аймактык башкаруучулар','Высокогорные области разделены между соперничающими правителями.|Highland regions are divided among rival rulers.|Бийик тоолуу аймактар атаандаш башкаруучулардын ортосунда бөлүнгөн.'],[1855,1889,'Эфиопская империя · восстановление центральной власти|Ethiopian Empire · central authority restored|Эфиопия империясы · борбордук бийликтин калыбына келиши','Теодрос II, затем Йоханныс IV укрепляют императорскую власть.|Tewodros II and then Yohannes IV strengthen imperial authority.|Адегенде Теодрос II, андан кийин Йоханныс IV императордук бийликти күчөтөт.'],[1889,1915,'Эфиопская империя · Менелик II|Ethiopian Empire · Menelik II|Эфиопия империясы · Менелик II','Менелик расширяет владения на юг. Победа при Адуа в 1896 году сохраняет независимость от Италии.|Menelik expands southward. Victory at Adwa in 1896 preserves independence from Italy.|Менелик ээликтерин түштүккө кеңейтет. 1896-жылы Адуадагы жеңиш Италиядан көз карандысыздыкты сактайт.',[[[36,14.4],[39.2,14.5],[40.8,12.5],[43.2,9.5],[45,8],[43,5.5],[38,4.7],[35,6.5],[34.5,10]]]]]);
 put('1789-harar',[[1849,1875,'Харар · эмират|Harar · emirate|Харар · эмирлик','Эмир управляет городом и торговыми путями.|The emir governs the city and its trade routes.|Эмир шаарды жана соода жолдорун башкарат.'],[1875,1885,'Харар · египетская оккупация|Harar · Egyptian occupation|Харар · Мисир оккупациясы','Город занят египетскими войсками.|Egyptian troops occupy the city.|Шаарды Мисир аскерлери ээлейт.',null,'influence'],[1885,1887,'Харар · восстановленный эмират|Harar · restored emirate|Харар · калыбына келген эмирлик','После ухода египтян эмир восстанавливает власть.|After Egyptian withdrawal the emir restores his rule.|Мисир аскерлери кеткенден кийин эмир бийлигин калыбына келтирет.'],[1887,1915,'Харар · Эфиопия|Harar · Ethiopia|Харар · Эфиопия','После битвы при Челенко город включён во владения Менелика.|After the battle of Chelenqo the city is incorporated into Menelik’s domains.|Челенко салгылашуусунан кийин шаар Менеликтин ээликтерине кирет.',null,'polity','#87996e']]);
 put('1914-eritrea',[[1890,1915,'Эритрея · итальянская колония|Eritrea · Italian colony|Эритрея · Италия колониясы','Колония объединяет итальянские владения на побережье Красного моря и высокогорье вокруг Асмэры.|The colony combines Italian Red Sea possessions and highlands around Asmara.|Колония Кызыл деңиз жээгиндеги Италия ээликтерин жана Асмэра айланасындагы тоолуу жерлерди бириктирет.',[[[36.5,14.7],[38.4,17.6],[39.2,16],[40.5,14.5],[43,12.5],[41.8,12.4],[39.8,14.5],[37.5,14.2]]]]],undefined,{region:'africa',coord:[38.9,15.3],color:'#819b78'});
 put('1789-zanzibar',[[1849,1861,'Занзибар · Оман|Zanzibar · Oman|Занзибар · Оман','Остров является центром восточноафриканских владений оманского султана.|The island is the centre of the Omani sultan’s East African possessions.|Арал Оман султанынын Чыгыш Африкадагы ээликтеринин борбору.'],[1861,1890,'Султанат Занзибар|Sultanate of Zanzibar|Занзибар султандыгы','Занзибар признан отдельным султанатом после разделения с Оманом.|Zanzibar is recognised as a separate sultanate after division from Oman.|Омандан бөлүнгөндөн кийин Занзибар өзүнчө султандык катары таанылат.'],[1890,1915,'Занзибар · британский протекторат|Zanzibar · British protectorate|Занзибар · британ протектораты','Султан сохраняет престол под британским протекторатом.|The sultan retains his throne under British protection.|Султан британ протекторатында тактысын сактайт.',null,'influence',br]]);
 for(const [id,y,local,owner,src] of [
 ['benin',1897,'Бенин|Benin|Бенин','британское управление|British administration|британ башкаруусу','Benin'],
 ['1815-sokoto',1903,'Сокото|Sokoto|Сокото','Северная Нигерия|Northern Nigeria|Түндүк Нигерия','Sokoto'],
 ['1789-asante',1901,'Ашанти|Asante|Ашанти','британская колония|British colony|британ колониясы','Africa'],
 ['1789-dahomey',1894,'Дагомея|Dahomey|Дагомея','французская колония|French colony|француз колониясы','Africa'],
 ['1789-cayor',1886,'Кайор|Cayor|Кайор','французский Сенегал|French Senegal|француз Сенегалы','Africa'],
 ['1789-jolof',1890,'Джолоф|Jolof|Жолоф','французский Сенегал|French Senegal|француз Сенегалы','Africa'],
 ['1789-futa-jallon',1896,'Фута-Джаллон|Futa Jallon|Фута-Жаллон','французская Гвинея|French Guinea|француз Гвинеясы','Africa'],
 ['1789-futa-toro',1891,'Фута-Торо|Futa Toro|Фута-Торо','французское управление|French administration|француз башкаруусу','Africa'],
 ['1789-imerina',1896,'Имерина|Imerina|Имерина','французский Мадагаскар|French Madagascar|француз Мадагаскары','Africa'],
 ['1848-ndebele',1893,'Ндебеле|Ndebele|Ндебеле','власть Британской Южно-Африканской компании|British South Africa Company rule|Британ Түштүк Африка компаниясынын бийлиги','Africa']
 ]){const old=before.get(id),name=local.split('|'),after=owner.split('|');put(id,[[1849,y,name,'Местная монархия сохраняет власть; усиливается давление европейских держав.|Local monarchy remains in power as European pressure increases.|Европа державаларынын басымы күчөсө да жергиликтүү монархия бийлигин сактайт.'],[y,1915,name.map((n,i)=>n+' · '+after[i]),'После завоевания меняются управление и земельные отношения; местные общества продолжают существовать.|Conquest changes government and land relations; local societies continue to exist.|Басып алуу башкарууну жана жер мамилелерин өзгөртөт; жергиликтүү коомдор жашоосун улантат.',null,'polity',owner.includes('French')?fr:br]],src);}
 put('1789-segou',[[1849,1861,'Сегу · Бамана|Ségou · Bamana|Сегу · Бамана','Баманское государство контролирует средний Нигер.|The Bamana state controls the middle Niger.|Бамана мамлекети ортоңку Нигерди көзөмөлдөйт.'],[1861,1890,'Сегу · государство Умара Талла и Ахмаду|Ségou · Umar Tall and Ahmadu’s state|Сегу · Умар Талл жана Ахмадунун мамлекети','Сегу завоёван войсками Умара Талла; затем здесь правит Ахмаду.|Umar Tall’s forces conquer Ségou; Ahmadu subsequently rules here.|Умар Таллдын аскери Сегуну алат; кийин бул жерде Ахмаду башкарат.'],[1890,1915,'Сегу · Французский Судан|Ségou · French Sudan|Сегу · Француз Суданы','Французские войска занимают Сегу.|French troops occupy Ségou.|Француз аскерлери Сегуну ээлейт.',null,'polity',fr]]);
 put('1914-samori',[[1878,1898,'Васулу · Самори Туре|Wassoulou · Samori Touré|Васулу · Самори Туре','Самори создаёт военное государство и сопротивляется французскому завоеванию; под давлением его центр смещается к востоку.|Samori builds a military state and resists French conquest; pressure shifts its centre eastward.|Самори аскердик мамлекет түзүп, француз басып алуусуна каршы турат; басымдын айынан борбору чыгышка жылат.',[[[-10.5,8],[-7.8,8],[-6.7,10],[-8,12],[-10.5,11]]],'influence'] ],undefined,{region:'africa',coord:[-9.3,10.6],color:'#8a9870'});
 for(const [id,y] of [['timbuktu-late',1894],['djenne-late',1893],['gao',1899],['early-songhay-dendi',1901],['1789-oyo',1893],['ife',1893]]){const n=before.get(id).phase.name||before.get(id).entry.name;const french=!['1789-oyo','ife'].includes(id);put(id,[[1849,y,n,'Местные правители и торговые общины сохраняют региональные связи.|Local rulers and trading communities maintain regional networks.|Жергиликтүү башкаруучулар жана соода жамааттары аймактык байланыштарын сактайт.'],[y,1915,n.map((s,i)=>s.split(' · ')[0]+(french?[' · французское управление',' · French administration',' · француз башкаруусу']:[' · британское управление',' · British administration',' · британ башкаруусу'])[i]),'Колониальное подчинение меняет систему власти; городские и сельские общества сохраняются.|Colonial subordination changes government; urban and rural societies endure.|Колониялык баш ийүү бийлик түзүлүшүн өзгөртөт; шаардык жана айылдык коомдор сакталат.',null,'polity',french?fr:br]]);}
 const congo=[[[12.3,-6],[15,-5],[17,-7],[21,-7],[24,-11],[28,-12],[30,-9],[29,-4],[30,1],[28,4.5],[23,5],[19,4],[18,1],[16,-2],[13,-4]]];
 put('1914-congo',[[1885,1908,'Свободное государство Конго|Congo Free State|Конго Эркин мамлекети','Владение Леопольда II расширяется по бассейну Конго; принудительный труд и насилие сопровождают сбор каучука.|Leopold II’s domain expands across the Congo Basin; forced labour and violence accompany rubber extraction.|Леопольд IIнин ээлиги Конго алабына кеңейет; каучук жыйноо мажбурланган эмгек жана зомбулук менен коштолот.',congo,'influence'],[1908,1915,'Бельгийское Конго|Belgian Congo|Бельгия Конгосу','Бельгийское государство принимает управление колонией.|The Belgian state takes over colonial administration.|Бельгия мамлекети колонияны башкарууну өзүнө алат.',congo,'polity']],'Congo',{region:'africa',coord:[23,-3],color:'#a2a06f'});
 const eastAfrica=[[[29.3,-1],[30.8,-1],[31.7,-1],[33.9,-1],[37.6,-3],[40.4,-4.7],[39.5,-8],[40.3,-10.5],[35,-11.5],[32,-9],[30,-6],[29.3,-3]]];
 put('1914-german-east',[[1885,1891,'Германская Восточная Африка · компания|German East Africa · Company|Герман Чыгыш Африкасы · компания','Компания заявляет владения и расширяет контроль; сопротивление на побережье вызывает военное вмешательство.|The Company asserts possessions and expands control; coastal resistance brings military intervention.|Компания ээликтерин жарыялап, көзөмөлүн кеңейтет; жээктеги каршылык аскердик кийлигишүүгө алып келет.',eastAfrica,'influence'],[1891,1915,'Германская Восточная Африка|German East Africa|Герман Чыгыш Африкасы','Имперское управление вводит налоги и принудительный труд. Восстание Маджи-Маджи начинается в 1905 году.|Imperial administration imposes taxation and forced labour. The Maji Maji rebellion begins in 1905.|Империялык башкаруу салыктарды жана мажбурланган эмгекти киргизет. Мажи-Мажи көтөрүлүшү 1905-жылы башталат.',eastAfrica,'polity']],undefined,{region:'africa',coord:[35,-6],color:de});
 put('1914-namibia',[[1884,1915,'Германская Юго-Западная Африка|German South West Africa|Герман Түштүк-Батыш Африкасы','Германская колонизация сопровождается отчуждением земли. В 1904–1908 годах германские войска совершают геноцид гереро и нама.|German colonisation brings land dispossession. In 1904–08 German forces perpetrate genocide against the Herero and Nama.|Герман колониялаштыруусу жерди тартып алуу менен коштолот. 1904–1908-жылдары герман аскерлери гереро жана нама элдерине геноцид жасайт.',[[[12,-17],[18,-17],[20,-18],[20,-28],[17,-28.5],[15,-24],[14,-20]]],'influence',de]],'Namibia',{region:'africa',coord:[17,-22]});
 put('1914-kenya',[[1895,1915,'Британская Восточная Африка|British East Africa|Британ Чыгыш Африкасы','Протекторат объединяет прибрежные владения и внутренние области; железная дорога связывает Момбасу с озером Виктория.|The protectorate links coastal and inland districts; a railway connects Mombasa with Lake Victoria.|Протекторат жээктеги жана ички аймактарды бириктирет; темир жол Момбасаны Виктория көлү менен байланыштырат.',[[[34,-1],[37.6,-3],[40.4,-4.7],[41,-2],[40,1],[37,4],[34,4]]],'influence',br]],undefined,{region:'africa',coord:[37,0]});
 put('1914-uganda',[[1894,1915,'Уганда · британский протекторат|Uganda · British protectorate|Уганда · британ протектораты','Протекторат начинается с Буганды и расширяется на соседние государства и общества.|The protectorate begins in Buganda and expands over neighbouring states and societies.|Протекторат Бугандадан башталып, коңшу мамлекеттерге жана коомдорго кеңейет.',box(30,-1,34,3),'influence',br]],undefined,{region:'africa',coord:[32.5,.3]});
 put('1848-zulu',[[1849,1879,'Зулусское королевство|Zulu kingdom|Зулу падышалыгы','Мпанде, затем Кечвайо правят королевством.|Mpande and then Cetshwayo govern the kingdom.|Падышалыкты Мпанде, андан кийин Кечвайо башкарат.'],[1879,1887,'Зулуленд · раздел и сопротивление|Zululand · partition and resistance|Зулуленд · бөлүнүү жана каршылык','После англо-зулусской войны королевство разделено; борьба за власть продолжается.|After the Anglo-Zulu War the kingdom is partitioned; struggles for power continue.|Англо-зулу согушунан кийин падышалык бөлүнөт; бийлик үчүн күрөш уланат.',null,'influence',br],[1887,1915,'Зулуленд · британское управление|Zululand · British administration|Зулуленд · британ башкаруусу','Зулуленд аннексирован Британией; в 1897 году включён в Наталь.|Britain annexes Zululand; in 1897 it is incorporated into Natal.|Британия Зулулендди аннексиялайт; 1897-жылы ал Наталга кирет.',null,'polity',br]],'SouthAfrica');
 put('1848-basotho',[[1849,1868,'Басуто · Мошвешве I|Basotho · Moshoeshoe I|Басуто · Мошвешве I','Королевство борется с Оранжевым Свободным Государством за землю.|The kingdom contests land with the Orange Free State.|Падышалык Оранж Эркин Мамлекети менен жер үчүн күрөшөт.'],[1868,1871,'Басутоленд · британская защита|Basutoland · British protection|Басутоленд · британ коргоосу','Мошвешве добивается британской защиты.|Moshoeshoe secures British protection.|Мошвешве британ коргоосуна жетишет.'],[1871,1884,'Басутоленд · Капская колония|Basutoland · Cape Colony|Басутоленд · Кап колониясы','Управление передано Капской колонии; война из-за разоружения начинается в 1880 году.|Administration passes to the Cape Colony; the Gun War begins in 1880.|Башкаруу Кап колониясына өтөт; куралсыздандырууга байланыштуу согуш 1880-жылы башталат.'],[1884,1915,'Басутоленд · отдельная коронная территория|Basutoland · separate Crown territory|Басутоленд · өзүнчө таажы аймагы','Восстановлено прямое британское управление. В Южно-Африканский Союз территория не входит.|Direct British administration is restored. The territory is not part of the Union of South Africa.|Түз британ башкаруусу калыбына келет. Аймак Түштүк Африка Союзуна кирбейт.',null,'influence',br]],'Basotho');
 const transvaal=[[[25.3,-25],[27,-22.5],[31,-22.5],[32,-25.5],[30,-27.3],[27,-27.5]]],orange=[[[24.5,-28.6],[27,-26.9],[29.6,-28.5],[28.7,-28.8],[27,-30.4],[25.5,-30.7]]];
 put('1914-transvaal',[[1852,1877,'Южно-Африканская Республика · Трансвааль|South African Republic · Transvaal|Түштүк Африка Республикасы · Трансвааль','Санд-Риверская конвенция признаёт независимость бурских поселенцев к северу от Вааля.|The Sand River Convention recognises Boer settler independence north of the Vaal.|Санд-Ривер конвенциясы Ваалдын түндүгүндөгү бур конуштарынын көз карандысыздыгын тааныйт.',transvaal],[1877,1881,'Трансвааль · британская аннексия|Transvaal · British annexation|Трансвааль · британ аннексиясы','Британия аннексирует республику; начинается сопротивление.|Britain annexes the republic; resistance follows.|Британия республиканы аннексиялайт; каршылык башталат.',transvaal,'polity',br],[1881,1902,'Южно-Африканская Республика|South African Republic|Түштүк Африка Республикасы','Самоуправление восстановлено. Открытие золота на Витватерсранде усиливает миграцию и конфликты.|Self-government is restored. Gold discoveries on the Witwatersrand intensify migration and conflict.|Өз алдынча башкаруу калыбына келет. Витватерсрандда алтындын табылышы көчүүнү жана жаңжалдарды күчөтөт.',transvaal],[1902,1910,'Трансвааль · британская колония|Transvaal · British colony|Трансвааль · британ колониясы','Мир в Феринихинге завершает войну; республика становится британской колонией.|The Peace of Vereeniging ends the war; the republic becomes a British colony.|Феринихинг тынчтыгы согушту аяктатат; республика британ колониясына айланат.',transvaal,'polity',br]],'SouthAfrica',{region:'africa',coord:[28.2,-25.7],color:'#9a9769'});
 put('1914-orange',[[1854,1902,'Оранжевое Свободное Государство|Orange Free State|Оранж Эркин Мамлекети','Бурская республика возникает после Блумфонтейнской конвенции.|A Boer republic is established after the Bloemfontein Convention.|Блумфонтейн конвенциясынан кийин бур республикасы түзүлөт.',orange],[1902,1910,'Оранжевая колония|Orange River Colony|Оранж колониясы','После войны территория становится британской колонией.|After the war the territory becomes a British colony.|Согуштан кийин аймак британ колониясына айланат.',orange,'polity',br]],'SouthAfrica',{region:'africa',coord:[26.2,-29.1],color:'#aa946d'});
 for(const id of ['1789-cape','1848-natal']){const old=before.get(id);put(id,[[1849,1910,old.phase.name,'Британская колония расширяет переселенческое хозяйство; политические права распределены неравномерно.|The British colony expands settler agriculture; political rights remain unequal.|Британ колониясында көчүп келгендердин чарбасы кеңейет; саясий укуктар тең эмес.']],'SouthAfrica');}
 put('1914-south-africa',[[1910,1915,'Южно-Африканский Союз|Union of South Africa|Түштүк Африка Союзу','Капская колония, Наталь, Трансвааль и Оранжевая колония объединяются в доминион с властью белого меньшинства.|The Cape, Natal, Transvaal and Orange River colonies unite as a dominion governed by a white minority.|Кап, Наталь, Трансвааль жана Оранж колониялары ак түстүү азчылык башкарган доминионго биригет.',[...G('1789-cape'),...G('1848-natal'),...transvaal,...orange,...G('1848-zulu')],'polity',br]],'SouthAfrica',{region:'africa',coord:[25,-29]});
 for(const [id,y,entry,title,text,coord,kind] of [
 ['suez',1869,'early-ottoman-egypt-sham','Открытие Суэцкого канала|Opening of the Suez Canal|Суэц каналынын ачылышы','Канал соединяет Средиземное и Красное моря.|The canal connects the Mediterranean and Red seas.|Канал Жер Ортолук жана Кызыл деңиздерди бириктирет.',[32.34,30.58],'culture'],
 ['adwa',1896,'ethiopia','Битва при Адуа|Battle of Adwa|Адуа салгылашуусу','Эфиопские войска побеждают итальянскую армию.|Ethiopian forces defeat the Italian army.|Эфиопия аскерлери Италия армиясын жеңет.',[38.9,14.16],'war'],
 ['omdurman',1898,'early-funj','Битва при Омдурмане|Battle of Omdurman|Омдурман салгылашуусу','Англо-египетская армия наносит решающее поражение махдистским силам.|The Anglo-Egyptian army decisively defeats Mahdist forces.|Англо-мисир аскери махдисттик күчтөрдү чечкиндүү жеңет.',[32.48,15.65],'war'],
 ['zulu',1879,'1848-zulu','Англо-зулусская война|Anglo-Zulu War|Англо-зулу согушу','Зулусская победа при Исандлване сменяется британским завоеванием королевства.|The Zulu victory at Isandlwana is followed by British conquest of the kingdom.|Исандлванадагы зулу жеңишинен кийин Британия падышалыкты басып алат.',[30.65,-28.36],'war'],
 ['boer',1902,'1914-transvaal','Мир в Феринихинге|Peace of Vereeniging|Феринихинг тынчтыгы','Бурские республики утрачивают независимость.|The Boer republics lose their independence.|Бур республикалары көз карандысыздыгын жоготот.',[27.93,-26.67],'diplomacy'],
 ['union',1910,'1914-south-africa','Южно-Африканский Союз|Union of South Africa|Түштүк Африка Союзу','Четыре колонии объединяются в доминион.|Four colonies unite as a dominion.|Төрт колония доминионго биригет.',[18.42,-33.93],'politics'],
 ['herero',1904,'1914-namibia','Геноцид гереро и нама|Genocide of the Herero and Nama|Гереро жана нама геноциди','Германские колониальные войска применяют массовое уничтожение, изгнание и лагеря.|German colonial forces employ mass killing, expulsion and camps.|Герман колониялык аскерлери массалык өлтүрүүнү, сүргүндү жана лагерлерди колдонот.',[17.1,-20.5],'war'],
 ['maji',1905,'1914-german-east','Восстание Маджи-Маджи|Maji Maji rebellion|Мажи-Мажи көтөрүлүшү','Общины юга Германской Восточной Африки восстают против колониального управления.|Communities in southern German East Africa rise against colonial rule.|Герман Чыгыш Африкасынын түштүгүндөгү жамааттар колониялык бийликке каршы чыгат.',[38.5,-9.3],'war']])event(id,y,entry,title,text,coord,kind);
};
