'use strict';
// Dates are inclusive. Lines are schematic directions between historical centres,
// not georeferenced daily itineraries. Keep this independent of territorial claims.
const T=s=>s.split('|');
const sources={
 caliphs:{title:'TDV İslâm Ansiklopedisi. Hulefâ-yi Râşidîn; Yermük Savaşı; İbn Abdülhakem. Fütûhu Mısr.',urls:['https://islamansiklopedisi.org.tr/hulefa-yi-rasidin','https://islamansiklopedisi.org.tr/yermuk-savasi','https://islamansiklopedisi.org.tr/mukavkis']},
 umayyad:{title:'Hugh Kennedy. The Great Arab Conquests; The Metropolitan Museum of Art. The Art of the Umayyad Period (661–750).',urls:['https://www.metmuseum.org/essays/the-art-of-the-umayyad-period-661-750']},
 mongols:{title:'Columbia University, Asia for Educators. The Mongols in World History: The Mongol Conquests; Library of Congress. Mongolia: A Country Study.',urls:['https://afe.easia.columbia.edu/mongols/conquests/conquests_2c.htm','https://afe.easia.columbia.edu/mongols/conquests/conquests_2d.htm','https://tile.loc.gov/storage-services/public/gdcmassbookdig/mongoliacountrys00word_0/mongoliacountrys00word_0.pdf']},
 ottoman:{title:'The Metropolitan Museum of Art. The Eastern Mediterranean, 1400–1600; Venice’s Principal Muslim Trading Partners; TDV İslâm Ansiklopedisi. Bağdat.',urls:['https://82nd-and-fifth.metmuseum.org/toah/ht/08/wae.html','https://www.metmuseum.org/essays/venices-principal-muslim-trading-partners-the-mamluks-the-ottomans-and-the-safavids','https://islamansiklopedisi.org.tr/bagdat']},
 russia:{title:'Атлас Азиатской России. Переселенческое управление, 1914; Президентская библиотека: освоение Сибири, Айгунский и Пекинский договоры.',urls:['https://www.loc.gov/item/2021666105/','https://www.prlib.ru/history/619270','https://www.prlib.ru/node/619718']},
 alaska:{title:'National Park Service. Russian Alaska; Three Saints Bay Site National Historic Landmark; Камчатский краевой объединённый музей. Памятный крест В. Атласова, 1697.',urls:['https://www.nps.gov/subjects/nhlalaska/russian-alaska.htm','https://www.nps.gov/places/three-saints-bay-site.htm','https://kamchatka-museum.ru/pamyatnyj-krest-ustanovlennyj-v-atlasovym-v-chest-prisoedineniya-kamchatki-k-territorii-rossijskogo-gosudarstva/']},
 qing:{title:'Yingcong Dai. Qing Military Institutions and Their Effects on Government, Economy, and Society, 1640–1800; Peter C. Perdue. China Marches West; The Cambridge World History of Genocide. The Qing Extermination of the Zünghars.',urls:['https://www.cambridge.org/core/journals/journal-of-chinese-history/article/qing-military-institutions-and-their-effects-on-government-economy-and-society-16401800/E1FDAA965C5B67C12274B2B3408AE206','https://www.cambridge.org/core/books/abs/cambridge-world-history-of-genocide/qing-extermination-of-the-zunghars/6D038CADD0F808459451175C1CAD6DC5']},
 qingTaiwan:{title:'Christine Moll-Murata. Tributary Labour Relations in China During the Ming-Qing Transition (Seventeenth to Eighteenth Centuries).',urls:['https://www.cambridge.org/core/journals/international-review-of-social-history/article/tributary-labour-relations-in-china-during-the-mingqing-transition-seventeenth-to-eighteenth-centuries/7AC034138FC2F5591D10313C256F2E53']},
 mughal:{title:'Victoria and Albert Museum. The Arts of the Mughal Empire; The Metropolitan Museum of Art. Islamic Art of the Deccan; Vincent A. Smith. Akbar the Great Mogul, 1542–1605.',urls:['https://www.vam.ac.uk/content/articles/a/the-age-of-the-mughals','https://www.metmuseum.org/essays/islamic-art-of-the-deccan','https://www.loc.gov/item/18002677/']},
 britain:{title:'National Army Museum. Battle of Plassey; Second Sikh War; Empire.',urls:['https://www.nam.ac.uk/explore/battle-plassey','https://www.nam.ac.uk/explore/second-sikh-war','https://www.nam.ac.uk/subjects/empire']},
 napoleon:{title:'Fondation Napoléon. Autour de la bataille d’Austerlitz; Napoleon’s Entry into Berlin, 27 October 1806.',urls:['https://www.napoleon.org/histoire-des-2-empires/chronologies/austerlitz-2-decembre-1805/','https://www.napoleon.org/en/history-of-the-two-empires/close-up/a-close-up-on-napoleons-entry-into-berlin-27-october-1806/']},
 france:{title:'Ministère des Armées, Chemins de mémoire. L’Armée française et la constitution du second empire colonial; Afrique du Nord — Conquêtes et pacifications, 1830–1934.',urls:['https://www.cheminsdememoire.gouv.fr/fr/theme-2-leurope-et-le-monde-au-xixe-siecle']},
 spain:{title:'Library of Congress. Spanish and Portuguese Exploration in the Americas; The Harkness Collection: Documents from Early Peru, the Pizarros and the Almagros, 1531–1578; Negotiating Empire, Part I.',urls:['https://www.loc.gov/classroom-materials/spanish-and-portuguese-exploration-in-the-americas/','https://findingaids.loc.gov/repositories/19/resources/2019','https://blogs.loc.gov/international-collections/2021/10/negotiating-empire-part-i-from-magellan-to-the-founding-of-manila-16th-18th-centuries/']},
 portugal:{title:'The Metropolitan Museum of Art. Interwoven Globe: chronology; Library of Congress. Europe Claims America: The Atlantic Joined.',urls:['https://www.metmuseum.org/exhibitions/listings/2013/interwoven-globe','https://www.loc.gov/exhibits/1492/eurocla.html']},
 usa:{title:'US National Archives. Louisiana Purchase Treaty (1803); Treaty of Guadalupe Hidalgo (1848); Treaty concerning the Cession of the Russian Possessions in North America (1867).',urls:['https://www.archives.gov/milestone-documents/louisiana-purchase-treaty','https://www.archives.gov/milestone-documents/treaty-of-guadalupe-hidalgo','https://www.archives.gov/milestone-documents/check-for-the-purchase-of-alaska']},
 inca:{title:'Smithsonian, National Museum of the American Indian. The Great Inka Road: Engineering an Empire; The Metropolitan Museum of Art. Central and Southern Andes, 1400–1600; UNESCO. Qhapaq Ñan.',urls:['https://americanindian.si.edu/inkaroad/inkauniverse/cusco/empire-builders.html','https://82nd-and-fifth.metmuseum.org/toah/ht/08/sanc.html','https://whc.unesco.org/document/152728']}
};
const states=[];
function state(id,from,to,name,aliases,source){const s={id,from,to,name:T(name),aliases,source,routes:[]};states.push(s);return (key,a,b,kind,title,text,points,extra={})=>s.routes.push({id:id+'-'+key,from:a,to:b,kind,title:T(title),text:T(text),points,sources:[source],...extra});}
let R=state('rashidun',632,660,'Праведный халифат|Rashidun Caliphate|Туура жолдогу халифат',['rashidun'],'caliphs');
R('sham',634,636,'campaign','Аравия → аш-Шам|Arabia → al-Sham|Арабстан → аш-Шам','После походов в аш-Шам победа при Ярмуке укрепила власть халифата в регионе.|Following campaigns in al-Sham, victory at the Yarmuk strengthened caliphal control in the region.|Аш-Шамга жортуулдардан кийин Ярмуктагы жеңиш халифаттын аймактагы бийлигин бекемдеди.',[[39.61,24.47],[36.22,32.52],[36.3,33.51]]);
R('iraq',633,637,'campaign','Аравия → Ирак и аль-Мадаин|Arabia → Iraq and al-Mada’in|Арабстан → Ирак жана ал-Мадаин','Походы в Ирак завершились захватом сасанидской столицы аль-Мадаин в 637 году.|Campaigns in Iraq culminated in the capture of the Sasanian capital al-Mada’in in 637.|Ирактагы жортуулдар 637-жылы Сасаниддердин борбору ал-Мадаинди алуу менен аяктады.',[[39.61,24.47],[44.3,31.9],[44.58,33.09]]);
R('egypt',639,642,'campaign','Палестина → Египет|Palestine → Egypt|Палестина → Мисир','Амр ибн аль-Ас продвинулся через Синай к Вавилону Египетскому и Александрии. Египет перешёл под власть халифата.|Amr ibn al-As advanced through Sinai to Babylon in Egypt and Alexandria. Egypt came under caliphal rule.|Амр ибн ал-Ас Синай аркылуу Мисирдеги Вавилонго жана Александрияга жеткен. Мисир халифатка өткөн.',[[34.47,31.5],[33.8,31.1],[31.23,30],[29.92,31.2]]);
R=state('umayyad',661,749,'Омейядский халифат|Umayyad Caliphate|Омейяд халифаты',['umayyad'],'umayyad');
R('carthage',670,698,'campaign','Ифрикия и Карфаген|Ifriqiya and Carthage|Ифрикия жана Карфаген','Кайруан стал опорой продвижения в Ифрикии. В 698 году арабские войска взяли Карфаген.|Kairouan became a base for expansion in Ifriqiya. Arab forces took Carthage in 698.|Кайруан Ифрикияга кеңейүүнүн таянычына айланган. 698-жылы араб аскерлери Карфагенди алган.',[[13.19,32.89],[10.1,35.68],[10.32,36.85]]);
R('andalus',711,714,'campaign','Магриб → аль-Андалус|Maghreb → al-Andalus|Магриб → ал-Андалус','Войска Тарика ибн Зияда и Мусы ибн Нусайра пересекли пролив; власть халифата распространилась на значительную часть Иберии.|The forces of Tariq ibn Ziyad and Musa ibn Nusayr crossed the strait; caliphal rule spread over much of Iberia.|Тарик ибн Зияд менен Муса ибн Нусайрдын аскерлери кысыктан өткөн; халифат Ибериянын көп бөлүгүнө жайылган.',[[-5.81,35.78],[-5.35,36.14],[-4.78,37.89],[-4.03,39.86]]);
R('transoxiana',705,712,'campaign','Хорасан → Мавераннахр|Khurasan → Transoxiana|Хорасан → Мавераннахр','Кутайба ибн Муслим вёл походы из Хорасана; Бухара и Самарканд были подчинены в ходе отдельных кампаний.|Qutayba ibn Muslim campaigned from Khurasan; Bukhara and Samarkand were subdued in separate campaigns.|Кутайба ибн Муслим Хорасандан жортуул жасаган; Бухара менен Самарканд өзүнчө жортуулдарда баш ийдирилген.',[[62.18,37.66],[64.42,39.77],[66.97,39.65]]);
R=state('mongols',1206,1367,'Монгольская империя и улусы|Mongol Empire and khanates|Монгол империясы жана улустар',['mongol','mongolRealm','yuan','goldenHorde','ilkhanate','late-yuan','late-jochi','late-ilkhan','late-chagatai'],'mongols');
R('jin',1211,1215,'campaign','Монголия → Чжунду|Mongolia → Zhongdu|Монголия → Чжунду','Поход против Цзинь привёл к взятию Чжунду в 1215 году. Вся держава Цзинь была завоёвана позднее, в 1234 году.|The campaign against Jin led to the capture of Zhongdu in 1215. The entire Jin state fell later, in 1234.|Цзинге каршы жортуулда Чжунду 1215-жылы алынган. Цзин мамлекети толук 1234-жылы басып алынган.',[[108,47],[115,41],[116.4,39.9]]);
R('khwarazm',1219,1220,'campaign','Отрар → Бухара → Самарканд|Otrar → Bukhara → Samarkand|Отрар → Бухара → Самарканд','Война с Хорезмом: монгольские армии наступали несколькими направлениями. Здесь показано продвижение к Бухаре и Самарканду.|War with Khwarazm: Mongol armies advanced on several axes. This direction leads to Bukhara and Samarkand.|Хорезм менен согушта монгол аскерлери бир нече багытта жылган. Бул жерде Бухара менен Самарканд багыты көрсөтүлгөн.',[[68.3,42.85],[64.42,39.77],[66.97,39.65]]);
R('rus',1236,1240,'campaign','Волга → Северо-Восточная Русь → Киев|Volga → north-eastern Rus → Kyiv|Волга → Түндүк-Чыгыш Русь → Киев','Западный поход Батыя: разгром Волжской Булгарии, вторжения в русские княжества и взятие Киева в 1240 году.|Batu’s western campaign defeated Volga Bulgaria, invaded the Rus principalities and took Kyiv in 1240.|Батыйдын батыш жортуулу Волга Булгарын талкалап, Русь княздыктарына кирип, 1240-жылы Киевди алган.',[[49.05,54.97],[40.42,56.13],[30.52,50.45]]);
R('baghdad',1256,1258,'campaign','Иран → Багдад|Iran → Baghdad|Иран → Багдад','Армия Хулагу после разгрома низаритских крепостей взяла Багдад. В Иране и Ираке сформировался улус Хулагу.|After defeating Nizari strongholds, Hülegü’s army captured Baghdad. His khanate took shape in Iran and Iraq.|Хулагунун аскерлери низарий чептерин талкалап, Багдадды алган. Иран менен Иракта Хулагунун улусу түзүлгөн.',[[50.59,36.44],[48.51,34.8],[44.37,33.31]]);
R('song',1268,1279,'campaign','Сянъян → Линьань → Ямынь|Xiangyang → Lin’an → Yamen|Сянъян → Линьань → Ямынь','Война Юань против Южной Сун: падение Линьаня в 1276 году, последнего двора Сун — после морского сражения 1279 года.|Yuan war against Southern Song: Lin’an fell in 1276; the last Song court fell after the naval battle of 1279.|Юандын Түштүк Сунга каршы согушу: Линьань 1276-жылы, акыркы Сун сарайы 1279-жылкы деңиз салгылашуусунан кийин кулаган.',[[112.14,32.04],[120.16,30.25],[113.08,22.3]]);
R=state('ottomans',1299,1918,'Османская империя|Ottoman Empire|Осмон империясы',['ottoman','late-ottoman'],'ottoman');
R('bursa',1326,1326,'campaign','Сёгют → Бурса|Söğüt → Bursa|Сөгүт → Бурса','Взятие Бурсы при Орхане закрепило османскую власть в северо-западной Анатолии.|Orhan’s capture of Bursa consolidated Ottoman power in north-western Anatolia.|Орхандын Бурсаны алышы түндүк-батыш Анадолуда Осмон бийлигин бекемдеген.',[[30.18,40.02],[29.06,40.19]]);
R('constantinople',1453,1453,'campaign','Эдирне → Константинополь|Edirne → Constantinople|Эдирне → Константинополь','После осады Мехмед II взял Константинополь. Город стал османской столицей.|Following the siege, Mehmed II captured Constantinople. The city became the Ottoman capital.|Мехмед II курчоодон кийин Константинополду алган. Шаар Осмон борборуна айланган.',[[26.56,41.68],[28.98,41.01]]);
R('syria',1516,1516,'campaign','Анатолия → Алеппо → Дамаск|Anatolia → Aleppo → Damascus|Анадолу → Алеппо → Дамаск','После победы при Мардж-Дабике Селим I установил власть над мамлюкской Сирией.|After victory at Marj Dabiq, Selim I took control of Mamluk Syria.|Мардж-Дабиктеги жеңиштен кийин Селим I мамлүк Сириясына бийлик орноткон.',[[32.49,37.87],[37.16,36.2],[36.3,33.51]]);
R('egypt',1517,1517,'campaign','Дамаск → Газа → Каир|Damascus → Gaza → Cairo|Дамаск → Газа → Каир','Поход Селима I через Палестину и Синай завершил завоевание Мамлюкского султаната.|Selim I’s advance through Palestine and Sinai completed the conquest of the Mamluk Sultanate.|Селим Iнин Палестина жана Синай аркылуу жортуулу Мамлүк султанатын басып алууну аяктаган.',[[36.3,33.51],[34.47,31.5],[33.8,31.1],[31.23,30.04]]);
R('hungary',1521,1526,'campaign','Белград → Мохач|Belgrade → Mohács|Белград → Мохач','После взятия Белграда последовала победа при Мохаче. Центральная Венгрия стала османской провинцией позднее, с 1541 года.|The capture of Belgrade was followed by victory at Mohács. Central Hungary became an Ottoman province later, from 1541.|Белград алынгандан кийин Мохачта жеңишке жетишкен. Борбордук Венгрия кийин, 1541-жылдан Осмон провинциясы болгон.',[[28.98,41.01],[20.46,44.82],[18.68,45.99]]);
R('baghdad',1534,1534,'campaign','Восточная Анатолия → Багдад|Eastern Anatolia → Baghdad|Чыгыш Анадолу → Багдад','Сулейман I взял Багдад. После сефевидского периода 1624–1638 годов город вновь перешёл к османам.|Süleyman I took Baghdad. After Safavid rule in 1624–1638, the city returned to the Ottomans.|Сулейман I Багдадды алган. 1624–1638-жылдардагы Сефевиддер мезгилинен кийин шаар кайра Осмондорго өткөн.',[[41.28,39.9],[46.29,38.08],[44.37,33.31]]);
R=state('russia',1547,1916,'Русское царство и Российская империя|Tsardom of Russia and Russian Empire|Орус падышалыгы жана Россия империясы',['early-russia','1789-russian-empire','early-siberian-forts'],'russia');
R('kazan',1552,1552,'campaign','Москва → Казань|Moscow → Kazan|Москва → Казан','Войска Ивана IV взяли Казань; Казанское ханство было включено в Русское царство.|Ivan IV’s forces captured Kazan; the Kazan Khanate was incorporated into the Russian tsardom.|Иван IVнүн аскерлери Казанды алган; Казан хандыгы Орус падышалыгына кошулган.',[[37.62,55.75],[44,56.33],[49.12,55.8]]);
R('siberia',1581,1582,'campaign','Урал → Кашлык|Urals → Qashliq|Урал → Кашлык','Поход Ермака привёл к взятию Кашлыка. Подчинение Сибирского ханства продолжалось после этого похода.|Yermak’s campaign led to the capture of Qashliq. The subjugation of the Siberian Khanate continued afterwards.|Ермактын жортуулунда Кашлык алынган. Сибирь хандыгын баш ийдирүү андан кийин да уланган.',[[58.1,58.3],[65.53,57.15],[68.5,58.13]]);
R('yakutsk',1619,1632,'settlement','Енисей → Лена|Yenisei → Lena|Энесай → Лена','Остроги стали опорами продвижения на восток: Енисейск основан в 1619 году, Якутский острог — в 1632 году.|Forts supported eastward expansion: Yeniseysk was founded in 1619 and Yakutsk fort in 1632.|Чептер чыгышка кеңейүүгө таяныч болгон: Енисейск 1619-жылы, Якутск чеби 1632-жылы негизделген.',[[92.17,58.45],[107.78,57.77],[129.73,62.03]]);
R('kamchatka',1697,1699,'campaign','Анадырский острог → Камчатка|Anadyrsk fort → Kamchatka|Анадырск чеби → Камчатка','Экспедиция Владимира Атласова усилила русское продвижение на Камчатку. Местные народы сопротивлялись подчинению.|Vladimir Atlasov’s expedition extended Russian expansion into Kamchatka. Indigenous peoples resisted subjugation.|Владимир Атласовдун экспедициясы Камчаткага орус бийлигинин жайылышын күчөткөн. Жергиликтүү элдер баш ийүүгө каршылык көрсөткөн.',[[169.7,64.7],[163,59.5],[158.6,54.9]],{sources:['alaska']});
R('alaska',1784,1784,'settlement','Охотск → Кадьяк|Okhotsk → Kodiak|Охотск → Кадьяк','На Кадьяке, в бухте Трёх Святителей, основано постоянное русское поселение. Морская связь обозначает колониальное продвижение через северную часть Тихого океана.|A permanent Russian settlement was founded at Three Saints Bay on Kodiak. The sea connection represents colonial expansion across the North Pacific.|Кадьяктын Үч Ыйыктын булуңунда туруктуу орус конушу негизделген. Деңиз багыты Тынч океандын түндүгү аркылуу колониялык кеңейүүнү көрсөтөт.',[[143.2,59.36],[156,57],[160,51],[175,51],[-170,53],[-153.49,57.13]],{sources:['alaska']});
R('amur',1858,1860,'treaty','Амур → Приморье|Amur → Primorye|Амур → Приморье','Айгунский и Пекинский договоры закрепили за Россией земли по левому берегу Амура и к востоку от Уссури.|The Aigun and Beijing treaties transferred the Amur’s left bank and lands east of the Ussuri to Russia.|Айгун жана Пекин келишимдери Амурдун сол жээгин жана Уссуринин чыгышындагы жерлерди Россияга өткөргөн.',[[127.54,50.29],[135.07,48.48],[131.89,43.12]]);
R=state('qing',1636,1911,'Империя Цин|Qing Empire|Цин империясы',['1789-qing'],'qing');
R('beijing',1644,1644,'campaign','Шэнцзин → Шаньхайгуань → Пекин|Shengjing → Shanhaiguan → Beijing|Шэнцзин → Шаньхайгуань → Пекин','Цинские войска вошли через Шаньхайгуань и заняли Пекин. Завоевание остальных земель Мин продолжалось десятилетиями.|Qing forces entered through Shanhaiguan and occupied Beijing. Conquest of the remaining Ming lands continued for decades.|Цин аскерлери Шаньхайгуань аркылуу кирип, Пекинди ээлеген. Калган Мин жерлерин басып алуу ондогон жылдар уланган.',[[123.43,41.8],[119.75,40.01],[116.4,39.9]]);
R('taiwan',1683,1683,'campaign','Фуцзянь → Пэнху → Тайвань|Fujian → Penghu → Taiwan|Фуцзянь → Пэнху → Тайвань','Флот Ши Лана разбил силы Чжэн у Пэнху; власть Чжэн на Тайване завершилась.|Shi Lang’s fleet defeated Zheng forces at Penghu; Zheng rule on Taiwan ended.|Ши Ландын флоту Пэнхуда Чжэн күчтөрүн талкалаган; Тайванда Чжэн бийлиги аяктаган.',[[118.08,24.48],[119.57,23.57],[120.2,23]],{sources:['qingTaiwan']});
R('dzungaria',1755,1758,'campaign','Ганьсу → Джунгария|Gansu → Dzungaria|Ганьсу → Жуңгария','Цинские армии уничтожили Джунгарское ханство. Война сопровождалась массовым уничтожением джунгарского населения.|Qing armies destroyed the Dzungar Khanate. The war involved mass extermination of the Dzungar population.|Цин аскерлери Жуңгар хандыгын жок кылган. Согуш жуңгар калкын жапырт кырып-жоюу менен коштолгон.',[[98.5,39.74],[93.52,42.83],[81.32,43.92]]);
R('tarim',1758,1759,'campaign','Джунгария → Кашгар и Яркенд|Dzungaria → Kashgar and Yarkand|Жуңгария → Кашкар жана Жаркент','После северных кампаний цинские войска подчинили оазисы Таримского бассейна.|After the northern campaigns, Qing forces subdued the oases of the Tarim Basin.|Түндүктөгү жортуулдардан кийин Цин аскерлери Тарим ойдуңунун оазистерин баш ийдирген.',[[81.32,43.92],[80.26,41.17],[75.99,39.47],[77.25,38.42]]);
R=state('mughals',1526,1857,'Империя Великих Моголов|Mughal Empire|Улуу Моголдор империясы',['early-mughal'],'mughal');
R('panipat',1525,1526,'campaign','Кабул → Панипат → Дели|Kabul → Panipat → Delhi|Кабул → Панипат → Дели','Бабур победил Ибрахима Лоди при Панипате; началось могольское правление в Северной Индии.|Babur defeated Ibrahim Lodi at Panipat, establishing Mughal rule in northern India.|Бабур Панипатта Ибрахим Лодини жеңип, Түндүк Индияда Могол бийлигин орноткон.',[[69.21,34.56],[71.52,34.01],[76.97,29.39],[77.21,28.61]]);
R('gujarat',1572,1573,'campaign','Агра → Гуджарат|Agra → Gujarat|Агра → Гужарат','Акбар завоевал Гуджарат, получив доступ к его городам и портам.|Akbar conquered Gujarat, gaining access to its cities and ports.|Акбар Гужаратты басып алып, анын шаарлары менен портторуна жеткен.',[[78.01,27.18],[75.78,26.91],[72.58,23.02]]);
R('bengal',1574,1576,'campaign','Северная Индия → Бенгалия|Northern India → Bengal|Түндүк Индия → Бенгалия','Разгром династии Каррани при Раджмахале закрепил могольское завоевание Бенгалии; сопротивление местных сил продолжалось.|Defeat of the Karrani dynasty at Rajmahal secured the Mughal conquest of Bengal; local resistance continued.|Ражмахалда Каррани династиясынын талкаланышы Бенгалияны басып алууну бекемдеген; жергиликтүү каршылык уланган.',[[78.01,27.18],[85.14,25.61],[87.83,25.04]]);
R('deccan',1686,1687,'campaign','Декан: Биджапур → Голконда|Deccan: Bijapur → Golconda|Декан: Бижапур → Голконда','Аурангзеб присоединил Биджапур в 1686 году и Голконду в 1687 году. Война с маратхами продолжалась.|Aurangzeb annexed Bijapur in 1686 and Golconda in 1687. War with the Marathas continued.|Аурангзеб 1686-жылы Бижапурду, 1687-жылы Голконданы кошкон. Маратхалар менен согуш уланган.',[[75.34,19.88],[75.71,16.83],[78.4,17.38]]);
R=state('britain',1707,1918,'Британская империя|British Empire|Британ империясы',['1789-great-britain','1789-british-india'],'britain');
R('bengal',1757,1757,'campaign','Калькутта → Плесси|Calcutta → Plassey|Калькутта → Плесси','Победа Ост-Индской компании при Плесси усилила её политическое влияние в Бенгалии; право сбора доходов получено в 1765 году.|The East India Company’s victory at Plassey strengthened its political influence in Bengal; revenue rights followed in 1765.|Ост-Индия компаниясынын Плессидеги жеңиши Бенгалиядагы таасирин күчөткөн; салык чогултуу укугу 1765-жылы берилген.',[[88.36,22.57],[88.26,23.79]]);
R('punjab',1848,1849,'campaign','Мултан → Гуджрат: Пенджаб|Multan → Gujrat: Punjab|Мултан → Гужрат: Пенжаб','Вторая англо-сикхская война завершилась аннексией Пенджаба Ост-Индской компанией.|The Second Anglo-Sikh War ended in the East India Company’s annexation of Punjab.|Экинчи англо-сикх согушу Ост-Индия компаниясынын Пенжабды аннексиялоосу менен аяктаган.',[[71.52,30.2],[73.96,32.57],[74.36,31.55]]);
R('egypt',1882,1882,'occupation','Исмаилия → Тель-эль-Кебир → Каир|Ismailia → Tel el-Kebir → Cairo|Исмаилия → Тел-эл-Кебир → Каир','Британские войска заняли Египет после победы над армией Ураби. Египет оставался под номинальным османским верховенством.|British troops occupied Egypt after defeating Urabi’s army. Egypt remained under nominal Ottoman suzerainty.|Урабинин аскерлери жеңилгенден кийин британ аскерлери Мисирди ээлеген. Мисир номиналдуу Осмон үстөмдүгүндө калган.',[[32.27,30.6],[31.94,30.54],[31.23,30.04]]);
R=state('france',1799,1918,'Франция: империя и колониальная экспансия|France: empire and colonial expansion|Франция: империя жана колониялык кеңейүү',['late-france'],'napoleon');
R('austerlitz',1805,1805,'campaign','Ульм → Вена → Аустерлиц|Ulm → Vienna → Austerlitz|Улм → Вена → Аустерлиц','Кампания Наполеона завершилась победой при Аустерлице и территориальными уступками Австрии. Вена не была включена во Францию.|Napoleon’s campaign ended in victory at Austerlitz and Austrian territorial concessions. Vienna was not annexed to France.|Наполеондун жортуулу Аустерлицтеги жеңиш жана Австриянын аймактык чегинүүлөрү менен аяктаган. Вена Францияга кошулган эмес.',[[10,48.4],[16.37,48.21],[16.88,49.15]]);
R('prussia',1806,1806,'occupation','Йена → Берлин|Jena → Berlin|Йена → Берлин','После побед при Йене и Ауэрштедте французская армия заняла Берлин. Пруссия сохранялась как отдельное государство.|Following victories at Jena and Auerstedt, the French army occupied Berlin. Prussia remained a separate state.|Йена менен Ауэрштедттеги жеңиштерден кийин француз армиясы Берлинди ээлеген. Пруссия өзүнчө мамлекет бойдон калган.',[[11.59,50.93],[13.41,52.52]]);
R('algiers',1830,1830,'campaign','Тулон → Сиди-Ферруш → Алжир|Toulon → Sidi Ferruch → Algiers|Тулон → Сиди-Ферруш → Алжир','Французский десант взял Алжир. Завоевание внутренних областей продолжалось десятилетиями и встретило сопротивление.|A French expedition captured Algiers. Conquest of the interior continued for decades and met resistance.|Француз десанты Алжирди алган. Ички аймактарды басып алуу ондогон жылдар уланып, каршылыкка кабылган.',[[5.93,43.12],[3.5,40],[2.84,36.76],[3.06,36.75]],{sources:['france']});
R=state('spain',1492,1918,'Испанская монархия и колониальная империя|Spanish monarchy and colonial empire|Испан монархиясы жана колониялык империясы',['late-castile','1789-spain'],'spain');
R('caribbean',1492,1493,'settlement','Иберия → Карибское море|Iberia → Caribbean|Иберия → Кариб деңизи','За первым плаванием Колумба последовали новые экспедиции и колонизация Эспаньолы, затронувшая общества таино.|Columbus’s first voyage was followed by further expeditions and colonisation of Hispaniola, affecting Taíno societies.|Колумбдун биринчи сапарынан кийин жаңы экспедициялар жана таино коомдоруна таасир эткен Эспаньоланы колониялаштыруу башталган.',[[-6.9,37.23],[-16.5,28],[-40,25],[-65,22],[-71,19.7]]);
R('mexico',1519,1521,'campaign','Куба → Веракрус → Теночтитлан|Cuba → Veracruz → Tenochtitlan|Куба → Веракрус → Теночтитлан','Кортес и его многочисленные местные союзники захватили Теночтитлан после осады 1521 года.|Cortés and his many Indigenous allies captured Tenochtitlan after the siege of 1521.|Кортес жана анын көп сандаган жергиликтүү союздаштары 1521-жылкы курчоодон кийин Теночтитланды алган.',[[-75.83,20.02],[-87,21],[-96.13,19.17],[-99.13,19.43]]);
R('peru',1532,1533,'campaign','Кахамарка → Куско|Cajamarca → Cusco|Кахамарка → Куско','Писарро захватил Атауальпу в Кахамарке; испанские силы и союзники вошли в Куско. Сопротивление инков продолжилось.|Pizarro seized Atahualpa at Cajamarca; Spanish forces and allies entered Cusco. Inca resistance continued.|Писарро Кахамаркада Атауальпаны туткундаган; испан күчтөрү жана союздаштары Куского кирген. Инктердин каршылыгы уланган.',[[-78.5,-7.16],[-75.99,-9.87],[-71.97,-13.53]]);
R('manila',1565,1571,'settlement','Себу → Манила|Cebu → Manila|Себу → Манила','После основания поселения на Себу испанские силы установили власть в Маниле. Контроль над архипелагом расширялся постепенно.|After establishing a settlement at Cebu, Spanish forces took control of Manila. Control over the archipelago expanded gradually.|Себуда конуш негизделгенден кийин испан күчтөрү Манилада бийлик орноткон. Архипелагдагы көзөмөл акырындап кеңейген.',[[123.89,10.32],[121.5,13.3],[120.98,14.6]]);
R=state('portugal',1415,1918,'Португальская империя|Portuguese Empire|Португал империясы',['late-portugal'],'portugal');
R('india',1497,1498,'voyage','Лиссабон → мыс Доброй Надежды → Каликут|Lisbon → Cape of Good Hope → Calicut|Лиссабон → Жакшы Үмүт тумшугу → Каликут','Плавание Васко да Гамы связало Португалию с Индией морским путём. Оно предшествовало захвату портов и созданию колониальной сети.|Vasco da Gama’s voyage linked Portugal and India by sea. It preceded the seizure of ports and creation of a colonial network.|Васко да Гаманын сапары Португалия менен Индияны деңиз жолу аркылуу байланыштырган. Андан кийин портторду ээлөө жана колониялык тармак түзүү башталган.',[[-9.14,38.72],[-20,20],[-28,-5],[-15,-30],[5,-37],[20,-36],[36,-22],[40,-5],[72,8],[75.78,11.26]]);
R('brazil',1500,1500,'voyage','Португалия → Бразилия|Portugal → Brazil|Португалия → Бразилия','Кабрал достиг побережья Бразилии. Португальские притязания предшествовали длительной колонизации населённых коренными народами земель.|Cabral reached the Brazilian coast. Portuguese claims preceded prolonged colonisation of Indigenous lands.|Кабрал Бразилиянын жээгине жеткен. Португал дооматтарынан кийин жергиликтүү элдердин жерлерин узак колониялаштыруу жүргөн.',[[-9.14,38.72],[-24,16],[-33,-4],[-39.06,-16.45]]);
R('goa',1510,1510,'campaign','Кочин → Гоа|Cochin → Goa|Кочин → Гоа','Афонсу де Албукерки захватил Гоа, будущий центр португальских владений в Индии.|Afonso de Albuquerque seized Goa, the future centre of Portuguese possessions in India.|Афонсу де Албукерки Индиядагы португал ээликтеринин болочок борбору Гоаны алган.',[[76.27,9.97],[74.5,12],[73.83,15.5]]);
R('malacca',1511,1511,'campaign','Гоа → Малакка|Goa → Malacca|Гоа → Малакка','Португальцы захватили Малакку, важный центр торговли в Юго-Восточной Азии.|The Portuguese captured Malacca, a major trading centre in Southeast Asia.|Португалдар Түштүк-Чыгыш Азиядагы маанилүү соода борбору Малакканы алган.',[[73.83,15.5],[74,7],[80,5],[94,6.5],[98,5],[102.25,2.2]]);
R=state('usa',1776,1918,'Соединённые Штаты Америки|United States of America|Америка Кошмо Штаттары',['1789-usa'],'usa');
R('louisiana',1803,1803,'treaty','США → Луизиана|USA → Louisiana|АКШ → Луизиана','Покупка французских прав на Луизиану увеличила территориальные притязания США. Коренные народы сохраняли свои земли и политические общества.|Purchase of French claims to Louisiana enlarged US territorial claims. Indigenous peoples retained their lands and political societies.|Франциянын Луизианага укуктарын сатып алуу АКШнын аймактык дооматтарын кеңейткен. Жергиликтүү элдер өз жерлерин жана саясий коомдорун сактаган.',[[-84.51,39.1],[-90.2,38.63],[-94,38]]);
R('mexican-cession',1848,1848,'treaty','США → Калифорния и Юго-Запад|USA → California and the Southwest|АКШ → Калифорния жана Түштүк-Батыш','Договор Гуадалупе-Идальго завершил американо-мексиканскую войну; Мексика уступила Калифорнию и обширные юго-западные территории.|The Treaty of Guadalupe Hidalgo ended the US–Mexican War; Mexico ceded California and extensive southwestern territories.|Гуадалупе-Идальго келишими АКШ–Мексика согушун аяктаган; Мексика Калифорнияны жана түштүк-батыштагы кең аймактарды өткөргөн.',[[-94.58,39.1],[-105.94,35.69],[-118.24,34.05]]);
R('alaska',1867,1867,'treaty','США → Аляска|USA → Alaska|АКШ → Аляска','Россия передала свои североамериканские владения США по договору о продаже. Стрелка обозначает передачу владений.|Russia transferred its North American possessions to the USA under a sale treaty. The arrow denotes a transfer of possessions.|Россия сатуу келишими боюнча Түндүк Америкадагы ээликтерин АКШга өткөргөн. Жебе ээликтердин өткөрүлүшүн билдирет.',[[-123,47.5],[-131,53],[-135.33,57.05]]);
R=state('inca',1438,1532,'Тауантинсуйу — держава инков|Tawantinsuyu — Inca Empire|Тауантинсуйу — Инк империясы',['cusco-inca'],'inca');
R('chimu',1470,1470,'campaign','Куско → Чан-Чан|Cusco → Chan Chan|Куско → Чан-Чан','Около 1470 года инки покорили государство Чиму. Его столицей был Чан-Чан на тихоокеанском побережье.|Around 1470 the Inca subdued the Chimú state, whose capital was Chan Chan on the Pacific coast.|Болжол менен 1470-жылы инктер Тынч океан жээгиндеги Чан-Чанды борбор кылган Чиму мамлекетин баш ийдирген.',[[-71.97,-13.53],[-75.99,-9.87],[-79.07,-8.1]],{approx:true});
R('south',1471,1493,'campaign','Куско → южные Анды|Cusco → southern Andes|Куско → түштүк Анддар','При Тупаке Инке Юпанки владения расширялись на юг. Показан общий коридор продвижения через Анды, с приблизительным периодом.|Under Tupac Inca Yupanqui, the empire expanded southward. This is a general Andean axis of expansion, dated approximately.|Тупак Инка Юпанкинин тушунда ээликтер түштүккө кеңейген. Анддар аркылуу жалпы багыт жана болжолдуу мезгил көрсөтүлгөн.',[[-71.97,-13.53],[-69.1,-16.56],[-68,-23],[-70.67,-33.45]],{approx:true});
R('north',1493,1527,'campaign','Куско → Кито|Cusco → Quito|Куско → Кито','При Уайна Капаке инки продолжили расширение к северу, включая земли нынешнего Эквадора.|Under Huayna Capac the Inca continued expanding northward, including into present-day Ecuador.|Уайна Капактын тушунда инктер түндүккө, азыркы Эквадордун жерлерине чейин кеңейген.',[[-71.97,-13.53],[-78.5,-7.16],[-78.47,-.18]],{approx:true});
sources.timur={title:'TDV İslâm Ansiklopedisi. Timur; Herat; The Metropolitan Museum of Art. The Art of the Timurid Period (ca. 1370–1507).',urls:['https://islamansiklopedisi.org.tr/timur','https://islamansiklopedisi.org.tr/herat','https://www.metmuseum.org/essays/the-art-of-the-timurid-period-ca-1370-1507']};
R=state('timur',1370,1405,'Держава Тимура|Timur’s empire|Тимурдун империясы',['late-timurid'],'timur');
R('herat',1380,1381,'campaign','Самарканд → Герат|Samarkand → Herat|Самарканд → Герат','Поход в Хорасан: Герат признаёт власть Тимура в 1381 году.|In the Khurasan campaign, Herat submits to Timur in 1381.|Хорасанга жортуулда Герат 1381-жылы Тимурдун бийлигин тааныйт.',[[66.96,39.65],[67.1,36.76],[62.2,34.35]]);
R('iran',1386,1387,'campaign','Хорасан → Иран|Khurasan → Iran|Хорасан → Иран','Тимур расширяет владения в Иране; в 1387 году захвачены Исфахан и Шираз.|Timur expands his domains in Iran; Isfahan and Shiraz are taken in 1387.|Тимур Ирандагы ээликтерин кеңейтет; 1387-жылы Исфахан менен Шираз алынат.',[[62.2,34.35],[59.6,36.3],[51.67,32.65],[52.58,29.59]]);
R('terek',1395,1395,'campaign','Кавказ → Терек|Caucasus → Terek|Кавказ → Терек','Победа над Тохтамышем на Тереке открывает путь к разорению ордынских центров. Этот поход не означает постоянного включения всей Орды в державу Тимура.|Victory over Tokhtamysh on the Terek opens the way to attacks on Horde centres. The campaign does not mean permanent annexation of the whole Horde.|Теректе Токтомушту жеңүү Ордонун борборлоруна чабуулга жол ачат. Бул жортуул бүт Ордонун туруктуу кошулганын билдирбейт.',[[48.3,38.75],[48.29,42.06],[46.5,43.6]]);
R('delhi',1398,1398,'campaign','Самарканд → Кабул → Дели|Samarkand → Kabul → Delhi|Самарканд → Кабул → Дели','Поход через Афганистан и Инд приводит к захвату Дели в декабре 1398 года. Армия возвращается в Центральную Азию.|The campaign through Afghanistan and across the Indus reaches Delhi in December 1398. The army returns to Central Asia.|Афганстан жана Инд аркылуу жортуул 1398-жылдын декабрында Делини алууга жеткирет. Аскер Борбордук Азияга кайтып келет.',[[66.96,39.65],[69.17,34.53],[72.23,33.89],[77.2,28.61]]);
R('sham',1400,1401,'campaign','Анатолия → Халеб → Дамаск|Anatolia → Aleppo → Damascus|Анадолу → Халеб → Дамаск','Войско Тимура разбивает мамлюков, захватывает Халеб в 1400 году и Дамаск в 1401 году.|Timur’s army defeats the Mamluks, taking Aleppo in 1400 and Damascus in 1401.|Тимурдун аскери мамлюктарды жеңип, 1400-жылы Халебди, 1401-жылы Дамаскты алат.',[[37.02,39.75],[37.16,36.2],[36.3,33.51]]);
R('ankara',1402,1402,'campaign','Сивас → Кайсери → Анкара|Sivas → Kayseri → Ankara|Сивас → Кайсери → Анкара','У Анкары Тимур побеждает Баязида I. В Османской державе начинается междоусобная борьба.|At Ankara Timur defeats Bayezid I. A succession struggle begins in the Ottoman state.|Анкарада Тимур Баязид Iни жеңет. Осмон мамлекетинде так үчүн күрөш башталат.',[[37.02,39.75],[35.49,38.72],[34.16,39.15],[32.96,40.05]]);
sources.oregon={title:'National Park Service. Oregon National Historic Trail: Official Map & Guide; First Year in Oregon, 1840–1869.',urls:['https://www.nps.gov/oreg/planyourvisit/upload/National-Park-Service-Large-Print-Trail-Brochure-508.pdf','https://www.nps.gov/oreg/faqs.htm']};
states.find(s=>s.id==='usa').routes.push({id:'usa-oregon-trail',from:1841,to:1869,kind:'settlement',title:T('Орегонская тропа|Oregon Trail|Орегон жолу'),text:T('Переселенческие обозы идут от Миссури через Скалистые горы к долине Уилламетт. Переселение усиливает давление на земли коренных народов.|Emigrant wagon trains travel from Missouri across the Rocky Mountains to the Willamette Valley. Settlement increases pressure on Indigenous lands.|Көчмөндөрдүн араба кербендери Миссуриден Аскалуу тоолор аркылуу Уилламетт өрөөнүнө барат. Көчүп келүү түпкү элдердин жерлерине басымды күчөтөт.'),points:[[-94.42,39.09],[-98.98,40.65],[-104.55,42.2],[-108.92,42.37],[-112.43,43.03],[-116.4,43.83],[-121.18,45.6],[-122.61,45.36]],sources:['oregon']});

for(const s of states)s.routes.sort((a,b)=>a.to-b.to||a.from-b.from);
module.exports={states,sources};
