// Short original biographies; article identifiers are editorial references, never links in the UI.
// name, TDV article title, Russian, English, Kyrgyz
module.exports=[
['Абу Хурайра','Ebû Hüreyre',
'Сподвижник из йеменского племени даус, присоединившийся к Пророку Мухаммаду ﷺ в мединский период. Посвятил себя запоминанию и передаче хадисов; от него учились многие сподвижники и табиины. Его сообщения занимают значительное место в основных хадисных сборниках.',
'A companion from the Yemeni Daws tribe who joined Prophet Muhammad ﷺ during the Medinan period. He devoted himself to remembering and transmitting hadith; many companions and successors learned from him. His reports have a prominent place in the main hadith collections.',
'Мединалык мезгилде Мухаммад пайгамбарга ﷺ кошулган йемендик даус уруусунун сахабасы. Хадистерди жаттоого жана риваят кылууга өмүрүн арнаган; андан көптөгөн сахабалар менен табииндер билим алышкан. Негизги хадис жыйнактарында анын риваяттары чоң орун ээлейт.'],
['Нафи, мауля Ибн Умара','Nâfi‘',
'Мединский передатчик хадисов поколения табиинов, вольноотпущенник и ученик Абдуллаха ибн Умара. Передавал сведения о словах и практике своего учителя; среди его учеников был Малик ибн Анас. Цепочка Малик — Нафи — Ибн Умар известна в хадисной традиции своей высокой оценкой.',
'A Medinan hadith transmitter of the successor generation, a freedman and student of Abdullah ibn Umar. He transmitted his teacher’s words and practice; Malik ibn Anas was among his students. The chain Malik — Nafi — Ibn Umar is highly regarded in hadith scholarship.',
'Табиин муунунун мединалык хадис риваятчысы, Абдуллах ибн Умардын азат кылынган кулу жана шакирти. Устатынын сөздөрүн, амалдарын риваят кылган; анын шакирттеринин арасында Малик ибн Анас болгон. Малик — Нафи — Ибн Умар тизмеги хадис илиминде жогору бааланат.'],
['Умар ибн аль-Хаттаб','Ömer',
'Второй Праведный халиф, руководивший общиной в 634–644 годах. При нём владения халифата расширились в Ираке, аш-Шаме и Египте; развивались управление провинциями и государственный учёт. С его правлением связано введение летосчисления от хиджры.',
'The second Rashidun caliph, who led the community in 634–644. His reign saw expansion in Iraq, al-Sham and Egypt and the development of provincial administration and state registers. The adoption of the Hijri era is associated with his rule.',
'634–644-жылдары үммөттү башкарган экинчи туура жолдогу халиф. Анын тушунда халифат Иракта, аш-Шамда жана Мисирде кеңейип, аймактык башкаруу жана мамлекеттик эсеп өнүккөн. Хижрадан жыл саноонун киргизилиши анын бийлиги менен байланыштуу.'],
['Усман ибн Аффан','Osman',
'Третий Праведный халиф, правивший в 644–656 годах, и один из ранних мусульман. При нём подготовили и разослали в главные центры общины образцовые списки Корана. Его гибель в Медине стала важным событием начала первой большой смуты.',
'The third Rashidun caliph, ruling in 644–656, and an early Muslim. Standard copies of the Quran were prepared and sent to major centres of the community during his reign. His death in Medina was a major event at the beginning of the first civil conflict.',
'644–656-жылдары башкарган үчүнчү туура жолдогу халиф жана алгачкы мусулмандардын бири. Анын тушунда Курандын үлгүлүү нускалары даярдалып, үммөттүн негизги борборлоруна жөнөтүлгөн. Мединада өлтүрүлүшү биринчи чоң бүлгүндүн башындагы маанилүү окуя болгон.'],
['Али ибн Абу Талиб','Ali',
'Двоюродный брат и зять Пророка Мухаммада ﷺ, супруг Фатимы и четвёртый Праведный халиф. Правил в 656–661 годах, сделав Куфу центром управления. Известен также передачей хадисов, знанием Корана и правовыми суждениями; его правление пришлось на первую большую смуту.',
'A cousin and son-in-law of Prophet Muhammad ﷺ, Fatima’s husband and the fourth Rashidun caliph. He ruled in 656–661 with Kufa as his administrative centre. He also transmitted hadith and was known for Quranic knowledge and legal judgements; his reign coincided with the first civil conflict.',
'Мухаммад пайгамбардын ﷺ аталаш тууганы жана күйөө баласы, Фатиманын жолдошу, төртүнчү туура жолдогу халиф. 656–661-жылдары Куфаны башкаруу борбору кылган. Хадис риваяттары, Куран билими жана укуктук чечимдери менен белгилүү; бийлиги биринчи чоң бүлгүнгө туш келген.'],
['Хадиджа бинт Хувайлид','Hatice',
'Первая супруга Пророка Мухаммада ﷺ и первая уверовавшая в его пророческую миссию. До брака занималась торговлей в Мекке. Поддерживала Пророка ﷺ в первые годы откровения и во время преследований; мать Фатимы и других его детей.',
'The first wife of Prophet Muhammad ﷺ and the first to believe in his prophetic mission. She conducted trade in Mecca before their marriage. She supported him during the early revelations and persecution and was the mother of Fatima and other children of the Prophet.',
'Мухаммад пайгамбардын ﷺ биринчи жубайы жана анын пайгамбарлыгына алгач ишенген адам. Никеге чейин Меккеде соода жүргүзгөн. Вахийдин алгачкы жылдарында жана куугунтук учурунда Пайгамбарды ﷺ колдогон; Фатиманын жана анын башка балдарынын энеси.'],
['Аиша бинт Абу Бакр','Âişe',
'Супруга Пророка Мухаммада ﷺ, дочь Абу Бакра и одна из главных передатчиц хадисов. После смерти Пророка ﷺ преподавала в Медине и отвечала на вопросы о вероучении, обрядах и семейной жизни. Её сообщения и правовые суждения занимают заметное место в исламской учёности.',
'A wife of Prophet Muhammad ﷺ, daughter of Abu Bakr and a major transmitter of hadith. After the Prophet’s death she taught in Medina and answered questions about belief, worship and family life. Her reports and legal judgements hold an important place in Islamic scholarship.',
'Мухаммад пайгамбардын ﷺ жубайы, Абу Бакрдын кызы жана хадистердин негизги риваятчыларынын бири. Пайгамбар ﷺ дүйнөдөн кайткандан кийин Мединада сабак берип, ишеним, ибадат жана үй-бүлө маселелерине жооп берген. Риваяттары менен укуктук пикирлери ислам илиминде маанилүү орунда.'],
['Фатима аз-Захра','Fâtıma',
'Дочь Пророка Мухаммада ﷺ и Хадиджи, супруга Али ибн Абу Талиба. Жила в Мекке и Медине; была матерью аль-Хасана и аль-Хусайна. Её семья занимает центральное место в истории Ахль аль-Байт — семьи Пророка ﷺ.',
'The daughter of Prophet Muhammad ﷺ and Khadija, and wife of Ali ibn Abi Talib. She lived in Mecca and Medina and was the mother of al-Hasan and al-Husayn. Her family holds a central place in the history of Ahl al-Bayt, the Prophet’s household.',
'Мухаммад пайгамбар ﷺ менен Хадиджанын кызы, Али ибн Абу Талибдин жубайы. Мекке менен Мединада жашаган, аль-Хасан менен аль-Хусайндын энеси болгон. Анын үй-бүлөсү Ахль аль-Байттын — Пайгамбардын ﷺ үй-бүлөсүнүн тарыхында негизги орунда.'],
['Хамза ибн Абдуль-Мутталиб','Hamza',
'Дядя Пророка Мухаммада ﷺ и его сподвижник. Принял ислам в Мекке, затем переселился в Медину. Участвовал в сражении при Бадре и погиб в сражении при Ухуде; в исламской традиции известен как один из выдающихся шахидов.',
'An uncle and companion of Prophet Muhammad ﷺ. He embraced Islam in Mecca and later migrated to Medina. He fought at Badr and was killed at Uhud; Islamic tradition remembers him as an eminent martyr.',
'Мухаммад пайгамбардын ﷺ агасы жана сахабасы. Меккеде исламды кабыл алып, кийин Мединага көчкөн. Бадрга катышып, Ухудда шейит болгон; ислам салтында көрүнүктүү шейиттердин бири катары эскерилет.'],
['Биляль ибн Рабах','Bilâl-i Habeşî',
'Сподвижник абиссинского происхождения и один из первых муэдзинов ислама. За принятие ислама подвергался преследованиям в Мекке и был освобождён Абу Бакром. После переселения в Медину призывал общину к молитве при Пророке ﷺ.',
'A companion of Abyssinian origin and one of Islam’s first muezzins. Persecuted in Mecca for embracing Islam, he was freed by Abu Bakr. After migrating to Medina, he called the community to prayer during the Prophet’s ﷺ lifetime.',
'Хабаша тектүү сахаба жана исламдын алгачкы азанчыларынын бири. Исламды кабыл алганы үчүн Меккеде куугунтукталып, Абу Бакр тарабынан эркиндикке чыгарылган. Мединага көчкөндөн кийин Пайгамбардын ﷺ учурунда жамаатты намазга чакырган.'],
['Халид ибн аль-Валид','Hâlid b. Velîd',
'Сподвижник и военачальник, известный как «Меч Аллаха». После принятия ислама участвовал в походах Пророка ﷺ, затем возглавлял войска при первых халифах. Сыграл важную роль в кампаниях в Ираке и аш-Шаме, в том числе при Ярмуке.',
'A companion and commander known as the “Sword of Allah”. After embracing Islam, he took part in the Prophet’s ﷺ expeditions and later commanded armies under the first caliphs. He played an important role in campaigns in Iraq and al-Sham, including Yarmuk.',
'«Аллахтын кылычы» деп белгилүү сахаба жана кол башчы. Исламды кабыл алгандан кийин Пайгамбардын ﷺ жортуулдарына катышып, алгачкы халифтердин тушунда кошуундарды башкарган. Ирак менен аш-Шамдагы, анын ичинде Ярмуктагы салгылаштарда маанилүү роль ойногон.'],
['Абу Убайда ибн аль-Джаррах','Ebû Ubeyde b. Cerrâh',
'Один из ранних мусульман и сподвижников Пророка ﷺ. При первых халифах командовал войсками в аш-Шаме и участвовал в управлении покорёнными областями. Умер во время эпидемии чумы Амваса в 639 году.',
'An early Muslim and companion of the Prophet ﷺ. Under the first caliphs he commanded armies in al-Sham and helped administer the conquered regions. He died during the plague of Amwas in 639.',
'Алгачкы мусулмандардын жана Пайгамбардын ﷺ сахабаларынын бири. Биринчи халифтердин тушунда аш-Шамдагы кошуундарды башкарып, алынган аймактарды башкарууга катышкан. 639-жылы Амвас чумасы учурунда дүйнөдөн кайткан.'],
['Абдуллах ибн Масуд','Abdullah b. Mes‘ûd',
'Один из ранних сподвижников, знаток чтения Корана и передатчик хадисов. После переселения из Мекки был близок к Пророку ﷺ. Позднее преподавал в Куфе, где его ученики участвовали в формировании иракской правовой традиции.',
'An early companion, expert in Quranic recitation and transmitter of hadith. After leaving Mecca he remained close to the Prophet ﷺ. He later taught in Kufa, where his pupils helped shape the Iraqi legal tradition.',
'Алгачкы сахабалардан, Куран окуунун билгичи жана хадис риваятчысы. Меккеден көчкөндөн кийин Пайгамбарга ﷺ жакын болгон. Кийин Куфеде сабак берип, шакирттери Ирактагы укуктук салттын калыптанышына катышкан.'],
['Зайд ибн Сабит','Zeyd b. Sâbit',
'Мединский сподвижник и писец откровения. При Абу Бакре руководил собиранием письменного текста Корана, а при Усмане — работой комиссии по изготовлению образцовых списков. Был также известен знанием наследственного права и судебной деятельностью.',
'A Medinan companion and scribe of revelation. Under Abu Bakr he led the collection of the written Quran; under Uthman he headed the committee producing standard copies. He was also known for inheritance law and judicial work.',
'Мединалык сахаба жана вахий катчысы. Абу Бакрдын тушунда Курандын жазма текстин чогултууну, Усмандын тушунда үлгүлүү нускаларды даярдаган комиссияны жетектеген. Мурас укугун билгени жана соттук иштери менен да белгилүү.'],
['Абдуллах ибн Аббас','Abdullah b. Abbas',
'Двоюродный брат Пророка Мухаммада ﷺ, передатчик хадисов и один из самых известных ранних толкователей Корана. Обучал последующее поколение мусульман; среди его учеников были Муджахид и Икрима. Его толкования широко представлены в литературе тафсира.',
'A cousin of Prophet Muhammad ﷺ, transmitter of hadith and a prominent early Quran commentator. He taught the following generation of Muslims; Mujahid and Ikrima were among his pupils. His interpretations are widely represented in tafsir literature.',
'Мухаммад пайгамбардын ﷺ аталаш тууганы, хадис риваятчысы жана Курандын белгилүү алгачкы тафсирчилеринин бири. Кийинки муунга сабак берген; шакирттеринин арасында Мужахид менен Икрима болгон. Анын түшүндүрмөлөрү тафсир адабиятында кеңири кездешет.'],
['Абдуллах ибн Умар','Abdullah b. Ömer b. Hattâb',
'Сын Умара ибн аль-Хаттаба, сподвижник и один из известных передатчиков хадисов. Большую часть научной деятельности вёл в Медине, отвечая на правовые вопросы. Известен внимательным следованием практике Пророка ﷺ; среди его учеников был Нафи.',
'The son of Umar ibn al-Khattab, a companion and prominent hadith transmitter. He carried out much of his scholarly work in Medina, answering legal questions. Known for closely following the Prophet’s ﷺ practice, he taught pupils including Nafi.',
'Умар ибн аль-Хаттабдын уулу, сахаба жана белгилүү хадис риваятчысы. Илимий ишинин көбүн Мединада жүргүзүп, укуктук суроолорго жооп берген. Пайгамбардын ﷺ амалдарын кылдат карманганы менен белгилүү; Нафи анын шакирти болгон.'],
['Муавия ибн Абу Суфьян','Muâviye b. Ebû Süfyân',
'Сподвижник, наместник аш-Шама и основатель Омейядского халифата. После соглашения с аль-Хасаном в 661 году установил власть с центром в Дамаске. Его правление связано с укреплением сирийского управления, развитием флота и переходом к наследственной передаче власти.',
'A companion, governor of al-Sham and founder of the Umayyad caliphate. After an agreement with al-Hasan in 661, he established rule centred on Damascus. His reign is associated with stronger Syrian administration, naval development and hereditary succession.',
'Сахаба, аш-Шамдын башкаруучусу жана Омейяд халифатынын негиздөөчүсү. 661-жылы аль-Хасан менен келишимден кийин Дамаскты борбор кылып бийлик орноткон. Анын башкаруусу Сириядагы башкаруунун, флоттун өнүгүшү жана бийликтин мурас аркылуу өтүшү менен байланыштуу.'],
['Саад ибн Абу Ваккас','Sa‘d b. Ebû Vakkās',
'Один из ранних мусульман и военачальников поколения сподвижников. Командовал мусульманскими войсками в сражении при аль-Кадисии против Персии Сасанидов. Участвовал в основании Куфы и был её наместником.',
'An early Muslim and commander from the generation of the companions. He led Muslim forces at al-Qadisiyya against Sasanian Persia. He helped establish Kufa and served as its governor.',
'Алгачкы мусулмандардын бири жана сахабалар муунунун кол башчысы. Сасанид Персиясына каршы аль-Кадисия салгылашында мусулман кошуундарын башкарган. Куфанын түптөлүшүнө катышып, анын башкаруучусу болгон.'],
['аль-Хасан аль-Басри','Hasan-ı Basrî',
'Учёный и проповедник поколения табиинов, родившийся в Медине и известный деятельностью в Басре. Передавал хадисы, занимался толкованием Корана и правовыми вопросами. Его наставления о нравственности, ответственности и умеренности повлияли на последующую духовную литературу.',
'A scholar and preacher of the Successors’ generation, born in Medina and known for his work in Basra. He transmitted hadith and addressed Quranic interpretation and law. His teachings on ethics, responsibility and restraint influenced later spiritual literature.',
'Мединада туулуп, Басрада ишмердиги менен белгилүү болгон табийин аалым жана насаатчы. Хадистерди риваят кылып, Куран тафсири жана укук маселелери менен алектенген. Адеп, жоопкерчилик жана токтоолук тууралуу насааттары кийинки руханий адабиятка таасир берген.'],
['Ибн Сирин','İbn Sîrîn',
'Мухаммад ибн Сирин — басрийский учёный поколения табиинов, передатчик хадисов и знаток права. Занимался также торговлей. Известен в традиции толкования сновидений, однако поздние книги, выпущенные под его именем, нельзя безусловно считать его собственными сочинениями.',
'Muhammad ibn Sirin was a Basran scholar of the Successors’ generation, hadith transmitter and jurist who also engaged in trade. He is remembered for dream interpretation, although later books issued under his name cannot automatically be treated as his own works.',
'Мухаммад ибн Сирин — басралык табийин аалым, хадис риваятчысы жана факих; соода менен да алектенген. Түш жоруу салтында белгилүү. Бирок кийин анын аты менен чыккан китептердин баарын өзүнүн чыгармасы деп эсептөөгө болбойт.'],
['Ата ибн Аби Рабах','Atâ b. Ebû Rebâh',
'Мекканский факих, толкователь Корана и передатчик хадисов из поколения табиинов. Учился у сподвижников, включая Ибн Аббаса. Долгое время отвечал на религиозные вопросы в Мекке, особенно о паломничестве.',
'A Meccan jurist, Quran commentator and hadith transmitter of the Successors’ generation. He studied with companions including Ibn Abbas. He answered religious questions in Mecca for many years, particularly on pilgrimage.',
'Меккелик табийин факих, Куран тафсирчиси жана хадис риваятчысы. Ибн Аббас баш болгон сахабалардан билим алган. Меккеде көп жыл диний суроолорго, өзгөчө ажылык тууралуу суроолорго жооп берген.'],
['Икрима, мауля Ибн Аббаса','İkrime el-Berberî',
'Учёный поколения табиинов, ученик и вольноотпущенник Ибн Аббаса. Особенно известен передачей его толкований Корана. Путешествовал, преподавая и передавая знания; его сообщения вошли в раннюю литературу хадисов и тафсира.',
'A scholar of the Successors’ generation, pupil and freedman of Ibn Abbas. He is particularly known for transmitting Ibn Abbas’s Quranic interpretations. He travelled to teach and transmit knowledge; his reports entered early hadith and tafsir literature.',
'Табийин аалым, Ибн Аббастын шакирти жана эркиндикке чыгарылган кулу. Айрыкча анын Куран түшүндүрмөлөрүн жеткиргени менен белгилүү. Сапарларда сабак берип, билим тараткан; риваяттары алгачкы хадис жана тафсир адабиятына кирген.'],
['Муджахид ибн Джабр','Mücâhid b. Cebr',
'Мекканский толкователь Корана из поколения табиинов и ученик Ибн Аббаса. После учителя продолжил преподавание тафсира в Мекке. Его объяснения аятов использовали последующие толкователи; дошедший под его именем тафсир связан с передачей учеников.',
'A Meccan Quran commentator of the Successors’ generation and pupil of Ibn Abbas. He continued teaching tafsir in Mecca after his teacher. Later commentators used his explanations of verses; the tafsir preserved under his name is associated with his pupils’ transmission.',
'Меккелик табийин тафсирчи жана Ибн Аббастын шакирти. Устатынан кийин Меккеде тафсир окутууну уланткан. Аяттарга берген түшүндүрмөлөрүн кийинки тафсирчилер колдонгон; аты менен жеткен тафсир шакирттеринин риваяттарына байланыштуу.'],
['Катада ибн Диама','Katâde b. Diâme',
'Басрийский учёный поколения табиинов, знаток тафсира, хадисов и арабского языка. Учился у аль-Хасана аль-Басри и передавал хадисы Анаса ибн Малика. Его толкования и сообщения сохранились в трудах последующих собирателей.',
'A Basran scholar of the Successors’ generation, versed in tafsir, hadith and Arabic. He studied with al-Hasan al-Basri and transmitted hadith from Anas ibn Malik. His interpretations and reports survive in the works of later collectors.',
'Басралык табийин аалым, тафсир, хадис жана араб тилинин билгичи. Аль-Хасан аль-Басриден окуп, Анас ибн Маликтен хадис риваят кылган. Түшүндүрмөлөрү менен кабарлары кийинки жыйноочулардын эмгектеринде сакталган.'],
['Аз-Зухри','Zührî',
'Мухаммад ибн Шихаб аз-Зухри — мединский учёный поколения табиинов, позднее работавший и в аш-Шаме. Один из важных участников раннего собирания и записи хадисов. Был учителем Малика ибн Анаса и других передатчиков следующего поколения.',
'Muhammad ibn Shihab al-Zuhri was a Medinan scholar of the Successors’ generation who later also worked in al-Sham. He played an important part in early hadith collection and recording. Malik ibn Anas and other transmitters of the next generation studied with him.',
'Мухаммад ибн Шихаб аз-Зухри — мединалык табийин аалым, кийин аш-Шамда да иштеген. Хадистерди алгачкы чогултуу жана жазууга катышкан маанилүү аалымдардын бири. Малик ибн Анас жана кийинки муундагы башка риваятчылар андан окуган.'],
['Таус ибн Кайсан','Tâvûs b. Keysân',
'Учёный поколения табиинов, связанный с Йеменом и Меккой. Учился у Ибн Аббаса и других сподвижников, передавал хадисы и давал правовые заключения. Известен также наставлениями о нравственности и независимым отношением к правителям.',
'A scholar of the Successors’ generation associated with Yemen and Mecca. He studied with Ibn Abbas and other companions, transmitted hadith and gave legal opinions. He is also remembered for ethical counsel and independence towards rulers.',
'Йемен жана Мекке менен байланышкан табийин аалым. Ибн Аббастан жана башка сахабалардан окуп, хадис риваят кылган жана укуктук пикирлерди берген. Адептик насааттары жана башкаруучуларга көз карандысыз мамилеси менен да эскерилет.'],
['Абу Ханифа','Ebû Hanîfe',
'Ан-Нуман ибн Сабит — куфийский правовед, чьё учение стало основой ханафитского мазхаба. Обсуждал правовые вопросы с кругом учеников, среди которых были Абу Юсуф и Мухаммад аш-Шайбани. Его школа оказала большое влияние на право Центральной Азии и многих других регионов.',
'Al-Numan ibn Thabit was a Kufan jurist whose teaching became the basis of the Hanafi school. He discussed legal questions with pupils including Abu Yusuf and Muhammad al-Shaybani. His school profoundly influenced law in Central Asia and many other regions.',
'Ан-Нуман ибн Сабит — окуусу ханафий мазхабынын негизин түзгөн куфалык факих. Абу Юсуф жана Мухаммад аш-Шайбани сыяктуу шакирттери менен укук маселелерин талкуулаган. Анын мектеби Борбордук Азиянын жана башка көп аймактардын укугуна чоң таасир берген.'],
['Малик ибн Анас','Mâlik b. Enes',
'Мединский правовед и хадисовед, с именем которого связан маликитский мазхаб. Автор «Аль-Муватта» — раннего собрания хадисов и правовых сообщений. В правовых рассуждениях придавал важное значение практике учёных и жителей Медины.',
'A Medinan jurist and hadith scholar associated with the Maliki school. He authored Al-Muwatta, an early collection of hadith and legal reports. His legal reasoning gave an important place to the practice of Medina’s scholars and inhabitants.',
'Маликиттик мазхаб менен аты байланышкан мединалык факих жана хадис аалымы. Хадистер менен укуктук кабарлардын алгачкы жыйнагы «Аль-Муваттанын» автору. Укуктук ой жүгүртүүдө Мединанын аалымдарынын жана тургундарынын амалдарына маани берген.'],
['Суфьян ас-Саури','Süfyân es-Sevrî',
'Хадисовед и правовед, чья научная деятельность связана прежде всего с Куфой. Был признанным передатчиком хадисов и основателем правовой школы, впоследствии не сохранившейся как отдельный мазхаб. Известен аскетическим образом жизни и отказом от близости к власти.',
'A hadith scholar and jurist associated chiefly with Kufa. He was a respected transmitter and founded a legal school that did not survive as a separate madhhab. He is known for an ascetic way of life and distance from political power.',
'Илимий иши негизинен Куфе менен байланышкан хадис аалымы жана факих. Таанылган риваятчы болуп, кийин өзүнчө мазхаб катары сакталбай калган укуктук мектепти негиздеген. Зухду жана бийликтен оолак турганы менен белгилүү.'],
['аль-Аузаи','Evzâî',
'Абд ар-Рахман аль-Аузаи — правовед и хадисовед аш-Шама. Родился в Баальбеке, работал в Дамаске и Бейруте. Его правовая школа была распространена в аш-Шаме и некоторое время в аль-Андалусе, прежде чем уступить место другим школам.',
'Abd al-Rahman al-Awzai was a jurist and hadith scholar of al-Sham. Born in Baalbek, he worked in Damascus and Beirut. His legal school spread in al-Sham and for a time in al-Andalus before giving way to other schools.',
'Абд ар-Рахман аль-Аузаи — аш-Шамдын факихи жана хадис аалымы. Баальбекте туулуп, Дамаск менен Бейрутта иштеген. Анын укуктук мектеби аш-Шамда жана бир мезгил аль-Андалуста жайылып, кийин башка мектептерге орун берген.'],
['Лейс ибн Саад','Leys b. Sa‘d',
'Египетский правовед и хадисовед, один из крупнейших учёных своего времени. Поддерживал научную переписку с Маликом ибн Анасом и вырабатывал самостоятельные правовые суждения. Его взгляды сохранились в сочинениях других авторов, хотя отдельная школа не закрепилась.',
'An Egyptian jurist and hadith scholar, among the leading scholars of his time. He corresponded with Malik ibn Anas and formed independent legal judgements. His views survive in other authors’ works, although his teaching did not endure as a separate school.',
'Мисирлик факих жана хадис аалымы, өз доорунун алдыңкы окумуштууларынын бири. Малик ибн Анас менен илимий кат алышып, өз алдынча укуктук пикирлерди чыгарган. Өзүнчө мектеп болуп сакталбаса да, көз караштары башка авторлордун эмгектеринде калган.'],
['Абдуллах ибн аль-Мубарак','Abdullah b. Mübârek',
'Уроженец Мерва, хадисовед, правовед и автор сочинений о нравственности и зухде. Совершал многочисленные поездки за знаниями в Хорасан, Ирак и Хиджаз. Занимался торговлей и помогал учёным и ученикам; известен сборником «Китаб аз-зухд».',
'A native of Merv, hadith scholar, jurist and author on ethics and asceticism. He travelled extensively for learning in Khurasan, Iraq and the Hijaz. He engaged in trade and supported scholars and students; his works include Kitab al-Zuhd.',
'Мервден чыккан хадис аалымы, факих жана адеп, зухд тууралуу эмгектердин автору. Билим издеп Хорасанга, Иракка жана Хижазга көп сапар жасаган. Соода кылып, аалымдарга жана шакирттерге жардам берген; «Китаб аз-зухд» менен белгилүү.'],
['Суфьян ибн Уяйна','Süfyân b. Uyeyne',
'Хадисовед, родившийся в Куфе и преподававший в Мекке. Передавал знания аз-Зухри и других учёных раннего поколения. Среди его учеников были аш-Шафии и Ахмад ибн Ханбаль; его сообщения широко представлены в хадисных сборниках.',
'A hadith scholar born in Kufa who taught in Mecca. He transmitted the learning of al-Zuhri and other early scholars. His pupils included al-Shafii and Ahmad ibn Hanbal, and his reports are widely represented in hadith collections.',
'Куфеде туулуп, Меккеде сабак берген хадис аалымы. Аз-Зухринин жана башка алгачкы аалымдардын билимин жеткирген. Аш-Шафии менен Ахмад ибн Ханбал андан окуган; анын риваяттары хадис жыйнактарында кеңири кездешет.'],
['аш-Шафии','Şâfiî',
'Мухаммад ибн Идрис аш-Шафии — правовед, с именем которого связан шафиитский мазхаб. Учился в Мекке и у Малика в Медине, позднее работал в Ираке и Египте. Его «Ар-Рисаля» занимает важное место в развитии учения об основах исламского права.',
'Muhammad ibn Idris al-Shafii was the jurist associated with the Shafii school. He studied in Mecca and with Malik in Medina, later working in Iraq and Egypt. His Al-Risala holds an important place in the development of Islamic legal theory.',
'Мухаммад ибн Идрис аш-Шафии — шафииттик мазхаб менен аты байланышкан факих. Меккеде жана Мединада Маликтен окуп, кийин Ирак менен Мисирде иштеген. «Ар-Рисалясы» ислам укугунун негиздери жөнүндөгү илимдин өнүгүшүндө маанилүү орунда.'],
['Ахмад ибн Ханбаль','Ahmed b. Hanbel',
'Багдадский хадисовед и правовед, с именем которого связан ханбалитский мазхаб. Собрал большой корпус преданий, известный как «Муснад». Во время михны подвергался преследованию за отказ принять навязываемое властями учение о сотворённости Корана.',
'A Baghdad hadith scholar and jurist associated with the Hanbali school. He assembled a large body of reports known as the Musnad. During the mihna he was persecuted for refusing the authorities’ imposed doctrine that the Quran was created.',
'Ханбалий мазхабы менен аты байланышкан багдаддык хадис аалымы жана факих. «Муснад» деп белгилүү чоң риваяттар жыйнагын түзгөн. Михна учурунда бийлик таңуулаган Курандын жаратылгандыгы жөнүндөгү пикирди кабыл албаганы үчүн куугунтукталган.'],
['аль-Бухари','Buhârî, Muhammed b. İsmâil',
'Мухаммад ибн Исмаил аль-Бухари — хадисовед из Бухары. Путешествовал по главным научным центрам мусульманского мира, изучая предания и их передатчиков. Составил «Аль-Джами ас-сахих», известный как «Сахих аль-Бухари», и биографический труд «Ат-Тарих аль-кабир».',
'Muhammad ibn Ismail al-Bukhari was a hadith scholar from Bukhara. He travelled through major Muslim centres of learning to study reports and their transmitters. He compiled Al-Jami al-Sahih, known as Sahih al-Bukhari, and the biographical work Al-Tarikh al-Kabir.',
'Мухаммад ибн Исмаил аль-Бухари — Бухарадан чыккан хадис аалымы. Риваяттарды жана алардын риваятчыларын изилдеп, мусулман дүйнөсүнүн негизги илимий борборлоруна барган. «Сахих аль-Бухари» деп белгилүү «Аль-Жами ас-сахихти» жана «Ат-Тарих аль-кабир» өмүр баяндык эмгегин түзгөн.'],
['Муслим ибн аль-Хаджжадж','Müslim b. Haccâc',
'Хадисовед из Нишапура, ученик и современник ведущих собирателей хадисов IX века. Составил «Сахих Муслим», один из двух наиболее авторитетных суннитских сборников достоверных хадисов. В его труде варианты одного сообщения и цепочки передачи часто собраны вместе.',
'A hadith scholar from Nishapur and a pupil and contemporary of leading ninth-century collectors. He compiled Sahih Muslim, one of the two most authoritative Sunni collections of authentic hadith. His work often groups a report’s variants and transmission chains together.',
'Нишапурдан чыккан хадис аалымы, IX кылымдын алдыңкы хадис жыйноочуларынын шакирти жана замандашы. Сунний салтындагы эң беделдүү эки сахих жыйнактын бири «Сахих Муслимди» түзгөн. Эмгегинде бир кабардын варианттары жана иснаддары көбүнчө чогуу берилет.'],
['Абу Дауд','Ebû Dâvûd es-Sicistânî',
'Сулайман ибн аль-Ашас ас-Сиджистани — хадисовед, происходивший из Сиджистана и позднее живший в Басре. Собирал предания во время научных поездок. Его «Сунан» преимущественно посвящён хадисам, используемым при рассмотрении правовых вопросов.',
'Sulayman ibn al-Ashath al-Sijistani was a hadith scholar from Sijistan who later lived in Basra. He collected reports during scholarly journeys. His Sunan is chiefly concerned with hadith used in addressing legal questions.',
'Сулайман ибн аль-Ашас ас-Сижистани — Сижистандан чыгып, кийин Басрада жашаган хадис аалымы. Илимий сапарларында риваяттарды чогулткан. «Сунаны» негизинен укуктук маселелерде колдонулган хадистерге арналган.'],
['ат-Тирмизи','Tirmizî',
'Абу Иса ат-Тирмизи — хадисовед из области Термеза. Учился у аль-Бухари и других собирателей хадисов. Его «Аль-Джами» соединяет предания с оценками передачи и сведениями о мнениях правоведов; «Аш-Шамаиль» посвящён облику и нравам Пророка ﷺ.',
'Abu Isa al-Tirmidhi was a hadith scholar from the Termez region. He studied with al-Bukhari and other collectors. His Al-Jami combines reports with transmission assessments and jurists’ views; Al-Shamail concerns the Prophet’s ﷺ appearance and character.',
'Абу Иса ат-Тирмизи — Термез аймагынан чыккан хадис аалымы. Аль-Бухариден жана башка жыйноочулардан окуган. «Аль-Жами» риваяттарды алардын баасы жана факихтердин пикирлери менен берет; «Аш-Шамаиль» Пайгамбардын ﷺ келбетине жана мүнөзүнө арналган.'],
['ан-Насаи','Nesâî',
'Ахмад ибн Шуайб ан-Насаи — хадисовед из Нисы в Хорасане, много лет преподававший в Египте. Изучал передатчиков и собирал правовые хадисы. Его «Ас-Сунан ас-сугра», также известный как «Аль-Муджтаба», входит в шесть основных суннитских сборников хадисов.',
'Ahmad ibn Shuayb al-Nasai was a hadith scholar from Nasa in Khurasan who taught in Egypt for many years. He studied transmitters and collected legal hadith. His Al-Sunan al-Sughra, also known as Al-Mujtaba, is one of the six principal Sunni hadith collections.',
'Ахмад ибн Шуайб ан-Насаи — Хорасандагы Нисадан чыккан, Мисирде көп жыл сабак берген хадис аалымы. Риваятчыларды изилдеп, укуктук хадистерди чогулткан. «Аль-Мужтаба» деп да белгилүү «Ас-Сунан ас-суграсы» алты негизги сунний хадис жыйнагына кирет.'],
['ат-Табари','Taberî, Muhammed b. Cerîr',
'Мухаммад ибн Джарир ат-Табари — историк, толкователь Корана и правовед из Табаристана, работавший в Багдаде. Автор тафсира «Джами аль-баян» и исторического свода «Тарих ар-русул ва-ль-мулюк». В историческом труде сохранил многочисленные сообщения с указанием цепочек передачи.',
'Muhammad ibn Jarir al-Tabari was a historian, Quran commentator and jurist from Tabaristan who worked in Baghdad. He authored the tafsir Jami al-Bayan and the chronicle Tarikh al-Rusul wa-l-Muluk. The chronicle preserves many reports with their transmission chains.',
'Мухаммад ибн Жарир ат-Табари — Табаристандан чыккан, Багдадда иштеген тарыхчы, тафсирчи жана факих. «Жами аль-баян» тафсиринин жана «Тарих ар-русул ва-ль-мулюк» тарыхый жыйнагынын автору. Тарыхый эмгегинде көп кабарларды иснаддары менен сактаган.'],
['ат-Тахави','Tahâvî',
'Египетский ханафитский правовед и хадисовед. В «Шарх маани аль-асар» сопоставлял предания, связанные с правовыми вопросами. Известен также кратким изложением вероучения, получившим название «Аль-Акида ат-Тахавийя».',
'An Egyptian Hanafi jurist and hadith scholar. In Sharh Maani al-Athar he compared reports relevant to legal questions. He is also known for a concise statement of belief commonly called Al-Aqida al-Tahawiyya.',
'Мисирлик ханафий факих жана хадис аалымы. «Шарх маани аль-асарда» укуктук маселелерге байланыштуу риваяттарды салыштырган. «Аль-Акида ат-Тахавийя» деген ат алган ишенимдин кыскача баяны менен да белгилүү.'],
['Ибн Абд аль-Барр','İbn Abdülber en-Nemerî',
'Андалусский хадисовед и маликитский правовед, родившийся в Кордове. Известен комментариями к «Аль-Муватта» — «Ат-Тамхид» и «Аль-Истизкар». Составил также «Аль-Истиаб», биографический труд о сподвижниках Пророка ﷺ.',
'An Andalusian hadith scholar and Maliki jurist born in Cordoba. He is known for Al-Tamhid and Al-Istidhkar, commentaries on Al-Muwatta. He also compiled Al-Istiab, a biographical work on the Prophet’s ﷺ companions.',
'Кордова шаарында туулган андалусиялык хадис аалымы жана маликит факих. «Аль-Муваттанын» «Ат-Тамхид» жана «Аль-Истизкар» түшүндүрмөлөрү менен белгилүү. Пайгамбардын ﷺ сахабалары тууралуу «Аль-Истиаб» өмүр баяндык эмгегин да түзгөн.'],
['аль-Багави','Begavî, Ferrâ',
'Аль-Хусайн аль-Багави — шафиитский правовед, хадисовед и толкователь Корана из Хорасана. Автор «Маалим ат-танзиль», «Шарх ас-сунна» и «Масабих ас-сунна». Его труды связывают толкование Корана с хадисами и объяснениями ранних учёных.',
'Al-Husayn al-Baghawi was a Shafii jurist, hadith scholar and Quran commentator from Khurasan. He authored Maalim al-Tanzil, Sharh al-Sunna and Masabih al-Sunna. His works connect Quranic interpretation with hadith and explanations by early scholars.',
'Аль-Хусайн аль-Багави — Хорасандан чыккан шафиит факих, хадис аалымы жана тафсирчи. «Маалим ат-танзиль», «Шарх ас-сунна» жана «Масабих ас-суннанын» автору. Эмгектери Куран тафсирин хадистер жана алгачкы аалымдардын түшүндүрмөлөрү менен байланыштырат.'],
['Абдуль-Кадир аль-Джиляни','Abdülkādir-i Geylânî',
'Ханбалитский правовед, проповедник и духовный наставник, происходивший из Гиляна и работавший в Багдаде. Преподавал и обращался к широкой аудитории с нравственными наставлениями. С его именем связано формирование кадирийской духовной традиции.',
'A Hanbali jurist, preacher and spiritual teacher from Gilan who worked in Baghdad. He taught students and offered ethical counsel to a broad audience. The development of the Qadiri spiritual tradition is associated with his name.',
'Гиландан чыгып, Багдадда иштеген ханбалий факих, насаатчы жана руханий устат. Шакирттерге сабак берип, кеңири жамаатка адептик насаат айткан. Кадирий руханий салтынын калыптанышы анын аты менен байланыштуу.'],
['Ибн Асакир','İbn Asâkir, Ebü’l-Kāsım',
'Дамасский хадисовед и историк, совершавший многочисленные поездки за знаниями. Его главный труд «Тарих Димашк» объединяет историю города с обширными биографиями людей, связанных с Дамаском. Преподавал хадисы в Дамаске при Нур ад-Дине.',
'A Damascus hadith scholar and historian who travelled extensively for learning. His principal work, Tarikh Dimashq, combines the city’s history with extensive biographies of people connected to it. He taught hadith in Damascus under Nur al-Din.',
'Билим издеп көп сапар жасаган дамасктык хадис аалымы жана тарыхчы. Негизги эмгеги «Тарих Димашк» шаардын тарыхын ага байланышкан адамдардын кеңири өмүр баяндары менен бириктирет. Нур ад-Диндин тушунда Дамаскта хадис окуткан.'],
['ан-Навави','Nevevî',
'Яхья ан-Навави — шафиитский правовед и хадисовед из Навы, учившийся и преподававший в Дамаске. Составил «Рияд ас-салихин» и знаменитые «Сорок хадисов». Написал комментарий к «Сахиху Муслима» и важные труды по шафиитскому праву.',
'Yahya al-Nawawi was a Shafii jurist and hadith scholar from Nawa who studied and taught in Damascus. He compiled Riyad al-Salihin and the celebrated Forty Hadith. He wrote a commentary on Sahih Muslim and important works of Shafii law.',
'Яхья ан-Навави — Навадан чыккан, Дамаскта окуп, сабак берген шафиит факих жана хадис аалымы. «Рияд ас-салихинди» жана белгилүү «Кырк хадисти» түзгөн. «Сахих Муслимге» түшүндүрмө жана шафиит укугу боюнча маанилүү эмгектерди жазган.'],
['Ибн Таймия','İbn Teymiyye, Takıyyüddin',
'Ахмад ибн Таймия — ханбалитский правовед и богослов, родившийся в Харране и выросший в Дамаске. Писал о вероучении, толковании Корана и праве, участвовал в научных спорах своего времени. Его труды оказали большое влияние на последующие исламские движения и дискуссии.',
'Ahmad ibn Taymiyya was a Hanbali jurist and theologian born in Harran and raised in Damascus. He wrote on belief, Quranic interpretation and law and took part in the scholarly debates of his time. His works strongly influenced later Islamic movements and discussions.',
'Ахмад ибн Таймия — Харранда туулуп, Дамаскта өскөн ханбалий факих жана акыйда аалымы. Ишеним, Куран тафсири жана укук жөнүндө жазып, өз доорунун илимий талкууларына катышкан. Эмгектери кийинки ислам кыймылдарына жана талкууларына чоң таасир берген.'],
['Ибн Кудама аль-Макдиси','İbn Kudâme, Muvaffakuddin',
'Ханбалитский правовед из Палестины, чья семья переселилась в Дамаск. Учился также в Багдаде и стал одним из главных представителей ханбалитской школы. Его «Аль-Мугни» рассматривает правовые вопросы с сопоставлением мнений различных учёных.',
'A Hanbali jurist from Palestine whose family moved to Damascus. He also studied in Baghdad and became a leading representative of the Hanbali school. His Al-Mughni examines legal questions by comparing the opinions of different scholars.',
'Үй-бүлөсү Дамаскка көчкөн палестиналык ханбалий факих. Багдадда да окуп, ханбалий мектебинин негизги өкүлдөрүнүн бири болгон. «Аль-Мугниде» укуктук маселелер ар түрдүү аалымдардын пикирлерин салыштыруу менен каралат.'],
['Ибн аль-Джаузи','İbnü’l-Cevzî, Ebü’l-Ferec',
'Багдадский ханбалитский учёный, проповедник и историк. Писал о толковании Корана, хадисах, нравственности и истории; среди трудов — «Зад аль-масир» и «Аль-Мунтазам». Его следует отличать от Ибн Каййима аль-Джаузийи, жившего позднее.',
'A Baghdad Hanbali scholar, preacher and historian. He wrote on Quranic interpretation, hadith, ethics and history; his works include Zad al-Masir and Al-Muntazam. He should be distinguished from Ibn Qayyim al-Jawziyya, who lived later.',
'Багдаддык ханбалий аалым, насаатчы жана тарыхчы. Куран тафсири, хадис, адеп жана тарых боюнча жазган; эмгектеринин арасында «Зад аль-масир» жана «Аль-Мунтазам» бар. Аны кийин жашаган Ибн Каййим аль-Жаузийядан айырмалоо керек.'],
['аль-Мунзири','Münzirî',
'Египетский хадисовед и шафиитский учёный, родившийся в Фустате. Преподавал в Каире и изучал хадисы во время поездок по научным центрам. Его «Ат-Таргиб ва-т-тархиб» собирает сообщения о добрых делах и предостережениях от дурных поступков.',
'An Egyptian hadith scholar and Shafii scholar born in Fustat. He taught in Cairo and studied hadith on journeys to centres of learning. His Al-Targhib wa-l-Tarhib collects reports encouraging good deeds and warning against wrongdoing.',
'Фустатта туулган мисирлик хадис аалымы жана шафиит. Каирде сабак берип, илимий борборлорго сапарларда хадис үйрөнгөн. «Ат-Таргиб ва-т-тархиб» жакшы иштерге үндөгөн жана жаман иштерден эскерткен кабарларды чогултат.'],
['Ибн Дакык аль-Ид','İbn Dakīkul‘îd',
'Египетский правовед и хадисовед, получивший образование в маликитской и шафиитской традициях. Преподавал в Кусе и Каире, позднее занимал должность главного шафиитского судьи Египта. Известен подробным разбором правовых хадисов в «Ихкам аль-ахкам».',
'An Egyptian jurist and hadith scholar educated in both Maliki and Shafii traditions. He taught in Qus and Cairo and later became Egypt’s chief Shafii judge. He is known for detailed analysis of legal hadith in Ihkam al-Ahkam.',
'Маликиттик жана шафииттик салттарда билим алган мисирлик факих жана хадис аалымы. Кус менен Каирде сабак берип, кийин Мисирдин башкы шафиит казылыгын аткарган. «Ихкам аль-ахкамда» укуктук хадистерди кылдат талдаганы менен белгилүү.'],
['аз-Захаби','Zehebî',
'Шамс ад-Дин аз-Захаби — дамасский хадисовед, историк и биограф. Изучал жизнь передатчиков и оценку хадисных сообщений. Его «Сияр алям ан-нубаля» и «Тарих аль-ислам» содержат большой материал об учёных, правителях и других деятелях мусульманской истории.',
'Shams al-Din al-Dhahabi was a Damascus hadith scholar, historian and biographer. He studied transmitters’ lives and the assessment of hadith reports. His Siyar Alam al-Nubala and Tarikh al-Islam preserve extensive material on scholars, rulers and other figures in Muslim history.',
'Шамс ад-Дин аз-Захаби — дамасктык хадис аалымы, тарыхчы жана өмүр баянчы. Риваятчылардын өмүрүн жана хадистердин бааланышын изилдеген. «Сияр алям ан-нубаля» менен «Тарих аль-ислам» мусулман тарыхындагы аалымдар, башкаруучулар жана башка ишмерлер тууралуу кеңири маалымат берет.']
];
